### ISSUE TITLE
Нельзя указать переменные окружения для процесса отладки

### ISSUE THREAD

**Issue by yukon39** [EvilBeaver/OneScript#1004]
**Проблема**
При запуске отладки в лаунчере нельзя указать значения переменных окружения для запускаемого процесса.

**Предлагаемое решение**
В настройка лаунчера необходимо реализовать дополнительный раздел `env`, вида:
```
env: {
    "ENV_KEY1" : "value1",
    "ENV_KEY2" : "value2"
}
```
При запуске процесса лаунчер должен установить переменные окружения `ENV_KEY1` и `ENV_KEY2` значениями "value1" и "value2" соответственно.

**Comment by EvilBeaver** [comment]
Принято
