### ISSUE TITLE
Отладчик 0.6 зависание при исключении в oscript

### ISSUE THREAD

**Issue by dvakor** [EvilBeaver/OneScript#1005]
**Опишите ошибку**
При использовании отладчика, в момент выброса исключения в oscript.exe зависает отладка VS code пока не нажмешь "Стоп"

**Воспроизведение ошибки**
Точно можно воспроизвести на коммите: 6ce7a34d4a26c8bb015f6848b477a1d2061e8d60

Запустить отладку на коде
```
connector = Новый COMОбъект("V83.COMConnector");
Сообщить(1);
Сообщить(2);
```
Поставив точку на `Сообщить(1)`

Попробывать перейти дальше по коду, или посмотреть на вотчер, у которого будет вечный индикатор загрузки

**Ожидаемое поведение**
VS code должен получить ответ. И выдать сообщение об ошибке

**Окружение**
 - ОС: Win 10
 - Версия: oscript 1.4 \ debug adapter 0.6

**Comment by arkuznetsov** [comment]
@ArchLord42RU У меня сразу виснет вот на таком коде:
```bsl
#Использовать irac

АгентКластера = Новый УправлениеКластером1С();

Кластеры = АгентКластера.Кластеры();

Кластер = Кластеры.Список()[0];

ИБ = Кластер.ИнформационныеБазы();

ПараметрыБазы = Новый Структура();

ПараметрыБазы.Вставить("АдресСервераСУБД", "localhost");
ПараметрыБазы.Вставить("ТипСУБД", Перечисления.ТипыСУБД.MSSQLServer);
ПараметрыБазы.Вставить("ИмяБазыСУБД", "tst001");
ПараметрыБазы.Вставить("ИмяПользователяБазыСУБД", "usr");
ПараметрыБазы.Вставить("ПарольПользователяБазыСУБД", "psw");
ПараметрыБазы.Вставить("БлокировкаРегламентныхЗаданийВключена", Перечисления.СостоянияВыключателя.Включено);

Попытка
	ИБ.Добавить("tst001",,Истина,ПараметрыБазы);
	ИБ.Удалить("tst001", Перечисления.ДействияСБазойСУБДПриУдалении.Удалить);
Исключение
	ВызватьИсключение ОписаниеОшибки();
КонецПопытки;
```
Выводит:
```
Unknown protocol. Using default
```
И даже до первой строки с точкой останова не доходит.

ОС: Win 10
oscript 1.4.0.161 \ debug adapter 0.6

**Comment by EvilBeaver** [comment]
@arkuznetsov попробуй пожалуйста сборку 162 или 163. И vsix обновить

**Comment by arkuznetsov** [comment]
@EvilBeaver Пока собирался уже 164 :-)
Oscript и дебагер обновил, поробовал, пока результат не изменился.
Может у меня еще что-то не так, подскажите что включить, чтобы было больше информации.

**Comment by EvilBeaver** [comment]
@arkuznetsov проверил на твоем коде - работает. Убедись, что точно все обновил, пожалуйста. Может расширение отладчика удалить и снова поставить свежее?

**Comment by arkuznetsov** [comment]
@EvilBeaver Что-то мы не учитываем.  Откатился до oscript 1.3 / debugger 0.5 - отладка работает. Установил oscript 1.4.0.165 / debugger 0.6 - опять та же фигня, виснет и в консоли отладки пишет:
```
Unknown protocol. Using default
```

**Comment by dvakor** [comment]
> @EvilBeaver Что-то мы не учитываем. Откатился до oscript 1.3 / debugger 0.5 - отладка работает. Установил oscript 1.4.0.165 / debugger 0.6 - опять та же фигня, виснет и в консоли отладки пишет:
> 
> ```
> Unknown protocol. Using default
> ```

Думаю начать стоит с launch.json, скинь плз

**Comment by arkuznetsov** [comment]
@EvilBeaver решилось:
	стояло "protocol" : "internal"
	поставил "protocol" : "tcp"

Видимо надо где-то про это указать, для тех у кого launch.json был создан ранее.

Спасибо за подсказку!

**Comment by EvilBeaver** [comment]
Это все-таки ошибка, т.к. при указании чего-либо неизвестного должен был включаться tcp-протокол, а не висеть.
