### ISSUE TITLE
Публикация в winget

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#1012]
Добавить OneScript в грядущее светило пакетных менеджеров - winget.

**Comment by zeegin** [comment]
https://github.com/microsoft/winget-pkgs
В текущей актуальной версии Windows winget уже доступен.

**Comment by dmpas** [comment]
у меня пока затык в том, что winget из коробки не воспринимает letsencrypt-овские сертификаты.

**Comment by nixel2007** [comment]
Шёл 2020ый год...

**Comment by dmpas** [comment]
`winget install OneScript`
`winget install --silent OneScript`
