### ISSUE TITLE
Ошибка в тесте при использовании moskito

### ISSUE THREAD

**Issue by Dezmont51** [EvilBeaver/OneScript#1016]
**Опишите ошибку**
При запуске test.os  c аргументом codestat=1.json возникает ошибка 
Тесты падает если один из тестов использует moskito и у опции или команды несколько вариантов написания
Например: КомандаПриложения.Опция("s ss", "", "")
```
ОШИБКА: Есть непрошедшие тесты. Красная полоса
System.Collections.Generic.KeyNotFoundException: Данный ключ отсутствует в словаре.
   в ScriptEngine.Machine.CodeStatProcessor.GetStatData()
   в oscript.ScriptFileHelper.OnAfterScriptExecute(HostedScriptEngine engine)
   в oscript.ExecuteScriptBehavior.Execute()
   в oscript.Program.Main(String[] args)
```

**Воспроизведение ошибки**
1. Запустить код 
```
Процедура ТестДолжен_ПолучитьСправку() Экспорт

    Аргументы = Новый Массив;
    
    Команда = Новый КомандаПриложения("testapp", "Тестовое приложения", новый КомандаТест());
    Команда.Спек = "ИДЕНТИФИКАТОРЗАДАЧИВЕРСИИ [ОПЦИИ]";
    Команда.ВывестиСправку();
        
КонецПроцедуры

Процедура ТестДолжен_ПолучитьМокСоединение() Экспорт

    HTTPЗапрос = Новый HTTPЗапрос("/ping");

    МокСоединение = Мок.Получить(Новый HTTPСоединение("localhost"));

    // Вызов метода Получить по умолчанию вернет NULL, без исключений о недоступности сервиса
    Результат = МокСоединение.Получить(HTTPЗапрос);
    Ожидаем.Что(Результат).Равно(NULL);
    
КонецПроцедуры

```
КомандаТест.os
```
Процедура ОписаниеКоманды(КомандаПриложения) Экспорт
    
    КомандаПриложения.Опция("s ss", "", "")
        .Обязательный(Истина);
    
КонецПроцедуры

```
2. Подать на вход параметры `oscript -codestat=1.json tasks\test.os`
3. Увидеть ошибку
**Окружение**
 - ОС: Windows Server 2012
 - Версия: 1.4.0.176 и 1.5.0.178

Вот полный пример
https://github.com/Dezmont51/OneScriptMockError

А еще как в vscode в lauhch.json указать codestat?
В runtimeArgs ругается на путь

**Comment by nixel2007** [comment]
> А еще как в vscode в lauhch.json указать codestat?

через массив `args`

**Comment by Dezmont51** [comment]
> через массив `args`

Так не сработало
Он относится уже не к oscript, а к моему скрипту
То есть файл не создается

**Comment by nixel2007** [comment]
> В runtimeArgs ругается на путь

а как ругается?

**Comment by Dezmont51** [comment]
Script file is not found '-codestat=1.json' 

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Отладка 1Script",
            "type": "oscript",
            "request": "launch",
            "program": "${file}",
            "args": [],
            "cwd": "${workspaceRoot}",
            "env": {},
            "runtimeExecutable": null,
            "runtimeArgs": ["-codestat=1.json"],
            "debugPort": 2801,
            "protocol": "tcp"
        }
    ]
}

```

**Comment by nixel2007** [comment]
А, ну так вы убрали аргумент с путем к файлу скрипта. Верните его обратно :)

**Comment by Dezmont51** [comment]
Ничего не понял, но "program": "${file}", это поидее и есть тот файл который я запускаю
"program": "${workspaceRoot}/tasks/test.os",

Так `"runtimeArgs": [ "-сodestat=1.json", "${workspaceRoot}/tasks/test.os"],`
та же ошибка
так
`"runtimeArgs": [ "${workspaceRoot}/tasks/test.os",  "-сodestat=1.json"],`
не создается файл
и ещ кучу разных способов попробовал не прокатило

**Comment by yukon39** [comment]
Похоже на рецедив #645

**Comment by Dezmont51** [comment]
Эту ошибку можно исправить [вот так](https://github.com/Dezmont51/OneScript/commit/0654316c4ac1c9991568f0f7bb44107c1566e9b4)
Но я не знаю на что это может еще повлиять

**Comment by EvilBeaver** [comment]
Господа, не затруднит ли вас проверить последнюю ночную сборку на предмет исправления ошибки?

**Comment by yukon39** [comment]
С удовольствием посмотрим.

**Comment by Dezmont51** [comment]
Ночная сборка отработала как и хотелось. Ошибка ушла

**Comment by nixel2007** [comment]
Подтверждаю, тесты энтити с кавереджем тоже прошли:
https://github.com/nixel2007/entity/runs/1192846430?check_suite_focus=true
