### ISSUE TITLE
Неожиданное переполнение целого числа в 1Script

### ISSUE THREAD

**Issue by unboxedtype** [EvilBeaver/OneScript#1019]
**Опишите ошибку**
Добрый день! Какова длина целого типа в 1Script? 
Руководствуясь информацией из книги "Описание встроенного языка 1С", должно быть до
38 знаков. 
Цитирую:
"_Числовым типом может быть представлено любое десятичное число. Над данными числового типа определены основные арифметические операции: сложение, вычитание, умножение и деление. Максимально допустимая разрядность числа 38 знаков._"

Но 1Script падает с переполнением уже на 30 знаках.

**Воспроизведение ошибки**
[shishkin@oberon 1script]$ cat hello.bsl                                                                                                 
a = 123456789012345678901234567890;                                                                                                      
Message(a);                       
[shishkin@oberon 1script]$ oscript hello.bsl                         
System.OverflowException: Value was either too large or too small for a Decimal.

**Ожидаемое поведение**
Ожидал увидеть число 123456789012345678901234567890
Ведёт ли себя также 1С, сказать не могу, потому что нет живой инсталляции.

**Окружение**
 - ОС: Linux Fedora 29 
 - Версия: Fedora 29

**Дополнительная информация**
На сайте, в разделе "отличия от 1С" не говорится о том, что тип целого не совпадает
с типом целого в 1С.

**Comment by EvilBeaver** [comment]
Это известное ограничение, нужно отразить его в документации.

**Comment by EvilBeaver** [comment]
fixed
