### ISSUE TITLE
Не запускается отладчик в VS Code

### ISSUE THREAD

**Issue by Divanmgn** [EvilBeaver/OneScript#1021]
Здравствуйте.

Следую примеру Виталия Онянова https://youtu.be/-nSrx86k_1k?t=366

1. По нажатию F5 у меня появляется больше вариантов выбора, чем у Виталия. 
2. Выбираю как и он 1Script Debugger. 

Однако, после этого действия не происходит создание launch.json. Также при повторном нажатии F5 не происходит запуск отладчика, а все также предлагается выбор как и на шаге 1.

Может быть проблема в том, что я не устанавливал VS Code, а просто скачал zip последней версии с официального сайта (64 разрядный), распаковал его и запустил. (как portable версию). Далее делал все так как рассказывает в своем вебинаре Виталий Онянов.

**Comment by dvakor** [comment]
Попробуте нажать **Run** -> **Open** configurations и выбрать **1Script debugger**, должен появится **launch.json** сохраните его с дефолтными настройками и тогда отладка должна заработать

![image](https://user-images.githubusercontent.com/4038422/89097507-aa966a80-d409-11ea-9d54-75852b7cea29.png)

**Comment by Divanmgn** [comment]
Спасибо, Файл json сформировался.
