### ISSUE TITLE
Отладка не останавливается на точке останова

### ISSUE THREAD

**Issue by Divanmgn** [EvilBeaver/OneScript#1022]
После действий описанных в #1021 у меня сформировался файл launch.json
При нажатии F5 запустился отладчик, однако, он не остановился ни на одной из точек останова.
Поведение по нажатии F5 в видеоролике https://www.screencast.com/t/bzdmVrAi

**Comment by EvilBeaver** [comment]
Что написано в launch.json?

**Comment by avito456** [comment]
Аналогичная ситуация. JSON - стандартный, созданный по умолчанию.
Тестовый файл os - как в примере выше.
При запуске отладки через visual studio появляется на несколько секунд панель с кнопками отладки. При этом сообщение выводимое скриптом в окне   Debug concole не появляется, а  вместо него выводится сообщение onescript, как если запустить его без параметров.

launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Отладка 1Script",
            "type": "oscript",
            "request": "launch",
            "program": "${file}",
            "args": [],
            "cwd": "${workspaceRoot}",
            "env": {},
            "runtimeExecutable": null,
            "runtimeArgs": [],
            "debugPort": 2801,
            "protocol": "tcp"
        }
    ]
}

**Comment by EvilBeaver** [comment]
Если runtimeExecutable = null, то вызываться будет oscript из PATH. Есть вероятность, что по команде oscript запускается, например, какой-то старый oscript, который не поддерживает отладчик v0.7? Или наоборот, какова вероятность, что в VSCode установлен старый отладчик?

**Comment by Morkhe** [comment]
Спасибо. Проблема решилась обновлением оскрипта на версию 1.4.


>не поддерживает отладчик v0.7?

Хотя у нас отладчик стоит версии 0.6 (показывает, что это последняя).

**Comment by EvilBeaver** [comment]
Закрыл, не увидев, что @Morkhe не является автором задачи. @Divanmgn @avito456 - вопрос к вам - что с актуальностью версий. Должен быть 1скрипт 1.4 отладчик 0.6

**Comment by Divanmgn** [comment]
> Закрыл, не увидев, что @Morkhe не является автором задачи. @Divanmgn @avito456 - вопрос к вам - что с актуальностью версий. Должен быть 1скрипт 1.4 отладчик 0.6

Думаю можно закрывать, так как у меня точно старый релиз. Обновление релиза на сервере в ближайшем будущем маловероятно. Поэтому проверить не смогу. Если на новом релизе повторится создам новую заявку.

Спасибо.

**Comment by avito456** [comment]
Спасибо. Проблема решилась. Дело было в неактуальной версии 1скрипта.
