### ISSUE TITLE
Падение парсера на `#КонецОбласти` в конце файла

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#1023]
**Опишите ошибку**

При запуске скрипта с `#КонецОбласти` в конце файла и при наличии полезной нагрузки перед КонецОбласти, выполнение скрипта падает с ошибкой "Неизвестная операция"

**Воспроизведение ошибки**

Запустить:

```bsl
#Область Инициализация

А = 0;

#КонецОбласти

```

**Окружение**
 - ОС: windows 10 pro
 - Версия: 1.4.0

**Comment by Mr-Rm** [comment]
Ещё примеры, пригодится для тестирования.
Вот так работает, хотя не должно: 
```bsl
#Область Инициализация
А = 0;
//убран #КонецОбласти
```
И так работает
```bsl
// отсутствует #Область
Перем А;
#КонецОбласти
```
Так падает на 2-й строке (где #Область)
```bsl
А = 0;
#Область Инициализация
Б = 0;
#КонецОбласти
```
Область без имени - допускается
```bsl
#Область
Перем А, Б;
#КонецОбласти
```
И пара примеров, на которых даже подсветка сбоит:
```bsl
Перем А, Б,
#Область Переменные
 В, Г;
#КонецОбласти
```
```bsl
Процедура Проц(
#Область Параметры
 а,  б
#КонецОбласти
)
КонецПроцедуры
```

**Comment by nixel2007** [comment]
> И пара примеров, на которых даже подсветка сбоит:

ну, подсветка на гитхабе на базе регулярок и здравого смысла. поэтому и сбоит :)

По подсветке - в 1c-syntax/1c-syntax
