### ISSUE TITLE
Возможен код в строке директивы препроцессора

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1027]
**Опишите ошибку**
После директив препроцессора группы `#Если` возможно продолжать код на той же строке.

**Воспроизведение ошибки**
```bsl
#Если Windows Тогда Сообщить("Windows");
#Иначе // комментарий можно, это не ошибка  
#КонецЕсли Сообщить("Всегда!");
```
Компилируется и работает.

**Ожидаемое поведение**
Всё, кроме комментария, должно считаться ошибкой. Код может продолжаться только со следующей строки.

**Comment by EvilBeaver** [comment]
А разве это ошибка?

**Comment by Mr-Rm** [comment]
Да, _"Ошибка в операторе препроцессора"_
