### ISSUE TITLE
В директивах условной компиляции считается ошибкой, если выражение начинается со скобки

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1028]
**Воспроизведение ошибки**
```bsl
#Если (Windows или Linux) и Сервер Тогда // здесь будет ошибка
#ИначеЕсли (Клиент) // и так тоже падает
#ИначеЕсли(Сервер) // вариант без пробела
#КонецЕсли
```
_Ошибка в строке: 1,8 / Ожидается выражение_

**Ожидаемое поведение**
Выражения с начальными скобками должны обрабатываться правильно

**Comment by Mr-Rm** [comment]
Добавлю сюда же: выражение не может начинаться с `НЕ`
```bsl
#Если Не Windows Тогда // здесь будет ошибка
#КонецЕсли
```
Всё вместе исправляется удалением двух строк
https://github.com/EvilBeaver/OneScript/blob/63cb1f061741355d8915d2b1dcaa62bd9e0a4aa3/src/OneScript.Language/LexicalAnalysis/PreprocessingLexer.cs#L128-L129

Есть и ещё ошибки в работе препроцессора.
Стоит ли заводить issue на каждую или всё же следует переработать препроцессор полностью?

**Comment by EvilBeaver** [comment]
Я займусь препроцессором. Исправление понятно.

А "полностью" - это насколько?

**Comment by Mr-Rm** [comment]
Сейчас работа с директивами препроцессора есть и в лексере, и в компиляторе, и в энжине. И не самым простым образом устроена.
Возможно, стоило бы перенести всю обработку в лексер.

Ещё найденная ошибка:
```bsl
#Если Windows и Не Windows Тогда // или другое ложное условие
// эта часть не компилируется никогда
#Иначе
// эта часть - всегда
// #КонецЕсли - отсутствует в конце модуля
```
Работает, а дожна быть ошибка _"Ожидается завершение оператора препроцессора Если"_
