### ISSUE TITLE
Сломалось получение значения константы из базы 1С через COM

### ISSUE THREAD

**Issue by milkin-vl** [EvilBeaver/OneScript#1029]
**Награда за решение**
За решение этой проблемы объявляется символическая награда в 5 000 рублей.
Давайте я только в этот раз переведу напрямую на карту закрывшего задачу, чтобы опять не было этой эпопеи с bountysource.

**Опишите ошибку**
При попытке выполнить следующий код:

connector = Новый COMОбъект("V83.COMConnector");
connection = connector.Connect("File=""X:\Bases\Demo"";Usr="""";Pwd="""";");
Сообщить(connection.Константы.ДатаТекущейВерсии.Получить());

выскакивает ошибка:

{Модуль <string> / Ошибка в строке: 3 / Внешнее исключение (System.ArgumentException): Элемент с тем же ключом уже был добавлен.}    
Сообщить(connection.Константы.ДатаТекущейВерсии.Получить());

**Воспроизведение ошибки**
1. Похоже, что что-то сломалось именно в движке. Проверял на 1С 8.3.16.1502 (32) и 8.3.17.1549 (64).
Базы БП 3.0.80.36 и БП 2.0.66.106.
2. Код работает на Onescript 1.2 и не работает на версиях 1.4 и 1.5.

**Comment by dvakor** [comment]
Добрый день, в прошлый раз не учел работу с синонимами. Падает на `Получить()`, до тех пор пока ПР не будет влит, можете юзать англ. версию наименований методов, в вашем случае это `Get()`

**Comment by dvakor** [comment]
Обращение к своим экспортным процедурам и функцию работает корректно, косяк только с теми, которые поставляются вместе с платформой.

т.е. `connection.Документы.МойДок.МойМетодМодуляМенеджера()` будет работать

**Comment by gI5WYOAgg8YBF30CB1A4OfS9DndYrF3EQgdkGPe** [comment]
Точно, через англ. версию наименований методов работает. Спасибо)
Дмитрий, прошу вас выслать на мою почту helpme1c.box@gmail.com реквизиты для перевода вознаграждения.

**Comment by EvilBeaver** [comment]
Исправлено? Закрываем?

**Comment by milkin-vl** [comment]
Да, я проверил на ночной сборке от 14 сентября - всё ок.
