### ISSUE TITLE
Чтение текста - Символ.ВК

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#103]
Originally reported by: **Pr-Mex (Bitbucket: [Pr-Mex](http://bitbucket.org/Pr-Mex), GitHub: [Pr-Mex](http://github.com/Pr-Mex))**

---

Если читать текстовый файл через ЧтениеТекста, но поведение OneScript отличается от 1С.
Если написать
    Текст = Новый ЧтениеТекста;
    Текст.Открыть(ИмяФайла,"UTF-8");
    Стр = Текст.ПрочитатьСтроку();   

то при встрече в тексте Символ.ВК будет считана ещё одна пустая строка.

Например, 1С вернёт:

Процедура ПриЗаписи(Отказ)
    Если Не КонтрольID(ЭтотОбъект) Тогда
        Отказ = Истина;
        Возврат;
    КонецЕсли;

а OneScrip вернёт:

Процедура ПриЗаписи(Отказ)

```
Если Не КонтрольID(ЭтотОбъект) Тогда

    Отказ = Истина;

    Возврат;

КонецЕсли;
```

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/103

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Дай, пожалуйста пример сбойного файла (или его фрагмент, на котором воспроизводится) Файл можно прикрепить прямо к issue.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Pr-Mex (Bitbucket: [Pr-Mex](http://bitbucket.org/Pr-Mex), GitHub: [Pr-Mex](http://github.com/Pr-Mex))**:

---

Файл, в котором встречаются Символы.ВК.

**Comment by EvilBeaver** [comment]
_Original comment by_ **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**:

---

Подтверждаю

Код ниже выдает разные результаты в 1С и 1Скрипт для указанного файла

```
ИмяФайла = "f:\ObjectModule.txt";
Текст = Новый ЧтениеТекста; 
Текст.Открыть(ИмяФайла,"UTF-8");
Пока Истина Цикл
    Стр = Текст.ПрочитатьСтроку();
    Если Стр = Неопределено Тогда
        Прервать;
    КонецЕсли;
    Сообщить("<"+Стр+">");
КонецЦикла;
Текст.Открыть(ИмяФайла,"UTF-8");
Стр = Текст.Прочитать();
Сообщить("<"+Стр+">");
Сообщить("СтрДлина <"+СтрДлина(Стр)+">"); 
//Сообщить("СтрЧислоСтрок <"+СтрЧислоСтрок(Стр)+">"); 
```

1С возвращает длину 125 (СтрЧислоСтрок 6)

1Скрипт возвращает длину 131 :(

**Comment by EvilBeaver** [comment]
_Original comment by_ **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**:

---

Приложил тест (пока помечен как пропущенный) see #103

**Comment by n-dimens** [comment]
Вопрос к 1С-никам: А почему 1С выдает такую маленькую длину строки? Получается, он\она\оно игнорирует какие-то символы (ВК\ПС)? Потому что 131 - это как раз полный набор символов, с учетом непечатных символов (считал вручную, в notepad++ :))

P.S.: С количеством строк все понятно - используемая функция .NET воспринимает единичный Символ.ВК как конец строки, отсюда "набегают" лишние строки в .net.

**Comment by EvilBeaver** [comment]
Собственно issue как раз о том, что 1С считает переводом строки \n, а CLR - любую из комбинаций \r \n \r\n. Причем в 1С есть еще и override перевода строки. Можешь сказать, что строки разделены подстрокой "ТутНоваяСтрока". Я не стал реализовывать эту логику из-за низкой востребованности.

**Comment by n-dimens** [comment]
Так с переводом строки-то понятно, но при подсчете общей длины текста\файла 1С игнорирует символы '\n' что ли? И получается, тогда либо ЧтениеТекста.Прочитать должно возвращать текст без символов '\n' (что мне кажется слегка диким), либо СтрДлина должна игнорировать символы '\n'?

P.S.: Я взялся за эту задачу из-за пометки "bug", привычка в первую очередь стараться фиксить баги... В github вообще кроме меток приоритет задача как-то можно обозначить? Не очень привычный интерфейс баг-трекера ((

**Comment by dmpas** [comment]
> при подсчете общей длины текста\файла 1С игнорирует символы '\n' что ли?

@svgorbunov нет, просто в строчке `Стр = Текст.Прочитать();` в случае с 1С все ВК исчезают, потому что внутри 1С для переводов строк используются только ПС.

**Comment by n-dimens** [comment]
ааа, понял, он при чтении файла автоматически переводы строк корректирует.. ок, спасибо за разъяснение =)

**Comment by n-dimens** [comment]
гм... но тогда получается противоречие с тестами text-document.os `ТестДолжен_ПроверитьЗаписьДокумента`, `ТестДолжен_ПроверитьЗаписьДокументаВКодировкеПоУмолчанию`

а) ТекстовыйДокумент по умолчанию вставляет \r\n
б) Тесты для ТекстовогоДокумента ожидают, что после записи и прочтения с помощью ЧтениеТекста.Прочитать, символы новой строки останутся неизменными = \r\n

Это такое противоречивое API у 1С, или поведение ТекстовыйДокумент в рамках OneScript так же не соответствует 1С, а тесты фиксируют ошибочное поведение? Мне тут видится проблема посолиднее, чем изначальная ошибка вычисление длины содержимого файла...

**Comment by dmpas** [comment]
@svgorbunov Односкрипт тут тоже не соответствует 1С. "\r" появляется/исчезает на границе 1С-файл. Внутри 1С \r не используется, если, конечно, явно не заставить.

**Comment by EvilBeaver** [comment]
Проблема в следующем: 1С считает "переводом строки" в файле некую комбинацию символов (на винде это \r\n, на линуксе не проверял). При считывании она конвертирует это во внутренний "перевод строки", который всегда \n

В 1Скрипте я сделал "в лоб" - использовал StreamReader.ReadLine.Однако у него совсем другая логика определения переводов строк. Нужно реализовывать собственное построчное чтение, аналогичное 1С. Причем, выявить дефолтное поведение в разных ОС.

И да, поведение ЧтениеТекста и ТекстовыйДокумент может отличаться и в самой 1С.

**Comment by artbear** [comment]
Предлагаю обозначить сценарии проверки, а затем проверить на Вин и Линукс.
Что именно нужно проверить? (многабукв, все не прочел)

**Comment by n-dimens** [comment]
@artbear Суть проблемы: противоречие между тестами

text-document.os:
- ТестДолжен_ПроверитьЗаписьДокумента
- ТестДолжен_ПроверитьЗаписьДокументаВКодировкеПоУмолчанию

(работают, потому что ЧтениеТекста обрабатывает концы строк `\r\n` как есть)

и

xmlwrite.os:
- ТестДолжен_ПрочитатьИзФайлаСРазнымиПереводамиСтрок

(НЕ работает, потому что ЧтениеТекста обрабатывает концы строк '\r\n' как есть)

Либо какой-то из тестов определяет поведение, не соответствующее требованиям, либо тесты text-document не должны зависеть от поведения ЧтениеТекста.

Задача: определить корректное поведение ЧтениеТекста и ТекстовыйДокумент, как под Linux, так и под Windows, и сформулировать требования к поведению в OneScript.

**Comment by EvilBeaver** [comment]
по-моему, "ТестДолжен_ПрочитатьИзФайлаСРазнымиПереводамиСтрок" вообще игнорируемый, не? @artbear?

**Comment by artbear** [comment]
@EvilBeaver Да, он пропускается

**Comment by artbear** [comment]
@EvilBeaver Но это сделано специально для обозначения того, что проблема есть и ее нужно порешать. См. https://github.com/EvilBeaver/OneScript/issues/103#issuecomment-207408190

**Comment by dmpas** [comment]
Возьму поковырять на досуге.

**Comment by EvilBeaver** [comment]
@dmpas спасибо, было бы здорово. Там API во многом может с 1с-ным не совпадать. Если вкратце, то внутри штатный StreamReader.ReadLine, который за перевод строки берет любой из вариантов - \r, \n или \r\n. А в 1С эти комбинации менее толерантно обрабатываются, да еще и параметризуются.

**Comment by dmpas** [comment]
@artbear @EvilBeaver взорвал мозг тесты придумывать! есть мысли, как это всё проверить, не сравнивая выходной файл с двоичными данными? :)

**Comment by EvilBeaver** [comment]
@dmpas "Это все" это что именно?

**Comment by dmpas** [comment]
@EvilBeaver что строка, которую я пишу в файл, пишется с правильными переводами строк. Что файл со всякими разными переводами строк получается ровно тем, что мне нужно. С чтением вроде более-менее понятно, а вот запись текста пока плохо: как мне проверить, что переводы строк в файле ровно те, что надо? только двоичные данные сравнивать или хеш...

**Comment by artbear** [comment]
@dmpas я в свое время сделал простейший тест, он есть до сих пор.

Простейший тест - тупо сверяется количество символов и количество строк https://github.com/EvilBeaver/OneScript/issues/103#issuecomment-207408192

**Comment by artbear** [comment]
> а вот запись текста пока плохо: как мне проверить, что переводы строк в файле ровно те, что надо? только двоичные данные сравнивать или хеш...

у тебя есть/будет устраивающий тест на чтение, используй чтение для проверки записи :)

**Comment by artbear** [comment]
А вариант сравнения с двоичными данными так же неплох.
Только ИМХО у нас в 1скрипт нет возможности работать с двоичными данными :( или я ошибаюсь :)

**Comment by EvilBeaver** [comment]
в принципе у нас есть функции хеширования, так что этот вариант неплох.

**Comment by dmpas** [comment]
Когда завершение маякнуло на горизонте, возникла новая забава: в 1С под линуксом для ЧтениеТекста и ЗаписьТекста по-умолчанию используется виндовый перевод строк ВК+ПС.

Внимание вопрос! как лучше делать? совместимо с 1С, чтобы перевод строк по-умолчанию во всех средах был ВК+ПС или же делать ожидаемое поведение с учётом текущей среды?

**Comment by EvilBeaver** [comment]
А мне помнится, что был разный разделитель на линуксах и винде. Или это в ТекстовомДокументе?

**Comment by dmpas** [comment]
В текстовом документе тоже ВК+ПС по-умолчанию. @pumbaEO в гиттере скидывал выдержки из мужика со шляпой.

**Comment by EvilBeaver** [comment]
Тогда, полагаю, нужно делать как в 1с. Это всегда была наша политика. Если здесь сделать иначе, это будет непоследовательно и будет вызывать вопросы при использовании.

**Comment by dmpas** [comment]
@artbear @EvilBeaver тест `ТестДолжен_ПрочитатьИзФайлаСРазнымиПереводамиСтрок`, как мне кажется, стоит убрать из `xmlwrite.os`.

**Comment by artbear** [comment]
@dmpas Если у тебя есть место, куда его вставить, переноси.
Главное, чтобы тест не пропал в никуда :)

**Comment by dmpas** [comment]
@Pr-Mex и двух лет не прошло! призываю проверить. :)

**Comment by dmpas** [comment]
@EvilBeaver @Pr-Mex закрываем?

**Comment by artbear** [comment]
ИМХО нужно закрывать, т.к. все выполнено. мой тест проходит.

**Comment by Pr-Mex** [comment]
:-)
