### ISSUE TITLE
Сравнение строк

### ISSUE THREAD

**Issue by Morkhe** [EvilBeaver/OneScript#1031]
**Описание ошибки**
Сравнение строк в oscript происходит с учетом регистра, в то время как в 1С без учета регистра.

**Воспроизведение ошибки**
1. Запустить код
```
Список = Новый СписокЗначений();
Список.Добавить("аааааб");
Список.Добавить("аааааа");
Список.Добавить("Бааааа");

Список.СортироватьПоЗначению();

Для Каждого Элемент Из Список Цикл
	Сообщить(Элемент.Значение);
КонецЦикла;
```
2. Результат:
```
Бааааа
аааааа
аааааб
```

**Ожидаемое поведение**
Результат в 1С:
```
аааааа
аааааб
Бааааа
```

**Окружение**
 - ОС: Win Server 2012 R2
 - Версия: 1.4.0.177

**Comment by dmpas** [comment]
> Сравнение строк в oscript происходит с учетом регистра, в то время как в 1С без учета регистра.

я так полагаю, не "сравнение" как таковое, а именно сравнение в `Список.СортироватьПоЗначению()`
Потому что само по себе "сравнение" в 1С тоже идёт с учётом регистра.

**Comment by Morkhe** [comment]
> > Сравнение строк в oscript происходит с учетом регистра, в то время как в 1С без учета регистра.
> 
> я так полагаю, не "сравнение" как таковое, а именно сравнение в `Список.СортироватьПоЗначению()`
> Потому что само по себе "сравнение" в 1С тоже идёт с учётом регистра.

Да, возможно только при сортировке.
При сортировке в дереве значений такая же проблема.

Upd.
```
а = "а";
б = "Б";
Рез = а > б;
```
1C - Ложь
oscript - Истина

**Comment by EvilBeaver** [comment]
Принято, спасибо
