### ISSUE TITLE
Не работает ЧтениеZipФайла с конструктором, который принимает на вход Поток

### ISSUE THREAD

**Issue by ovcharenko-di** [EvilBeaver/OneScript#1032]
**Опишите ошибку**
При вызове конструктора "ЧтениеZipФайла(Поток)" возникает ошибка.

**Воспроизведение ошибки**
Вызвать конструктор "ЧтениеZipФайла(Поток)"

**Ожидаемое поведение**
Аналогично поведению 1С

**Окружение**
 - ОС: Windows
 - Версия: 1.4

**Дополнительная информация**
https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Zip/ZipReader.cs#L29

**Comment by Chipazawra** [comment]
Прошу заасайнить на меня
