### ISSUE TITLE
Поддержка внешних компонент Native API

### ISSUE THREAD

**Issue by lintest** [EvilBeaver/OneScript#1036]
**Цель:** реализовать полноценную поддержку внешних компонент, разработанных по технологии Native API

**Предлагаемые изменения:**
- **ScriptEngine.NativeApi.dll** - новая библиотека на C++, транслирующую вызовы между C# и Native API
- новые классы на С#, для подключения библиотеки Native API и создания экземпляров компонент
- новые параметры для метода глобального контекста **AttachAddIn()** 

**Дополнительная информация**
- большая часть реализована, готовится Pull Request: https://github.com/lintest/OneScript

**Comment by lintest** [comment]
Рабочий пример вызова свойств и методов библиотеки Native API

![testnative](https://user-images.githubusercontent.com/92895/97618866-9b3ab380-1a30-11eb-89ad-e6f89cbe70ff.png)

**Comment by lintest** [comment]
Новые классы и изменения в глобальном контексте

![image](https://user-images.githubusercontent.com/92895/97619721-9de9d880-1a31-11eb-8213-856a8f860a71.png)

**Comment by EvilBeaver** [comment]
Огонь! Только тогда уж 2 элемента перечисления - Native и... и.... как назвать протокол ВК односкрипта...??

@dmpas @nixel2007 @ArchLord42RU

**Comment by dmpas** [comment]
CLR ? OneScriptNative ?

**Comment by nixel2007** [comment]
> Огонь! Только тогда уж 2 элемента перечисления - Native и... и.... как назвать протокол ВК односкрипта...??

просто `OneScript`?

**Comment by nixel2007** [comment]
и да, обратную совместимость не поломать.

**Comment by lintest** [comment]
> и да, обратную совместимость не поломать.

Обратная совместимость сохраняется. 

Если второй параметр функции ПодключитьВнешнююКомпоненту() пустой, подключается компонента OneScript, если задан второй параметр, подключается компонента Native API. Третий параметр всегда игнорируется. Добавил его только для совместимости кода OneScript с кодом 1С.

**Comment by asosnoviy** [comment]
Шах и Мат, Исполнитель!

**Comment by dvakor** [comment]
@EvilBeaver а нужен ли и правда второй вариант?) Как и сказал @lintest это для обратной совместимости с 1Сным кодом.

в 1С два варианта вызова, мы можем ориентироваться на них же:

ПодключитьВнешнююКомпоненту(<Местоположение>, <Имя>, <Тип>) << подключит компоненту NativeApi как и в 1С
ПодключитьВнешнююКомпоненту(<ИдентификаторОбъекта> (Местоположение в нашем случае)) << тут вместо сома подключит оскриптовую


UPD

Хотя при написании кода, который работает и в оскрипте и в 1С лучше чтобы это значение было, можно будет сразу видеть не совместимые конструкции.

Правда будет немного тупое условие тогда будет, при выборе типа, щас то там просто string.IsNullOrEmpty().
И не понятно как вызвов будет осуществляться: походу так `ПодключитьВнешнююКомпоненту(ПутьКВК, "", ТипВнешнейКомпоненты.OScript);` ?)
В общем если и делать, то тогда я +1 к @nixel2007 "OneScript" \ "OScript" \ "OS" звучит не плохо)

**Comment by lintest** [comment]
Вопрос: Как из своего модуля вызвать метод глобального контекста?
```C#
ApplicationHost.Echo(message, status);
```
Это необходимо для callback-функций внешней компоненты: 
- сообщения об ошибках внешней компоненты
- обработка внешнего события
- показ статус-строки

**Comment by nixel2007** [comment]
> И не понятно как вызвов будет осуществляться: походу так ПодключитьВнешнююКомпоненту(ПутьКВК, "", ТипВнешнейКомпоненты.OScript); ?)

а почему не зарегистрировать какое-то имя для оскриптовой компоненты? или его потом негде будет использовать?

**Comment by lintest** [comment]
Второй вариант **ТипВнешнейКомпоненты.OScript** не нужен:
1. Нарушается совместимость кода с платформой 1С
1. Функция подключения  компоненты игнорирует этот параметр 
1. Тип компоненты нигде далее в коде не используется

**Comment by nixel2007** [comment]
> Нарушается совместимость кода с платформой 1С

спорное утверждение. это наоборот позволит привести код подключения оскриптовых библиотек к синтаксису платформы

> Функция подключения компоненты игнорирует этот параметр

ничто не мешает переделать функцию подключения компоненты на учет этого параметра.

> Тип компоненты нигде далее в коде не используется

см п.2

**Comment by lintest** [comment]
Странно, что дискуссию вызвал второстепенный вопрос, который не имеет существенного влияния на реализуемый функционал. 

Для меня сейчас актуальными задачами являются сборка для Linux и покрытие функционала компоненты юнит тестами. Для юнит тестов также потребуется эталонная внешняя компонента, которая максимально реализует возможности Native API. Вопрос: включать её программный код в состав проекта OneScript или реализовать как отдельный проект?

**Comment by lintest** [comment]
Желательно также добавить в OneScript новый тип объектов **ОписаниеОповещения**, чтобы иметь возможность подключать пользовательские обработчики для событий внешней компоненты: ошибка, внешнее событие, статус строка.

**Comment by nixel2007** [comment]
> Странно, что дискуссию вызвал второстепенный вопрос, который не имеет существенного влияния на реализуемый функционал.

Дискуссию вызвал дизайн апи, который очень легко изначально сделать корявым, а потом мучительно больно его ломать с нарушением обратной совместимости между версиями движка. 

Эталонную компоненту, думаю, можно положить в проект с тестами, там же, где и тестовые библиотеки лежат.

**Comment by nixel2007** [comment]
С описанием оповещения сложнее. В движке, насколько я помню, вообще нет понятия event loop, и некому будет обрабатывать входящее сообщение. Плюс он однопоточный.

**Comment by nixel2007** [comment]
Поэтому и родилась библиотека notify. Но опять таки она синхронная

**Comment by lintest** [comment]
События компоненты тоже однопоточные, фактически речь идёт о вызове callback функций

**Comment by lintest** [comment]
![Screenshot_20201031-131403_Chrome](https://user-images.githubusercontent.com/92895/97776665-0abcba00-1b7b-11eb-804b-c35dca40a58b.jpg)

**Comment by nixel2007** [comment]
Разве код 1с встаёт в синхронное ожидание после НачатьВызов... и модально ждёт вызова колбэка? Я думал, что он продолжает выполнение кода, то есть работает в отдельном от компоненты потоке

**Comment by lintest** [comment]
> Разве код 1с встаёт в синхронное ожидание после НачатьВызов... и модально ждёт вызова колбэка? Я думал, что он продолжает выполнение кода, то есть работает в отдельном от компоненты потоке

У меня сложилось ощущение, что после вызова **ВК.НачатьВызов<>** продолжается выполнение программного кода модуля 1С в основном потоке. И только когда закончится выполнение кода, управление передаётся внешней компоненте для выполнения её методов, результат которых будет передан callbaсk функции, заданной в объекте **ОписаниеОповещения**.

Я пытался делать вызовы внешней компоненты VanessaExt для получения снимков экрана в режиме запрета использования синхронных вызовов расширений платформы и внешних компонент. Если делать в основном потоке, то снимки делаются уже после того, как отработали все шаги сценария Vanessa Automation. Можно внутри компоненты создать отдельный поток, это сейчас используется для визуализации нажатия мыши. Но чтобы вернуть результат в 1С всё равно потребуется синхронизировать вызов с основным потоком.

**Comment by nixel2007** [comment]
Понятно, спасибо!

**Comment by lintest** [comment]
Готова реализация для Windows. Отправил Pull Request.

Нужна помощь!
Не смог самостоятельно разобраться, как правильно добавить в общую сборку свои файлы проектов.
- \src\ScriptEngine.NativeApi\ScriptEngine.NativeApi.vcxproj
- \tests\native-api\AddInNative.vcxproj

**Comment by EvilBeaver** [comment]
По поводу потоков - полагаю разница будет видна только в веб-клиенте 1С. Обычный клиент не обязан вызывать компоненту асинхронно, это браузерное ограничение. В самом NativeAPI все методы синхронные.

**Comment by EvilBeaver** [comment]
Задача выполнена. Вопрос с типом компоненты решил введением значения OneScript в перечисление ТипВнешнейКомпоненты.

Мотивация:

* Всегда видно 1С-несовместимый код
* Наличие перечисления позволяет писать 1С-совместимый код.
