### ISSUE TITLE
Переход на Net 5.0

### ISSUE THREAD

**Issue by asosnoviy** [EvilBeaver/OneScript#1037]
# Описание задачи

Исходное обсуждение из странного места: 
https://github.com/EvilBeaver/OneScript/commit/ab2b93381e1afa042b6653be8bf3609ce4ca23f5#r43688540

> @EvilBeaver пока ты допилишь Netcore 3.1 - выйдет NET 5.0. Рассмотри предложение работать сразу на NET 5.0 - они наконец-то стабилизировали все свои NETCORE, NETSTANDART в единый контекст net5.0

На выходе @aliczin присылает полнофункциональный PR сборочного скрипта на входе которого команда

`dotnet publish Build.csproj /p:ReleaseNumber=x.x.x <какие-то еще опции>`
а на выходе каталог:

* win-32
  * bin
  * lib
  * docs
  * examples
  * VERSION - текстовый файл с текущей версией
* win-64
  * аналогично в других платформах
* linux-64
* mac-64

все bin файлы собраны в TargetFramework netcoreapp3.1, в режиме self-contained deployment с включением всех зависимостей в bin.

**Comment by asosnoviy** [comment]
@aliczin как то так на ГХ принято оформлять предложения, в Issues.

**Comment by aliczin** [comment]
@asosnoviy это было не обязательно - но спасибо

**Comment by aliczin** [comment]
![изображение](https://user-images.githubusercontent.com/56105699/97688969-feb5f700-1aab-11eb-82a6-0deece4aa068.png)

5-ка и 3-шка по разному себя ведут в части упаковки в один файлик

в 3-шке - приходится костылить 
в 5-ке - добавили флаг `-p:IncludeNativeLibrariesInSingleFile=true` которые делает все проще

**Comment by EvilBeaver** [comment]
@aliczin в критериях и голосом явно проговорили НЕ упаковывать в один файлик. Там получается 80Мб exe и рядом все равно конфиги. Т.е. файл все равно не один, а коли так, то преимущество single-file-deploy теряется и тогда пусть будет привычный набор файлов.

**Comment by aliczin** [comment]
@EvilBeaver можно все в один файл, можно runtrime отдельно. Погоди до вчера посмотришь что получилось

**Comment by EvilBeaver** [comment]
Перечитал критерии и понял, что возможна путаница в терминологии. Упомянутый self-contained deployment (SCD) это не то же самое, что single-file. self-contained, это когда фремворк кладется рядом с самим приложением при публикации и таким образом не требуется установка .netcore на целевую машину. В отличие от framework-depended deploy (FDD), когда по классике публикуется только приложение, но на целевой машине должен жить фреймворк.

single-file-deploy - это то же, что и SCD, но упакованое прямо в один файл. Оно действительно сыроватое, реализуется по-разному и в целом все равно не остается ЕДИНЫМ файлом. Так что пока не нужно.

https://habr.com/ru/post/311520/

А вот PublishReadyToRun - когда происходит прекомпиляция в машинный код, а не JIT - интересно. Можно поэкспериментировать

**Comment by aliczin** [comment]
> А вот PublishReadyToRun - когда происходит прекомпиляция в машинный код, а не JIT - интересно. Можно поэкспериментировать

пока тесты не проходят с этой опцией - смотрю

**Comment by aliczin** [comment]
Новый AST выдал странное - как будто перепутал контекст модуля и класса

![изображение](https://user-images.githubusercontent.com/56105699/97759606-70c12700-1b12-11eb-80b0-2ba30312b6d9.png)

Работа продолжается

**Comment by aliczin** [comment]
![изображение](https://user-images.githubusercontent.com/56105699/97761735-8b49cf00-1b17-11eb-810a-313a70279c42.png)
![изображение](https://user-images.githubusercontent.com/56105699/97761893-090dda80-1b18-11eb-8df5-b53c87c60e5a.png)
![изображение](https://user-images.githubusercontent.com/56105699/97761902-15923300-1b18-11eb-84fd-fb4319a0dc77.png)
![изображение](https://user-images.githubusercontent.com/56105699/97761954-3e1a2d00-1b18-11eb-9197-8f7fb4eaa5c8.png)

Одна команда - например для Windows

```
dotnet publish -p:PublishTrimmed=true -p:PublishReadyToRun=true -p:PublishReadyToRunShowWarnings=true -f netcoreapp3.1 -p:DebugType=None -r win-x64  -c Release --self-contained true --force -p:IncludeNativeLibrariesInSingleFile=true -p:CopyOutputSymbolsToPublishDirectory=false .\src\oscript\oscript.csproj -o distrs\net31\win-x64\bin
```

P.S. JIT компиляция работает только у Windows

ЛоЖка дегтя - падает AST на JSON пакете - тут я пока остановлюсь - на выходных еще сделаю подход

@EvilBeaver но формально - то что ты хотел работает

**Comment by aliczin** [comment]
@asosnoviy переименую пожалуйста задачу "Переход на NetCore 3.1 стабильный и перспективный NET 5.0"

**Comment by akpaevj** [comment]
NET 5 - не LTS, переходить в таком крупном проекте на него (на мой взгляд) не совсем правильно. Скоро зарелизится NET 6 LTS

**Comment by aliczin** [comment]
@akpaevj пробник уже сделал Андреем https://github.com/EvilBeaver/OneScript/releases/tag/v2.0.0-alpha-2
формально по этой задаче уже больше можно не делать ничего, а дальше в рабочем порядке ;-)
