### ISSUE TITLE
AST при компиляции "вначале добавляет методы глобального контекста", в силу чего методы классов имеющие идентичные имена будут выдавать ошибку компиляции, после чего неверно парсит часть модулей

### ISSUE THREAD

**Issue by aliczin** [EvilBeaver/OneScript#1039]
относится к https://github.com/EvilBeaver/OneScript/tree/feature/compiler-v2

**Цель:**
Разрешить конфликты имен методов глобального контекста и методов классов

**Опишите решение**
Во время компиляции класса при помощи AST добавлять методам глобального контекста определенный признак чтобы не было конфликта с методами класса, а во время вызова вызывать метод класса, а не глобального контекста

**Пример**

* существует метод глобального контекста `ПрочитатьJSON`
* я пишу свой скрипт скажем `Тесть.os`
* в первой строке я указываю `#Использовать json`
* библиотека `json` определяет класс `ПарсерJSON` и внутри класса экспортный метод `ПрочитатьJSON`
* `AstBasedCodeGenerator` попытается "посетить метод класса" и выдаст ошибку, так как у него в "контексте" уже есть такой метод"

**Способ воспроизведения проблематики**

* взять бранч https://github.com/aliczin/OneScript/tree/feature/compiler-v2-publisher
* запустить файлик `publish.bat`

получим ошибку

```
opm\oscript_modules\json\src\json.os / Ошибка в строке: 264,1 / AST: Метод с таким именем уже определен: ПрочитатьJSON в контексте 10 по коду 0;}
```

**Еще дополнительный пример**

* существует метод глобального контекста `СоздатьКаталог`
* я пишу свой скрипт скажем `Тесть.os`
* в первой строке я указываю `#Использовать tempfiles`
* библиотека `tempfiles` определяет класс `МенеджерВременныхФайлов` и внутри класса экспортный метод `СоздатьКаталог`
* `AstBasedCodeGenerator` попытается "посетить метод класса" и выдаст ошибку, так как у него в "контексте уже есть такой метод"

с временными файлами еще хуже - там и класс и модуль - это один и тот же файл https://github.com/oscript-library/tempfiles/blob/master/lib.config

Данная задача блокирует работу над тестированием #1038 

Место Exception'а https://github.com/EvilBeaver/OneScript/blob/feature/compiler-v2/src/ScriptEngine/Compiler/ByteCode/AstBasedCodeGenerator.cs#L196

**Comment by EvilBeaver** [comment]
Странно, почему старый компилятор не падает, ведь алгоритм разрешения имен видимости один и тот же

**Comment by aliczin** [comment]
@EvilBeaver падает на AstBasedCodeGenerator

` if (_ctx.TryGetMethod(signature.MethodName, out _))`

Дело в том что к этому моменту уже 

` var hasMethod = _ctx.TryGetMethod(identifier, out var methBinding);`
``

https://github.com/EvilBeaver/OneScript/blob/feature/compiler-v2/src/ScriptEngine/Compiler/ByteCode/AstBasedCodeGenerator.cs#L696

То есть в контексте уже есть Глобальные функции - а в `VisitMethod` видимость не проверяется

в связанном PULL REQUEST убрал всю магию - оставил только чистое состсояние воспроизведения ошибки

**Comment by aliczin** [comment]
@EvilBeaver пока при исследовании обошел так

![изображение](https://user-images.githubusercontent.com/56105699/98045641-da567380-1e39-11eb-96b4-febb21364df4.png)

Теперь что-то AST не нравится с ПараметрыКоманды

![изображение](https://user-images.githubusercontent.com/56105699/98045684-ecd0ad00-1e39-11eb-87c1-2e0022be426a.png)

**Comment by EvilBeaver** [comment]
Ну раз компилятор падает - предлагаю это повесить на меня, т.к. привнесен баг в движок, а в рамках PR вернуться к сборке дистрибутива. В дистрибутив же можно включить и сломаный движок, главное, чтоб сам билд-скрипт работал. Т.е. собирались написать новый билд-скрипт. А косяки компилятора - на мне.

**Comment by aliczin** [comment]
@EvilBeaver билд скрипт работает - сейчас уберу WIP

Точнее его правильно называть Publish+Build скрипт

**Comment by Mr-Rm** [comment]
Возврат к старому поведению не годится, т.к. оно ошибочно позволяло в основном модуле переопределять общие функции глобального контекста:
```bsl
Функция КаталогПрограммы()
	Возврат "/dev/null";
КонецФункции

Сообщить(КаталогПрограммы());
```
получаем
_/dev/null_
вместо ожидаемого
_Ошибка в строке: 1,1 / Метод с таким именем уже определен: КаталогПрограммы_

**Comment by Mr-Rm** [comment]
Посмотрел в
https://github.com/oscript-library/tempfiles/blob/master/ВременныеФайлы.os
```bsl
Функция СоздатьКаталог(Знач Расширение = "tmp") Экспорт

	ИмяФайла = НовоеИмяФайла(Расширение);
	СоздатьКаталог(ИмяФайла);
	
	Возврат ИмяФайла;

КонецФункции

```
Выглядит как рекурсия. Что-то в этом есть неправильное.

**Comment by EvilBeaver** [comment]
Да я тоже удивился что такое возможно, однако, @aliczin упомянул, что именно старое поведение позволяет тестам проходить, а новое - нет. Я не проверял этот тезис и почему старое поведение должно остаться - не знаю.

**Comment by aliczin** [comment]
@EvilBeaver тесты НЕ проходят я выше написал - после данного исправления идет ошибка в пакете `CLI`

![изображение](https://user-images.githubusercontent.com/56105699/98369178-8fab4600-2049-11eb-8fff-a7c30d8a6c6a.png)

**Comment by Mr-Rm** [comment]
Новый AST-based компилятор плохо работает с `#Область` / `#КонецОбласти`
_Ошибка в строке: 746,10_  возникает после `#Использовать cli` в файле КомандаПриложения.os:
```bsl
#Область Работа_с_входящими_аргументами

Процедура ОчиститьАргументы(АргументыCLI)
//       ^ здесь
```

**Comment by aliczin** [comment]
@Mr-Rm в порядке теста я убрал области из файла класса `ПараметрыКоманды` - ситуация не поменялась. Что-то другое - чего я пока не понял - это как отлаживать новое AST. Учитывая ошибку в количестве строк - думаю недочет где-то даже в Lexer. Прям не хочется Visual Studio ставить - но видимо придется.

**Comment by Mr-Rm** [comment]
Убирать Области надо из класса `КомандаПриложения` - он загружается раньше. Но всё равно падает, только уже по другой причине:
_{Модуль C:\Program Files\OneScript\lib\logos\src\log-manager.os / Ошибка в строке: 172 / Внешнее исключение (System.NullReferenceException): Object reference not set to an instance of an object.}    
		КаталогКонфига = СтартовыйСценарий().Каталог;_
Проблемы с Областью, отмеченные в issue #1023, в новом парсере только ухудшились.

**Comment by EvilBeaver** [comment]
Области вообще не обрабатываются пока. Для работ над сборкой под core лучше не использовать пока новый компилятор. Там абсолютно ужасно сделана работа с препроцессором в принципе - и в старом и по наследству - в новом. Я хочу все это перепилить

**Comment by EvilBeaver** [comment]
@aliczin кажется, компилятор v2 готов к новым испытаниям. По крайней мере области научился обрабатывать, спасибо @Mr-Rm

**Comment by aliczin** [comment]
@EvilBeaver - в среду вечером займусь снова.

**Comment by aliczin** [comment]
@EvilBeaver так я и не победил - теперь на fluent падает. Ошибку выдает

`OneScript.Language.SyntaxAnalysis`

Причем - еще и не срабатывает локализация исключения.

![изображение](https://user-images.githubusercontent.com/56105699/101286048-7ab50480-37f9-11eb-8632-c318fc56042a.png)

**Comment by EvilBeaver** [comment]
@aliczin все тесты ветки теперь v2 проходят

**Comment by aliczin** [comment]
@EvilBeaver AST больше не падает - там уже другое - но это ишуз предлагаю закрыть
