### ISSUE TITLE
Актуальность версий библиотек в системе сборки и тесты

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1042]
**Воспроизведение ошибки**

1. Локально, для ветки `develop` в каталоге `tests` запускаем
**oscipt testrunner.os -run constructor.os**
2. Тест падает с ошибкой:
> Тест №4: ТестДолжен_СоздатьОбъектЛог
> 
> ОШИБКА: Тест: <ТестДолжен_СоздатьОбъектЛог>
> Файл: <S:\\_Repo\OneScript\tests\constructor.os>
> Сообщение: Параметры конструктора: необходимых параметров: 1, передано параметров 0

**Окружение**
 - библиотека `logos` версии 1.1.2 или выше

**Дополнительная информация**
До версии 1.1.2 в библиотеке `logos` использовался конструктор без параметров. В расчёте на это работает и тест:
https://github.com/EvilBeaver/OneScript/blob/137bffe0152146506ee42fb94e8ad3fdff3cf9a5/tests/constructor.os#L95
После обновления `logos` до актуальной версии (1.3.0) тест не проходит.

Однако, автоматическая сборка и тестирование текущей версии завершается успешно. Значит, сборка и тесты производятся со старыми версиями библиотек. Т.е. тесты проверяют устаревшее поведение.

Обновлять в системе сборки библиотеки до актуальных версий и, при необходимости, корректировать тесты или зафиксировать используемые версии и явно их перечислить?
Добавить в runtime возможность определять версию используемой библиотеки?

**Comment by nixel2007** [comment]
> Значит, сборка и тесты производятся со старыми версиями библиотек. Т.е. тесты проверяют устаревшее поведение.

насколько я понимаю смысл этого теста - проверить то, что классы из библиотек вообще создаются. в окружении теста (на старой версии логоса) класс создается и тест проходит. (не говорю уже о том, что конструктор `Лог`'а - это вообще внутреннее приватное api библиотеки).

конечно досадно, что тест из-за этого падает. но на мой взгляд тут проблема скорее в том, что тест завязан на неподконтрольное движку окружение. добавлю я второй параметр в этот конструктор (а первый как раз я добавлял) - тесты движка упадут? следует переписать этот тест так, чтобы инстанцировались объекты подконтрольной тестовой библиотеки, либо выпилить его вообще.

**Comment by Mr-Rm** [comment]
Тогда стоит убрать обращение к `logos` из `constructor.os`. Проверка работы конструктора тестовой библиотеки выполнится в `librarytest.os`.
Порядок выполнения тестов для `testrunner.os -all` не задан.
А testrunner сложен настолько, что запускать из него, например, тест `engine-behaviors.os` имеет мало смысла - в случае проблем он сам упадет раньше. Такие низкоуровневые тесты надо бы запускать прямо из start.cmd или start.sh.

И остаётся предложение о функции, определяющей версию библиотеки.
