### ISSUE TITLE
Имена библиотек в директиве #Использовать

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1044]
Препроцессор передаёт в обработчик директив в качестве параметра всё, находящееся после имени директивы, до конца строки.
Загрузчик библиотек рассматривает переданный параметр как путь к каталогу библиотеки и в варианте с кавычками, и без кавычек.
В результате:
- не допускаются комментарии после имени библиотеки.
Не работают примеры со страницы документации https://oscript.io/docs/page/libraries
`#Использовать json // встроенный алгоритм поиска`
и
`#Использовать "lib/mylib" // явное указание пути к библиотеке`
Причём второй пример падает с неперехваченным системным исключением
_Illegal characters in path._

- возможно использовать без кавычек пробелы в именах библиотек и путях к ним
`#Использовать json 2`
(будет загружаться бибилиотека "lib\json 2", если есть)
`#Использовать ..\..\..\Program Files\OneScript\lib\json`

- из-за особенностей работы .net с путями файлов (в Windows) возможны конструкции
`#Использовать json///\\\///`
`#Использовать ..// /// //lib  \\\./.\. \\\json`

Варианты:
1. Передавать загрузчику параметром содержимое строки либо до пробела, либо в кавычках.
При этом будут разрешены комментарии в конце строки, но потеряется возможность указывать имя или путь к библиотеке с пробелами без кавычек.
2. Оставить как есть, исправив пример в документации и перехват исключения.

**Comment by EvilBeaver** [comment]
Это известный косяк реализации. Все что касается импорта библиотек делалось в спешке. Идейно должна быть следующая грамматика:

`#Директива [ПараметрыДирективы][Комментарии]NEWLINE`

А параметры - любое что угодно - пока не встретится комментарий, решать должен DirectiveResolver. Но там все не срослось с этим подходом, поэтому костыли и адъ.
