### ISSUE TITLE
Недопустимые символы в строках, исключённых директивами условной компиляции

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1049]
**Опишите ошибку**
Если в строках, исключённых директивами условной компиляции, есть произвольные символы, не предусмотренные грамматикой языка, то возникает ошибка.

**Воспроизведение ошибки**
```bsl
#Если Windows и Linux Тогда
!!
#КонецЕсли
```
_Ошибка в строке: 2,1 / Неизвестный символ !_

**Ожидаемое поведение**
Строки, исключённые директивами условной компиляции должны игнорироваться полностью до закрывающей блок директивы. 

**Дополнительная информация**
Заменить полексемное сканирование игнорируемых блоков на построчное.

**Comment by EvilBeaver** [comment]
Ой-вей... А в 1С так, да?

**Comment by Mr-Rm** [comment]
Да, и в 1С, и в других языках - в некомпилируемой части пропускается всё.

**Comment by Mr-Rm** [comment]
Сюда же:
Если в некомпилируемой ветви `#Иначе` встречаются директивы `#Использовать` или `#Область`, то падает с ошибкой
_Ожидается директива препроцессора #КонецЕсли_,
а не должно.
