### ISSUE TITLE
Выражение в директивах #Если/#ИначеЕсли может быть перенесено на новую строку

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1050]
**Опишите ошибку**
```bsl
#Если Windows
 или Linux
 Тогда
//!!
#КонецЕсли
```
Компилируется, а не должно.

**Comment by EvilBeaver** [comment]
Исправлено в 2.0, в 1.x предлагаю не исправлять

**Comment by Mr-Rm** [comment]
Уже исправил.
Но в ветке feature/compiler-v2 пример по-прежнему компилируется.
