### ISSUE TITLE
Ошибка запуска отладчика OneScript.Web

### ISSUE THREAD

**Issue by arkuznetsov** [EvilBeaver/OneScript#1052]
При попытке запуска отладчика OneScript.Web возникает ошибка:
![image](https://user-images.githubusercontent.com/10762909/101132459-19820b00-3618-11eb-8b9d-efe3bbc41ea5.png)
![image](https://user-images.githubusercontent.com/10762909/101132494-26066380-3618-11eb-9bd1-056c41233958.png)
![image](https://user-images.githubusercontent.com/10762909/101132541-361e4300-3618-11eb-925f-f613e3eaae63.png)

На некоторых машинах, после некоторого количества нажатий F5 все-таки запускается, на других так и не удается запустить.

Порт 2801 открыт.

launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Отладка 1Script.Web",
            "type": "oscript.web",
            "request": "launch",
            "appDir": "${workspaceRoot}\\src",
            "env": {},
            "runtimeExecutable": "d:\\oscript.web\\OneScript.WebHost.exe",
            "runtimeArgs": [],
            "debugPort": 2801,
            "protocol": "tcp"
        }
    ]
}
```

VSC:1.51
Oscript.Web: 0.7

**Comment by EvilBeaver** [comment]
Да, проблема известна. Спасибо, что зарегистрировал.

**Comment by arkuznetsov** [comment]
@EvilBeaver Могу попробовать помочь, если подскажете как отлаживать отладчик. :-)

**Comment by EvilBeaver** [comment]
Там лучше без огнемета в код не залазить.
