### ISSUE TITLE
Создание файла по относительному пути (поведени отличается от 1С)

### ISSUE THREAD

**Issue by arkuznetsov** [EvilBeaver/OneScript#1061]
**Опишите ошибку**

Создаем файл по отностиельному пути:

```
ИмяФайлаАрхива = ".\tmp\distr\Accounting30\3.0.82.24\Accounting_3_0_82_24_updsetup.exe";
ФайлАрхива = Новый Файл(ИмяФайлаАрхива);
```

В созданном объекте получаем:
![image](https://user-images.githubusercontent.com/10762909/104731074-39930700-574c-11eb-9c97-4bb431bd2fec.png)

т.е. в свойстве "Путь" имеем относительный путь, а свойстве "ПолноеИмя" - абсолютный.

В 1С (8.3.17.1851) вообще другое поведение, там так:
![image](https://user-images.githubusercontent.com/10762909/104731233-79f28500-574c-11eb-8d61-3ba7c45cfdab.png)

т.е. символы подстановки вообще удаляются в обоих свойствах.

Что забавно, если использовать подстановку `..` или даже `..\..`, то в 1С она тоже просто удаляется.

**Ожидаемое поведение**
По идее нужно унифицировать поведение, но в 1С оно мне не нравится. Возможно нужно либо в обоих свойствах разрешать относительные пути, либо в обоих не разрешать.

**Окружение**
 - ОС: Win10
 - Версия: 1.4

**Comment by EvilBeaver** [comment]
Подстановки точно будут удаляться. А вот то, что в Путь - относительный путь - это, пожалуй баг.

**Comment by arkuznetsov** [comment]
@EvilBeaver Т.е. ты хочешь в "Путь" сделать тоже абсолютный?
Это будет "не как в 1С"?

**Comment by EvilBeaver** [comment]
а как "в 1С"? в 1С нет понятия "текущего каталога" из которого запущена платформа. Как там работает Файл(ОтносительныйПуть)?

**Comment by nixel2007** [comment]
Кажется, пару лет назад уже было обсуждение про текущий каталог. Он отличается в зависимости от способа запуска/определения. Где-то от эхешника платформы, где-то от пути к внешней обработке, а где-то прям CWD из терминала в момент запуска

**Comment by EvilBeaver** [comment]
Я скорее про то, как ведет себя 1С если мы делаем Файл по неполному пути и вызываем у него "Путь" и "ПолноеИмя"?

**Comment by arkuznetsov** [comment]
@EvilBeaver В 1С (я написал в описании) оставляет относительный и в "Путь" и в "ПолноеИмя", да еще и чистит лидирующие подстановки (`.`, `..`, `..\..` и т.д.).

**Comment by EvilBeaver** [comment]
Мне кажется, для скриптового движка как раз потребность узнать ПолныйПуть по относительному - это важная фича.

**Comment by arkuznetsov** [comment]
@EvilBeaver Наверное ты прав. Т.е. сделать, чтобы путь был полным в обоих полях?
Может еще добавить поле "ИсходныйПуть", где будет лежать в том виде, в котором задан путь в конструкторе?

**Comment by arkuznetsov** [comment]
@EvilBeaver UP!

**Comment by EvilBeaver** [comment]
Мне кажется правильным:

1. В свойстве ПолноеИмя всегда должен быть полный путь, относительно рабочей директории.
2. В свойстве Путь - хрен знает что, наверное, не так важно, может быть и относительный, относительно того, что передали в конструктор
3. Свойство ИсходныйПуть не нужно

@dmpas @nixel2007 @Mr-Rm @ArchLord42RU discuss

**Comment by arkuznetsov** [comment]
@EvilBeaver Принято!

**Comment by nixel2007** [comment]
@EvilBeaver в java и js (если я правильно помню) - в путях лежит именно тот путь, который был передан в конструктор.
в полном имени - путь + имя файла, но опять же, так как они были переданы в конструктор.

а для разрешения полного есть отдельный метод нормализации/каноникализации пути, который уже возвращает реальный путь относительно CWD и особенностей файловой системы (симлинки и прочее)

**Comment by EvilBeaver** [comment]
@nixel2007 ну мы же не станем опускаться до того, чтоб копировать api java, верно? )

**Comment by nixel2007** [comment]
@EvilBeaver иногда тебя это не останавливает)

**Comment by dmpas** [comment]
Не припомню, чтобы я вообще когда-то использовал `Путь`. `Имя`, `ИмяБезРасширения` и `ПолноеИмя` - всё, что нужно. Предлагаю за-wontfix-ить и ждать, когда 1С задепрекейтит этот срам. :)
