### ISSUE TITLE
Падает ВвестиСтроку() при вводе короче заданной длины

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1065]
_(Впервые ошибку обнаружил @tihov три года назад.)_

**Опишите ошибку**
Функция `ВвестиСтроку()` падает с ошибкой, если указана максимальная длина вводимой строки, но вводится меньшее число символов.

**Воспроизведение ошибки**
1. Запустить код 
```bsl
СтрокаВвода = "";
Длина = 5;
Если ВвестиСтроку(СтрокаВвода,Длина) Тогда
  Сообщить(СтрокаВвода);
КонецЕсли
```
2. ввести *123*
3. Увидеть ошибку
_{Модуль D:\test\OneScript\issue-input.os / Ошибка в строке: 3 / Внешнее исключение (System.ArgumentOutOfRangeException): Index and length must refer to a location within the string.
Parameter name: length}_

**Ожидаемое поведение**
вывод _123_

**Дополнительная информация**
С этой ошибкой всё понятно, но по базовой платформе функция должна быть:
> ВвестиСтроку(<Строка>, <Подсказка>, <Длина>, <Многострочность>)

Исправляем как есть или приводим к оригиналу?

**Comment by EvilBeaver** [comment]
Я бы предложил не поддерживать многострочность, т.к. не совсем понятно, как ее организовать в консоли

**Comment by Mr-Rm** [comment]
Для многострочности - считывать строки, пока не конец файла (в консоли для Windows - ^Z , для Linux - ^D)
Еще, наверное, и для однострочного, и для многострочного варианта по вводу пустой строки тоже возвращать `Истина`, а только для EOF (Console.ReadLine() вернуло null) - `Ложь`.

**Comment by EvilBeaver** [comment]
Можно, только мало кто знает про F6/^Z в консоли

**Comment by dmpas** [comment]
> 
> 
> Можно, только мало кто знает про F6/^Z в консоли

кто не знает, тот пусть не пользуется :)

**Comment by EvilBeaver** [comment]
Ну тогда давайте остановимся на этом

**Comment by EvilBeaver** [comment]
@Mr-Rm я хочу начать выпуск релиза 1.6. Могу я надеяться на исправление этой задачи в 1.6?

**Comment by Mr-Rm** [comment]
_"Doufat, neustále doufat"_

При многострочном вводе конвейером из файла: если длина ввода ограничена, то следует ли считывать всё, а затем обрезать до нужной длины или читать построчно, пока не превышен лимит, а затем прекращать ввод (возможно, до следующего `ВвестиСтроку()`)? 

Внесённое исправление ломает совместимость, но кто-нибудь использовал эту функцию раньше?

**Comment by EvilBeaver** [comment]
У нас конвеер не поддерживался никогда. Приложение не открывает stdin без команды. Думаю нужно релизовывать полноценные потоки, причем двоичные, а не текстовые, чтобы работать с конвеерами. Полагаю, этой функцией не пользовался никто. `ВвестиСтроку` что в 1С что в 1Скрипт подразумевало исключительно интерактивный ввод с клавиатуры

**Comment by Mr-Rm** [comment]
> Приложение не открывает stdin без команды

Так `ВвестиСтроку()` читает из консоли, т.е. из stdin. Вопрос был про случай

**oscript.exe somescript.os < very_long_input_file.txt**

когда в скрипте есть `ВвестиСтроку(СтрокаДляВвода, Подсказка,  ОченьКороткаяДлина, Истина)`, причём с повтором.

(Подсказка, как и `Сообщить()`, пишется в stdout, а способа писать в stderr, кажется, нет?)

**Comment by EvilBeaver** [comment]
Я понял вопрос. Этот сценарий через ВвестиСтроку не поддерживаем. stderr да, не пишется
