### ISSUE TITLE
Некорректный разбор аргументов командной строки

### ISSUE THREAD

**Issue by Morkhe** [EvilBeaver/OneScript#1072]
**Опишите ошибку**
В скрипт внешней системой передается в качестве аргумента путь к файлу, обрамленный в кавычки и заканчивающийся слэшем. При разборе аргументов слэш с кавычкой воспринимается как экранированный символ.

**Воспроизведение ошибки**
1. Запустить код ...
2. Подать на вход параметры `"C:\temp\" Вася`
3. В массиве АргументыКоманднойСтроки будет 1 элемент `C:\temp\" Вася`

**Ожидаемое поведение**
В массиве АргументыКоманднойСтроки должно быть 2 элемена `C:\temp\` `Вася`

**Окружение**
 - ОС: Win2012
 - Версия: 1.4.0.177

**Дополнительная информация**
Возможно связано с https://github.com/EvilBeaver/OneScript/issues/139

**Comment by nixel2007** [comment]
Дайте пример кода, пожалуйста.

**Comment by Morkhe** [comment]
Нуу, кода как такового нет. Есть запуск скрипта из git extension
```
Command: C:\Program Files\OneScript\bin\oscript.exe
Argument: -encoding=utf-8 ФайлСкрипта.os load {WorkingDir} -d {sHash} {cHash}
```

В `{WorkingDir}` подставляется путь к репозиторию со слэшем в конце.
В самом скрипте в коллекции `АргументыКоманднойСтроки `приходит вот такое
![image](https://user-images.githubusercontent.com/24790188/113895951-25eac000-97d2-11eb-8faf-f0d3d86d3bfe.png)

**Comment by nixel2007** [comment]
А, тогда это претензия не к оскрипту, а к терминалу, в котором вы запускаете скрипт. Оскрипт сам по себе ничего не экранирует и не вырезает, аргументы такими к нему приходят уже от командного процессора, который воспринимает бэкслэш как экранирующий символ. Используйте прямые слеши или следите за концевыми бэкслешами

**Comment by Morkhe** [comment]
При запуске отладки через VSC точно такая же проблема, кстати. Хотя туда аргументы как массив передаются вроде бы -.-

**Comment by nixel2007** [comment]
Они все равно склеиваются в единую строку при запуске приложения :)

**Comment by EvilBeaver** [comment]
Экранирование кавычек делает консоль. Внутри 1скрипта `\"` не обрабатывается

**Comment by artbear** [comment]
все уже высказались, но дополню слегка - 
в винде фактически нельзя юзать слеш в конце параметра в кавычках, т.к. консоль съест

я в ванесса-раннер даже добавлял спец.код для быстрого отлова таких ошибок еще до запуска 1С

**Comment by Morkhe** [comment]
Понял, спасибо
