### ISSUE TITLE
Параметр КодировкаТекста в виде строки

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1076]
_... или все ли особенности платформы стоит учитывать?_

Многие функции работы с текстовыми данными имеют параметр `Кодировка`, который может быть либо перечислением `КодировкаТекста`, либо строкой с названием кодировки. Во втором случае OneScript полагается на системную функцию `System.Text.Encoding.GetEncoding()`,  список допустимых значения для которой не совпадает со списком 1С. И с этим, видимо, ничего не сделать. Но есть и существенные различия в правилах разбора имён кодировок. В OneScript требуется строгое совпадение строки с допустимым именем кодировки. В 1С возможны разные варианты:
_(во всех перечисленных ниже случаях OneScript падает с внешним исключением System.ArgumentException)_
```bsl
ЧтениеТекста = Новый ЧтениеТекста(ИмяФайла,"UTF8");
``` 
Ок, можно и без дефиса.

```bsl
ЧтениеТекста = Новый ЧтениеТекста(ИмяФайла,""); // пустая строка
```
Ок, используется кодировка по-умолчанию (UTF-8). Вот это, наверное, можно повторить в OneScript.

```bsl
ЧтениеТекста = Новый ЧтениеТекста(ИмяФайла," "); // только пробел
```
Ошибка: Неправильное имя кодировки.

```bsl
ЧтениеТекста = Новый ЧтениеТекста(ИмяФайла," UTF-8 "); // пробелы до и после имени
``` 
Ок. Тоже логично, можно учесть.

И странное:
```bsl
ЧтениеТекста = Новый ЧтениеТекста(ИмяФайла,"UTF-16, а может, UTF-8?"); // UTF-16, всё после запятой игнорируется
ЧтениеТекста = Новый ЧтениеТекста(ИмяФайла,","); // только запятая: ошибка
ЧтениеТекста = Новый ЧтениеТекста(ИмяФайла,"!#U%&'(t)*-./:F;?@1{|6}~");  // UTF-16 ! No comments
ЧтениеТекста = Новый ЧтениеТекста(ИмяФайла,"§¤» UTF-16");  // ошибка, не ASCII не пройдёт
``` 
Итак, предлагается изначально пустую строку рассматривать как кодировку по-умолчанию, после чего удалять пробелы вокруг имени.

**Comment by EvilBeaver** [comment]
С пустой строкой дело хорошее, в остальных случаях я не уверен, что овчинка стоит выделки. Скольким людям это реально понадобится?

**Comment by EvilBeaver** [comment]
У меня подозрение, что 1С просто прокидывает имя кодировки в библиотеку ICU, а она уже делает из "!#U%&'(t)*-./:F;?@1{|6}~" строку UTF-16. Но это так, размышление вслух...

**Comment by Mr-Rm** [comment]
Про ICU, похоже, верно. Тогда выходит, что .NET не поддерживает [Unicode Technical Standard #22](https://www.unicode.org/reports/tr22/tr22-8.html#Charset_Alias_Matching)
