### ISSUE TITLE
Ошибка "Новый ДвоичныеДанные(Путь)" для файлов более 2 Гб

### ISSUE THREAD

**Issue by 240596448** [EvilBeaver/OneScript#1080]
Код: ".... = Новый ДвоичныеДанные(ПутьКФайлу);"
Ошибка: "Внешнее исключение (System.OverflowException): Измерения массива превысили поддерживаемый диапазон.}"

Проверено на
 - ОС: windows10 x64
 - Версия onescript:  1.5.0.178 x64

**Comment by EvilBeaver** [comment]
Это связано с #598

**Comment by EvilBeaver** [comment]
В качестве обходного маневра предлагаю воспользоваться Потоками для работы с данными.

**Comment by arkuznetsov** [comment]
> В качестве обходного маневра предлагаю воспользоваться Потоками для работы с данными.

Так и сделал.
