### ISSUE TITLE
[BUG] обновление пакетов удаляет плагины add

### ISSUE THREAD

**Issue by sulfur17** [EvilBeaver/OneScript#1081]
**Опишите ошибку**
Выполняю команду "opm u -a" и все мои дополнительные плагины из папки add/plugins удаляются

**Воспроизведение ошибки**
1. В папку OneScript\lib\add\plugins\ добавляем любой файл
2. В cmd выполняем команду opm u -a
3. Увидеть что наш файл исчез

**Ожидаемое поведение**
Файлы должны остаться на месте

**Окружение**
 - ОС: Win10x64
 - Версия: 1.0.2

**Comment by nixel2007** [comment]
vanessa-add при установке очищает собственный каталог, это заложенное поведение. Собственные плагины следует располагать в отдельном каталоге, например, в репозитории вашего проекта.

**Comment by sulfur17** [comment]
Разве? Я в коде OneScript\lib\add\xddTestRunner.epf в процедуре ЗагрузитьПлагины формы УправляемаяФорма вижу что плагины берутся строго из "plugins/"
@artbear куда в add пользовательские плагины класть?

**Comment by asosnoviy** [comment]
Это же ихуз либо в опм либо в адд, но точно не в оскрипт =)

**Comment by sulfur17** [comment]
ок, создал в opm https://github.com/oscript-library/opm/issues/196
