### ISSUE TITLE
ХешированиеДанных не работает с ПотокВПамяти или ФайловыйПоток

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1083]
**Опишите ошибку**
`ХешированиеДанных.Добавить(Поток)` падает с ошибкой, если `Поток` имеет тип `ПотокВПамяти` или `ФайловыйПоток`

**Воспроизведение ошибки**
1. Запустить код
```bsl
  // БДД = ПолучитьБуферДвоичныхДанныхИзСтроки("123"); // функция не реализована
  БДД = ПолучитьБуферДвоичныхДанныхИзHexСтроки("313233");
  Поток = новый ПотокВПамяти();
  Поток.Записать(БДД, 0, 3);
  Поток.Перейти(0,ПозицияВПотоке.Начало);
  ХД = новый ХешированиеДанных(ХешФункция.MD5);
  ХД.Добавить(Поток);
  Cообщить(ХД.ХешСумма);
```
2. Увидеть ошибку
_Ошибка в строке: 7 / Неверный тип аргумента}

**Ожидаемое поведение**
Вывод: _20 2C B9 62 AC 59 07 5B 96 4B 07 15 2D 23 4B 70_

**Дополнительная информация**
То же для `Поток=новый ФайловыйПоток(...)`
Вызов `ХД.Добавить(Поток.ПолучитьПотокТолькоДляЧтения());` работает, т.к. добавляется значение типа `Поток`.
В 1С таким образом проявляется подобие наследования?

**Comment by Chipazawra** [comment]
Можно на меня заасайнить
