### ISSUE TITLE
Аннотация после #Область - Недопустимые символы в директиве

### ISSUE THREAD

**Issue by asosnoviy** [EvilBeaver/OneScript#1087]
**Опишите ошибку**
Если первый метод в Области содержит аннотацию то получаем ошибку 
`Недопустимые символы в директиве`

```bsl
#Область Первая

&Аннотация
Процедура Метод()

КонецПроцедуры

#КонецОбласти
```

**Окружение**
 - ОС: Microsoft Windows [Version 10.0.19042.985]
 - Версия: 1.6.0.213

**Comment by asosnoviy** [comment]
отработает нормально
```bsl
#Область Первая

Процедура Метод2()

КонецПроцедуры


&Аннотация
Процедура Метод()

КонецПроцедуры

#КонецОбласти
```

**Comment by Mr-Rm** [comment]
Сломалось при исправлении препроцессора.
Быстрая заплатка есть, но надо бы дополнительно уточнить синтаксис аннотаций.
Аннотация сейчас - лексема из двух слитных токенов (причина ошибки), поэтому
```bsl
& Аннотация
Процедура Метод()
КонецПроцедуры
``` 
– не компилируется. Но при этом допускается создание безымянных аннотаций, в том числе с параметрами:
```bsl
& ("Параметр") // ок
Процедура Метод2()
КонецПроцедуры
```
Должна ли каждая аннотация начинаться на новой строке?
Должны ли параметры аннотаций располагаться полностью на той же строке, что и её имя?
Сейчас  разрешаются одинаковые имена аннотаций для одного объекта или одинаковые имена параметров для одной аннотации. Это правильно?

_На странице https://oscript.io/docs/page/annotations есть ошибки_

**Comment by nixel2007** [comment]
> Должна ли каждая аннотация начинаться на новой строке?

Нет.

> Должны ли параметры аннотаций располагаться полностью на той же строке, что и её имя?

Не хотелось бы иметь такое ограничение.

> Сейчас разрешаются одинаковые имена аннотаций для одного объекта или одинаковые имена параметров для одной аннотации. Это правильно?

Первое - да, нормально. Второе - не уверен, что правильно , но такое поведение может быть полезно для параметров-массивов. @dmpas?

**Comment by nixel2007** [comment]
> Но при этом допускается создание безымянных аннотаций, в том числе с параметрами:

А вот это странно... Кажется, это какое-то не запланированное поведение

**Comment by dmpas** [comment]
> Сейчас разрешаются одинаковые имена аннотаций для одного объекта или одинаковые имена параметров для одной аннотации. Это правильно?

такое поведение было заложено, да. Насчёт "правильно" - тут хз, нет на это "правила" ни у нас, ни у Мамки

**Comment by EvilBeaver** [comment]
Множественные аннотации должны быть, мы их закладывали

**Comment by Mr-Rm** [comment]
Отложим пока множественные имена. Надо определиться с работой лексера.
Сейчас имя аннотации (если оно есть!) должно быть строго слитно с предшествующим '&'. 
С другой стороны, компилируется следующее:
```bsl
&Аннотация1
&("Параметр")
&&
&Аннотация2 & Процедура Метод() 
КонецПроцедуры 
```
В результате имеем у Метода 6 аннотаций с именами: "Аннотация1", "(", "&", `Символы.ПС`, "Аннотация2", " " (пробел).
Поменяв местами 2-ю и 3-ю строку, получаем ошибку:
_Модуль G:\OneScript\issue1087.os / Ошибка в строке: 3,13 / Неизвестная операция}    
&("Параметр")_

В аналогичных конструкциях 1С допускает пробельные символы:
```bsl
& НаКлиенте
// или даже на новой строке:
&
НаКлиенте
```

**Comment by nixel2007** [comment]
Аннотаций без имён точно не должно быть.
А вот в чем проблема с пробелами я не совсем понимаю.

**Comment by EvilBeaver** [comment]
Нет, между & и именем аннотации не должно быть пробелов, на мой взгляд. Хотя, если в 1С так, наверное из соображений совместимости нам тоже надо бы так сделать. А вот аннотации && и &() - это баги, это не несет смысла.
