### ISSUE TITLE
Не работает ИнтернетПрокси в Linux

### ISSUE THREAD

**Issue by RedMammoth** [EvilBeaver/OneScript#1110]
Ошибки при работе с объектом ИнтернетПрокси в linux.

1. Под linux не работает создание прокси по-умолчаию:
   
   ```
   Новый ИнтернетПрокси(Истина);
   ```
   
   **Ожидаемое поведение**
   Согласно описанию в синтаксис-помощнике 1с, для linux ПроксиПоУмолчанию создается из переменных окружения http_proxy, https_proxy и т.д.
   Если переменные не удалось разобрать, то исключения не возникает.

   **Окружение**
   - ОС: Ubuntu 20.04 LTS
   - Версия: 1.6

2. Под linux не работает basic авторизация, при установке ручных настроек для ИнтернетПрокси
   
   ```
   Прокси = Новый ИнтернетПрокси(Ложь);
   Прокси.Установить("http", "server", 8080, "user", "password", Ложь);
   Прокси.Установить("https", "server", 8080, "user", "password", Ложь);   
   ```
   Запрос возвращает код 407

   **Ожидаемое поведение**
   Согласно описанию в синтаксис-помощнике 1с, если при устновке прокси заданы пользователь и пароль, а поле ИспользоватьАвторищациюОС = Ложь,
   то используется не NTLM, а Basic авторизация.

   **Окружение**
   - ОС: Ubuntu 20.04 LTS
   - Версия: 1.6

**Comment by RedMammoth** [comment]
@EvilBeaver, привет!

Тест, который проверяет авторизацию прокси, оставляет дефолтное значение ИспользоватьАутентификациюОС равное Истиной:

```
Процедура ТестДолжен_ПроверитьАвторизациюПрокси() Экспорт

	Прокси = Новый ИнтернетПрокси();

	Прокси.Установить("http","proxy.server.lan", 8080, "someuser", "somepassword");
	
	юТест.ПроверитьРавенство("someuser",Прокси.Пользователь("http"));
	юТест.ПроверитьРавенство("somepassword",Прокси.Пароль("http"));

КонецПроцедуры
```

С одной сторны в 1с он выполнится, но если использовать сам объект ИнтернетПрокси с такими настройками,
то пользователь и пароль проигнорируется и выполнится NTLM авторизация.

Если я правильно понимаю, то Пользователь и Пароль имеют смысл только когда используется basic авторизация, которая включается если установить ИспользоватьАутентификациюОС в ложь:
```Прокси.Установить("http","proxy.server.lan", 8080, "someuser", "somepassword", Ложь);```
(В таком случае тест пройдет).

Т.к. свойства Пользователь и Пароль признаны устаревшими, а установка авторизации и прочих настроек прокси производится через метод Установить, который заменяет
все настройки для схемы, то я реализовал класс без использования ProxySettings. Метод Установить создает новый IWebProxy, согласно аргументов, и кладет в словарь _proxies.

Вопрос, как лучше поступить:
поправить реализацию и хранить всегда Пользователь и Пароль, даже если используется аутентификация ОС
или оставить хранение только для Basic авторизации и добавить в тест ИспользоватьАутентификациюОС = Ложь.

**Comment by EvilBeaver** [comment]
Спасибо за разбор. Я не знаю как правильнее поступить, у меня нет опыта в разнообразных комбинациях настроек проксей. Буду рад, если мне и самому кто-то расскажет, например, Вы.

В общем случае, думаю стоит ориентироваться на поведение 1С. И если оно по какой-то причине некорректное - сделать корректно.

**Comment by RedMammoth** [comment]
У меня тоже нет опыта, столкнулся с проблемой на работе и начал разбирать. Я сейчас пробую написать тест для basic авторизации. Пока идея такая:
внутри тестирующих контейнеров запустить два небольших контейнера объединенных единой сетью, с статическими IP адресами:
1. простой прокси сервер с basic авторизацией, например squid
2. примитивный веб-сервер, который на get запрос отдает ip-адрес клиента

Затем в тестовой процедуре делать запрос к веб-серверу и проверять, что в ответе ip-адрес прокси-сервера.
Т.к. я новичок в настройке jenkins, docker и т.д. Подскажите, пожалуйста, жизнеспособна ли эта идея, или искать что-то другое.

**Comment by nixel2007** [comment]
> Т.к. я новичок в настройке jenkins, docker и т.д. Подскажите, пожалуйста, жизнеспособна ли эта идея, или искать что-то другое.

жизнеспособна, но надо будет подключить тест-контейнер в режиме docker-in-docker с пробросом сокета или использовать подход с sidecar containers: https://www.jenkins.io/doc/book/pipeline/docker/#running-sidecar-containers

**Comment by RedMammoth** [comment]
Хоршо, спасибо, буду пробовать
