### ISSUE TITLE
ЧтениеДанных / ЗаписьДанных должны работать с беззнаковыми целыми

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1115]
**Опишите ошибку**
Для объекта `ЧтениеДанных` метод `ПрочитатьЦелое16()` и для объекта `ЗаписьДанных` методы `ЗаписатьЦелое16()`, `ЗаписатьЦелое32()`, `ЗаписатьЦелое64()` должны работать с беззнаковыми целыми числами.

**Воспроизведение ошибки**
```bsl
Буфер = ПолучитьБуферДвоичныхДанныхИзHexСтроки("FDFF");
Поток = Новый ПотокВПамяти(2);
Поток.записать(буфер,0,2);
Поток.Перейти(0,ПозицияВПотоке.Начало);
ЗД=новый ЧтениеДанных(Поток);
Рез=ЗД.ПрочитатьЦелое16();
Сообщить(Рез);
Поток.Перейти(0,ПозицияВПотоке.Начало);
ЗД=новый ЗаписьДанных(Поток);
ЗД.ЗаписатьЦелое16(65533);
```
вывод:
_-3
Ошибка в строке: 10 / Внешнее исключение (System.OverflowException): Value was either too large or too small for an Int16.}_
**Ожидаемое поведение**
вывод:
_65533_
без ошибок

**Дополнительная информация**
Глобально, нужна строгая типизация (см.#1113), причём, похоже, для всех объектов, введённых с версии 8.3.9.

**Comment by EvilBeaver** [comment]
Но это вроде косяк именно реализации `ЗаписатьЦелое16(65533)`. Она трактует вход, как знаковое, а должна как беззнаковое, не?

**Comment by EvilBeaver** [comment]
С другой стороны, кто сказал, что невозможен вызов `ЗаписатьЦелое16(-32768)`?

**Comment by Mr-Rm** [comment]
Спецификация:
> Значение числа должно находиться в диапазоне от 0 до 65535

Можно, конечно, сделать и диапазон -2^(n/2) . . 2^n-1

**Comment by EvilBeaver** [comment]
Не, раз спека есть, то прекрасно. Спасибо!
