### ISSUE TITLE
Ошибка после обновления на версию 1.5+

### ISSUE THREAD

**Issue by Arti4k** [EvilBeaver/OneScript#1117]
**Опишите ошибку**
После установки gitsync, запускаю команду gitsync получаю ошибку {Модуль C:\OneScript\lib\gitsync\src\core\Классы\internal\Классы\ПодключениеПлагиновКаталога.os / Ошибка в строке: 73 / Внешнее исключение (OneScript.Language.SyntaxErrorException): {Модуль C:\Users\user\AppData\Local\gitsync\plugins\gitsync-plugins\src\Классы\smartTags.os / Ошибка в строке: 298,1 / Ожидается завершение директивы препроцессора #Область}
}

**Окружение**
 - ОС: win10
 - Версия:  Version 1.6.0.213, 1.7

**Comment by arkuznetsov** [comment]
Надо вручную удалить каталог плагинов gitsync и выполнить инициализацию плагинов заново.

**Comment by EvilBeaver** [comment]
Да, в 1.6 исправили ошибку синтаксиса, а в гитсинке она как раз была
