### ISSUE TITLE
Особенности работы функций Символ и КодСимвола

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1124]
**Опишите ошибку**
1. Функция `Символ` для кодов, больших 65535 или меньших 0, возвращает строку, содержащую символ с кодом, равным заданному **по модулю 2^16**. 1С в таком случае возвращает пустую строку.
2. Если в функцию `КодСимвола` передаётся второй параметр (НомерСимвола) со значением, большим длины строки либо нулевым или отрицательным, а также если длина строки нулевая, а 2-го параметра нет, то выбрасывается исключение _"Неверное значение аргумента"_. 1С возвращает **-1**.

**Воспроизведение ошибки**
```bsl
Cтр = Символ(65859);
Сообщить("Длина="+СтрДлина(Стр));
Сообщить("Код="+КодСимвола(Стр));
Сообщить("Код вне строки="+КодСимвола(Стр,10));
```
Вывод OneScript:
_Длина=1
Код=323
{Модуль S:\OneScript\tst-char.os / Ошибка в строке: 4 / Неверное значение аргумента}_

Вывод 1C:
_Длина=0
Код=-1
Код вне строки=-1_

**Ожидаемое поведение**
Делать совместимо? Или подумать, как будет правильней?

**Comment by EvilBeaver** [comment]
Лучше сделать совместимо
