### ISSUE TITLE
Ругается на "недопустимые символы в директиве", указывая строку, не соответствующую строке директивы

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#1130]
( По мотивам #1087 ) Ругается на "недопустимые символы в директиве", указывая строку, не соответствующую строке директивы.

Берём код:
```bsl
#Если Условие Тогда
Ф=1;
#Иначе
Ф=2;
#КонецЕсли
```
Кладём код в файл, ставим окончания строк `LF`, отдаём файл оскрипту, ловим ошибку
```
{Модуль preproc-failure.os / Ошибка в строке: 3,0 / Недопустимые символы в директиве}
```
Движок 2.0
[preproc-failure.txt](https://github.com/EvilBeaver/OneScript/files/7232086/preproc-failure.txt)

**Comment by EvilBeaver** [comment]
@dmpas я же правильно понимаю, что это исправлено в d6b52f6fb6?

**Comment by dmpas** [comment]
@EvilBeaver пощёлкал - вроде работает.
