### ISSUE TITLE
Конструктор ОписаниеТипов не воспринимает КвалификаторыДаты: ДатаВремя

### ISSUE THREAD

**Issue by aleksandr-ermakov** [EvilBeaver/OneScript#1133]
**Опишите ошибку**
При создании класса ОписаниеТипов для Даты, полученный тип не содержит время, даже при явном указании в квалификаторе.

**Воспроизведение ошибки**
```bsl
ОписаниеТипаДатаВремя = Новый ОписаниеТипов("Дата", ,,,, Новый КвалификаторыДаты(ЧастиДаты.ДатаВремя)); 
Сообщить(ОписаниеТипаДатаВремя.КвалификаторыДаты.ЧастиДаты);     // Дата

ОписаниеТипаДатаВремя = Новый ОписаниеТипов("Дата");
Сообщить(ОписаниеТипаДатаВремя.КвалификаторыДаты.ЧастиДаты);     // Дата
```

**Ожидаемое поведение**
В платформе в обоих случаях будет "Дата и время"

**Окружение**
 - ОС: Win 10 Версия 10.0.19042 Сборка 19042
 - Версия: 1.7.0

**Comment by dmpas** [comment]
```
ОписаниеТипаДатаВремя = Новый ОписаниеТипов("Дата", ,,,, Новый КвалификаторыДаты(ЧастиДаты.ДатаВремя)); 
Сообщить(ОписаниеТипаДатаВремя.КвалификаторыДаты.ЧастиДаты);     // Дата
```

Вот этот вариант в 1С тоже не должен работать. Он работает, но по факту видим недокументированное поведение: в 1С вызывается конструктор "На основании объекта ОписаниеТипов" (видимо исходя из количества параметров), который однако первым параметром требует ОписаниеТипов, а не строку.

Оскрипт первым параметром видит строку и идёт по пути второго конструктора, "На основании типов и квалификаторов". Так что я бы тут крепко подумал, а нужна ли нам тут такая совместимость.

А вторая часть кода - косяк однозначно. Значение по-умолчанию в ОСкрипте не равно 1С. Удивительно, что до сих пор не выплывало.

**Comment by Mr-Rm** [comment]
В 1С ещё и не проверяется точное соответствие типов Квалификаторов позиции параметра.
```bsl
ОписаниеТипаВремя = Новый ОписаниеТипов("Дата",Новый КвалификаторыДаты(ЧастиДаты.Время)); 
```
\- работает, хотя правильно должно быть:
```bsl
ОписаниеТипаВремя = Новый ОписаниеТипов("Дата",,,Новый КвалификаторыДаты(ЧастиДаты.Время)); 
```

**Comment by dmpas** [comment]
ещё вот так:
```bsl
ОписаниеТипаВремя = Новый ОписаниеТипов("Дата",Новый КвалификаторыДаты(ЧастиДаты.Время), Новый КвалификаторыЧисла(10, 2), Новый КвалификаторыСтроки(10));
```

не работает, но и не ругается во время исполнения.

**Comment by EvilBeaver** [comment]
Окей, делаем-то что?

**Comment by dmpas** [comment]
@EvilBeaver Значение по-умолчанию однозначно фиксим.

А по поводу конструктора продолжаем бурлесрач: недокументированные возможности мы обычно ~~отметаем~~ оставляем на доработку страждущим

**Comment by Mr-Rm** [comment]
> 
> ещё вот так:
> ```bsl
> ОписаниеТипаВремя = Новый ОписаниеТипов("Дата",Новый КвалификаторыДаты(ЧастиДаты.Время), Новый КвалификаторыЧисла(10, 2), Новый КвалификаторыСтроки(10));
> ```
> не работает, но и не ругается во время исполнения.

Работает, `Сообщить(ОписаниеТипаВремя.КвалификаторыДаты.ЧастиДаты);` -> _Время_

Плохо, что работает вот так :
```bsl
// Квалификатор 'Время' на своей позиции:
ОписаниеТипаВремя = Новый ОписаниеТипов("Дата",,,Новый КвалификаторыДаты(ЧастиДаты.Время), Новый КвалификаторыДаты(ЧастиДаты.Дата));
Сообщить(ОписаниеТипаВремя.КвалификаторыДаты.ЧастиДаты);
```
-> _Дата_ , т.е. последний по порядку для данного типа.
Баг платформы, по 8.3.20.1590 включительно.

@EvilBeaver
>Окей, делаем-то что?

Второй случай - исправлять. 
С параметрами - приводить в соответствие либо с описанием (наверное, будет правильней; там и TODO в `TypeDescription.cs` висит), либо с поведением (или дожидаться исправления платформы или документации?)

**Comment by dmpas** [comment]
> Работает

@Mr-Rm в части Даты да, в части Числа и Строки квалификаторы не учитываются

**Comment by Mr-Rm** [comment]
Так нет же типов для Числа и Строки. А если так:
```bsl
ОписаниеТипов = Новый ОписаниеТипов("Строка,Дата,Число",
   Новый КвалификаторыДаты(ЧастиДаты.Время), 
   ,,, // !
   Новый КвалификаторыЧисла(11, 2),
   Новый КвалификаторыСтроки(7));
Сообщить(ОписаниеТипов.КвалификаторыЧисла.Разрядность);
Сообщить(ОписаниеТипов.КвалификаторыСтроки.Длина);
Сообщить(ОписаниеТипов.КвалификаторыДаты.ЧастиДаты);
```
_11
7
Время_
Всё учитывается. И получается, что конструктор фактически один.
Но выяснять поведение проверками, когда есть документация - а где? или её нет? -  как-то неправильно.

**Comment by EvilBeaver** [comment]
Поскольку у нас квалификаторы считай что не используются, предлагаю исправить то что явно неверно, а на недокументированные фичи платформы - забить

**Comment by dmpas** [comment]
@EvilBeaver Используюся в таблице значений и дереве. Но кто этим на самом деле пользуется, сложно сказать. Вот, первая досада за столь продолжительное время.

**Comment by dmpas** [comment]
@Mr-Rm всё забавнее и забавнее.
