### ISSUE TITLE
Метод Сообщить( ) в разных терминалах использует разную кодировку и отличается от Консоль.ВывестиСтроку( )

### ISSUE THREAD

**Issue by 240596448** [EvilBeaver/OneScript#1134]
Проблемное поведение на скрине:
https://t.me/oscript_library/50297
![image](https://user-images.githubusercontent.com/35220983/140658267-697306fc-6913-4e2f-9bcf-59eeac025f6b.png)

1. Кодировка в методе сообщить в разных терминалах выводится по разному.
2. Кодировка в выводе в консоль не зависит от опции `-encoding=`

Независимо воспроизводилось на разных виндос-машинах.
vscode и gitscm - обновленные
onescript 1.4-1.7

**Comment by 240596448** [comment]
Дополню по ситуации разного вывода кодировок в "разных терминалах"...

Если выбрать при установке параметр "Use Windows default console window", то поведение в vscode и git-bash будет идентичным.
![image](https://user-images.githubusercontent.com/35220983/140664354-ce80ce8a-b1cd-47e3-b04a-43491af94e82.png)

Т.е. vscode всегда запускает консоль с некими виндовыми настройками, отсюда проблема.

**Comment by EvilBeaver** [comment]
1. Ключ -encoding влияет на любой вывод движка, кроме прямого доступа к консоли (поэтому консоль его игнорирует)
2. Консоль использует системную кодировку, какую дала ОС. Поэтому в разных терминалах это по разному
3. Кажется, что не надо без нужды использовать ключ --encoding, если нужна кодировка системной консоли, т.к. этот ключ как раз игнорит настройку консоли и заставляет 1скрипт писать текст в заданной кодировке, а не в кодировке системы

В качестве фикса могу предложить такое изменение, что класс Консоль тоже будет смотреть на ключ --encoding

@240596448 не очень понимаю, какое поведение Вами ожидается, как корректное?

**Comment by 240596448** [comment]
Вообще, я начал копаться в консолях из-за вывода opm в bash-консоли vscode кракозябрами.
Уже после обратил внимание на расхождения в поведении в разных консолях и разным способом вывода.

Пункты 1 и 2 - понятны.
Ожидаемое поведение - отсуствие кракозябр  ;).

С пунктом 3 (_не надо без нужды использовать ключ --encoding_) - полностью согласен. Вопрос нужно адресовать в `opm`. Именно из-за добавления ключа с utf-8 в скрипт запуска приложений/библиотек под линукс и возникает проблема в виндовых bash-терминалах.
С ключем - проблема в vscode (он запускает bash-термнал как виндовс консоль c cp866).
Без ключа - вроде везде корретно работает. ps, cmd, gitbash, gitcmd (и открывания одно из другого), ubuntu. Cygwin - не юзаю.

@nixel2007 говорит, что наоборот это решало какие-то проблемы... Вопрос в каких случаях?

**Comment by 240596448** [comment]
_В качестве фикса могу предложить такое изменение, что класс Консоль тоже будет смотреть на ключ --encoding_

Острой необходимости нету. Но возможно, унификация поведения - это неплохая идея.

**Comment by EvilBeaver** [comment]
Ключ как раз да, решал проблемы, когда нужно было выводить именно в конкретной кодировке, а не системной. Например, в лог дженкинса или в консоль vscode. Поэтому, кракозябры при использовании ключа - это как раз не баг, а фича. Кодировка жестко прибивается гвоздем, а то, что консоль ее не может прочесть - это дело десятое.

**Comment by nixel2007** [comment]
> Именно из-за добавления ключа с utf-8 в скрипт запуска приложений/библиотек под линукс и возникает проблема в виндовых bash-терминалах.

уточню. encoding добавляется только в sh-скриптах, генерируемых для винды. на линуксе encoding не добавляется.

**Comment by 240596448** [comment]
В причинах поведения кодировок разобрался. 
Консоль пусть будет как есть.
Закрою.
