### ISSUE TITLE
Отсутствует итератор по перечислениям

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1138]
Отсутствует итератор по перечислениям

**Воспроизведение ошибки**
- Запустить код
```bsl
Для Каждого элем из ЧастиДаты  Цикл
	Сообщить("ЧастиДаты:"+элем);
КонецЦикла;
```
- Увидеть ошибку
_{Модуль S:\OneScript\tst-enum.os / Ошибка в строке: 1 / Итератор не определен}_

**Ожидаемое поведение**
Вывод
_ЧастиДаты:Дата
ЧастиДаты:Время
ЧастиДаты:Дата и время_

**Дополнительная информация**
Не работает для любого перечисления.

**Comment by Mr-Rm** [comment]
После применения исправления выводится:
_ЧастиДаты:Дата
ЧастиДаты:ДатаВремя
ЧастиДаты:Время_

Проблемы:
1. Порядок элементов перечисления не совпадает с платформой. Нужно проверять для **всех** перечислений.
2. Строковые представления всегда совпадают с идентификаторами, а в платформе имеются читаемые (`ДатаВремя` -> `"Дата и время"`).
3. Всегда используется только русское представление, вне зависимости от локали.

Предполагаю 1-е править, 2-е нет, 3-е - ??

**Comment by EvilBeaver** [comment]
Третье тоже не править. Практически нигде у нас локаль не привязана к свойствам и методам языка

**Comment by EvilBeaver** [comment]
@Mr-Rm может для начала просто сделаем наличие итераторов, а потом уже подгонять, если потребуется?

**Comment by EvilBeaver** [comment]
@Mr-Rm а это мы разве еще не влили в dev?

**Comment by Mr-Rm** [comment]
Нет, последний PR #1159 не вливали. А предыдущий был отменен из-за возникших проблем.
