### ISSUE TITLE
ПолучитьДвоичныеДанныеИзСтроки ЗаписатьBOM

### ISSUE THREAD

**Issue by ilyabaztard** [EvilBeaver/OneScript#1140]
**Опишите ошибку**
Функция ПолучитьДвоичныеДанныеИзСтроки игнорирует параметр ЗаписатьBOM

**Воспроизведение ошибки**
1. Запустить код 
``` bsl
Сообщить(ПолучитьДвоичныеДанныеИзСтроки("123", КодировкаТекста.UTF8, Ложь));
Сообщить(ПолучитьДвоичныеДанныеИзСтроки("123", КодировкаТекста.UTF8, Истина));
```
2. Результат выполнения кода
```
31 32 33
31 32 33
```

**Ожидаемый результат выполнения кода**
```
31 32 33
EF BB BF 31 32 33
```

**Окружение**
 - ОС: Win 10 pro 1909
 - Версия: oscript 1.7.0

**Дополнительная информация**
Параметр ЗаписатьBOM определяет, будет ли добавлена метка порядка байт (BOM) кодировки текста в начало данных.
Для кодировки UTF8 должны быть добавлены байты EF BB BF
Прочие описаны здесь [википедия](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%80%D0%BA%D0%B5%D1%80_%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%B1%D0%B0%D0%B9%D1%82%D0%BE%D0%B2)

**Comment by EvilBeaver** [comment]
В качестве обхода возьмите кодировку `КодировкаТекста.UTF8БезBOM` ее нет в 1С, а у нас появилась намного раньше, чем 1С добавила параметр ЗаписатьBOM. Отсюда и расхождение

**Comment by Mr-Rm** [comment]
Проблема в том, что в .NET `byteOrderMark`=true не добавляет BOM автоматически:

_To ensure that the encoded bytes are decoded properly, you should prefix the beginning of a stream of encoded bytes with a preamble. Note that the GetBytes method does not prepend a BOM to a sequence of encoded bytes; supplying a BOM at the beginning of an appropriate byte stream is the developer's responsibility._

Но и поведение 1С тоже вызывает вопросы:
```bsl
Запись = Новый ЗаписьДанных("ExistingFile",,,,истина,,истина); // Дописать, с BOM
```
\- при последующей записи вставит  BOM **в конце** ExistingFile

**Comment by ilyabaztard** [comment]
> В качестве обхода возьмите кодировку `КодировкаТекста.UTF8БезBOM`

Мне нужна запись с добавлением BOM
Кроме того
``` bsl
Сообщить(ПолучитьДвоичныеДанныеИзСтроки("123", КодировкаТекста.UTF8));
Сообщить(ПолучитьДвоичныеДанныеИзСтроки("123", КодировкаТекста.UTF8БезBOM));
```
Результат выполнения кода
```
31 32 33
{Модуль C:\Data\oscript\test.os / Ошибка в строке: 2 / Свойство объекта не обнаружено (UTF8БезBOM)}
```

**Comment by bapho-bush** [comment]
> КодировкаТекста.UTF8БезBOM

Полагаю очепятка. В сорцах эта кодировка значится как UTF8NoBOM. 
![изображение](https://user-images.githubusercontent.com/30332279/142269027-3b3557a6-55c0-4adc-bb2b-8f59f7907c83.png)

**Comment by EvilBeaver** [comment]
@ilyabaztard прошу прощения, да, у нее нет русского аналога. Правильно - Utf8NoBOM
