### ISSUE TITLE
NullReferenceException при вызове конструктора с пропущенными параметрами

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1141]
**Опишите ошибку**
В некоторых случаях падает с NullReferenceException при вызове конструктора, если пропущен (или установлен в Неопределено) необязательный параметр.

**Воспроизведение ошибки**
```bsl
Zip = Новый ЗаписьZipФайла(ИмяФайла, , , , , , ); // пустой 7-й параметр
// если параметров 6 или меньше - работает:
Zip = Новый ЗаписьZipФайла(ИмяФайла, , , , ,);
```
**Дополнительная информация**
Падение происходит, если пропущен параметр, для которого в конструкторе указан тип - объект, отличный от `IValue`, и значение по умолчанию, не равное `null`.
Причина: такая ситуация не обрабатывается в `TypeFactory`.
Видится задача унифицировать вызов конструкторов и методов в `TypeFactory` и `ContextMethodMapper` соответственно. Появится возможность усилить типизацию.
_(Или отложить всё на v2?)_

**Comment by EvilBeaver** [comment]
в v2 своих задач хватает, лучше исправить в v1
