### ISSUE TITLE
ПолучитьСтрокуИзДвоичныхДанных

### ISSUE THREAD

**Issue by ilyabaztard** [EvilBeaver/OneScript#1142]
**Опишите ошибку**
Функция ПолучитьСтрокуИзДвоичныхДанных некорректно преобразует двоичные данные, предваряемые BOM

**Воспроизведение ошибки**
1. Запустить код 
``` bsl
лДвоичныеДанныеБезBOM = ПолучитьДвоичныеДанныеИзHexСтроки("313233");
лДвоичныеДанныеBOM = ПолучитьДвоичныеДанныеИзHexСтроки("EFBBBF313233");

лСтрока1 = ПолучитьСтрокуИзДвоичныхДанных(лДвоичныеДанныеБезBOM);
лСтрока2 = ПолучитьСтрокуИзДвоичныхДанных(лДвоичныеДанныеBOM);
Сообщить(лСтрока1);
Сообщить(лСтрока2);
Сообщить("Строки равны: " + (лСтрока1 = лСтрока2));
```
2. Результат выполнения кода
```
123
?123
Строки равны: Нет
```

**Ожидаемый результат выполнения кода**
```
123
123
Строки равны: Да
```

**Окружение**
 - ОС: Win 10 pro 1909
 - Версия: oscript 1.7.0

**Дополнительная информация**
Функция ПолучитьСтрокуИзДвоичныхДанных не должна преобразовывать маркер (BOM) в символ.

**Comment by nixel2007** [comment]
Эм. А почему они должны быть равны? Разве 1с их приравнивает?

**Comment by ilyabaztard** [comment]
Потому что первые 3 байта здесь "EFBBBF313233" это BOM. Преобразование в символы должно выполняться начиная с четвертого байта. И тогда в обоих случаях получается одинаковые строки.
1С так и делает.

**Comment by nixel2007** [comment]
>  Преобразование в символы должно выполняться

кем должно?

> 1С так и делает.

очень странное и нелогичное поведение. но раз 1с так делает, то и здесь имеет смысл хотя бы дать возможность сделать совместимо. хотя на мой взгляд явный метод skipBOM() (как в других языках) подошел бы лучше.

**Comment by ilyabaztard** [comment]
> кем должно?

Да никем не должно.

Однако есть стандарты [unicode.org](https://unicode.org/faq/utf_bom.html), которые определяют, что последовательность EFBBBF в начале потока является маркером, а содержательная часть начинается с четвертого байта. 
Кроме того, OneScript [декларирует](https://oscript.io/docs/page/language) совместимость поведения с 1С и ожидаемый результат выполнения кода соответствует поведению 1С

**Comment by EvilBeaver** [comment]
Никита говорил немного про другое, но вы все равно правы: если 1С пропускает БОМ то и нам стоит. Хотя, все тут определяет кодировка. Если читать байты (хоть и с EFBBBF в начале) но кодировкой ANSI, никакого пропуска BOM быть не должно. А вот при кодировке UTF8 (которую мы и 1С трактуем как "withBOM") надо бы пропустить.

**Comment by Mr-Rm** [comment]
> но кодировкой ANSI, никакого пропуска BOM быть не должно

У 1С своё мнение на этот счёт:
```bsl
лДвоичныеДанные1 = ПолучитьДвоичныеДанныеИзHexСтроки("FFEDE5FF");
лДвоичныеДанные2 = ПолучитьДвоичныеДанныеИзHexСтроки("FFFEE5FE");
Кодировка="windows-1251";
лСтрока1 = ПолучитьСтрокуИзДвоичныхДанных(лДвоичныеДанные1, Кодировка);
лСтрока2 = ПолучитьСтрокуИзДвоичныхДанных(лДвоичныеДанные2, Кодировка);
Сообщить("Строки равны: " + (лСтрока1 = "янея"));
Сообщить("Строки равны: " + (лСтрока2 = "яюею"));
```
_Строки равны: Да
Строки равны: Нет_

**Comment by ilyabaztard** [comment]
> У 1С своё мнение на этот счёт:

Провел следующий эксперимент
``` bsl
ДвДанные = ПолучитьДвоичныеДанныеИзHexСтроки("42A642A642A6"); // строка ꙂꙂꙂ в кодировке  UTF16 без BOM
Строка = ПолучитьСтрокуИзДвоичныхДанных(ДвДанные, КодировкаТекста.UTF16);
Сообщить(Строка);
> ꙂꙂꙂ
Строка = ПолучитьСтрокуИзДвоичныхДанных(ДвДанные, КодировкаТекста.ANSI);
Сообщить(Строка);
> B¦B¦B¦
Строка = ПолучитьСтрокуИзДвоичныхДанных(ДвДанные, КодировкаТекста.OEM);
Сообщить(Строка);
> BжBжBж
```
Теперь добавляем BOM в двоичные данные
``` bsl
ДвДанные = ПолучитьДвоичныеДанныеИзHexСтроки("FFFE42A642A642A6"); // строка ꙂꙂꙂ в кодировке  UTF16 c BOM
Строка = ПолучитьСтрокуИзДвоичныхДанных(ДвДанные, КодировкаТекста.UTF16);
Сообщить(Строка);
> ꙂꙂꙂ
Строка = ПолучитьСтрокуИзДвоичныхДанных(ДвДанные, КодировкаТекста.ANSI);
Сообщить(Строка);
> ꙂꙂꙂ
Строка = ПолучитьСтрокуИзДвоичныхДанных(ДвДанные, КодировкаТекста.OEM);
Сообщить(Строка);
> ꙂꙂꙂ
```
**Вывод**
Как только в двоичных данных появляется BOM, 1С игнорирует второй параметр и определяет кодировку самостоятельно по BOM

**Comment by Mr-Rm** [comment]
> Как только в двоичных данных появляется BOM, 1С игнорирует второй параметр и определяет кодировку самостоятельно по BOM

Ну так баг же.  Если кодировка явно указана, к тому же восьмибитная, то почему работа со строкой "яюэьыъ...." в начале данных  должна отличаться от работы с "абвгд..."?

**Comment by ilyabaztard** [comment]
Я бы так сказал.
Для языка общего назначения это был бы баг.
Для 1С, для которого родная кодировка UTF8 и на первое место поставлено правильное извлечение текста из двоичных данных, это скорее фича. В данных есть маркер, который явно указывает в какой кодировке представлен дальнейший текст, значит так и читаем, мало ли что там программист 1с указал.
Но я согласен, что логичнее было бы оставить за программистом возможность вторым параметром указать кодировку принудительно.

**Comment by Mr-Rm** [comment]
Итак, предложение такое:
- если при вызове функции указана кодировка, не предусматривающая BOM, то она и применяется к двоичным данным. Это несовместимо с 1С, но представляется более правильным;
- если указана unicode-кодировка, то начало данных проверяется на наличие BOM для UTF-8, UTF-16 и UTF-32. В случае найденного соответствия BOM пропускается, и последующие данные принимаются в этой кодировке, независимо от явно указанной. (Другие unicode-кодировки: UTF-7, X-ISO-10646-UCS-4 - не определяются). Если никакой BOM не найден, то используется кодировка, заданная параметром;
- если кодировка не задана, то применяется вариант как для указанной UTF-8.

Ошибки декодирования игнорируются, в строку записывается заменяющий символ ("?" или U+FFFD).

Так же должна работать и функция `ПолучитьСтрокуИзБуфераДвоичныхДанных`.
