### ISSUE TITLE
ГенераторСлучайныхЧисел не выдаёт последнее число в заданном диапазоне.

### ISSUE THREAD

**Issue by aleksandr-ermakov** [EvilBeaver/OneScript#1145]
**Опишите ошибку**
ГенераторСлучайныхЧисел.СлучайноеЧисло() не выдаёт последнее число в заданном диапазоне.

**Воспроизведение ошибки**
```bsl

// Получаем график распределения значений в цифрах.
// Каждое значение в массиве Результаты - это сколько раз выпало это число из генератора

КолВариантов = 10;
Результаты = новый Массив(КолВариантов);
Для Инд = 0 По КолВариантов - 1 Цикл
	Результаты[Инд] = 0;
КонецЦикла;

ГСЧ = Новый ГенераторСлучайныхЧисел(ТекущаяДата());

КолПопыток = 10000;
Для НомерПопытки = 1 По КолПопыток Цикл

	НомерВарианта = ГСЧ.СлучайноеЧисло(1, КолВариантов);
	Инд = НомерВарианта - 1;
	Результаты[Инд] = Результаты[Инд] + 1;

КонецЦикла;

РезультатыСтрокой = Новый Массив;
Для каждого Результат Из Результаты Цикл
	РезультатыСтрокой.Добавить(Формат(Результат, "ЧН=0; ЧГ="));
КонецЦикла;
РезультатыСтрокой = СтрСоединить(РезультатыСтрокой, " ");

Сообщить(РезультатыСтрокой);
```

**Ожидаемое поведение**
Ожидаем 10 примерно одинаковых чисел;
Получаем  `1115 1083 1089 1123 1130 1088 1142 1117 1113 0`. 
Последним числом — ноль.

**Окружение**
 - ОС: Win 10.0.19043
 - Версия: 1.7.0.214

**Comment by EvilBeaver** [comment]
А если увеличить диапазон на +1 - начинает выдавать?

**Comment by aleksandr-ermakov** [comment]
> А если увеличить диапазон на +1 - начинает выдавать?

Верхнюю границу? Нет, никакое верхнее число не выпадает.

Вот проверочный код попроще:
```bsl
ГСЧ = Новый ГенераторСлучайныхЧисел(ТекущаяДата());
Стр = "";
Для й = 1 ПО 1000 Цикл
	Стр = Стр + ГСЧ.СлучайноеЧисло(1,9);
КонецЦикла;
Сообщить("Найди девятку: " + Стр);
```

**Comment by Mr-Rm** [comment]
Если увеличить диапазон на 1, то не будет правильно работать `ГСЧ.СлучайноеЧисло(0,4294967295)`
А `ГенераторСлучайныхЧисел(ТекущаяДата())` - не должно работать, т.к. Дата не приводится к Числу.

**Comment by Mr-Rm** [comment]
В платформе найдено нечто в духе _Жёлтого чайника_:
```bsl
ГСЧ = Новый ГенераторСлучайныхЧисел();
СлЧ = ГСЧ.СлучайноеЧисло(9,1);
```
Что будет в `СлЧ`?
Правильный ответ: случайное число в диапазоне [2,8] !

**Comment by aleksandr-ermakov** [comment]
> А `ГенераторСлучайныхЧисел(ТекущаяДата())` - не должно работать, т.к. Дата не приводится к Числу.

Как говорится, ~не может, а летает~ не должно, а работает. В OneScript. 

> Правильный ответ: случайное число в диапазоне [2,8] !

Нетрудно пару раз выполнить код, чтобы убедиться что это не так:
![image](https://user-images.githubusercontent.com/28656669/147346026-3bc2a787-4f1a-4330-a88c-6433a08b1507.png)

**Comment by Mr-Rm** [comment]
Mea culpa!
```bsl
СлЧ = ГСЧ.СлучайноеЧисло(9,1);
```

**Comment by aleksandr-ermakov** [comment]
> Mea culpa!
> 
> ```bsl
> СлЧ = ГСЧ.СлучайноеЧисло(9,1);
> ```

I'm calling the police

**Comment by Mr-Rm** [comment]
Меняем код из воспроизведения ошибки:
```bsl
КолПопыток = 10000;
Для НомерПопытки = 1 По КолПопыток Цикл
	НомерВарианта = ГСЧ.СлучайноеЧисло( 1.45, КолВариантов);
	Инд = НомерВарианта - 1;
	Результаты[Инд] = Результаты[Инд] + 1;
КонецЦикла;
```
_529 1038 1050 1013 1073 1036 1047 1115 1063 1036_

А теперь
```bsl
НомерВарианта = ГСЧ.СлучайноеЧисло( 1.95, КолВариантов);
```
_55 1078 1117 1152 1099 1098 1103 1143 1078 1077_

```bsl
НомерВарианта = ГСЧ.СлучайноеЧисло( 1.999, КолВариантов);
```
_2 1150 1057 1099 1138 1129 1072 1117 1143 1093_

Вызывайте лучше санитаров...

**Comment by EvilBeaver** [comment]
А мы точно хотим повторять в точности всякую наркоманию?

**Comment by aleksandr-ermakov** [comment]
> А мы точно хотим повторять в точности всякую наркоманию?

Вряд ли требуется повторять веселье с 1.999, да и инициализация датой вряд ли кому-то будет мешать.
А вот число из верхней границы всё-таки хочется иногда получать.
