### ISSUE TITLE
Инициализация ГенераторСлучайныхЧисел() большим числом

### ISSUE THREAD

**Issue by aleksandr-ermakov** [EvilBeaver/OneScript#1146]
**Воспроизведение ошибки**
Пишем по привычке:
```bsl
ГСЧ = Новый ГенераторСлучайныхЧисел(ТекущаяУниверсальнаяДатаВМиллисекундах());
```
И получаем:
`Внешнее исключение (System.OverflowException): Значение было недопустимо малым или недопустимо большим для Int32.}`

**Окружение**
 - ОС: Win 10
 - Версия: 1.7.0.214

**Дополнительная информация**
Может из параметра инициализации просто брать младшие байты?

**Comment by EvilBeaver** [comment]
Ну поскольку низом там лежит реализация из .NET, то все поведение зависит от .NET. Ошибка понятна, спасибо!
