### ISSUE TITLE
Поддержка менеджера пакетов scoop

### ISSUE THREAD

**Issue by pumbaEO** [EvilBeaver/OneScript#1148]
# Поддержка менеджера пакетов scoop https://scoop.sh/

Для случаев когда админы тормоза  и не очень хотят давать права на установку доп пакетов лучшим решением являетса установка в режиме и с правами пользователя, но для этого необходимо выполнять множество действий скачать zip вручную распоковать куда либо Downloads , прописать путь к bin в переменную path следить за обновлением и т.д. , с scoop это проще выполнить одной командой и он сам проверит релизы на github и установит новый...

Пример scoop  пакета подготовил в https://github.com/pumbaEO/oscript-scoop в принципе можно склонировать поменять в редми ссылки и все работает, в зависимости от архитектуры качает x86.zip или x64.zip  распаковывает в %appdata%\scoop\appdata\onescript, добавляет в переменную path  каталог bin oscript , opm работает и установка пакетов 
```
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

scoop bucket add onescript https://github.com/pumbaEO/oscript-scoop.git
scoop install onescript
```

**Comment by otymko** [comment]
@pumbaEO а просто `ovm` (https://github.com/oscript-library/ovm) недостаточно? Или хочется весь софт ставить через `scoop`?

**Comment by EvilBeaver** [comment]
scoop неплохо тоже

**Comment by pumbaEO** [comment]
все так же скачать exe ,
