### ISSUE TITLE
OScript по умолчанию не подставляет заголовок User-Agent для HTTP-запросов

### ISSUE THREAD

**Issue by bapho-bush** [EvilBeaver/OneScript#1151]
**Опишите ошибку**

OScript по умолчанию не подставляет заголовок `User-Agent` для HTTP-запросов.

**Воспроизведение ошибки**

1. Выполнить любой HTTP-запрос без явного указания заголовка `User-Agent`;
2. Посмотреть содержимое Headers - заголовок будет отсутствовать.

**Ожидаемое поведение**
Ожидается, что по умолчанию будет подставляться какой-то заголовок, свидетельствующий, что запрос выполнен из OScript.
1C подставляет заголовок `1C: Enterprise/8.3`.

![изображение](https://user-images.githubusercontent.com/30332279/156329611-f8f920a3-b944-4358-9b03-668a53d5fb51.png)

**Окружение**
 - ОС: Windows 10
 - Версия: 1.7.0

**Дополнительная информация**

https://t.me/oscript_library/55493 - ниже-выше обсуждение проблемы

**Comment by beton-kun** [comment]
Постараюсь исправить

**Comment by EvilBeaver** [comment]
@beton-kun есть успехи?
