### ISSUE TITLE
Не работают точки останова в процедуре, вызванной через Выполнить()

### ISSUE THREAD

**Issue by aleksandr-ermakov** [EvilBeaver/OneScript#1152]
**Опишите ошибку**
![image](https://user-images.githubusercontent.com/28656669/158558152-1325a6fb-97d1-4940-910e-9a587c5bdd99.png)

**Воспроизведение ошибки**

1. Поставить точку
2. Запустить код
```bsl
Процедура ПлюсОдин(Арг)
	Арг = Арг + 1;
КонецПроцедуры;

Арг = 0;
Выполнить("ПлюсОдин(Арг)");
Сообщить(Арг);
```
3. Увидеть ошибку `error while processing request 'stackTrace' (exception: Путь содержит недопустимые знаки.)`

**Ожидаемое поведение**
Точка останова должна работать

**Дополнительно**
Дебаг ставится на паузу, после возобновления сам код дорабатывает без проблем.

**Окружение**
Среда VS Code 1.65, OneScriptDebug 0.7.1, 1Script 1.7.0.214
Параметры отладки (launch.json) "по умолчанию".

**Comment by EvilBeaver** [comment]
Принято, спасибо
