### ISSUE TITLE
Запись JSON в версии 2.0 записывает дату, как dd.mm.yyyy hh:mm:ss вместо формата ISO

### ISSUE THREAD

**Issue by OLEG-LV** [EvilBeaver/OneScript#1153]
**Опишите ошибку**

Выполнение загрузки релизов библиотекой Yard при использовании 1Script V 2.0, в отличии от V 1.7 завершается критической ошибкой

https://t.me/oscript_library/57099

**Воспроизведение ошибки**

1. Запустить код ...
УстановитьПеременнуюСреды("LOGOS_LEVEL", "DEBUG");

Команда      = Новый Команда;

ТекстКоманды = "oscript E:\YARD\src\yard.os process --work-dir D:\T1 D:\T1\settingsGIT.json";

Команда.УстановитьСтрокуЗапуска(ТекстКоманды);
Команда.ПоказыватьВыводНемедленно(Истина);

3. Подать на вход параметры ...  settingsGIT.json

{
    "ИмяОбработки":"СписокРелизов1С",
    "Параметры":{

            "ИмяПользователя" : "",
            "ПарольПользователя" : "",	
            "ФильтрПриложений" : ["Управление торговлей.*11"],
            "ФильтрВерсий" : ["11\\.4.*"],  
            "ФильтрВерсийНачинаяСДаты" : "2022-02-05T00:00:00"
    },
    "Обработчики":[
        {
            "ИмяОбработки":"ЗагрузчикРелизов1С",
            "ИдОбработчика":"ЗагрузчикУТ_11_4",
            "Параметры":{
                "ИмяПользователя" : "",
                "ПарольПользователя" : "",
                "КаталогДляСохранения" : "$workDir\\tmp\\distr",
                "РаспаковыватьEFD" : true,
                "КаталогДляРаспаковкиEFD" : "$workDir\\tmp\\tmplts",
                "ФайлыДляРаспаковкиEFD" : "1Cv8.cf",
                "УдалитьПослеРаспаковкиEFD" : true 
            },
            "Обработчики":[
                {
                    "ИмяОбработки":"ВыгрузкаКаталогаКонфигурацииВГит",
                    "ИдОбработчика":"ВыгрузкаДО",
                    "Параметры":{
                        "ПутьККаталогуКонфигураций" : "$workDir\\tmp\\tmplts\\Trade110",
                        "РепозитарийГит" : "$workDir\\Trade11",
                        "ИмяВеткиГит" : "release_1C",
                        "КонвертироватьВФорматЕДТ" : true,
                        "ВерсияЕДТ" : "2021.3.3",
                        "СнятьСПоддержки" : true,
                        "ОтносительныйПуть" : "Trade"
                    }
                }
            ]
        }
    ]
}

4. Увидеть ошибку

**Ожидаемое поведение**

Как и при использовании 1Script  V 1.7 , где выполнение скрипта завершается корректно, без критических ошибок

**Окружение**
 - ОС: Windows 
 - Версия:10

**Дополнительная информация**

**Comment by EvilBeaver** [comment]
А текст критической ошибки-то какой?

нашел в телеге: Преобразование к типу число не может быть выполнено.
YARD, ВыгрузкаКаталогаКонфигурацииВГит.os, строка 340

**Comment by OLEG-LV** [comment]
> 
Там видимо вызов функции из модуля "Служебный" не отрабатывает 
https://t.me/oscript_library/57093
https://t.me/oscript_library/57091

**Comment by nixel2007** [comment]
Нет, это ошибки от линтера, а не от движка.

Я просил добавить вывод подробного текста исключения со стак трейсом движка, но, кажется, его так и не сняли.

**Comment by EvilBeaver** [comment]
@OLEG-LV можете посмотреть в отладчике или через "Сообщить", чему равно значение `ВерсииДляОбработки[0].Дата` в строке 340? И какого типа это значение?

**Comment by OLEG-LV** [comment]
02.05.2022, 22:12, "Andrei Ovsiankin" ***@***.******@***.*** можете посмотреть в отладчике или через "Сообщить", чему равно значение ВерсииДляОбработки[0].Дата в строке 340?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by OLEG-LV** [comment]
Сейчас пока нет, на неделе посмотрю сообщу.  Уже выпало из  оперативной памяти, надо повспоминать контекст ситуации) 02.05.2022, 22:12, "Andrei Ovsiankin" ***@***.******@***.*** можете посмотреть в отладчике или через "Сообщить", чему равно значение ВерсииДляОбработки[0].Дата в строке 340?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by EvilBeaver** [comment]
Результат расследования:

1. ЗаписьJSON при записи даты пишет ее в формате dd.mm.yyyy hh:mm:ss, а должна в формате ISO (YYYY-MM-DDTHH:MM:SS), как делает 1С и версия 1.x
2. Тесты записи JSON есть, но не прогонялись на CI, т.к. находились в подкаталоге (исправлен testrunner)
