### ISSUE TITLE
ЧтениеXML.ИгнорироватьПробелы выдает NRE

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#1170]
**Опишите ошибку**

```bsl
Чтение = Новый ЧтениеXML
Чтение.ИгнорироватьПробелы = Истина
```

Исключение NullReferenceException

**Окружение**
 - ОС: все 
 - Версия:  1.7

**Comment by Mr-Rm** [comment]
Сюда же, к примеру:
```bsl
Чтение = Новый ЧтениеXML;
Кодировка = Чтение.КодировкаXML;
```
_Внешнее исключение (System.NullReferenceException)_
Плюс есть несколько _NotSupported_

И глобальнее:
```bsl
ПараметрыЧтения = Новый ПараметрыЧтенияXML;
```
_Конструктор не найден (ПараметрыЧтенияXML)_

**Comment by EvilBeaver** [comment]
NotSupported считаем нормой, из разряда "кому надо, тот придет и сделает". А NRE надо бы починить по возможности.

**Comment by Mr-Rm** [comment]
Ок, починка в процессе.
_Как бы всё глобально зарефакторить_
