### ISSUE TITLE
Interop c .net - возможность инстацировать классы .net и вызывать их методы c передачей параметров

### ISSUE THREAD

**Issue by xukku** [EvilBeaver/OneScript#1171]
# Описание задачи

расширение возможностей без модификации и перекомпиляции движка 

**Опишите решение**

возможность инстацировать классы .net и вызывать их методы c передачей параметров из скриптов

**Дополнительная информация**

**Comment by dmpas** [comment]
OneScript умеет общаться с CLR-средой через COM-объект.
Например так:
https://github.com/EvilBeaver/OneScript/blob/develop/tests/managed-com.os#L58

**Comment by dmpas** [comment]
Плюс для целей `расширение возможностей без модификации и перекомпиляции движка` используется технолония внешних компонент - DLL на .net по определённому формату:
https://oscript.io/dev/page/components

**Comment by xukku** [comment]
понятно - хочу попробовать вот это https://habr.com/ru/company/otus/blog/666676/

хорошо если  получится без C# оберток

**Comment by EvilBeaver** [comment]
@xukku такую штуку даже в виде C# обертки было бы неплохо завернуть в движок
