### ISSUE TITLE
РегулярноеВыражение: Ошибочная проверка на число

### ISSUE THREAD

**Issue by aleksandr-ermakov** [EvilBeaver/OneScript#1173]
Ложноположительное срабатывание метода `Совпадает()`.

**Воспроизведение ошибки**
```bsl
РегВыр = Новый РегулярноеВыражение("\d+");
Сообщить(РегВыр.Совпадает("[0]")); // Да
Сообщить(РегВыр.Совпадает("(0)")); // Да
Сообщить(РегВыр.Совпадает("-0-")); // Да
Сообщить(РегВыр.Совпадает("0-")); // Да
Сообщить(РегВыр.Совпадает("0- -")); // Да
Сообщить(РегВыр.Совпадает("0пыщпыщололо")); // Да
```

**Ожидаемое поведение**
Строка содержит число, но не совпадает с шаблоном.

**Окружение**
  - Версия: 1.7.0.214

**Comment by nixel2007** [comment]
Этот метод ищет по частичному вхождению строки. Если нужно искать полное совпадение, добавляйте ^ и $

**Comment by aleksandr-ermakov** [comment]
Спасибо. Стоит добавить это в документацию, а то название вводит в заблуждение.

**Comment by EvilBeaver** [comment]
Это фишка регулярных выражений, как таковых. В документации по ним это есть

**Comment by aleksandr-ermakov** [comment]
Хорошо что там это есть, плохо что здесь этого нет.

Допустим, я зачем-то таки полезу в документацию левого языка (не зная что здесь используется под капотом).
Вот что найду в JS:
> Используйте метод test(), если вы просто хотите узнать, находится ли шаблон в строке (он почти аналогичен методу String.prototype.search(), только вместо индекса шаблона возвращает true или false)

а здесь
> Проверяет, что строка совпадает с шаблоном регулярного выражения.

По факту, метод Совпадает() говорит что строка, не совпадающая с шаблоном -- совпадает.
Назывался бы метод Содержит() - вопрос бы не стоял.

**Comment by nixel2007** [comment]
Совпадает - это перевод от match. Во всех известных мне движках это поиск по вхождению. А чёткий поиск - find. В оскрипт нет find, только match

**Comment by aleksandr-ermakov** [comment]
Match про другое. Везде оно коллекцию совпадений возвращает.
Если имеется в виду IsMatch, то там
> Значение true, если регулярное выражение обнаруживает соответствие; в противном случае — значение false.

Так копипастните в справку, если уж прям этот метод используется. 
Сейчас метод делает не то что заявляет.

**Comment by Mr-Rm** [comment]
А если так:
_Проверяет, что в строке есть совпадение с шаблоном регулярного выражения._
