### ISSUE TITLE
Приватные свойства в рефлекторе

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#1175]
# Описание задачи

**Опишите вашу Цель, которую вы сможете достичь с помощью новой функциональности**
Какую задачу вы смогли бы решить, если бы в 1Script была предлагаемая Вами функциональность?

Добавление приватных свойств в рефлектор позволило бы библиотекам, активно работающим с рефлексией, более полно уметь взаимодействовать со внутренним состоянием класса. 

Например, в autumn можно будет реализовать внедрение зависимостей в приватное поле. 

**Опишите решение**
Четкое и понятное описание того, что Вы хотите видеть в проекте и как именно?

Добавить в метод ПолучитьСписокСвойств флаг ТолькоЭкспортные (по умолчанию истина). Добавить колонку с флагом Экспортное в данные свойства по аналогии с данными о методах. 

**Дополнительная информация**
Любая дополнтельная информация

**Comment by EvilBeaver** [comment]
Спасибо!
