### ISSUE TITLE
Несогласованное завершение Функции (Процедуры) по КонецПроцедуры (КонецФункции)

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1180]
**Опишите ошибку**
Если последним оператором в Функции (Процедуре) является ключевое слово, то возможно её завершение несогласованным парным ключевым словом КонецПроцедуры (КонецФункции)

**Воспроизведение ошибки**
```bsl
Процедура Проц1()
    Возврат
КонецФункции

Функция Функ1()
    Если Истина Тогда
        Возврат 0
    КонецЕсли
КонецПроцедуры

Процедура Проц2()
    Для й=0 по 1 Цикл
    // ...
    КонецЦикла
КонецФункции

```
и т.п. - компилируется, хотя не должно.

А так уже нормально, с ошибкой _Ожидается символ: EndProcedure_:
```bsl
Процедура Проц3()
    Возврат;
КонецФункции
```
**Ожидаемое поведение**
Должна всегда выдаваться ошибка для несогласованной пары ключевых слов

**Дополнительная информация**
В сообщении _"Ожидается символ: EndProcedure"_ ожидаемый символ (ключевое слово) всегда на английском языке

**Comment by Mr-Rm** [comment]
Всё гораздо хуже
```bsl
Процедура Проц4()
    Для й=0 по 1 Цикл
    КонецЦикла
ИначеЕсли

Функция Функ2()
    Если Истина Тогда
        Возврат 0
    КонецЕсли
КонецПопытки
Сообщить("Это тоже работает")
```

**Comment by Mr-Rm** [comment]
И ещё баг **в парсере**
```bsl
Процедура Проц3()
	Попытка
		Возврат
	Исключение
	КонецПопытки
КонецПроцедуры
```
_Ошибка в строке: 4,12 / Процедуры не могут возвращать значение
	Исключение_

В том числе и в v2

**Comment by EvilBeaver** [comment]
А в 1.x тоже? Интересно, когда сломалось

**Comment by Mr-Rm** [comment]
Сломалось на PR #608. И там в ревью было замечание на этот счёт.

**Comment by Mr-Rm** [comment]
Тоже в парсере, косвенно связанное с обсуждаемым (не углубляясь в обработчики событий). Успешно компилируется:
```bsl
Процедура Обработчик()
КонецПроцедуры

Если Истина Тогда 
	 ДобавитьОбработчик ЭтотОбъект.Событие ИначеЕсли ЭтотОбъект.Обработчик
КонецЕсли
```

**Comment by EvilBeaver** [comment]
> Сломалось на PR https://github.com/EvilBeaver/OneScript/pull/608. И там в ревью было замечание на этот счёт.

@dmpas смотри, как ты умеешь надежно ломать - пять лет никто не находил! 😏

**Comment by Mr-Rm** [comment]
А влить PR#1181 для v1?

**Comment by EvilBeaver** [comment]
Разве в v1 не влито???

**Comment by EvilBeaver** [comment]
Да, был уверен, что мы это влили в 1.8... мой косяк
