### ISSUE TITLE
не работает при отсутствии графики на сервере Linux

### ISSUE THREAD

**Issue by ivankexko** [EvilBeaver/OneScript#1185]
**Опишите ошибку**

Есть сервер под управлением Linux с установленным 1С. На этом сервере нет графического окружения.
На сервере, для обновления конфигурации 1С в ИБ скриптом - установлено ПО OneScript.
Для ПО OneScript установлена надстройка deployka.

При подключении к серверу по ssh при выполнении команды deployka loadcfg и deployka dbupdate возникает ошибка:

При deployka loadcfg:

ОШИБКА - Получен ненулевой код возврата 255. Выполнение скрипта остановлено!  
ОШИБКА - Информации об ошибке нет

При deployka dbupdate:

ИНФОРМАЦИЯ - Запускаю обновление конфигурации БД
ОШИБКА - Получен ненулевой код возврата 255. Выполнение скрипта остановлено!  
ОШИБКА - Информации об ошибке нет

На сервере нет графики совсем, Иксы не установлены.
Если подключиться к серверу по ssh в режиме форвардинга иксов, то команды так же не исполняются. Хотя другие программы, имеющие графический интерфейс (та же 1С), при форвардинге Иксов запускаются корректно.

Дополнительно есть рабочее место под управлением Linux с установленным 1С и установленным графическим окружением Cinnamon.
На этой машине при выполнении команд deployka loadcfg и deployka dbupdate ошибок нет, если команды выполняются из графической сессии.
Но если к этой же машине подключиться по ssh, то ошибка повторяется в точности так же. То есть команды выполняются только при активном графическом окружении.

Не всегда есть возможность воспользоваться рабочим местом с установленным графическим окружением. И так же, из-за проявленной ошибки нет возможности использовать надстройку в скриптах автоматизации.

**Воспроизведение ошибки**
1. Подключиться к серверу 1С по ssh
2. Выполнить deployka loadcfg ...
3. Ошибка: "ОШИБКА - Получен ненулевой код возврата 255. Выполнение скрипта остановлено!  
ОШИБКА - Информации об ошибке нет"

**Ожидаемое поведение**
1. Подключиться к серверу 1С по ssh
2. Выполнить deployka loadcfg ...
3. Увидеть результат

**Окружение**
 - ОС: Ubuntu 18.04, Debian 11, RedOS MUROM
 - Версия: oscript -version
1.8.0.3

**Comment by nixel2007** [comment]
оскрипт тут не причем. 1с требует для своей работы поднятные иксы, даже в при работе с конфигуратором. код 255 возвращает сама 1с. включив отладочные логи можно вытащить запускаемую команду и проверить самому
