### ISSUE TITLE
Лишний CR при записи в JSON

### ISSUE THREAD

**Issue by 240596448** [EvilBeaver/OneScript#1189]
Пример кода из установки плагинов `gitsinc p e ...`
```bsl
Функция ОБъектВJson(Знач Объект, ПараметрыЗаписи = Неопределено) Экспорт
	Если ПараметрыЗаписи = Неопределено Тогда
		ПараметрыЗаписи = Новый ПараметрыЗаписиJSON(ПереносСтрокJSON.Авто, " ", ,,,,,, Истина);
	КонецЕсли;

	ЗаписьJSON = Новый ЗаписьJSON;
	ЗаписьJSON.УстановитьСтроку(ПараметрыЗаписи);
	ЗаписатьJSON(ЗаписьJSON, Объект);

	Возврат ЗаписьJSON.Закрыть();
КонецФункции
```
Для `ПереносСтрокJSON.Windows` перенос формируется как `CRCRLF`
![image](https://user-images.githubusercontent.com/35220983/190919810-45a2a823-951c-4369-8d70-333b3d60ff2d.png)

Для `ПереносСтрокJSON.Unix` перенос формируется как `CRLF`
![image](https://user-images.githubusercontent.com/35220983/190919853-dd8ba0fa-7420-4d7a-9e3a-b7874dd364be.png)

Проверено на Win10, OneScript 1.7, 1.8

Тип переменной `Объект` - `Соотвествие`

**Comment by Mr-Rm** [comment]
Проблема не в ЗаписьJSON. Функция `ОБъектВJson` из примера возвращает строку с переносами строк в соответствии с параметрами: {7B 0D 0A 20 22 69 6E 63 72 65 6D 65 6E 74 22 3A 20 66 61 6C 73 65 2C 0D 0A 20 22...}. 
Если же записывать полученную строку в файл через `ЗаписьТекста.Записать()`, то этот метод по умолчанию принудительно конвертирует **все** "\n"в "\r\n", делая из "\r\n" -  "\r\r\n". 1С делает то же самое.
Можно использовать `ЗаписьJSON.ОткрытьФайл()` либо задавать"\n" как разделитель строк в  `ЗаписьТекста.Записать()`. 
_(найдено отличие в поведении функции `ЗаписатьJSON()` )_

**Comment by 240596448** [comment]
@Mr-Rm, т.е. просто двойная конвертация переносов произошла?
Ясно, что-то сообразил сразу глянуть символьную последовательность и дальнейшую запись...
Тогда закрываю.
