### ISSUE TITLE
v2 native: не работает сложение строк

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1192]
**Опишите ошибку**
В v2.0.0-rc1 в режиме native не работает сложение строк.

**Воспроизведение ошибки**
1. Запустить код:
```bsl
#native
Б = "Г" + "Д";
```
2. Увидеть ошибку:
_Ошибка в строке: 2,3 / Ошибка компиляции статического модуля
System.InvalidOperationException: The binary operator Add is not defined for the types 'System.String' and 'System.String'._

**Окружение**
 - ОС: Windows 10 x64, .Net 6.0.9
 - Версия: OneScript-2.0.0-rc1-win-x64

**Дополнительная информация**
Упал пример кода со [страницы пре-релиза](https://github.com/EvilBeaver/OneScript/releases/tag/v2.0.0-rc1).
Слишком просто и очевидно. Может быть, я что-то упустил?

**Comment by EvilBeaver** [comment]
Упс.. должно по идее было забиндится на стандартный оператор сложения строк, но кажется, я это выпилил и теперь понятно, что напрасно
