### ISSUE TITLE
Ошибка получения источника скрипта в отладке

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#1196]
**Опишите ошибку**

```bsl
#Использовать logos
Перем Лог Экспорт;

Процедура ПриСозданииОбъекта(Параметр = Ложь)
  Лог = Логирование.ПолучитьЛог("oscript.app.CreateReleaseFiles");
  Лог.УстановитьРаскладку(ЭтотОбъект);
  Лог.УстановитьУровень(УровниЛога.Отладка);
КонецПроцедуры  

Если ТекущийСценарий().Источник = СтартовыйСценарий().Источник Тогда
    
  //ПриСозданииОбъекта(Истина);
  Лог.Отладка("Начало выполнения скрипта: " + ТекущийСценарий().Источник);

КонецЕсли;
```

**Воспроизведение ошибки**
1. Поставить точку остановки на `Лог.Отладка("Начало выполнения скрипта: " + ТекущийСценарий().Источник);`
1. Запустить код в отладчике
1. Развернуть переменные в отладчике
2. Увидеть, что ТекущийСценарий.Источник = <expression>, что неверно
3. Продолжить выполнение и увидеть ошибку `Значение не является значением объектного типа`

**Ожидаемое поведение**
Система не падает, в отладчике источник текущего скрипта соответствует действительности

**Окружение**
 - Версия: 1.7

**Comment by nixel2007** [comment]
> Продолжить выполнение и увидеть ошибку Значение не является значением объектного типа

Возможно это падает из-за неинициализированного Лог

**Comment by EvilBeaver** [comment]
> Возможно это падает из-за неинициализированного Лог

Суть в том, что в дебаггере сорс скрипта меняется на левое значение. Так быть не должно
