### ISSUE TITLE
В конструкторе "Структура" (System.NullReferenceException): Object reference not set to an instance of an object}

### ISSUE THREAD

**Issue by otymko** [EvilBeaver/OneScript#1197]
**Опишите ошибку**

В v8 допустим код (хотя не скажу что это не косяк в платформе):
```os
Значение = Новый Структура(, Неопределено);
```

В ОСкрипте в лицо прилетает исключение:
```sh
{Модуль /Users/olegtymko/data/rnd/structure.os / Ошибка в строке: 1 / Внешнее исключение (System.NullReferenceException): Object reference not set to an instance of an object}
```

**Воспроизведение ошибки**

Выполнить код:
```os
Значение = Новый Структура(, Неопределено);
```

**Ожидаемое поведение**

Исключение не должно быть, создается пустая структура.

**Окружение**
 - ОС: MacOs 12.2
 - Версия: 1.7.0.214

**Дополнительная информация**

**Comment by Mr-Rm** [comment]
Ровно та же ошибка по той же самой причине возникает также в следующих случаях:
```bsl
ЗаписатьJSON(); // !
ХешированиеДанных=Новый ХешированиеДанных(ХешФункция.CRC32);
ХешированиеДанных.Добавить(,); // !
ДеревоЗначений =новый ДеревоЗначений();
ДеревоЗначений.Строки.Сдвинуть(,0); // ! а Сдвинуть(,) - ещё хуже
ДеревоЗначений.Строки.НайтиСтроки(,); // !
XMLЗначение(,); // !
ЧтениеZipФайла = Новый ЧтениеZipФайла(,); // !
ФиксированнаяСтруктура = Новый ФиксированнаяСтруктура(,); // !
ФайловыйПоток = Новый ФайловыйПоток(ИмяФайла, РежимОткрытияФайла.Открыть);
ФайловыйПоток.КопироватьВ(,); // !
ПотокВПамяти = Новый ПотокВПамяти();
ПотокВПамяти.КопироватьВ(,); // !
```

**Comment by EvilBeaver** [comment]
пропущенный первый параметр неправильно обрабатывается?

**Comment by Mr-Rm** [comment]
Отсутствует проверка на null перед вызовом `GetRawValue()`.
А `ДеревоЗначений.Строки.Сдвинуть(,)` падает раньше, по второму параметру в `ContextMethodsMapper.ConvertParam<T>()`. Это по какой-то другой причине.
