### ISSUE TITLE
Индексы в Таблице значений

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#1211]
Индексы в Таблицу Значений и Дерево Значений добавляются, но никак не влияют на производительность.
Необходимо добавить использование индексов при поисках.

**Comment by EvilBeaver** [comment]
@dmpas ты же вроде открывал пулреквест на это, не?

**Comment by dmpas** [comment]
> @dmpas ты же вроде открывал пулреквест на это, не?

Не...

**Comment by EvilBeaver** [comment]
Мяу-мяу?

**Comment by dmpas** [comment]
> Мяу-мяу?

@EvilBeaver Всё. Приступил.

**Comment by EvilBeaver** [comment]
Мяу?

**Comment by dmpas** [comment]
@EvilBeaver всё будет. Сначала до NUnit бы добраться...

**Comment by EvilBeaver** [comment]
@dmpas не, NUnit гиблое дело, лучше индексы сначала. Пользы людям больше будет. Вон, в ОСени, например, сканирование типов на таблицах значений может ускориться на сколько-то миллисекунд

**Comment by tormozit** [comment]
Что в вашем шифре означает "мяу"?

**Comment by EvilBeaver** [comment]
> Что в вашем шифре означает "мяу"?

У тебя что, кота никогда не было?

**Comment by dmpas** [comment]
Вот уже даже что-то начинает работать.

**Comment by EvilBeaver** [comment]
@dmpas привет! Можем надеяться на пулреквест?

**Comment by dmpas** [comment]
> @dmpas привет! Можем надеяться на пулреквест?

@EvilBeaver да, постараюсь сегодня закинуть. Вчера решил вдруг аннотации в двойку перенести и как-то погряз...

**Comment by dmpas** [comment]
В дереве-то ещё нет ничего.

**Comment by EvilBeaver** [comment]
Ну... А я уже и ветку снёс

**Comment by dmpas** [comment]
в дереве значений нет индексов. Закрываем без него.
