### ISSUE TITLE
Ошибка расширения OneScript Debug (BSL)

### ISSUE THREAD

**Issue by mavlenkov** [EvilBeaver/OneScript#1216]
Ошибка в выходных данных Visual Studio Code:
_[Error - 09:39:23] Starting client failed
Launching server using command /usr/lib/jvm/zulu-fx-11-amd64/bin/java failed._
Выполняю следующие инструкции:
_Откройте папку с проектом oscript
Нажмите F5
Будет создан файл launch.json с параметрами отладки._
При этом ожидаю работу подсветки синтаксиса и возможность отладки, не работает ни то, ни другое.
Проверялось на Astra Linux Orel 2.12 и Slackware 15.0
oscript из командной строки работает корректно. Также установлено расширение Поддержка встроенного языка 1С:Исполнителя (SBSL)

**Comment by nixel2007** [comment]
> [Error - 09:39:23] Starting client failed
Launching server using command /usr/lib/jvm/zulu-fx-11-amd64/bin/java failed.

это очень странное сообщение, т.к. отладчик оскрипта написан на шарпе, а не на джаве и джаве там запускать нечего.
точно ли речь не идет про bsl languaage server, который запускается плагином 1C (BSL) Language? 

Ну а bsl ls никак не связан с отладчиком :)

Подсветка должна работать, если стоит плагин 1C (BSL) Language и выбрать язык 1C (BSL)

**Comment by mavlenkov** [comment]
Вот и мне это показалось странным. На данный момент пока понятно только то, что каким-то образом я привязал вместо отладчика oscript запуск 1С:Исполнителя, который как раз на java. С подсветкой разобрался, спасибо, а вот при попытке запустить отладчик таки получаю ошибку, но уже более вменяемую: _Can't launch debugee (ApplicationName='oscript.exe', ...)._ Не очень понятно только, как её победить.

**Comment by nixel2007** [comment]
В launch.json вместо oscript.exe укажите oscript

**Comment by mavlenkov** [comment]
Вот мой launch.json
```
{
    // Используйте IntelliSense, чтобы узнать о возможных атрибутах.
    // Наведите указатель мыши, чтобы просмотреть описания существующих атрибутов.
    // Для получения дополнительной информации посетите: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Отладка 1Script",
            "type": "oscript",
            "program": "oscript",
            "request": "launch",
            "env": {},
            "runtimeExecutable": null,
            "runtimeArgs": [],
            "debugPort": 2801
        }
    ]
}
```
В таком варианте возникает ошибка "Script '/home/username/oscript' does not exist." Если я меняю на program": "/usr/bin/oscript" где он по факту и располагается, то возникает ошибка описанная выше: _Can't launch debugee (ApplicationName='oscript.exe', ...)._

**Comment by EvilBeaver** [comment]
Попробуйте указать путь не к shell-файлу запуска oscript, а к самому oscript.exe. Я не помню куда он устанавливается, но можно в shell-запускалке посмотреть. @dmpas куда кладется сам файл exe на линуксе?

**Comment by dmpas** [comment]
Usr share lib oscript bin
 Вроде бы

**Comment by mavlenkov** [comment]
```
username@hostname:~$ whereis oscript
oscript: /usr/bin/oscript /etc/oscript.cfg /usr/share/oscript
username@hostname:~$ cd /usr/share/oscript/bin
username@hostname:/usr/share/oscript/bin$ ls
ASPNETHandler.dll           Newtonsoft.Json.dll          OneScript.Language.dll  ScriptEngine.dll               ScriptEngine.NativeApi64.dll
DotNetZip.dll               OneScript.DebugProtocol.dll  oscript.cfg             ScriptEngine.HostedScript.dll  ScriptEngine.NativeApi64.so
ICSharpCode.AvalonEdit.dll  OneScript.DebugServices.dll  oscript.exe             ScriptEngine.NativeApi32.so    TestApp.exe
username@hostname:/usr/share/oscript/bin$
```
Какое-то такое расположение.
Сделал символическую ссылку /usr/bin/oscript на /usr/bin/oscript.exe В launch.json прописал "program": "/usr/bin/oscript", после чего ошибки в окнах исчезли, но при запуске кода ничего не выполняется, а в консоли отладки вот такое:
```
System.MissingMethodException: Method 'System.Net.Sockets.TcpListener.Create' not found.
  at oscript.DebugBehavior.Execute () [0x00047] in <ff68fd75110a4c9c9416e2d7bf72ecf3>:0
  at oscript.Program.Main (System.String[] args) [0x00007] in <ff68fd75110a4c9c9416e2d7bf72ecf3>:0

```

**Comment by EvilBeaver** [comment]
Да, для всего этого еще нужно Mono, желательно самое свежее, т.к. мы недавно перешли на .NET 4.8
Подозреваю, что MissingMethod может быть из-за версии Mono.

**Comment by mavlenkov** [comment]
Есть такое вот:
```
username@hostname:~$ mono --version
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen

```

**Comment by EvilBeaver** [comment]
Очень старое. На нем вообще почти ничего в 1Скрипт не работает. Ставьте свежее из реп моно

**Comment by EvilBeaver** [comment]
@mavlenkov завелось? Могу закрыть issue?

**Comment by mavlenkov** [comment]
Нет, но закрывайте - у меня не получилось найти Mono новее на Astra Linux, может попробую потом собрать сам. Спасибо!

**Comment by EvilBeaver** [comment]
Astra это deb или rpm дистрибутив?

**Comment by mavlenkov** [comment]
Deb

**Comment by EvilBeaver** [comment]
@mavlenkov ну тогда по идее к ней должны подходить стандартные репы mono для убунту или дебиана

https://www.mono-project.com/download/stable/#download-lin-debian

**Comment by dmitri77** [comment]
У меня была ошибка "Сan't launch debugee" упомянутая выше, но нужно было не в program прописывать путь к oscript.exe, а а runtimeExecutable! Вот что у меня норм взлетело:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Отладка 1Script",
            "type": "oscript",
            "request": "launch",
            "program": "${workspaceFolder}/test.os",
            "args": [],
            "cwd": "${workspaceFolder}",
            "env": {},
            "runtimeExecutable": "d:/onescript/bin/oscript.exe",
            "runtimeArgs": [],
            "debugPort": 2801
        }
    ]
} 
```

**Comment by mavlenkov** [comment]
> У меня была ошибка "Сan't launch debugee" упомянутая выше, но нужно было не в program прописывать путь к oscript.exe, а а runtimeExecutable! Вот что у меня норм взлетело:
> 
> ```
> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Отладка 1Script",
>             "type": "oscript",
>             "request": "launch",
>             "program": "${workspaceFolder}/test.os",
>             "args": [],
>             "cwd": "${workspaceFolder}",
>             "env": {},
>             "runtimeExecutable": "d:/onescript/bin/oscript.exe",
>             "runtimeArgs": [],
>             "debugPort": 2801
>         }
>     ]
> } 
> ```

Спасибо за информацию!

**Comment by riazmey** [comment]
https://github.com/EvilBeaver/OneScript/issues/1216?ysclid=lrjdgc9pws796783938?ysclid=lrjdgc9pws796783938#issuecomment-1460138783
Спасибо за ответ. Он мне помог наладить отладку на Linux-е.
Вот так как у меня заработало:
 ```
{
    // Используйте IntelliSense, чтобы узнать о возможных атрибутах.
    // Наведите указатель мыши, чтобы просмотреть описания существующих атрибутов.
    // Для получения дополнительной информации посетите: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Отладка OneScript",
            "type": "oscript",
            "request": "launch",
            "program": "${file}",
            "args": ["внести", "100"],
            "cwd": "${workspaceRoot}",
            "env": {},
            "runtimeExecutable": "/usr/bin/oscript",
            "runtimeArgs": [],
            "debugPort": 2801
        }
    ]
}
```

**Comment by mineralkee** [comment]
> > У меня была ошибка "Сan't launch debugee" упомянутая выше, но нужно было не в program прописывать путь к oscript.exe, а а runtimeExecutable! Вот что у меня норм взлетело:
> > ```
> > {
> >     // Use IntelliSense to learn about possible attributes.
> >     // Hover to view descriptions of existing attributes.
> >     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
> >     "version": "0.2.0",
> >     "configurations": [
> >         {
> >             "name": "Отладка 1Script",
> >             "type": "oscript",
> >             "request": "launch",
> >             "program": "${workspaceFolder}/test.os",
> >             "args": [],
> >             "cwd": "${workspaceFolder}",
> >             "env": {},
> >             "runtimeExecutable": "d:/onescript/bin/oscript.exe",
> >             "runtimeArgs": [],
> >             "debugPort": 2801
> >         }
> >     ]
> > } 
> > ```
> 
> Спасибо за информацию!

День добрый.
Получилось у вас тогда запустить отладку на Астре?

**Comment by mavlenkov** [comment]
> 
> День добрый. Получилось у вас тогда запустить отладку на Астре?

Приветствую. Нет, там тогда слишком много надо было всего сделать и вроде как Mono пересобрать, не помню точно уже, забил в итоге, а потом вообще перешёл с Астры на Альт Линукс и по сей день на нём живу. К слову, интерсено, а на нём будет отладка работать? (:

**Comment by mineralkee** [comment]
@EvilBeaver добрый вечер.

У нас ситуация "интереснее": Астра, которая не имеет доступа в интернеты... Все пакеты были скачаны в другом месте заранее и перекинуты на неё.
Выполнение о-скриптов в vscode таской работает корректно. А вот отладка не стартует. То есть после нажатия на кнопку запуска на мгновение появляются управляющие кнопки (старт, стоп, перезапуск отладки и т.п.), а потом быстро исчезают. И никаких ошибок или другой информации нет ни в output ни где либо ещё. 

Играться с абсолютными и относительными путями к файлу и среде исполнения (о чём тут писали выше) пробовали - безрезультатно. 
Грешили на порт, но с любым другим ситуация неизменна. 

Поэтому интересовался у автора ишузы, получилось ли запустить на данной ОС.

Или, может, есть понимание, в какие логи надо идти, чтобы получить хоть какую-то информацию о происходящем?

**Comment by EvilBeaver** [comment]
@mineralkee имеет смысл включить логи отладчика и прислать сюда. Логи включаются в конфиг файле, где установлено расширение отладчика. На моей убунте это `~/.vscode/extensions/evilbeaver.oscript-debug-0.9.1` где на Астре не знаю, скорее всего, там же.

Конфиг лежит по пути `bin/VSCode.DebugAdapter.exe.config` в нем надо раскомментировать логирование и вписать валидный путь для лога в папку, куда точно есть доступ.

```
  <!-- Пример включения лога с уровнем подробности Debug, записываемого в файл-->
    <appSettings>
        <add key="serilog:minimum-level" value="Debug" />
        <add key="serilog:using:File" value="Serilog.Sinks.File" />
        <add key="serilog:write-to:File.path" value="/home/user/OneScript.Debugger.log" />
    </appSettings>
   
```

**Comment by mineralkee** [comment]
> [@mineralkee](https://github.com/mineralkee) имеет смысл включить логи отладчика и прислать сюда. Логи включаются в конфиг файле, где установлено расширение отладчика. На моей убунте это `~/.vscode/extensions/evilbeaver.oscript-debug-0.9.1` где на Астре не знаю, скорее всего, там же.
> 
> Конфиг лежит по пути `bin/VSCode.DebugAdapter.exe.config` в нем надо раскомментировать логирование и вписать валидный путь для лога в папку, куда точно есть доступ.
> 
> ```
>   
>     <appSettings>
>         <add key="serilog:minimum-level" value="Debug" />
>         <add key="serilog:using:File" value="Serilog.Sinks.File" />
>         <add key="serilog:write-to:File.path" value="/home/user/OneScript.Debugger.log" />
>     </appSettings>
>    
> ```

Лог вывел ошибку загрузки типов

System.TypeLoadException: Failure has occurred while loading a type.
  at VSCodeDebug.ProtocolServer.ProcessData () [0x00044] in <a02a82bd5c7c49cf8080dadf7d935fcb>:0 
  at VSCodeDebug.ProtocolServer.Start (System.IO.Stream inputStream, System.IO.Stream outputStream) [0x0003b] in <a02a82bd5c7c49cf8080dadf7d935fcb>:0 
  at VSCode.DebugAdapter.Program.StartSession (System.IO.Stream input, System.IO.Stream output) [0x0003a] in <a02a82bd5c7c49cf8080dadf7d935fcb>:0

**Comment by EvilBeaver** [comment]
@mineralkee это версия моно. Нужна 6.12+

**Comment by vsbronnikov** [comment]
Была такая же проблема на Ubuntu. Помогла установка из репозитория проекта mono-project пакета mono-complete. Установилась версия 6.12.0.200.
