### ISSUE TITLE
TCPСоединение - сброс соединения при отправке ответа

### ISSUE THREAD

**Issue by Macegor** [EvilBeaver/OneScript#1221]
**Описание ошибки**
Создаётся TCPСервер и ожидает соединения, как только происходит обращение создаётся TCPСоединение и ожидается что при отправке ответа соединение останется активным и произойдёт отправка ответа, но получается так что сразу после выполнения отправки ответа соединение сбрасывается а ответ так и не приходит.

**Воспроизведение ошибки**
Вот [ссылка](https://github.com/Macegor/SocketServer)  на репозиторий с примером

**Ожидаемое поведение**
Объект TCPСоединение должен оставаться активным после отправки ответа и ответ должен быть отправлен.

**Окружение**
 - ОС: Windows
 - Версия: 11

**Comment by Nivanchenko** [comment]
Я по этим граблям скакал тоже. Я сделал репу со своим расследованием, на сколько мог подробно описал проблематику. Там несколько файлов для легкого воспроизведения ошибки.
https://github.com/Nivanchenko/oscript-tcp-issue-example
Причем, если прокрисовать ответы от другого сервера, то почему-то оно работает. В репе этот момент тоже описал.

ОС: Мак
Mono JIT compiler version 6.12.0.182
1Script Execution Engine. Version 1.8.1.13

**Comment by Nivanchenko** [comment]
Еще обратил внимание, что между рабочим и не рабочим ответом разница переноса строк CRLF и LF, но пробовал менять перед отправкой, не помогло.

**Comment by Nivanchenko** [comment]
Мой пример заработал. https://github.com/Nivanchenko/oscript-tcp-issue-example/blob/master/miniserver.os
Это рабочий вариант. Но там идет шифрование фреймов сообщений. Тут энтузиастам можно пожелать сил =)

**Comment by EvilBeaver** [comment]
Правильно понимаю, что в движке ошибки нет и можно закрывать issue? Или все-таки есть?

**Comment by Macegor** [comment]
По идее да, но хотелось бы что бы какое то исключение возникало при не правильной работе, а то вот так пальцем в небо не дело конечно тыкать

**Comment by Nivanchenko** [comment]
> По идее да, но хотелось бы что бы какое то исключение возникало при не правильной работе, а то вот так пальцем в небо не дело конечно тыкать

Не, зачем тебе исключение, если соединение закрыл кто-то там в далеке? может у него интернет пропал. а у тебя исключение.

**Comment by EvilBeaver** [comment]
Тут спорный момент. Если соединение закрыли, то в нем больше нет смысла и хочется узнавать об этом заранее. С другой стороны, сетевой стек так устроен, что ты не можешь достоверно проверить живо соединение или нет, пока не пошлешь в него байты. Поэтому правильное решение - это исключение, но в момент попытки чтения/записи сокета. Флаг "Активно" показывает в некоторой мере "погоду", потому что ты проверил флаг, получил "Активно = Истина" а в следующей строке кода - соединение бах и закрылось.

```bsl
Если Соединение.Активно Тогда // вот тут соединение активно
    // А вот тут уже бабах и связь оторвалась
    Соединение.ОтправитьСтроку("Привет");
КонецЕсли;
```

**Comment by Nivanchenko** [comment]
Не как раз при попытке отправки в закрытое соединение вроде будет исключение. Тут как будто логично. Я больше говорил про историю когда я что-то отправил, соединение отложил до лучших времен и делаю другую полезную нагрузку. А в этот момент у меня соединение закрылось. Тут я не хотел бы никаких исключений =)

**Comment by Macegor** [comment]
В нашем случае сброс соединения прошел из-за не верных заголовков, вот как это можно понять? Подозреваю что никак.

**Comment by Nivanchenko** [comment]
такова спецификация. Браузер думает, что подключился куда-то не туда, и закрыл соединение.

**Comment by Macegor** [comment]
Я думаю вопрос можно считать закрытым)))
