### ISSUE TITLE
Печать макетов

### ISSUE THREAD

**Issue by woodholly** [EvilBeaver/OneScript#1222]
Реализован ли движок макетов ?
Можно ли распечатать макет с помощью OneScript ? Если нет, это возможно сделать?

**Comment by nixel2007** [comment]
О чем речь? Каких макетов?

**Comment by woodholly** [comment]
Видимо нет...

**Comment by nixel2007** [comment]
В движке есть макеты. Но вы явно подразумеваете под ними что-то отличное от понятий движка или 1с.

**Comment by woodholly** [comment]
Например макет Акта или Накладной, можно ли в OneScript их заполнить и напечатать ?

**Comment by nixel2007** [comment]
Вы про табличные документы?

**Comment by EvilBeaver** [comment]
В 1Скрипт есть только один тип макетов - "ДвоичныеДанные". Других, к сожалению, нет
