### ISSUE TITLE
Unable to initialize GTK+ при запуске vrunner compile

### ISSUE THREAD

**Issue by rike18** [EvilBeaver/OneScript#1223]
Выходит ошибка такого вида:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/32277697/205621493-5f9bf1cc-765d-481c-baa6-e489954ad7aa.png">

Выполняю команду:  vrunner compile --src=/project/main --out=/project/1Cv8.cf

Судя по контексту ошибки, он пытается что-то отрисовать, но на системе нет GUI. Есть предположение, что из-за отсутствия лицензии, он пытается показать соответствующее окно, но это только предположение. 
<img width="333" alt="image" src="https://user-images.githubusercontent.com/32277697/205622642-5b872c91-91ee-4df1-8976-ce5ce05b0ec1.png">

Лицензию не ставлю, так как тестирую функционал и жду ошибку, которая сигнализирует об этом  ) 

Ожидаю сборку cf из XML файлов.

Установлено:
EDT - v.2022.1.3
1С Server и Толстый клиент - v.8.3.21.1393
Onescript - v.1.8.1.4
Vrunner - v.1.11.11

Окружение:
Linux CentOS7

**Comment by rike18** [comment]
Возможно тут нужен xvfb, судя по этому https://github.com/oscript-library/v8runner/blob/master/.travis.yml

**Comment by nixel2007** [comment]
> Судя по контексту ошибки, он пытается что-то отрисовать, но на системе нет GUI. Есть предположение, что из-за отсутствия лицензии, он пытается показать соответствующее окно, но это только предположение.

1с на linux требует поднятых иксов.

**Comment by rike18** [comment]
В итоге: поставил xvfb, объявил переменную export DISPLAY=:0.0 и получил то, что хотел.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/32277697/205631731-1d371adb-ba8c-4dc9-81b1-1b1120c12ffd.png">
