### ISSUE TITLE
System.TypeLoadException при взаимодействии с vanessa-runner

### ISSUE THREAD

**Issue by bapho-bush** [EvilBeaver/OneScript#1225]
**Опишите ошибку**

Возникает исключение `System.TypeLoadException` при взаимодействии с vanessa-runner

![image](https://user-images.githubusercontent.com/30332279/206201370-ce8d636e-2eb4-4c9c-aa50-2571609fece9.png)

**Воспроизведение ошибки**

1. Установить vanessa-runner
2. Набрать vanessa-runner --help

Появится ошибка "error loading assemblies".

**Ожидаемое поведение**

Отсутствие исключения

**Окружение**
 - ОС: Windows
 - Версия: 2.0

**Дополнительная информация**

https://t.me/oscript_library/58570

**Comment by EvilBeaver** [comment]
@artbear можешь подтвердить?

**Comment by pravets** [comment]
На всякий случай up

Проверял на версиях `2.0.0.4-rc3` и `2.0.0.431-rc4-28321016` 

Хоть дело и не в версии oscript

**Comment by nixel2007** [comment]
Угу, от dll v8unpack прилёт

**Comment by EvilBeaver** [comment]
Кажется, можно закрывать, v8unpack выпущен
