### ISSUE TITLE
Добавить сборку osx и osx-arm

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#1232]
В net6 поддерживается сборка scd для MacOS в архитектуре arm, а также fdd в net6 может работать под arm

- [x] Перейти на net6
- [x] Добавить дистрибутивы osx в билд-скрипт
- [x] Добавить дистрибутивы osx на сайт
- [x] Добавить на сайт заметку с краткими схемами урлов скачивания
- [x] Доработать ovm для скачивания всего зоопарка вариантов

**Comment by EvilBeaver** [comment]
@nixel2007 сориентируй плиз, мы что-то в ovm еще будем делать или ставлю последнюю галочку и закрываю таск?

**Comment by nixel2007** [comment]
Я бы хотел таки дотащить до овм scd.

**Comment by EvilBeaver** [comment]
@nixel2007 я понимаю, что тебе некогда, но мяу?

Может хотя бы в виде постановки задачи другому падавану, где, что как?

**Comment by nixel2007** [comment]
@EvilBeaver Основная мысль - надо добавить анализ ОС и архитектуры процессора в овм. С последним может быть сложно на маке - не помню, добавлял ли @dmpas доработку анализа ядра в 1.х или только в 2.0.

Соответственно если запрашиваемая к установке версия night-build или >= 2.0 или в последствии stable, то урл для скачки должен быть собран из оси и архитектуры.

Текущие процедуры генерации батников) oscript и opm) в установщике заточены под 1.х и fsc. Под scd их вероятно надо обновить.

**Comment by nixel2007** [comment]
@EvilBeaver плюс ты говорил, что надо батники добавить прям в scd. Тогда их генерацию можно будет убрать

**Comment by EvilBeaver** [comment]
@nixel2007 давай воскресим и актуализируем? Я сделал #1284, починил шеллы для разных дистров.

**Comment by sfaqer** [comment]
@EvilBeaver я так понимаю #1360 к этому ишузу

**Comment by nixel2007** [comment]
Кажется, на стороне овм нет определения арм-неарм @sfaqer ты вроде говорил, что не хватает информации в СИ

**Comment by sfaqer** [comment]
> Кажется, на стороне овм нет определения арм-неарм @sfaqer ты вроде говорил, что не хватает информации в СИ

Все так, там нет архитектуры процессора

**Comment by nixel2007** [comment]
@dmpas ты вроде работал над этим?
