### ISSUE TITLE
Показ отладчиком приватных значений объектов\модулей

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#1235]
# Описание задачи

**Опишите вашу Цель, которую вы сможете достичь с помощью новой функциональности**
есть объект 1С, создан через Новый по имени класса чужой библиотеки
внутри модуля этого класса есть приватные\закрытые переменные

Добавить показ отладчиком приватных значений объектов

**Опишите решение**

**Дополнительная информация**

**Comment by dvakor** [comment]
Это сделать довольно легко, единственное, что хотелось бы обсудить это необходимость как-то помечать экспортные и / или приватные переменные.

Тут проблема в том, что в DAP спеке есть VariablePresentationHint, но к сожалению, в сам VSC до сих пор не завезли его поддержку для Variables

Собственно вариантов у меня на уме несколько:

Покурив другие дебаггеры я пришел к 3 вариантам

1) Забить :)

2) Вывести в представление имени переменной:
![image](https://github.com/EvilBeaver/OneScript/assets/4038422/56cfd156-e486-4086-b3e5-63b08bf59cfb)
Мое имхо: выглядет так себе, но нет сайд эффектов (см 3 пункт)

3) Вывести в представление значения переменной:
![image](https://github.com/EvilBeaver/OneScript/assets/4038422/e2eedc1d-4982-49fd-9623-764b78fc3ac8)
Скрин взят с просторов интернета, но суть я думаю передает
Мое имхо: выглядет по лучше, но несет в себе сайд эффект в виде немного поломанной функции `copy value`, тк она копирует представление то и скопирует [Экспорт]

ЗЫ я за 2й вариант

**Comment by EvilBeaver** [comment]
Как насчет сделать scope? В DAP есть понятие scope-ов

**Comment by dvakor** [comment]
@EvilBeaver, есть, но они располагаются на самом верхнем уровне в дереве.

те 
```
- scope
-- variable
--- property
```

сделать так, на сколько я понял нельзя

```
- scope
-- variable
--- scope1
---- property
```

**Comment by EvilBeaver** [comment]
Я имел в виду другое. Есть задача: #569 я планировал решить ее через scopes:

```
- Переменные модуля
- - А: Строка
- - Б: Число
- Локальные переменные
- - блаблабла
```

Но понял, что вот эта задача #1235 она про другое. Мне кажется, разработчик ожидает увидеть сначала публичные свойства, а потом приватные. Если presentationHints не поддержаны в VSCode их все равно надо добавить в адаптер, ибо, когда MS их "поддержит" все заработает красиво.
А пока они не поддержаны, можно добавлять к ним какой-то префикс, но лучше не в значение, а в Имя, т.к. префикс может сбивать с толку, как будто это часть значения. А в имя можно дописывать, например `$`

```
МойОбъект:
   - Свойство: "Привет"
   - $ПриватноеСвойство: "Меня видно только в отладчике"
```
