### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#124]
Originally reported by: **dreamwalkertg (Bitbucket: [dreamwalkertg](http://bitbucket.org/dreamwalkertg), GitHub: Unknown)**

---

Не могли бы вы указать лицензию под которой распространяется ваша библиотека? Можно ли её использовать в коммерческих продуктах?

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/124

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

На данный момент лицензия не выбрана. Это значит, что вы не можете включать этот код в свои продукты ни коим образом, до получения явного разрешения автора (меня). Т.е. действует **Принцип автоматической охраны** [Википедия](https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D1%80%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%BA%D0%BE%D0%BD%D0%B2%D0%B5%D0%BD%D1%86%D0%B8%D1%8F_%D0%BE%D0%B1_%D0%BE%D1%85%D1%80%D0%B0%D0%BD%D0%B5_%D0%BB%D0%B8%D1%82%D0%B5%D1%80%D0%B0%D1%82%D1%83%D1%80%D0%BD%D1%8B%D1%85_%D0%B8_%D1%85%D1%83%D0%B4%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D1%85_%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B9)

Я склоняюсь к лицензии Apache или GPL2. Если вкратце, то:
- по Apache вы можете использовать как угодно и не делиться своими доработками. Обязательно сохраняете копирайты и указываете где взяли код.
- по GPL2 - аналогично, но вы еще обязаны и предоставить все свои доработки к исходному коду, если у вас такие попросят.

В любом случае, мы можем обсудить и договориться о чем угодно ;)

**Comment by EvilBeaver** [comment]
_Original comment by_ **Alexey Lustin (Bitbucket: [allustin](http://bitbucket.org/allustin), GitHub: [allustin](http://github.com/allustin))**:

---

Мы когда выбирали - выбрали Apache http://choosealicense.com/licenses/

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

fixed #124: Применена лицензия Mozilla Public License 2.0

**Comment by artbear** [comment]
@EvilBeaver В тексте лицензии не вижу тебя как владельца прав.
Это специально сделано?

**Comment by EvilBeaver** [comment]
@artbear а где там он (владелец прав) должен быть?

**Comment by artbear** [comment]
@EvilBeaver ИМХО внизу где-то

**Comment by nixel2007** [comment]
@EvilBeaver @artbear владелец авторских прав при желании указывается в бойлерплейте в каждом файле исходника. Бойлерплейт берется по примеру Exhibit A.

**Comment by EvilBeaver** [comment]
@nixel2007 ну вот я там не нашел место под владельца

**Comment by nixel2007** [comment]
@EvilBeaver 

Exhibit A - Source Code Form License Notice

```
  This Source Code Form is subject to the
  terms of the Mozilla Public License, v.
  2.0. If a copy of the MPL was not
  distributed with this file, You can
  obtain one at
  http://mozilla.org/MPL/2.0/.
```

If it is not possible or desirable to put the notice in a particular file,
then You may include the notice in a location (such as a LICENSE file in a
relevant directory) where a recipient would be likely to look for such a
notice.

**You may add additional accurate notices of copyright ownership.**

---

т.е. куда и как хочешь, так и вписывай авторство. плюс по аналогии с апачем вместо бойлерплейтов ты можешь создать в корне файл NOTICE, в котором прописать эту вставку с указанием авторских прав.

**Comment by EvilBeaver** [comment]
Тут непонятный момент с владельцем прав. На движок да, а с контрибьюцией как быть?

**Comment by nixel2007** [comment]
1.1. "Contributor"
means each individual or legal entity that creates, contributes to the
creation of, **or** owns Covered Software.

...

1.3. "Contribution"

means Covered Software of a particular Contributor.

1.4. "Covered Software"

means Source Code Form to which **the initial Contributor has attached the
notice in Exhibit A**, the Executable Form of such Source Code Form, and
Modifications of such Source Code Form, in each case including portions
thereof.

---

Все ж написано :) Контрибьютор не обязательно владелец. "Покрытое лицензией ПО" - исходный код, к которому изначальный контрибьютор приложил Exhibit A.

Изначально владелец - ты. в целом любую последующую доработку можно расценивать как "модификацию":

> 1.10. "Modifications"
>      means any of the following:
>      a. any file in Source Code Form that results from an addition to,
>         deletion from, or modification of the contents of Covered Software; or
>      b. **any new file** in Source Code Form that contains any Covered Software.
