### ISSUE TITLE
Регламентное задание

### ISSUE THREAD

**Issue by Absolemus** [EvilBeaver/OneScript#1252]
@EvilBeaver
Я правильно понимаю, чтобы была возможность создавать РЗ в ОСкрипте, нужно подтянуть в зависимость библиотеку [Hangfire](https://github.com/EvilBeaver/OneScript.Web/blob/8168f44a228adb3a0157109294daf436fb5ec112/src/OneScript/BackgroundJobs/ScheduledJobsManagerContext.cs#L13), как это сделано в oscript.web? Или есть еще какие-то вещи, которые не давали возможности сделать РЗ ранее?

**Comment by EvilBeaver** [comment]
Регламентное задание это когда какой-то процесс висит в памяти и по таймеру просыпается и делает действие. Скрипт он же запустился, сделал и умер.

Ну т.е. если нужно "регламентное задание" то надо просто сделать в скрипте "Приостановить(1000)" и РЗ готовы. Иными словами, в скриптах ничего не мешает сделать РЗ кроме модели выполнения скриптов. Нужно держать запущенным процесс односкрипта. А зачем, если в любой ОС есть cron или Scheduler, который запустит скрипт по расписанию?

**Comment by Absolemus** [comment]
Я запускаю фоновое задание в котором есть: 
````bsl
Пока Истина Цикл
    // Какой-то код
    Приостановить(10000)
КонецЦикла
````

Например в библиотеке winow я не могу ожидать завершения своего фонового задания, я могу запустить его, а дальше winow будет слушать порт. Тем временем, если мое фоновое задание упадет, я никак об этом не узнаю и никак не смогу на это отреагировать. Hangfire  в этом случае никак мне не поможет?

**Comment by nixel2007** [comment]
Это решается запуском фонового задания из отдельного управляющего потока. Планировал сделать такое в осени

**Comment by Absolemus** [comment]
@nixel2007 а как добиться получения отдельного управляющего потока? Учитывая что главный поток на себя полностью забирает winow.

**Comment by EvilBeaver** [comment]
@Absolemus до запуска winow в стартовом скрипте сделать все что нужно, а потом уже стартовать Поделку из winow

**Comment by Macegor** [comment]
Можно пример кода создания отдельного потока?

**Comment by EvilBeaver** [comment]
> Можно пример кода создания отдельного потока?

`ФоновыеЗадания.Выполнить("ТелоЗадания")`

**Comment by nixel2007** [comment]
@Absolemus запустить его раньше рогатки winow.

**Comment by Macegor** [comment]
Так а если задание завершится с ошибкой, об этом никак не узнать, это получается нужно в основном потоке ожидать завершение задачи и если это системное, перезапускать

**Comment by Absolemus** [comment]
> @Absolemus запустить его раньше рогатки winow.

Так и сделал. Запустил свое ФЗ раньше winow. И оно работает. Но что если ФЗ упадет? Исполняющий код winow никогда не узнает о том, что надо перезапустить мое ФЗ.

**Comment by Absolemus** [comment]
https://github.com/EvilBeaver/OneScript/issues/1252#issuecomment-1381480085

Этот код должен работать весь период жизни приложения в отдельном потоке, и пока я не вижу, как это сделать максимально отказоустойчиво

**Comment by Absolemus** [comment]
В любом случае, @EvilBeaver, если ты говоришь что в OneScript РЗ не нужны, тогда я закрываю issue и ищу пути решения другим способом

**Comment by nixel2007** [comment]
@Absolemus обернуть весь код в попытку не предлагать?

**Comment by Absolemus** [comment]
@nixel2007, да, это единственный вариант. И в исключении логос кидает сообщение что все плохо. Главное мониторить логи)
