### ISSUE TITLE
Некорректное поведение ЗаписатьJSON->ПрочитатьJSON для значений Неопределено

### ISSUE THREAD

**Issue by jdeshin** [EvilBeaver/OneScript#1253]
Сериализация значений Неопределено процедурой ЗаписатьJSON преобразует их в null (это нормально), однако, последующая десериализация функцией ПрочитатьJSON преобразует null в значение ValueFactory.CreateNullValue() тогда как 1С преобразует в Неопределено т.е. в ValueFactory.Create()

**Comment by EvilBeaver** [comment]
Спасибо

**Comment by Mr-Rm** [comment]
1. OneScript **записывает** в json значение `NULL` (как null), хотя должно быть исключение по недопустимому типу.
2. Содержащийся в тестах файл "json-mock.json" содержит строку `"Неопределено": undefined`. OneScript, используя Newtonsoft.Json, **читает** это значение (как `Неопределено`), _что не соответствует стандарту JSON_.
1С при попытке ПрочитатьJSON из этого файла выбрасывает исключение.

**Comment by EvilBeaver** [comment]
Интересно, удастся ли выйти на связь с @alexkmbk и попросить его совершить доброе дело, которое он уже когда-то сделал, написав объекты Json?
