### ISSUE TITLE
v2: Ошибка в вычислении выражений

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1256]
**Опишите ошибку**
Ошибка в вычислении арифметических выражений: неверный порядок действий

**Воспроизведение ошибки**
```bsl
Рез = -1 / 1 * 2;
Сообщить(Рез);
```
_-0.5_

**Ожидаемое поведение**
_-2_

**Окружение**
 - Версия: v2 develop

**Дополнительная информация**
Влияет первый минус. `1 / 1 * 2` и `1 / -1 * 2` вычисляются верно.
В режиме native ошибка остаётся.

**Comment by EvilBeaver** [comment]
Это, наверное, я отломал, когда параметры аннотаций делал. Возьму.

**Comment by Mr-Rm** [comment]
Там неверно строится AST. Конкретнее - в DefaultBslParser.cs, начиная с BuildBinaryOperation()

**Comment by EvilBeaver** [comment]
Да, уже нашел и починил (наверное :)).
