### ISSUE TITLE
Функция Окр со вторым отрицательным параметром работает не так как в 1с.

### ISSUE THREAD

**Issue by beethlw** [EvilBeaver/OneScript#1258]
**Опишите ошибку**
Функция Окр со вторым отрицательным параметром работает не так как в 1с.

**Воспроизведение ошибки**
1. Запустить код:
а = Окр(1234, -2);
Сообщить(а);

Получим:
0.12

**Ожидаемое поведение**
В 1с после выполнения Окр(1234, -2), получаем 1 200.

**Окружение**
 - ОС: linux
 - Версия: 1.8.3.2

**Дополнительная информация**

**Comment by Mr-Rm** [comment]
```bsl
а = Окр(1234.567);
Сообщить(а);
```
_1234_
Хм.
```bsl
а = Окр(1234.567,null);
```
_Ошибка в строке: 1 / Преобразование к типу 'Число' не поддерживается}_
Нуу...
```bsl
а = Окр(1234.567, ,0);
```
_Ошибка в строке: 1 / Внешнее исключение (System.NotImplementedException): Метод или операция не реализована.}_
Ой.
```bsl
а = Окр(1234.567,2,РежимОкругления.Окр15как20);
```
_Ошибка в строке: 1,36 / Неизвестный символ: РежимОкругления}_
Ой-ой-ой!

**Comment by EvilBeaver** [comment]
Удивлен, что за 9 лет никому не понадобился 3-й параметр РежимОкругления

**Comment by Mr-Rm** [comment]
...и никто не заметил, что режим округления по умолчанию - не тот.

Не вынести ли эту функцию из встроенных в глобальный контекст? В ней нужна нетривиальная проверка параметров. Да ещё с перечислением.

**Comment by EvilBeaver** [comment]
А что там нетривиального в проверке параметров?

**Comment by Mr-Rm** [comment]
Обязательный второй параметр при наличии третьего; возможность передать первым и вторым параметром другой тип, например,  строку, приводимую к числу, но строго число или перечисление для третьего. 
Плюс общая проблема для всего движка - возможная передача перечисления другого типа:
```bsl
а = Окр(1234.567,2,СтатусСообщения.ОченьВажное); // работает
```

**Comment by Mr-Rm** [comment]
А вот это замечательное из 1С:
```bsl
Перем РежимОкругления;
РежимОкругления = Новый Структура("Окр15как20", 0);
а = Окр(1.5, 0, РежимОкругления.Окр15как20);
Сообщить("а="+а);
```
_а=1_

**Comment by EvilBeaver** [comment]
> А вот это замечательное из 1С

Да вы, батенька, хакир!

**Comment by Mr-Rm** [comment]
Это, конечно, не
```c
#define true false
```
но что-то близкое.
Возможность создать переменную с именем как у системного перечисления - неудачная идея

**Comment by EvilBeaver** [comment]
Это еще бог с ним, а вот то, что метод принимает данный define, как родной, действительно смешно. Говорят, что Сообщить в 1С так же делает с параметром СтатусСообщения

**Comment by Mr-Rm** [comment]
Тут фокус в том, что `Окр` третьим параметром принимает перечисление либо число.
`Сообщить` вторым - только перечисление.

**Comment by Mr-Rm** [comment]
Но если постараться:
```bsl
процедура СообщитьНеважное( СтатусСообщения )
	Сообщить("неважно-важно", СтатусСообщения.БезСтатуса );
конецПроцедуры

Статус = Новый Структура("БезСтатуса",СтатусСообщения.ОченьВажное);
СообщитьНеважное( Статус );

```
