### ISSUE TITLE
Ошибка упаковки в exe (oscript -make) на 1.8.3

### ISSUE THREAD

**Issue by nmnike** [EvilBeaver/OneScript#1264]
**Опишите ошибку**
При попытке упаковать скрипт в exe на версии 1.8.3 выходит ошибка: 
System.Runtime.Serialization.SerializationException: Тип "ScriptEngine.Machine.Values.StringValue" в сборке "ScriptEngine, Version=1.8.3.2, Culture=neutral, PublicKeyToken=null" не помечен как сериализуемый.
На версии 1.7.0 такой проблемы нет.

**Воспроизведение ошибки**
1. oscript -make
2. Подать на вход параметры: имя скрипта и имя exe файла.
3. Увидеть ошибку

**Ожидаемое поведение**
Такое же, как и на 1.7.0. Успешное создание exe файла

**Окружение**
 - ОС: Windows 10
 - Версия: 22H2
 - Версия OneScript: 1.8.3

**Скриншот**
![Screenshot](https://user-images.githubusercontent.com/25655511/225935558-6200b992-5da4-4b63-9b9d-93b5ca208c34.png)

**Comment by EvilBeaver** [comment]
@nmnike просьба проверить на сборке https://build.oscript.io/job/1Script/job/latest/28/artifact/built/
