### ISSUE TITLE
Отладчик: выражения в watch вычисляются без учета выбранного фрейма стека вызовов

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1266]
**Опишите ошибку**
При отладке в VSCode выражения в панели Watch вычисляются всегда в текущем контексте и не меняют значений при выборе другого фрейма стека вызовов, в отличие от локальных переменных.

**Воспроизведение ошибки**
1. Загрузить в VSCode код
```bsl
Процедура Проц()
  Перем А;
  А = 2;
КонецПроцедуры
А = 1;
Проц();

```
2. Установить breakpoint на `КонецПроцедуры` 
3. Добавить в "Watch" переменную `А` 
4. Запустить отладку
5. После останова в Variables `А: 2`, в Watch `А: 2`
6. В панели "Call Stack" выбрать фрейм `$entry`
в Variables значение поменяется на `А: 1`, в Watch останется `А: 2`

**Ожидаемое поведение**
Ожидается, что в Watch тоже поменяется на `А: 1`

**Окружение**
Версия: OneScript 1.8.4 latest, OneScript Debug v0.7.2, VSCode version: 1.76.2

**Дополнительная информация**
Действительно ли это issue, или так тоже номально? Но другие отладчики (например, от Исполнителя) при смене фрейма содержимое Watch соответственно пересчитывают.

_В любом случае, `VSCode.DebugAdapter\OscriptDebugSession.cs` содержит "спящий" баг_

**Comment by nixel2007** [comment]
Да, сталкивался с таким поведением watch и тоже хотелось, чтобы оно работало в рамках выбранного фрейма
