### ISSUE TITLE
В статистике выполнения кода не учитывается код исполненный фоновыми заданиями

### ISSUE THREAD

**Issue by sfaqer** [EvilBeaver/OneScript#1267]
**Опишите ошибку**
При запуске скрипта с указанием -codestat в итоговом файле не отражается исполнение кода фоновыми заданиями

**Воспроизведение ошибки**
1. Сделать сценарий с использованием фоновых заданий
2. Запустить сценарий oscript -codestat=stat.json СценарийСФоновымиЗаданиями.os
3. Убедится что в файле stat.json нет информации о коде исполненном фоновыми заданиями

**Ожидаемое поведение**
Ожидаем что в файле stat.json будет информация о коде исполненном фоновыми заданиями

**Окружение**
 - ОС:  Win11
 - Версия: 1.8.3

**Comment by EvilBeaver** [comment]
Вау, кто-то пользуется код-статом!

**Comment by sfaqer** [comment]
Так покрытие же: https://github.com/oscript-library/coverage
И профайлер:  https://github.com/oscript-library/codestatprofiler
=)
