### ISSUE TITLE
Классы коллекции

### ISSUE THREAD

**Issue by sfaqer** [EvilBeaver/OneScript#1269]
# Описание задачи
Хотелось бы иметь возможность реализовать собственные классы коллекции, которые можно было бы обходить циклом ДляКаждого

**Опишите вашу Цель, которую вы сможете достичь с помощью новой функциональности**
В рамках реализации библиотеки: https://github.com/sfaqer/collectionos были реализованы новые типы коллекций, хотелось бы предоставить пользователям библиотеки возможность обходить эти новые коллекции циклом `ДляКаждого`

**Опишите решение**
Моё предложение:
1. Добавить новую аннотацию `&Обходимое`/`&Iterable`
    Аннотация вещается на `ПриСозданииОбъекта()`, если класс помечен этой аннотацией то компилятор проверяет что у класса есть функция `Итератор()`/`Iterator()`
2. Добавить новую аннотацию `&Итератор`/`&Iterator`
    Аннотация вещается на `ПриСозданииОбъекта()`, если класс помечен этой аннотацией то компилятор проверяет что у класса есть 2 функции: `ЕстьСледующий()`/`HasNext()` и `Следующий()`/`Next()`
3. При обходе циклом по объекту который помечен как &Обходимое, движок вызывает на нём функцию Итератор() и проверяет что вернулся класс помеченный аннотацией &Итератор, если вернулось что-то другое, падаем в исключение, если вернулся всё же итератор, то используем его для реализации цикла `ДляКаждого` с помощью:
    ```bsl
    Пока Итератор.ЕстьСледующий() Цикл
        Элемент = Итератор.Следующий();
    КонецЦикла;
    ```

Как это будет выглядеть с точки зрения bsl кода:

```bsl

// src/Классы/МояКласснаяКоллекция.os

Функция Итератор() Экспорт
    Возврат Новый МойКлассныйИтератор();
КонецФункции

&Обходимое
Процедура ПриСозданииОбъекта()
КонецПроцедуры

```

```bsl

// src/Классы/МойКлассныйИтератор.os

Функция ЕстьСледующий() Экспорт
    Возврат Истина;
КонецФункции

Функция Следующий() Экспорт
    Возврат 1;
КонецФункции;

&Итератор
Процедура ПриСозданииОбъекта()
КонецПроцедуры

```

```bsl

МояКласснаяКоллекция = Новый МояКласснаяКоллекция();

Для каждого Элемент Из МояКласснаяКоллекция Цикл
    Сообщить(Элемент);
КонецЦикла;

// > 1
// > 1
// > 1
// > 1
// > 1
// ....

```

**Comment by nixel2007** [comment]
С учётом пункта 3 возможно надо доработать декоратор. Я не думаю, что сейчас он переносит аннотации над конструктором

**Comment by sfaqer** [comment]
> С учётом пункта 3 возможно надо доработать декоратор. Я не думаю, что сейчас он переносит аннотации над конструктором

Он и конструктор не переносит, приватные методы же нельзя вызвать, поэтому декоратор их игнорит.
Но в теории можно для магического метода сделать исключение и создать пустой конструктор с аннотациями

**Comment by Nivanchenko** [comment]
> > С учётом пункта 3 возможно надо доработать декоратор. Я не думаю, что сейчас он переносит аннотации над конструктором
> 
> Он и конструктор не переносит, приватные методы же нельзя вызвать, поэтому декоратор их игнорит. Но в теории можно для магического метода сделать исключение и создать пустой конструктор с аннотациями

А может попросить развязать руки рефлектору, и позволить работать с приватными методами, по аналогии с приватными полями =)

**Comment by sfaqer** [comment]
> > > С учётом пункта 3 возможно надо доработать декоратор. Я не думаю, что сейчас он переносит аннотации над конструктором
> > 
> > 
> > Он и конструктор не переносит, приватные методы же нельзя вызвать, поэтому декоратор их игнорит. Но в теории можно для магического метода сделать исключение и создать пустой конструктор с аннотациями
> 
> А может попросить развязать руки рефлектору, и позволить работать с приватными методами, по аналогии с приватными полями =)

Позволить работать вообще мысль не плохая, только с магическими методами типа конструктора всё равно надо работать по особенному.)

**Comment by Absolemus** [comment]
> 

Я дико извиняюсь за вмешательство. Но рефлектор умеет получать приватные методы. Или нужно чтобы рефлектор их именно мог вызвать?

[пруф](https://github.com/EvilBeaver/OneScript/blob/fb0a373ba6dfa3330bf4de68136adafebabce19b/tests/reflector.os#L147C42-L147C42)

**Comment by Nivanchenko** [comment]
> > 
> 
> Я дико извиняюсь за вмешательство. Но рефлектор умеет получать приватные методы. Или нужно чтобы рефлектор их именно мог вызвать?
> 
> [пруф](https://github.com/EvilBeaver/OneScript/blob/fb0a373ba6dfa3330bf4de68136adafebabce19b/tests/reflector.os#L147C42-L147C42)

Приватные методы рефлектор видит. А вот вызывать не может.
<img width="1033" alt="изображение" src="https://github.com/EvilBeaver/OneScript/assets/36507839/2ddf706f-5222-4bfd-86e0-880c12198903">

**Comment by EvilBeaver** [comment]
Раньше был обход через "Действие", но я это починил :)

**Comment by EvilBeaver** [comment]
Реализовано в #1385
