### ISSUE TITLE
ЗапуститьПриложение на макОС oscript 2.0

### ISSUE THREAD

**Issue by Nivanchenko** [EvilBeaver/OneScript#1272]
При выполнении инструкции 
```bsl
ЗапуститьПриложение("http://www.google.com");
```
на MacOS, оскрипт 2.0.0.341-rc2-27985426(Возможно на unix тоже) получаю ошибку:

`Внешнее исключение (System.ComponentModel.Win32Exception): An error occurred trying to start process 'http://www.google.com' with working directory '/Users/n.ivanchenko/Documents/repos/'. No such file or directory}`

Аналогичный код на 1.8.3 открывает браузер по указанному адресу.

**Comment by EvilBeaver** [comment]
ЕМНИП, .net использует функцию WinAPI ShellExecute, которой на МакОС нет, само собой. Любопытно, почему он выдал System.ComponentModel.Win32Exception, а не скажем PlatformNotSupportedException?

**Comment by EvilBeaver** [comment]
https://stackoverflow.com/questions/71977866/c-sharp-net-6-how-to-open-a-link-in-default-browser
https://stackoverflow.com/questions/21835891/process-starturl-fails/61035650#61035650

**Comment by Nivanchenko** [comment]
На 2.0.0.356-rc3-28069562 работает.
