### ISSUE TITLE
Неверно форматируется пустая дата

### ISSUE THREAD

**Issue by d-hurricane** [EvilBeaver/OneScript#1280]
**Опишите ошибку**
Функция "Формат", применяемая к пустой дате, использует из форматной строки только параметр "ДП", игнорируя "ДФ" и "ДЛФ". Это неверно, платформа 1С ведет себя иначе:
* если значение параметра "ДП" не пустое, возвращается именно оно;
* если значение параметра "ДП" пустое, пустая дата будет отформатирована в соответствии с параметрами "ДФ" и "ДЛФ", если таковые имеются.

**Воспроизведение ошибки**
Запустить код:
```bsl
Стр = Формат('0001-01-01', "ДФ='dd.MM.yyyy'; ДП=''");
Сообщить(Стр);

Стр = Формат('0001-01-01', "Л='ru_RU'; ДЛФ='DD'; ДП=''");
Сообщить(Стр);
```
Убедиться, что в консоль будут выведены две пустые строки.

**Ожидаемое поведение**
В консоли должны быть выведены следующие строки:
```
01.01.0001
1 января 0001 г.
```

**Окружение**
 - ОС: Windows 10 Pro, 22H2
 - Версия: 1.8.3.2

**Comment by EvilBeaver** [comment]
Верно ли я понял, что существует обход: указать в ДП то же самое, что в ДФ и он работает?

**Comment by d-hurricane** [comment]
Да. Т.е. для моих примеров способ обхода такой:
```bsl
Стр = Формат('0001-01-01', "ДФ='dd.MM.yyyy'; ДП='01.01.0001'");
Сообщить(Стр);

Стр = Формат('0001-01-01', "Л='ru_RU'; ДЛФ='DD'; ДП='1 января 0001 г.'");
Сообщить(Стр);
```

**Comment by EvilBeaver** [comment]
@dmpas сможешь посмотреть?

**Comment by dmpas** [comment]
> @dmpas сможешь посмотреть?

https://github.com/EvilBeaver/OneScript/blob/0a4f66d07d2ba3223f213592b958c53fd4779b26/src/OneScript.Core/Commons/ValueFormatter.cs#L425

собственно, так и есть. Вся локальная часть игнорится, возвращается пустая строка.

**Comment by Mr-Rm** [comment]
```bsl
Стр = Формат('0001-01-01');
```
_Ошибка в строке: 1,28 / Недостаточно фактических параметров_
**?!**

**Comment by EvilBeaver** [comment]
> ```bsl
> Стр = Формат('0001-01-01');
> ```
> 
> _Ошибка в строке: 1,28 / Недостаточно фактических параметров_ **?!**

Второго аргумента нет.

**Comment by Mr-Rm** [comment]
>Синтаксис:
Формат(<Значение>, <ФорматнаяСтрока>)
Параметры:
<Значение> (обязательный)
Тип: {Число}, {Дата}, {Булево}. 
Форматируемое значение.
<ФорматнаяСтрока> **(необязательный)**
Тип: {Строка}.

**Comment by EvilBeaver** [comment]
> <ФорматнаяСтрока> **(необязательный)**

``¯\_(ツ)_/¯``

**Comment by dmpas** [comment]
Ща зафиксим по-бырому.

**Comment by nixel2007** [comment]
> Ща зафиксим по-бырому.

Three years later (c)

**Comment by dmpas** [comment]
@nixel2007 тесты вон уже накидываю
![image](https://user-images.githubusercontent.com/5665433/232208995-2d828c3e-e071-481f-9a99-9c2150b69ea8.png)
