### ISSUE TITLE
Функция ПолучитьИмяВременногоФайла() без параметров не устанавливает расширение ".tmp"

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1290]
**Опишите ошибку**
Функция ПолучитьИмяВременногоФайла() без параметров не устанавливает для временного файла расширение по умолчанию ".tmp"

**Воспроизведение ошибки**
```bsl
ИмяФайла = ПолучитьИмяВременногоФайла();
Сообщить(ИмяФайла);
```
Получаем нечто вроде
_C:\Users\user\AppData\Local\Temp\iax2jdsk.c2u_ (или _/tmp/iax2jdsk.c2u_)

**Ожидаемое поведение**
_C:\Users\user\AppData\Local\Temp\iax2jdsk.**tmp**_

**Окружение**
- OC: Windows, Linux
 - Версия: все до 1.8.4 latest, v2 develop

**Comment by EvilBeaver** [comment]
Так оно вроде и не должно... tmp регламентировано в 1С разве?

**Comment by Mr-Rm** [comment]
Из СП / EDT help:
> Если параметр не задан, то создается временный файл с расширением по умолчанию (.tmp).
