### ISSUE TITLE
Флаг --native для приложения oscript

### ISSUE THREAD

**Issue by Nivanchenko** [EvilBeaver/OneScript#1295]
Как мне кажется, было бы здорово, если бы можно было запускать оскрипт вот так
```
oscript --native myfile.os
```
И тогда все загружаемые сценарии воспринимались так, как буд-то у них включена деректива ```#native```.

- В первую очередь, так было бы удобно тестировать новый режим. Есть куча библиотек и скриптов, которые можно прогнать через новый режим и поймать багули, не влезая в код.
- ~~В вскод сейчас синтаксическая проверка ломается на ```#native```~~
- В перспективе, когда нейтив будет лишен багов, такой флаг может бесплатно подбавить скорости имеющимся скриптам(с оговорками естесно)

**Comment by nixel2007** [comment]
> • В вскод сейчас синтаксическая проверка ломается на #native 

А вот это стоит зарепортить отдельно

**Comment by Nivanchenko** [comment]
> А вот это стоит зарепортить отдельно

Кажется тут я сам затупарил, и плагин не тем оскриптом делал -check...

**Comment by EvilBeaver** [comment]
Поскольку native это считай другой диалект, несовместимый с основным, я с опаской отношусь к такому ключу. С высокой вероятность скрипт не заработает. Наличие ключа подразумевает, что это именно "режим", котороый можно переключать. На самом же деле, это "файл написан на другой версии bsl", именно поэтому это директива на исходнике. Ключ добавить можно, но боюсь, он будет вводить в заблуждение

**Comment by EvilBeaver** [comment]
@all discuss

**Comment by Nivanchenko** [comment]
Если в финальном варианте вот такой синтаксис будет обязательным https://github.com/EvilBeaver/OneScript/issues/1277. То наверное да, такой флаг будет бесполезен. Если синтаксис не обязательный, то почему бы и нет. Назовем это не режим, а как-то по другому. Мои предложения в том, что удобно играясь флагом и не меняя исходники можно очень много прогнать через нейтив и отловиться всякого, и включать возможность подебажить.

**Comment by nixel2007** [comment]
Как вариант, добавить не в cli, а в oscript.cfg. Там его найдёт только тот, кому это действительно надо.

**Comment by EvilBeaver** [comment]
> Как вариант, добавить не в cli, а в oscript.cfg. Там его найдёт только тот, кому это действительно надо.

Туда я тоже планировал. Можно попробовать и то и это, на самом деле.

**Comment by EvilBeaver** [comment]
@Nivanchenko добавил конфиг-параметр `runtime.default`. Его можно указать либо в oscript.cfg, либо через стандартную переменную настроек

```cmd
set OSCRIPT_CONFIG=runtime.default=native
oscript my-test-script.os
```

Так же добавлена "отключающая" директива под названием `stack`, которая делает обратное: гвоздями прибивает файл к стековому рантайму, если глобально включен нативный.

```bsl
#stack

Процедура ЯБудуВсегдаВыполнятьсяОбычнымРантаймом()

КонецПроцедуры
```

**Comment by nixel2007** [comment]
Опять в BSL parser тащить :D

**Comment by Nivanchenko** [comment]
> Опять в BSL parser тащить :D

Тоже самое подумал 😁

**Comment by EvilBeaver** [comment]
А почему бы там не сделать абстрактные аннотации в начале os-модулей? У меня сейчас парсится `#DIRECTIVENAME ANYTHING\n`

**Comment by nixel2007** [comment]
У тебя честный препроцессор :)

**Comment by EvilBeaver** [comment]
Нет, он довольно подлый и хитрый, и притворяется еще и синтаксисом аннотаций
