### ISSUE TITLE
Работас процессами в 2.0

### ISSUE THREAD

**Issue by Nivanchenko** [EvilBeaver/OneScript#1299]
2.0.0.362-rc3-28083335 MacOS(возможно линух тоже)

Вот такой код работает и получает версию оскрипта хорошо при запуске 1.8

```bsl
СтрокаЗапуска = "sh -c 'oscript -version'";
РабочийКаталог = ".";
ПерехватыватьПотоки = Истина;
ПеременныеСредыПроцесса = Новый Соответствие();

Процесс = СоздатьПроцесс(СтрокаЗапуска, РабочийКаталог, ПерехватыватьПотоки, ПерехватыватьПотоки, , 
				ПеременныеСредыПроцесса);

Процесс.Запустить();
Приостановить(1000);
ОчереднаяСтрокаВывода = Процесс.ПотокВывода.Прочитать();
ОчереднаяСтрокаОшибок = Процесс.ПотокОшибок.Прочитать();

Сообщить(ОчереднаяСтрокаВывода);
Сообщить(ОчереднаяСтрокаОшибок);
```

Но на 2.0 я получаю из потока ошибок следующее
```
-version': -c: line 0: unexpected EOF while looking for matching `''
-version': -c: line 1: syntax error: unexpected end of file
```

Поймал багу на библиотеке 1commands. т.е. она не работает совсем.

**Comment by EvilBeaver** [comment]
Текст ошибки выглядит, как будто его выдает sh. И он ругается на незакрытую одинарную кавычку.

**Comment by Nivanchenko** [comment]
> Текст ошибки выглядит, как будто его выдает sh. И он ругается на незакрытую одинарную кавычку.

Да, что-то непонятное, может там под капотом дотнет коверкает строку запуска? на 1.8 то работает. могу я как-то помочь в расследовании ?

**Comment by EvilBeaver** [comment]
> могу я как-то помочь в расследовании ?

Если только отладчиком залезть в момент парсинга строки... В метод СоздатьПроцесс в движке

**Comment by Nivanchenko** [comment]
Для истории и будущего ниндзя программиста. Отдебажил движковый объект там с параметрами все хорошо. Где-то ниже проблемы. Обойти можно если заменить одинарные кавычки двойными.

**Comment by dvakor** [comment]
@EvilBeaver в неткоре поменялся парсер аргументов походу, но если память не подводит, то в целом рекомендуется юзать AgrumentList, который является коллекцией строк (в данный момент аргументы пробрасываются в Arguments). Собственно тут 2 варика

1) Принять это как необратимое изменение
2) Написать свой парсер аргументов, который бы из строки коллекцию аргументов выплевывал

пример выхлопа парсера думается должен быть таким

```
-c 'oscript -version' = ["-c", "'oscript -version'"]
-c oscript -version = ["-c", "oscript", "-version"]
-c '"oscript" -version' = ["-c", "'\"oscript\" -version'"]
-c "'oscript' -version" = ["-c", "\"'oscript' -version\""]
```

что думаешь?

на коленке накидал парсер и проверил несколько кейсов, вроде работает адекватно :)

**Comment by EvilBeaver** [comment]
Ну тогда накидывай тестов и вперед!

**Comment by EvilBeaver** [comment]
@dvakor не знаю почему, но коммит 746f28d3, который влил парсер ком. строки, ломает тест process.os (японские буквы)

![image](https://github.com/EvilBeaver/OneScript/assets/2657561/6b6cadf2-8b4b-4f0c-8a83-6d29265655a7)

Предыдущий коммит 39f9f0f2 (тоже твой с кодировкой в отладчике) исправный.

**Comment by dvakor** [comment]
@EvilBeaver Принял, гляну что там

**Comment by JohnyDeath** [comment]
Обнаружился неправильный разбор кавычек аргументов. На предыдущих версиях работает нормально.
Текст скрипта:
```bsl
#Использовать 1commands

командаЗапуска = Новый Команда;
командаЗапуска.УстановитьКоманду("echo");
командаЗапуска.ДобавитьПараметр("""Привет, Мир""");
кодВозврата = командаЗапуска.Исполнить();
выхлоп = командаЗапуска.ПолучитьВывод();
Сообщить(СтрШаблон("Код возврата = %1, Выхлоп: %2", кодВозврата, выхлоп));
```
вывод для разных версий oscript отличается. В версии 2.0 после этих изменении "Привет, Мир" выводится без кавычек:
![image](https://github.com/EvilBeaver/OneScript/assets/5936030/5d62d926-b24e-4bf7-b3de-0abdf4467230)

**Comment by JohnyDeath** [comment]
Вариант решения от ИИ (плагин Codium в VSCode)
```csharp
private void HandleQuotes(char quoteChar)
{
    if (_isInQuotes && quoteChar == _currentQuote)
    {
        _isInQuotes = false;
    }
    else if (!_isInQuotes)
    {
        _isInQuotes = true;
        _currentQuote = quoteChar;
    }
    else
    {
        PushChar(quoteChar);
    }
}
```
Сам я это конечно же не тестировал.

**Comment by EvilBeaver** [comment]
Ты предлагаешь нам выяснить, что написал железный джун? А если он написал хорошо, нам уже подыскивать вакансию проституток?

**Comment by EvilBeaver** [comment]
Нашел дичайше интересное чтиво по теме https://web.archive.org/web/20220629212707/https://windowsinspired.com/understanding-the-command-line-string-and-arguments-received-by-a-windows-program/

> Attempting to find pairs of double quote characters that enclose meaningful chunks of text is possibly the biggest conceptual mistake that people make when looking at a complicated command line.

**Comment by nixel2007** [comment]
Нормальный такой наброс на вентилятор

**Comment by EvilBeaver** [comment]
> Нормальный такой наброс на вентилятор

Приобщайся к прекрасному :)

**Comment by nixel2007** [comment]
С нуля я бы решал эту задачу через стек и удвоение кавычек для экранирования, но судя по статье это не posix way
