### ISSUE TITLE
Пропуск обязательных параметров встроенных функций

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1302]
**Опишите ошибку**
Для встроенных функций с более, чем одним параметром, пропуск обязательных параметров не диагностируется при компиляции, а падает в рантайме с нерелевантной ошибкой (или даже вовсе не падает).

**Воспроизведение ошибки**
1. 
```bsl
Сообщить("Старт");
Рез = Лев(, 0);
Сообщить(Рез);
```
v1.8 latest:
_Старт
{Модуль C:\_lab\OneScript\tst-defarg2.os / Ошибка в строке: 2 / Внешнее исключение (System.NotImplementedException): Метод или операция не реализована.}_

v2 develop **StackVM**:
_Старт_

2. 
```bsl
Сообщить("Старт");
Рез = ДобавитьМесяц(, 2);
Сообщить(Рез);
```
v1.8 latest:
_Старт
{Модуль C:\_lab\OneScript\tst-defarg2.os / Ошибка в строке: 2 / Внешнее исключение (System.NotImplementedException): Метод или операция не реализована.}_

v2 develop **StackVM**:
_Старт
{Модуль C:\_lab\OneScript\tst-defarg2.os / Ошибка в строке: 2 / Преобразование к типу 'Дата' не поддерживается}_

**Ожидаемое поведение**
Ошибка при компиляции/попытке запуска (сообщения "Старт" не должно быть)
1С не сохраняет модуль с такой ошибкой с диагностикой _"Ожидается выражение"_
Но в 1С тоже есть аналогичное: по документации
>Сообщить(<ТекстСообщения>, <Статус>)
Параметры:
<ТекстСообщения> (обязательный)
Тип: [Строка](v8help://SyntaxHelperLanguage/def_String).

однако код
```bsl
Сообщить( , );
```
спокойно отрабатывает. В OneScript тоже.

**Дополнительная информация**
OneScript v2 native _сейчас_ выдает ошибку:
_{Модуль C:\_lab\OneScript\tst-defarg2.os / Ошибка в строке: 3,5 / Ошибка компиляции статического модуля
OneScript.Compilation.CompilerException: {Модуль C:\_lab\OneScript\tst-defarg2.os / Ошибка в строке: 3,10 / Пропущен обязательный параметр 1 'str'}
Рез = Лев(,0);_

**Comment by EvilBeaver** [comment]
@Mr-Rm чтобы не делать двойную работу: я могу это себе взять или ты хочешь починить?

**Comment by Mr-Rm** [comment]
Есть готовый фикс, но выглядит как заплатка. Сделаю PR, напишу

**Comment by EvilBeaver** [comment]
@Mr-Rm Это не интуитивно, но `Сообщить( , )` считается корректной конструкцией. Оба параметра переданы и равны некоторому магическому значению (у нас называется skipped). Т.е. это в V2 я про такое забыл, а при реализации V1 специально так делал.
