### ISSUE TITLE
Сравнение перечислений

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1313]
Допускается сравнение перечислений на больше/меньше, в том числе разных типов.

**Воспроизведение ошибки**
```bsl
Если ЦветКонсоли.Черный < СтатусСообщения.БезСтатуса Тогда
	Сообщить("меньше");
Иначе
	Сообщить("не меньше");
КонецЕсли;
```
OneScript v1.8:
_меньше_
OneScript v2:
_не меньше_

**Ожидаемое поведение**
1C (runtime):
_Операции сравнения на больше-меньше допустимы только для значений совпадающих примитивных типов (Булево, Число, Строка, Дата)_

**Дополнительная информация**
В OneScript v2 native перечисления **вообще не работают**, никак.

_Про перечисления ещё много можно написать_

**Comment by EvilBeaver** [comment]
Странно. Явно же оно специально было сделано, не случайный баг. @nixel2007 @theshadowco могло такое быть, что раньше (2013-2014) перечисления можно было сравнивать?
