### ISSUE TITLE
При исполнении делегата в фоновом задании, результат исполнения делегата не помещается в Результат фонового задания

### ISSUE THREAD

**Issue by sfaqer** [EvilBeaver/OneScript#1317]
**Опишите ошибку**
Если выполнить делегат в фоновом задании то результат исполнения делегата не помещается в результат фонового задания, судя по отладке ФЗ корректно заходит в метод. но результат игнорируется.

**Воспроизведение ошибки**
```bsl
Функция Тест(Парам1, Парам2) Экспорт // Объявляем функцию

	Возврат Парам1 + Парам2;

КонецФункции

Действие = Новый Действие(ЭтотОбъект, "Тест"); // Создаём делегат на функцию

Парам = Новый Массив;
Парам.Добавить(1);
Парам.Добавить(2);

ФЗ = ФоновыеЗадания.Выполнить(Действие, "Выполнить", Парам); // Выполняем делегат в фоновом задании

ФЗ.ОжидатьЗавершения(); // Ждём завершения ФЗ

Сообщить("Результат = " + ТипЗнч(ФЗ.Результат)); // Убеждаемся что результат неопределено

// > Результат = Неопределено

```

**Ожидаемое поведение**
Ожидаем что в поле Результат фонового задания будет результат исполнения делегата

**Окружение**
 - ОС: Win 11
 - Версия: 1.8.3.2

**Дополнительная информация**

**Comment by nixel2007** [comment]
А туда разве можно передать делегат первым параметром? Он же объект скрипта ждёт, разве нет?

**Comment by sfaqer** [comment]
> А туда разве можно передать делегат первым параметром? Он же объект скрипта ждёт, разве нет?

![image](https://github.com/EvilBeaver/OneScript/assets/32082417/7730012e-0b40-499c-82fd-aff2da827294)

И даже работать будет, только результат игнорит

**Comment by EvilBeaver** [comment]
Я не очень понял, зачем передавать делегат в ФЗ, когда можно передавать сразу целевой метод делегата?

**Comment by nixel2007** [comment]
Унификация. Делегат - удобный контейнер для указателя на функцию (против структуры объект+имя метода). Лямбдас/флюент работает на делегатах

**Comment by sfaqer** [comment]
> Я не очень понял, зачем передавать делегат в ФЗ, когда можно передавать сразу целевой метод делегата?

Для того что бы из апи который принимает делегат запускать ФЗ который выполнит этот делегат, ну т.е на входе в условную библиотеку может не быть объекта и метода а только делегат, а из самого делегата информацию о объекте и методе достать нельзя насколько я понимаю
