### ISSUE TITLE
Проблема с кодировкой при запуске отладки на MacOS

### ISSUE THREAD

**Issue by dvakor** [EvilBeaver/OneScript#1318]
**Опишите ошибку**
При запуске отладки сообщения в debug console вылетают в некорректной кодировке

**Воспроизведение ошибки**
1) Открыть vs code
2) Создать файл с кодом:

```
Сообщить("Привет");
```
3) В окне debug output будет выведено ?????

**Ожидаемое поведение**
Русские буквы должны отображаться корректно

**Окружение**
 - ОС: MacOS
 - Версия: Скорее всего любая :)

**Дополнительная информация**
Проблема связана с изменение поведения в Encoding.Default в класическом фреймворке и нет коре
- В классическом информация берется из системы, в случае мак ос это будет US-ASCII, если не указана LC_ALL
- В случае нет кора, она всегда UTF-8

Соответственно DebugAdapter в данный момент идет на классическом фреймворке, а oscript на нет коре, что и приводит к проблеме.

Временное решение: установить переменную окружения LC_ALL, по умолчанию она не заполнена и моно на мак ос всегда возращает US-ASCII

**Comment by EvilBeaver** [comment]
Думаю, надо везде для отладчика сделать UTF-8, в первой версии (на классическом), во второй (на коре) и в дебаг-адаптере
