### ISSUE TITLE
Автоподстановщик и IDE

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#132]
Originally reported by: **Alexey Lustin (Bitbucket: [allustin](http://bitbucket.org/allustin), GitHub: [allustin](http://github.com/allustin))**

---

По мере использования и по мере наращивания функционала становится необходимо реализовать полноценную инфраструктуру для кодирования

Необходимо:
1. IDE
2. Отладчик скриптов
3. **Автоподстановщик кода**

Стиль реализации подобного можно использовать из Go

структура реализации следующая:
1. IDE на выбор - Sublime, atom, IntelligentIDE, Eclipse
2. плагин/пакет для IDE
3. сервер для автоподстановки

Пример сервера автоподстановки http://nosmileface.ru/images/gocode-demo.swf

Соответственно для подобного необходимо реализовать аналоги 2-ух пакетов из Go
- Обработчик исходного кода http://golang.org/pkg/go/parser/
- Искатель "токенов" http://golang.org/pkg/go/token/ или скорее Рефлектор

P.S. Данная задача - всего-лишь один из вариантов реализации будущей поддержки IDE

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/132

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

R U kiddin' me?  :)

Вообще, если без шуток, то @dmpas встраивал 1Script в IDE Geany, так что, некоторый опыт в создании плагинов к IDE у него есть. Но эпичность идеи нагоняет на меня скепсис. Одному мне такое точно не потянуть. @dmpas, что скажешь?

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

Я не делал плагин к Geany, я брал Geany и пилил его в направлении заточить его под односкрипты. Запилить подсветку кода, вычленение символов и подстановка кода - это не так уж и сложно, вопрос только в том, насколько хорошо документирована та или иная IDE.
Из предложенных лично мне больше нравится Eclipse, но раз мы крутимся вокруг .Net, почему бы не посмотреть в сторону MonoDevelop.
Вот отладчик делать - вот это действительно сложно.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

С MonoDevelop, кажется, идёт дело. Документации по привязке своих языков, как кот наплакал, но на неделе должно что-то получиться.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

Набросал расширение для MonoDevelop (у меня 5.7, потому пока для него). Пока только подсветка кода. Если есть потребность, запилю разбор символов, автоподстановку, свёртку кода.
[Ссылка](https://bitbucket.org/dmpas/monoonescriptbinding)

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

@dmpas, круто! насколько я понял, расширения пишутся так же на C#? Тогда лексер можно взять с ветки 2.0 он работает довольно шустро, проверяли на модуле в 50к строк весом 5Мб

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

@EvilBeaver да, на C# - в этом существенный плюс :)
вот с лексером тут не всё так просто. Лексер в компиляторе предполагает, что файл синтаксически верен, и в случае чего капризно вываливается с SyntaxError, тогда как лексер в редакторе по-умолчанию должен считать, что код кривой, неправильный и вообще на другом языке :)

PS. Хотя скорее всего твой лексер и будет содран чуть ли не полностью :)

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Нет, как раз лексер в ветке 2.0 заточен под то, чтобы код был кривой и на другом языке. Я там попытался сделать "пропуск" некорректных строк, по тому же принципу, как в 1С при синтаксическом контроле. Но случая протестировать пока не представилось :) Скорее всего, прямо сходу не заработает, но задел там есть.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

Ещё один тонкий момент. Когда я разбор символов прикручивал к джину, там нужно было делать следующим образом: редактор может вызывать лексер с любой строки, передав, собственно, номер строки и состояние, в котором была завершена предыдущая строка. Таким образом файл не парсится каждый раз целиком.

PS. Пример, как у меня в Джине выглядит разбор символов:
![screenshot.png](https://bitbucket.org/repo/yMLGMn/images/465651744-screenshot.png)

**Comment by EvilBeaver** [comment]
_Original comment by_ **Alexey Lustin (Bitbucket: [allustin](http://bitbucket.org/allustin), GitHub: [allustin](http://github.com/allustin))**:

---

@dmpas Потребность есть. Документация к сожалению куцая - в основном сводится только к http://www.monodevelop.com/developers/articles/language-addins/
и разбросанным по просторам интернета git репозиториям

по расширению - пришлось по ProjectTypeGuid догадаться что необходимо поставить плагин AddInMaker

![2015-04-07 06-27-09 Скриншот экрана.png](https://bitbucket.org/repo/yMLGMn/images/2101567942-2015-04-07%2006-27-09%20%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0.png)

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

@allustin Про AddInMaker написано на сайте: [Creating a Simple Add-In](http://www.monodevelop.com/developers/articles/creating-a-simple-add-in/)

С разбросанными по интернету расширениями тоже довольно весело: приходится текстовым редактором вставлять в файл проекта строчку с ProjectTypeGuid, чтобы проект собирался и отлаживался, как расширение.

А чтобы сильно не лазить по интернетам, можно взять исходники самого Девелопа - я оттуда бессовестно сдираю код с VBNetBinding.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Все-таки, имхо, для ставить скриптинга целую IDE как-то тяжеловато. Адаптация sublime мне кажется более выгодной в плане отношения скорость разработки/полезность. Хотя, конечно, не так увлекательно :)

**Comment by EvilBeaver** [comment]
_Original comment by_ **Alexey Lustin (Bitbucket: [allustin](http://bitbucket.org/allustin), GitHub: [allustin](http://github.com/allustin))**:

---

@EvilBeaver я конечно с тобой согласен, что MonoDevelop тяжеловат. Но применительно к проекту добавляет эффект синергии. Из исходников пока сборку всё также победить не удалось. Но проблема явно одна:

```
#!c#

namespace ScriptEngine.Machine.Contexts
{
    class ManagedCOMWrapperContext : COMWrapperContext
    {

```

```
#!c#

Machine/Contexts/ManagedCOMWrapperContext.cs(9,38): error CS0246: The type or namespace name `COMWrapperContext' could not be found. Are you missing an assembly reference?
```

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

Нужен штурм. Или голосовалка.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Согласен с @allustin. Делая плагин к IDE мы получаем исследовательский интерес и опыт. Плюс отладчик нам, наверное, все же понадобится, а значит и IDE для просмотра переменных - тоже. А sublime я наверное добью. Там нетривиально настраивается подсветка и подсказка, но доки есть, значит все возможно.

Насчет сборки под Mono - там странное поведение компилятора. Он ругается на то, что не переопределен метод в каком-то абстрактном классе из Reflection, но этот метод приватный и не может никак переопределяться. Короче, какая-то байда :) Вся эта прелесть вылезает в части работы с COM, который под Linux как-бы и не нужен. Но без этого куска у нас получается неполноценная assembly, которую нельзя скомпилировать один раз и запускать в любой среде.
Сборка под Mono сейчас тупо вырезает проблемные куски препроцессором, поэтому, скорее всего, ты и получаешь указанную ошибку при компиляции. ManagedCOMWrapperContext - это новый класс, в нем тоже надо поставить условие препроцессора. Однако это не решит основную проблему.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

Тут вот [новость](http://infostart.ru/public/344802/) объявилась, что уже в бетке вышел конфигуратор под Eclipse. Соотвественно, пока не поздно, может и правда начать пилить расширение под него, благо он в некотором будущем будет стоять у большинства 1С-ников? Я, если честно, не ожидал, что это так скоро будет :-)

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

@dmpas Они делали на базе XText. https://eclipse.org/Xtext/ Я пока не изучал, что за зверь, но вроде как раз, то, что нужно.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

@EvilBeaver Попробую на неделе одолеть.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

@dmpas , @allustin надо бы сформулировать требования к такой IDE и сценарии использования. Т.е. четко представить себе, чем этот продукт будет являться и чем НЕ будет.
Предлагаю сформулировать.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

Обязательная часть: подсветка и подстановка кода. По крайней мере это сейчас уже можно пилить, а остальное по мере обсуждения.

**Comment by dmpas** [comment]
Эту-то закрыть можно, я думаю?

**Comment by EvilBeaver** [comment]
Благодаря @nixel2007, думаю можно )
