### ISSUE TITLE
Не работают параметризованные исключения в v2

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#1322]
**Опишите ошибку**

Параметризованные исключения не поддержаны

**Воспроизведение ошибки**

```bsl
ВызватьИсключение Новый ИнформацияОбОшибке("тратата", Параметры)
```

**Ожидаемое поведение**

1. Компилируется
2. Выбрасывается параметризованное исключение

**Окружение**
 - Версия: v2-rc3

**Comment by Mr-Rm** [comment]
Это  же в native? Проблема не в исключении:
```bsl
#native
Информация = Новый ИнформацияОбОшибке("тратата", 0);

```
_System.InvalidCastException: Unable to cast object of type 'ScriptEngine.Machine.Contexts.ExceptionTemplate' to type 'ScriptEngine.Machine.Contexts.ExceptionInfoContext'.
   at OneScript.Native.Runtime.DynamicOperations.StrictConstructorCall[T](ITypeManager typeManager, IServiceContainer services, String typeName, BslValue[] args) in C:\_Repo\OneScript\src\OneScript.Native\Runtime\DynamicOperations.cs:line 163_

Тут не срабатывает (точнее, наоборот - некорректно срабатывает) типизация. В операторе `Новый` указан тип `ИнформацияОбОшибке` (ExceptionInfoContext), а фактически конструктор (Create) возвращает ExceptionTemplate, который не приводится к ExceptionInfoContext.
То, что переменная `Информация` получает тип ExceptionInfoContext, значения не имеет. До присваивания даже не доходит.

**Comment by EvilBeaver** [comment]
Там не только это, там и момент обработки при catch тоже отсутствует. Иными словами полностью не сделана функциональность
