### ISSUE TITLE
Похоже выходные параметры методов COM объектов не считываются

### ISSUE THREAD

**Issue by tormozit** [EvilBeaver/OneScript#1324]
**Опишите ошибку**
Похоже выходные параметры методов COM объектов не считываются. В 1С тот же код возвращает считанное значение ключа реестра.

**Воспроизведение ошибки**
```
        РеестрОС = ПолучитьCOMОбъект("winmgmts:{impersonationLevel=impersonate}!\\.\root\default:StdRegProv");
        ИмяФайлаКласса = "";
        РеестрОС.GetStringValue("2147483650", "SOFTWARE\Classes\CLSID\{e92b75e3-2ea1-4fec-b493-cef3ec59fca6}\LocalServer32",, ИмяФайлаКласса); // 2147483650 = HKEY_LOCAL_MACHINE
```

**Ожидаемое поведение**
В переменной ИмяФайлаКласса появилось значение ключа реестра.

**Окружение**
 - ОС: Windows 10

**Comment by tormozit** [comment]
Активно пользую ОСкрипт для работы с COM методами. Ощущаю часто нехватку этой возможности.
Какие перспективы?

**Comment by EvilBeaver** [comment]
Постараюсь сегодня вечером посмотреть

**Comment by tormozit** [comment]
Где взять сборку для проверки? Или может уже скоро релиз намечается? =)

**Comment by Nivanchenko** [comment]
> Где взять сборку для проверки? Или может уже скоро релиз намечается? =)

Все сборки можно качать тут https://build.oscript.io/job/1Script/

**Comment by EvilBeaver** [comment]
> Где взять сборку для проверки?

Все сборки "в разработке" находятся для версии 1.х тут: https://oscript.io/downloads/archive/latest-dev
Для версии 2.0 - тут: https://oscript.io/downloads/archive/night-build
