### ISSUE TITLE
Непонятная ошибка при пропущенном параметре в вызове метода

### ISSUE THREAD

**Issue by tormozit** [EvilBeaver/OneScript#1325]
**Опишите ошибку**
https://turboconf.atlassian.net/browse/TCRDT-12
Выполняю в среде TurboConf скрипт

`ТурбоКонф.НачатьВызовВнешнегоОкнаАсинх("Выбор объекта метаданных", 2000, АктивноеОкно, РежимОткрытияВнешнегоОкна.Диалог, , МодулиИР.ирКэш.ИдентификаторПроцессаОСЛкс());`

Получаю ошибку
```
ScriptEngine.Machine.ExternalSystemException: {Модуль <string AD00C64C> / Ошибка в строке: 192 / Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}    
			ТурбоКонф.НачатьВызовВнешнегоОкнаАсинх("Выбор объекта метаданных", 2000, АктивноеОкно, РежимОткрытияВнешнегоОкна.Диалог,, МодулиИР.ирКэш.ИдентификаторПроцессаОСЛкс());
 ---> System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в ScriptEngine.Machine.Contexts.ContextMethodsMapper1.InternalMethInfo.ConvertParam[T](IValue value, Object def)    в lambda_method(Closure , Api , IValue[] )    в ScriptEngine.Machine.Contexts.AutoContext1.CallAsProcedure(Int32 methodNumber, IValue[] arguments)
   в ScriptEngine.Machine.MachineInstance.ResolveMethodProc(Int32 arg)
   в ScriptEngine.Machine.MachineInstance.MainCommandLoop()
   --- Конец трассировки внутреннего стека исключений ---
   в TurboConf.HostApplication.ApplicationForm.ShowExceptionInfo(Exception exc)
   в ScriptEngine.HostedScript.Process.Start()
   в TurboConf.HostApplication.ApplicationForm.ExecuteScript(Script script, Keys ctrl, Keys alt, Keys shift, ScreenForm statusForm, String entryPoint)

```
**Ожидаемое поведение**
Понятная формулировка ошибки, например "Пропущен обязательный параметр №5 (ИспользоватьРегулярноеВыражение)"

**Окружение**
 - ОС: Windows 10

**Дополнительная информация**

**Comment by nixel2007** [comment]
Для начала нужно движок обновить в турбоконфе с 1.7 до актуальных версий.

**Comment by EvilBeaver** [comment]
@nixel2007 тут скорее не в версии дело, а в классе турбоконфа и его интеграции с односкриптом. Нужен Михаил @bolsun для расследования

**Comment by bolsun** [comment]
Метод выглядит так

        [ContextMethod("НачатьВызовВнешнегоОкнаАсинх", "StartExternalWindowCallAsync")]
        public void StartExternalWindowHandlingAsync(string title, int timeout, long confWnd,
            ExternalWindowOpeningMode mode, bool regex, long pid = 0)
        {
        }
        
Если пропустить обязательный параметр regex, то до выполнения метода дело не доходит. Oscript падает раньше.

ТурбоКонф.НачатьВызовВнешнегоОкнаАсинх("Моя форма из 1С", 1000, АктивноеОкно, РежимОткрытияВнешнегоОкна.Диалог, , 0);

{Модуль <string 3BF609A2> / Ошибка в строке: 169 / Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}

**Comment by Mr-Rm** [comment]
Было исправлено в PR#1198 и,  соответственно,  в версии 1.8.1
Можно добавить к сообщению номер параметра. 

_... и есть ещё вариант, когда такое исключение будет даже в latest._

**Comment by EvilBeaver** [comment]
> ... и есть ещё вариант, когда такое исключение будет даже в latest.

А подробнее?

**Comment by Mr-Rm** [comment]
Если в методе глобального контекста с более, чем одним параметром есть параметр value-типа без значения по умолчанию, то при вызове этого метода с пропуском такого параметра получим ошибку _System.NullReferenceException: 'Ссылка на объект не указывает на экземпляр объекта.'_

**Comment by Mr-Rm** [comment]
Очередной виток спирали несовместимости приведения аргументов (см. #371, #735, #814)
```bsl
Результат = СтрНайтиПоРегулярномуВыражению(234,"4"); // с 8.3.23, нет в OneScript
```
Рантайм: _Несоответствие типов (параметр номер '1')_

При этом работает
```bsl
Результат = СтрЗаканчиваетсяНа(234,"4"); // с 8.3.6
Сообщить(Результат);
```
_Да_

С расхождением:
```bsl
Результат = ПолучитьДвоичныеДанныеИзСтроки(234,КодировкаТекста.UTF8); // с 8.3.10
Сообщить(Результат);
```
OneScript: _32 33 34_
1С: _Несоответствие типов (параметр номер '1')_

С пропущенным первым параметром - всё аналогично.
И отмеченное NRE:
```bsl
Результат = ПобитовоеИ(,234);
Сообщить(Результат);
```
OneScript: _Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта._
1С: _Несоответствие типов (параметр номер '1')_

**Comment by EvilBeaver** [comment]
Ну так оно потому, что и у нас и в 1С поведение зависит от того, как реализован конкретный метод и как именно автор метода кастит универсальный bsl-value к конкретному классу

**Comment by EvilBeaver** [comment]
NRE, конечно же, надо исправить

**Comment by Mr-Rm** [comment]
В 1С до версии 8.3.8 аргументы функций/методов приводились по правилам: `все (в т.ч. Неопределено или пропуск) -> Строка`, `Булево -> Число`, `Строка -> Число|ошибка`, `Число -> Булево`. Далее же для новых функций стала выполняться строгая проверка типов.
В OneScript для параметров типа `IValue` проверка отдана вызываемой функции. А для параметров явно указанных конкретных типов (string, int...) `ContextValuesMarshaller` **всегда** пытается выполнить кастинг. Для string - всегда удачно, для других типов - возвращая null или значение по умолчанию (отдельная беда с перечислениями).
Нужно выделять параметры со строгой проверкой типов (что-то вроде `StrictType<T>` ?).
И для пропущенных параметров: передавать ли методам `null`, `Неопределено` с последующим кастингом или извлекать значение по умолчанию из сигнатуры метода, падая при его отсутствии.
Сейчас для методов объектов работает третий вариант, а для функций глобального контекста - первый.
Явно задавать `Nullable`? Может понадобиться пересмотреть всю стандартную библиотеку.

Проверку пропуска/несоответствия параметров для методов глобального контекста можно перенести из рантайма на компиляцию, как это уже делается для методов, реализованных как встроенные функции ВМ.

**Comment by EvilBeaver** [comment]
@Mr-Rm можно закрывать же?

**Comment by Mr-Rm** [comment]
Пожалуй, можно. Изначальная ошибка исправлена.
