### ISSUE TITLE
Добавить директиву компиляции для защиты от бесконечной рекурсии

### ISSUE THREAD

**Issue by tormozit** [EvilBeaver/OneScript#1326]
Словил сегодня медленную бесконечную рекурсию. Возможности подключать отладчик к сожалению в этой среде пока 
нет. Довольно долго мучался. Не мог понять что происходить и как диагностировать.
Если бы я мог ограничить в целях диагностики максимальную глубину стека в 100, то нашел бы причину проблемы намного раньше.

**Comment by nixel2007** [comment]
Максимальную глубину стека можно ограничить средствами встроенного языка, добавив в функцию параметр-счётчик.

**Comment by EvilBeaver** [comment]
Не очень понял, как именно должна выглядеть такая директива компиляции и как она будет определять, что рекурсия - бесконечная?

**Comment by tormozit** [comment]
Я не прошу определять что рекурсия бесконечная, на стороне движка. Я прошу добавить любое средство которое поможет программисту это выявлять. В платформе 1С в серверном интерпретаторе реализован выброс исключения при превышении пороговой (ненастраиваемой) глубины стека с выводом фрагмента стека, по которому легко выявить цикл стека. 
Хотелось бы тут аналогичное удобство. Но важный момент - у меня был тяжелый (без возможности отладки) случай медленной рекурсии. Поэтому до 1000 глубина стека врядли бы дошла за разумное время. Поэтому мне нужно ручное управление порогом.

**Comment by nixel2007** [comment]
Так и в оскрипте реализован выброс исключения при превышении стека, разве нет? Не понимаю, причём тут сравнение с платформой, если твоя проблема в том, что у тебя была медленная функция, которая не дошла до пределов стека.

Ты просто просишь добавить возможность управления допустимой глубиной стека, без привязки к материнской платформе.

**Comment by EvilBeaver** [comment]
> Поэтому до 1000 глубина стека врядли бы дошла за разумное время. Поэтому мне нужно ручное управление порогом.

т.е. ты хочешь что-то типа

```bsl
&КонтрольРекурсии(4)
Процедура Рекурсивная()
    Рекурсивная();
КонецПроцедуры
```

и чтобы на 4 вызове она выдала некое исключение?

**Comment by tormozit** [comment]
> чтобы на 4 вызове она выдала некое исключение?

Да. Только я не знаю какие методы образуют цикл вызовов. Поэтому директива компиляции нужна для модуля, а не метода.

**Comment by tormozit** [comment]
Пример исключения в платформе 1С

```
Переполнение стека встроенного языка на сервере
по причине:

Справочник.ОбработчикиОбъектов.Форма.ФормаСписка.Форма : 13 : СлужебныйМодуль.ФормаСпискаПриСозданииНаСервере(ЭтотОбъект, Отказ, СтандартнаяОбработка);
ОбщийМодуль.СлужебныйМодуль.Модуль : 2606 : ПодключаемыеКоманды.ПриСозданииНаСервере(Форма);
ОбщийМодуль.ПодключаемыеКоманды.Модуль : 88 : КэшФормы = ПодключаемыеКомандыПовтИсп.КэшФормы(ИмяФормы, ИсточникиЧерезЗапятую, ЭтоФормаОбъекта);
ОбщийМодуль.ПодключаемыеКомандыПовтИсп.Модуль : 12 : Возврат Новый ФиксированнаяСтруктура(ПодключаемыеКоманды.КэшФормы(ИмяФормы, ИсточникиЧерезЗапятую, ЭтоФормаОбъекта));
...
ОбщийМодуль.ОбщегоНазначения.Модуль : 3830 : Возврат Справочники.ИдентификаторыОбъектовМетаданных.ИдентификаторОбъектаМетаданных(
Справочник.ИдентификаторыОбъектовМетаданных.МодульМенеджера : 644 : Идентификаторы = ИдентификаторыОбъектовМетаданных(Массив, ВызыватьИсключение, Истина);
Справочник.ИдентификаторыОбъектовМетаданных.МодульМенеджера : 659 : ИдентификаторыПоПолнымИменам = КэшИдентификаторов().ИдентификаторыПоПолнымИменам;
Справочник.ИдентификаторыОбъектовМетаданных.МодульМенеджера : 0
по причине:
Переполнение стека встроенного языка на сервере
```

**Comment by nixel2007** [comment]
@EvilBeaver предлагаешь использовать декоратор?)

**Comment by EvilBeaver** [comment]
> @EvilBeaver предлагаешь использовать декоратор?)

Нет, не предлагаю. Не уверен что он поможет. У тебя же цепочка рекурсии необязательно А->А, может быть А->Б->В->А

**Comment by nixel2007** [comment]
Сяетчиу на уровне класса ничего не мешает сделать же

**Comment by EvilBeaver** [comment]
> Сяетчиу на уровне класса ничего не мешает сделать же

на уровне класса Коллстек?

**Comment by nixel2007** [comment]
Нет, прям на уровне декоратора. В нем можно добавить поле и добавить перехватчик на вызываемый метод, который будет счётчик инкрементировать, проверять на переполнение и кидать исключение.
