### ISSUE TITLE
Описание типов не приводит значение

### ISSUE THREAD

**Issue by Absolemus** [EvilBeaver/OneScript#1327]
**Опишите ошибку**
Описание типа "Тип" не приводит значение

**Воспроизведение ошибки**
1. Запустить код 
```bsl
Тип = Новый ОписаниеТипов("Тип");
Строка = ТипЗнч("Строка");
Результат = Тип.ПривестиЗначение(Строка);
```
2. Увидеть что в переменную результат попадает пустое значение

**Ожидаемое поведение**
Чтобы работало как в 1С
![image](https://github.com/EvilBeaver/OneScript/assets/20809734/633755fd-7723-4443-805c-f36af3cc6d9c)

**Окружение**
 - ОС: Windows
 - Версия: 1.8.3

**Дополнительная информация**

**Comment by EvilBeaver** [comment]
@dmpas можешь посмотреть?

**Comment by dmpas** [comment]
@EvilBeaver да, но только на следующей недельке. Отпуск тут свалился на голову...

**Comment by Absolemus** [comment]
И если можно в эту же копилку, тип двоичные данные тоже не приводится
```bsl
Тип = Новый ОписаниеТипов("ДвоичныеДанные");
ДД = ПолучитьДвоичныеДанныеИзСтроки("Привет, Мир!");
Результат = Тип.ПривестиЗначение(ДД);
```
Тут в результате пустое значение

А в 1С
![image](https://github.com/EvilBeaver/OneScript/assets/20809734/d82634ae-8492-47d1-a8e0-ff1d12d0867b)

**Comment by Mr-Rm** [comment]
Сейчас правильно приводятся только примитивные типы в простых случаях.
А для более сложных вариантов как правильно не скажет и документация 1С - она неполна и противоречива.

**Comment by Mr-Rm** [comment]
Например, [вот тут]( https://its.1c.ru/db/metod8dev#content:2611:hdoc) написано:
> Если типов несколько и переданное значение не соответствует ни одному типу, то будет возвращаться значение Неопределено.

В 1С выполняем
```bsl
КвС = Новый КвалификаторыСтроки(1, ДопустимаяДлина.Фиксированная);
ОписаниеТипа = Новый ОписаниеТипов("Число,Строка", КвС);
Результат = ОписаниеТипа.ПривестиЗначение(Истина);
Сообщить("Результат="Результат); 
```
получаем
_Результат=Д_

**Comment by EvilBeaver** [comment]
Д? А, ну т.е. это "Да" полученный через ToString, а потом обрезаный под квалификатор.

**Comment by Mr-Rm** [comment]
Работает такое только для примитивных типов:
```bsl
Тип = Новый ОписаниеТипов("Дата,Булево");
Результат = Тип.ПривестиЗначение(-2);
Сообщить("Рез="+Результат+":"+ТипЗнч(Результат)); 
```
_Рез=Да:Булево_

но
```bsl
Тип = Новый ОписаниеТипов("Структура,ФиксированныйМассив");
Результат = Тип.ПривестиЗначение(Новый Массив);
Сообщить("Рез="+Результат+":"+ТипЗнч(Результат)); 
```
_Рез=:Не определено_

при том, что
```bsl
Тип = Новый ОписаниеТипов("ФиксированныйМассив");
Результат = Тип.ПривестиЗначение(Новый Массив);
Сообщить("Рез="+Результат+":"+ТипЗнч(Результат)); 
```
_Рез=ФиксированныйМассив:Фиксированный массив_

Реализация последнего варианта, как кажется, будет сложной.

P.S. _Если бы где нашлось *полное* описание преобразования типов..._

**Comment by Mr-Rm** [comment]
_To whom it may concern._

1С 8.3.23.1782 (и предыдущие):
Создать объект без конструктора по умолчанию?
```bsl
Тип = Новый ОписаниеТипов("ЧтениеДанных");
Результат = Тип.ПривестиЗначение();
Сообщить("Рез="+Результат+":"+ТипЗнч(Результат));
```
_Рез=ЧтениеДанных:Чтение данных_

Создать объект, **вообще не имеющий конструктора**?
```bsl
Тип = Новый ОписаниеТипов("Поток");
Результат = Тип.ПривестиЗначение();
Сообщить("Рез="+Результат+":"+ТипЗнч(Результат));
```
_Рез=Поток:Поток_

При попытке обратиться к свойствам/методам полученного объекта -  платформа падает.
Отладка падает сразу.

**Comment by dmpas** [comment]
Ещё любопытная штука, что `Новый ОписаниеТипов("Число,Строка")` и `Новый ОписаниеТипов("Строка,Число")` даёт в в массиве `Типы()` одинаковый порядок `Строка, Число`.

**Comment by nixel2007** [comment]
Сортировка по uuid типа?

**Comment by dmpas** [comment]
> Сортировка по uuid типа?

Вероятно. И попытка приведения, соответственно, идёт в определённом порядке. То есть, всё равно сначала будет приводить к строке, какой бы порядок ни был указан в конструкторе.

**Comment by Mr-Rm** [comment]
Независимо от набора типов (простых или объектных), возможных повторов и порядка, указанного в конструкторе, `ОписаниеТипов.Типы()` всегда возвращает список типов, отсортированный одинаковым образом, без повторений. Судя по отсутствию какой-либо логики в этом порядке, вполне возможно, что сортируется по uuid или другому хешу. 

По сумме найденной документации и результатов проверок, выяснены следующие правила приведения:
- если `ОписаниеТипов` не содержит никакого типа, то возвращается переданное значение как есть (или `Неопределено`, если значение не указано). Квалификаторы игнорируются.
- если в конструкторе  указан единственный тип `Неопределено`, то считается, что `ОписаниеТипов` не содержит никакого типа. При этом `СодержитТип(ТипЗнч(Неопределено))` возвращает `Ложь`, а `Типы().Количество()` равно 0
- если `ОписаниеТипов` содержит только один тип, тогда:
   * тип совпадает с типом переданного значения: возвращается переданное значение с применением квалификатора, если он указан для этого типа;
   * `ОписаниеТипов` содержит тип `Строка`: значение переводится в строку,  с применением квалификатора;
   * значение типа `Строка` может быть приведено к типам `Число`, `Дата` или `Булево`, либо результатом будет `Неопределено`, если преобразование невозможно;
   * значение типа `Число` может быть приведено к типу `Булево`;
   * значение типа `Булево` может быть приведено к типу `Число`;
   * в остальных случаях возвращается неинициализированный объект заданного в Описании типа, __даже если этот тип не имеет конструктора по умолчанию!__ _(Это явный баг)_
 - если `ОписаниеТипов` содержит несколько типов, тогда:
   *  имеется тип, совпадающий с типом переданного значения: возвращается переданное значение (с учетом квалификаторов);
   * `ОписаниеТипов` содержит тип `Строка`: значение переводится в строку,  с применением квалификатора;
   * для переданного значения типа `Строка` выполняются попытки приведения к типам `Число`, `Дата` или `Булево`, если они содержатся в Описании (преобразования несовместимы, возможно только одно из них), либо результатом будет `Неопределено`, если никакое преобразование невозможно;
   * значение типа `Число` приводится к типу `Булево`, если он содержится в Описании;
   * значение типа `Булево` приводится к типу `Число`, если он содержится в Описании;
   * в остальных случаях возвращается `Неопределено`
Когда `ОписаниеТипов` содержит несколько типов, функция `СодержитТип(ТипЗнч(Неопределено))` всегда возвращает `Истина`, но в массиве, получаемом из `Типы()` `Неопределено` отсутствует, а его размер соответствует списку типов, переданных в конструктор, без учета `Неопределено` и без повторов.

**Comment by dmpas** [comment]
@Mr-Rm Спасибо!!!

**Comment by Absolemus** [comment]
Господа, вопрос по поводу реализации 
>в остальных случаях возвращается неинициализированный объект заданного в Описании типа, даже если этот тип не имеет конструктора по умолчанию! (Это явный баг)

Мы будем возвращать такое же значение, какое заложено в 1С, или Неопределено?

**Comment by Mr-Rm** [comment]
Если считать `ПривестиЗначение()` аналогом оператора `as`, а не кастинга, то надо возвращать `Неопределено`.

**Comment by dmpas** [comment]
Я за `Неопределено`. Делать в движке создание неинициализированных объектов - такое себе развлечение.

**Comment by dmpas** [comment]
> Я за `Неопределено`. Делать в движке создание неинициализированных объектов - такое себе развлечение.

С другой стороны это ломает ожидаемое поведение. Есть у нас колонка таблицы значений, там колонка типа "Поток" какой-нибудь. И мы ждём, что там так или иначе будет поток, но уж никак не `Неопределено`.
Возможно в нашем случае надо подумать над выбросом исключений.

**Comment by EvilBeaver** [comment]
Не, погодите, возврат Неопределено, если тип привести не удается, это же документированное поведение. Так и должно работать, не?

**Comment by Absolemus** [comment]
Ну тут 2 варианта. Либо всегда писать сравнение с ```Неопределено``` для проверки, либо вызывать приведение значения в попытке и обрабатывать исключения. По мне так лучше ```Неопределено```, потому что исключение я и сам могу кинуть при необходимости.

**Comment by EvilBeaver** [comment]
![image](https://github.com/EvilBeaver/OneScript/assets/2657561/5d00267d-092b-4792-8efe-226fd627a2e2)

Про Неопределено ничего не написано, надо экспериментировать. Что будет если

```bsl
ОписаниеБезСтрок = Новый ОписаниеТипов("Число,Булево")
РезультатПриведения = ОписаниеБезСтрок.ПривестиЗначение(ТекущаяДата())
```

Что будет?

**Comment by Absolemus** [comment]
![image](https://github.com/EvilBeaver/OneScript/assets/20809734/e27b714c-cda7-4b3e-95cd-623a2f8ad45d)

**Comment by EvilBeaver** [comment]
Мы всегда старались повторять поведение 1С. Кажется, что замена тут на исключение это какое-то неоправданное расхождение. @dmpas @Mr-Rm @nixel2007 что думаете?

**Comment by nixel2007** [comment]
В случае с примитивами - неопределено вполне нормальный вариант. А вот неинициализированные объекты, созданные в обход конструктора могут привести к неприятным чудесам :(

**Comment by EvilBeaver** [comment]
> неинициализированные объекты, созданные в обход конструктора могут привести к неприятным чудесам

Такое мы и вообще не факт, что можем повторить в нашем движке. Думаю это не то, что стоит стремиться повторить

**Comment by Mr-Rm** [comment]
Исключение точно сломает совместимость. И не стоит повторять откровенные баги.
Возьмем пример с ТЗ и Потоком:
```bsl
ТаблицаЗначений = Новый ТаблицаЗначений(); 
ОписаниеТипов = Новый ОписаниеТипов("ЧтениеФайла,Поток");
ТаблицаЗначений.Колонки.Добавить("Поток",ОписаниеТипов);  
СтрокаТЗ = ТаблицаЗначений.Добавить(); // исключение прервёт дальнейшее выполнение, а не должно
Сообщить(ТипЗнч(СтрокаТЗ.Поток)); // потенциальное расхождение: должен быть "Поток", будет "Неопределено"
// ДоступноЧтение = СтрокаТЗ.Поток.ДоступноЧтение // фатальный крэш в 1С. В OneScript - исключение
СтрокаТЗ.Поток = Новый ФайловыйПоток("НекийСуществующийФайл", РежимОткрытияФайла.Открыть); // ок, продолжаем
ДоступноЧтение = СтрокаТЗ.Поток.ДоступноЧтение; // OneScript может продолжить. А 1С всё равно грохнется!!

```

**Comment by EvilBeaver** [comment]
Хакир вы, милейший. Нешто так можно над системами издеваться

**Comment by Mr-Rm** [comment]
В примере есть неточность - "ЧтениеФайла" в ОписанииТипа лишнее.
Вот чистый пример, который должен работать, но роняет платформу по версию 8.3.24.1201 включительно:
```bsl
ТаблицаЗначений = Новый ТаблицаЗначений(); 
ОписаниеТипов = Новый ОписаниеТипов("Поток");
ТаблицаЗначений.Колонки.Добавить("Поток", ОписаниеТипов);  
СтрокаТЗ = ТаблицаЗначений.Добавить();

Поток = Новый ФайловыйПоток(ПолучитьИмяВременногоФайла(), РежимОткрытияФайла.Создать);
Если Поток.ДоступнаЗапись Тогда    
	СтрокаТЗ.Поток = Поток;
	ДоступнаЗапись = СтрокаТЗ.Поток.ДоступнаЗапись;
КонецЕсли;

```

**Comment by dmpas** [comment]
@Absolemus https://build.oscript.io/blue/organizations/jenkins/1Script/detail/PR-1337/5/artifacts
есть возможность погонять сборку?

**Comment by EvilBeaver** [comment]
@dmpas сможем для 2.0 повторить?

**Comment by Absolemus** [comment]
> есть возможность погонять сборку?

Если еще актуально, завтра вечером могу прогнать

**Comment by EvilBeaver** [comment]
Актуально. Будем признательны

**Comment by dmpas** [comment]
> @dmpas сможем для 2.0 повторить?

@EvilBeaver я вообще сначала в 2.0 сделал, а потом уже уточнил у тебя что в latest. Так что да

**Comment by dmpas** [comment]
> @dmpas сможем для 2.0 повторить?

@EvilBeaver принимай:
https://github.com/EvilBeaver/OneScript/pull/1353

**Comment by Absolemus** [comment]
> есть возможность погонять сборку?

Я прогнал свой проект на latest, @dmpas спасибо большое, все работает!
