### ISSUE TITLE
При вызове методов COM-объектов не учитвывается доступность параметров для записи

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1331]
**Опишите ошибку**
1. После исправления issue #1324 все передаваемые как параметры в метод COM-объекта переменные считаются получающими возвращаемое значение и доступными для записи, а это не всегда верно

**Воспроизведение ошибки**
```bsl
Рег = Новый ФиксированнаяСтруктура("HKEY_LOCAL_MACHINE", "2147483650"); 
ИмяФайлаКласса = "";
РеестрОС = ПолучитьCOMОбъект("winmgmts:{impersonationLevel=impersonate}!\\.\root\default:StdRegProv");
Рез=РеестрОС.GetStringValue(Рег.HKEY_LOCAL_MACHINE, "SOFTWARE\Microsoft\Windows\CurrentVersion","DevicePath", ИмяФайлаКласса);
Сообщить("Рез="+Рез+" Имя="+ИмяФайлаКласса);
```
_Ошибка в строке: 4 / Свойство  недоступно для записи_
(из-за попытки записи в `Рег.HKEY_LOCAL_MACHINE`)

2. Все свойства COM-объектов считаются доступными для записи
**Воспроизведение ошибки**
```bsl
Путь = C:\1S\DB7\";
Пользователь = "Администратор";
База = Новый COMОбъект("V77.Application");
Рез = База.Initialize(База.RMTrade, "/d"""+Путь+"""  /N"+ Пользователь, "NO_SPLASH_SHOW");
```
_Ошибка в строке: 4 / Внешнее исключение (System.ArgumentException): Значение не попадает в ожидаемый диапазон._
(из-за попытки записи в `База.RMTrade`)

**Ожидаемое поведение**
1С нормально отрабатывает оба примера.

**Окружение**
 - ОС: Windows 10 x64
 - Версия: latest

**Дополнительная информация**
Требуется получать больше информации, чем дает `DispatchUtility`.

**Comment by EvilBeaver** [comment]
Да, я так и пробовал сделать, но:

* не все COM-объекты имеют TypeInfo
* какой-то дикий головняк с получением флагов доступа к параметрам, включающий в себя черную магию COM
