### ISSUE TITLE
XMLЗначение: исключение при передаче имени системного перечисления.

### ISSUE THREAD

**Issue by aleksandr-ermakov** [EvilBeaver/OneScript#1332]
**Опишите ошибку**
`xmlЗначение` падает при передаче имени системного перечисления.

**Воспроизведение ошибки**
Выполнить код
```bsl
Тип = Тип("ДопустимаяДлина");
Значение = XMLЗначение(Тип, "Фиксированная");
```
Получаем: `{Модуль <string> / Ошибка в строке: 2 / Неверное значение аргумента}`

**Ожидаемое поведение**
Код должен возвращать значения типа `ДопустимаяДлина`. В платформе работает.

**Окружение**
 - ОС: Win 10 x64
 - Версия: 1.8.3.2

**Comment by EvilBeaver** [comment]
Спасибо

**Comment by EvilBeaver** [comment]
@Mr-Rm давай для develop тоже поправим
