### ISSUE TITLE
Вызвал функцию с 3-мя фактическими параметрами, хотя у нее лишь 2 формальных. Исключения не возникло.

### ISSUE THREAD

**Issue by tormozit** [EvilBeaver/OneScript#1333]
Вызвал функцию с 3-мя фактическими параметрами, хотя у нее лишь 2 формальных. Исключения не возникло. 
В платформе 1С при этом выбрасывается исключение "Слишком много фактических параметров".
Хотелось бы аналогичного контроля и тут.

```
Функция Ф(П1, П2)
КонецФункции
Ф(1,2,3);
```

**Comment by nixel2007** [comment]
Версия движка?

**Comment by tormozit** [comment]
Нашел такую версию. Это она?
![изображение](https://github.com/EvilBeaver/OneScript/assets/11896251/a794902d-8b17-46db-b7c9-bf9b360a1873)

**Comment by tormozit** [comment]
Разработчик Турбоконф сообщил, что версия движка 1.7

**Comment by nixel2007** [comment]
Я все понимаю, но кажется стоит сначала обновиться на 1.8.3, а потом уже проверять совместимость. Уже не первый ишуз с проблемой, которая давно исправлена.

**Comment by tormozit** [comment]
Перепроверил. Проблема НЕ подтвердилась. Скорее всего в момент наблюдения проблемы исполнялся неактуальный код модуля. Без отладчика сложновато корректно диагностировать подобные проблемы. Теперь в тесте возникает ожидаемое исключение

Не удалось выполнить скрипт ВычислитьВыражение
ScriptEngine.Compiler.CompilerException: {Модуль <string F66414E5> / Ошибка в строке: 567,53 / Слишком много фактических параметров}    
	Ф = Ф(,, ТекстПоля);

**Comment by EvilBeaver** [comment]
@bolsun кстати, прикрутить отладчик к турбоконфу вполне возможно. Надо?

**Comment by bolsun** [comment]
> @bolsun кстати, прикрутить отладчик к турбоконфу вполне возможно. Надо?

надо конечно. Я какие-то эксперименты пробовал проводить. Но раньше через процесс запускал и как-то не получилось заставить работать.

**Comment by EvilBeaver** [comment]
> надо конечно. Я какие-то эксперименты пробовал проводить. Но раньше через процесс запускал и как-то не получилось заставить работать.

@bolsun - добавил отладку в пример https://github.com/EvilBeaver/1ScriptExample

**Comment by bolsun** [comment]
> > надо конечно. Я какие-то эксперименты пробовал проводить. Но раньше через процесс запускал и как-то не получилось заставить работать.
> 
> @bolsun - добавил отладку в пример https://github.com/EvilBeaver/1ScriptExample

Спасибо! Посмотрю, отпишусь.

**Comment by bolsun** [comment]
> > надо конечно. Я какие-то эксперименты пробовал проводить. Но раньше через процесс запускал и как-то не получилось заставить работать.
> 
> @bolsun - добавил отладку в пример https://github.com/EvilBeaver/1ScriptExample

Заработало, спасибо!
Надо бы добавить в пример информацию, что грузить код для отладки нужно обязательно методом FromFile()

И пример launch.json бы приложить. Т.к. с ним были сложности.

**Comment by EvilBeaver** [comment]
> Надо бы добавить в пример информацию, что грузить код для отладки нужно обязательно методом FromFile()
> И пример launch.json бы приложить. Т.к. с ним были сложности.

Чем хорош мой пример, так это тем, что в него можно делать пулреквесты и добавлять любую дополнительную информацию 😉
