### ISSUE TITLE
Зависание "ожидания процесса" при отладке

### ISSUE THREAD

**Issue by 240596448** [EvilBeaver/OneScript#1335]
При запуске отладки по F5 после метода создания процеса выполнение замирает на строке ожидания завершения процесса и ожидает бесконечно до нажатия F11 (или сработки таймаута, если параметр у метода указан)

```bsl
Процедура ВыполнитьКоманду(КоманднаяСтрока)
	
	Процесс = СоздатьПроцесс(КоманднаяСтрока, ".", Истина);
	Процесс.Запустить();
	Процесс.ОжидатьЗавершения();
	
	Пока Процесс.ПотокВывода.ЕстьДанные Цикл
		Сообщить(Процесс.ПотокВывода.ПрочитатьСтроку());
	КонецЦикла;

КонецПроцедуры

ВыполнитьКоманду("git");
```

Замечено, что подобное зависание происходит именно на команде `git`.
В тоже время `gitrunner` запускается несколько иначе, через `1command` - там подобного не воспроизводится.

 _- ОС: win 10; server 2019;_
 _- Версия: 1.7.0, 1.8.1, 1.8.3 (from ovm)_
 _- vscode 1.82.2 user setup_
 _- расширение OneScript Debug (BSL) v0.7.2_

Писал про это [тут](https://t.me/oscript_library/94165) и [тут](https://t.me/oscript_library/94169)

**Comment by EvilBeaver** [comment]
Это зависание не связано с отладкой скорее всего. Каждый процесс, если у него перехвачен поток вывода, может вывести в поток только ограниченное количество текста, потом поток останавливается силами ОС, пока кто-то не начнет вычитывать накопленные данные из буфера. Получется следующее:

```bsl
Процесс.Запустить();
Процесс.ОжидатьЗавершения(); // тут процесс работает и что-то пишет в вывод, а мы его ждем
// если процесс написал в вывод слишком много, ОС его остановит, пока вывод не будет вычитан.
// а вычитан он не будет, т.к. мы ждем завершения процесса и читаем только после завершения, а завершения не будет, т.к. процесс ждет, пока кто-то его прочитает.
```

Для упрощения данного алгоритма как раз и создана библиотека 1commands, которая это оборачивает в относительно простой API

**Comment by 240596448** [comment]
> Для упрощения данного алгоритма как раз и создана библиотека 1commands, которая это оборачивает в относительно простой API

Да, это понятно.
Пример был выдернут из `vanessa-runner`. Там такое устаревшее использование.

Если подобное поведение - известная особенность, то вопрос закрыт.
Спасибо за разъяснения.
