### ISSUE TITLE
Бесконечная рекурсия при вызове ИмпортXS.РазрешеннаяСхема

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#1344]
**Опишите ошибку**

По результатам анализа сонаром найдена бесконечная рекурсия

https://sonar.openbsl.ru/project/issues?id=OneScript&issues=AYqkzEbX0SV0_h7JCOA0&open=AYqkzEbX0SV0_h7JCOA0
https://sonar.openbsl.ru/project/issues?id=OneScript&issues=AYqkzEbl0SV0_h7JCOA9&open=AYqkzEbl0SV0_h7JCOA9
https://sonar.openbsl.ru/project/issues?id=OneScript&issues=AYqkzEbJ0SV0_h7JCOAp&open=AYqkzEbJ0SV0_h7JCOAp

**Ожидаемое поведение**
Свойство должно быть написано правильно

**Comment by EvilBeaver** [comment]
@yukon39 возьмешься починить? Судя по блейму, это к тебе

**Comment by yukon39** [comment]
Гляну, конечно.

Сонар прикрутили - огонь!
