### ISSUE TITLE
Добавить контекст для использования разными тестами

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#135]
Originally reported by: **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**

---

Добавить контекст для использования разными тестами
Интерфейс:
процедура УстановитьКонтекст(Контекст, ИдентификаторКонтекста = Неопределено)
функция ПолучитьКонтекст(ИдентификаторКонтекста = Неопределено)

контекст может быть любым

[Аналогичная задача из xUnitFor1C](https://github.com/xDrivenDevelopment/xUnitFor1C/issues/453)

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/135

**Comment by dmpas** [comment]
@artbear а по этой мохнатой задаче можно капельку подробней?

**Comment by artbear** [comment]
Это был некий зачаток для сценарных тестов.
Теперь эту задачу лучше решать в 1testrunner

**Comment by dmpas** [comment]
@artbear @EvilBeaver Закрываем?

**Comment by artbear** [comment]
@EvilBeaver Закрывай. 
ЗЫ у меня прав нет.
