### ISSUE TITLE
Перестал собираться latest после добавления цветов к консоли

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#1350]
Коммит 3e73a22731db кажется сломал сборку.

Не собирается latest https://build.oscript.io/blue/organizations/jenkins/1Script/detail/latest/55/pipeline

https://build.oscript.io/blue/organizations/jenkins/1Script/detail/PR-1337/6/pipeline#step-45-log-650

**Comment by Mr-Rm** [comment]
А казалось бы безобиднейший коммит...  Fixed
