### ISSUE TITLE
2.0 Не работает ПолучитьЗначениеСистемнойНастройки()

### ISSUE THREAD

**Issue by sfaqer** [EvilBeaver/OneScript#1358]
**Опишите ошибку**
Метод ПолучитьЗначениеСистемнойНастройки не возвращает информацию из oscript.cfg

**Воспроизведение ошибки**
1. Установить oscript 2.0
2. Запустить код 
```bsl
Сообщить(ПолучитьЗначениеСистемнойНастройки("lib.system"));
```
3. Увидеть Пустую строку

**Ожидаемое поведение**
Ожидается что вернётся параметр указанный в oscript.cfg
![image](https://github.com/EvilBeaver/OneScript/assets/32082417/3ed3db95-135f-48ac-b2f5-4d77e9b19120)

**Окружение**
 - ОС: Win11 x64
 - Версия: 2.0.0.413-rc3-28262419 scd-win

**Дополнительная информация**

**Comment by Mr-Rm** [comment]
Снова тема "DI vs static".
Есть два варианта решения:
в `ScriptEngine.HostedScript\SystemConfigAccessor.cs`
```cs
 public SystemConfigAccessor(ConfigurationProviders providers)
 {
     Provider = providers;
     Refresh();
 }
// ...
  public static IAttachableContext CreateInstance(ConfigurationProviders providers)
  {
      return new SystemConfigAccessor(providers);
  }
```
или
```cs
  internal static ConfigurationProviders Provider { get; set; }
// ...
  public static IAttachableContext CreateInstance(ConfigurationProviders providers)
  {
      Provider = providers;
      return new SystemConfigAccessor();
  }
```

**Comment by nixel2007** [comment]
Эта штука полностью блокирует обновление опм на линуксе на последнем девелопе оскрипта :(

**Comment by EvilBeaver** [comment]
Да, я уже сделал первый вариант, предлагаемый @Mr-Rm, только сделал через одно место непонятно почему. Видимо, был не в себе.
