### ISSUE TITLE
2.0 Не понятно как поставляются bat\bash скрипты для запуска

### ISSUE THREAD

**Issue by sfaqer** [EvilBeaver/OneScript#1360]
На текущий момент в SCD поставках оскрипта поставляется bat\bash скрипты для запуска с контентом в стиле `dotnet oscript.dll` в свою очередь поставляется так же и исполняемый файл oscript так что наличие самих скриптов не видится необходимым вовсе  
В свою очередь в FDD поставках нет ни исполняемого файла, ни скрипта для запуска

Хотелось бы что бы скрипты запуска из SCD переместились в поставку FDD

**Comment by sfaqer** [comment]
* Уточнение, в ветке night-build bat\sh файлы fdd дистрибутива присутствуют, они отсутствуют в ветке preview (вероятно старые сборки)

**Comment by EvilBeaver** [comment]
@sfaqer да, размещение файлов было исправлено в текущем девелопе

**Comment by nixel2007** [comment]
@EvilBeaver кажется, у sh файла лишнее расширение. Он должен быть просто oscript, а не oscript.sh

**Comment by sfaqer** [comment]
> @sfaqer да, размещение файлов было исправлено в текущем девелопе

Надо их ещё из scd поставки убрать, а то не понятно зачем они там вообще
