### ISSUE TITLE
Метод ПрочитатьJSON добавляет в возвращаемых данных (в массиве) закоментированные строки

### ISSUE THREAD

**Issue by 240596448** [EvilBeaver/OneScript#1373]
Если в массиве json есть закомментированная строка, то она попадает в структуру данных в виде элемента массива.

Пример воспроизведения прикреплен
![image](https://github.com/EvilBeaver/OneScript/assets/35220983/059023fa-ac8b-42f7-aed3-3a10f673d75f)

Проверил на 1.1.1, 1.4.0, 1.8.4

[testjson.zip](https://github.com/EvilBeaver/OneScript/files/13191312/testjson.zip)

Листинги
```json
[
    {
        "NAME": "",
        "Method": "",
        "PATH": ""
    },
    {
        "NAME": "",
        // "Method": "",
        "PATH": ""
    }
    // },
    // {
    //     "NAME"   : ""
    //     "Method" : "",
    //     "PATH"   : ""
]
```

```os
ЧтениеТекста = Новый ЧтениеТекста("test.json", КодировкаТекста.UTF8NoBOM);
Текст = ЧтениеТекста.Прочитать();
ЧтениеТекста.Закрыть();

ЧтениеJSON = Новый ЧтениеJSON();
ЧтениеJSON.УстановитьСтроку(Текст);
Настройка = ПрочитатьJSON(ЧтениеJSON);
ЧтениеJSON.Закрыть();
Для Каждого Стр Из Настройка Цикл
	Сообщить(Стр);
КонецЦикла;
```

Обсуждение https://t.me/oscript_library/98144

**Comment by Mr-Rm** [comment]
Не только в массиве:
```bsl
Текст = "
|{
|  'test': //fail
|  'pass'
|}";
ЧтениеJSON = Новый ЧтениеJSON();
ЧтениеJSON.УстановитьСтроку(Текст);
Результат = ПрочитатьJSON(ЧтениеJSON);
ЧтениеJSON.Закрыть();
Сообщить(Результат.test);
```
_fail_
вместо  "pass"

**Comment by EvilBeaver** [comment]
Я не знаю, какое должно быть правильное поведение. Комментариев в синтаксисе Json вообще не предусмотрено....

**Comment by 240596448** [comment]
>  Комментариев в синтаксисе Json вообще не предусмотрено....  

Вопрос дискуссионный. С одной стороны именно таким он и создавался, а с другой формат вырос до одно- и многострочных комментариев.

>  Я не знаю, какое должно быть правильное поведение.  

В чем имеено логическая ловушка?
Нужны однострочные комментарии. В многострочные не лезть. Обработка комментариев построчная.
