### ISSUE TITLE
В версии 1.8 сломался возврат результатов функций через COM 

### ISSUE THREAD

**Issue by tormozit** [EvilBeaver/OneScript#1376]
**Опишите ошибку**
сломался возврат результатов функций через COM видимо в процессе починки возврата значений параметров этих же функций 
https://github.com/EvilBeaver/OneScript/issues/1324

**Воспроизведение ошибки**
```
ф = Новый COMОбъект("V83.Application");
СтрокаСоединения = <Строка соединения с любой базой 1С>;
ф.Connect(СтрокаСоединения);
я = ф.Метаданные.Справочники.Количество();
```

получаем ошибку 

ScriptEngine.Machine.ExternalSystemException: {Модуль D:\Projects\TurboConf\TurboConf.HostApplication\bin\Debug\user_scripts\SampleCOM.os / Ошибка в строке: 119 / Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}    
  я = ф.Метаданные.Справочники.Количество();
 ---> System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в ScriptEngine.Machine.Contexts.UnmanagedCOMWrapperContext.CallAsFunction(Int32 methodNumber, IValue[] arguments, IValue& retValue)
   в ScriptEngine.Machine.MachineInstance.ResolveMethodFunc(Int32 arg)
   в ScriptEngine.Machine.MachineInstance.MainCommandLoop()
   --- Конец трассировки внутреннего стека исключений ---
   в ScriptEngine.Machine.MachineInstance.MainCommandLoop()
   в ScriptEngine.Machine.MachineInstance.ExecuteCode()
   в ScriptEngine.Machine.MachineInstance.ExecuteMethod(IRunnable sdo, Int32 methodIndex, IValue[] arguments)
   в ScriptEngine.Machine.Contexts.ScriptDrivenObject.CallAsFunction(Int32 methodNumber, IValue[] arguments, IValue& retValue)
   в TurboConf.HostApplication.HostApplicationForm.ExecuteScript(Script script, Keys ctrl, Keys alt, Keys shift, ScreenForm statusForm, String entryPoint, IVariable[] parameters, ScriptOptions options) в D:\Projects\TurboConf\TurboConf.HostApplication\HostApplicationForm.cs:строка 253

**Comment by tormozit** [comment]
В ветку 1.8 будет вливаться?

**Comment by nixel2007** [comment]
ветка latest - это 1.х

**Comment by tormozit** [comment]
Киньте ссылку на установщик или архив с проблемной версией 1.9

**Comment by EvilBeaver** [comment]
https://oscript.io/downloads/archive/latest-dev

**Comment by tormozit** [comment]
Проверил на чистом движке ОСкрипт 1.9 (без Турбоконфа) по ссылке выше. 
Ошибки нет. Тест приложен.
```
ф = Новый COMОбъект("V83.Application");
СтрокаСоединения = "File=""C:\1C\DB\ИР Подсистема 8.3"";usr=1";
ф.Connect(СтрокаСоединения);
Пар1 = 1;
Рез = ф.ирКэш.ПолеТекстаПрограммы(Пар1);
Сообщить("1");
```

**Comment by bolsun** [comment]
> Проверил на чистом движке ОСкрипт 1.9 (без Турбоконфа) по ссылке выше. Ошибки нет. Тест приложен.
> 
> ```
> ф = Новый COMОбъект("V83.Application");
> СтрокаСоединения = "File=""C:\1C\DB\ИР Подсистема 8.3"";usr=1";
> ф.Connect(СтрокаСоединения);
> Пар1 = 1;
> Рез = ф.ирКэш.ПолеТекстаПрограммы(Пар1);
> Сообщить("1");
> ```

Данный тест в ТурбоКонф тоже работает, в таком варианте:

```
Процедура РедактироватьТекст()	

	ПодключениеИР = ПодключениеИР(,, Ложь);
	Если ПодключениеИР = Неопределено Тогда
		Возврат;
	КонецЕсли;
	Если Не ЗначениеЗаполнено(ТекстМодуля) Тогда
		Возврат;
	КонецЕсли;
	МодулиИР = МодулиИР(ПодключениеИР);

	Пар1 = 1;
	Рез = МодулиИР.ирКэш.ПолеТекстаПрограммы(Пар1);
	Сообщить("Работает!");
	Возврат;
```

Если закомментировать Возврат - происходит ошибка:
Ошибка в строке: 1130 / Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}

**Comment by bolsun** [comment]
Строка 1130 такая:
ЗаголовокОкна = ТурбоКонф.ПолучитьЗаголовокТекущегоОкна();

**Comment by EvilBeaver** [comment]
Объект "Турбоконф", как я понимаю, не объект движка. Смотреть надо в его веутренности и в реализацию метода ПолучитьЗаголовок...

**Comment by bolsun** [comment]
> Объект "Турбоконф", как я понимаю, не объект движка. Смотреть надо в его веутренности и в реализацию метода ПолучитьЗаголовок...

        [ContextMethod("ПолучитьЗаголовокТекущегоОкна", "GetForegroundWindowTitle")]
        public string GetWindowTitle()
        {
            return User32.GetText(User32.GetForegroundWindow());
        }

**Comment by bolsun** [comment]
Не факт, что это именно эта строка. Т.к. мы выяснили, что иногда они не совпадают. Проверю отладчиком.

**Comment by bolsun** [comment]
Да, строка не та.
Падает здесь:

```
Функция ПолеТекстаПрограммыИР(ПодключениеИР, ТекстМодуля, ПозицияВТексте, ВыделенныйТекст = "", ПереходитьВоВложенныйКонтекст = Истина, Знач КакВызовМетода = Неопределено,
	Знач ЭтоДокумент = Истина, Знач СИменемКонфигурации = Ложь, Знач ЭтоАвтодополнение = Ложь, Знач ИдентификаторПоля = Неопределено, Знач ИмяКонфигурации = "")

	Если ЭтоДокумент Тогда
		Попытка
			ТекущийДокумент = Конфигуратор.ТекущийДокумент;
		Исключение
		КонецПопытки;
		Если ЗначениеЗаполнено(ТекущийДокумент) Тогда
			ЗаголовокОкна = ТекущийДокумент.Заголовок;
			ИмяКонфигурации = ТекущийДокумент.ИмяКонфигурации;
			ИдентификаторПоля = ТекущийДокумент.DocumentRuntimeId;
		//   Сообщить(ТекущийДокумент.ConfRuntimeId);  
		КонецЕсли;
	КонецЕсли;
	МоментЗапуска = ТекущаяУниверсальнаяДатаВМиллисекундах();
	ПолноеИмяМодуля = "";
	ЭтоМодульВнешнегоОбъекта = Ложь;
	КлючКэша = "ПолеТекстаПрограммы";
	ПолеТекстаПрограммы = ВосстановитьЗначениеСеансаКонфигуратора(КлючКэша);
	Попытка
		Пустышка = ПолеТекстаПрограммы.мИмяМодуля;
	Исключение
		ПолеТекстаПрограммы = Неопределено;
	КонецПопытки;
	Если ПолеТекстаПрограммы = Неопределено Тогда
		МодулиИР = МодулиИР(ПодключениеИР);
		ПолеТекстаПрограммы = МодулиИР.ирКэш.ПолеТекстаПрограммы(ЯзыкПрограммы);
```

**Comment by bolsun** [comment]
![image](https://github.com/EvilBeaver/OneScript/assets/2655167/3fcf769f-21a2-406a-86f0-c807b88f7c7c)

**Comment by bolsun** [comment]
![image](https://github.com/EvilBeaver/OneScript/assets/2655167/c73215cf-9d84-4740-9acd-30a4de1f40b5)

**Comment by tormozit** [comment]
Если фактический параметр вызываемого COM метода имеет значение "Неопределено", то на чистом движке ОСкрипт 1.9 (без Турбоконфа) у меня то же возникает ошибка в тесте:
```
ф = Новый COMОбъект("V83.Application");
СтрокаСоединения = "File=""C:\1C\DB\тест1"";usr=1";
ф.Connect(СтрокаСоединения);
Пар1 = Неопределено;
Рез = ф.Сообщить(Пар1);
```
{Модуль C:\TerminalDisk\comtest.os / Ошибка в строке: 5 / Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}

**Comment by EvilBeaver** [comment]
@tormozit принял, посмотрю, что можно сделать. Спасибо за исследование. Но стоит понимать, что `Неопределено` языка BSL в этом случае передается в COM-объект, а он не знает ничего про `Неопределено`, `Неопределено` транслируется в "NULL общего назначения" и дальше уже падает сам COM-объект, который там null не ожидает. Мне кажется, можно там что-то отрегулировать, но не уверен, что удастся

**Comment by bolsun** [comment]
> @tormozit принял, посмотрю, что можно сделать. Спасибо за исследование. Но стоит понимать, что `Неопределено` языка BSL в этом случае передается в COM-объект, а он не знает ничего про `Неопределено`, `Неопределено` транслируется в "NULL общего назначения" и дальше уже падает сам COM-объект, который там null не ожидает. Мне кажется, можно там что-то отрегулировать, но не уверен, что удастся

Т.к. этот же код работает в 1.7, то вроде шансы есть ))

**Comment by Mr-Rm** [comment]
Тест @tormozit падает тут:
https://github.com/EvilBeaver/OneScript/blob/cb2a8d5f2db7f12a72f54ee5b96ab7e4137ae47b/src/ScriptEngine/Machine/Contexts/UnmanagedCOMWrapperContext.cs#L248
с исключением 
_System.NullReferenceException: 'Ссылка на объект не указывает на экземпляр объекта.'
initialValues[] was null._

**Comment by EvilBeaver** [comment]
initialValues не может быть null, он создается перед вызовом всегда... Странно

**Comment by Mr-Rm** [comment]
На самом деле initialValues[0]==null, но сообщение Студии именно такое.
И да, причина падения в маршалинге `Неопределено` в `null`, но не из-за передачи его в COM, а из-за попытки возврата параметра.

**Comment by EvilBeaver** [comment]
Да, уже починил

**Comment by Mr-Rm** [comment]
Кажется, можно уронить и это исправление...

**Comment by Mr-Rm** [comment]
В примере делаем
```
Пар1 = NULL;
```
и получаем
_Ошибка в строке: 5 / Тип ScriptEngine.Machine.Variable не поддерживает преобразование в CLR-объект_

**Comment by EvilBeaver** [comment]
Ну это не совсем ошибка так-то... Null это же субд-шный литерал, отличный от Неопределено. И текст исключения честный

**Comment by EvilBeaver** [comment]
Закрываю, кажется что худо-бедно, но исправлено.
