### ISSUE TITLE
OneScript v2 внешнее исключение при использовании библиотеки 

### ISSUE THREAD

**Issue by JohnyDeath** [EvilBeaver/OneScript#1378]
OneScript 2.0.0.431-rc4-28321016
Код
```bsl
#Использовать ClientSSH

КлиентSSH = Новый КлиентSSH("127.0.0.1", 22, "test", "test");
Соединение = КлиентSSH.ПолучитьСоединение();
Результат = Соединение.ВыполнитьКоманду("echo 123");   
Сообщить(Результат);
Соединение.Отключиться();
```
Приводит к ошибке:

> {Модуль ...\lib\ClientSSH\package-loader.os / Ошибка в строке: 6 / Внешнее исключение (System.TypeLoadException): Could not load type 'ScriptEngine.Machine.Contexts.ContextClassAttribute' from assembly 'ScriptEngine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.}

На версии 1.8.4 правильное поведение:

> {Модуль testssh.os / Ошибка в строке: 4 / Внешнее исключение (System.Net.Sockets.SocketException): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение}

**Comment by EvilBeaver** [comment]
Тут проблема обратной совместимости. DLL-компоненты версии 1 несовместимы с версией 2. И не сделан слой совместимости по типу 1С-ного, когда у тебя зип-архив с разными бинарями и манифест.

Кстати, надо бы на это дело issue создать

**Comment by arkuznetsov** [comment]
@EvilBeaver Переведи! 
Т.е. можно сделать что-то более правильное, чем обновить зависимость и пересобрать?
Есть где пример глянуть?

**Comment by EvilBeaver** [comment]
В компоненте rabbitmq есть ветка перевода на v2

**Comment by EvilBeaver** [comment]
https://github.com/yukon39/CoverageBSL/commit/593ab24d8eb750eb9cf53026ac60d07213abae34#diff-f96b48604d10c2220cb8454b03bcd3c149fdcec1b67abe4ee60a70351bead621

**Comment by EvilBeaver** [comment]
Решено в рамках #1379
