### ISSUE TITLE
Поддержать кросс-платформенные внешние компоненты

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#1379]
# Описание задачи

Сейчас ospx с внешними компонентами для версии 1 несовместим с версией 2. И если автор пакета просто перекомпилирует бинарь под v2, то его пакет потеряет совместимость с первой версией.

**Опишите решение**

Нужно поддержать загрузку бинарей компонент из зип-архивов, наподобие того, как делает 1С, либо сделать это на уровне стандартного загрузчика package-loader.os, чтобы он выбирал разные DLL (из разных папок, например, или с разными суффиксами имени)

**Критерий успешности**

Автор публикует один ospx на хабе, в нем так или иначе поставлены 2 версии DLL и рантаймы версии 1 и 2 работают, загружая правильный бинарь. При этом, решение предложено общее "типовое", а не каждый автор сам придумывает как решить эту задачу

**Comment by EvilBeaver** [comment]
@dmpas @Mr-Rm @nixel2007 и др. прошу высказываться

**Comment by nixel2007** [comment]
Вариант с пэкэдж лоадером мне нравится. Да и из СИ версию оскрипта достать легко. Только нужно какую-то сравнивалку версий завезти или в крайнем случае добавить версию интерфейса компонент 1/2 в си

**Comment by nixel2007** [comment]
Завезти - прям сразу же реализовать в пэкэджлоадере, для копипаста.

**Comment by nixel2007** [comment]
Ещё можно подумать над доработкой общего пэкэджлоадера. Например, добавить в опм новый метод "ОпределяетВнешнююКомпоненту", сложить её в манифест какой-нибудь, а в общем загрузчике потом из манифеста доставать. Вариант красивый, но потребует обновления опм на клиентах для работы. А в случае с лоадером под либу - нет

**Comment by dmpas** [comment]
Звучит хорошо.

**Comment by EvilBeaver** [comment]
>  Да и из СИ версию оскрипта достать легко. Только нужно какую-то сравнивалку версий завезти или в крайнем случае добавить версию интерфейса компонент 1/2 в си

Что такое СИ в данном ключе?

**Comment by nixel2007** [comment]
СистемнаяИнформация
