### ISSUE TITLE
Ошибка  Can't launch debugee (Не удается найти указанный файл)

### ISSUE THREAD

**Issue by morskoj** [EvilBeaver/OneScript#1381]
**Опишите ошибку**
При попытке запустить отладку, вываливается в ошибку. В параметре "program" писал точный путь до файла, косые менял, джейсон сохранял... ничего не помогло.

**Окружение**
 - ОС:  Windows 10
 - Версия: 

**Дополнительная информация**

**Comment by nixel2007** [comment]
Файл в студию

**Comment by morskoj** [comment]
> Файл в студию
[test.zip](https://github.com/EvilBeaver/OneScript/files/13513166/test.zip)

**Comment by morskoj** [comment]
> Файл в студию

[launch.zip](https://github.com/EvilBeaver/OneScript/files/13513179/launch.zip)

**Comment by nixel2007** [comment]
Что выдаёт `where.exe oscript` в терминале?

**Comment by morskoj** [comment]
> Что выдаёт `where.exe oscript` в терминале?

Я не знаю что такое "where.exe oscript"

**Comment by EvilBeaver** [comment]
> Я не знаю что такое "where.exe oscript"

Пуск/Выполнить, там cmd, ОК
Далее в консоли набрать `where oscript`, Enter. Покажет путь, где установлен oscript

**Comment by morskoj** [comment]
> Что выдаёт `where.exe oscript` в терминале?

C:\Program Files\OneScript\bin\oscript.exe

**Comment by morskoj** [comment]
> > Я не знаю что такое "where.exe oscript"
> 
> Пуск/Выполнить, там cmd, ОК Далее в консоли набрать `where oscript`, Enter. Покажет путь, где установлен oscript

Спасибо!

**Comment by nixel2007** [comment]
А в терминале vscode можете ту же команду выполнить?

**Comment by EvilBeaver** [comment]
@morskoj подниму тему. Все получилось? Заркывать задачу?

**Comment by morskoj** [comment]
> @morskoj подниму тему. Все получилось? Заркывать задачу?

Да, спасибо.
