### ISSUE TITLE
OneScript Debug for VSCodium

### ISSUE THREAD

**Issue by WonderMr** [EvilBeaver/OneScript#1387]
Продукт: https://marketplace.visualstudio.com/items?itemName=EvilBeaver.oscript-debug
Проблема: Продукт доступен только в магазине приложений VSCode, недоступен для VSCoduim и на [open-vsix](https://open-vsx.org/)
Запрос: Андрей, можешь добавить расширение в https://open-vsx.org/ пожалуйста? Хочется без костылей пользоваться.
Костыли:
1. https://milicendev.netlify.app/article/install-vs-codium-and-integrate-vs-code-extensions/
2. https://github.com/OliverKeefe/vscode-extensions-in-vscodium

**Comment by EvilBeaver** [comment]
Проверьте, все ли работает: https://open-vsx.org/extension/EvilBeaver/oscript-debug

**Comment by WonderMr** [comment]
Вот это скорость! А коллеги [с ноября протолкнуть не могут ](https://github.com/1c-syntax/vsc-language-1c-bsl/issues/274)
Потестирую сегодня, отпишусь.
Огромное спасибо!

**Comment by EvilBeaver** [comment]
> Вот это скорость! А коллеги https://github.com/1c-syntax/vsc-language-1c-bsl/issues/274

Там есть заморочка с подпиcанием договора с Eclipse. У меня он просто уже подписан, поэтому "Далее, Далее, Далее, ОК"

**Comment by WonderMr** [comment]
Пока была только проблема
![image](https://github.com/EvilBeaver/OneScript/assets/5370211/01d9e895-7af6-4282-946e-a0f9d7e5928d)
Но я решил её при помощи
`ln /usr/bin/oscript /usr/bin/oscript.exe`

**Comment by EvilBeaver** [comment]
Так же можно решить, прописав полный путь к oscript.exe в конфигурации launch.json, в свойстве `runtimeExecutable`

**Comment by WonderMr** [comment]
Проблема размщенения и работы расширения точно закрыта. Большое спасибо ещё раз!
