### ISSUE TITLE
Не понятное поведение встроенного TCPСервер

### ISSUE THREAD

**Issue by Macegor** [EvilBeaver/OneScript#1391]
**Описание ошибки:**
Не понятное поведение встроенного TCPСервер, а именно при выполнении соединения любым браузером возникает непонятная задержка начального соединения ~300мс. Если выполнять запрос через postman, такой проблемы не наблюдается. Странность ситуации в том что на linux и на macos такой проблемы нет, исключительно на windows, но ещё более странностей добавляет тот факт, что в winow этой задержки нет даже на windows, при том что код выполняется идентичный. @Nivanchenko тоже не понимает в чём собственно дело. Но я не стал вам выгружать всю свою разрабатываемую платформу, сделал специально с использованием autumn легковесный набросок который возвращает предопределенный текст ответом на любой запрос. Очень прошу помочь разобраться с этой проблемой.

**Воспроизведение ошибки**
1. Скачать [приложенный](https://github.com/EvilBeaver/OneScript/files/13998816/stuffy_platform.zip) архив в любую удобную папку
2. Просто запустить отладку, launch.json уже есть.
3. В сообщении увидите адрес, перейдите по нему в браузере
4. В средствах разработчика браузера найдите вкладку "Сеть" или похожую
5. Обновите страницу (можно несколько раз)
6. Убеждайтесь что есть задержка в начальном соединении

**Ожидаемое поведение**
При начальном соединении задержка должна быть вменяема, и по крайней мере на всех платформах работать идентично, обычно задержка не превышает и 5мс.

**Окружение**
 - ОС: Windows 11
 - Версия: 1.8,4

**Дополнительная информация**
Устанавливать пакеты не нужно, они заботливо упакованы в архиве

**Comment by Macegor** [comment]
Решили вопрос, проблема именно в хроме, точнее в его платформе.

**Comment by EvilBeaver** [comment]
Прошу понять правильно, у меня едва-едва хватает времени, чтобы порешать какие-то свои задачи по 1скрипту. Я вряд ли быстро смогу посмотреть что-то непонятное и магическое. Будет лучше и быстрее, если этим займется кто-то, кто не я.

**Comment by dmpas** [comment]
Проблема возникает в хромоподомных браузерах при обращении по имени:
сначала пытается подсоединться к ipv6 (а на нём оскриптовый сокет не слушает) и потом по таймауту переходит на ipv4 адрес.
Вероятно другие браузеры или сначала отрабатывают ipv4, или делают оба запроса в два потока, но в них лага не наблюдается.

Временное решение - не обращаться к веб-серверу через localhost, а сразу через 127.0.0.1 - так задержки нет.
Более глобальное решение - сделать, чтобы TCPСервер слушал так же ipv6 адрес [::1]
