### ISSUE TITLE
В ветке 1.9 не работает передача параметров в вызов метода делегата рефлектором

### ISSUE THREAD

**Issue by sfaqer** [EvilBeaver/OneScript#1395]
**Опишите ошибку**

```bsl
Функция Тест(Парам) Экспорт
	
	Возврат "1" + Парам;

КонецФункции

Действие = Новый Действие(ЭтотОбъект, "Тест");

Параметры = Новый Массив;
Параметры.Добавить(21);

Рефлектор = Новый Рефлектор();
а = Рефлектор.ВызватьМетод(Действие, "Выполнить", Параметры);

Сообщить(а);
```

Этот код в ветке 1.9 падает в ошибку, при этом в ветке 2.0 корректно отрабатывает:

![image](https://github.com/EvilBeaver/OneScript/assets/32082417/b47e5c9d-209c-4d7a-9620-997ef362ac7c)

**Comment by nixel2007** [comment]
@EvilBeaver можно надеяться на 1.9.1, раз это пофикшено?
