### ISSUE TITLE
Ошибка в отладчике при использовании ЗагрузитьСценарийИзСтроки 

### ISSUE THREAD

**Issue by realalexasha** [EvilBeaver/OneScript#1396]
**Опишите ошибку**

При попытке посмотреть в отладчике значение, возвращаемое методом ЗагрузитьСценарийИзСтроки вижу ошибку "Неизвестный символ: error" Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции". При этом сам сценарий отрабатывает, значение экспортной переменной рассчитывается. Если в параметры передавать пустую структуру или не передавать второй параметр вовсе, то ошибки нет.

**Воспроизведение ошибки**
1. Запустить код 
```
Код = "Перем Результат Экспорт; Результат = Множитель * 5";
Параметры = Новый Структура("Множитель", 2);
ЗагружаемыйСценарий = ЗагрузитьСценарийИзСтроки(Код, Параметры);

```
2. Остановиться отладчиком на строке после этого кода
3. Посмотреть значение переменной ЗагружаемыйСценарий в watch

![photo_2024-02-06_16-11-26](https://github.com/EvilBeaver/OneScript/assets/107741281/a593e2b1-8a84-4f82-9b96-529e64edcf1a)

**Окружение**
 - ОС: Windows
 - Версия: 10

**Comment by nixel2007** [comment]
Версия oscript?

**Comment by EvilBeaver** [comment]
На версии 2.0 и отладчике 0.8 не подтверждается. Однако, на этих версиях отладчик не показывает свойство "Множитель", хотя оно есть у объекта
