### ISSUE TITLE
Ошибка "Конструктор не найден"

### ISSUE THREAD

**Issue by bolsun** [EvilBeaver/OneScript#1399]
В версии 1.9.0 при попытке вызова конструктора в таком варианте 

`ВопросПользователю = Новый ("ВопросПользователю", РежимДиалогаВопрос.ДаНетОтмена);`

возникает ошибка

ScriptEngine.Machine.RuntimeException
  HResult=0x80131600
  Message={Модуль <string 252D09C8> / Ошибка в строке: 1 / Конструктор не найден (ВопросПользователю)}    
ВопросПользователю = Новый ("ВопросПользователю", РежимДиалогаВопрос.ДаНетОтмена); Сообщить("Работает!");
  Source=ScriptEngine
  StackTrace:
   at ScriptEngine.Machine.MachineInstance.NewFunc(Int32 argCount)
   at ScriptEngine.Machine.MachineInstance.MainCommandLoop()
   at ScriptEngine.Machine.MachineInstance.ExecuteCode()
   at ScriptEngine.Machine.MachineInstance.ExecuteModuleBody(IRunnable sdo)
   at ScriptEngine.Machine.Contexts.UserScriptContextInstance.OnInstanceCreation()
   at ScriptEngine.ScriptingEngine.NewObject(LoadedModule module, ExternalContextData externalContext)
   at HostAppTest.Form1..ctor() in D:\Projects\OneScript190\src\HostAppTest\Form1.cs:line 95
   at HostAppTest.Program.Main() in D:\Projects\OneScript190\src\HostAppTest\Program.cs:line 19

В таком варианте отрабатывает без ошибки

`ВопросПользователю = Новый ВопросПользователю(РежимДиалогаВопрос.ДаНетОтмена);`

**В версии 1.7.0 оба варианта работают.**

Тестовое приложение

[HostAppTest.zip](https://github.com/EvilBeaver/OneScript/files/14722108/HostAppTest.zip)

**Comment by nixel2007** [comment]
Второй параметр должен быть массивом

**Comment by tormozit** [comment]
Движок ругается на первый параметр. Без второго параметра такая же ошибка.

**Comment by tormozit** [comment]
В версии 1.7 вариант 
```
		Параметры = Новый Массив;
		Параметры.Добавить(РежимДиалогаВопрос.ДаНетОтмена);
		ВопросПользователю = Новый ("ВопросПользователю", Параметры);
```
выдает ошибку 
`ScriptEngine.Machine.ExternalSystemException: {Модуль C:\Portable\TurboConf\user_scripts\RDT.os / Ошибка в строке: 3030 / Внешнее исключение (System.ArgumentException): Невозможно преобразовать объект типа "ScriptEngine.HostedScript.Library.ArrayImpl" к типу "ScriptEngine.Machine.Contexts.CLREnumValueWrapper`1[System.Windows.Forms.MessageBoxButtons]".}    `

Допускаю что и в 1.9 будет та же ошибка.

В версии 1.7 вариант 
`		ВопросПользователю = Новый ("ВопросПользователю");`
выдает ошибку 
```
ScriptEngine.Machine.RuntimeException: {Модуль C:\Portable\TurboConf\user_scripts\RDT.os / Ошибка в строке: 3030 / Конструктор не найден (ВопросПользователю)}    
		ВопросПользователю = Новый ("ВопросПользователю");   в ScriptEngine.Machine.MachineInstance.NewInstance(Int32 argCount)
```

**Comment by tormozit** [comment]
Очень желательно придумать вариант исправления кода скрипта с сохранением динамического имени типа, который бы работал на всех упомянутых версиях (1.7 и 1.9)
А на 1.7 пока единственный рабочий вариант - текущий
`		ВопросПользователю = Новый ("ВопросПользователю", РежимДиалогаВопрос.ДаНетОтмена);`

**Comment by bolsun** [comment]
@tormozit
>		ВопросПользователю = Новый ("ВопросПользователю", РежимДиалогаВопрос.ДаНетОтмена);

Почему в качестве обходного пути, не использовать предложенный мною вариант? Чтобы скрипт сейчас работал у пользователей на 6.1?

`ВопросПользователю = Новый ВопросПользователю(РежимДиалогаВопрос.ДаНетОтмена);`

https://turboconf.ru/Tasks/9292

**Comment by tormozit** [comment]
Вариант 
`ВопросПользователю = Новый ВопросПользователю(РежимДиалогаВопрос.ДаНетОтмена);`
Сильно затруднит редактирование скрипта, т.к. тогда я не смогу его редактировать в удобном редакторе в конфигураторе.
При его текущем размере удобства играют большую роль.

**Comment by bolsun** [comment]
Тогда я буду откатывать используемую версию OneScript на 1.7 до исправления бага.

**Comment by nixel2007** [comment]
Может Андрея дождаться? :)

**Comment by tormozit** [comment]
Через сколько минут он придет? :)

**Comment by nixel2007** [comment]
Да хоть недель. Сначала нужно подтвердить наличие бага вообще, может это в пользовательском классе ошибка, а не в движке.

**Comment by EvilBeaver** [comment]
@Mr-Rm сможешь посмотреть это? Хотя бы в общих чертах понять, что происходит там

**Comment by maximkin7** [comment]
Добрый день!

В период с 23.03.2024 по 01.04.2024 включительно буду находиться в ежегодном отпуске.
Почта просматриваться не будет.

**Comment by Mr-Rm** [comment]
Изменение в поведении конструктора появилось в версии v1.8.0, а именно как fix #700 - https://github.com/EvilBeaver/OneScript/commit/aeacfe2f2de5c4516b289580447b9d1cfa749233
В версии 1.9.0.6 вариант
```bsl
Параметры = Новый Массив;
Параметры.Добавить(РежимДиалогаВопрос.ДаНетОтмена);
ВопросПользователю = Новый ("ВопросПользователю", Параметры);
```
работает.

**Comment by tormozit** [comment]
Ясно. Тогда сделаю отдельные ветки создания диалога в скрипте с привязкой к версии среды.

**Comment by EvilBeaver** [comment]
> Добрый день! В период с 23.03.2024 по 01.04.2024 включительно буду находиться в ежегодном отпуске. Почта просматриваться не будет.

@maximkin7 спасибо, но Вы обязательно держите нас в курсе!
