### ISSUE TITLE
При вызове через COM пропущенные параметры получают значение Неопределено вместо значения по умолчанию

### ISSUE THREAD

**Issue by tormozit** [EvilBeaver/OneScript#1405]
Имею ОСкрипт 1.7-9 внутри Турбоконфа.
Зову из скрипта функцию базы 1С
```
Функция Ф(П = Ложь) Экспорт
     Сообщить(П);
КонецФункции
```
через COM V83.Application:
`COM.Ф()`
И вижу в отладчике что фактический параметр приходит Неопределено вместо ожидаемого Ложь.

**Comment by EvilBeaver** [comment]
А если из другого языка вызвать, скажем, из VBScript?

**Comment by tormozit** [comment]
Работает ожидаемо из COM клиента 1C. Запустить обычное приложение и нажать кнопку "COM вызов" и закрыть окно нового приложения.
```
	Соединение = Новый COMОбъект("V83.Application");
	Соединение.Connect(СтрокаСоединенияИнформационнойБазы());
	Р = Соединение.Тест();
	Сообщить(ТипЗнч(Р));
```
```
Функция Тест(П = Ложь) Экспорт
	Возврат П;
КонецФункции  
```
Выводит сообщение
_Булево_
[Моя.zip](https://github.com/EvilBeaver/OneScript/files/15215881/default.zip)

**Comment by Mr-Rm** [comment]
Не воспроизводится.
Модуль 1С 8.3.24.1467:
```bsl
Функция Тест(П = Истина) Экспорт
	Сообщить(Строка(ТипЗнч(П))+"="+П);
	Возврат П;
КонецФункции  
```
Запускается OneScript 1.9.1:
```bsl
Соединение = Новый COMОбъект("V83.Application");   
Соединение.Connect("File=""C:\_lab\1S\default\""");
Рез = Соединение.Тест();
Сообщить(Строка(ТипЗнч(Рез))+"="+Рез);
Соединение = 0;
```
Оба сообщения: _Булево=Да_

**Comment by tormozit** [comment]
@bolsun Тогда возможно проблема в Турбоконфе, т.к. я уже десятки раз это проверял и всегда получал в этих параметрах Неопределено. Создал связанную заявку по Турбоконфу https://turboconf.ru/Tasks/9425

**Comment by tormozit** [comment]
Моя ошибка. Неверно обрезал тест. Прошу проверить новый тест. Ключевое отличие - пропуск параметра перед явно передаваемым параметром.
```
Функция Тест(П = Ложь, Я = Ложь) Экспорт
	Возврат П;	
КонецФункции  
Р = Соединение.Тест(, 1);
```
Вызов из 1С через COM опять же показывает ожидаемый результат "Булево".
[Моя.zip](https://github.com/EvilBeaver/OneScript/files/15338735/default.zip)

**Comment by Mr-Rm** [comment]
Новый тест подтверждает ошибку.
Но! При аналогичном вызове из 1С v7.7 также получается `Неопределено`.

**Comment by EvilBeaver** [comment]
> При аналогичном вызове из 1С v7.7 также получается Неопределено

Потому что значение зависит от вызывающего клиента. Там в COM надо передавать специальное значение. Полагаю, v77 и 1Скрипт этого не делают, или делают способом отличным от того, что ожидает v8.

https://stackoverflow.com/questions/32521574/passing-a-com-method-default-parameter

**Comment by Mr-Rm** [comment]
Проверил `System.Reflection.Missing.Value` как значение пропущенного параметра.
Для V83.Application - исправляет рассматриваемую ошибку.
На других проверенных COM-объектах также работает корректно.
Для V77.Application меняет
_Внешнее исключение (System.ArgumentException): Значение не попадает в ожидаемый диапазон._
на 
_Внешнее исключение (System.Runtime.InteropServices.COMException): Несовпадение типов. (Исключение из HRESULT: 0x80020005 (DISP_E_TYPEMISMATCH))_

В дополнение:
Вызов метода с **лишним** пропущенным параметром
```bsl
FSO = ПолучитьCOMОбъект("","Scripting.FileSystemObject");
Рез = FSO.DriveExists("C", );  // <--
```
вызвает **падение** платформы 1С по версию 8.3.25.1286 включительно.

OneScript отрабатывает в целом нормально:
_Внешнее исключение (System.Reflection.TargetParameterCountException): Указанное число параметров не соответствует ожидаемому числу._

**Comment by nixel2007** [comment]
Может быть захардкодить v77, а для остальных случаев передавать Missing.Value?

**Comment by Mr-Rm** [comment]
Пока непонятно, каким значением хардкодить.  Даже вызов  v77 из  v77 с пропущенным параметром не приводит к подстановке значения по умолчанию, остается неопределенное значение (ТипЗначения==0).
Предлагаю игнорировать.

**Comment by EvilBeaver** [comment]
@Mr-Rm можно попросить фикс этого для 2.0?

**Comment by tormozit** [comment]
Возможно связанная ошибка https://github.com/EvilBeaver/OneScript/issues/1588

**Comment by tormozit** [comment]
Да, похоже связь есть.

Сначала ContextValuesMarshaller.ConvertToClrObject() превращает Неопределено в Null
https://github.com/EvilBeaver/OneScript/blob/3845405819e3f6f5dacf6dad110c2bbf5d27ef1d/src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs#L371
А затем этот Null в COMWrapperContext.MarshalIValue() превращается в Missing.Value, т.е. <пропущенный параметр>
https://github.com/EvilBeaver/OneScript/blob/3845405819e3f6f5dacf6dad110c2bbf5d27ef1d/src/ScriptEngine/Machine/Contexts/COMWrapperContext.cs#L161C17-L161C94
` retValue = ContextValuesMarshaller.ConvertToClrObject(val) ?? Missing.Value;;`

Таким образом значение Неопределено в маршалинге 1.9.2-3 превращается в <пропущенный параметр>, т.е. подстановку значения по умолчанию на стороне COM 1C.

Значение Неопределено не должно сливаться с <пропущенный параметр>, т. к. у них разное поведение на стороне приемника COM 1С.

**Comment by tormozit** [comment]
Предлагаю добавить константу BslNoParameter и переписать код так

``` csharp
        public static object ConvertToClrObject(IValue value)
		{
            if (value == null)
                return BslNoParameter;

            // TODO: Вероятно, можно просто заменить на ассерт, что это не IValueReference
            if (value is IValueReference r)
                return ConvertToClrObject(r.Value);
            
            return value switch
            {
                BslNumericValue num => (decimal)num,
                BslBooleanValue boolean => (bool)boolean,
                BslStringValue str => (string)str,
                BslDateValue date => (DateTime)date,
                BslUndefinedValue _ => null,
                BslNullValue _ => null,
                BslTypeValue type => type.SystemType.ImplementingClass,
                IObjectWrapper wrapper => wrapper.UnderlyingObject,
                BslObjectValue obj => obj,
                _ => throw ValueMarshallingException.NoConversionToCLR(value.GetType())
            };
        }

        public static object MarshalIValue(IValue val)
        {
            object retValue;
            if (val is BslDateValue dateVal)
            {
                var date = (DateTime)dateVal;
                retValue = date < MIN_OLE_DATE ? MIN_OLE_DATE : date;
            }
            else if (val == BslNoParameter)
            {
                retValue = Missing.Value;
            }
            else
            {
                retValue = ContextValuesMarshaller.ConvertToClrObject(val);
            }
            return retValue;
        }
```
