### ISSUE TITLE
Английский вариант СоединитьДвоичныеДанные в 1С - ConcatBinaryData, а в OS - ConcatenateBinaryData

### ISSUE THREAD

**Issue by Bayselonarrend** [EvilBeaver/OneScript#1411]
![02a9d1536b7bb9ca7bd7e0664088c1f1](https://github.com/EvilBeaver/OneScript/assets/105596284/20c0084f-20ae-4af4-bf4d-224aa5fbf7e1)

**Comment by Bayselonarrend** [comment]
UPD: Еще метод файла Существует()
1С: Exists
OS: Exist

**Comment by nixel2007** [comment]
Некоторые методы платформы переименовывались. Может быть и здесь так получилось?

**Comment by Bayselonarrend** [comment]
> Некоторые методы платформы переименовывались. Может быть и здесь так получилось?

¯\_(ツ)_/¯

**Comment by Bayselonarrend** [comment]
Пытаюсь всяким devops колдунством перевести либу на английский, вот натыкаюсь на такие штуки

**Comment by nixel2007** [comment]
Спасибо, фиксы - это хорошо

**Comment by Bayselonarrend** [comment]
UPD: Еще (для объекта HTTPЗапрос)

SetBodyFromBinaryData > SetBodyFromBinary
GetBodyAsBinaryData > GetBodyAsBinary

**Comment by dmpas** [comment]
@EvilBeaver Надо вводить deprecated-alias :)
чтобы старый работал и ругался, но и новый работал тоже.

**Comment by nixel2007** [comment]
@dmpas А есть же уже. Кажется как раз на Консоль быль. Или на СИ.ПеременныеСреды

**Comment by EvilBeaver** [comment]
> @EvilBeaver Надо вводить deprecated-alias :) чтобы старый работал и ругался, но и новый работал тоже.

Так он ведь вроде есть, разве нет?
