### ISSUE TITLE
Метод HTTPОтвет.GetBodyAsBinary(), как английский вариант ПолучитьТелоКакДвоичныеДанные(), возвращает строку

### ISSUE THREAD

**Issue by Bayselonarrend** [EvilBeaver/OneScript#1413]
**Опишите ошибку**
GetBodyAsBinary() возвращает строку, хотя ПолучитьТелоКакДвоичныеДанные() - двоичные данные

**Воспроизведение ошибки**
```bsl
Сайт = Новый HTTPСоединение("https://openintegrations.dev");
HTTPЗапрос = Новый HTTPЗапрос("/test_data/picture.jpg");

Ответ = Сайт.Получить(HTTPЗапрос);
ТелоДвоичныеEng  = Ответ.GetBodyAsBinary();
ТелоДвоичныеRus  = Ответ.ПолучитьТелоКакДвоичныеДанные();

Сообщить(ТипЗнч(ТелоДвоичныеEng));
Сообщить(ТипЗнч(ТелоДвоичныеRus));
```

**Ожидаемое поведение**
Должны возвращаться двоичные данные

**Окружение**
 - ОС: Windows 10
 - Версия: 1.9.0.6

![изображение](https://github.com/EvilBeaver/OneScript/assets/105596284/d2e3374f-357d-48f5-b1f7-ab22ad151cdc)

**Comment by dmpas** [comment]
Правильный английский вариант: `GetBodyAsBinaryData`
так что косяк в том, почему оно не поругалось на несуществующий метод... Но это уже другая история.

**Comment by nixel2007** [comment]
@dmpas смотри на всякий случай в обеих ветках. В чате сегодня выяснили, что в 2.0 и 1.9 разные англ синонимы. Тут речь про 1.9
