### ISSUE TITLE
Отладчик одинаково реагирует на Stop и Disconnect, продолжая выполнение

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#1418]
**Опишите ошибку**
При команде Stop в IDE отладчик не завершает процесс, а отключается и продолжает выполнение. При Disconnect аналогично

**Ожидаемое поведение**

Одна из команд должна прерывать процесс

**Окружение**
 - ОС: Windows
 - Версия: 2.0-rc5

**Comment by akpaevj** [comment]
Забыл close в коммите указать
