### ISSUE TITLE
Ошибка в версии 1.8 при получени списка кластеров чере COM

### ISSUE THREAD

**Issue by MikPetrov** [EvilBeaver/OneScript#1422]
**Опишите ошибку**
При получении списка кластеров через COM возникает ошибка, но только на версии 1.8.* 

**Воспроизведение ошибки**
Коннектор = Новый COMОбъект("v83.COMConnector");
СоединениеСАгентомСервера = Коннектор.ConnectAgent("server:2540");
КластерыСерверов = СоединениеСАгентомСервера.GetClusters(); 

получаем ошибку
Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}

**Окружение**
 - ОС: Windows 10
 - Версия oscript: lts (1.8.4.1) и 1.8.4.5 (переключаю через ovm)

**Дополнительная информация**
 - на версиях 1.8.1.4 и 1.9.* ошибка Не проявляется

**Comment by EvilBeaver** [comment]
Спасибо. А можете посмотреть, проявляется ли на версии 2.0?

**Comment by MikPetrov** [comment]
В preview (2.0.0.5-rc4) - Работает.

**Comment by EvilBeaver** [comment]
Если на 1.9 и 2.0 не проявляется, то закрываю, как исправленное
