### ISSUE TITLE
Возникновение исключения "(System.InvalidOperationException): Stack empty.}"

### ISSUE THREAD

**Issue by Macegor** [EvilBeaver/OneScript#1425]
**Описание**
При возникновении исключения в попытке, завершает процедуру в штатном режиме но генерирует исключение "(System.InvalidOperationException): Stack empty.}" в месте вызова. Выполнение в фоновом задании.

**Воспроизведение ошибки**
1. Распаковать архив
2. Настроив рабочую среду выполнить  oscript main.os в терминале
3. В терминале выведется адрес по которому нужно пройти в браузере, пройти по нему
4. Увидеть ошибку в терминале

**Ожидаемое поведение**
Продолжит выполнение кода без исключения

**Окружение**
 - ОС: MacOS 
 - Версия: 1.8.0 - 2.0
[Пример.zip](https://github.com/user-attachments/files/16351727/default.zip)

**Comment by Mr-Rm** [comment]
_MacOS испортила в архиве букву "й" в именах файлов._

Ошибка возникает в onecore\src\Классы\Шаблонизатор.os `ЗаполнитьМассивКодом(Результат, Данные)`:
В функцию `Выполнить(ВесьКод);` передается код из Ядро\Шаблоны\ТестовыйВложенный.html, а именно `Для каждого Элемент из Данные.Массив Цикл`
Контроля параметра `Данные` нет, туда прилетает `Неопределено` и вызывает ошибку _Значение не является значением объектного типа_. Далее идёт некорректная обработка исключения в движке.
В "чистом" виде ошибка выделена в #1427

**Comment by EvilBeaver** [comment]
Закрываю, как исправленное в #1428
