### ISSUE TITLE
Вычислить в подключенном сценарии не видит импортированных модулей 

### ISSUE THREAD

**Issue by sfaqer** [EvilBeaver/OneScript#1451]
**Опишите ошибку**
Внутри сценария подключенного через `ПодключитьСценарий`, `Вычислить` не видит модулей импортированных в этом сценарии

**Воспроизведение ошибки**
1. Распаковать: [_osSyncBag.zip](https://github.com/user-attachments/files/17163708/_osSyncBag.zip)
2. oscript entrypoint.os

```
oscript entrypoint.os
Тест
{Модуль {C:\git\_osSyncBag\src\Тесты\Тест.os}:7:<eval> / Ошибка в строке: 1,1 / Неизвестный символ: Модуль}
```

**Ожидаемое поведение**
```
oscript entrypoint.os
Тест
Тест
```

**Окружение**
 - ОС: Win11
 - Версия: 2.0.0.502-rc4-28767603+e09146395a07e80b39044aaeab5edc7e0a35812d

**Дополнительная информация**

**Comment by akpaevj** [comment]
Так закрыта же была? Косяк какой или по ошибке открыта?
