### ISSUE TITLE
Процедура "ВыгрузитьИнформационнуюБазу" удаляет все файлы в каталоге

### ISSUE THREAD

**Issue by Rambomax** [EvilBeaver/OneScript#1458]
![Буфер обмена02](https://github.com/user-attachments/assets/30f4294e-dcf1-4dfd-9dd6-8731f539536d)

В документации написано: Процедура ВыгрузитьИнформационнуюБазу(ПутьВыгрузкиИБ) - выгрузка информационной базы в файл
"ПутьВыгрузки" подразумеват "путь", т.е. это "каталог", "директория", "папка" и т.п.
Но если указать там вышеперечисленное, то с удивлением можно увидеть, что после выполнения скрипта по указанному "пути" нет файлов - в коде видно, что процедура "ОбеспечитьКаталог(КаталогВыгрузкиИБ)" его "обеспечивает", т.е. "зануляет".
А вот если указать вместо "пути" "ИмяФайлаВыгрузки", то всё работает ОК.
Необходимо или в документации написать, что под словом "путь" понимается "файл", либо добавить детскую проверку, что в параметрах передали "путь" и что-то с этим делать.

**Comment by Bayselonarrend** [comment]
Это же метод v8runner
https://github.com/oscript-library/v8runner

Сам движок OS тут не при делах

**Comment by Bayselonarrend** [comment]
> "ПутьВыгрузки" подразумеват "путь", т.е. это "каталог", "директория", "папка" и т.п.

Кстати, очень спорно: выгрузка идет в **один** файл, поэтому ПутьВыгрузки как путь к файлу выгрузки, на мой взгляд, звучит вполне корректно. Но это ИМХО

**Comment by Rambomax** [comment]
> Это же метод v8runner https://github.com/oscript-library/v8runner
> 
> Сам движок OS тут не при делах

Да, верно, OS, тут вообще не при чём, просто я не знал куда писать, простите)))

**Comment by Rambomax** [comment]
> > "ПутьВыгрузки" подразумеват "путь", т.е. это "каталог", "директория", "папка" и т.п.
> 
> Кстати, очень спорно: выгрузка идет в **один** файл, поэтому ПутьВыгрузки как путь к файлу выгрузки, на мой взгляд, звучит вполне корректно. Но это ИМХО

Возможна выгрузка в "файлы", тогда да, там указывается "путь"
А тут выгрузка была в "файл", я думал он сделает с "ИменемПоУмолчанию", а он грохнул все скрипты, гиты и вскоды в текущем каталоге, обидно было))))

**Comment by Bayselonarrend** [comment]
Да, случаются недопонимания)

**Comment by Bayselonarrend** [comment]
Я бы посоветовал этот Issue закрыть и открыть в репозитории v8runner, потому что ими разные люди занимаются
