### ISSUE TITLE
Ошибка в linux при вызове ЗаписьJSON.УстановитьСтроку()

### ISSUE THREAD

**Issue by salexdv** [EvilBeaver/OneScript#1463]
**Опишите ошибку**
При вызове ЗаписьJSON.УстановитьСтроку() возникает ошибка
`Внешнее исключение (System.TypeInitializationException): The type initializer for 'Newtonsoft.Json.JsonWriter' threw an exception.}`

**Воспроизведение ошибки**
1. Создаем файл json.os с содержимым
```bsl
Значение = Новый Структура("Поле", "Значение");
Запись = Новый ЗаписьJSON();
Запись.УстановитьСтроку();
ЗаписатьJSON(Запись, Значение);
Сообщить(Запись.Закрыть());
```
2. Запускаем `oscript json.os`
3. Видим ошибку
`Ошибка в строке: 3 / Внешнее исключение (System.TypeInitializationException): The type initializer for 'Newtonsoft.Json.JsonWriter' threw an exception.}`

**Ожидаемое поведение**
```json
{
"Поле": "Значение"
}
```

**Окружение**
 - ОС: Kernel: 6.8.0-45-generic arch: x86_64 bits: 64, Desktop: Cinnamon v: 6.2.9 Distro: Linux Mint 22 Wilma
 - Версия: 1.9.2.10

**Comment by nixel2007** [comment]
Mono из официальных реп моно или из убунты? Надо из официальных реп.

**Comment by salexdv** [comment]
> Mono из официальных реп моно или из убунты? Надо из официальных реп.

Ага, помогло. Спасибо!
