### ISSUE TITLE
Нет перевода ПолучитьДвоичныеДанныеИзСтроки > GetBinaryDataFromString

### ISSUE THREAD

**Issue by Bayselonarrend** [EvilBeaver/OneScript#1464]
**Опишите ошибку**
Попытка использования английской версии функции ПолучитьДвоичныеДанныеИзСтроки - GetBinaryDataFromString - приводит к ошибке

**Воспроизведение ошибки**
1. Добавить GetBinaryDataFromString в модуль

**Ожидаемое поведение**
Ошибка не появляется. Также подобной ошибки нет в 1.9.1

**Окружение**
 - ОС: Windows 10
 - Версия: 2.0.0-rc4

**Дополнительная информация**
```
Ошибка в строке: 160,11 / Неизвестный символ: GetBinaryDataFromString}
```

![изображение](https://github.com/user-attachments/assets/2b5f3805-7463-4622-a65c-0b5845634bba)

**Comment by Bayselonarrend** [comment]
UPD: Воспроизводится на rc5

**Comment by maximkin7** [comment]
Добрый день!

В период с 27.10.2024 по 04.11.2024 включительно, буду находиться в ежегодном отпуске.
Почта просматриваться не будет.

**Comment by Bayselonarrend** [comment]
UPD: ПолучитьHexСтрокуИзДвоичныхДанных > GetHexStringFromBinaryData еще нету

**Comment by Bayselonarrend** [comment]
UPD: РазделитьДвоичныеДанные > SplitBinaryData

**Comment by Bayselonarrend** [comment]
Фул лист крч)

```bsl
	СоответствиеОшибок.Вставить("GetBinaryDataFromString"          , "ПолучитьДвоичныеДанныеИзСтроки");
	СоответствиеОшибок.Вставить("GetHexStringFromBinaryData"       , "ПолучитьHexСтрокуИзДвоичныхДанных");
	СоответствиеОшибок.Вставить("SplitBinaryData"                  , "РазделитьДвоичныеДанные");
	СоответствиеОшибок.Вставить("GetStringFromBinaryData"          , "ПолучитьСтрокуИзДвоичныхДанных");
	СоответствиеОшибок.Вставить("GetBinaryDataBufferFromString"    , "ПолучитьБуферДвоичныхДанныхИзСтроки");
	СоответствиеОшибок.Вставить("GetBinaryDataFromHexString"       , "ПолучитьДвоичныеДанныеИзHexСтроки");
	СоответствиеОшибок.Вставить("GetBinaryDataBufferFromBinaryData", "ПолучитьБуферДвоичныхДанныхИзДвоичныхДанных");
	СоответствиеОшибок.Вставить("GetBinaryDataBufferFromHexString" , "ПолучитьБуферДвоичныхДанныхИзHexСтроки");
	СоответствиеОшибок.Вставить("GetBinaryDataFromBinaryDataBuffer", "ПолучитьДвоичныеДанныеИзБуфераДвоичныхДанных");
        СоответствиеОшибок.Вставить("ConcatBinaryData"                 , "СоединитьДвоичныеДанные");
```

**Comment by Mr-Rm** [comment]
Лист, увы, не фулл. В нём также ещё и все Bitwise-функции. 
Способа решения два:
- явно прописать всем методам недостающие алиасы
- изменить атрибут `ContextMethod`, сохранив  идею, что если алиас не указан, то им будет имя метода

_Причина проблемы в v2 - появление класса `SymbolsCollection`_

**Comment by EvilBeaver** [comment]
> изменить атрибут ContextMethod, сохранив идею, что если алиас не указан, то им будет имя метода

Вот это. Я был уверен, что так и работает. Если не работает, надо починить
