### ISSUE TITLE
Поддержка оператора Goto

### ISSUE THREAD

**Issue by Diversus23** [EvilBeaver/OneScript#1468]
# Описание задачи

OneScript практически полностью покрывает весь синтаксис 1С, но не добавлен оператор **goto**. Понятно, что любой код можно написать и без goto и это давний спор нужен он в принципе или нет, но для обратной совместимости, все же, было бы не плохо, если бы его добавили.

## Кейс использования

Столкнулся с тем, что [обфускатор нетленки](https://netlenka.org) обфусцирует код и активно использует для этих целей оператор goto и получается, обфускатор нельзя использовать для скриптов на OneScript. Мы, в одной своей коммерческой разработке используем нетленку и есть идея, что можно было бы собрать не только в конфигурации 1С свою разработку, но и упаковать модули в exe с помощью OneScript, но так как это все открыто, то будет правильнее обфусцировать код модулей перед упаковкой в exe.

PS: Понимаю, что OneScript - это open source и меня сейчас заклюют с осуждениями по поводу обфускации кода, но все же изначальный вопрос не совсем к этому относится. Просто привел кейс когда это может быть нужно.

**Comment by EvilBeaver** [comment]
Дубль #1329 и #6

**Comment by EvilBeaver** [comment]
Закрываю, как дубль
