### ISSUE TITLE
Не работает опубликованный плагин отладчика 0.9.0

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#1470]
**Опишите ошибку**

Есть жалобы на неработоспособность отладчика 0.9.0 в МакОс (и вероятно, вообще)

**Окружение**
 - ОС: Мак (любая?)
 - Версия: 1.9 (возможно, 2)

**Comment by EvilBeaver** [comment]
1. Собираемый с ветки develop плагин отладчика содержит бинари в корне vsix, а должен в подпапке bin
2. Собираемый с ветки develop плагин отладчика имеет конфиг, в котором нет примера для включения логирования
3. При подключении к версии 1.9 ругается `"Данный ключ отсутствует в словаре.","$type":"RpcExceptionDto"},"Id":"SetMachineExceptionBreakpoints","ServiceName":"IDebuggerService","$type":"RpcCallResult"}` - это из-за новых фич по брейкпоинтам. Их нет в целевом рантайме.

**Comment by akpaevj** [comment]
> 1. Собираемый с ветки develop плагин отладчика содержит бинари в корне vsix, а должен в подпапке bin
> 2. Собираемый с ветки develop плагин отладчика имеет конфиг, в котором нет примера для включения логирования
> 3. При подключении к версии 1.9 ругается `"Данный ключ отсутствует в словаре.","$type":"RpcExceptionDto"},"Id":"SetMachineExceptionBreakpoints","ServiceName":"IDebuggerService","$type":"RpcCallResult"}` - это из-за новых фич по брейкпоинтам. Их нет в целевом рантайме.

Выведи отладчики в отдельные ветки (и сборки, соответственно) хотя-бы, иначе так и будут спотыкания об совместимость и постоянный якорь, мешающий развитию
