### ISSUE TITLE
Не поддерживается шифрование Zip

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#152]
Originally reported by: **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**

---

Используемая библиотека работы с Zip бросает NullReferenceException при попытке шифрования архива.

Вообще, библиотека Ionic.Zip уже не развивается. Желательно перейти на SharpZibLib

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/152

**Comment by asosnoviy** [comment]
@EvilBeaver закрывай

**Comment by EvilBeaver** [comment]
Не, я лучше гляну, вдруг можно починить.

**Comment by asosnoviy** [comment]
я шифрование с установкой пароля перепутал, посмотрел тест, там установка пароля была =(
