### ISSUE TITLE
Не плохо бы сделать подписку на новости по проекту

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#166]
Originally reported by: **Anonymous**

---

по почте или твитер

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/166

**Comment by EvilBeaver** [comment]
_Original comment by_ **Alexey Lustin (Bitbucket: [allustin](http://bitbucket.org/allustin), GitHub: [allustin](http://github.com/allustin))**:

---

@EvilBeaver - лучше использовать форму mailchimp подписку на новости сайта oscript.io. Сразу встраивается.

Кстати - а как получается что задачу создаёт "Аноним" ?

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Кто бы мне еще это сделал про mailchimp))

**Comment by bambr1975** [comment]
http://email-practice.ru/2012/04/15/11-mailchimp-signup-form/ зарегистрироваться на сайте mailchimp.com нужно только
> Копируем код созданной формы из поля снизу и вставляем на свой сайт — туда, куда вам угодно: на поля, в подвал сайта, на конкретную страницу.

**Comment by EvilBeaver** [comment]
wontfix: все новости печатаются в телеграм. Отдельной процедуры написания "новостей" не появилось.
