### ISSUE TITLE
Работа с БД

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#169]
Originally reported by: **Виктор Сергиенко (Bitbucket: [nextkmv](http://bitbucket.org/nextkmv), GitHub: [nextkmv](http://github.com/nextkmv))**

---

Есть желание реализовать обертку для ado .net. Реализующую взаимодействие с БД посредством ODBC драйвера. 
В идеале работа с БД будет сводиться к следующему виду.

```
#!1с

 // Подключаем библиотеку для работы с БД
 ПодключитьВнешнююКомпоненту("onedb.dll");
 Запрос = Новый Запрос(); 
 // Задаем строку подключения к ODBC
 // Поддерживаеся большое количество СУБД
 Запрос.СтрокаПодключения    = "Driver={Microsoft Access Driver (*.mdb)};"
                            + "Dbq=c:\\Data\\Northwind.mdb;Uid=Admin;Pwd=;";
 // Указываем наш запрос                          
 Запрос.ТекстЗапроса  = "SELECT ProductID, UnitPrice, ProductName from products "
                        + "WHERE UnitPrice > &МинимальнаяЦена "
                        + "ORDER BY UnitPrice DESC;";
 // Устанавливаем параметры
 Запрос.УстановитьПараметр("МинимальнаяЦена",100);
 // Выполняем запрос
 // В качестве результата возвращем ТаблицаЗначений
 ТаблицаЗапроса = Запрос.Выполнить();



 // Для варианта с добавлением записей предлагаю формат
 Запрос.ТекстЗапроса  = "INSERT INTO products (ProductID, UnitPrice, ProductName) VALUES (&КодПродукта, &Цена, &Наименование)";
 // Устанавливаем параметры
 Запрос.УстановитьПараметр("КодПродукта",1);
 Запрос.УстановитьПараметр("Цена",5000);
 Запрос.УстановитьПараметр("Наименование","Планшет Samsung");
 // Выполняем запрос
 // В качестве результата вернется пустая таблица
Запрос.Выполнить();
```

Ваши предложения и замечания?

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/169

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

Может, стоит проработать схему со стандартными для 1С Результатом Запроса и Выборкой?

**Comment by EvilBeaver** [comment]
_Original comment by_ **Виктор Сергиенко (Bitbucket: [nextkmv](http://bitbucket.org/nextkmv), GitHub: [nextkmv](http://github.com/nextkmv))**:

---

Да. Возможно так будет лучше.
Тогда функция Выполнить вернет РезультатЗапроса в случае запроса на выборку, и пустой РезультатЗапроса в случае со вставкой значений.
Далее результат запроса можно использовать так же как и в 1С.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Стандартная схема всяко лучше. Для UPDATE/DELETE запросов можно возвращать вообще отдельный объект СкалярныйРезультатЗапроса (или как-то так)

```
sql = "INSERT INTO Production.ProductCategory (Name) VALUES (@Name); "
        + "SELECT CAST(scope_identity() AS int)";
Запрос.Текст = sql;
Результат = Запрос.Выполнить();
Сообщить("Новый идентификатор записи = " + Число(Результат));
```

Понятно, что конкретную семантику надо продумать, это я на глаз набросал.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Только у нас еще соединение с БД не подразумевается неявно, значит в объектной модели надо будет еще и соединение с БД предусмотреть и запрос к ней привязать.

Вброс варианта:

```
СУБД = ПодключитьСУБД(); // некий способ возвращающий подключение (сейчас неважно)
Запрос = Новый Запрос(СУБД);
// блабла
Запрос.Выполнить();
```

**Comment by EvilBeaver** [comment]
_Original comment by_ **Дмитрий Малюгин (Bitbucket: [magin67](http://bitbucket.org/magin67), GitHub: [magin67](http://github.com/magin67))**:

---

Позволю себе пару замечаний.
1)  Функционал работы с БД полезен и нужен для проекта.
2) Не вижу большого смысла в копировании подходов 1С. Простота должна быть в приоритете, а не "стандартные схемы".
3) Работа с БД и поддержка запросов - это не одно и то же.
4) Создание для каждого чиха нового типа  данных ("СкалярныйРезультатЗапроса") - некошерно, - приводит к умножению количества сущностей без необходимости.
5) Это я все к чему. В проекте уже есть крутой тип данных " ТаблицаЗначений". Вот его и надо использовать/развивать для взаимодействия с БД. Вполне пока будет достаточно возможности добавления к записям таблицы БД заданной таблицы значений, и наоборот,  - извлечения данных из БД в виде ТЗ.
Необязательно в виде запроса, можно определить обычные функции/методы объекта работы с БД.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Alexey Lustin (Bitbucket: [allustin](http://bitbucket.org/allustin), GitHub: [allustin](http://github.com/allustin))**:

---

Позволю себе прокомментировать и высказать свои мысли

Во первых - пожалуйста не забудьте что мы тут на *nix живем, поэтому обертка на ADO.NET насколько мне помниться лишит нас совместимости с linux.

Отдельно я соглашусь с Дмитрием - уже есть объект таблица значений. Возможно стоит реализовать его расширение, когда ТаблицаЗначений "мапится" напрямую в БД. Этакий ORM получается https://ru.wikipedia.org/wiki/ORM, хотя там мапятся классы. Или даже https://ru.wikipedia.org/wiki/ActiveRecord

раз у нас внизу C#/Mono то тогда возможно стоит делать расширение ТаблицыЗначений c помощью LINQ https://msdn.microsoft.com/ru-ru/library/bb397926.aspx

То есть я к тому, что насколько я помню - LINQ и есть "обёртка" над ADO.NET, ТаблицаЗначений - объект "Контролер" данных и остается еще реализовать Класс "КонтекстБазыДанных"

Фактически появляется объект ТаблицаЗначенийСКонтекстомБазыДанных.

тогда на псевдо коде это будет выглядеть так (или еще как-то)

```
#!c#

_контекстБазы = Новый КонтекстБазыДанных("Data Source=1sjournal.sqlite");
_таблицаЗаписейЖурнала =  _контекстБазы.СоздатьКонтекстТаблицы("Entries");

Для каждого _запись из _таблицаЗаписейЖурнала Цикл
  Сообщить(_запись.TimeStamp);
КонецЦикла

```

Как делать запись - тут вопрос длинный. Очень не хочется работать напрямую с ODBC, потому что тогда возникают "ужасные" вопросы работы с PreparedStatements (параметризированные запросы) или еще хуже прямое управление транзакциями и уровнями блокировок. 

Пока мысли такие...

**Comment by EvilBeaver** [comment]
_Original comment by_ **Alexey Lustin (Bitbucket: [allustin](http://bitbucket.org/allustin), GitHub: [allustin](http://github.com/allustin))**:

---

Дополнительно - как вы поняли наверное, мне видится очень много опасностей если будем работать с прямыми запросами INSERT, UPDATE, DELETE. Хотя возможно я слишком привык к различными ORM движкам, которые за меня сами управляют работой с БД.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Виктор Сергиенко (Bitbucket: [nextkmv](http://bitbucket.org/nextkmv), GitHub: [nextkmv](http://github.com/nextkmv))**:

---

В общем вопрос большой и очень емкий.
По поводу работы в linux то судя по http://www.mono-project.com/docs/database-access/providers/odbc/ это возможно.
Что касается ORM то это вопрос гораздо более сложный чем просто работа с БД, и наверное больше зависит от того что мы в итоге хотим получить от 1Script. Нужно с чего то начать, я вижу что пока нужно хотя бы базовая возможность работы с БД, ODBC с одной стороны представляет простую возможность в реализации с другой поддержку нескольких СУБД. В дальнейшем естественно функционал следует наращивать, используя все возможности .Net.
По поводу схемы работы, я думаю что не стоит изобретать велосипед там где это не надо. Понятно что полной совместимостью с 1С не добиться но сделав логику работу аналогичной той что принята в 1С мы значительно снизим порог вхождения в 1script. Кстати к ORM это тоже относиться. В linq нужно "въехать" поэтому если и делать ORM то максимально похоже на то что принято в 1С.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Коллеги, я не соглашусь вот с каким тезисом:

```
Простота должна быть в приоритете, а не "стандартные схемы"
```

Как раз стандартная схема и обеспечивает простоту. Любой 1С-ник умеет работать с запросами. Порог вхождения в классы СУБД у нас будет нулевой, если мы возьмем стандартную схему. Любая другая приведет к необходимости изучать новый API.

Т.е. возможна и схема с таблицей значений, но стандартная схема должна быть, т.к. ее уже все знают "из коробки".

И потом - получить таблицу значений из СУБД можно командой Запрос.Выполнить().Выгрузить().

Насчет "СкалярногоРезультата" и прочего - вопрос открыт, это было всего лишь предложение для обсуждения. Предлагаю сообществу продолжить дискуссию :)

Таблица значений не должна ничего знать про индексы СУБД и ключи. Есть принцип единой ответственности (SRP). Таблица - это универсальная коллекция и пусть ей остается. Не надо на нее навешивать СУБД.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Виктор Сергиенко (Bitbucket: [nextkmv](http://bitbucket.org/nextkmv), GitHub: [nextkmv](http://github.com/nextkmv))**:

---

Согласен. Сохранение синтаксиса 1С, будет преимуществом. Изобретение нового API там где без этого можно обойтись будет недостатком.
А по поводу скалярного запроса, вопрос открытый. Хотя вполне возможно возвращать тот же РезультатЗапроса.
Если запрос не возвращает ничего то будет пустой результат запроса, в противном случае будет возвращена таблица значений.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Дмитрий Малюгин (Bitbucket: [magin67](http://bitbucket.org/magin67), GitHub: [magin67](http://github.com/magin67))**:

---

Поскольку я не участник проекта и вряд ли им стану в ближайшее время, то приоритет в принятии решений в любом случае остается за теми, кто реально что-то делает по проекту.

Тем не менее меня смущает стремление "делать все как у 1С", повторяя все "изгибы и ямочки". В 1С нет, например, подключаемых через use библиотек, а в onescript есть, и это большой плюс onescript с потенциалом.

Всё-таки надо стремиться "сохранить дух, а не букву". OneScript все равно требует отдельного изучения. Не думаю, что есть какие-то проекты, которые надо портировать на oscript, не меняя ни строчки кода.

Что касается использования в работе с БД именно языка запросов, то в наших проектах это считается плохим стилем. Поскольку тексты запросов высокоэнтропийны, трудны в поддержке и пр.

Опять же по нашей практике все реляционные операции все равно пришлось реализовать для всех типов коллекций, то есть писать код соединений,  объединений и выборок без языка запросов.

И да, для хорошей проработки вопроса требуется написать намного больше букв.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Михаил Кузнецов (Bitbucket: [Hotey](http://bitbucket.org/Hotey), GitHub: [Hotey](http://github.com/Hotey))**:

---

Доброго дня. Просто в качестве мыслей вслух. Если реализовывать Запросы 1-в-1 как в 1С, пытаясь сохранить низкий порог вхождения, то придётся озаботиться ещё и воспроизведением конструктора запросов 1С. Многие ведь пишут запросы используя только конструктор, при этом не особо разбираясь в стандарте SQL.
Я это всё к тому, что возможно и правда не стоит для запросов сильно заморачиваться сохранением синтаксиса 1С?..

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Речь не идет о сохранении синтаксиса языка запросов 1С. Язык запросов 1С - это не SQL, он привязан к ORM и оперирует объектами, реквизитами, табличными частями и т.п. Как справедливо заметили выше - нам не нужен ORM, т.к. нет самих объектов, хранимых в СУБД.

Нам нужен доступ к СУБД общего назначения - обычные SQL запросы. Ну и конструктор запросов это тоже как-бы часть IDE, а никак не библиотек доступа к СУБД.
Вопрос в том, как должен выглядеть API работы с базой данных.

@nextkmv, насколько я понял, ты планируешь реализовать эту задачу? Могу назначить ее тебе?

**Comment by EvilBeaver** [comment]
_Original comment by_ **Виктор Сергиенко (Bitbucket: [nextkmv](http://bitbucket.org/nextkmv), GitHub: [nextkmv](http://github.com/nextkmv))**:

---

Буду рад внести свои 5 копеек в проект. Назначай.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

@nextkmv явно назначить не получается, просто сделай форк и мы будем ждать pull-request

**Comment by EvilBeaver** [comment]
_Original comment by_ **Nikita Gryzlov (Bitbucket: [nixel2007](http://bitbucket.org/nixel2007), GitHub: [nixel2007](http://github.com/nixel2007))**:

---

Позвольте свои пять копеек. А это точно нужно на уровне движка, а не в составе стандартной библиотеки?  
Черновой вариант реализации выглядит очень похоже на библиотеку v8runner. Подключение по ODBC вроде и в линуксе и в винде можно реализовать. Какой плюс от вливания такого функционала в движок?

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

@nixel2007 оно и планировалось в составе библиотеки, как внешняя компонента. Просто @nextkmv создал issue здесь, как фича-реквест.

**Comment by ret-Phoenix** [comment]
Реализовал в виде компоненты https://github.com/ret-Phoenix/oscript-sql

**Comment by artbear** [comment]
ИМХО исходная задача реализована @ret-Phoenix 
@EvilBeaver @nextkmv @nixel2007 что скажете?

**Comment by EvilBeaver** [comment]
Спасибо, @ret-Phoenix !!!

**Comment by nixel2007** [comment]
:+1:
