### ISSUE TITLE
Работа с ftp

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#170]
Originally reported by: **Евгений Мартыненков (Bitbucket: [EvgenyMartynenkov](http://bitbucket.org/EvgenyMartynenkov), GitHub: Unknown)**

---

Хотелось бы иметь объекты-аналоги "FTPСоединение" и "FTPФайл"

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/170

**Comment by Diversus23** [comment]
Да, было бы отлично, если бы появилась поддержка FTP

**Comment by EvilBeaver** [comment]
Найдите исполнителя, кто может. Быстрее пойдет.

**Comment by ret-Phoenix** [comment]
Фактически портировать: http://www.cyberforum.ru/csharp-beginners/thread1296122.html
Либо http://metanit.com/sharp/articles/1.php

**Comment by dmpas** [comment]
в работе
https://github.com/dmpas/oscript-ftp

**Comment by dmpas** [comment]
`opm install ftp`
