### ISSUE TITLE
Объект ОписаниеТипов

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#182]
Originally reported by: **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**

---

Для типизации колонок ТаблицыЗначений и ДереваЗначений

P.S. примерная реализация есть в V8Viewer 2.0, надо перетащить

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/182

**Comment by EvilBeaver** [comment]
_Original comment by_ **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**:

---

А зачем нам нужна типизация этих колонок?

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

Ну если навскидку, то:
1. заполнять колонку пустым значением нужного типа
2. ругаться, если не тот тип в колонку суём

а для чего именно - это уже второй вопрос, но по-хорошему, библиотеки не скрипты и должны выполняться с соблюдением некоторой строгости.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

@artbear 
1. Совместимость с кодом, портируемым из 1С.
2. Вставка значения по умолчанию нужного типа (Колонка Булево, точно Ложь при добавлении строки)
3. Приведение типов (Метод Привести объекта ОписаниеТипов) - редкая функция, но весьма полезная.

**Comment by dmpas** [comment]
@EvilBeaver я тут взялся, не серчай :smiley_cat:

**Comment by EvilBeaver** [comment]
Я только рад :)
