### ISSUE TITLE
Установка c помощью chocolatey

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#183]
Originally reported by: **Alexey Lustin (Bitbucket: [allustin](http://bitbucket.org/allustin), GitHub: [allustin](http://github.com/allustin))**

---

необходимо упростить установку движка и его обновления через пакетный менеджер 

```
#!Gherkin

# encoding: utf-8
# language: ru

Функционал: Установка через пакетный менеджер chocolatey.org

Как разработчик скриптов и библиотек
Я хочу чтобы 1Script устанавливался через командный пакетный менеджер 
Чтобы была возможность автоматизировано устанавливать и обновлять 1Script одной командой

Контекст:
Существует официальный аккаунт 1Script на сайте "https://chocolatey.org/"
И существует пакет oscript загружаемый автоматизировано через сервер сборок доступный по адресу https://chocolatey.org/packages/oscript.install
И пакет oscript имеет подтвержденный статус

@ForCIServer
Сценарий: Загрузка нового дистрибутива на сервер chocolatey
Когда я вызываю команду на сервере сборок "choco pack && choco push"
Тогда я вижу что в таблице версий на странице https://chocolatey.org/packages/oscript.install появилась новая сборка

Сценарий: Установка стабильной сборки 1Script
Когда я вызываю команду на клиентской Windows машине "choco instal oscript"
Тогда при вызове команды "oscript.exe" я наблюдаю стандартный вывод 1Script с версией соответствующей текущей стабильной версии

Сценарий: Установка версии "ночная сборка" 1Script
Когда я вызываю команду на клиентской Windows машине "choco instal oscript-develop"
Тогда при вызове команды "oscript.exe" я наблюдаю стандартный вывод 1Script с версией соответствующей текущей ночной сборке

Сценарий: Установка версии "ночная сборка" 1Script когда уже была установлена стабильная сборка
Когда я вызываю команду на клиентской Windows машине "choco instal oscript-develop"
Тогда происходит замена стабильной версии на ночную сборку
И в консоли я вижу текст "ПРЕДУПРЕЖДЕНИЕ: обнаружена установленная стабильная версия 1Script - переход с версии develop обратно на стабильную будет невозможен"  
И при вызове команды "oscript.exe" я наблюдаю стандартный вывод 1Script с версией соответствующей текущей ночной сборке

Сценарий: Обновление стабильной сборки 1Script
Когда я вызываю команду на клиентской Windows машине "choco upgrade oscript"
Тогда при вызове команды "oscript.exe" я наблюдаю стандартный вывод 1Script с версией

Сценарий: Установка версии "ночная сборка" 1Script
Когда я вызываю команду на клиентской Windows машине "choco upgrade oscript-develop"
Тогда при вызове команды "oscript.exe" я наблюдаю стандартный вывод 1Script с версией

```

Документация тут - https://github.com/chocolatey/choco/wiki/CreatePackages

P.S. Задачу создаю чтобы не забыли про развертывание у конечных пользователей

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/183

**Comment by EvilBeaver** [comment]
_Original comment by_ **Alexey Lustin (Bitbucket: [allustin](http://bitbucket.org/allustin), GitHub: [allustin](http://github.com/allustin))**:

---

BDD в действии - во время написания задачи сразу возникли 2 коллизии на которые необходимо обратить внимание:
- как сделать пакет **доверенным** - об этом уже давно стоит задуматься
- откат с ночной сборки на стабильную лучше всего делать через деинсталяцию/инсталяциию

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

@allustin **доверенный пакет**, ты имеешь в виду подписанный setup.exe?

**Comment by artbear** [comment]
Автоматическая установка и обновление OneScript реализованы в https://github.com/artbear/OneScript-install

И Вин, и Линукс.
Проверено на travis-ci и appveoyor

**Comment by JohnyDeath** [comment]
А с самим шоколадом что? В пакетах до сих пор нет.
Взываю @pumbaEO . Ты же вроде бы собирался их попинать. Получилось?

**Comment by dmpas** [comment]
тут всё глухо, как я понял?

@allustin @pumbaEO @EvilBeaver

**Comment by artbear** [comment]
Так 1скрипт давно уже умеет ставиться и без шоколада.
Мой репозитарий https://github.com/artbear/OneScript-install

И Вин, и Линукс.
Проверено на travis-ci и appveoyor

**Comment by artbear** [comment]
Упс, оказывается, я выше уже писал о репо :)

**Comment by artbear** [comment]
Примеры развертывания 1скрипта на новых виртуалках
+ https://github.com/artbear/1testrunner/blob/develop/.travis.yml
+ https://github.com/artbear/1testrunner/blob/develop/appveyor.yml

**Comment by dmpas** [comment]
@artbear 

ну если задача сводится только к установке последней версии на целевую машину, то твои скрипты решают вопрос.

а если всё-таки заявитель хочет заиметь шоколадный пакет со всеми его шоколадными прелестями - это другой вопрос.

задачу надо закрыть либо как выполненную, либо как забитую.

**Comment by ghost** [comment]
ну закрывайте

p.s. "заявитель" блин - прям напрягли

**Comment by JohnyDeath** [comment]
Почему закрывать? Заявитель говорил именно о шоколаде

**Comment by EvilBeaver** [comment]
Закрывать не надо. Забитые задачи должны мозолить глаза и мучить совесть. А ну как придет контрибьютор и возьмется?

**Comment by JohnyDeath** [comment]
Так @pumbaEO пулял туда запрос уже очень давно. Но что там не так он не говорит почему-то

**Comment by dmpas** [comment]
@pumbaEO призовись!

**Comment by pumbaEO** [comment]
Создаем шаблон:
```
choco.exe new onescript silentargs="/S" url="http://oscript.io/downloads/latest/msi"
```
редактируем onescript.nuspec и заменяем все что в _REPLACE_ 
и финальный после этого выполняем 
```
choco pack
``` 
после этого стандартно 
```
choco push onescript.nuget
``` 
но для отправки, Андрею надо зарегистрироваться и получить api для публикации.

**Comment by dmpas** [comment]
@pumbaEO звучит вроде просто. а затык в чём был?

**Comment by pumbaEO** [comment]
Просто год назад, было значительно проблемней.

**Comment by dmpas** [comment]
тренируюсь на кошках (v8unpack). Если всё получится - доделаю и здесь.

**Comment by dmpas** [comment]
на chocolatey.org модерацию уже неделю не могу дождаться, потому будем хоститься на myget.
```
choco install onescript.cli -Source http://myget.org/F/onescript -y
```
Сейчас там 13, 14, 15 и 16 версии. Как по-правильному закидывать ночник, я ещё не придумал.

@allustin @artbear @pumbaEO @EvilBeaver

**Comment by igostv** [comment]
Лучше с https
`choco install onescript.cli -Source https://myget.org/F/onescript -y`

**Comment by dmpas** [comment]
@EvilBeaver ты обещал README на английском. Попробуем 20-ку протолкнуть в родные шоколадные репы.

**Comment by EvilBeaver** [comment]
Ога, займусь

**Comment by igostv** [comment]
>Лучше с https

Получается без разницы, т.к. все равно http://oscript.io
```
Downloading onescript 
  from 'http://oscript.io/downloads/1_0_19/OneScript-1.0.19-setup.exe'
```

**Comment by ghost** [comment]
Подниму вверх - мы все также устанавливаем ? через myget ?

**Comment by dmpas** [comment]
@allustin да. Нам надо README на второй язык одинэса перевести.

**Comment by ghost** [comment]
@dmpas README из текущего репозитория ? Я правильно понимаю что это файлик рядом README_EN.md или они хотят один файлик с двумя языками ?

**Comment by dmpas** [comment]
@allustin им главное, чтобы было описание на английском. В каком виде - не особо важно.

**Comment by EvilBeaver** [comment]
@dmpas закрываю же?

**Comment by dmpas** [comment]
не. Давай таки я добью автоматический push из твоего дженкинса при сборке мастера.

**Comment by EvilBeaver** [comment]
Права есть?

**Comment by dmpas** [comment]
кажись да.

**Comment by asosnoviy** [comment]
winget на дворе. гасите ихуз =)

**Comment by dmpas** [comment]
согласен. в топку шоколад
