### ISSUE TITLE
ВызватьИсключение c передачей контекста исключения

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#188]
Originally reported by: **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**

---

`ВызватьИсключение Новый ИнформацияОбОшибке(/*Любой контекст*/);`

По мотивам https://github.com/EvilBeaver/oscript-library/pull/29#issuecomment-154034817

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/188

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Тогда сразу конкурс: как будет называться свойство в объекте ИнформацияОбОшибке, в котором мы будем получать то значение, которое передали в момент выброса?

```
Исключение
    Сообщить(ИнформацияОбОшибке.<какое-тоСвойство>);
КонецПопытки
```

**Comment by EvilBeaver** [comment]
_Original comment by_ **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**:

---

`КонтекстИсключения` ? `ЗначениеИсключения` ? `ОбъектИсключения` ?

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

ПараметрыИсключения, Параметры.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

ДополнительныеДанные?

```
// ....
Исключение
     Сообщить(ИнформацияОбОшибке().ДополнительныеДанные);
     Сообщить(ИнформацияОбОшибке().ПараметрыИсключения);
     Сообщить(ИнформацияОбОшибке().Параметры);
     Сообщить(ИнформацияОбОшибке().КонтекстИсключения);
КонецПопытки;
```

**Comment by EvilBeaver** [comment]
_Original comment by_ **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**:

---

`ДополнительныеСвойства`  как у 1С ?

**Comment by EvilBeaver** [comment]
_Original comment by_ **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**:

---

На чем остановимся?

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Я за _ДополнительныеДанные_ или за _Параметры_. @dmpas?

**Comment by EvilBeaver** [comment]
_Original comment by_ **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**:

---

`Параметры` короче

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

Поддерживаю _Параметры_.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Принято. Только одно уточнение. Если мы будем передавать в конструктор некий anyType, то тогда это `Параметр`, ибо `Параметры` намекает на какую-то коллекцию. Как считаете?

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

@dmpas, @artbear - все-таки множественное или единственное число?

**Comment by EvilBeaver** [comment]
_Original comment by_ **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**:

---

Договорились о Параметры, значит, множественное

**Comment by artbear** [comment]
Ура!

**Comment by EvilBeaver** [comment]
Запрашиваю всестороннее тестирование

**Comment by artbear** [comment]
Доработаю код в своем проекте https://github.com/artbear/1bdd
Вот и будет тестирование :)

**Comment by artbear** [comment]
@EvilBeaver Ты просил проверить, я проверил и нашел баг.
Выложил PR #274

Исправишь?

**Comment by artbear** [comment]
Посмотрел код https://github.com/EvilBeaver/OneScript/commit/756dc8b1e4945d3ea43b13ce47af0d4cf752ee7e
ИМХО архитектурная проблема.
В случае параметризованного исключения и обычного исключения внутри кода обработки исключения на самом деле разные объекты, получаемые по `ИнформацияОбОшибке()` :(
В первом случае у объекта есть атрибут `Параметры`, а вот во втором нету, что и приводит к ошибке.

С точки зрения клиентского кода внутри кода обработки нельзя заранее знать, какое исключение было вызвано - обычное или параметризованное.
Поэтому предлагаю всегда использовать атрибут `ИнформацияОбОшибке::Параметры`

**Comment by artbear** [comment]
@EvilBeaver Переоткрывай issue

**Comment by EvilBeaver** [comment]
Переоткрывать не надо, это новый баг, штатный процесс

**Comment by EvilBeaver** [comment]
Да, я проглядел это... Спасибо @artbear.
