### ISSUE TITLE
Метод Выполнить()

### ISSUE THREAD

**Issue by theshadowco** [EvilBeaver/OneScript#2]
Пишу пакет для авто тестов на oscript'е и столкнулся с проблемой - нет аналога 1с-ного метода Выполнить. Есть в планах или предложение, как реализовать?

**Comment by EvilBeaver** [comment]
Выполнить не поддерживается, но можно немного это компенсировать классом "Рефлектор". Вам **"Выполнить"** для какой задачи потребовался?

Ссылка на документацию: http://oscript.io/docs/page/language

И потом, пакет автотестов у нас вроде как есть (только не пакет, а инструмент, который надо бы оформить в пакет) https://github.com/EvilBeaver/oscript-library/issues/31

**Comment by theshadowco** [comment]
Спасибо, попробую данный класс (как не увидел его), должен подойти.
Ну а по задаче (кстати за ссылку на раннер спасибо, посмотрю) - пишу автотестировщик, который на основании версии в ГИТе (спасибо ГитСинку) разворачивает (или обновляет) тестовую и прогоняет набор тестов из гита (и не только) и формирует отчет YandexAllure.

**Comment by artbear** [comment]
@theshadowco 
> набор тестов из гита (и не только)

Поделись, что за набор тестов? какой инструмент для тестирования юзаешь?

**Comment by theshadowco** [comment]
@artbear пока небольшой - в основном дымовые (проверка платформой и вызов сервисных методов прикладного режима в режиме предприятия), затем хочу подключить vanessa'ские (конечно будет патченный плеер, если мои разработки не будут приняты сообществом) + статический анализ исходников.

В принципе делаю универсальную схему - анализ каталога на наличие скриптов os, имеющих набор определенных методов 
 - инфо о тесте
 - добавление тестов в набор (содержит набор кейсов, шагов и методов для выполнения шага)
Потом менеджер тестирования будет их выполнять (вызывая указанные методы из теста). По собранным данным генерить отчет аллюр.

Пока такие планы.

@EvilBeaver Гигантское спасибо за Рефлектор - подошел как нельзя кстати.

**Comment by artbear** [comment]
Не совсем понял структуру.
Какую роль выполняет os-скрипты?
Где будут храниться тесты и наборы тестов? в os-скриптах или обработках или где?
как будут выполняться тесты и наборы тестов?

**Comment by artbear** [comment]
А изучал наш xUnitFor1C для возможности тестирования в режиме Предприятия?
чем не устроил? в чем фишка нового инструмента?
я не с целью потроллить, а именно с целью узнать новое!

ЗЫ Я Рефлектор для OneScript как раз в первую очередь для тестов и сделал :)

**Comment by allustin** [comment]
@theshadowco ты явно делаешь что-то странное, но лучше не буду тебя останавливать.

**Comment by theshadowco** [comment]
@artbear os-скрипты могут сами содержать сценарии тестирования (методы скрипта), а также могут запускать сторонние инструменты, например xUnitFor1C по сути передавая им управление.

Фишка проста - может использовать как кем-то разработанные фреймворки, для чего нужно будет только реализовать скрипт для подключения, так и использовать специально написанные сценарии тестирования и получать отчет в едином формате.

**Comment by theshadowco** [comment]
@allustin странное? возможно.
