### ISSUE TITLE
Не проходит тест process при запуске из под Cygwin

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#212]
Originally reported by: **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**

---

Оставлю себе напоминалку

```
 Тест №3: ТестДолжен_ЗаписатьВоВходнойПотокПроцесса: C:\home\dmpas\workspace\onescript\tests\process.os

ОШИБКА: Упал тест <ТестДолжен_ЗаписатьВоВходнойПотокПроцесса>, файл <C:\home\dmpas\workspace\onescript\tests\process.os>:
    {Модуль C:\home\dmpas\workspace\onescript\tests\testrunner.os / Ошибка в строке: 69 / Сравниваемые значения (1
2
3
; 1
3
2
) не равны, а хотели, чтобы были равны.}
```

Обновление: воспроизводится только в случае работы через SSH-соединение.

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/212

**Comment by n-dimens** [comment]
Версия приложения 1.0.13.135

Тест также не проходит с такой же ошибкой на Windows 10 x64 ru, в cmd.exe и powershell.

Условие выполнения: кодовая страница 65001. При cp866 и cp1251 тест проходит успешно. Так что видимо дело не SSH и Cygwin, а в utf-8 в консоли в винде

**Comment by dmpas** [comment]
Ха! Вот это спасибо! И правда, даже под SSH при кодировке 1251 всё проходит успешно.

**Comment by n-dimens** [comment]
Новые выводы: Проблема не совсем в том, что в Windows проблемы с кодировкой UTF-8. Проблема в "гармонии" между программой sort.exe и кодировкой UTF-8 в Windows. Т.е. по факту - это не баг OneScript.

Новое предложение: Поскольку цель теста - тестирование возможности записи во входной поток процесса, создаваемого через 1Script, а не тестирование использования sort.exe из 1Script, использовать другой процесс для теста, корректно работающий в разных ОС. Например, консольная программа со следующим кодом:

``` cs
 static void Main(string[] args) {
    using (var reader = Console.In) {
        var lines = new List<String>();

        var line = reader.ReadLine();
        while (line != null) {
            lines.Add(line);
            line = reader.ReadLine();
        }

        lines.Sort();

        foreach (var line1 in lines)
        {
            Console.Out.WriteLine(line1);    
        }                
    }
}
```

успешно прошла тест записи во входной поток независимо от текущей кодировки консоли.
Правда в этом случае усложняется сборка проекта, поскольку надо таскать дополнительный проект и подкладывать результат сборки тестам... Ну тут уже надо дальше думать, как лучше сделать.

P.S.: Возможно, для подобных сценариев (вызывающих ошибку), если они будут возникать в реальной работе, стоит лучше предоставить возможность управления кодировкой консоли напрямую через 1Script, и тогда "костыльное" решение можно будет использовать в конкретных случаях, не портя исходную реализацию 1Script.

**Comment by EvilBeaver** [comment]
Я за управление кодировкой потоков. Отдельный проект не таскаем, ни к чему это

**Comment by n-dimens** [comment]
Тогда я свой PR закрываю, а эта задача превращается в:
1. Изменить тест `ТестДолжен_ЗаписатьВоВходнойПотокПроцесса` так, чтобы он использовал стандартный процесс, не зависящий от кодировки входного потока
2. Добавить в библиотеку процедуру, позволяющую изменить InputEncoding консоли, и функцию, возвращающую текущую InputEncoding консоли

@EvilBeaver Правильный итог?

**Comment by EvilBeaver** [comment]
П. 1 я бы исключил. Во-первых, я не знаю такой процесс, а во-вторых, с появлением апи управления кодировкой этот тест просто будет регулировать кодировку для sort

**Comment by n-dimens** [comment]
@EvilBeaver Задачу, я так понимаю, можно закрыть?

**Comment by EvilBeaver** [comment]
Да
28 Июн 2016 г. 8:57 AM пользователь "Gorbunov Sergey" <
notifications@github.com> написал:

**Comment by faberlic-service-1c** [comment]
@EvilBeaver Закрывай issue, больше ни у кого прав нет.
