### ISSUE TITLE
ФиксированноеСоответствие.Получить() ругается при несуществующем ключе

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#216]
Originally reported by: **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**

---

```
Соответствие = Новый Соответствие;
ФиксированноеСоответствие = Новый ФиксированноеСоответствие(Соответствие);

ТутНеДолжноРугаться = ФиксированноеСоответствие.Получить(1);
// АВотТутДолжноРугаться = ФиксированноеСоответствие[1];
```

1С не ругается, ОдноСкрипт ругается: Ошибка в строке: 4 / Значение, соответствующее ключу, не задано

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/216

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Ну что вот за люди, а? Эти методы должны же одинаково работать - по индексу и через Получить.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

Таки нет. Вот выдержка из синтаксис-помощника для Соответствие.Получить() :

```
Возвращаемое значение:

Значение элемента соответствия.
Неопределено - если указанный ключ отсутствует. 
Описание:

Получает значение по ключу. **Работает аналогично оператору [].**
```

А вот для ФиксированноеСоответствие.Получить() :

```
Возвращаемое значение:

Тип: Произвольный. 
Неопределено - ключ не найден 
Описание:

Получает значение по ключу.
```

то есть уже **без** этого пояснения.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Да, но зачем эта разница? Какой сценарий применения это должно покрывать?

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

Не знаю.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

А я кажется знаю. Там внутри какой-то костыль, который меняет объект Соответствие при обращении по индексу даже на чтение. Я что-то такое помню и именно поэтому была бага #215, которую ты зарегистрировал. Что-то на эту тему проскакивало где-то на форумах. И 1С не смогла этот костыль побороть, поэтому вынуждена была сделать разницу.

ИМХО.

**Comment by EvilBeaver** [comment]
_Original comment by_ **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**:

---

Ага, у 1с есть баг смены соответствия при получении несуществующего ключа.
Наше поведение считаю верным.
Помнится мне, я даже спец.тест этой фичи для 1скрипт написал
Предлагаю оставить, как есть, и issue закрыть

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

Я ж теперь спать не смогу! Всю жизнь я делал так:

```
Если КакоетоСооветствие.Получить("Ключ") = Неопределено Тогда
    // Ключа там нет
    // ну или он там есть, но по неведомой причине кто-то сунул туда Неопределено
    //    , что в моём случае равносильно тому, что его там нет
    Возврат;
КонецЕсли;
```

Это ж теперь придётся сначала циклом обходить коллекцию и смотреть, есть там ключ или нет.

Я понимаю про [] - он возвращает по сути своей ссылку, но Получить() даёт RawValue, которое ну никак не повлияет на исходный объект.

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Артур, поясни, что имел в виду про "баг смены соответствия"?

**Comment by EvilBeaver** [comment]
_Original comment by_ **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**:

---

Баг изменения соответствия, добавления ключа со значением Неопределено, о
чем ты и писал выше

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Что-то я уже путаться начинаю. @dmpas почему ты спать не сможешь? В #215 ты привел пример кода, который показывает, что 1С не добавляет ключ, если его не было. Или все-таки добавляет?

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

И да, @artbear полагаю, issue закрывать не надо. На мой взгляд, наоборот, ни оператор [] ни Получить() не должны бросать исключений при несуществующем ключе. НО: в 1С поведение такое, как описано в issue. Поэтому:
- Нужно поддержать сценарий, приведенный @dmpas - когда надо безопасно проверить отсутствие ключа в коллекции
- Нужно оставить поведение оператора [] таким же, как в 1С. По принципу наименьшего удивления. Ожидается, что наши объекты ведут себя так же, как 1С-овские.

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

1С исключение не бросает, если я делаю **Фиксированное**Соответствие.Получить("НесуществующийКлюч").

Мы здесь про **Фиксированное** соответствие говорим. В #215 было не фиксированное.

1С добавляет ключ в **обычное** соответствие при использовании оператора [] и в случае записи туда. То есть:

```
А = Соответствие[1]; // ничего не добавляется и ни на что не ругается. Даёт Неопределено и всё.
Соответствие[1] = 2; // <-- вот тут добавляется
```

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

@dmpas в задаче ты себя поставил - правильно ли я понял, что ты сам исправишь?

**Comment by EvilBeaver** [comment]
_Original comment by_ **Sergey Batanov (Bitbucket: [dmpas](http://bitbucket.org/dmpas), GitHub: [dmpas](http://github.com/dmpas))**:

---

@EvilBeaver [Да](https://bitbucket.org/EvilBeaver/1script/pull-requests/32/fixed-216/diff)

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

fixed #216 Исправлено поведение метода ФиксированноеСоответствие.Получить()

**Comment by dmpas** [comment]
Что-то я подзабыл, на чём мы остановились в этой задаче?
Ошибка есть, из обсуждения видно, что я хотел исправить, но @EvilBeaver закрыл задачу.

**Comment by EvilBeaver** [comment]
@dmpas так пофиксили же вроде, не?

**Comment by dmpas** [comment]
@EvilBeaver как-то [нет](https://github.com/EvilBeaver/OneScript/blame/develop/src/ScriptEngine.HostedScript/Library/FixedMapImpl.cs)

**Comment by EvilBeaver** [comment]
@dmpas у меня четкое ощущение дежа-вю, что я это фиксил. Да, я вижу blame, но в него не верю %) Посмотри, кстати камент выше: `fixed #216 Исправлено поведение метода ФиксированноеСоответствие.Получить()` Это было еще на битбакете. но этого коммита сейчас нет. Где он?

**Comment by dmpas** [comment]
@EvilBeaver на битбакете ветка удалялась после слияния, вот и нет коммита. По истории коммитов искал в этих периодах - не нашёл ничего.

**Comment by EvilBeaver** [comment]
Ну ветка же куда-то сливалась. Значит изменения не должны были пропасть....

**Comment by EvilBeaver** [comment]
https://bitbucket.org/EvilBeaver/1script/issues/216/------------------------------------------

Последний линк ведет в никуда.

**Comment by EvilBeaver** [comment]
@dmpas короче, налицо потеря коммита. В битбакете есть ссылки, но все мертвые. Пулреквест с исправлением - пустой. Я переоткрываю задачу, надо внести исправление.

**Comment by dmpas** [comment]
На битбакете запросы сливались в новую ветку, а в девелоп ты потом сам сливал после тестов. Может, ты слил мои коммиты к себе, но в девелоп не слил потом?

**Comment by dmpas** [comment]
я люблю гит :) 

нашёл коммит и на своей машине, и в битбакете

https://bitbucket.org/dmpas/onescript/commits/e0519d2c3b9bf1f62ff1d9ea9bd9c40b7c753a3d?at=master

**Comment by EvilBeaver** [comment]
Жду пулреквест ))
