### ISSUE TITLE
Сделать прототип новой экосистемы сборки

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#222]
Originally reported by: **Alexey Lustin (Bitbucket: [allustin](http://bitbucket.org/allustin), GitHub: [allustin](http://github.com/allustin))**

---

Нужно сделать прототип сборочных серверов

https://circleci.com/
http://wercker.com/
https://appveyor.com/

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/222

**Comment by dmpas** [comment]
Эту закрыть может?
