### ISSUE TITLE
API чтения потоков процесса требует расширения

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#231]
Originally reported by: **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**

---

Синхронные операции чтения потоков вывода/ошибок процесса недостаточно гибкие. В текущей реализации легко попасть на deadlock.

Требуется дополнить API чтения потоков средствами разруливания блокировок и ожиданий чтения.

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/231

**Comment by dmpas** [comment]
@EvilBeaver 
> легко попасть на deadlock

А можешь привести лёгкий сценарий такого лёгкого попадания?

**Comment by EvilBeaver** [comment]
Да, есть статья в MSDN, краткая суть:

Есть два потока выхлопа: stdout и stderr. Если оба они будут читаться синхронно, то это потенциальный deadlock. Один из них должен читаться другим потоком в фоне.

У потока процесса есть некий буфер, куда он гадит. При переполнении буфера (если читающее приложение не вычитывает буфер), то ОС приостановит поток, ожидая, пока буфер вычитают.

Приложение читает чей-то stdout, в этот момент читаемое приложение выдает ошибку и пишет в свой stderr. Переполняет его буфер и блокируется. но Читатель ждет пока закончится наполнение stdout, а оно уже никогда не закончится.

Разруливается чтением в 2 Thread-а. В однопоточной среде нужны таймауты операций чтения на потоках IO.

**Comment by EvilBeaver** [comment]
Реализовал неблокирующее чтение из потоков процесса.
Коммиты: 65f0c46b2 c4be395688

Особенность (возможно Breaking change):

Методы **ЕстьДанные** **Прочитать** и **ПрочитатьСтроку** возвращают результат немедленно, показывая "Срез" на момент вызова. Отсутствие данных не означает конца потока. Оно означает, что на момент вызова в потоке данных не было.

Данные в потоке появляются "построчно". Т.е. не будет оборванных на середине строк.
