### ISSUE TITLE
Разбор тегов #Область и #КонецОбласти

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#241]
Originally reported by: **Nikita Gryzlov (Bitbucket: [nixel2007](http://bitbucket.org/nixel2007), GitHub: [nixel2007](http://github.com/nixel2007))**

---

Сейчас если в теле скрипта встречаются инструкции препроцессору (в том числе и Область), oscript валится с ошибкой.

Хорошо бы добавить поддержку этих тегов (ничего не делающих), хотя бы для областей.

Цель (как обычно) - упросить порт с 1с.  
P.S. Да и в редакторах будет полезно наличие сворачиваемых групп в *.os.

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/241

**Comment by dmpas** [comment]
Заберу поковырять на досуге

**Comment by EvilBeaver** [comment]
В DirectiveResolver просто сделай логику их игнорирования

**Comment by dmpas** [comment]
@EvilBeaver ага, это место я уже нашёл. Я думаю, не прикрутить ли сразу ЕслиКлиентыВсякие.

**Comment by EvilBeaver** [comment]
Просто на игнор? В 2.0 можно украсть препроцессор, он там есть. Давай лучше пока без него

**Comment by dmpas** [comment]
@nixel2007 можно закрывать заявку?

https://github.com/EvilBeaver/OneScript/commit/e2306466a6d06cdce9d863f44863acaaceb6272a

**Comment by nixel2007** [comment]
@dmpas если работает, то, думаю, да :)
