### ISSUE TITLE
метод НайтиФайлы зацикливается в ссылках

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#242]
Originally reported by: **Anonymous**

---

Вот такой кусок:

```
    СИ = Новый СистемнаяИнформация;
Енв = СИ.ПеременныеСреды();
Корень = Енв.Получить("USERPROFILE")+"..\";
НайденныеФайлы = НайтиФайлы(Корень, "????????-????-????-????-????????????", Истина);
Для Каждого нн Из НайденныеФайлы Цикл
```

приводит к ошибке:

```
 running command> oscript -encoding=utf-8 e:\_git_\ini_parse\main.os stat
 Oscript: 1.0.13.77
 {Модуль e:\_git_\ini_parse\main.os / Ошибка в строке: 86 / Внешнее исключение: Отказано в доступе по пути "C:\Users\sukhikh\AppData\Local\Application Data".}
```

В 1С отрабатывает нормально.

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/242

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

@vsuh А точно это полный фрагмент кода? Просто у меня не воспроизводится. Может ошибка в другой строке?

**Comment by EvilBeaver** [comment]
_Original comment by_ **Valery Sukhikh (Bitbucket: [vsuh](http://bitbucket.org/vsuh), GitHub: [vsuh](http://github.com/vsuh))**:

---

точно.

```
СИ = Новый СистемнаяИнформация;
Енв = СИ.ПеременныеСреды();
Корень = Енв.Получить("USERPROFILE")+"..\";
НайденныеФайлы = НайтиФайлы(Корень, "????????-????-????-????-????????????", Истина);
Message(НайденныеФайлы);
```

Сейчас удалил линки `Application Data` и `History` в `%userprofile%\local`  теперь пишет:

```
{Модуль E:\_git_\1.os / Ошибка в строке: 4 / Внешнее исключение: Отказано в доступе по пути  C:\Users\sukhikh\AppData\Local\Microsoft\Windows\INetCache\Content.IE5".}
```

windows 10x64

**Comment by EvilBeaver** [comment]
_Original comment by_ **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**:

---

Стоп, а под термином "линки" мы что понимаем в данном случае?

**Comment by EvilBeaver** [comment]
Вероятно, удастся объединить с #307

**Comment by EvilBeaver** [comment]
@vsuh, можешь подсказать, а как 1С себя ведет при нахождении линков? Оно включает их в результат или игнорирует?

**Comment by vsuh** [comment]
Если долго наступать в Far на Junction `Application Data` в каталоге `c:\users\default\appdata`, то цепочка получится бесконечной:
![image](https://cloud.githubusercontent.com/assets/12156293/17562441/99f14ca8-5f33-11e6-9290-6fb4cbabd5de.png)

1С в массив возвращаемый методом `НайтиФайлы("C:\Users\Default\AppData","*.*",Истина);` включает только `C:\Users\Default\AppData\Local\Application Data (и
C:\Users\Default\AppData\Local\History)
`

а `OneScript`, соответственно, говорит, что 
D:\tmp>oscript search.os
{Модуль D:\tmp\search.os / Ошибка в строке: 2 / Внешнее исключение: Отказано в доступе по пути
 "c:\Users\All Users\Application Data".}

**search.os**:

```
dir="c:\users\ALLUSE~1";
arf=FindFiles(dir, "*.*",true);
Message(arf.count());

```

**Comment by vsuh** [comment]
Кстати, в Питоне 3.5 метод `rglob` класса `pathlib` **Junctions**, похоже, пропускает не глядя. По крайней мере в выводе этой программы я ни одного **Junction** не нашел

```
from pathlib import Path
i=0
cr = sorted(Path("c:/users").rglob("*/*.*"))
for f in cr:
    i+=1
    try:
        k=f.stat()
        print(i,"[", str(k.st_nlink),"]", str(f))
    except PermissionError as err:
        print(err)
    except UnicodeEncodeError as utf:
        print(utf)
```
