### ISSUE TITLE
Обновление библиотек средствами движка

### ISSUE THREAD

**Issue by JohnyDeath** [EvilBeaver/OneScript#245]
Реально ли добавить возможность обновление библиотек из https://github.com/EvilBeaver/oscript-library параметром к oscript.exe ? Примерно так:
`oscript.exe -update-libs`

**Comment by EvilBeaver** [comment]
А зачем?

**Comment by EvilBeaver** [comment]
кстати, в opm есть ключ update

**Comment by nixel2007** [comment]
@JohnyDeath @EvilBeaver этот вопрос и вопрос в гиттере - все решается через opm)

**Comment by JohnyDeath** [comment]
Ну кака зачем?
У меня есть движок с плагинами. Хочу, чтоб и движок и плагины были по возможности в актуальном состоянии. И я не хочу заморачиваться с гитом и клонированием реп. Что такое opm я и большинство будущих пользователей не знают.

Взгляните на любую программу с плагинами. В большинстве из них плагины можно обновлять из самой программы без кучи гемора.

**Comment by nixel2007** [comment]
> Что такое opm я и большинство будущих пользователей не знают.

если вкратце - предполагается, что opm в обозримом будущем будет основным способом установки и обновления библиотек. Работа с гитом и исходниками библиотек останется только для контрибьюторов библиотек.

Для этого надо доработать opm и провести "рекламную компанию" по его популяризации. С анонсами и всей фигней.

**Comment by JohnyDeath** [comment]
Т.е. это будет плагин для установки и обновления плагинов?

> Для этого надо доработать opm

А что там на повестке дня?

**Comment by nixel2007** [comment]
> Т.е. это будет плагин для установки и обновления плагинов?

вроде того. полноценный пакетный менеджер, как gem для ruby или npm для node.js.
Который будет поставляться сразу с oscript (он и сейчас поставляется в виде опции в установке библиотек, а надо бы сделать его установку принудительно).

> А что там на повестке дня?

Очень драфтово я начал накидывать вот здесь https://github.com/nixel2007/opm-features.
По большей части там то, что есть сейчас. Просто надо зафиксировать это в виде фич для структурированности и последующих проверок поведения.

Лично я хочу это сделать как кальку с npm (с несколько меньшей функциональностью на начальном этапе, конечно же).
Когда я это обсуждал с @EvilBeaver, он вроде бы согласился с моей точкой зрения на развитие opm в этом направлении. 

Отвечая на твой вопрос - на повестке дня допроектировать функциональность и начать ее реализовывать. Впрочем, как и всегда :D
