### ISSUE TITLE
Позволить писать точку с запятой после #Использовать

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#247]
Сейчас, если написать `#Использовать tempfiles;` отобразится синтаксическая ошибка.

В 1с через # отображаются инструкции препроцессору, в которых вроде бы и не было никогда точек с запятой (#Если, #Область...).
Но #Использовать - это такая директива, после которой прямо хочется впаять точку с запятой. Как uses в том же паскале/делфи. 

Вот такое пожелание.

**Comment by EvilBeaver** [comment]
Все, что после "Использовать" - это имя пакета. Точка с запятой - это оператор языка и к препроцессору отношения не имеет. Даже комментарии после "Использовать" это не комментарии, а часть имени.
Делалось это за тем, чтобы возможны были иерархические импорты

```
#Использовать json/v2
#Использовать cmdline/fluent-api
```

**Comment by EvilBeaver** [comment]
Хотя, вполне возможно, что это я перемудрил.

**Comment by EvilBeaver** [comment]
В любом случае, точка с запятой это не лексема препроцессора. В 1С если ты поставишь точку с запятой после #КонецЕсли; то точно также получишь ошибку

**Comment by nixel2007** [comment]
Примерно таких комментариев я и ожидал :) согласен, с точки зрения синтаксиса это не верно
