### ISSUE TITLE
Добавить класс "СведенияОВерсииФайла"

### ISSUE THREAD

**Issue by JohnyDeath** [EvilBeaver/OneScript#249]
Хочется иметь возможность получать информацию о версии файла.
Вот такой класс: https://msdn.microsoft.com/ru-ru/library/system.diagnostics.fileversioninfo(v=vs.110).aspx

Для начала хотя бы просто получить версию указанного файла.

**Comment by JohnyDeath** [comment]
@EvilBeaver это сложно включить в проект? Библиотека вроде бы стандартная.
Без этого метода я не могу определить текущую версию платформы 1С, которая нужна мне для определения того, умеет ли платформа сама выгружать исходники иерархически.
В том исусе можно, конечно, пойти и другим "костылявым" путем, но хотелось бы проверять именно версию файла платформы.

Единственное я не в курсе, будет ли работать эта стандартная библиотека в линуксах

**Comment by artbear** [comment]
А в чем проблема определять по имени каталога, как сделано сейчас?

чт, 19 Май 2016, 8:12 Evgeny Martynenkov notifications@github.com:

**Comment by JohnyDeath** [comment]
В линуксе не прокатит

**Comment by EvilBeaver** [comment]
@JohnyDeath в линуксе и версия файла, считываемая из виндовых манифестов не прокатит.

**Comment by JohnyDeath** [comment]
ок, тогда в той задаче пойду другим путем. 
У этой задачи можно сделать наинизший приоритет.

**Comment by EvilBeaver** [comment]
Это если и делать, то в виде компоненты в составе библиотеки.

**Comment by artbear** [comment]
@JohnyDeath Заведешь issue в репо библиотек?

**Comment by JohnyDeath** [comment]
А почему в составе библиотек? В 1С есть встроенные средства по выдаче сведений о версии файла.
Как оно, кстати, в линуксах работает?

**Comment by artbear** [comment]
> В 1С есть встроенные средства по выдаче сведений о версии файла.

Это какие?

**Comment by JohnyDeath** [comment]
Обознался. Оказывается нету (
