### ISSUE TITLE
Missing Message procedure / отсутствует процедура Сообщить();

### ISSUE THREAD

**Issue by Areso** [EvilBeaver/OneScript#250]
Title says it all.
Проблема возникает если выполнить что-либо содержащее вызов этой процедуры из обычного запуска, варианты: компилировать/выполнить. 
Версия 1.0.12 (Windows)

**Comment by nixel2007** [comment]
@Areso так сообщить - это не класс, это процедура.

Вы используете его с `Новый`?

P.S. помимо заголовка issue хорошо бы еще приложить версию интерпретатора, пример кода, и способ вызыва ошибки - из обычного запуска, из `-check` или из `-compile`

**Comment by Areso** [comment]
@nixel2007 - спасибо за уточнение; нет.
Вот строчка кода из рабочей функции: 
Message(ErrorDescription(), MessageStatus.Attention);
её аналог на русском также работает без проблем в 1С:Предприятии 8.2

**Comment by nixel2007** [comment]
@Areso согласно встроенному синтаксис-помощнику, у метода "сообщить" нет второго параметра

http://oscript.io/syntax/page/%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D0%B4%D1%83%D1%80%D1%8B%20%D0%B8%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20%D0%B2%D0%B7%D0%B0%D0%B8%D0%BC%D0%BE%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F%20%D1%81%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%BE%D0%B9

/cc @EvilBeaver выглядит как ситуация с НСтр. Параметр ничего менять не будет, но для упрощения портирования надо его добавить.

**Comment by Areso** [comment]
@nixel2007 на текущий момент OneScript не умеет правильно обрабатывать
сообщить(); 
и спотыкается именно на нем, а не на втором параметре.

**Comment by nixel2007** [comment]
@Areso я к тому, что в oscript вообще у процедуры Сообщить() только один параметр. В принципе.

**Comment by nixel2007** [comment]
А так Сообщить используется в сотнях скриптов, без каких-либо проблем.

**Comment by ghost** [comment]
@Areso метод сообщить() штатный и используется везде.

https://github.com/EvilBeaver/OneScript/blob/5897fd6464ecc7ade9e852a0194094661cad42a2/tests/socket.os#L19

Как вы вызываете `Сообщить()`

**Comment by nixel2007** [comment]
@allustin там выше по тексту:

`Message(ErrorDescription(), MessageStatus.Attention);`

**Comment by ghost** [comment]
версию oscript можно посмотреть просты запуском oscript без параметров, у большинства из нас

```
$ oscript
1Script Execution Engine. Version 1.0.13

Usage:

I. Script execution: oscript.exe <script_path> [script arguments..]

II. Special mode: oscript.exe <mode> <script_path> [script arguments..]
Mode can be one of these:
  -measure   measures execution time
  -compile   shows compiled module without execution
  -encoding=<encoding-name> set output encoding

III. Build standalone executable: oscript.exe -make <script_path> <output_exe>
  Builds a standalone executable module based on script specified

IV. Run as CGI application: oscript.exe -cgi <script_path> [script arguments..]
  Runs as CGI application under HTTP-server (Apache/Nginx/IIS/etc...)
```

**Comment by ghost** [comment]
@Areso  А тогда тут по другому - для таких вещей используется https://github.com/EvilBeaver/oscript-library/tree/develop/src/logos

то есть в вашем случае нужно писать

```
#Использовать logos

Лог = Логирование.ПолучитьЛог("oscript.aresso.testing-script");
Лог.УстановитьУровень(УровниЛога.Ошибка);
Лог.Ошибка(ErrorDescription());
```

**Comment by Areso** [comment]
@allustin Version 1.0.12.58 http://oscript.io/downloads скачивал там Windows Installer ( http://oscript.io/downloads/latest/msi ), там отдает именно эту версию.

**Comment by Areso** [comment]
Хорошо, без второго параметра (я даже не помню откуда он там взялся, видимо копипастой с какого-то предыдущего проекта) все работает, спасибо.
@nixel2007 @allustin , скажите на Предупреждение(); issue открывать или я опять чего-то сделал не так или недопонял?

**Comment by nixel2007** [comment]
@Areso насколько я понимаю, метода "Предупреждение" вообще нет в оскрипте, т.к. это работа с интерфейсом (модальное всплывающее окно).

**Comment by nixel2007** [comment]
@Areso если вам нужно разграничение типов сообщений, то посмотрите в сторону библиотеки logos, ссылку на которую давал @allustin 

Эту задачу прошу не закрывать, на лицо разница в поведении с платформой, и надо это обсудить с @EvilBeaver

**Comment by EvilBeaver** [comment]
@Areso **"Предупреждение"** - это интерактивный диалог. Его в консольной утилите не имеет смысла держать. Поэтому, данный метод отсутствует. Аналогично и с "Вопрос".

@nixel2007 да, полагаю, что второй параметр для Сообщить надо сделать. Предлагаю @Areso завести отдельную issue, как автору требования.

**Comment by Areso** [comment]
@EvilBeaver  хорошо.

**Comment by JohnyDeath** [comment]
@nixel2007 ты не тот "Сообщить" смотришь в синтаксис-помощнике. Метод "Сообщить" из глобального контекста всегда имел 2 параметра

> Глобальный контекст.Сообщить (Global context.Message)
> Глобальный контекст (Global context)
> Сообщить (Message)
> Синтаксис:
> Сообщить(<ТекстСообщения>, <Статус>) 

А вот метод "Сообщить" из класса "СообщениеПользователю" параметров не имеет

**Comment by Areso** [comment]
@JohnyDeath мы перешли в следующий issue (https://github.com/EvilBeaver/OneScript/issues/251) для обсуждения вопроса, можете туда также скопировать?

**Comment by nixel2007** [comment]
@Areso мне кажется, @JohnyDeath меня не так понял. я имел ввиду именно процедуру глобального контекста и именно СП оскрипта. класса СообщениеПользователю в оскрипте вообще нет, насколько я помню.

**Comment by JohnyDeath** [comment]
Да, я неправильно понял.
