### ISSUE TITLE
Message procedure doesn't take second parameter / процедура Сообщить() не принимает второй параметр

### ISSUE THREAD

**Issue by Areso** [EvilBeaver/OneScript#251]
Отличается поведение процедуры Сообщить(); на OneScript и 1С:Предприятие.
OneScript не принимает второй параметр, в то время как платформа позволяет такое. 
Пример на английском:
Message(ErrorDescription(), MessageStatus.Attention);
Пример на русском:
Сообщить(ОписаниеОшибки(), СтатусСообщения.Внимание);

**Comment by EvilBeaver** [comment]
Полагаю, здесь можно также сделать и задачку #68 

БезСтатуса и Обычное - стандартный цвет консоли
Внимание - Желтый
Важное/ОченьВажное - красный
