### ISSUE TITLE
Не поддерживается кодировка сценария windows-1251.

### ISSUE THREAD

**Issue by n-dimens** [EvilBeaver/OneScript#252]
Сценарий, отредактированный в стандартном notepad, или notepad++ выдает ошибку

`{Модуль D:\home\code\onescript.os / Ошибка в строке: 1 / Неизвестный символ ?}`

Если тот же файл пересохранить с помощью TestApp, то он выполняется нормально.

Текст сценария

`Сообщить("Привет")`

Кодировка - windows-1251

Запускаю из командной строки Windows 10

`oscript onescript.os`
или
`oscript -encoding=windows-1251 onescript.os`

Команда
`D:\home\code>oscript -check onescript.os`

выдает сообщение

`{Модуль D:\home\code\onescript.os / Ошибка в строке: 1 / Неизвестный символ ?}`
`????????("??????!")`

После преобразования в utf-8 через notepad++ ошибка исчезла, сценарий выполняется нормально.

**Comment by nixel2007** [comment]
Сообщите версию oscript, пожалуйста.
`oscript -v`

**Comment by nixel2007** [comment]
@EvilBeaver на 1.0.13.106 (сегодняшний ночник) такое поведение подтверждаю.

**Comment by n-dimens** [comment]
`D:\home\code>oscript -v`

`1Script Execution Engine. Version 1.0.12.58`

**Comment by n-dimens** [comment]
Скачал сегодня zip-архив со страницы "Загрузки". Разблокировал, разархивировал на диск C. Прописал в PATH путь к папке onescript\bin.

**Comment by EvilBeaver** [comment]
@svgorbunov Поддержка win-1251 была выпилена не помню уже в какой версии. В обсуждении о выпиле участвовали @dmpas и @nixel2007 

Теперь по дефолту только utf-8.

В принципе, в каталоге установки, в подпапке bin есть конфиг-файл oscript.cfg. В нем можно указать кодировку в параметре #encoding.script=utf-8

Только указать надо windows-1251

**Comment by artbear** [comment]
@EvilBeaver 
Андрей, ты хочешь сказать, что запуск `oscript -encoding=windows-1251 file.os` выполнять бесполезно, т.е. параметр `-encoding` не работает?

**Comment by nixel2007** [comment]
@EvilBeaver 

> Теперь по дефолту только utf-8.

а, вот оно как... я думал, что ты просто сделал utf-8 дефолтной кодировкой без проверки на BOM.

**Comment by nixel2007** [comment]
>  не помню уже в какой версии.

не раньше 12, т.к. до этого в обсуждении я особо не участвовал.

**Comment by EvilBeaver** [comment]
@artbear нет, речь идет о кодировке, в которой записан файл скрипта. А ключ encoding влияет на кодировку, в которой пишется вывод stdout

**Comment by EvilBeaver** [comment]
@nixel2007 

> я думал, что ты просто сделал utf-8 дефолтной кодировкой без проверки на BOM

Ну да. А разве я что-то другое написал?

**Comment by nixel2007** [comment]
@EvilBeaver это все из-за -encoding. я постоянно путаю и считаю, что он отвечает за формат файла, а не за кодировку вывода в stdin.

**Comment by nixel2007** [comment]
@EvilBeaver в таком случае надо поменять документацию [здесь](http://oscript.io/docs/page/install).
указать, что из коробки 1251 не работает, и если надо, то надо править/класть рядом cfg

> А ключ encoding влияет на кодировку, в которой пишется вывод stdout

и вот это **жирненьким** :)

**Comment by artbear** [comment]
@nixel2007 по обоим пунктам мое мнение совпадает.

**Comment by nixel2007** [comment]
может я скажу страшное.
как насчет добавить новый параметр `-file-encoding`?

**Comment by artbear** [comment]
@nixel2007 и совсем все запутать :) ?
хотя я за добавление такого параметра, сам по-другому считал.

**Comment by n-dimens** [comment]
Может быть стоит параметр `-encoding` переименовать в `-output-encoding`? Во избежание дальнейшей путаницы? Для начала :)

**Comment by nixel2007** [comment]
@svgorbunov для вас на данном этапе вариантов решения три:
1) сохранять файл в utf-8
2) поменять конфиг
3) пользоваться другими редакторами (по умолчанию сохраняющие в utf-8), например, Visual Studio Code. Для него как раз есть удобный пакет с поддержкой 1сного языка.

**Comment by nixel2007** [comment]
> Может быть стоит параметр -encoding переименовать в -output-encoding? Во избежание дальнейшей путаницы? Для начала :)

обратная совместимость. =/ breaking change для всех настроенных ci/cd.

**Comment by n-dimens** [comment]
@nixel2007 Спасибо, по обсуждению я понял, в чем текущая проблема :) Ну и соответственно пути решения так же стали ясны. Просто решил уточнить, какие изменения будут допустимы в сложившейся ситуации (если я вдруг соберусь pull-request отправить :) )

**Comment by n-dimens** [comment]
Думаю, если внести уточнение насчет кодировки в документации, issue можно закрыть. Тем паче, раз поддержка только utf-8 сделана осознанно, это уже не баг, а фича :)

**Comment by EvilBeaver** [comment]
Удалил устаревшее упоминание windows-1251 с сайта
