### ISSUE TITLE
Пустая коллекция параметров при запуске через ассоциацию Windows

### ISSUE THREAD

**Issue by ghost** [EvilBeaver/OneScript#254]
немногие знали что файлы os можно ассоциировать напрямую с oscript интерпретатором средствами windows, после этого файлы os становятся такими же как cmd/bat файлы (эксперимент с этим провел @alehinsasha)

собственно в перспективе возможно делать вот такое средствами инсталятора https://msdn.microsoft.com/en-us/library/windows/desktop/cc144156(v=vs.85).aspx, но это другая issue

однако в текущей develop версии наблюдается странное поведение:

``` Gherkin
Функционал: Передача параметров
  Как разработчик скрипта 
  Я хочу передавать аргументы командной строки
  Чтобы делать универсальные инструменты реагирующие на параметры заданые пользователем

@only-windows

Контекст:
  Дано существует файл `example.os` с содержанием   "Сообщить(АргументыКоманднойСтроки[0]);"
  И установлен oscript c доступом через $PATH

Сценарий: Запуск через интерпретатор
   Когда я вызывая команду "oscript example.os parameter"
   Тогда в консоли вывода я получаю "parameter"

@bug-implement

Сценарий: Запуск через интерпретатор
    Допустим расширение "os" ассоциировано с файлом "oscript.exe"
    Когда я вызывая команду "example.os parameter"
    Тогда в консоли вывода я получаю "parameter"
```

Сделал специально в контексте правильного поведения и неправильного - падающий сценарий сделал тегом `bug-implement`

p.s. сценарий был специально разобран на вебинаре Инфостарта

**Comment by EvilBeaver** [comment]
Подозреваю, что это не баг, а фича того, как ОС запускает ассоциированные файлы.

**Comment by ghost** [comment]
@EvilBeaver не соглашусь - bat файл когда запускаешь, он же привязан также к интерпретатору и python ведет себя также как bat файл - если его ассоциируешь, параметры передаются

**Comment by EvilBeaver** [comment]
просто при таком способе ассоциации в реестре прописано для данного расширения скорее всего "путь.exe" %1 - т.е. брать первый параметр только.

@awa делал полноценную регистрацию файлов .os, как исполняемых, код у меня на работе есть,  выложу gist после выходных.

**Comment by ghost** [comment]
@EvilBeaver маленький офтопик - я думаю все таки назрел вопрос о логотипе. придумал бы его что-ли. не хватаете favicon для файлов и ассоциции. или объяви что-ли конкурс на создание логотипа в режиме крайдсорсинга.

Просто файловые ассоциации некрасиво выглядят - получается 

![image](https://cloud.githubusercontent.com/assets/55323/15450067/b66b3b48-1f99-11e6-8781-ee40ff193ba9.png)

**Comment by EvilBeaver** [comment]
@allustin вот гист от @awa, который должен делать кошерное ассоциирование, не приводящее к теме данной issue

https://gist.github.com/EvilBeaver/82c9aa10ddcfde575a7ba13f0d8979f2

**Comment by ghost** [comment]
@EvilBeaver тогда может перенести в состав движка ? А эту задачу закрыть ?

**Comment by EvilBeaver** [comment]
Перенести в состав движка что?
