### ISSUE TITLE
Передача парамеров в конструкторы классов

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#256]
Возможность передавать параметры в некую предопределенную процедуру создания экземпляра класса.

Со стороны пользователя библиотеки это будет выглядеть как-то так:

``` bsl
Конфигуратор = Новый УправлениеКонфигуратором(СтрокаСоединения);
```

v8runner выбран в демонстрационных целях :)

**Comment by artbear** [comment]
Давно пора.
А на деструкторы я Андрея давно уговариваю :)

**Comment by EvilBeaver** [comment]
Это называется magic methods в других языках. Но в 1С этого нет

**Comment by artbear** [comment]
А `Новый УправлениеКонфигуратором`, значит, есть? :)

**Comment by JohnyDeath** [comment]
@EvilBeaver а почему ты не хочешь добавить конструкторов и деструкторов? Я пропустил как-то этот момент

**Comment by EvilBeaver** [comment]
Добавить-то можно, но зачем? Передача параметров в объект при создании? Ну да, но без этого жить можно же, не? Зато не вносим несовместимые конструкции в язык

**Comment by artbear** [comment]
@EvilBeaver без конструктора еще можно обойтись инициилизирующим постконструктором, а вот деструктор бы очень пригодился для освобождения объектов (RAII)

**Comment by nixel2007** [comment]
> без конструктора еще можно обойтись инициилизирующим постконструктором

собственно, чтобы вот этого всего не было)

**Comment by JohnyDeath** [comment]
@EvilBeaver 

> Зато не вносим несовместимые конструкции в язык

А какие-такие несовместимые конструкции мы этим внесем? Это ж просто экспортный метод

**Comment by nixel2007** [comment]
@JohnyDeath думаю, Андрей имел ввиду что-то глобальное типа Конструктор()... КонецКонструктора.

**Comment by nixel2007** [comment]
Это конечно более правильно... Но в наших реалиях есть смысл просто застолбить имена процедур

**Comment by JohnyDeath** [comment]
нее, какой нафиг "КонецКонструктора".
Все придумано до нас в 1С++

**Comment by artbear** [comment]
Конечно, мы это давно проходили.

**Comment by JohnyDeath** [comment]
Вот: http://www.1cpp.ru/docum/html/classes.html

Еще оттуда можно взять: 

```
ПриПолучении_ИмяАтрибута и ПриЗаписи_ИмяАтрибута
```

**Comment by EvilBeaver** [comment]
Я в самом начале написал - это называется волшебные методы. Они возможны, никто не спорит. Мне кажется просто, что они нам не шибко нужны.

Про RAII я в курсе, даже задача есть. Но там все сложно. @artbear, ты же в курсе, что деструкторы!=RAII

**Comment by JohnyDeath** [comment]
Ну как это "не нужны". Конструкторы с заданными параметрами выглядят куда краше, чем начальная инициализация объекта в несколько строк.
Конечно, это не горит, но поиметь такое очень хотелось бы

**Comment by alexkmbk** [comment]
Приведу usecase: Объект ПараметрыЗаписиJSON может быть заполнен только через конструктор, у него все свойства только для чтения.
То есть без этого функционала, полнофункциональную реализацию объекта ЗаписьJson сделать просто не возможно.
О чем вообще думали разработчики, придумывая этот объект...

**Comment by dmpas** [comment]
@alexkmbk разработчики нюхнули функционального программирования. Неизменяемые объекты - там эта концепция одна из основополагающих.

**Comment by EvilBeaver** [comment]
@alexkmbk уточни, пожалуйста, как твой комментарий относится к теме данного issue? ПараметрыЗаписиJSON это же системный объект, а не скриптовый.

**Comment by alexkmbk** [comment]
@EvilBeaver Значит я не так понял. Просто у меня сейчас возникли непонятные ошибки с передачей параметров в конструктор и увидев этот issue я подумал что поддержки нет в самом движке.

**Comment by nixel2007** [comment]
Нет поддержки передачи параметров в конструктор класса, объявляемого библиотекой или через ЗагрузитьСценарий. Парометры в системных конструкторах конечно же есть.
