### ISSUE TITLE
v8unpack - добавить в дистрибутив

### ISSUE THREAD

**Issue by ghost** [EvilBeaver/OneScript#258]
Добавлю по итогам обсуждения gitter и вебинаров

Очень хочется, чтобы
- дистрибутив onescript содержал v8unpack.exe
- поддерживал установку v8unpack в rfnfkju %OSCRIPT_BIN%

обоснование простое:
- сейчас бинарный файл  v8unpack лежит в GIT репозитории и вынуждено копируется во все библиотеки с ним связанные
- за основу лучше всего взять бинарный файл @dmpas 

P.S. Это просто предложение, сейчас мы выкручиваемся вручную - копируем v8unpack в bin всегда при установке с помощью `chocko` и `curl`

**Comment by dmpas** [comment]
Плохая затея, как мне кажется. Во-первых, смешиваем разные инструменты. Во-вторых, появляется дополнительная зависимость от платформы.

По-моему, лучше как-нибудь придумать, чтобы качать v8unpack через opm.

**Comment by dmpas** [comment]
ещё как вариант, портировать v8unpack во внешнюю компоненту для односкрипта. Обретём платформонезависимость и работу с распаковщиком средствами языка.

**Comment by nixel2007** [comment]
> По-моему, лучше как-нибудь придумать, чтобы качать v8unpack через opm.

отличная идея.

**Comment by artbear** [comment]
> Плохая затея, как мне кажется. Во-первых, смешиваем разные инструменты. Во-вторых, появляется дополнительная зависимость от платформы.
> 
> По-моему, лучше как-нибудь придумать, чтобы качать v8unpack через opm.

Поддерживаю по обоим пунктам (выше также проголосовал)

**Comment by artbear** [comment]
По этим же причинам я против копирования `v8unpack` внутри файла `interactive-install.os` в PR https://github.com/xDrivenDevelopment/precommit1c/pull/87

**Comment by ghost** [comment]
@dmpas 

> Это просто предложение,

на самом деле это НЕ архрешение, а "просто боль" - но уже понятно что так дальше уже нельзя. Выглядит странно сейчас эти манипуляции с update and install

@artbear с пул реквестом вы ребят конечно повеслелись знатно - я его на вебинаре показал. Этот пул-реквест очень показателен - как нельзя работать с пулреквестами.

**Comment by ghost** [comment]
Проголосовал за opm

**Comment by EvilBeaver** [comment]
А мне расскажите - какой-такой пулреквест?

По теме - не надо смешивать дистрибутив движка и технические сложности прекоммита. Хотели же сделать пакет прекоммита, чтобы сам ставился.

**Comment by artbear** [comment]
@EvilBeaver я выше линк на pr дал

ОФФ/2
@allustin 

> @artbear с пул реквестом вы ребят конечно повеслелись знатно - я его на вебинаре показал. Этот пул-реквест очень показателен - как нельзя работать с пулреквестами.

я с разными PR в разных проектах работал, опыт имею, как ты знаешь. ИМХО от автора не требовалось слишком многого, фактически был проделан этап код-ревью и выдвинуты некоторые нежесткие предложения (кроме, конечно, копирования v8unpack в bin).
Ничего сложного :)

Если в свою очередь, посмотреть на требования к PR в ВБ, ИМХО вот там как раз есть серьезные требования :) например, обязательное наличие фичи

**Comment by EvilBeaver** [comment]
@dmpas давно портировать unpack в компоненту хочу. Тем более, что код-то уже есть в моем V8Viewer

**Comment by EvilBeaver** [comment]
Сомнительная штука, нужно понимать конкретный сценарий. в VB, например, от копирования в PATH уже избавились меньшей кровью и архитектурно правильно.
