### ISSUE TITLE
Портировать методы работы с JSON из 1С

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#259]
В 1С появились родные методы работы с JSON, значит можно их реализовать.

**Comment by Inkasor** [comment]
Они целиком основаны на этом решении 
https://github.com/open-source-parsers/jsoncpp
может быть имеет смысл его сразу интегрировать в OneScript?

**Comment by artbear** [comment]
@Inkasor откуда информация?

**Comment by pumbaEO** [comment]
c:\Program Files (x86)\1cv8\8.3.8.1652\licenses\3rd_party\
там список .

2016-06-01 11:00 GMT+03:00 Artur Ayukhanov notifications@github.com:

> @Inkasor https://github.com/Inkasor откуда информация?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/EvilBeaver/OneScript/issues/259#issuecomment-222920635,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAKIc_wqPRBp-3kKRxugYjpjjaB5pIhNks5qHTwWgaJpZM4InjeU
> .

## 

З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by EvilBeaver** [comment]
Залинковать методы управляемого кода на неуправляемую dll, конечно, можно. Но хотелось бы полностью .NET-овское решение.

**Comment by Inkasor** [comment]
Идейно самописное или классику вроде https://github.com/JamesNK/Newtonsoft.Json ?

**Comment by dmpas** [comment]
@Inkasor идейно совместимое по лицензии :smiley: в первую очередь

**Comment by EvilBeaver** [comment]
@Inkasor да, я именно в сторону Ньютона думал.
@dmpas там MIT, она совместимая с нашей, насколько я знаю.

**Comment by dmpas** [comment]
а средствами языка переделать существующий уже JSON под новый API получится?

**Comment by EvilBeaver** [comment]
@dmpas получится. Только CLR с его JITработает же быстрее, чем односкрипт

**Comment by dmpas** [comment]
@EvilBeaver с этим не поспоришь, конечно, но это плохая логика. в долгосрочной перспективе полезнее всё же наращивать кодовую базу на самом односкрипте и пилить движок в сторону ускорения.

**Comment by EvilBeaver** [comment]
@dmpas тут палка о двух концах. 1С-ник будет ожидать "платформенные" API не в виде библиотек, а сразу из коробки. Ну и производительность опять же.

**Comment by dmpas** [comment]
@EvilBeaver и с этим не поспоришь. но принцип опенсурса "помоги себе сам" выливается в то, что для того, чтобы поправить багу надо знать уже ДВА языка вместо одного привычного. и движок выпускается реже, чем библиотеки.

**Comment by EvilBeaver** [comment]
>  и движок выпускается реже, чем библиотеки.

А вот здесь, думаю надо что-то менять. Например, назначить вешки, в которые будет выходить релиз. Каждые 2 месяца, например. И каждые 4 - LTS :)

**Comment by alexkmbk** [comment]
Делаю Чтение JSON на фреймворке Newtonsoft, так что скоро планирую выложить пуллреквест.
Про запись пока не знаю, возьмусь или нет, так что если есть желающие - берите запись.

**Comment by EvilBeaver** [comment]
Спасибо! А что мешает взять еще и запись вторым этапом?

**Comment by alexkmbk** [comment]
Занятость

**Comment by EvilBeaver** [comment]
Проклятая штука )

**Comment by alexkmbk** [comment]
@EvilBeaver 
"...Но то не лень, а занятость, она
В который раз тиранит нас, тиранит нас." (Чайф)

Приложу сюда ссылку на пулреквест по объекту ЧтениеJSON - #360

**Comment by dmpas** [comment]
Это ж запилили: и чтение, и запись. Да?

**Comment by artbear** [comment]
Ага, меня также интересует, можно ли юзать в качестве полной замены пакета json ?

**Comment by EvilBeaver** [comment]
Насколько я знаю, полной замены пакету json нет, есть только потоковое чтение. А чтения сразу в структуру или соответствие так и нет. Хотя можно закрыть и оформить другую задачу, про сериализацию объектов.

**Comment by alexkmbk** [comment]
@artbear @dmpas  Ну эта задача изначально не предполагала реализацию замены пакета json, задача была обеспечить совместимость с функционалом платформы, что и было сделано и для чтения и для записи (с некоторыми оговорками). А совместимость с пакетом json это другая задача.
