### ISSUE TITLE
Сделать RPM-пакет

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#260]
Наверное, для площадки выберем CentOS?

Призыв Всадников-Линуксоидов:
@pumbaEO @allustin @dmpas @nixel2007

**Comment by nixel2007** [comment]
@EvilBeaver в rpm никогда не работал, все мои познания линукса ограничивались дебианом и убунтой :(

**Comment by pumbaEO** [comment]
На меня ставь.

**Comment by pumbaEO** [comment]
Т.е. делаем скрипт, который поднимет docker контейнер с centos и из *.zip с библиотекой создаст oscript.rpm?

**Comment by dmpas** [comment]
@pumbaEO сейчас deb строится так:
- получает на вход каталог с бинарниками, упаковывает их
- упаковывает поставку с библиотеками oscript-library
- и 4 вспомогательных скрипта для `/usr/bin/`

**Comment by dmpas** [comment]
А, ещё запускает oscript.exe, чтобы версию оттуда получить

**Comment by EvilBeaver** [comment]
Получалка версии из oscript. Папка $DISTPATH - место куда распакован ZIP-дистрибутив

```
DISTPATH=$(pwd)/osbin
BINPATH=$DISTPATH/bin

if [ -z "$TMP" ] ; then
    TMP=/tmp
fi
echo "Binaries path: $BINPATH"
echo "Dist path: $DISTPATH"

VERSIONFILE=$BINPATH/VERSION
if [ -f "$VERSIONFILE" ] ; then
    rm $VERSIONFILE
fi

mono ${BINPATH}/oscript.exe | head -1 | \
        grep -oE '([[:digit:]]+\.){2}[[:digit:]]+' \
        > ${BINPATH}/VERSION

if [ ! -f "$VERSIONFILE" ] ; then
    echo "No version file created"
    exit 1
fi

mkdir -p $DISTPATH/deb
cp -r ${PWD}/install/builders/deb/* $DISTPATH/deb
docker build -t onescript:deb ${PWD}/install/builders/deb/
docker run --rm -v ${DISTPATH}:/media onescript:deb
```

**Comment by dmpas** [comment]
@EvilBeaver ты не деббилдом пользуешься?

**Comment by EvilBeaver** [comment]
Я пользуюсь твоим докерфайлом же, забыл?

**Comment by EvilBeaver** [comment]
@pumbaEO, в репо, в папке install/builders/deb лежат скрипты и докерфайл сборки деб. Приведенный выше скрипт, это то, что в шаге билдсервера записано.

**Comment by dmpas** [comment]
@EvilBeaver так деббилд почти то же самое делает, что твой скрипт :) вот мне и интересно стало, в чём разница и почему она не закоммичена :smile:

**Comment by EvilBeaver** [comment]
Блин, до меня дошло, что за деббилд ))) Да, это он и есть, просто когда я делал сборку на сервере, он еще не принимал параметр с путём на вход. Теперь вроде как принимает, верно?

**Comment by dmpas** [comment]
ага, принимает первым параметром.

**Comment by pumbaEO** [comment]
Просьба дополнительно публиковать на сайте src.rpm и пикеты исходные для сборки debian пакетов (origin, dsc) и т.д. для возможности публикации в репозитариях https://build.opensuse.org/package/show/home:pumbaEO/onescript-engine

**Comment by EvilBeaver** [comment]
Спасибо, Женя! :)
