### ISSUE TITLE
Добавить метод ТекущаяУниверсальнаяДатаВМиллисекундах()

### ISSUE THREAD

**Issue by Pr-Mex** [EvilBeaver/OneScript#262]
Как разработчик 
Я хочу, чтобы в oscript был метод ТекущаяУниверсальнаяДатаВМиллисекундах()
Чтобы я мог делать точный замер производительности работы скрипта

**Comment by EvilBeaver** [comment]
Для этого запускай oscript с ключом -measure

**Comment by Areso** [comment]
А если нужно измерить производительность отдельных этапов скрипта, разбивать его на подскрипты? Тоже часто пользуюсь этим функционалом, голосую за.

**Comment by artbear** [comment]
+1

**Comment by dmpas** [comment]
https://github.com/dmpas/OneScript/commit/ab91d4372baba31ecc225bc08992d3ecb071d7c0

Кто подскажет подходящий тест???
