### ISSUE TITLE
В zip дистрибутиве неверная кодировка русских файлов

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#263]
Никогда такого не было и вот опять...

ZIP-дистрибутив, создаваемый сервером сборок содержит некорректные русские имена файлов.

**Comment by pumbaEO** [comment]
Teamcity?
31 мая 2016 г. 20:10 пользователь "Andrei Ovsiankin" <
notifications@github.com> написал:

**Comment by EvilBeaver** [comment]
да. Причем, раньше работало прекрасно
