### ISSUE TITLE
Реализация API работы с двоичными данными

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#264]

**Comment by artbear** [comment]
Еще одна плюшка в сторону сабжа https://gitter.im/EvilBeaver/oscript-library?at=57bc419b87f779f0691e867a

Valeriy Ageev @awa15 15:29
Хотите извращений? Их есть у меня! https://yadi.sk/d/sbJBjFvFuRKLw
Это распаковщик, аналог половины v8unpack, только написан полностью на 1С. Работает только на 8.3.9, естественно.
Осторожно! Не запускайте распаковку больших файлов! Файл cf размером 40 мегабайт распаковывался 2 часа 13 минут (но распаковался!).
Написан данный распаковщик, чтобы посмотреть, можно ли реально работать с двоичными данными в 1С. Ответ - уже можно! В данной обработке на 1С написан inflate (deflate не реализован). Несмотря на очень медленную работу это все же работает! А deflate/inflate - это не просто работа с байтами, это работа с битами, под что 1С пока не заточена вообще никак.
Если же распаковать тот же файл cf размером 40 мегабайт без inflate (примерный аналог - это v8unpack.exe с ключем -u) то распаковка проходит всего за 12 секунд!
Я это всё к тому, что если реализовать в oscript классы работы с двоичными данными, появившимися в 8.3.9 и добавить от себя еше две функции (deflate и inflate), то вполне можно написать полностью на односкрипте аналог v8unpack, tool_1cd и ещё что угодно, при этом работать это всё будет не очень сильно медленней, зато уйдут многие проблемы совместимости линуксов и прочих ос. @EvilBeaver , пора! )))

**Comment by nixel2007** [comment]
я подниму внимание к цитате @awa15
@EvilBeaver @artbear @pumbaEO @Infactum

**Comment by awa15** [comment]
@nixel2007 
Именно это извращение я и попытался запустить на новой версии оскрипт. Однако сразу уперся в нереализованность ЧтениеДанных. @EvilBeaver зачем закрыл задачу? Ведь до конца она не выполнена?

**Comment by nixel2007** [comment]
@awa15 вроде бы @EvilBeaver говорил, что реализация ЧтениеДанных почти полностью свопадает с БуферДвоичныхДанных. по крайней мере я так понял. это не так?

**Comment by EvilBeaver** [comment]
Я закрыл задачу, а доработку оформлю другой более конкретной задачей

**Comment by Infactum** [comment]
Если все так любят переписывать v8unpack, то что мешало его в виде плагина к oscript оформить? Уж на C# все бы явно быстро работало, и никаких проблем с кроссплатформенностью.
Если очень хочется именно с использованием механизмов работы с ДД все сделать, то логично было бы в качестве плагина хотя бы работу с gzip добавить, т.к. очевидно это самая медленная часть.

**Comment by dmpas** [comment]
> что мешало его в виде плагина к oscript оформить? 

@Infactum да ничего не мешало, просто выбор стоял - его переписывать или двоичные данные в движок запилить. Второе победило, ибо более широкий круг задач покрывает.
