### ISSUE TITLE
COMОбъект MSSQL

### ISSUE THREAD

**Issue by mickey1cx** [EvilBeaver/OneScript#266]
Не создается бэкап при выполнении команды "BACKUP DATABASE ..." из скрипта. Аналогичный код из 1С выполняется корректно.

При начале выполнения скрипта файл бэкапа появляется, но потом удаляется. В журнале SQL следующие ошибки:

Ошибка: 3041, серьезность: 16, состояние: 1.
# 

Запрошенный доступ к реестру запрещен. (Security)

---

Расположение программы:

   в Microsoft.SqlServer.Management.SqlManagerUI.LogSourceWindowsNT.Microsoft.SqlServer.Management.SqlManagerUI.ILogSource.Initialize()
   в Microsoft.SqlServer.Management.SqlManagerUI.LogSourceAggregation.Microsoft.SqlServer.Management.SqlManagerUI.ILogSource.Initialize()
# 

Запрошенный доступ к реестру запрещен. (mscorlib)

---

Расположение программы:

   в System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   в Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   в System.Diagnostics.EventLog.Exists(String logName, String machineName)
   в System.Diagnostics.EventLogInternal.OpenForRead(String currentMachineName)
   в System.Diagnostics.EventLogInternal.get_EntryCount()
   в Microsoft.SqlServer.Management.SqlManagerUI.LogSourceTypeWindowsNT.Init(String machineName)

**Comment by artbear** [comment]
Код скрипта приведи

**Comment by mickey1cx** [comment]
Функция ПодключитьSQL()

```
Перем Command;

СтрокаПодключения = 
"Provider=SQLOLEDB.1;
|User ID=sa;
|Pwd=secured_pass;
|Data Source=server_sql;";

Попытка

    Connection  =   Новый COMОбъект("ADODB.Connection");
    Command  =      Новый COMОбъект("ADODB.Command");
    Connection.Open(СокрЛП(СтрокаПодключения));
    Command.ActiveConnection   = Connection;

Исключение
    Сообщить(ОписаниеОшибки());
КонецПопытки; 

Возврат Command;
```

КонецФункции    

Процедура СоздатьБэкап(COM_SQL)

```
ТекстЗапроса = 
"BACKUP DATABASE [test_base] TO  
|DISK = N'F:\SQL_Backup\test_base.bak' WITH NOFORMAT, 
|NOINIT,  NAME = N'test_base_full', SKIP, NOREWIND, NOUNLOAD,  STATS = 10";

COM_SQL.CommandText = ТекстЗапроса;
COM_SQL.Execute();
```

КонецПроцедуры

COM_SQL = ПодключитьSQL();  
Если COM_SQL = Неопределено Тогда
    ВызватьИсключение "!";
КонецЕсли;

СоздатьБэкап(COM_SQL);

COM_SQL = Неопределено;

**Comment by EvilBeaver** [comment]
@mickey1cx на какой конкретно строке падает? Какая авторизация на SQL прописана в источнике данных **server_sql**?

**Comment by EvilBeaver** [comment]
@mickey1cx у меня не воспроизвелось. Бэкап создался. Но я подключался напрямую к серверу по имени машины, а не через источники данных ODBC DNS.

Тут что-то с выдачей удостоверений. Без воспроизведения ошибки у себя, я не смогу помочь.

**Comment by EvilBeaver** [comment]
И в качестве еще одной идеи - попробуйте поменять Provider на MSDASQL

**Comment by mickey1cx** [comment]
Ок, победил, всем спасибо. Помогло следующее, вместо provider указал одну из строк:
DRIVER={SQL Server};
DRIVER={SQL Server Native Client 11.0};
DRIVER={ODBC Driver 11 for SQL Server};
