### ISSUE TITLE
Проблема - Не удается удалить каталог, если он является текущим

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#272]
Нарвался на интересный баг работы со временными файлами через библиотеку `ВременныеФайлы` - часто не удается удалить файлы/каталоги при завершении работы различных скриптов. Например, недавно мы с этим столкнулись в precommit1c, также в паре моих проектов есть эти же проблемы.

Начал копать и увидел проблему - Не удается удалить каталог, если он является текущим

Следующий тест падает с ошибкой

```
Процедура ТестДолжен_ПроверитьУдалениеВременногоКаталогаЕслиОнУстановленКакТекущий() Экспорт

    ПутьВременногоКаталога = ПолучитьИмяВременногоФайла("");
    СоздатьКаталог(ПутьВременногоКаталога);
    УстановитьТекущийКаталог(ПутьВременногоКаталога);
    УдалитьФайлы(ПутьВременногоКаталога);
КонецПроцедуры
```

текст ошибки:

```
{Модуль C:\projects\tempfiles-test.os / Ошибка в строке: 32 / Внешнее исключение: 
Процесс не может получить доступ к файлу "C:\Users\user\AppData\Local\Temp\2zqhhip5.330",
так как этот файл используется другим процессом.}
        УдалитьФайлы(ПутьВременногоКаталога);
```

Считаем это багом или это будем считать это нормальным поведением?

Есть 2 сценария
1. удаление временных файлов при завершении работы скрипта
2. удаление временных файлов внутри скрипта, без его завершения

для сценария 1 ИМХО не важно, какой каталог является текущим, и файлы должны удаляться безусловно, т.е. ошибки быть не должно.

для сценария 2 текущий каталог важен и нельзя просто так его удалять.

Проблема будет встречаться при завершении разных скриптов и в будущем.
Нам нужно выбрать единый вариант.

Предложения:
- 1) считаем это не багом. 
  - Решение: Документируем в спец.документ "Известные проблемы" и отсылаем всех туда.
- 2) считаем это багом только при завершении работы. 
  - Решение: И что-то с этим делаем. Например, опять говорим о деструкторах для RAII :) или добавляем некую параметризацию для пакета `ВременныеФайлы`

Товарищи, предлагаю обсудить и договориться.

PS проблема специфична для 1script, т.к. в 1С нет метода `УстановитьТекущийКаталог`

**Comment by EvilBeaver** [comment]
Артур, ты прикалываешься? Текущий каталог занимается любым приложением и его никогда нельзя удалить. Создай папку, зайди в нее через cmd, а потом попробуй в проводнике удалить

**Comment by artbear** [comment]
@EvilBeaver в твоем сценарии это разные приложения.
А я говорю об одном приложении, которое к тому же завершает свою работу. для этого случая хочется безусловного удаления, т.е. безусловного выполнения того самого деструктора

**Comment by ghost** [comment]
@artbear это нормально поведение - это уровень операционной системы

> Your shell process has that directory as its current directory, which keeps its inodes on disk allocated in much the same way as an open file keeps its inodes allocated after unlinking, until all processes holding an open handle to that file close them.

В linux это даже описано в самой операционной системе - таково реализованное поведение операционных систем. В Windows cсобственно тоже.

Может проще переходить в главный контекст временных файлов операционной системы и подчищать за собой

```
Процедура ТестДолжен_ПроверитьУдалениеВременногоКаталогаСПереходомВКонтекстКаталогаВременныхФайловОперационнойСистемы() Экспорт

    ПутьВременногоКаталога = ПолучитьИмяВременногоФайла("");
    СоздатьКаталог(ПутьВременногоКаталога);

    УстановитьТекущийКаталог(КаталогВременныхФайлов());
    УдалитьФайлы(ПутьВременногоКаталога);
КонецПроцедуры
```

P.S. Если разработчик скрипта / обработки 1С создал временный файл / каталог - пусть сам за собой и чистит. А вот если временные дескрипторы создает платформа или скриптовый движок - то уже разработчик платформы или скриптового движка обязан за собой чистить. В данном сценарии - вопрос к автору библиотеки: вроде уже было много раз реализован метод

```
Перем мВременныеДекскрипторы;

Функция ПолучитьИмяВременногоДескриптораСОчисткойПриОкончанииРаботыСкрипта(_Расширение)

    _имяДескриптора = ПолучитьИмяВременногоФайла(_Расширение);

    мВременныеДекскрипторы.Вставить(_имяДескриптора);

    Возврат _имяДескриптора;

КонецФункции

Процедура ОчиститьВременныеДескрипторы()
     УстановитьТекущийКаталог(КаталогВременныхФайлов);
     Для каждого _временныйДескриптор из мВременныеДекскрипторы  Цикл
           УдалитьФайлы(_временныйДескриптор); 
     КонецЦикла
КонецПроцедуры

мВременныеДекскрипторы = Новый Массив();

_дескриптор = ПолучитьИмяВременногоДескриптораСОчисткойПриОкончанииРаботыСкрипта("")

СоздатьКаталог(_дескриптор);

ОчиститьВременныеДескрипторы();

```

**Comment by artbear** [comment]
@allustin @EvilBeaver я в целом согласен с вами обоими, хотел бы договориться о едином подходе, о чем я и писал выше.

Тогда остается только задокументировать подобную проблему в "Известные проблемы при разработке скриптов" и закрыть issue.

**Comment by artbear** [comment]
@allustin да, именно подобный код я и предлагаю поместить в решение проблемы в разделе `Известные проблемы при разработке скриптов`

Или как вариант - в пакет `ВременныеФайлы` добавить метод `УдалитьПриЗавершенииСкрипта` для упрощения работы скриптописателей.

Что скажете?

@allustin ну и в твоем коде небольшая ошибка :) - `КаталогВременныхФайлов` в одном месте без скобочек

**Comment by ghost** [comment]
Включать это в раздел "известные проблемы" я бы не стал - это не проблема, а просто банальное знание о временных файлах.  Это больше рекомендация по правильному кодированию, в том числе и в 1С. Создал временный файл - будь добр почисти за собой. А в библиотеке временные файлы создать и использовать безопасный метод получения временных файлов. 

Таково моё мнение:
- oscript тут не причем. 
- 1С-никам в том числе и на oscript нужно читать ИТС и учить матчасть

Что действительно бы пригодилось так это деструктор - но эта задачу уже есть по моему.

**Comment by EvilBeaver** [comment]
> - oscript тут не причем.
> - 1С-никам в том числе и на oscript нужно читать ИТС и учить матчасть

Абсолютно в точку. Это не баг, это штатное поведение ОС. Делать к нему обходы или считать "проблемой" - как-то странно.

**Comment by artbear** [comment]
Пишу как человек, который много соли съел на разработке и поддержке продуктов.
Опыт - если один разработчик нарвался на проблему, то и другие попадут.

Задумайтесь о разработчиках, пользователях продукта.
ИМХО подобное поведение не такая уж редкость.
Сообщения, которые сейчас выдает система, не совсем понятны и могут путать пользователя.

Как разработчику определить, кто виноват в этом сообщении? его скрипт или какая-то другая программа, которую он вызвал?

Если мы дадим ему хотя спец.метод (например, ВременныеФайлы.УдалитьПриЗавершенииРаботыСкрипта) + задокументируем где-нибудь это поведение и эту проблему, всем будет проще в будущем.

ИМХО объясняю азы поддержки пользователей :)

**Comment by EvilBeaver** [comment]
@artbear убей не понимаю, при чем тут временные файлы. Код пытается удалить занятый каталог. Это не даст сделать операционная система. Если код занял каталог, он обязан его освободить.

Любая точка входа в приложение всегда оборачивается в Попытку, где идет обработка, так называемого last chance. Именно там чистятся все ресурсы в безусловном виде. Со счетчиком ссылок и автоочисткой не канает, их реализовать проблемно сейчас. А с тем что имеем - подход такой, как я описал.
