### ISSUE TITLE
Класс "Файл" не возвращает путь, если объект-файл был инициализирован без полного пути к файлу

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#273]
Еще один баг в копилку :)
ИМХО это уже нужно срочно исправлять.

Тест падает:

```
Процедура ТестДолжен_ПроверитьАтрибутПутьУФайлаВТекущемКаталоге() Экспорт

    ИмяФайла = "file1.txt";
    Файл = Новый Файл(ИмяФайла);
    Ожидаем.Что(Файл.ПолноеИмя, "Файл.ПолноеИмя").Равно(ОбъединитьПути(ТекущийКаталог(), ИмяФайла));
    Ожидаем.Что(Файл.Путь, "Файл.Путь").Равно(ТекущийКаталог()); // здесь и падает

КонецПроцедуры
```

Ошибка:

```
Ожидали, что проверяемое значение () РАВНО (C:\projects).
Файл.Путь}
```

Т.е. видно, что Файл.ПолноеИмя работает правильно и использует текущий каталог.

А вот Файл.Путь работает неверно

@EvilBeaver сможешь побыстрее поправить?

**Comment by artbear** [comment]
@EvilBeaver Сделал исследование тебе в помощь :)
Посмотрел код 1скрипт
https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/FileContext.cs#L83

Почитал [msdn Path.GetDirectoryName](https://msdn.microsoft.com/ru-ru/library/system.io.path.getdirectoryname%28v=vs.110%29.aspx)

```
Path.GetDirectoryName - метод (String)

.NET Framework (current version) Другие версии 

Возвращает для указанной строки пути сведения о каталоге.
Пространство имен:   System.IO
Сборка:  mscorlib (в mscorlib.dll)

Синтаксис
C#C++F#VB
public static string GetDirectoryName(
    string path
)
Параметры
path
Путь к файлу или каталогу.
Возвращаемое значение
Type: System.String
Сведения о каталоге для path, или значение null, если путь path указывает на корневой каталог или равен NULL.
Возвращает String.Empty, если параметр path не содержит сведения о каталоге.
```

ИМХО проблема в последней строке `Возвращает String.Empty, если параметр path не содержит сведения о каталоге.`
Это как раз наш случай :( т.е. как раз и возвращается пустая строка!

Сможешь поправить?

**Comment by artbear** [comment]
А после изучения строки `Возвращаемое значение: значение null, если путь path указывает на корневой каталог`
родился еще один тест, подтверждающий соседний баг :)

```
Процедура ТестДолжен_ПроверитьАтрибутПутьУФайлаВКорневомКаталоге() Экспорт

    ИмяФайла = "C:\";
    Файл = Новый Файл(ИмяФайла);
    Ожидаем.Что(Файл.ПолноеИмя, "Файл.ПолноеИмя").Равно("C:\");
    Ожидаем.Что(Файл.Путь, "Файл.Путь").Равно("C:\");
КонецПроцедуры
```

Текст ошибки:

```
Внешнее исключение: Ссылка на объект не указывает на экземпляр объекта.}
        Ожидаем.Что(Файл.Путь, "Файл.Путь").Равно("C:\");
```

как раз `null` и получили

PS вот до чего жизнь холостяка доводит :) - одни баги сегодня прут. 
Семья у меня в Сочи, а не то, что вы подумали :)

**Comment by artbear** [comment]
Проверил поведение 1С

```
file1.txt
Файл.ПолноеИмя file1.txt
Файл.Путь 

C:\
Файл.ПолноеИмя C:\
Файл.Путь C:\
```

Видно, что первый баг есть и у 1С. Но 1С проще, в коде 1С мы фактически с текущим каталогом не работаем. А вот для скриптов 1скрипт это важно.

А вот второго бага у 1С нету.

@EvilBeaver когда сможешь поправить?

**Comment by EvilBeaver** [comment]
Артур, тут многабуков. Давай "баг, который есть и у 1С" все-таки багом не считать. Это не баг, а "поведение, которое @artbear считает неверным". Тут реальные баги, если есть, их надо поправить.

**Comment by artbear** [comment]
@EvilBeaver я скриптингом давно занимаюсь, поэтому и пишу.

Для разработчика скрипта не должно быть разницы в использовании объекта Файл, если используем относительный или абсолютный путь.

Сейчас есть серьезные различия в поведении при передаче указанных путей.

Представь, во что превратится написание скриптов, если обычный и привычный класс `Файл` будет работать по разному для случая `скрипт относительный-путь` и `скрипт абсолютный-путь` ??
я уже _наслаждаюсь_ 3-й день :(

уже приходится вставлять дебильный (по-другому не могу сказать) код

```
// TODO обход бага https://github.com/EvilBeaver/OneScript/issues/273
Функция ПолучитьФайлПоПути(Знач Путь)
    РезФайл = Новый Файл(Путь);
    Если Не ЗначениеЗаполнено(РезФайл.Путь) Тогда 
        РезФайл = Новый Файл(ОбъединитьПути(ТекущийКаталог(), Путь));
    КонецЕсли;
    Возврат РезФайл;
КоецФункции // ПолучитьФайлПоПути()
```

вместо простого `Файл = Новый Файл(Путь);`

И так придется делать в каждом скрипте, который использует пути - а это просто ВСЕ скрипты, который есть и будут !!

Извращение полное.

PS Андрей, сам подумай о поведении, оно не должно отличаться!

Причем исправление-то несложно сделать :)

**Comment by artbear** [comment]
@EvilBeaver Ты немного различай поведение 1С и 1скрипта.
У 1С нет понятия "текущий каталог", в скриптинге и у нас есть.
Поэтому 1С все равно не может работать с относительным путями, а скриптинг обязан с ними работать, это азы скриптинга.

Значит, и наш движок должен уметь работать с относительными путями.
и поведение движка не должно отличаться для относительных и абсолютных путей.

@EvilBeaver если ты еще не согласен, я уже и не знаю, нафига тогда скриптовый движок, который нарушает правила скриптинга :(

**Comment by artbear** [comment]
И насчет "тут многабуков" - я старался облегчить тебе/контрибьюторам исправление, чтобы все было очевидно и не пришлось тратить время на доп.исследования.

**Comment by EvilBeaver** [comment]
Мое мнение такое, что 1С-ник вправе ожидать от кода такое же поведение, как в 1С. У нас уже есть отличия и они уже сейчас порождают проблемы и вопросы пользователей. Я против того, чтобы вводить еще одно отличие. Предлагаю начать с основ - сценарии применения. Какую задачу ты решал, наткнувшись на такое поведение? Может, мы сможем решить эту задачу иными средствами, не прибегая к введению отличий от 1С?

**Comment by artbear** [comment]
1С не умеет работать с относительными путями, т.к. у 1С нет понятия "текущий каталог".

У скриптинга же текущий каталог и относительные пути - это одно из ключевых понятий.
Отсюда и все различия в поведении. В данном случае мы от этого не денемся.

И 1скрипт, как **скриптовый** язык, должен уметь работать как с текущим каталогом, так и с относительными путями.

Одно из правил скриптинга - скрипты должны уметь работать с относительными путями.
Если этого нет, для пользователя скриптов это жутко неудобно, приходится задавать длинные пути, строки вызова растут и т.п.
Сильно неудобно и неправильно.

Мы не вводим различие с 1С, оно уже по определению есть :) и нужно сделать так, чтобы это различие не приводило к багам.

Что плохого в том, что Файл.Путь будет **всегда** возвращать правильный путь ?
А не как сейчас, иногда :) ?

**Comment by EvilBeaver** [comment]
Ничего плохого, кроме того, что отличаться от 1С будет. Я твои доводы понимаю и с ними не спорю. Надо думать.

**Comment by artbear** [comment]
@EvilBeaver Андрей, если уж говорить о разнице с 1С, сразу вспомни о библиотеках, Использовать, Консоль и прочее. Эти отличия гораздо серьезнее, чем та мелочь, о которой я написал.

Мы не меняем язык, мы меняем прикладные вещи и тут никуда не деться.

А чего думать-то? Ведь и правда мелочь, 2 простых бага на 3 строчки кода :)

**Comment by artbear** [comment]
Отличий от 1С не будет, т.к. в 1С `Новый Файл(ОтносительныйПуть)` не имеет никакого прикладного смысла и никогда и никем не используется, т.к. мы в 1С не можем управлять текущим каталогом, а значит, и получать неизвестно какой файл не можем :)

**Comment by EvilBeaver** [comment]
> Использовать, Консоль и прочее

Этих штук нет в 1С, и копипаста из 1С в односкрипт такая невозможна. А вот Файл в 1С есть и код, который работал одним образом, при копипасте станет работать по-другому. И хрен это отловишь. Вот чего мне не нравится, понимаешь? Неявное, незаметное **изменение** поведения.

**Comment by EvilBeaver** [comment]
Кстати, вот обход:

```
ПолныйПуть = ОбъединитьПути(ТекущийКаталог(), ВозможноАбсолютныйПуть);
```

Вспоминаем давний холивар и точку зрения @dmpas (и мою вслед за ним). Это фича. Которая теперь решает и твою проблему тоже.

**Comment by artbear** [comment]
Конечно, я понимаю, я также подобные неявные изменения не люблю.

**Comment by artbear** [comment]
Обходя понятен, я другой вариант привел выше.

Тут главное - что подобное поведение Файл.Путь будет аукаться каждый раз по-разному, как раз здесь я вижу неявное поведение.

Придется заставлять себя использовать указанную тобой конструкцию, что ИМХО слабо наглядно.

А новичкам-разработчикам как быть или тем, кто на какое-то время не писал скрипты, все же забудется. А потом здравствуйте, грабли.

ИМХО нужно исправлять, придумывать и **помнить** какие-то странные обходные пути не хочется.

**Comment by artbear** [comment]
> Придется заставлять себя использовать указанную тобой конструкцию, что ИМХО слабо наглядно.

Особенно с учетом того, что в 1С вообще нет ОбъединитьПути :(

**Comment by EvilBeaver** [comment]
Смотри, апи объекта Файл, практически полностью заимствовано фирмой 1С из .NET. Имена методов и возвращаемые значения. Всё. Объект Файл - это парсер пути. Он в большинстве случаев даже к диску не обращается, а бегает по строке. Так ведет себя .NET, так ведет себя 1С. Это осознанная реализация. Не надо делать другое поведение здесь.

**Comment by artbear** [comment]
Буду бить тебя твоим же оружием :)

Вот тебе отличие

```
Процедура ТестДолжен_ПроверитьАтрибутПутьУФайлаВКорневомКаталоге() Экспорт

    ИмяФайла = "C:\";
    Файл = Новый Файл(ИмяФайла);
    Ожидаем.Что(Файл.ПолноеИмя, "Файл.ПолноеИмя").Равно("C:\");
    Ожидаем.Что(Файл.Путь, "Файл.Путь").Равно("C:\");
КонецПроцедуры
```

Интересно, почему 1С сделала поведение, отличное от .Net ?
Почему не захотела возвращать пустое значение, как  написано в MSDN `GetDirectoryName('C:\') returns ''` ?

**Comment by EvilBeaver** [comment]
Не сошлись во мнениях, что такое "родительский каталог диска C:" Очевидно же. :smile:

**Comment by artbear** [comment]
Это и есть пример разного поведения.
1С выбрала ИМХО верный с точки зрения конечного пользователя вариант.
В Windows нет понятия `пустого` пути, корень один - корневой каталог диска, поэтому логично, что 1С выбрала его же как путь.

У нас похожая ситуация - с путем по относительному имени файла.

**Comment by EvilBeaver** [comment]
@artbear. Исправление предлагается следующее: падение по null-reference по-любому исправляется, поведение по остальным пунктам приводится в соответствие с 1С. Получение полных путей из относительных остается на уровне кода скрипта (однострочный пример - выше). Хочется послушать мнения @dmpas и @allustin

**Comment by dmpas** [comment]
Добавлю букв. Я думаю, ноги тут растут из самых наимохнатейших времён: файл - это не всегда то, что лежит где-то в папочке на диске. Файлом может быть сетевой сокет, КОМ-порт, вообще что угодно. И понять, что это в действительности, можно только системными обращениями к ОСи, что как бы относительно не быстро. Потому издревле работа с файлами разделяется на две части: тупая обработка пути, как строки, и получение некоторых физических данных. Соответственно, первое у 1С представлено свойствами, второе - методами (Размер, ПолучитьВремяИзменения).

В общем, я к чему? В общем случае получение физически верного полного пути для файла - это дорогостоящая операция. И к тому же далеко не всегда прозрачная: сталкивался с тем, что система отказывалась вычислять полный путь, если в пути были несуществующие каталоги.

**Comment by ghost** [comment]
@dmpas соглашусь...
в моём коде часто можно увидеть такое или примерно такое

``` BSL
имяДескриптора = "null";
полныйПутькДескриптору = "/dev";
адресДескриптора = ОбъединитьПути(полныйПутькДескриптору,имяДескриптора);

_дескрипторФайла = Новый Файл(адресДескриптора);
```

это я делаю специально для себя и команды - **чтобы не забывать что объект Файл, фактически только указатель на что-то и не обязательно файл.**

А еще хуже - файл, это вообще странное понятие: 

>  именованная область данных на носителе информации.

в некоторых операционных системах можно хранить указатель на носитель информации, но потом отдельным потоком удалить его с носителя, сохранив в памяти приложения - которая также является носителем информации.

И вот вопрос на засыпку - что в 1С должен вернуть данный метод ? Так как он валиден.

```
_дескрипторФайла = Новый Файл("\\\\.\\COM1");
Сообщить(_дескрипторФайла.Путь);
```

**Comment by dmpas** [comment]
@allustin ответ на отсыпку:

```
    \\\\
```

**Comment by ghost** [comment]
что касается темы дискуссии - мой подход давно известен
- либо мы повторяем поведение 1С
- либо регистрируем баг и меняем поведение 1С через **bugboard** и потом меняем поведение у себя ;-)

я сторонник делать либо так :

```
ИмяФайла = "./file1.txt";
Файл = Новый Файл(ИмяФайла);
```

либо так 

```
ИмяФайла = ОбъединитьПути(ТекущийКаталог(),"file1.txt");
Файл = Новый Файл(ИмяФайла);
```

**Comment by EvilBeaver** [comment]
3 vs 1. Решение принято.

**Comment by artbear** [comment]
@dmpas Жду продолжения (послеобеденного)

**Comment by artbear** [comment]
@EvilBeaver @dmpas еще не высказался.

**Comment by EvilBeaver** [comment]
Разве? Ну ок, ждем.

**Comment by dmpas** [comment]
@artbear я то же сообщение отредактировал.

В общем, против я. Есть опасность огрести гораздо больше косяков и получить тормоза на ровном месте. Предлагаю задачку не закрывать, я сделаю предлагаемую запилку и попробую воочию показать, где и как будет падать, чтобы 3:1 превратить в 4:0 :)

**Comment by artbear** [comment]
> я сделаю предлагаемую запилку и попробую воочию показать, где и как будет падать, чтобы 3:1 превратить в 4:0 :)

@dmpas Отличное предложение по "запилке", но я не совсем понял про "показать, где и как будет падать"

**Comment by artbear** [comment]
Лады, предлагаю следующее:
- задачу пока не закрываем
- проблему с текущим каталогом оставляем, как есть
- ждем "запилки" @dmpas
- решаем, кто поправит баг с корнем для Файл.Путь ? https://github.com/EvilBeaver/OneScript/issues/273#issuecomment-223752006

**Comment by EvilBeaver** [comment]
Исправлено
