### ISSUE TITLE
Нельзя обратиться к ЦветТекста/ЦветФона консоли до их инициализации

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#275]
Так **падает**

```
Консоль = Новый Консоль();
ПредыдущийЦветТекстаКонсоли = Консоль.ЦветТекста;
```

а так работает

```
Консоль = Новый Консоль();
Консоль.ЦветТекста = ЦветКонсоли.Зеленый;
ПредыдущийЦветТекстаКонсоли = Консоль.ЦветТекста;
```

**Comment by EvilBeaver** [comment]
@artbear странно, у меня и второй вариант не работает. А у тебя? И какой у тебя текст ошибки?

**Comment by artbear** [comment]
> странно, у меня и второй вариант не работает. А у тебя? И какой у тебя текст ошибки?

Второй вариант у меня изначально был следующий:

```
Консоль = Новый Консоль();
ПредыдущийЦветТекстаКонсоли = ЦветКонсоли.Зеленый;
Консоль.ЦветТекста = ПредыдущийЦветТекстаКонсоли;
```

**Comment by EvilBeaver** [comment]
Ну так а текст ошибки какой?

Исправлено в 1.0.13.143 (скачивается с "ночной")
