### ISSUE TITLE
Демо-пример готового проекта на .Net для демонстрации подключения внешних библиотек/пакетов

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#279]
Хотел бы получить пример готового демо-проекта, который можно подключить как внешнюю компоненту, пакет к 1скрипту.

ИМХО для разработчиков прикладных вещей может быть полезно.
Например, я в C# не особо волоку, но к готовому проекту добавить полезные фичи могу.

Эта идея родилась после #249, который как раз просится в виде отдельного пакета

@dmpas

**Comment by dmpas** [comment]
Набросал на скорую руку: https://github.com/dmpas/oscript-component-example

**Comment by EvilBeaver** [comment]
Все так. Быстрее, чем для 1С, верно? ))

**Comment by artbear** [comment]
@dmpas Быстро! Круто! Спасибо!

@EvilBeaver Теперь бы еще эту инфу задокументировать на офиц.сайте и в доке на гитхабе :)

**Comment by dmpas** [comment]
@EvilBeaver быстро, это точно :smiley: единственное, у меня вопрос по версиям нугет пакета. я так полагаю, в хранилище лежит ночная сборка? могу я писать компонент, основываясь на предыдущих версиях?

**Comment by EvilBeaver** [comment]
В nuget выложены только релизные версии. Ночных сборок там нет.

**Comment by dmpas** [comment]
@EvilBeaver вчера там дата обновления стояла "06.06.2016", оттого я и подумал, что ночные.

**Comment by EvilBeaver** [comment]
не, это я вчера копался

**Comment by dmpas** [comment]
@artbear расширил пример

**Comment by artbear** [comment]
@dmpas Спасибо, то, что нужно.
Закрываю открытые issue в твоем репо

**Comment by dmpas** [comment]
@artbear по этой задаче ещё есть что-нибудь кроме "задокументировать"?

**Comment by artbear** [comment]
ИМХО только задокументировать осталось.

**Comment by EvilBeaver** [comment]
http://oscript.io/dev/page/components
