### ISSUE TITLE
Файл.Путь для каталогов работает неверно, нет совместимости с 1С

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#281]
Писал универсальный код под Винду и Линукс для https://github.com/EvilBeaver/OneScript/pull/277#issuecomment-224043444

В итоге еще один баг с `Файл.Путь` нашелся :)
Следующий код запускаю в 1С и в 1скрипт

```
Процедура ТестДолжен_ПроверитьАтрибутПутьУФайлаВКорневомКаталоге() Экспорт

    //ИмяФайла = КаталогПрограммы(); // для универсальности под Вин и Линукс
    ИмяФайла = "C:\Program Files (x86)\1cv8\8.3.8.1675\bin\";

    Пока Истина Цикл
        Файл = Новый Файл(ИмяФайла);
        Сообщить("ИмяФайла " +ИмяФайла);
        Сообщить(" Файл.Путь " +Файл.Путь);
        Если Файл.Путь = ИмяФайла Тогда // для корневого каталога 1С возвращает его самого
            Прервать;
        ИначеЕсли ПустаяСтрока(Файл.Путь) Тогда
            ВызватьИсключение "Файл.Путь в 1С не должен возвращать пустую строку";
        КонецЕсли;
        ИмяФайла = Файл.Путь;
    КонецЦикла;
    //юТест.ПроверитьРавенство(Файл.Путь, "C:\", "Файл.Путь должен возвращать корневой каталог диска, а это не так"); // тут падает в 1скрипт

КонецПроцедуры
```

1С возвращает следующий результат

```
ИмяФайла C:\Program Files (x86)\1cv8\8.3.8.1675\bin\, Файл.Путь C:\Program Files (x86)\1cv8\8.3.8.1675\
ИмяФайла C:\Program Files (x86)\1cv8\8.3.8.1675\, Файл.Путь C:\Program Files (x86)\1cv8\
ИмяФайла C:\Program Files (x86)\1cv8\, Файл.Путь C:\Program Files (x86)\
ИмяФайла C:\Program Files (x86)\, Файл.Путь C:\
ИмяФайла C:\, Файл.Путь C:\
```

А 1скрипт возвращает всего 1 строку
`ИмяФайла C:\Program Files (x86)\1cv8\8.3.8.1675\bin\, Файл.Путь C:\Program Files (x86)\1cv8\8.3.8.1675\bin\`

и завершает свою работу :(
Баг, господа, баг!

На всякий случай напишу - `ИмяФайла = ОбъединитьПути(ТекущийКаталог(), "C:\Program Files (x86)\1cv8\8.3.8.1675\bin\");` не спасает.

PS Что-то многовато вопросов к простому объекту `Файл`
@EvilBeaver А ты говоришь, что 1С сделала поведение, как у .Net :)

**Comment by artbear** [comment]
Правда, в этом баге не падает со странной ошибкой, как в #277 :)

Так что нужно править и #277 и #281

**Comment by EvilBeaver** [comment]
> А ты говоришь, что 1С сделала поведение, как у .Net

Зато я не говорил, что EvilBeaver сделал поведение, как у .Net. Там мои алгоритмы в части свойств.

Объект Файл вовсе не простой. Можешь приобщиться, там масса нюансов

**Comment by artbear** [comment]
Андрей, 
только что скачал ночную сборку.
1.0.13.143
Баг не исправлен.
Указанный код падает.

**Comment by artbear** [comment]
Ночной сборки так и нет.
Предлагаю переоткрыть баг.
