### ISSUE TITLE
Требуется явное преобразование типа параметра командной строки

### ISSUE THREAD

**Issue by vsuh** [EvilBeaver/OneScript#283]
В файле `tasks.json` в выражении _args_ описания задачи допускаются только строки
![image](https://cloud.githubusercontent.com/assets/12156293/15891756/d1300420-2d7e-11e6-913c-a80bd880276f.png)

если полученный параметр использовать без преобразования, в некоторых случаях это приводит к ошибке:

```
п = АргументыКоманднойСтроки[0];

Для нн = 1 По п Цикл
  Сообщить(нн);
КонецЦикла;

```

running command> oscript.exe -encoding=utf-8 e:_git_\our_local_repos\TestAlgo\t.os 6 20000
{Модуль e:_git_\our_local_repos\TestAlgo\t.os / Ошибка в строке: 3 / Внешнее исключение: Внутренняя ошибка: неверное состояние стека}

При запуске из комстроки картина такая:

E:\ххх>OScript t.os 2
{Модуль E:\ххх\t.os / Ошибка в строке: 3 / Внешнее исключение: Внутренняя ошибка: неверное
состояние стека}

**Comment by EvilBeaver** [comment]
А что за преобразование? Что такое "6, 20000"?

**Comment by EvilBeaver** [comment]
Все, понял. Система запускает цикл 1 по "6", без приведения к числу. Интересно, а что 1С в таком случае говорит?

**Comment by EvilBeaver** [comment]
@vsuh @artbear 

1С в таком случае говорит:

"Встроенный язык: Строка 3: Операции сравнения на больше-меньше допустимы только для значений совпадающих примитивных типов (Булево, Число, Строка, Дата)"

Исправлением будет приведение поведения системы к такому же

**Comment by vsuh** [comment]
Да, согласен.
мне почему-то думалось, что 1с неявно преобразует тип к числу...
