### ISSUE TITLE
Команда для показа версии продукта

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#290]
Предлагаю команду `--version` как во многих аналогичных консольных утилитах
Нужно показать только версию продукта в консоли без доп.сообщений

**Comment by dmpas** [comment]
@artbear как бы выглядел тест по этой задачке?

**Comment by nixel2007** [comment]
@dmpas 

```
ВыводКоманды = ВыполнитьКоманду("oscript --version");
Если Не СтрНайти(ВыводКоманды, "Версия продукта:") > 0 Тогда
    ВызватьИсключение "алярм, алярм";
КонецЕсли;
```

Ну или как там в xUnit принято строки сравнивать с киданием исключений

**Comment by dmpas** [comment]
предлагаю ключ назвать "-version" - с одной чёрточкой для единообразия.

**Comment by artbear** [comment]
@dmpas Согласен, только тест чуток поправить и готово.

**Comment by dmpas** [comment]
@artbear поправил тест

**Comment by artbear** [comment]
@dmpas Да, теперь самое оно.
