### ISSUE TITLE
Проблемы с передачей параметров в 1script со строками с пробелами

### ISSUE THREAD

**Issue by ret-Phoenix** [EvilBeaver/OneScript#294]
c:\work\portable\OneScript\bin\oscript.exe c:\work\tmp\my_ini_parse\clearCash.os P "c:\work\tmp\My Path\"
параметр видит как: c:\work\tmp\My Path\"
т.е. пропадает 1 кавычка

**Comment by EvilBeaver** [comment]
У вас в конце слэш+кавычка. Это означает экранирование символа. Уберите слэш перед кавычкой. Не ошибка программы.

**Comment by ret-Phoenix** [comment]
А если мне нужно передавать именно в таком виде?

**Comment by EvilBeaver** [comment]
Тогда и первую кавычку экранируйте

**Comment by ret-Phoenix** [comment]
Понял. Спасибо
