### ISSUE TITLE
Поправить авторские права

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#299]
`Copyright (c) 2014 BeaverSoft`

Как бы уже половина 2016 года прошла :smile:

**Comment by EvilBeaver** [comment]
Да это там устаревшая хрень написана. Что бы там написать нужного и актуального - вот вопрос

**Comment by dmpas** [comment]
@EvilBeaver так эта хрень устаревшая в свойствах exe-файла торчит :) для начала хватит и того, чтобы год поправить :)

**Comment by dmpas** [comment]
Кстати, в нугете 2015 год стоит:

Copyright
OneScript OpenSource Community 2015

**Comment by EvilBeaver** [comment]
насколько я помню (могу ошибаться) копирайты каждый год и не меняет никто. Типа "копирайт, начиная с.."

**Comment by nixel2007** [comment]
Меняют, если в году было изменение исходного кода. 
Типа ты мог кодить  в 2014 и 2016, в копирайте тогда будет именно 2014, 2016
