### ISSUE TITLE
Поддержка AnyCPU платформы

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#300]
Предлагаю в NuGet-хранилище складывать пакет, собранный под AnyCPU. В стандартной поставке под винды, я так понимаю, x86 нужен для снегопата, но в остальных случаях навязывание одной платформы совершенно неоправданно.

**Comment by EvilBeaver** [comment]
да, x86 только для снегопата.

**Comment by EvilBeaver** [comment]
@rsyuzyov, напомни, пожалуйста, в каком состоянии проект переезда на реборн? Я бы хотел исключить snegopat из данного репо, как некроссплатформенную библиотеку, но без альтернативы  (в виде твоей разработки) не могу этого сделать.

**Comment by rsyuzyov** [comment]
@EvilBeaver если загрузка позволит - закончу в эти выходные, иначе в следующие.

**Comment by rsyuzyov** [comment]
@EvilBeaver в виду жопы с загрузкой скотина не поспевает, вынужден еще раз отложить до конца недели. Скоро исправлюсь :)

**Comment by EvilBeaver** [comment]
Завел отдельную задачку по отделению основного проекта #316
