### ISSUE TITLE
Складывать в нугет пакеты из ночных сборок

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#304]
Чтобы разрабатывать компоненты, не дожидаясь выпуска очередной версии.

**Comment by EvilBeaver** [comment]
Там вроде бы есть альфа-версии библиотек, да? Типа stable и dev?

**Comment by dmpas** [comment]
В монодевелопе у меня есть галка "show pre-release packages". Так что думаю, что есть возможность отделить релиз от нерелиза. А вот альфа/бета/рц/... - такого нигде не вижу.

**Comment by EvilBeaver** [comment]
релиз/нерелиз будет достаточно

**Comment by dmpas** [comment]
> You only need to specify a version string that uses SemVer format (e.g. 1.0-beta) instead of the usual format (e.g. 1.0) and NuGet will automatically treat it as a prerelease package.

http://stackoverflow.com/questions/10590978/how-to-publish-nuget-prerelease-version-package

**Comment by alexkmbk** [comment]
Кстати вот столкнулся с тем что 1.0.14 нет класса ScriptEngine.Machine.Contexts.CLREnumValueWrapper
а 1.0.15 он есть :-)

**Comment by dmpas** [comment]
@alexkmbk ну вот это чуть ли не основная причина появления этой заявки :) а ещё коллекции будут по-другому работать.

**Comment by EvilBeaver** [comment]
@dmpas нельзя положить в нугет пакет с одинаковым номером версии 1.0.15, например. Но публикацию сделал

**Comment by dmpas** [comment]
@EvilBeaver я тут поковырялся: https://github.com/EvilBeaver/OneScript/pull/391
