### ISSUE TITLE
Отличается поведение Новый Файл("") от 1С

### ISSUE THREAD

**Issue by demidych** [EvilBeaver/OneScript#306]
В 1С "ф = Новый Файл("");" отрабатывает без ошибок, а 1Script(1.0.14.167) выводит ошибку:
"{Модуль test5.os / Ошибка в строке: 6 / Неверное значение аргумента}"

Необходимо сделать поведение аналогичным 1С, чтобы упростить портирование. Например, такой код есть в "V8Reader.epf".

**Comment by EvilBeaver** [comment]
А вот интересно, что в 1С означает объект Файл, инициализированный пустой строкой?
@demidych можешь расследовать, как себя ведет такой объект, что возвращают его свойства?

**Comment by demidych** [comment]
Вот что показывает отладчик для "Новый Файл("")":

| Свойство | Значение | Тип |
| --- | --- | --- |
| Имя | "" | Строка |
| ИмяБезРасширения | "" | Строка |
| ПолноеИмя | "" | Строка |
| Путь | "" | Строка |
| Расширение | "" | Строка |

| Свойство | Значение | Тип |
| --- | --- | --- |
| ф.Существует() | Ложь | Булево |
| ф.Размер() | {(1)}: Ошибка при вызове метода контекста (Размер) |  |

**Comment by artbear** [comment]
@bambr1975 Интересно, а для чего код `Ф = Новый Файл("")` юзается в `v8reader` ?

**Comment by bambr1975** [comment]
Очень интересно, я тоже не знаю, где. Можно ссылочку на строку кода?

**Comment by artbear** [comment]
@demidych Можно ссылкой отсюда https://github.com/bambr1975/v8Reader/blob/master/src/V8Reader/ObjectModule.txt или из соседних форм?

**Comment by demidych** [comment]
По факту не используется, но в коде есть:
"Файл1 = Новый Файл(Путь1);" , а Путь1 может быть пустым.
https://github.com/xDrivenDevelopment/v8Reader/blob/810ba879d974e36f0c90e6284b011f9902549842/src/V8Reader/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/module.bsl#L4266

Я переделал прекоммит, чтобы работал только на 1Script (выдернул код из v8Reader и закомментировал все, что мешало распаковке отчетов/обработок). А после перехода на 1Script 1.0.14 этот код перестал работать.

**Comment by bambr1975** [comment]
вау, круто. А может, просто в условия обернуть?

**Comment by bambr1975** [comment]
Выложишь свою реализацию precommit?

**Comment by artbear** [comment]
> Я переделал прекоммит, чтобы работал только на 1Script (выдернул код из v8Reader и закомментировал все, что мешало распаковке отчетов/обработок). 

Ага, выложи свои доработки.
Ждем

**Comment by demidych** [comment]
Выложил здесь https://github.com/demidych/precommit1C_1Script

Но там треш полный, т.к. старался по минимуму править код v8reader, чтобы было проще через сравнение накатывать новые версии.
Плюс у меня своя набралась библиотека для 1Script, поэтому пришлось в код добавлять некоторые методы, чтобы убрать от нее зависимость.

**Comment by bambr1975** [comment]
https://api.github.com/repos/demidych/precommit1C_1Script/commits disada3@gmail.com - это Ваш e-mail? Ну надо же!!!!! Нашелся!!!! Спасибо, что выложил!!!!!

**Comment by demidych** [comment]
Мой :smile:

**Comment by artbear** [comment]
@demidych 

> Плюс у меня своя набралась библиотека для 1Script

Что за библиотека? поделись

**Comment by demidych** [comment]
Ничего особого. Просто набор общих методов, которые я часто использую в 1Script или 1С.

Частично дублирует oscript-library, т.к. методы взятые из 1С имеют уж слишком длинные имена. Например, РазложитьСтрокуВМассивПодстрок() у меня называется СтрокаМассив() и т.д.

**Comment by artbear** [comment]
Сможешь поделиться в своем репо :) ?

**Comment by demidych** [comment]
Выложил здесь https://github.com/demidych/oscript-library-demidych
