### ISSUE TITLE
Сделать ICollectionContext не IEnumerable

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#310]
`ICollectionContext` объявлен, как потомок `IEnumerable<IValue>`, однако его ИЕнумерабельность в самом движке по сути нигде не используется, зато дико доставляет горя при написании внешних компонент.

Для примера возьмём хотя бы Соответствие:

``` C#
var someMap = new MapImpl();
foreach (var someKV in someMap)
{
    // someKV - IValue, но (гадом буду!) там всегда KeyAndValueImpl !!!
    var KV = someKV as KeyAndValueImpl; // совершенно излишнее преобразование
    // которое нужно делать в каждом цикле
}
```

Предложение: убрать наследование от `IEnumerable<IValue>` в `ICollectionContext` и добавить в каждую коллекцию отдельно тот, который нужен (`<IValue>`, `<KeyAndMapImpl>`, `<AnyClassFromDll>`).

Изменению подвергнутся два десятка файлов, тесты проходят, проверил :)

Да, сломаются уже существующие коллекции в уже существующих внешних компонентах, но что-то мне подсказывает, что их мало.

**Comment by EvilBeaver** [comment]
А разве в Для Каждого..Из не получается этот енумератор из коллекции?

**Comment by dmpas** [comment]
нет, там берётся `GetManagedIterator` из `ICollectionContext`, который уже в своём исполнении может получать этот иенумератор из коллекции.

**Comment by EvilBeaver** [comment]
В принципе, да, можно
