### ISSUE TITLE
`DiscoverGlobalContexts` при подключении компоненты

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#311]
Запрос на прояснение.

`ПодключитьВнешнююКомпоненту` подключает только классы, но не подключает перечисления. Чтобы подключить перечисления, нужно создавать библиотеку, класть туда компоненту и в загрузчике библиотеки подгружать компоненту.

Вопросы: правильно ли я понял? И какой в это заложен смысл?

**Comment by EvilBeaver** [comment]
Скорее всего это баг. По задумке должен подключать все, что есть в компоненте.
