### ISSUE TITLE
Встроенный метод ЗапуститьПриложение двойные пробелы превращает в одинарные

### ISSUE THREAD

**Issue by bambr1975** [EvilBeaver/OneScript#312]
В пустом git-репозитории создан os-скрипт с названием "Наименование  с двойным пробелом.os" (два пробела после слова "Наименование") и текстом
ЗапуститьПриложение("cmd /C ""git add --all ""Наименование  с двойным пробелом.os"" > ""C:\Users\Admin\AppData\Local\Temp\mkjdzpf4.ynf.tmp"" 2>&1""");

После его запуска в файле mkjdzpf4.ynf.tmp такой текст 
fatal: pathspec 'Наименование с двойным пробелом.os' did not match any files
Смысл в том, что двойной пробел преобразуется в одинарный и из-за этого коммита не происходит. Что делать?

**Comment by EvilBeaver** [comment]
Здесь неверно использованы кавычки. Такая строки и просто в cmd не работает.

**Comment by bambr1975** [comment]
Работает. Проверено.
