### ISSUE TITLE
Работа с ЭтотОбъект

### ISSUE THREAD

**Issue by ret-Phoenix** [EvilBeaver/OneScript#313]
При приведении к Строке объекта реализующего IRuntimeContextInstance получаю testFormButton19a33fc545f9424aa9708af41f45cbe4, где test-FormButton.os - файл из которого работаю с объектом

Хотелось бы имея ссылку на объект получать информацию по имени файла

`
Кнопка2.УстановитьДействие(ЭтотОбъект, "Нажатие", "ПриНажатииНаКнопку2");

private IRuntimeContextInstance _thisScript;

```
    [ContextMethod("УстановитьДействие", "SetAction")]
    public void setAction(IRuntimeContextInstance contex, string eventName, string methodName)
    {
        if (eventName == "Нажатие")
        {
            ((Button)this._item).Click -= BtnClick;
            ((Button)this._item).Click += BtnClick;
            this._thisScript = contex;
            this._methodName = methodName;
        }
    }
```

`

**Comment by dmpas** [comment]
В качестве временного решения можно передавать не `ЭтотОбъект`, а `ТекущийСкрипт()`.

**Comment by EvilBeaver** [comment]
@dmpas, а что это даст?

**Comment by ret-Phoenix** [comment]
Кнопка2.УстановитьДействие(ТекущийСкрипт(), "Нажатие", "ПриНажатииНаКнопку2");
{Модуль c:\work\GitHub\tests\testrunner.os / Ошибка в строке: 339 / Внешнее исключение: {Модуль c:\work\GitHub\oscript-simple-gui\tests\test-FormButton.os / Ошибка в строке: 162 / Неизвестный символ: ТекущийСкрипт}  

oscript: 1.0.14.195

**Comment by dmpas** [comment]
@EvilBeaver оттуда ж можно `Source` взять

**Comment by dmpas** [comment]
@ret-Phoenix `ТекущийСценарий()` / `CurrentScript()`

**Comment by ret-Phoenix** [comment]
Спасибо, сработало. Забыл об этом методе.

+к 0. Было бы интересно получить имя класса, если это библиотека.

**Comment by dmpas** [comment]
@ret-Phoenix а зачем нужно имя файла в данном случае?

**Comment by ret-Phoenix** [comment]
Сообщить("Действие: " + Кнопка2.ПолучитьДействие("Нажатие"));
Действие: c:\work\GitHub\oscript-simple-gui\tests\test-FormButton.os:ПриНажатииНаКнопку2

Чтобы понять где лежит обработчик события

**Comment by dmpas** [comment]
@ret-Phoenix тут есть два подводных камня:
1. запуск из TestApp, что не страшно, ибо не для пользователей сделано
2. если обработчик лежит не в файле - во внешней компоненте, например.

**Comment by ret-Phoenix** [comment]
Поэтому и хотел .ToString() нормальный )
В случае с ВК он вернул бы: ИмяМоейВК.МойКласс

**Comment by dmpas** [comment]
Я так с ходу не уверен, что это хороший вариант, возвращать путь к файлу в ToString для скрипта. Тут надо крепко подумать.

**Comment by EvilBeaver** [comment]
Путь к файлу не надо. Скрипт не обязательно в файле лежит, это важно. Специально сделан отдельный объект (возвращаемый из упомянутого ТекущийСценарий), чтобы отвязать происхождение скрипта от самого объекта скрипта

**Comment by ret-Phoenix** [comment]
ТекущийСценарий - вполне подошел.
