### ISSUE TITLE
Ошибки, возникающие при вызове ЗагрузитьСценарий, не ловятся в блоке Попытка-Исключение

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#315]
Более того, не выполняется код, следующий за вызовом `ЗагрузитьСценарий`

Пример кода:

```
УстановитьТекущийКаталог("C:\projects\oscript-library\src\gitsync\src\");
ФайлИсполнителя = Новый Файл("C:\projects\oscript-library\src\gitsync\src\gitsync.os");
    Попытка
Сообщить("Начало1");
        ИсполнительШагов = ЗагрузитьСценарий(ФайлИсполнителя.ПолноеИмя);
Сообщить(20);
    Исключение
Сообщить(30);
    КонецПопытки;
Сообщить(40);
```

Можно указанный код запустить в `TestApp`

Получаю следующий текст:

```
Script started: 01.08.2016 22:03:38
Начало1
Синхронизация хранилища конфигураций 1С с репозитарием GIT.
Использование: 
    gitsync <storage-path> <git-url> [local-dir] [ключи]
    gitsync <команда> <параметры команды> [ключи]
... Куча справки по гитсинк
Для подсказки по конкретной команде наберите gitsync help <команда>
ОШИБКА - Указаны некорректные аргументы командной строки

Error detected. Exit code = 1
Script completed: 01.08.2016 22:03:39
Duration: 00:00:00.4227273
```

Как можно видеть, кроме текста `Начало1` и справки гитсинк больше никаких сообщений не выводится :( хотя сообщения должны выводиться.

Явный и довольно серьезный баг :(

/cc @EvilBeaver @dmpas Что скажете?

**Comment by artbear** [comment]
Аналогичная проблема с ПодключитьСценарий

```
//ИсполнительШагов = ЗагрузитьСценарий(ФайлИсполнителя.ПолноеИмя);
ПодключитьСценарий(ФайлИсполнителя.ПолноеИмя, "МойОбъект1");
ИсполнительШагов = Новый МойОбъект1; 
```

**Comment by EvilBeaver** [comment]
Загрузить сценарий используется сплошь и рядом в библиотеке. В такой формулировке бага точно нет.

**Comment by artbear** [comment]
@EvilBeaver Ты пути для гитсинка поменяй и код запусти, пожалуйста, в `TestApp.exe`
Сразу сам проявление увидишь.
Жду.

А неужели из кода баг непонятен?
Ни одного доп.сообщения ведь нету, а они должны быть.

**Comment by EvilBeaver** [comment]
Пример кода понятен, но ровно такой же используется в тестраннере и работает. Тут происходит что-то еще, имхо

**Comment by EvilBeaver** [comment]
Кстати, а там внутри случайно не вызывается ЗавершитьРаботу(1)??

**Comment by artbear** [comment]
Да, там вызывается именно `ЗавершитьРаботу(1)` для указания правильного кода возврата.

Хотелось бы разруливать подобное - безусловное завершение работы внутри загружаемого сценария не должно завершать внешний сценарий!

@EvilBeaver что скажешь?

**Comment by pumbaEO** [comment]
Имхо, это не баг. Я в том же предприятии 1с могу подключить внешнюю обработку и там будет "ЗавершитьРаботуСистемы()" и все закроется без вопросов. 

Имхо, это баг именно самого gitsync, а не движка.

**Comment by EvilBeaver** [comment]
Завершить работу аналогичен ExitThread. Это принудительное завершение приложения (не скрипта) с кодом возврата для ОС. Это поведение менять не будем. Нужно переписывать клиентский скрипт, чтобы не завершал приложение.

**Comment by artbear** [comment]
Ребята, вопросы:
- как в скрипте завершить работу и передать нужный код возврата в систему без использования ЗавершитьРаботуСистемы?
- как в **универсальном** скрипте, который может загружать разные сценарии, обеспечить нормальную работу без вылета системы для скрипта, использующего ЗавершитьРаботуСистемы?

Вариант - не загружать такой скрипт не предлагать, подчеркну, это универсальный скрипт, который анализирует сценарии после загрузки.
например, эта ситуация может возникнуть в тест-раннере.
Реально проблема возникла при работе с моим проектом 1bdd.

**Comment by artbear** [comment]
@EvilBeaver 

> Нужно переписывать клиентский скрипт, чтобы не завершал приложение.

я уже задал вопрос:
- как в скрипте завершить работу и передать нужный код возврата в систему без использования ЗавершитьРаботуСистемы?

**Comment by pumbaEO** [comment]
Ну имхо, в самом скрипте gitsync должна стоять какая-либо проверка признака "интерактивный запуск" или подключение в режиме бибилиотеки и там уже делать правильный выход. 
Универсально никак не сделаем, т.к. если эту тему развивать, то придем к песочнице и разрешениями на запуск разных io и потом к манифесту и т.д.

**Comment by artbear** [comment]
@EvilBeaver @pumbaEO жду ответов на вопросы.

Текущее поведение считаю серьезным багом.

**Comment by artbear** [comment]
Приведу пример запуска тест-раннера для гитсинк с абсолютно той же проблемой

```
C:\projects\oscript-library\src\gitsync\src>
oscript C:\projects\oscript-library\tests\testrunner.os -run gitsync.os
Версия приложения 1.0.15.170
ИНФОРМАЦИЯ - Начинаю синхронизацию хранилища 1С и репозитария GIT
ИНФОРМАЦИЯ - Получение изменений с удаленного узла (pull)
ИНФОРМАЦИЯ - fatal: 'gitsync.os' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

ОШИБКА - {Модуль C:\projects\oscript-library\src\gitsync\src\gitsync.os / 
Ошибка в строке: 321 / Не удалось получить изменения с удаленного узла (код: 1)}
```

**Comment by pumbaEO** [comment]
Еще раз, имхо, текущее поведение правильное. То что gitsync неправильно работает в режиме подключения библиотеки - вот главный вопрос и сопутствующий просто "как в скрипте определить, он вызван как подключаемый или же интерактивно" и дальше уже исправлять именно gitsync с выбросом исключения, а не ЗавершитьРаботуСистемы()

**Comment by EvilBeaver** [comment]
Артур, это проблема гитсинка, а не движка, ну елы палы

**Comment by nixel2007** [comment]
> это проблема гитсинка, а не движка, ну елы палы

+1

**Comment by artbear** [comment]
Ребята, ну елы палы :(
я уже выше написал вопросы:

> как в скрипте завершить работу и передать нужный код возврата в систему без использования ЗавершитьРаботуСистемы?

@EvilBeaver жду ответа на этот вопрос.
Если его удастся решить, тогда удастся доработать гитсинк и все остальные подобные скрипты.

**Comment by artbear** [comment]
А еще полезен ответ на доп.вопрос

> как в скрипте определить, он вызван как подключаемый или же интерактивно

@EvilBeaver также жду ответа

**Comment by nixel2007** [comment]
@artbear так же, как пробрасываются все остальные данные. Экспортная переменная

**Comment by artbear** [comment]
@nixel2007 тебя не понял, прием :)
какая экспортная переменная?? 
Напоминаю, это скрипт гитсинк.
это обычный скрипт, вызывается через oscript гитсинк.ос
он должен код возврата в систему
как вернуть этот код возврата в систему без ЗавершитьРаботуСистемы ?

**Comment by pumbaEO** [comment]
Вызвать исключение и тогда кодвозврата не будет 0

**Comment by artbear** [comment]
мне нужно указать конкретные коды возврата в зависимости от разных условий.
напоминаю, это скрипт.
и разные коды возврата в скриптах - это хорошо :)

**Comment by nixel2007** [comment]
Параметризированные исключения?

**Comment by pumbaEO** [comment]
Открываем документацию: 

```
СтартовыйСценарий / EntryScript()

Возвращает информацию о сценарии, который был точкой входа в программу. Можно выделить два вида сценариев: те, которые были подключены, как классы и те, которые запущены непосредственно. Метод СтартовыйСценарий возвращает информацию о сценарии, запущенном непосредственно. Для получения информации о текущем выполняемом сценарии см. метод ТекущийСценарий()
Возвращаемое значение

Объект ИнформацияОСценарии
```

В gitsync исправляем условия с учетом значения данной переменной.

**Comment by artbear** [comment]
@pumbaEO Женя, ты понимаешь, что фактически мы говорим о том, что 
1 ЗагрузитьСценарий/Подключить нельзя использовать универсально?
2 ЗавершитьРаботуСистемы очень опасный инструмент, который лучше не юзать без блока проверки на стартовый сценарий???

какое-то кособокое использование получается :(

**Comment by artbear** [comment]
> Параметризированные исключения?

@nixel2007 я опять не понял, где тут разные коды возврата :)

**Comment by artbear** [comment]
Пример с тест-раннером:
я специально писал его так, чтобы мог натравить его на произвольный каталог и он должен выбрать тест-файлы и выполнить только эти файлы, а прочие пропустить.

сейчас я не могу это сделать, т.к. ЗавершитьРаботуСистемы в любом из скриптов ломает всю загрузку.

**Comment by EvilBeaver** [comment]
Это баг гитсинка. Он не должен вызывать завершение. Даже идеологически.

**Comment by pumbaEO** [comment]
@artbear   я не считаю что ЗавершитьРаботуСистемы необходимо как-то изолировать, такой же пример с 1С с завершением в коде внешней обработке приведет к завершению системы. 
Поэтому универсально не получится никогда. 
Можно хоть читать скрипт загрузки и там найти строку ЗавершитьРаботуСистемы и тогда не загружать этот скрипт.

**Comment by EvilBeaver** [comment]
Артур, я верно понял, что ты гитсинк.ос подключил через загрузить сценарий? И именно это проблема, что он так не работает?

**Comment by artbear** [comment]
Пишу с телефона, поэтому коротко.
Запустите 'oscript tests/Testrunner.os -runall .' в папке oscript-library и
посмотрите на результат.
Я пока наткнулся на гитсинк.

Предложение анализировать текст скрипта в рантайме перед запуском не
выдерживает никакой критики. Это какой же у нас фреймворк тогда?

Проблема в том, что я пооучил неожиданное завершение работы своего скрипта,
когда натравил его на список скриптов.
Я без движка не могу понять, упадет у меня мой код или нет. И сделать
ничего не могу, т.к.заранее это узнать нельзя.

Хотелось бы получить помощи от движка.

вт, 2 Авг 2016, 17:39 Andrei Ovsiankin notifications@github.com:

**Comment by pumbaEO** [comment]
Я считаю, что движок работает верно. И пинать надо авторов строк в gitsync (да и меня тоже, за это)

**Comment by EvilBeaver** [comment]
Нельзя подключать gitsync.os через ПодключитьСценарий. Это не библиотека, это exe-шник. Он считает, что он запустился как стартовый и работает себе. Нельзя требовать от него, чтобы он вел себя, как DLL, если он для этого не предназначен.

**Comment by EvilBeaver** [comment]
Не проблема движка. В формулировке, вынесенной в заголовок, бага нет.

**Comment by artbear** [comment]
Злые вы! :)
Ничего, будет и на нашей улице праздник :)
