### ISSUE TITLE
Добавить работу с почтой

### ISSUE THREAD

**Issue by gubanoff** [EvilBeaver/OneScript#319]
Добавить работу с почтой, возможно, через отдельную библиотеку.

**Comment by ret-Phoenix** [comment]
Реализовать отправку - особых сложностей нет, есть родное в .net.
Получение несколько сложней, в сети можно найти работу с POP используя сокеты, где-то даже либы встречал.

Что хочется увидеть в первую очередь от работы с почтой?

**Comment by JohnyDeath** [comment]
Как я понял, основная проблема - дублировать методы и свойства объектов почты из 1С

**Comment by ret-Phoenix** [comment]
Да, если по максимуму дублировать - много мороки. Если реализовать основные - уже не так проблематично. Отправку уж точно сделать не проблема. в том же MSDN есть примеры.

**Comment by EvilBeaver** [comment]
Принимаются предложения по улучшению этой мороки. Например, на входе синтакс помощник, на выходе код класса С# с пустыми телами методов. @awa15 и @bambr1975 умеют парсить синтакс-помощник.

**Comment by artbear** [comment]
@EvilBeaver Лучше день потерять, а потом за 5 минут долететь? :)

**Comment by EvilBeaver** [comment]
Именно. Мы же не только эти классы собираемся портировать. Там и джсон и двоичные данные и фтп. Даешь кодогенератор!

**Comment by gubanoff** [comment]
Re: [EvilBeaver/OneScript] Добавить работу с почтой (#319)

Здравствуйте, EvilBeaver/OneScript.

Вы писали 1 сентября 2016 г., 15:08:42:

Реализовать отправку - особых сложностей нет, есть родное в .net.
Получение несколько сложней, в сети можно найти работу с POP используя сокеты, где-то даже либы встречал.
Что хочется увидеть в первую очередь от работы с почтой?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

Отправка почты более приоритетна, чем получение. Можно начать только с отправки. 
Это будет полезно для отсылки на емейл отчета о результате работа скрипта, чтобы
можно было контролировать выполнился он или нет.

**Comment by artbear** [comment]
Да, для начала отправку бы реализовать.

**Comment by dmpas** [comment]
Почту взял кто-нибудь в работу?

**Comment by EvilBeaver** [comment]
@dmpas сделали специальный кодогенератор https://github.com/ret-Phoenix/ClassGenerator1CtoCSharp чтобы руками классы не создавать.

Но в работу не брали

**Comment by dmpas** [comment]
Ставлю себе в план на Октябрь. Кто раньше надумает - свистните!

**Comment by dmpas** [comment]
Посмотрел я это "родное в .net". SMTP-клиент отправлять, конечно, отправляет, но на этом он весь и заканчивается. Все эти ваши настройки SSL/TLS идут лесом - есть строго зашитый алгоритм, куда как соваться, и всё.

Пробую через сторонние наработки: https://github.com/jstedfast/MailKit
но там зависимостей на 4МБ, потому это лучше буду делать компонентой, а не в движок добавлять.

**Comment by dmpas** [comment]
office365 и mail.ru уже отправляют, яндекс и gmail пока ни в какую :(

**Comment by dmpas** [comment]
smtp работает: yandex, gmail, office365 и mail.ru поддались.
pop3 начал пилить.

ссылка на всякий случай: https://github.com/dmpas/oscript-mail.git

**Comment by EvilBeaver** [comment]
Ждемс!

**Comment by dmpas** [comment]
pop3 в первом приближении заработал. Берусь за IMAP.

**Comment by dmpas** [comment]
Запилил получение через IMAP: https://github.com/dmpas/oscript-mail/releases/tag/1.0.1

**Comment by EvilBeaver** [comment]
Можно утаскивать в библиотеку?

**Comment by dmpas** [comment]
Рано. Отправки через IMAP нет и зависимость от 15-й версии.

**Comment by nixel2007** [comment]
@dmpas пропиши версию среды в манифесте и можешь больше не переживать по этому поводу :)

**Comment by dmpas** [comment]
@gubanoff https://github.com/dmpas/oscript-mail/releases/tag/1.0.2

@EvilBeaver 
Предлагаю здесь задачу закрыть и все остальные вопросы решать в соответствующем хоронилище.
