### ISSUE TITLE
Виндовс10 ругается на установщик OneScript

### ISSUE THREAD

**Issue by vsuh** [EvilBeaver/OneScript#320]
![image](https://cloud.githubusercontent.com/assets/12156293/17600433/26a6067e-600c-11e6-9ab4-37869652a113.png)

```
Microsoft Windows [Version 10.0.14393]
```

**Comment by EvilBeaver** [comment]
Угу, на виндовс сервере тоже ругается. Надо поизучать что не так

**Comment by EvilBeaver** [comment]
Раньше такое сообщение было синим, а не красным. Про него пишут, что "приложение должно заслужить репутацию, прежде чем оно будет ставиться без предупреждения". Насчет красного сообщения ничего не сказано. То ли это особенность дизайна конкретной версии винды, то-ли это сбой в подписании MSI....

**Comment by EvilBeaver** [comment]
Положу ссылку, чтобы не потерять
http://stackoverflow.com/questions/38915281/why-windows-smartscreen-is-red-on-my-signed-installer

**Comment by fenixnow** [comment]
Оно может быть и желтым, в зависимости цветовой схемы виндовс :)

**Comment by fenixnow** [comment]
И ругается она из за того, что ей не нравится сертификат, и программа которая хочет внести изменения в системные переменные.

**Comment by EvilBeaver** [comment]
Это понятно. Непонятно, что именно ей не нравится в сертификате. Он выдан уважаемым центром сертификации, виден в свойствах файла... Будем рады любой конкретной информации - что можно поменять в подписи, чтобы она не пугала.

**Comment by fenixnow** [comment]
При беглом взгляде, в личном сертификате есть два предупреждения, возможно они, может истекающий срок сертификата.... тут нужно более пристально посмотреть.
Интересно, что при повторной установке, предупреждение на "красном" фоне не вылезло, а вылезло стандартное предупреждение контроля учетных записей

**Comment by nixel2007** [comment]
> программа которая хочет внести изменения в системные переменные.

в какие? системный PATH?

**Comment by EvilBeaver** [comment]
@nixel2007 да, пишет в системный. Но тут беда в другом. Это окно выдается еще до запуска инсталлятора. Она не знает, что и куда он будет писать, но уже сразу обзывает вирусом.

**Comment by Areso** [comment]
Это, в целом, бесполезно.
Уже неоднократно ругался и слил себе кучу кармы на Хабре, но всем плевать.
Гугл и МС используют немного разные алгоритмы, особенности они не разглашают (иначе, мол, хакерам будет проще), сводится к тому, что хэш-сумма загруженного файла отправляется на их сервер, затем, если после N загрузок и времени (недели-другой) компроментации не произошло, то всем остальным такую плашку уже не показывают.
Вплоть до того, что "этот файл редко скачивают, а потому он может быть опасен".

**Comment by EvilBeaver** [comment]
Тут дело в том, что на подписанный файл сразу ругается как на вредоносносный, а неподписанный - пишет редко скачивается, будьте осторожнее. Получается, что подписанные более опасны. За что боролись на то и напоролись, блин

**Comment by nixel2007** [comment]
Fuck logic

26 сентября 2016 г., 14:42 пользователь Andrei Ovsiankin <
notifications@github.com> написал:

**Comment by EvilBeaver** [comment]
Ну да. МС так старался перевести всех на подписанный софт, что теперь, когда это случилось - весь подписанный софт считает вредоносным. @dmpas прав, Линукс перешел от сборки исходников к пакетам, а винда скоро перейдет от пакетов к сборке из исходников.

**Comment by Areso** [comment]
Думаю, что они такими методами загоняют всех (и разработчиков и пользователей) в свой магазин приложений.

**Comment by EvilBeaver** [comment]
Отключено подписывание MSI
