### ISSUE TITLE
Различные типы переменных во внешнем соединении

### ISSUE THREAD

**Issue by vsuh** [EvilBeaver/OneScript#322]
```
Коннектор = Новый COMОбъект("v83.COMConnector");
Агент = Коннектор.ConnectAgent(Прм.ИмяСервера);
...
Сеансы = Агент.GetInfoBaseSessions(Кластер, ИнформационнаяБаза);
```

Количество сеансов в `OneScript` возвращает метод count() переменная имеет тип ComObject.
( _а как посмотреть набор свойств и методов у com-объекта в_ `OneScript`?)
В `1С` тип объекта `ComSafeArray` и количество нужно узнавать у `GetLength(0)` или `GetUpperBound(0)`

```
  РабПроц = Коннектор.ConnectWorkingProcess("tcp://"+Прм.ИмяСервера + ":" + Порт);
  СоединенияБазы = Агент.GetInfoBaseConnections(Кластер, ИнформационнаяБаза);
...
  РабПроц.Disconnect(Соединение);
```

вызывает в OneScript исключение 
_Несовпадение типов. (Exception from HRESULT: 0x80020005 (DISP_E_TYPEMISMATCH))}_

**Comment by EvilBeaver** [comment]
Ошибку вызывает метод Disconnect?
В 1Скрипте нет настоящего "ComSafeArray", а есть его обертка http://oscript.io/syntax/page/SafeArrayWrapper

Он строго одномерный, поэтому методы оригинала я не портировал. Но элементы этого массива и его самого можно передавать в методы Com-объектов. Ошибок быть не должно. В приведенном примере кода непонятно, какой тип имеет переменная "Соединение", передаваемая в `РабПроц.Disconnect` и сложно сказать, почему возник TYPE_MISMATCH

**Comment by vsuh** [comment]
Disconnect, да
, а как узнать тип у объекта в `onescript`? **ТипЗнч()** вернет `ComObject`.
`Соединение` является экземпляром коллекции `СоединенияБазы` которая получается из метода `GetInfoBaseConnections` агента.

**Comment by EvilBeaver** [comment]
В 1С такой код отрабатывает?

**Comment by vsuh** [comment]
Да, отрабатывет

**Comment by EvilBeaver** [comment]
@vsuh а можешь дать полный кусок кода, без многоточий, чтобы проще воспроизвести мне было?

**Comment by vsuh** [comment]
[clear-session.txt](https://github.com/EvilBeaver/OneScript/files/416544/clear-session.txt)

**Comment by vsuh** [comment]
offtop:
Кстати, зацените, как в vsc можно todoшки заводить и отмечать их как выполненные или отмененные. см. текст.

**Comment by EvilBeaver** [comment]
@vsuh вы получаете переменную Соединение из Агента. Она имеет тип "Описание соединения". Далее вы передаете ее в метод Disconnect рабочего процесса, а он хочет на вход переменную с типом "Соединение". Иными словами, тут закономерный TYPE_MISMATCH. Соединение для отключения нужно получать из метода _РабПроц.GetInfoBaseConnections(ИнформационнаяБаза)_ (см. строку 130)

**Comment by EvilBeaver** [comment]
@vsuh проблема ушла?

**Comment by vsuh** [comment]
Да, Андрей, спасибо.
Извините за задержку.
