### ISSUE TITLE
НайтиФайлы не находит файлов в подкаталогах - свежий баг 15 версии

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#324]
`МассивФайлов = НайтиФайлы(ФайлБиблиотек.ПолноеИмя, "*.os", Истина);` не находит файлов в подкаталогах 
В 14 релизе все работает.

на машине была установлена 14 версия, сегодня поставил ночник 15
сразу упали тесты моего проекта https://github.com/artbear/1bdd
установил обратно версию 14, все снова заработало

**Comment by artbear** [comment]
Исследовал ситуацию.
В 14 релизе `МассивФайлов = НайтиФайлы(ФайлБиблиотек.ПолноеИмя, "*.os", Истина);` возвращает файлы из подкаталога.
В ночнике 15 версии не возвращает.

**Comment by artbear** [comment]
Проверить исправление легко.
Открыть мой проект https://github.com/artbear/1bdd (ветку мастер или девелоп) в VSC
Выполнить команду `Tasks: Run Task`
выбрать `Exec all features`
Подождать 20-30 секунд.
Увидеть, что все фичи,сценарии и шаги пройдены, нет упавших или нереализованных.

Если есть нереализованные шаги, это баг.
Если прогон завершится в первые 5 секунд, это баг :)

**Comment by EvilBeaver** [comment]
Я в курсе, это дубликат. Завтра исправлю.
