### ISSUE TITLE
Полное имя внешнего исключения

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#325]
Предлагаю при возникновении внешнего исключения добавлять полное имя класса исключения:

```
{Модуль /.../checkwsdl.os / Ошибка в строке: 14 / Внешнее исключение (System.NotImplementedException): WSProxy.[Call]}
{Модуль /.../checkwsdl.os / Ошибка в строке: 6 / Внешнее исключение (System.Net.WebException): Error: NameResolutionFailure}
```

**Comment by EvilBeaver** [comment]
Согласен. На всякий случай, напомню, что в информацииОбОшибке есть метод, выдающий полный текст ошибки, вместе со стеком вызовов CLR
