### ISSUE TITLE
Вынести операции с IValue

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#326]
Вынести операции с `IValue` из `MachineInstance` в публичные статические методы (`ValueFactory`, к примеру) для использования компонентами.

**Comment by EvilBeaver** [comment]
Какие именно?

**Comment by dmpas** [comment]
Add, Sub, Mul, Div, Mod, Neg.

**Comment by EvilBeaver** [comment]
А можешь привести пример использования внутри компоненты? Просто в машине же эти операции активно используют главный стек, не совсем ясно, как и, главное, зачем это нужно выносить?

**Comment by dmpas** [comment]
да мне не нужен стэк и всё такое. Вот ты извлёк из стэка два `IValue` и потом начинаешь смотреть их `DataType` и в зависимости от него отрабатывать операцию. Вот эту проверку и само вычисление я предлагаю вынести и опубличить. Не трогая стэк.

Есть у меня некоторый вычислятор, в нём формула заложена. В формулу я из пользовательского кода передаю несколько `IValue`, в формуле делаю сложение, вычитание - всё такое.

То есть, не всю процедуру `Add`, а только ту часть, где непосредственно расчёт `IValue` идёт.

**Comment by EvilBeaver** [comment]
Ну так-то я понял, да. Ок, давай сделаем. Возьмешь?

**Comment by dmpas** [comment]
ага.
