### ISSUE TITLE
Создать генератор классов на основе данных СП

### ISSUE THREAD

**Issue by ret-Phoenix** [EvilBeaver/OneScript#328]
Продолжение: https://github.com/EvilBeaver/OneScript/issues/319#issuecomment-244100899

**Comment by ret-Phoenix** [comment]
Накидал [вариант](http://itpath.ru/downloads/class-gen-1c-csharp.rar)

**Comment by awa15** [comment]
@ret-Phoenix , отлично!
На всякий случай уточню, если вдруг кто не понял, обработка, приложенная @ret-Phoenix , предназначена для базы 1С отсюда https://bitbucket.org/awa15/metaread

**Comment by EvilBeaver** [comment]
@bambr1975 а для VisualStudio Code синтакс-помощник из этой же базы генерится?

**Comment by bambr1975** [comment]
нет, из https://gitter.im/xDrivenDevelopment/1c-syntax?at=57ac419046610f1739516a51

**Comment by EvilBeaver** [comment]
А это разве не идентичная по метаданным база?

**Comment by awa15** [comment]
Это та же самая база. Просто https://bitbucket.org/awa15/metaread раньше был закрыт. Я сегодня там тоже обновлю типы до 8.3.9.

**Comment by ret-Phoenix** [comment]
Андрей, на начальной стадии генерируемый код подойдет? если есть предложения - пиши, сегодня/завтра думаю смогу заняться.

**Comment by EvilBeaver** [comment]
@ret-Phoenix да. Не хватает только генерации using и прочего, ну это дело техники уже. Спасибо!

**Comment by awa15** [comment]
Мои замечания по текущей реализации:
1. Не обрабатываются конструкторы.
2. Имена параметров методов выводятся по-русски

``` c#
[ContextMethod("Записать", "Write")]
public void Write( IValue Буфер, IValue ПозицияВБуфере, IValue Количество)
{

}       
```

```
```

**Comment by EvilBeaver** [comment]
@ret-Phoenix заводи репо с прекоммитом (разбором на исходники EPF). Если подумать, то там же нужна типизация, хотя бы простых типов вместо IValue. А в идеале - генерация N файлов по количеству типов, рекурсивно.

Например, ТаблицаЗначений зависит от СтрокаТаблицыЗначений, КоллекцияКолонокТаблицыЗначений, КолонкаТаблицыЗначений и пр. По кнопке генерить все зависимости можно.

Сообща одолеем.

**Comment by ret-Phoenix** [comment]
@awa15 Конструкторы пока не обрабатываются, сделаю в ближайшие дни.
"2. Имена параметров методов выводятся по-русски" в базе есть имена параметров на английском? я не нашел этого (

@EvilBeaver Простую типизацию сделаю, скорее всего завтра.
Генерировать с учетом зависимостей - тоже думал, но пока решил не делать. сейчас можно легко сделать выбор нескольких типов для создания классов, именно поэтому в генераторе и передается тип как параметр, а не берется из реквизита )

**Comment by awa15** [comment]
@ret-Phoenix , сорри, имен параметров методов на английском в базе действительно нет. Потому что в русском синтакс-помощнике указаны и русские и английские имена типов, свойств, методов, а вот имена параметров методов указаны только русские. А разбираю я, естественно, именно русский синтакс-помощник. Я подумаю об этом))

**Comment by ret-Phoenix** [comment]
@awa15  в порядке бреда, а может есть какой полностью англоязычный вариант платформы? и оттуда скомуниздить...

**Comment by ghost** [comment]
@ret-Phoenix я разворачивал Win7x64en - без русского языка от слова совсем и тогда все было на английском, если ставить платформу через Далее-Далее-Далее. Насколько я помню - есть язык платформы, язык конфигурации и язык информационной системы. Их сочетание и влияет.

**Comment by EvilBeaver** [comment]
На данном этапе и русских параметров за глаза. Это же файл-заготовка. Реализатор так или иначе будет работать с кодом и поправит. Все лучше, чем сейчас

**Comment by awa15** [comment]
Почему бред? Есть английский синтакс-помощник. Только у него формат отличается тем, что там не указаны имена на другом языке (русском), и текущая загрузка не сможет это обработать. Да и для генератора нужны имена на обоих языках. Т.е. нужно как-то совместить оба синтакс помощника. Об этом я собирался подумать))

**Comment by awa15** [comment]
@allustin , чтобы увидеть английский синтакс-помощник, достаточно запустить конфигуратор с ключем /Len

**Comment by ret-Phoenix** [comment]
совместно с @bambr1975 чуток допилил OneScriptDocumenter, сейчас планах сделать словарь для типов 1С и C# реализаций из OneScript (ArrayImp = Массив, ValueTable = ТаблицаЗначений и т.д.). Задача сводится к замене полного пути на C# класс типом из 1С.

Этот словарь пригодится и здесь, но работающий в обратную сторону, таким образом можно будет при типе, например, Массив сразу подставлять ArrayImp, в using само собой попадет путь до library.

**Comment by ret-Phoenix** [comment]
@EvilBeaver Репозиторий создал: https://github.com/ret-Phoenix/ClassGenerator1CtoCSharp

**Comment by EvilBeaver** [comment]
> совместно с @bambr1975 чуток допилил OneScriptDocumenter

@ret-Phoenix А где допилки, пулреквесты?

**Comment by ret-Phoenix** [comment]
Пока нет, но думаю скоро будут )
Сейчас код вообще не причесан, как добавлю что хотим, причешу хоть чуток - поделимся )
