### ISSUE TITLE
Расширение функциональности ZIP из версии 8.3.9

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#329]
В версии 1С:8.3.9 добавлена следующая возможность:

Имена файлов в zip-архиве записываются в кодировке UTF8.
Для конструктора объекта ЗаписьZipФайла и метода этого объекта Открыть() реализованы параметры позволяющие управлять кодировкой имен файлов в zip-архивах. Значения вышеуказанных параметров имеют приоритет над значением параметра FileNamesEncodingInZipFile файла conf.cfg.
Для параметра FileNamesEncodingInZipFile файла conf.cfg, значением по умолчанию является значение UTF8.
В режиме совместимости с версией 8.3.8 поведение не изменилось.

**Comment by artbear** [comment]
Непонятно, что именно ты предлагаешь :)
сделать новую функциональность, отказавшись от старой? или сделать совместимость? или ... ?

**Comment by EvilBeaver** [comment]
Совместимость с 8.3.9

**Comment by JohnyDeath** [comment]
@EvilBeaver а как ты хочешь поддерживать режимы совместимости в 1Скрипт? Вводить глобальную переменную?
Или я неправильно понял и переезжаем сразу на вариант, который использует платформа в версии 8.3.9?

**Comment by EvilBeaver** [comment]
Конечно. Просто добавляем функциональность, которая появилась в 839
