### ISSUE TITLE
Ошибка при вызове глобальной процедуры из внешней компоненты

### ISSUE THREAD

**Issue by alexkmbk** [EvilBeaver/OneScript#330]
При попытке вызова глобальной процедуры из внешней компоненты, на строке вызова выходит следующая ошибка:
_Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index_

Прикладываю пример проекта, на котором воспроизводится ошибка. В нем реализована глобальная функция Предупреждение.
Пример вызова:
# Использовать dialogs

Предупреждение("Привет!");

Каталог с библиотекой:
[dialogs.zip](https://github.com/EvilBeaver/OneScript/files/468990/dialogs.zip)

Проект на VisualStudio:
[StandardDialogs.zip](https://github.com/EvilBeaver/OneScript/files/468993/StandardDialogs.zip)

Ошибка воспроизводится на версиях 1Script 1.0.14 и 1.0.15

**Comment by EvilBeaver** [comment]
@dmpas ты вроде пробовал делать глобальные в компонентах. Работало?

Я посмотрел, там есть проблема, просто уточнить - ты на нее натыкался?

**Comment by dmpas** [comment]
@EvilBeaver нет, не натыкался. да и не делал вроде :)
