### ISSUE TITLE
Неразрешённая зависимость DEB-пакета

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#331]
Проблема обнаружена в Ubuntu 16, Mint 18: нет libmono-corlib4.0

**Comment by EvilBeaver** [comment]
Они выкинули моно из реп? Или пакет переименовали?

**Comment by dmpas** [comment]
конкретно `libmono-corlib4.0` нет конкретно в убунту 16, в репах. `libmono-system4.0`, другие пакеты для 4.0 есть, а вот корлиба 4.0 по неведомой мне причине нет. Только 4.5.

**Comment by ret-Phoenix** [comment]
На Ubuntu 16 (x32) OneScript запустился.

**Comment by alexkmbk** [comment]
А не связано ли как то остутствие корлиба с появлением .Net Core от Microsoft под Linux?

**Comment by dmpas** [comment]
@alexkmbk думаю, что нет. корлиб 4.5 же есть и работает вместо 4.0.

**Comment by dmpas** [comment]
@EvilBeaver будет возможность пересобрать пакеты для старых версий?

**Comment by EvilBeaver** [comment]
А зачем?

**Comment by dmpas** [comment]
чтобы не только ночную сборку можно было скачивать и устанавливать, но и последнюю 14 хотя бы.
