### ISSUE TITLE
РегулярноеВыражение.Группы[1].Значение определяется без учета свойства ИгнорироватьРегистр объекта РегулярноеВыражение

### ISSUE THREAD

**Issue by bambr1975** [EvilBeaver/OneScript#333]
https://yadi.sk/d/372pKOLSvdwbQ
По ссылке лежит скрипт FilterValue.os - отличный скрипт от ret-Phoenix, использующий лежащий рядом с ним oscript-simple-gui.dll, хорошо работает, все в порядке. Там возникла проблема в 21, 23, 25 строке, которые сейчас закомментированы. Почему-то если их раскомментировать, перестанут определяться написанные с маленькой буквы "о", "д" и "т" (которые в словах в списке написаны с большой буквы).

**Comment by EvilBeaver** [comment]
@artbear, ты автор регекспов, тебе и кнопки в руки. Я в них ни бум-бум.

**Comment by dmpas** [comment]
Проверил. У меня по-другому: просто перестаёт восприниматься первая буква слов, но поиск идёт и без учёта регистра. То есть, по строке поиска "А" находится "Два".

**Comment by dmpas** [comment]
Вот с такой регуляркой работает:

``` bsl
РегВыражение = Новый РегулярноеВыражение("(?:.*)(" + СтрПоиска + ")(?:.*)");
```

**Comment by bambr1975** [comment]
Получается, что синтаксис не взаимозаменяемый? В основу взято ICU?

**Comment by EvilBeaver** [comment]
@bambr1975 думаю, что заменяемый, вопрос только в настройках парсера. За основу взято то, что есть в .net. Не знаю, на чем там основано. Есть вероятность, что совместимо с COM-объектом, который ты используешь в V8Reader

**Comment by artbear** [comment]
Я брал тот парсер, что по умолчанию в .net

@bambr1975 @ret-Phoenix а нет прямой ссылки на этот скрипт в каком-нибудь репозитории? сразу на гитхабе или еще где посмотреть?

**Comment by ret-Phoenix** [comment]
Только на github, скрипт писался как поимер работы библиотеки. И потом хотел использовать его в v8Ahk

**Comment by artbear** [comment]
@ret-Phoenix Адрес?

**Comment by ret-Phoenix** [comment]
https://github.com/ret-Phoenix/oscript-simple-gui/blob/master/bin/src/FilterValue.os

**Comment by EvilBeaver** [comment]
@bambr1975 проблема ушла?

**Comment by bambr1975** [comment]
Не было проблемы. Все в порядке))) Нужно почаще перечитывать MSDN)))
