### ISSUE TITLE
Недоработки в документации

### ISSUE THREAD

**Issue by fenixnow** [EvilBeaver/OneScript#334]
Набрел на ваш проект, решил протестировать, установил через рекомендованный установщик в операционную систему Win10. Запускаю командную строку, oscript - получаю, что это не является исполняемой командой. http://oscript.io/docs/page/install - действие после установки - ничего толкового не говорит. 

Далее...
Рассмотри ситуацию с работой библиотеки http://oscript.io/library/package/gitsync 
Ручная установка - скопировать.... - откуда??? 
аналогично и с автоматической установкой....

Пичалька, что "возможно" хороший продукт подан отвратительно. Возможно кому-то и интересно разгадывать квесты и ребусы?

http://oscript.io/dev/contribute но если вы хотите помочь проекту, указать явные ошибки - мы принимаем помощь в доработке и раскрутки сайта - пишите не деревню дедушке и шлите в толстом конверте, чтобы не помялось.... даже тут куча загадок.

Если делаете публичный проект, делайте его плиз для людей....

**Comment by rsyuzyov** [comment]
Странно, мне как пользователю казалось, что парни его как-раз для людей сделали, да и сами они, в общем-то, гуманоиды :). Давайте попробуем немного помочь проекту в плане "для людей". По первому пункту: удалось разобраться? Причина была в path или в чем-то другом?

**Comment by fenixnow** [comment]
Я не знаю в чем причина в пути или еще в чем то, возможно инсталятор не отрабатывает...

**Comment by EvilBeaver** [comment]
Добрый вечер. Ваша критика понятна, но хотелось бы все же получить больше конструктива. Так мы сможем понять, что именно у вас происходит и как вам помочь.

Например, установка. При установке путь к oscript.exe прописывается в переменную PATH. Что у вас там написано? Установщик не прописал, или вы пробовали запускать в окне cmd, которое было открыто до установки? Во втором случае, оно не увидит изменений, его надо перезакрыть. Ну и т.п. Исправление ошибок может быть эффективным, только при наличии конкретики.

Идем дальше. На сайте дана ссылка на мою личную почту. Написано, "пишите EvilBeaver", никаких деревень и дедушек. Кроме того, есть ссылки на гитхаб, чат gitter и прочее. Предложите, если не сложно, текст, который будет более понятен.

Про gitsync и работу с ним - отдельный проект, https://github.com/oscript-library/gitsync. Как скачать архив кода с гитхаба надо объяснять?

> Если делаете публичный проект, делайте его плиз для людей....

Я не покривлю душой, если скажу, что мы делаем его для себя. Для решения личных задач на рабочих местах. Отдавая его людям мы делимся тем, что полезно лично нам. Мы принимаем пожелания, а особенно - доработки от тех, кому проект пригодился. Да, нам не всегда удается написать внятную документацию. Вы могли бы помочь, перефразировав что-либо или написав. Это и будет "работа для людей". Попробуйте.

**Comment by fenixnow** [comment]
по первому пункту, скачал установщик, http://oscript.io/downloads/latest/exe согласился, что ничего не сломается и нажал установить.
путь в системных переменных походу отсуствует. Давайте в установке напишем, что там должно быть по умолчанию для винды чтобы возможно было понять и дописать руками.

Про вашу почту написано в первом абзаце, про доработку сайта, это уже предпоследний абзац, по мне, нужно информацию предоставлять по тексту.

Про гитсинк, он есть в папках libs/ как понимаю скачивать ни откуда не нужно (это при установке .exe)

Я тоже стараюсь делать для людей, но незнаю или наша широкая душа или еще что то мешает концентрироваться на деталях, размазывая все.

Чтобы помочь с чем-то нужно сначала это что-то понять и пощупать :)

**Comment by EvilBeaver** [comment]
Нажмите, пожалуйста Win+R, введите cmd, и приведите, пожалуйста, результат команды:

```
echo %PATH%
```

**Comment by rsyuzyov** [comment]
И неплохо бы уточнить: консоль была открыта до установки, или после?

**Comment by EvilBeaver** [comment]
@rsyuzyov я про это уже спросил. Нужна свежая консоль.

**Comment by fenixnow** [comment]
сейчас будет

**Comment by rsyuzyov** [comment]
Ога, но ответа вроде не было?

**Comment by fenixnow** [comment]
![2016-09-25_222206](https://cloud.githubusercontent.com/assets/13418562/18817663/ecf1d922-836e-11e6-9324-f616bb94f417.jpg)

**Comment by fenixnow** [comment]
консоль была закрыта, было закрыто все, кроме гугл хрома

**Comment by EvilBeaver** [comment]
Перепроверил. Удалил oscript из PATH, переустановил инсталлятором exe. oscript прописался в PATH.

Win 10 свежайшая. Видимо, какие-то особенности вашей системы не позволяют инсталлятору сработать штатно. Коллеги, есть предположения?

**Comment by fenixnow** [comment]
можете ткнуть на строкчку в проекте, которая вносит этот параметр

**Comment by rsyuzyov** [comment]
@evilbeaver, завтра уточню - кажется было такое как-то, но почему не помню
@fenixnow, а в свойствах системы если посмотреть path - там тоже пути к катологу onescript нет? Если нет - можно пока добавить руками в пользовательскую переменную

**Comment by EvilBeaver** [comment]
https://github.com/EvilBeaver/OneScript/blob/develop/install/install.iss#L64-L65

Это непосредственно запись в реестр.

https://github.com/EvilBeaver/OneScript/blob/develop/install/install.iss#L94-L108

Это функция проверки того, что надо вносить запись в реестр. (проверяет, что путь к 1script там уже есть)

**Comment by fenixnow** [comment]
скорее тк пишется в сессию, которая уже начата, запись из реестра не подхватывалась, хотя и присуствовала там, выход и вход пользователя решил проблему.

В документации нужно пометить, что происходит запись в реестр в переменную "path" Если системе не удается обратиться к oscript, то требуется перезаход в систему.

И последний вопрос на сегодня (читать буду завтра) почему не используете WIKI github?

**Comment by EvilBeaver** [comment]
> почему не используете WIKI github

так сложилось.

> Если системе не удается обратиться к oscript, то требуется перезаход в систему.

Вообще-то нет. Переменные подхватываются сразу при старте процесса. Если у вас cmd.exe был запущен до установки, то он прочитает новые значения при повторном запуске.

Наверное, explorer также себя ведет, если консоль открывали из проводника, а не через Win+R

**Comment by pumbaEO** [comment]
Для винды не всегда перезапуск cmd применит переменную patch, перезагрузка точно поможет.

**Comment by EvilBeaver** [comment]
@pumbaEO интернеты пишут, что окружение всегда считывается с нуля при старте процесса. Другое дело, что процесс может быть запущен, как дочерний. Тогда он наследует окружение родителя (а оно могло устареть)

Скажем, если я запускаю Total Commander, потом меняю окружение, потом запускаю 2 cmd. Первый - из тотала, второй обычный через Win+R. Тот который из Тотала будет со старым окружением, т.к. Тотал запускает cmd дочерним себе.

**Comment by rsyuzyov** [comment]
Уточнил у камрада: он спотыкался на том, что на win7 и win2008r2 при отключенном uac path обновлялся только после перевхода, с включенным uac все  ок. На win 10 у меня не воспроизводится, а времени на вдумчивое курение такой херни как-то жалко...

**Comment by fenixnow** [comment]
недоработки документации плавно переросли в другую проблему :)
