### ISSUE TITLE
Реализовать отключение использование небезопасных обращений

### ISSUE THREAD

**Issue by deniznet** [EvilBeaver/OneScript#336]
Идея использовать OneScript как скриптовый движок в проектах для реализации динамических вычислений на стороне сервера для пользователей. Например, проект требует реализации вычислительных процедур на стороне сервера, которые создают сами пользователи сайта. В планах реализовать это на OneScript, однако, возникает вопрос о безопасности. На Java в ScriptManager это реализуется правами. В PHP на V8 тоже есть проблемы безопасного использования. При использовании OneScript хотелось бы иметь быстрое отключение всех небезопасных вызовов, чтобы код можно было использовать только выполнения вычислительных процедур работу с массивами структурами, но отключить обращение к файлам, сети, к среде окружения.

**Comment by EvilBeaver** [comment]
Можете привести пример такого алгоритма, который бы не требовал обращения к машине, но был все же полезен человеку, размещающему его в облаке?

**Comment by deniznet** [comment]
Абстрактный пример, в базе/приложении есть значения различных параметров (от физических величин до финансовых показателей). Заранее не известен (мы даем определять пользователю самому) алгоритм расчета какого-то другого важного значения, которые затем должен быть сохранен в базе и использоваться позже. При этом заранее все возможные алгоритмы предположить не можем, но сам алгоритм запускается часто и по различным событиям.
Более конкретный. Есть ответы на вопросы испытуемых, нужно заложить в базу алгоритм их обработки, чтобы вычислить новую характеристику испытуемого. Поэтому алгоритм нужно хранить вместе с анкетой в базе, так как анкет может быть много, и пользователю (создающему анкету) нужно дать возможность написать алгоритм обработки самостоятельно. На клиент нельзя обработку отправить (например в JavaScript), так как не хотим, чтобы испытуемый подглядел алгоритм обработки или фальсифицировать значение расчетной характеристики. 
Фактически нужно дать возможность выполнять расчетные задачи, обращаться к массивам, структурам и т.д., но отключить все небезопасное (обращаться к COM, файлам, сеть и т.д.), чтобы можно было запускать на стороне сервера, то есть использовать OneScript в проекте например на PHP как скриптовый серверный движок.

**Comment by dmpas** [comment]
@deniznet разверните docker-контейнер, в котором будете запускать односкрипт под пользователем с никакими правами.

Ещё можно сделать свою усечённую сборку проекта HostedScript.

Для прикручивания настраиваемой политики безопасности на уровне движка пока нет совершенно никакого понимания, как, что, куда, зачем, в каком виде.

**Comment by pumbaEO** [comment]
А в докере можно еще ограничить по ресурсам, что-бы 100% проца не забирало.

**Comment by EvilBeaver** [comment]
@deniznet присоединюсь к коллегам. Вопросам хостинга кода не один уже десяток лет. Практически все решается инфраструктурными средствами - выделением квот и правами доступа.

**Comment by EvilBeaver** [comment]
не до конца понятен сценарий и требования. Отложим.
