### ISSUE TITLE
На CI не работает компиляция новых конструкций языка

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#338]
Нововведения языка C# не компилируются на сервере сборок. Требуется настроить.

**Comment by EvilBeaver** [comment]
@dmpas я не перешел на сборку в VS2015 поскольку бинарники, которые она создавала, не работали в Моно. Новые фичи языка будут работать только в компиляторе от VS2015.

Можешь проверить на свежем Моно - будет ли работать dll, полученная сборкой для VS2015? Если да, то я переключусь и будет счастье.

**Comment by EvilBeaver** [comment]
P.S. бинарники от VS2015 будут в ночной сборке через 5-6 минут.

**Comment by dmpas** [comment]
@EvilBeaver ага, жду.

**Comment by dmpas** [comment]
ну как бы, под убунтой я ж собираю те же самые исходники. То есть, 6-й шарп моно знает. Дело в платформе - 4.6 под моно до сих пор нет, но 4.0 и 4.5 должны спокойно запускаться.

**Comment by EvilBeaver** [comment]
Готово. Хотя, чего это я... тесты же под Линуксом на CI прошли, значит работает. Я точно помню, что падало, но какой в этот момент был Моно уже не скажу.

**Comment by dmpas** [comment]
@EvilBeaver deb с сайта работает; deb, собранный на месте из зипа, тоже работает.

```
$ mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
```

**Comment by dmpas** [comment]
в репах убунты до сих пор третий моно. скорее всего, в этом затык был. то есть для хорошего годного моно надо подключать репы с их сайта.

**Comment by EvilBeaver** [comment]
@dmpas Спасибо!
