### ISSUE TITLE
Использовать "." перестало загружать классы

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#340]
main.os

``` bsl
#use "."
A = new class1;
```

Классы\class1.os

```
Procedure DoNothing() Export
EndProcedure
```

Односкрипт 1.0.14.167 загружает и не ругается, текущий ночник выдаёт 

```
Ошибка в строке: 2 / Внешнее исключение (System.Collections.Generic.KeyNotFoundException): Данный ключ отсутствует в словаре.
```

**Comment by EvilBeaver** [comment]
Чорт.... у меня не воспроизводится((( Копаю.

**Comment by nixel2007** [comment]
@EvilBeaver 
Воспроизвелось на запуске `opm` из командной строки. осркипт - сегодняшний ночник.

**Comment by EvilBeaver** [comment]
в опм да, а локализовать пока не смог. Хочу сделать тест движка, но не получается

**Comment by dmpas** [comment]
А без package-loader сработает?

**Comment by EvilBeaver** [comment]
@dmpas не понял вопроса

**Comment by dmpas** [comment]
В тесте в customlib есть package-loader. С ним в таком виде работало и до этого. А вот без него работало только в 14.

Домой приеду, посмотрю исправление точнее
