### ISSUE TITLE
Чистить созданные временные файлы при завершении процесса скрипта

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#341]
Как считаете, нужно это делать? 1С чистит это дело самостоятельно.

**Comment by nixel2007** [comment]
Не всегда это нужно, к сожалению. Для целей отладки, например, важно после выполнения скрипта посмотреть какие где файлики остались и их содержимое.

**Comment by EvilBeaver** [comment]
Ну это можно решить какими нибудь гл. методами типа ПолитикаУдаленияВременныхФайлов.НеУдалять

**Comment by EvilBeaver** [comment]
А еще лучче - добавить событие ПриЗавершенииРаботыСистемы и там делать что нужно.

**Comment by dmpas** [comment]
Движок должен сам по-умолчанию удалять временные файлы. Простые вещи должны делаться просто, а если в каждый второй скрипт впиливать ПриЗавершенииРаботыСистемы одинакового содержания - это никуда не годится.

Неудаление временных файлов, как мне кажется, лучше делать через переменные среды: поставил перед запуском скрипта что-нибудь вроде OSCRIPT_DONOTCLEARTEMP=1 и внутренний менеджер временных файлов ничего не удалит.

Самому скрипту ведь не может понадобиться неудаление временных файлов после своего завершения - верно? Это вопрос внешнего вызывающего процесса. Соответственно, извне это и должно задаваться.

**Comment by artbear** [comment]
Автоудаление временных файлов - это все-таки прикладная часть.
В движок не нужно закладыватт.
А вот если бы деструктор был бы ;) или хотя бы обработчик завершения
работы, тогда мы сразу бы добавили в прикладной класс временных файлов эту
функциональность

ср, 5 Окт 2016, 20:35 Sergey Batanov notifications@github.com:

**Comment by EvilBeaver** [comment]
@artbear ну в 1С это НЕ прикладная часть и ВФ чистит платформа. Но я не вкурил, как именно она это делает, т.к. делает она это при старте, а не при завершении.

**Comment by artbear** [comment]
1с это не скриптовая система. У нее другое поведение

ср, 5 Окт 2016, 22:38 Andrei Ovsiankin notifications@github.com:

**Comment by artbear** [comment]
Будем голосовать?
/cc @EvilBeaver @nixel2007 @dmpas @pumbaEO

**Comment by dmpas** [comment]
@artbear варианты голосования подскажи. я смутно представляю, за что именно сейчас мы будем голосовать.

**Comment by pumbaEO** [comment]
Временные файлы на то и временные, что-бы о них заботилась ОС. Имхо, запоминать oscript-у что он там создавал, не вижу смысла. 
Сам разработчик нагадил, сам убрал. Чисто не там где убирают, а там где не сорят.

**Comment by dmpas** [comment]
@pumbaEO 

> Чисто не там где убирают, а там где не сорят

оно как бы да, но уборщица в офисе - это очень здорово всё-таки :)

**Comment by artbear** [comment]
Пока вижу 3 варианта голосовалки:
- [ ] удалять временные файлы движком после завершения работы скрипта
- [x] 1скрипт никак не следит за временными файлами
- [ ] свой вариант

Свой вариант я отметил

**Comment by artbear** [comment]
> Временные файлы на то и временные, что-бы о них заботилась ОС. Имхо, запоминать oscript-у что он там создавал, не вижу смысла. 

Согласен с @pumbaEO

**Comment by artbear** [comment]
А еще попробуйте ответить на вопрос - что такое временные файлы? :)
как движок может определить, какой файл временный, а какой нет :) ?

**Comment by dmpas** [comment]
@artbear ну, собственно, указание на временность файла должно явно быть прописано в конечном скрипте. Делаешь ПолучитьИмяВременногоФайла и все понимают, что этот файл на выходе из твоего чёрного ящика никому не нужен.

Вместо голосовалки лучше задам другие вопросы (типа "свой вариант"):
1. Надо ли удалять временные файлы?
2. Надо ли удалять их автоматически?
3. Кто это должен делать автоматически?
4. и как и откуда этот кто узнает, что файл временный и более никому не нужен?

**Comment by EvilBeaver** [comment]
Идеологически я согласен с @dmpas. Временные файлы не нужны после работы процесса, за исключением каких-то редких моментов. По вопросам:
1. Нужно
2. Нужно
3. Фиг знает, полагаю, что движок.
4. Зависит от ответа на вопрос 3.

**Comment by artbear** [comment]
@EvilBeaver Исходя из части ответа "3. полагаю, что движок."
Дай ответ на "4. и как и откуда этот кто (движок!) узнает, что файл временный и более никому не нужен?"

**Comment by EvilBeaver** [comment]
Движок как раз узнает просто. Метод получить имя временного файла говорит о том что файл временный и нужен только работающему коду. Как только код завершен файл не нужен. А если был бы нужен, то он копируется куда-то в более внятный каталог, нежели дебри tmp

**Comment by pumbaEO** [comment]
А я получаю имя временного файла, отрезаю у него расширение и создаю временный каталог.

**Comment by EvilBeaver** [comment]
А расширение-то зачем отрезать? Я тоже так делаю, но с этим не заморачиваюсь.

**Comment by dmpas** [comment]
тру-стори из гетто. не далее, чем на той неделе возникло вот такое недоразумение: обработка обмена от сторонних разрабов (1) качает zip-ку, (2) распаковывает файл в темпы, (3) пытается грузить - падает.

Вот, 1С эти файлы сама не удаляла, обмен запускался раз в 5 минут, а распакованные файлики весили по 80МБ - это по гигу в час кушалось. Разумеется, никто не заметил и место неожиданно закончилось.

Мораль: дворник нужен не потому что я - свин, а чтобы за другими негодяями было, кому убрать.

**Comment by ghost** [comment]
@dmpas у нас было такое же - внезапно стала тормозить 1С, начали копать (Документооборот). Место было с избытком, однако прям тормозило и прям на сервере. 

Начали разбираться открыли %TMP% - а проводник Windows ее вообще не открыл и завис: более миллиона временных файлов. Пришлось делать `delete /all` - прям из консоли. Вообще это беда Документооборота - чистить за собой файлы программно. А платформа - если переменная файл вышла за область видимости и не содержит ссылок - переменную грохает, а вот файл то остается. объекта БезопасныйВремменныйФайл - такого нет.

@EvilBeaver а разве прям 1С чистит временные файлы ? Которые программно созданы ?

**Comment by nixel2007** [comment]
>  а разве прям 1С чистит временные файлы ? Которые программно созданы ?

@allustin вроде во всех книжках 1сных написано, что да, чистит файлы, полученные через ПолучитьИмяВременногоФайла().

**Comment by pumbaEO** [comment]
при перезапуске сервера чистит?

**Comment by dmpas** [comment]
> при перезапуске сервера чистит?

= "не чистит вообще". или "чистит, когда рухнет от нехватки места"

**Comment by nixel2007** [comment]
вроде бы при завершении сеанса, разве нет?

**Comment by EvilBeaver** [comment]
@nixel2007 я не помню документации, где бы говорилось когда именно чистит. Опытным путем устанавливал, что при закрытии 1С (файловой) не чистит, а при повторном старте - чистит. На сервере не экспериментировал. И было это сто лет назад, могло поменяться.

**Comment by EvilBeaver** [comment]
Синтакс-помощник:

> Если файл не будет удален средствами встроенного языка, он будет удален платформой при следующем запуске.
> Рекомендуется удалять временный файл самостоятельно после его использования, т.к. при активном создании файлов временные файлы могут занять значительную часть дискового пространства раньше, чем произойдет перезапуск платформы. 
> Данная рекомендация особенно актуальна для кода, исполняемого на сервере, так как регламент его эксплуатации может не предполагать регулярного перезапуска. 

Т.е. на сервере чистит при рестарте аж сервера, но никак не сеанса.

**Comment by EvilBeaver** [comment]
Подниму тему. Чо как?

**Comment by artbear** [comment]
Меня и @nixel2007 текущее положение дел устраивает, насколько я понимаю.
Каждый скрипт разруливает сам.

**Comment by EvilBeaver** [comment]
Ок, закрываю до тех пор, пока не понадобится
