### ISSUE TITLE
параметр использовать НЕ  безопасные заголовки для HTTP соединения

### ISSUE THREAD

**Issue by ghost** [EvilBeaver/OneScript#343]
бывает что внешний сервис неверно устанавливает заголовки ответа

тогда мы получаем исключение

```
(System.Net.WebException): Сервер нарушил протокол. Section=ResponseStatusLine}
```

workaroud описан тут http://www.cookcomputing.com/blog/archives/000556.html
и [более подробно тут](https://social.msdn.microsoft.com/Forums/ru-RU/7a2c28e4-c9b8-4d3c-98a1-45b5b0b0e0a4/-systemnetwebexception-?forum=fordesktopru)

нужно как то пробросить возможность установки свойства

``` csharp
[ConfigurationPropertyAttribute(useUnsafeHeaderParsing, DefaultValue = false)] 

public bool UseUnsafeHeaderParsing 
{ 
    get;
    set;
} 

```

предполагаю что скорее всего где-то тут https://github.com/EvilBeaver/OneScript/blob/36c8480caaa342d2b827c210f49966be42ffcc34/src/ScriptEngine.HostedScript/Library/Http/HttpConnectionContext.cs#L24

Ожидаемый код 1С

``` bsl
// тут где-то инициализация соединения
соединениеHTTP.ИспользоватьНеБезопасноеЧтениеЗаголововков = Истина;
```

P.S. Чтобы вы понимали - это на API.github выловлено.

/сс @nixel2007

**Comment by dmpas** [comment]
А пример неработающего кода можно? Так было бы проще.

**Comment by nixel2007** [comment]
@dmpas 

``` bsl
Сервер = "https://api.github.com";
Соединение = Новый HTTPСоединение(Сервер);

Ресурс = "/orgs/oscript-library/repos";
Заголовки = Новый Соответствие();
Заголовки.Вставить("Accept", "application/vnd.github.v3+json");

Запрос = Новый HTTPЗапрос(Ресурс, Заголовки);
Ответ  = Соединение.Получить(Запрос);
```

**Comment by dmpas** [comment]
Забавно, 1С на это говорит:

```
Встроенный язык: Строка 9: Ошибка при вызове метода контекста (Получить): Ошибка работы с Интернет:   Couldn't resolve host name
```

**Comment by ghost** [comment]
@dmpas они походу оборачивают ошибку в try-except а ловят другой тип, но его cast'ят

**Comment by nixel2007** [comment]
@dmpas 
Вроде 200 возвращается.
![image](https://cloud.githubusercontent.com/assets/1132840/19151310/aaceccb2-8bd4-11e6-9521-d064ab090f0a.png)
![image](https://cloud.githubusercontent.com/assets/1132840/19151304/a2c53d94-8bd4-11e6-834f-74201d7962d3.png)

**Comment by dmpas** [comment]
@nixel2007 я не к тому, что адрес не доступен, это я и сам проверил. Просто удивился, что 1С такое пишет.

**Comment by EvilBeaver** [comment]
@dmpas, 1C не любит хттп в адресе. Оно требует только имя сервера, без протокола

**Comment by EvilBeaver** [comment]
Странная хрень, если честно... Добавлять свойство не вижу смысла, в API 1С его нет, а сценариев, в которых мы бы захотели его програмно варьировать, в голову не приходит.

**Comment by nixel2007** [comment]
@EvilBeaver ну... Либо его менять программно, либо зашить по умолчанию. Потому что иначе часть хттп запросов просто не работает :)

**Comment by EvilBeaver** [comment]
Зашить, я про это же.

**Comment by EvilBeaver** [comment]
Ну и в качестве обхода можно положить рядом с exe тот конфиг файл, который по ссылкам в статье от  @allustin

**Comment by nixel2007** [comment]
@EvilBeaver 

> Ну и в качестве обхода можно положить рядом с exe тот конфиг файл, который по ссылкам в статье от @allustin

Попробовал, не помогло. Погуглил по поводу app.config - вроде пишут, что он кладется в каталог c# проекта, а не рядом с готовым бинарем.

**Comment by EvilBeaver** [comment]
Файл должен называться oscript.exe.config. И иметь содержание:

``` xml
<?xml version ="1.0"?>
<configuration>
  <system.net>
    <settings>
      <httpWebRequest useUnsafeHeaderParsing="true" />
    </settings>
  </system.net>
</configuration>
```

**Comment by dmpas** [comment]
@/all если никто не против, сегодня зашью.

**Comment by artbear** [comment]
Зашивай :)
