### ISSUE TITLE
Ошибка при выполнении теста с помощью testrunner.os

### ISSUE THREAD

**Issue by alexkmbk** [EvilBeaver/OneScript#344]
Текст ошибки:
_Не удалось загрузить тест <путь к файлу с тестами>
{Модуль C:\Program Files (x86)\OneScript\lib\package-loader.os / Ошибка в строке: 7 / Внешнее исключение (System.ArgumentOutOfRangeException): Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index}_

Ошибка появляется при тестировании библиотеки, у которой есть свой файл package-loader.os вложенный в каталог библиотеки, где выполняется инициализация внешней компоненты.
То ли дело в этом вложенном файле, то ли в том, что в тестируемой внешней компоненте имеются глобальные функции, не понятно.

Полагаю появление ошибки связано с исправлениями по моему issue #330 потому что данная ошибка воспроизводится именно на 1Script ночной сборки.

Прилагаю библиотеку, на которой воспроизводится ошибка:
[dialogs.zip](https://github.com/EvilBeaver/OneScript/files/513888/dialogs.zip)

Проект этой библиотеки (проект создан в демонстрационных целях):
[StandardDialogs.zip](https://github.com/EvilBeaver/OneScript/files/513893/StandardDialogs.zip)

Файл теста, на котором воспроизводится ошибка:
[test-MessageBox.zip](https://github.com/EvilBeaver/OneScript/files/513897/test-MessageBox.zip)

Если использовать данную библиотеку вне testrunner.os, как обычно, то все работает без ошибок.

Версия 1Script:  1.0.15.212

**Comment by alexkmbk** [comment]
Ребята извините если я вас замучил со своей темой глобальных функций во внешних компонентах, я не специально )))

**Comment by dmpas** [comment]
@alexkmbk да нам только в радость!

**Comment by artbear** [comment]
+1

**Comment by alexkmbk** [comment]
Оказалось дело не в testrunner.os а в том, что при таком способе подключения библиотеки ошибка вылазит в случае, если какая еще либо библиотека используется, то есть например
#use dialogs
#use v8tunner

если подключить только dialogs, то ошибки не будет.
Всё опять уперлось в невозможность добавить глобальную функцию с помощью внешней компоненты :(

**Comment by EvilBeaver** [comment]
Постараюсь сегодня вечером исправить глобалки в ВК

4 Фев 2017 г. 12:52 пользователь "Alexey Kostromin" <
notifications@github.com> написал:

**Comment by EvilBeaver** [comment]
А чо за хрень я получаю при попытке загрузить эту dll-сборку?

```
Предпринята попытка загрузить сборку из сетевого ресурса, что в предыдущих версиях .NET Framework могло привести к помещению сборки в "песочницу". Этот выпуск .NET Framework не включает политику CAS по умолчанию, поэтому данная загрузка может быть опасной. Если эта нагрузка не предназначена для изоляции сборки, включите переключатель loadFromRemoteSources. Дополнительные сведения см. на странице http://go.microsoft.com/fwlink/?LinkId=155569.
```

Выдается на строке: ``` var assembly = System.Reflection.Assembly.LoadFrom(dllPath);```

Путь не сетевой, а файловый, приходящий из package-loader.os

**Comment by EvilBeaver** [comment]
> If an application has been copied from the web, it is flagged by Windows as being a web application, even if it resides on the local computer. You can change that designation by changing the file properties, or you can use the <loadFromRemoteSources> element to grant the assembly full trust. As an alternative, you can use the UnsafeLoadFrom method to load a local assembly that the operating system has flagged as having been loaded from the web.

Ну прикольна... получается, что те dll, которые приехали из веба, (читай из opm) еще и грузиться не будут, т.к. недоверенные...

**Comment by EvilBeaver** [comment]
В-общем, на данный момент обход такой: пакет, который меняет глобальный контекст - размещать самым последним в списке "Использовать". Разобраться что куда и как - не получилось.

**Comment by alexkmbk** [comment]
@EvilBeaver  чтож, печально. Выходит все таки, по факту нельзя (ну или чревато проблемами) во внешних компонентах добавлять глобальные функции. Эх... а так хотелось чтобы была простая функция: Предупреждение();
