### ISSUE TITLE
OScript встраивание в Eclipse - возможно ли ?

### ISSUE THREAD

**Issue by ghost** [EvilBeaver/OneScript#345]
тут в меня давеча вбросили следующее

"а можно ли встроить oscript в EDT ?" точнее не так - "думали ли мы о встраивании".

этот issue - предлагаю сделать артефактом "на подумать" как это делать и делать ли вообще.

я этот вопрос исследовал немного и пришел к выводу что задача не тривиальная, и вполне возможно неверная. учитывая что у нас C# - первое что приходило на ум, это https://sourceforge.net/projects/jacob-project/support, но учитывая свой Java опыт - могу сказать что оно не работает.
Понятно дело что нам понадобится написать свой плагин http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Ffirstplugin.htm
А вообще то даже по другому http://www.vogella.com/tutorials/EclipseExtensionPoint/article.html
и вот по последней ссылке возникают очень интересные мысли:
- Eclipse сам построен на принципе точек входа в плагин
- наверное архитектурное решение представляет собой "проброс" неких точек из EDT внутрь скрипта на OScript. 

Я думаю в течении года ближайшего нужно как то подумать над архитектурным решением - если таковое возможно вообще.

**Comment by nixel2007** [comment]
``` gherkin
Как некто с партнерки
Я хочу встроить oscript в EDT
Чтобы <что?>
```

**Comment by artbear** [comment]
Какие задачи oscript должен решать в Eclipse ?
Выступать в роли ядра для плагинов на языке 1С ?

**Comment by EvilBeaver** [comment]
Мне вот тоже интересно, это было праздное любопытство или есть идеи применения?

**Comment by EvilBeaver** [comment]
А давайте рассмотрим шире - порт на Java (или ваш любимый язык), нужен ли? Почему?

**Comment by dmpas** [comment]
@EvilBeaver на PHP и никак иначе!

Тут порт сам по себе не нужен, достаточно односкрипт держать запущенной службой или вроде того - слушать запрос, отдавать ответ. А уже на условном ПхП делать прослойку, которая к нему обращается.

но опять же... ЗАЧЕМ?!

**Comment by kuntashov** [comment]
```
Я как 1С:Разработчик, использующий EDT
Хочу встроить oscript в EDT 
Чтобы автоматизировать свою работу в EDT скриптами на языке 1C
```

Разработка плагинов под EDT для решения простых задач - слишком тяжеловесный подход с полным циклом разработки. А хотелось бы иметь возможность писать скрипты как для конфигуратора при помощи Снегопата, сосредоточившись на решении своей задачи, а не на нюансах разработки плагина и жонглирования низкоуровневыми объектами.

Естественно, с учетом "популярности" EDT и его ограничений это пока скорее гипотетические потребности, но рано или поздно он же заменит конфигуратор :)

Кстати, для "скриптования" Eclipse загуглился проект EASE (https://eclipse.org/ease/).

**Comment by ghost** [comment]
@kuntashov точно так - чтобы плагины разрабатывать полегче, точнее даже не плагины - а именно скрипты. но нужен ли для этого OScript - для меня вопрос открытый. 

Я вот и подумал - что стоит сформулировать либо отказ, либо способ решения. И создал issue - чтобы если кто-то еще раз спросит: направить его в эту задачу.

**Comment by kuntashov** [comment]
> но нужен ли для этого OScript - для меня вопрос открытый.

Может быть нужен ровно по тем же причинам, по которым OScript вообще существует (кроме всех видов удовольствия для тех, кто его разрабатывает) - чтобы 1Сники могли решать свои задачи не переключая "контекст". Так ведь и административные задачи 1Сника можно решать на любом скриптовом языке - от шелл-скриптов до питонов/рубей.

А так да - торопиться пока некуда.

**Comment by EvilBeaver** [comment]
Для эклипса, имхо, лучше сразу заюзать родной bsl движок. Хакерским способом в стиле Саши Орефкова или продавить в 1С. Мой ответ - односкрипт там не нужен. До поры точно.

**Comment by kuntashov** [comment]
@EvilBeaver а что, там интерпретатор встроен? Мне кажется, там максимум лексер/парсер - для обеспечения соответствующей инфраструктуры плагинов, а исполняемой среды (runtime) нет. Но это лишь мои догадки, я исходники не смотрел.

**Comment by EvilBeaver** [comment]
@kuntashov да фиг знает, чего там. Скорее всего, ты прав.

**Comment by EvilBeaver** [comment]
В таком случае, закроем пока очень сильно не понадобилось. Нет ни сценариев, ни ресурсов разработки, ни понимая целесообразности.
