### ISSUE TITLE
`oscript -check` ругается на CGI-скрипты

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#353]
предлагаю добавить пометку, что проверка идёт в режиме CGI:

```
oscript -check -cgi myscript.os
```

или

```
oscript -cgi -check myscript.os
```

В частности, ругается на `ВебЗапрос` и `ВывестиЗаголовок`, ибо они не подключаются в контекст.

**Comment by best-tech** [comment]
а сейчас тоже добавлен? у меня ругается...

**Comment by dmpas** [comment]
@1Cmobile `oscript -check -cgi script.os` - такой вызов ругается?

**Comment by best-tech** [comment]
в такой интерпретации 
System.IO.FileNotFoundException: Файл ..\os-cgi\-cgi' не найден.
Имя файла: '..\os-cgi\-cgi'
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs,
 String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   в ScriptEngine.Environment.FileBasedSource.GetCodeString()
   в ScriptEngine.Environment.FileBasedSource.ScriptEngine.Environment.ICodeSource.get_Code()
   в ScriptEngine.CompilerService.Compile(ICodeSource source)
   в ScriptEngine.CompilerService.CreateModule(ICodeSource source)
   в oscript.CheckSyntaxBehavior.Execute()
   в oscript.Program.Main(String[] args)

а без -cgi 
/ Ошибка в строке: 2 / Неизвестный символ: ВывестиЗаголовок}
ВывестиЗаголовок("Content-type");

при oscript -cgi -check  не ругается
но vsc всеравно подсвечивает

**Comment by dmpas** [comment]
это надо как-то VSC настраивать. сам oscript не может распознать, cgi ему подсунули или обычный скрипт.

**Comment by nixel2007** [comment]
@dmpas причем тут VSC? Оо

**Comment by nixel2007** [comment]
Вообще странноватый путь :)
`Имя файла: '..\os-cgi-cgi'`

**Comment by dmpas** [comment]
@nixel2007 
>причем тут VSC? Оо

там же где-то настраивается путь для линтера?

**Comment by nixel2007** [comment]
Погоди, так проблема-то в чем? в движок этот флаг добавили. В VSC могу его тоже добавить, если надо.

Если проблема в VSC - то надо перенести ишуз в 1c-syntax :)

**Comment by dmpas** [comment]
@nixel2007 проблема в том, что надо VSC где-то указать, что сей файл есть CGI и проверять его надо не просто `-check`, а `-check -cgi`. То есть, это не проблема движка или VSC, это вопрос, куда как настроить.

**Comment by nixel2007** [comment]
@dmpas помешает ли флаг -cgi проверке обычных скриптов? если нет, то я могу его безусловно передавать всегда.

**Comment by best-tech** [comment]
ну еще вопрос не в тему, скопилить для cgi можно или только запуском движка? 
p.s. жаль по cgi документации маловато(

**Comment by dmpas** [comment]
@1Cmobile CGI сейчас - костыль "шоббыло". Потому документации по нему больше, я думаю, не станет. Вчера решили прорабатывать ASP MVC для Односкрипта.

**Comment by dmpas** [comment]
@nixel2007 да, можно так сделать. Но лучше, мне кажется, пользователю ручками указывать, что тут CGI, а что нет.

**Comment by best-tech** [comment]
@dmpas мне от него не много нужно сейчас, получить запрос, обработать и вывести ответ
только вот все никак не запускается..
так все-таки комлилится или нет?

**Comment by dmpas** [comment]
@1Cmobile нет, не компилится.
https://gist.github.com/dmpas/a095134238f3dae007eb13244b4b962b - пример, как у меня получается запрос, обрабатывается и выводится.

**Comment by dmpas** [comment]
Кусок настройки апача
```
Alias "/oscgi/" "C:/opt/oscgi"
<Directory "C:/opt/oscgi">
	Options +ExecCGI
	AddHandler cgi-script .os
</Directory>
```

**Comment by best-tech** [comment]
@dmpas то что нужно, спасибо

**Comment by EvilBeaver** [comment]
В принципе, был вариант сделать отдельный exe типа oscript-cgi, чтобы в шебанге ключ не указывать.

**Comment by dmpas** [comment]
@EvilBeaver ключ в шебанге - обычное дело, ничего страшного в этом нет.
