### ISSUE TITLE
Более детальная расшифровка ошибки "Symbol already defined in the scope"

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#354]
Предлагаю как-то дополнительно расшифровывать сообщение `Symbol already defined in the scope`

Мне лично пришлось строку с ошибкой искать двоичным поиском, комментируя части кода.
Предлагаю добавить выдачу имени подобного идентификатора и номер строки для повышения ясности у разработчика.

Призываю @EvilBeaver @dmpas

Например, проблема возникла при решении https://github.com/artbear/1bdd/issues/95#issuecomment-255172018

**Comment by EvilBeaver** [comment]
ЕМНИП, там в некоторых местах символ выводится, а в некоторых нет. Можете поймать исключение и вывести стектрейс C# через метод 

```
ИнформацияОбОшибке().ПодробноеОписаниеОшибки() ?
```

**Comment by artbear** [comment]
@EvilBeaver ИМХО удобен показ имени подобного идентификатора и номера строки для повышения ясности у разработчика.

стектрейс вряд ли в этом поможет :(

**Comment by EvilBeaver** [comment]
@artbear я как раз об этом. Мне нужен стектрейс C# чтобы понять, где внутри движка это исключение было брошено. Там несколько таких мест и в каких-то нельзя узнать имя символа.

**Comment by artbear** [comment]
@EvilBeaver Ага, понял.
Тебе именно сейчас нужно показать стектрейс возникшей у нас ошибки :)
Выложу сюда

**Comment by artbear** [comment]
```
C:\projects\gitrunner>bdd features/РаботаСНастройкамиGit.feature
BDD for OneScript ver.1.2
ПРЕДУПРЕЖДЕНИЕ   - Ошибка при загрузке файла C:\projects\gitrunner\features\step_definitions\РаботаСНастройкамиGit.os
- {Модуль C:\projects\1bdd\src\bdd-exec.os / Ошибка в строке: 366 / Внешнее исключение (System.InvalidOperationException): Symbol already defined in the scope}
                                ИсполнительШагов = ЗагрузитьСценарий(ПутьИсполнителя);
- ScriptEngine.Machine.ExternalSystemException: {Модуль C:\projects\1bdd\src\bdd-exec.os / Ошибка в строке: 366 / Внешнее исключение (System.InvalidOperationException): Symbol already defined in the scope}
 ---> System.InvalidOperationException: Symbol already defined in the scopeполнителя); // И ВОТ ЗДЕСЬ прикольно :) scopeполнителя
-    в ScriptEngine.Compiler.SymbolScope.DefineVariable(String name, SymbolType symbolType)
-    в ScriptEngine.Compiler.Compiler.BuildSingleMethod()
-    в ScriptEngine.Compiler.Compiler.DispatchModuleBuild()
-    в ScriptEngine.Compiler.Compiler.BuildModule()
-    в ScriptEngine.Compiler.Compiler.Compile(Parser parser, ICompilerContext context)
-    в ScriptEngine.CompilerService.Compile(ICodeSource source)
-    в ScriptEngine.CompilerService.CreateModule(ICodeSource source)
-    в ScriptEngine.Machine.Contexts.AttachedScriptsFactory.CreateModuleFromSource(CompilerService compiler, ICodeSource code, ExternalContextData externalContext)
-    в ScriptEngine.Machine.Contexts.AttachedScriptsFactory.LoadAndCreate(CompilerService compiler, ICodeSource code, ExternalContextData externalContext)
-    в ScriptEngine.HostedScript.Library.SystemGlobalContext.LoadScript(String path, StructureImpl externalContext)
-    в ScriptEngine.Machine.Contexts.ContextMethodsMapper`1.<>c__DisplayClass32`3.<CreateFunction>b__31(TInstance inst, IValue[] args)
-    в ScriptEngine.HostedScript.Library.SystemGlobalContext.CallAsFunction(Int32 methodNumber, IValue[] arguments, IValue& retValue)
-    в ScriptEngine.Machine.MachineInstance.CallContext(IRuntimeContextInstance instance, Int32 index, MethodInfo& methInfo, IValue[] argValues, Boolean asFunc)
-    в ScriptEngine.Machine.MachineInstance.MethodCallImpl(Int32 arg, Boolean asFunc)
-    в ScriptEngine.Machine.MachineInstance.CallFunc(Int32 arg)
-    в ScriptEngine.Machine.MachineInstance.MainCommandLoop()
-    --- Конец трассировки внутреннего стека исключений ---
-    в ScriptEngine.Machine.MachineInstance.MainCommandLoop()
-    в ScriptEngine.Machine.MachineInstance.ExecuteCode()
```

**Comment by artbear** [comment]
@EvilBeaver ИМХО еще бы в методе [DefineMethod](https://github.com/EvilBeaver/OneScript/blob/42ca46e95817e1969b6ad7c75926af5cc3e74983/src/ScriptEngine/Compiler/SymbolScope.cs#L119) добавить вывод method.Name в исключение аналогично сделанному тобой исправлению

**Comment by artbear** [comment]
Не получил ответа.
Повторюсь:
@EvilBeaver ИМХО еще бы в методе DefineMethod добавить вывод method.Name в исключение аналогично сделанному тобой исправлению

ЗЫ я сам исправить не могу, на рабочей машине нет среды сборки проекта

**Comment by EvilBeaver** [comment]
С дефайнметод проще. Оно наверх не вылезает

**Comment by adva-cg** [comment]
Не знаю, было ли уже исправлено:
подобная ошибка возникла когда для процедуры указал ошибочно:
Процедура Тест(стр, стр.Н)
Указание было на стр, но без строки. А данная переменная активно испольовалась, долго пришлось искать причину

**Comment by EvilBeaver** [comment]
@adva-cg можешь прислать пример воспроизведения отдельным issue?

**Comment by adva-cg** [comment]
К сожалению кода, который содержал ошибку, не осталось, а на простом примере, не воспроизвелось. Если попадется, то попробую отдельным issue сделать
