### ISSUE TITLE
-make

### ISSUE THREAD

**Issue by fenixnow** [EvilBeaver/OneScript#355]
Долго я мучаюсь.... пытаясь подружиться с gitsync.

Дошел до компиляции скрипта в "бинарный файл" 
Если запустить в "C:\Program Files (x86)\OneScript\bin\TestApp.exe" компиляцию "C:\Program Files (x86)\OneScript\lib\gitsync\src\gitsync.os" получаю ошибку 

> {Модуль <string> / Ошибка в строке: 10 / Библиотека не найдена "core"}    
Перем Лог;

Пробую метод 2 описанный тут http://oscript.io/docs/page/running :)

oscript.exe -make <файл-скрипта> <файл-exe>

файл-exe - добавьте плиз описание где вылавливать по умолчанию скопмилированный файл? или же требуется изменить, что это путь в который скомпилируется файл.

Подскажите плиз, выложен где нибудь в гите сайт с контентом, чтобы была возможность делать pull reque...

**Comment by fenixnow** [comment]
не взлетело

![image](https://cloud.githubusercontent.com/assets/13418562/19883763/24fc2028-a027-11e6-81e2-f01e5c018e6b.png)

**Comment by nixel2007** [comment]
@fenixnow Гитсинк не сможет работать в режиме exe, т.к. он дополнительно запускает внешние ресурсы, которые не компилируются внутрь exe'шника.

Зачем вам именно exe?

**Comment by fenixnow** [comment]
У меня не получается начать работать через gitsync.os инициализаровать репозиторий.
В документации фигурирует просто http://oscript.io/library/package/gitsync
я так понимаю что это отдельный файл

**Comment by nixel2007** [comment]
@fenixnow в документации используется специальная обертка, которая должна была создаться автоматически при установке oscript. видимо не создалась (/cc @EvilBeaver).
откройте cmd, перейдите в каталог `program files (x86)/OneScript/lib/gitsync` и выполните команду `opm app src/gitsync.os`

После этого переоткройте консоль. Теперь gitsync должен быть доступен по имени.

**Comment by fenixnow** [comment]
спасибо за решение вопроса с запуском gitsync

**Comment by fenixnow** [comment]
пытаюсь инициализировать репозиторий
![image](https://cloud.githubusercontent.com/assets/13418562/19886703/81737686-a035-11e6-8192-96a5407182d0.png)

но если выполнить инициализацию репо напрямую из git, то все работает
![image](https://cloud.githubusercontent.com/assets/13418562/19886752/adadd994-a035-11e6-83c9-d5ed7f5dc606.png)

**Comment by nixel2007** [comment]
попробуйте перед запуском gitsync init сделать `chcp 65001` или `chcp 1251`, чтобы получить вывод команд.

**Comment by fenixnow** [comment]
это просто адский ад :)
![image](https://cloud.githubusercontent.com/assets/13418562/19887077/8095e6ac-a037-11e6-9f9f-1945c8cd4770.png)

**Comment by nixel2007** [comment]
так... а если это выполнить в git bash? (без chcp)

> вечно эта проблема с кодировками консоли...

**Comment by fenixnow** [comment]
![image](https://cloud.githubusercontent.com/assets/13418562/19887263/77460090-a038-11e6-9040-095f162822f0.png)
![image](https://cloud.githubusercontent.com/assets/13418562/19887416/4c22d8f6-a039-11e6-82f4-7944c26f6184.png)

**Comment by fenixnow** [comment]
УРА! Получилось!

**Comment by fenixnow** [comment]
.... А как в репозиторий клонировать все из хранилища 1с?

**Comment by nixel2007** [comment]
Выполнить `gitsync export`.
Обратите внимание, у вас там где-то в репе создался файл VERSION и AUTHORS.
В VERSION лежит номер версии хранилища с которой надо выгружать - его надо либо заполнить, либо поставить 0. Выгрузка одной версии может занимать довольно долгое время, в зависимости от размера конфигурации (около 15 минут на БП на 8.3.8, например).
В AUTHORS необходимо настроить связку пользователей хранилища и пользователей вашего сервера git (главное - почта)

**Comment by fenixnow** [comment]
<VERSION>0</VERSION>
![image](https://cloud.githubusercontent.com/assets/13418562/19887748/546ff33e-a03b-11e6-8385-c8bcd673d5d5.png)

**Comment by fenixnow** [comment]
нужно переходить в сам каталог с репозиторием?

**Comment by nixel2007** [comment]
там много параметров. выполните `gitsync help export`

**Comment by EvilBeaver** [comment]
Задачу закрываю?

**Comment by fenixnow** [comment]
подождите немножко, я запустил выгрузку конфигурации, если она завершится успешно, то закроем

**Comment by EvilBeaver** [comment]
@fenixnow выше уже написали, что упаковка в exe не имеет смысла. gitsync завязан на внешние бинарные файлы.

**Comment by fenixnow** [comment]
я запустил gitsync export.
Жду окончания его работы. 
По завершению, думаю работа будет понятна и с этим я перестану приставать

**Comment by JohnyDeath** [comment]
@EvilBeaver у меня вот тоже было огромное желание сделать из gitsync один exe-файл, если помнишь.
С ним намного проще как минимум для передачи на сервера сборок или другим начинающим падаванам.
Можно в порядке исключения что-нибудь придумать? Глядишь, там и общее решение по этому вопросу найдется.

**Comment by fenixnow** [comment]
Спасибо, конвертация хранилища в репозиторий прошла успешно. Задачу можно закрывать.

Если интересно мое мнение, как человека пытающего освоить ваши труды, то для меня огромный провал оставляет документация, она вроде есть но для решения проблем, она бесполезна. Мне намного легче было освоиться с например gitlab, fullpage и другими англоязычными проектами, чем вникнуть в onescript. Надеюсь никого не обидел, тк рассчитываю продолжать его использовать и изучать :smile: 
Веду внутреннюю корпоративную документацию для продавцов в магазинах. Для этих целей использую wiki c markdown синтаксисом. Из предложений могу предложить перенести вашу сюда, на гитхаб, Возможно людям, освоившие операции, будет возможность дополнять ее самостоятельно.

**Comment by EvilBeaver** [comment]
@fenixnow 

>  Из предложений могу предложить перенести вашу сюда

нашу - это какую?

И еще - часть документации - это исходники. Все по-гиковски, да. Но на 1С-языке все в состоянии прочесть и понять. То, что нет доков - это плохо, мы знаем. Вот кто бы еще написал? Может вы? Как раз, вы недавно по этому всему прошли и знаете чего именно в доках не хватает.

**Comment by fenixnow** [comment]
я не могу править на вашем сайте http://oscript.io/docs даже форкнуть его будет не очень успешное занятие

**Comment by artbear** [comment]
@fenixnow Можно форкнуть проект и в файле readme.md (markdown-разметка) дополнить документацию.
Далее штатным способом pull-request

Пока свежи воспоминания :)

**Comment by EvilBeaver** [comment]
@fenixnow можно прислать файл мне письмом, но лучше, как сказал @artbear

**Comment by dmpas** [comment]
Эту, может, закрыть уже?

@EvilBeaver @fenixnow
