### ISSUE TITLE
Добавить в решение проект внешней компоненты

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#357]
Простейшая компонента для тестирования компилируемости компоненты при внесении изменений в движок. Чтобы понимать:
  1. что с новыми изменениями движка компоненты продолжать собираться
  2. какие изменения нужно внести в компоненты, чтобы они работали с новой версией движка

Если компонента не компилируется - валится сборка. Если есть изменения в схеме работы - в коммите будет явно видно, какого плана доработки необходимо внести.

**Comment by EvilBeaver** [comment]
Что должно минимально быть в компоненте, чтобы обеспечить такую проверяемость?

**Comment by dmpas** [comment]
Класс с методом и двумя свойствами, одно из которых - перечисление. Класс-коллекция.
