### ISSUE TITLE
Сломан COMОбъект в версии 1.0.15

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#359]
А = Новый COMОбъект("V83.ComConnector");

Падает с ошибкой Внешнее исключение (System.Runtime.InteropServices.COMException): Не удалось получить фабрику класса COM для компонента с CLSID {181E893D-73A4-4722-B61D-D604B3D67D47} из-за следующей ошибки: 80040154 Класс не зарегистрирован (Исключение из HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).}

**Comment by EvilBeaver** [comment]
версия 1.0.15 переведена в режим AnyCPU. И пытается загрузить 64-разрядный ком-объект 1С Предприятия. Его, действительно, в системе нет. Вот и падает.

@dmpas есть идеи, чо делать?

**Comment by artbear** [comment]
> И пытается загрузить 64-разрядный ком-объект 1С Предприятия. Его, действительно, в системе нет. Вот и падает.

@EvilBeaver Если компоненты нет в системе, тогда падение закономерно и бага нет! или что-то другое?

**Comment by EvilBeaver** [comment]
Ну так-то как бы да, но если мы выкатим в поставке односкрипт x64, то все скрипты, юзающие ком-коннекторы 1С (а это, как минимум, наш деплой, если ты помнишь) сломаются.

**Comment by nixel2007** [comment]
@artbear клиент 1с по умолчанию грузит 32битную версию компоненты. 64битную версию использует только х64 сервер

**Comment by nixel2007** [comment]
@EvilBeaver погоди, если поставка односкрипта будет х64, то логично, что требоваться будут 64битные компоненты. Это вполне ожидаемое поведение

**Comment by EvilBeaver** [comment]
да, только отдельной поставки 64 нет. Есть AnyCPU. И она единственная. Т.е. человек, поставивший версию 15 не сможет юзать КомКоннектор 1С под 32 бита. Т.к. поставить версию x32 не сможет, ибо ее нет.

**Comment by dmpas** [comment]
Вот уныние-то. Видимо, придётся ставить "anycpu32bitpreferred".

**Comment by EvilBeaver** [comment]
Блин, все проще
*.exe делаются под 32 бита, а dll-под anycpu. И всем щастье. Цель из задачи #300 не пострадает
