### ISSUE TITLE
Неизвестный символ: Message

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#362]
```
{Модуль <string> / Ошибка в строке: 5 / Неизвестный символ: Message}    
```

https://github.com/EvilBeaver/OneScript/commit/c29f33f736ca42305e254ba0a1e46f34041e2f0a#diff-8c563a877d4ee9837fb92cdc5351c76fR150

**Comment by artbear** [comment]
@EvilBeaver @dmpas А как же, блин, тесты?
Неужели все тесты прошли?

**Comment by pumbaEO** [comment]
Тесты не гарантируют 100% работоспособность, а только уменьшают вероятность появления ошибки.

**Comment by artbear** [comment]
Женя, про 100% я, конечно, знаю :(
Тут вопрос в том, что ошибка ИМХО достаточно критичная и нарваться на нее можно было быстро при запуске разных скриптов, в т.ч. и тестов.
Поэтому у меня и возник вопрос - а как же тесты? тесты где?

**Comment by dmpas** [comment]
@artbear у движка с тестами своей внутренней кухни пока что плоховато. Вот легендарная 2.0 прям вся в лучших традициях ТДД :)

**Comment by artbear** [comment]
@dmpas Про 2.0 слышу очень давно, неужели Андрей еще ее не забросил? :)

у нас полно **приемочных** тестов движка, как я уже писал, странно, что они не сработали.
Возможно, что их не запускали :)

**Comment by dmpas** [comment]
@artbear насколько я помню, ни один приёмочный тест не заморочен на проверку всех возможных английских псевдонимов.

**Comment by artbear** [comment]
@dmpas Но сейчас-то ты добавишь тест на Message ? в лучших традициях разработки :)

**Comment by artbear** [comment]
@dmpas Увидел коммит, теста не увидел :( не гуд!

**Comment by dmpas** [comment]
@artbear там сейчас не просто **тест** надо запилить, там сейчас вообще **тестирование** надо делать, так как оно там отсутствует. А с этим надо отдельно подумать.

**Comment by artbear** [comment]
@dmpas ИМХО ты не прав. Тестирование не отсутствует полностью.
Есть приемочные тесты, которые прогоняются через CI
А вот внутренних тестов (быстрых юнит, приемочных), которые прогоняются в среде сборки, не хватает, это верно.

**Comment by dmpas** [comment]
@artbear я про внутреннее тестирование и говорю. Внешними тестами никак не проверить, что какой-то там `ContextMethodMapper` при каких-то там условиях делает не то, что нужно. Потому что это всё скрыто он внешнего мира. Инкапсуляция и разделение ответственности.
