### ISSUE TITLE
Добавить тестирование в движок

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#363]
По мотивам https://github.com/EvilBeaver/OneScript/issues/362

Стоит добавить NUnit-проект с тестами внутренностей движка.

**Comment by EvilBeaver** [comment]
😢 ну нетути его, нетути...

**Comment by ghost** [comment]
я бы предложил арендовать speclog для OpenSource организации - тогда дело бы пошло быстрей.

**Comment by Faithfinder** [comment]
Это от отчаяния :)?

**Comment by EvilBeaver** [comment]
Нет, просто @dmpas не знает про наш вчерашний разговор. @Faithfinder как раз хочет сделать юниттесты в движок.

**Comment by Faithfinder** [comment]
Только я хочу на MSTest. Почитал и про NUnit и про MSTest и пока что мне возможность запускать debug прямо из VS кажется полезнее того что предлагает NUnit.

Поверхностное гугление говорит что тесты нельзя запускать без VS, но более глубокое что это не так ;)

https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=TestAgent&rel=15

**Comment by dmpas** [comment]
Под моно заработает?

**Comment by Faithfinder** [comment]
Ммм..... Вроде нет. С другой стороны гугление этого вопроса показало, что NUnit теперь отлично встраивается в студию, нужно только добавить к тестовому проекту пакет NUnit3TestAdapter.

Такое ощущение что TDD совсем не такая передовая методология как кажется и в инете все статьи пишут или те кто сам не шарит, или те кто последний раз вопросом интересовался 8 лет назад

**Comment by EvilBeaver** [comment]
NUnit работает внутри MSVS. Но я не пробовал подключать. А TDD это всего лишь инструмент. Им или умеешь пользоваться, или не умеешь, или он плохо подходит в каком-то конкретном случае. Это не религия.

**Comment by EvilBeaver** [comment]
Более того, отсутствие TDD != отсутствие тестирования

**Comment by Faithfinder** [comment]
Короче, NUnit отлично работает, в студию встраивается, дебаг запускается, я уже проверил. Используем.
