### ISSUE TITLE
Ошибка инициализации COMОбъект

### ISSUE THREAD

**Issue by emakei** [EvilBeaver/OneScript#368]
> Script started: 2016-12-01 17:23:56
{Модуль <string> / Ошибка в строке: 2 / Внешнее исключение (System.Runtime.InteropServices.COMException): Не удалось получить фабрику класса COM для компонента с CLSID {181E893D-73A4-4722-B61D-D604B3D67D47} из-за следующей ошибки: 80040154 Класс не зарегистрирован (Исключение из HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).}    
Коннектор = Новый COMОбъект("V83.ComConnector")
Error detected. Exit code = 1
Script completed: 2016-12-01 17:23:56
Duration: 00:00:00.2221353

Ошибка на ночной сборке 1.0.15
Хотя в толстом клиенте версии 8.3.6 работает корректно.

**Comment by dmpas** [comment]
@mrDSide прям свежая ночная сборка? вроде ж это уже правили в начале ноября

https://github.com/EvilBeaver/OneScript/commit/5b65b40a4063744b64b90b33b49c61239fd29790

**Comment by emakei** [comment]
Прям только что скачал ) Проверил буквально несколько функций и вот результат. Качал по ссылке [ночной сборки](http://oscript.io/downloads/night-build/exe). Система Win 8.1 x64

**Comment by EvilBeaver** [comment]
Проверю. Это действительно, недавно фиксили

**Comment by dmpas** [comment]
@EvilBeaver правда, не включилась 32-битка в exe-шнике
```
C:\usr\os\bin>corflags oscript.exe
Microsoft (R) .NET Framework CorFlags Conversion Tool.  Version  4.6.1055.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32
CorFlags  : 0x1
ILONLY    : 1
32BITREQ  : 0
32BITPREF : 0
Signed    : 0
```

**Comment by AdapterBatareev** [comment]
получил снова эту ошибку, свежая сборка, версия 8.3.10 х64. версию 32 не ставил

**Comment by EvilBeaver** [comment]
Смотрите, какая штука: разрядность компоненты администрирования должна совпадать с разрядностью приложения, которое ее использует. Если у вас нет на машине 32-битной 1С-компоненты, то ни одно приложение 32-битное (включая 1script) не сможет администрировать 1С с ее помощью.
