### ISSUE TITLE
ОдноСкрипт Неопределено === C# null

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#371]
Предлагаю внутри в коде не выделять отдельно `DataType.Undefined` и считать за Неопределено любое null-значение.

Основной посыл: когда разрабатывается функционал на языке C#, то на `null` проверка есть всегда, а на Неопределено обычно заб(ы|и)ваем. С другой стороны, проверка на Неопределено несёт в себе просто дублирование логики, ибо поведение ничем не отличается от `null`.

**Comment by artbear** [comment]
+1

Добавлю, что из-за этого `заб(ы|и)ваем` в гитсинке появилась неприятная ошибка, которая еще 2 недели находилась в девелоп :(

**Comment by EvilBeaver** [comment]
А можно подробнее, в каком месте в метод пришло неопределено вместо c#null?

**Comment by artbear** [comment]
Обсуждение https://gitter.im/EvilBeaver/oscript-library?at=584a91a29ce5147013cd0817

**Comment by dmpas** [comment]
@EvilBeaver  всё просто:
```bsl
ПС = Неопределено;
З = Новый ЗаписьТекста("", , , Ложь, ПС);
```

приходит Неопределено

**Comment by EvilBeaver** [comment]
1C делает четкую разницу между не переданным параметром и Неопределено. И есть классы, которые не принимают Неопределено в качестве необязательного параметра. Т.е. у них, как и у нас, зависит от реализации класса контекста.

Я понимаю неудобство, но жестко делать эквивалент не хочу.

**Comment by EvilBeaver** [comment]
Например, делаем хелпер-метод в utils, типа IsNullOrUnfefined. Кроме того, в маршаллере если параметр заявлен как Ivalye, то неопределено разрешаем, а если конкретный тип, то приводим к нулл

**Comment by dmpas** [comment]
>  И есть классы, которые не принимают Неопределено в качестве необязательного параметра

это какие? там, наверное, значение по-умолчанию есть какое-то определённое и простозначное?

**Comment by EvilBeaver** [comment]
Да, там точно помню было необязательный аргумент и Неопределкно вызывало исключение, мол, неверный тип аргумента. Класс не помню, возможно хттпСоединение и параметр Прокси

**Comment by EvilBeaver** [comment]
Я за хелпер-метод IsNullOrUndefined. Все таки, это не эквивалент с непереданным

**Comment by awa15** [comment]
Сорри что влезаю, я совсем не понимаю ваши сишарпные заморочки, но мне показалось, что вы все немного ошибаетесь. Null в 1С не есть непереданное значение, точно так же и Неопределено не есть непереданное значение. Андрей, я тебе как-то передавал коды операций виртуальной машины 1С. Есть 3 разных кода операций в виртуальной машине 1С. Код 8 - Загрузить на стек Неопределено, код 9 - Загрузить на стек Null, код 10 - Загрузить на стек пустое значение. Когда мы пропускаем значение параметра при вызове процедуры, тогда используется код 10.
```bsl
фубар(П1, , П2);
```
Здесь в качестве второго параметра будет передано то самое пустое значение, которого генерится кодом операции 10.
И вот только это пустое значение, которое не является ни Неопределено, ни Null, заменяется в процедуре на значение по умолчанию. Если значение по умолчанию в процедуре не задано, то тогда значение параметра заменяется на Неопределено. Выражаясь немного тавтологично, значением по умолчанию значения по умолчанию параметра процедуры является Неопределено.
Напоследок, чтобы было понятней, простейший тест:
```bsl
Процедура КнопкаВыполнитьНажатие(Кнопка)
	Сообщить("1. Передаем Неопределено");
	ТестПараметров(Неопределено, Неопределено);
	Сообщить("2. Передаем Null");
	ТестПараметров(Null, Null);
	Сообщить("3. Передаем пустое значение");
	ТестПараметров(, );
КонецПроцедуры

Процедура ТестПараметров(П1, П2 = 2)
	Если П1 = Неопределено Тогда
		П1 = "Неопределено";
	ИначеЕсли П1 = Null Тогда
		П1 = "Null";
	КонецЕсли;
	Если П2 = Неопределено Тогда
		П2 = "Неопределено";
	ИначеЕсли П2 = Null Тогда
		П2 = "Null";
	КонецЕсли;
	Сообщить("П1 = " + П1 + "; П2 = " + П2);
КонецПроцедуры
```
В результате получаем такой вывод
```
1. Передаем Неопределено
П1 = Неопределено; П2 = Неопределено
2. Передаем Null
П1 = Null; П2 = Null
3. Передаем пустое значение
П1 = Неопределено; П2 = 2
```
Из ваших обсуждений мне показалось, что вы вместо пустого (непереданного) значения используете Null, а на самом деле это некое третье пустое значение, ни являющееся ни Null, ни Неопределено. Это значение невозможно получиться в явном виде в какой-то переменной. Оно существует только в момент вызова процедур и заменяется на значение по умолчанию в самом начале процедуры.

**Comment by awa15** [comment]
Хотя, сорри, ваше c#null, наверно и есть такое третье пустое значение.

**Comment by jdeshin** [comment]
Полностью согласен с мотивировочной частью @dmpas в исходном посте. Собственно опишу, почему я поднял эту тему. В процессе ковыряния либы telegram, с целью перевести ее на os столкнулся с достаточно большим количеством свойств и методов, которые могут иметь значение/возвращать null. Здесь есть два момента: первый - вроде как типы c# автоматически транслируются движком туда-обратно. С другой стороны - null стоит особняком, что неудобно. второй момент - это практическая целесообразность и удобство при написании оберток, что приводит к постоянному использованию подобных конструкций:

```
        [ContextProperty("Поток", "FileStream")]
        public ScriptEngine.HostedScript.Library.Binary.GenericStream FileStream
        {
            get
            {
                if (_voice.FileStream != null)
                    return new GenericStream(_voice.FileStream);
                else
                    //return null;
                    return (GenericStream)ValueFactory.Create();
            }
            set
            {
                // Не дебажил, что передается, поэтому две проверки
                if (value != null && value != ValueFactory.Create())
                    _voice.FileStream = value.GetUnderlyingStream();
                else
                    _voice.FileStream = null;
            }
        }
```

Если бы преобразование null было бы автоматическим, можно было бы сократить до

```
get 
{
          if (_voice.FileStream != null)
              return new GenericStream(_voice.FileStream);
         else
             return null; 
}
set 
{
        _voice.FileStream = value?.GetUnderlyingStream();
}
```

**Comment by jdeshin** [comment]
И да, для простых типов еще проще: get {return значение;} set {значение = value;}

**Comment by jdeshin** [comment]
Относительно null в 1С - по моему оно используется только в запросах, по крайней мере я не припомню его использование где-либо еще (хотя я не настоящий сварщик и могу ошибаться)

**Comment by dmpas** [comment]
Загвоздка сейчас в том, что с точки зрения жёлтой платформы если свойство имеет тип Поток, то оно не может быть Неопределено. Если оно может быть Неопределено, то в справке так и пишется: `Тип: Поток; Неопределено`.

Соответственно, наш документер тоже будет видеть только `GenericStream` и не будет понимать, может там быть Неопределено или не может. Сейчас однозначно считаем, что не может.

То есть нельзя решить проблему просто приравняв шарповый нулл к Неопределено. Можно выдумать какую-нибудь аннотацию, обозначающую, что может передаваться Неопределено - и вот в этом случае явно преобразовывать в null, минуя всякие `ValueFactory.Create()`

**Comment by EvilBeaver** [comment]
Например, еще одно свойство в [ContextMethod] или отдельный атрибут, скажем [MarshalNull] для возвращаемого типа.

```c#
public [MarshalNull] string MyFunc()
{
    // но вот тут придется химичить с делегатами вызова, ибо сейчас они простые как валенок, а тут придется утяжелять
    return null;
}
```

**Comment by EvilBeaver** [comment]
Ну, или если учесть, что 90% возвращаемых null-ов действительно должны мапиться в Неопределено, а только 10% - запрещать возврат null, то можно наоборот - разрешать по умолчанию и делать какой-то [StrictReturn] для методов, которым низя возвращать null

**Comment by EvilBeaver** [comment]
А вообще, проблема довольно надуманная. Имхо, невелика беда вместо ``return null`` написать ``return ValueFactory.Create()``

Или если по модно-молодежному, то:

     return SomeThirdPartyLib.GetStringOrNull()?? ValueFactory.Create()

**Comment by dmpas** [comment]
> Имхо, невелика беда вместо return null написать return ValueFactory.Create()

тогда у тебя возвращаемый тип должен быть `IValue` (Произвольный), а не `MyCoolType` (МойОфигенныйТип). Что скажется и на документации (привет, СП! мы о тебе помним), и на внутреннем использовании этой функции внутри C# (привет, `NullOrUndefined`).

**Comment by jdeshin** [comment]
@dmpas  Ида и нет - это же Кант :) С одной стороны - все верно, наверное, во всех свойствах типа Поток, внутренних объектов платформы значение свойства не может принимать или возвращать значение Неопределено. И нет причин не повторить это поведения в классах-двойниках 1С в OS. С другой стороны, 1С не накладывает подобных ограничений на пользовательский код. Вы вполне можете создать структуру, присвоить полю значение типа Поток, неопределено etc. Аналогичная ситуация с функциями и процедурами. Во внешних компонентах также нет таких ограничений. Ты скажешь, что во всех перечисленных случаях используется IValue и будешь прав т.к. ничего другого нет. И тогда, по логике необходимо объявлять все функции в c# как возвращающие и принимающие IValue, однако это неудобно с практической точки зрения, поэтому вы организовали автоматическое преобразование типов, за что вам спасибо. Однако эта фича выглядит неполной без преобразования null. Для одних типов так, для других сяк и соответственно доп проверки etc. 
Относительно реализации невозможности передачи null в классах-двойниках в c# это на мой взгляд надо отдать на откуп программисту. Когда я реализую класс 1С я изучаю его поведение и строю программу соответствующим образом, скажем сразу создаю поток в конструкторе (что я и сделал). На мой взгляд - это особенности реализации внутренних типов 1С, которые нужно повторить, но это не должно быть каким-то ограничением языка.

**Comment by dmpas** [comment]
>   это не должно быть каким-то ограничением языка

таки язык-то ни в чём не ограничен.

**Comment by jdeshin** [comment]
@EvilBeaver Давай подойдем чисто с практической точки зрения меньше времени->больше пива :)
Использование IValue в качестве параметров и возвращаемого значения приводит к доп коду распаковки (извлечения значения) и упаковке (преобразованию значения в IValue). Соответственно автоматическое преобразование типов, как простых так и классов - это здорово.
В c# подавляющее количество типов могут принимать значение null. Поскольку на мой взгляд, аналогом null в 1С является Неопределено неплохо бы его также преобразовывать. 
Как ты правильно заметил 90% null должно мапиться в неопределено (а я бы сказал 100%).
Соответственно вопрос в методике 
Добавление всяческих атрибутов - это доп сучение руками, это можно забыть и вылавливать уже при отладке.
Автоматический маппинг - ничего делать не надо, код короче и понятнее для программирующего на c# -> профит

Проблема надумана:
Она надумана, если имеем один класс и 10 свойств, которые могут быть null. В противном случае - сучение руками, непонятки, почему int конвертируется, а null нет -> не профит.
И да, молодежный стиль годится только для System.String

**Comment by jdeshin** [comment]
@dmpas Ну тогда, что мешает довести до логического "конца"? Распаковываются/упаковываются все простые типы, null и классы AutoContext. А как кстати сейчас передаются в параметрах классы AutoContext как IValue?

**Comment by dmpas** [comment]
> А как кстати сейчас передаются в параметрах классы AutoContext как IValue?

https://github.com/EvilBeaver/OneScript/blob/d0f7b001777764c93a52c8eed99d8bbcc202d2fd/src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs#L86-L89

**Comment by jdeshin** [comment]
@dmpas Если мы в os пишем А.МоеСвойство = Непределено; Какое значение IValue и типа будет здесь? https://github.com/EvilBeaver/OneScript/blob/d0f7b001777764c93a52c8eed99d8bbcc202d2fd/src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs#L36

**Comment by jdeshin** [comment]
@dmpas Я правильно понимаю, что эта функция преобразует параметры в типы/значения c# которые передаются в функции и свойства set?

**Comment by dmpas** [comment]
> Если мы в os пишем А.МоеСвойство = Непределено;

это уже зависит от конкретной реализации `GetPropertyValue`. В случае AutoContext: 

https://github.com/EvilBeaver/OneScript/blob/d0f7b001777764c93a52c8eed99d8bbcc202d2fd/src/ScriptEngine/Machine/Contexts/AutoContext.cs#L45

Если копать глубже, то курить тут: https://github.com/EvilBeaver/OneScript/blob/d0f7b001777764c93a52c8eed99d8bbcc202d2fd/src/ScriptEngine/Machine/Contexts/ContextPropertyMapper.cs

То есть, тебе в любом случае приходит `IValue`, который ты дальше разбираешь сам.

**Comment by dmpas** [comment]
> Я правильно понимаю, что эта функция преобразует параметры в типы/значения c# которые передаются в функции и свойства set?

Не совсем, но да.

**Comment by jdeshin** [comment]
Т.е. если мы здесь https://github.com/EvilBeaver/OneScript/blob/d0f7b001777764c93a52c8eed99d8bbcc202d2fd/src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs#L36
Что-то типа:

```
 if (value == null || value.DataType == DataType.NotAValidValue || value == ValueFactory.Create()) 
37             { 
38                 return null; 
39             } 
```

То все Неопределено будут преобразовываться в null. Так?

**Comment by jdeshin** [comment]
И здесь: https://github.com/EvilBeaver/OneScript/blob/d0f7b001777764c93a52c8eed99d8bbcc202d2fd/src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs#L101
напишем:

```
object objParam = (object)param; 

if(objParam == null)
    return ValueFactory.Create();

102             if (type == typeof(IValue)) 
```

То все null значения будут преобразовываться в неопределено. Так?

**Comment by jdeshin** [comment]
А если мы попытаемся присвоить параметру, с входящим типом, скажем целое, значение Неопределено, мы соответственно огребем исключение и это хорошо.

**Comment by jdeshin** [comment]
Т.е. в общем то на первый взгляд можно это реализовать малой кровью

**Comment by dmpas** [comment]
@jdeshin можно. Но теперь расскажи, как ты при этом решишь проблему с синтаксис-помощником. И как обеспечишь нулл-безопасность.

**Comment by jdeshin** [comment]
@dmpas Я поэтому и написал на первый взгляд. Я же не обладаю полнотой картины. 
А в чем проблема с синтаксис помощником? Можешь привести пример?
И что ты вкладываешь в понятие null-безопасность? Можешь привести пример, в чем проблема?

**Comment by dmpas** [comment]
@jdeshin https://github.com/EvilBeaver/OneScript/issues/371#issuecomment-353888008
вот тут я написал. Проблема в том, что если в доке не написано, что может быть возвращено Неопределено, то мы считаем, что его там и не будет. + сейчас это валится в рантайме (из-за чего весь разговор, собственно). Соответственно, проблема в том, что нужно и документеру, и рантайму как-то обозначить, что тут может быть Неопределено, а тут - нет.

**Comment by jdeshin** [comment]
@dmpas Ну если в доке не написано, то соответственно и возвращаться не должно. Это же забота человека, который пишет либу/стандартный объект 1С. К тому же на классы AutoContext это не распространяется https://github.com/EvilBeaver/OneScript/blob/d0f7b001777764c93a52c8eed99d8bbcc202d2fd/src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs#L154
Так, что anyway это делает программист (если я все правильно понял).
Т.е. камень преткновения это runtime отслеживание для типов DateTime, int/..., string?

**Comment by dmpas** [comment]
> anyway это делает программист (если я все правильно понял).

дока документером пилится.

**Comment by dmpas** [comment]
Короче, запили ПР, если не лень. Думаю, мы его примем, ибо принципиальных-то вопросов нет. Частности уже по ходу будем обдумывать.
