### ISSUE TITLE
Объявить функцию Выполнить() как DEPRECATED

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#375]
Для совместимости с 1С и возможности в дальнейшем реализовать функционал оператора Выполнить требуется запретить компиляцию метода с таким именем. 

Для начала, добавить предупреждение в системный вывод при компиляции такого метода.

**Comment by nixel2007** [comment]
Да, сонар вчера изрядно поругался на нее

**Comment by dmpas** [comment]
гы, а чё, есть такая???

**Comment by EvilBeaver** [comment]
@dmpas я могу объявить такую функцию в скриптах, но не в 1С. И эта функция уже сильно распространена в библиотеке. Нужно ее вытеснить оттуда.
