### ISSUE TITLE
Возможно объявить переменную после кода [old Странное поведение]

### ISSUE THREAD

**Issue by Alienjob** [EvilBeaver/OneScript#376]
Не работает, ругается что нет точки с запятой в строке 3

Сообщить("Привет мир!");
Перем ТекДата;
ТекДата = ТекущаяДата();
Сообщить(ТекДата);

Работает
*******************************
Перем ТекДата;
ТекДата = ТекущаяДата();
Сообщить(ТекДата);
**********************************
Сообщить("Привет мир!");
Перем ТекДата;
;
ТекДата = ТекущаяДата();
Сообщить(ТекДата);

**Comment by dmpas** [comment]
@Alienjob какая версия движка? Вообще, нынешний движок не любит объявление переменных после того, как начались команды тела модуля. Но ошибка, правда, невнятная, странная.

**Comment by dmpas** [comment]
Забавно, так тоже сработало:
```bsl
Сообщить("Привет мир!");
Перем ТекДата;;
ТекДата = ТекущаяДата();
Сообщить(ТекДата);
```

**Comment by Alienjob** [comment]
только что скачал актуальную, не ночную

**Comment by dmpas** [comment]
Спасибо, поправим.

По логике должна выдаваться синтаксическая ошибка на второй строке.

**Comment by EvilBeaver** [comment]
эээ, чуваки, так не должно быть. Объявление переменной после начала кода не должно работать вообще!
