### ISSUE TITLE
отсутствие опций -run и -runall

### ISSUE THREAD

**Issue by SergeyDjam** [EvilBeaver/OneScript#379]
Версия oscript 1.0.14
OS ROSA Linux R8 x86_64
1C 8.3.9

В разделе OneScript-1.0.14/tests находятся скрипты запуска тестирования: start.sh и start_all.sh
где присутствует такая строка: 
../src/oscript/bin/Debug/oscript.exe testrunner.os -runall $@ или ../src/oscript/bin/Debug/oscript.exe testrunner.os -run $@

Есть две проблемы:
1. при таком запуске oscript требует wine, наверное вернее строку указать таким образом
mono ../src/oscript/bin/Debug/oscript.exe testrunner.os -runall "$@"
2. отсутствуют опции -run и -runall 
oscript -run
1Script Execution Engine. Version 1.0.14.0

Usage:

I. Script execution: oscript.exe <script_path> [script arguments..]

II. Special mode: oscript.exe <mode> <script_path> [script arguments..]
Mode can be one of these:
  -measure   measures execution time
  -compile   shows compiled module without execution
  -encoding=<encoding-name> set output encoding

III. Build standalone executable: oscript.exe -make <script_path> <output_exe>
  Builds a standalone executable module based on script specified

IV. Run as CGI application: oscript.exe -cgi <script_path> [script arguments..]
  Runs as CGI application under HTTP-server (Apache/Nginx/IIS/etc...)

**Comment by dmpas** [comment]
1. в частности в убунте работает и без вайн, но прописывать в начале mono - это всё равно правильно, согласен

2. опции -run и -runall находятся не в движке, а в скрипте testrunner.os

**Comment by SergeyDjam** [comment]
тогда выходит такая штука: 

./start.sh .
 Версия приложения 1.0.14.0
{Модуль /home/admin/rpmbuild/BUILD/OneScript-1.0.14/tests/testrunner.os / Ошибка в строке: 331 / Пока не умею обрабатывать каталоги тестов}
Tests failed

и

./start-all.sh .
Упали тесты. Количество 2 шт :
    тест №1 : ТестДолжен_ПроверитьПолучениеКаталогаВПолномПути : путь файла </home/admin/rpmbuild/BUILD/OneScript-1.0.14/tests/file-object.os>
    тест №2 : ТестДолжен_ЗаписатьСоответствиеПространстваИмен : путь файла </home/admin/rpmbuild/BUILD/OneScript-1.0.14/tests/xmlwrite.os>
 
Есть нереализованные/пропущенные тесты. Количество 2 шт :
    тест №1 : ТестДолжен_СоздатьСокет : путь файла </home/admin/rpmbuild/BUILD/OneScript-1.0.14/tests/socket.os>
    тест №2 : ТестДолжен_ПрочитатьИзФайлаСРазнымиПереводамиСтрок : путь файла </home/admin/rpmbuild/BUILD/OneScript-1.0.14/tests/xmlwrite.os>

**Comment by dmpas** [comment]
первый вариант запуска неверен - `start.sh` используется для запуска ОДНОГО файла теста.

второй вариант правильный и он честно сознаётся, что два теста не прошли. Почему - это уже надо разбираться. :) как вариант - попробовать ночную сборку.

**Comment by SergeyDjam** [comment]
Понял. Спасибо

**Comment by EvilBeaver** [comment]
Я пока закрою, вроде проблема решена. Если будут возражения - пишите.
