### ISSUE TITLE
ЗапуститьПриложение("git") открывает проводник

### ISSUE THREAD

**Issue by demidych** [EvilBeaver/OneScript#381]
При запуске скрипта с кодом
`
ЗапуститьПриложение("git");
`
открывается проводник с каталогом "D:\Tools\Git", в котором в папке "bin" лежит "git.exe".

Если изменить на
`
ЗапуститьПриложение("git.exe");
`
то запускается git нормально.

В 1С работают правильно оба варианта.

Т.к. ЗапуститьПриложение("git") часто встречается в скриптах, то получается я один с такой ошибкой. Видимо какие-то настройки. Подскажите в какую сторону рыть.

**Comment by nixel2007** [comment]
Как временный обходной путь - попробуйте СоздатьПроцесс. Или сразу библиотеку 1commands.

**Comment by artbear** [comment]
Потроллю Никиту - или сразу гитраннер, чего уж :)

**Comment by artbear** [comment]
@demidych в командной строке напиши `where git` и посмотри, какие там приложения стоят.

**Comment by demidych** [comment]
@nixel2007
Как временный - работает ЗапуститьПриложение("git.exe")

**Comment by demidych** [comment]
@artbear
where git
d:\Tools\Git\bin\git.exe

**Comment by demidych** [comment]
Переименовал d:\tools\git в d:\tools\git2 (и в path поменял) и  заработало "ЗапуститьПриложение("git")"
Я так понимаю где-то прописана ассоциация на git и это приводит к открытию папки.

Но вообще это странный способ применения этого метода. 
Я всегда считал, что ЗапуститьПриложение() необходимо использовать только для запуска ассоциированного приложения. Например, ЗапуститьПриложение("1.pdf") чтобы посмотреть pdf.

**Comment by EvilBeaver** [comment]
Не ошибка, закрываю.
