### ISSUE TITLE
Падает TestApp при нажатии Выполнить

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#382]
Только что скачал стабильную версию.
1.0.15.260

Написал в окне `ЗапуститьПриложение("git");`
получил вылет приложения

Пишу `f=1;`, запускаю и вылет.

Вин10 64

Заметил еще на ночниках текущей ветки девелоп - месяца два или даже более.

Кто виноват и что делать?

**Comment by EvilBeaver** [comment]
подтверждаю.

**Comment by EvilBeaver** [comment]
@artbear у меня как-то самопочинилось на последнем коде в develop.... Можешь уточнить, работает или нет?

**Comment by EvilBeaver** [comment]
Закрываю, больше не воспроизводится.
