### ISSUE TITLE
Запись текста без BOM

### ISSUE THREAD

**Issue by best-tech** [EvilBeaver/OneScript#384]
ЗаписьТекста = Новый ЗаписьТекста ; 
ЗаписьТекста.Открыть(ПутьНазначения,"UTF-8");

Записывает файл с BOM

Возможность указать без BOM отсутствует

**Comment by dmpas** [comment]
```bsl
ЗаписьТекста = Новый ЗаписьТекста ;
ЗаписьТекста.Открыть(ПутьНазначения, КодировкаТекста.UTF8NoBOM);
```

**Comment by nixel2007** [comment]
Запись с bom - поведение, совпадающее с платформой. 
Для записи без бом специально добавлена отдельная кодировка

**Comment by best-tech** [comment]
спасибо за информацию
Кодировка UTF-8 без BOM называется "CESU-8".
