### ISSUE TITLE
oscript.cfg - читать из CWD

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#385]
Предложение добавить чтение oscript.cfg не только из КаталогаПрограммы() + месторасположения скрипта, но и из текущей рабочей директории.

Сценарий использования:
```bat
opm install -l
oscript-config set lib.system "./oscript_modules"
oscript path/to/my/script
```

Библиотеки ставятся в oscript_modules от CWD, запуск oscript.exe зачитывает находящийся в CWD каталог с библиотеками и начинает работать с ними.

**Comment by rsyuzyov** [comment]
+1

**Comment by EvilBeaver** [comment]
Эм... Это все хорошо, но я не понял зачем...

**Comment by nixel2007** [comment]
Допустим у меня в репе лежат несколько скриптов. Да ещё и в разных каталогах. Сейчас для переопределения настроек oscript мне надо класть oscript.cfg рядом с каждым из скриптов. Если эти настройки будут забираться из CWD, то мне достаточно один раз из положить в корень проекта.

**Comment by EvilBeaver** [comment]
Конфиг файл - это настройка приложения. И она должна лежать рядом с приложением (в данном случае со скриптом). А забор настройки из cwd для меня подозрителен. Я так и не понял, что за настройки движка ты хочешь переопределять и для чего?

**Comment by nixel2007** [comment]
Хочу переопределять lib.system и lib.additional

**Comment by EvilBeaver** [comment]
Никит, я тя убью )
Ты можешь сразу сказать ЧТО ты хочешь делать, а не КАК ты предполагаешь это делать?

**Comment by nixel2007** [comment]
@EvilBeaver ^_^

Глобально - хочу отставить в Program files только opm + его зависимости. В идеале - его зависимости в opm/oscript_modules

Все остальные зависимости - в oscript_modules в корне проекта.

Причины все те же (если исключить мое "идеальное" видение мира, о чем со мной с удовольствием поспорит @dmpas ;) ) - максимальная изоляция скрипта/приложения от окружения.

**Comment by dmpas** [comment]
@nixel2007  вот пусть в каталоге скрипта и лежит конфиг его окружения.

**Comment by nixel2007** [comment]
@dmpas знаешь, я в целом с тобой согласен. и согласен с @EvilBeaver о том, что забирать конфиг из CWD в обещм случае - это подозрительно.

Просто хочется иметь легкий способ переопределить поведение oscript не глобально навсегда (в программ файлс), а грубо говоря в рамках текущего окна cmd/проекта. Конфиг рядом с каждым скриптом это позволяет сделать, согласен, просто менее удобный способ.

**Comment by pumbaEO** [comment]
А вот тут я напомнюсь, помните просил когда-то, что-бы путь к библиотекам, можно было переопределить в переменной окружения (так питон тоже позволяет сделать).

**Comment by EvilBeaver** [comment]
@pumbaEO, это можно
