### ISSUE TITLE
"Символы" не перечисление, а набор значений

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#388]
https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/SymbolsEnum.cs#L14

В альма-матери они входят не в "Системные перечисления", а в "Системные наборы значений" и не создают нового типа значений.

По большому счёту нигде не мешает, но для справедливости надо переделать во что-нибудь иное.

**Comment by EvilBeaver** [comment]
Согласный
