### ISSUE TITLE
Свойство ProduceExtraCode компилятора бесполезно

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#390]
Код отслеживания покрытия (LineNum) всегда генерируется независимо от свойства ProduceExtraCode, поскольку в AddCommand никогда не передается последний добавленный параметр.

@dmpas, призовись.

**Comment by dmpas** [comment]
Призвался. LineNum же не только для отладки, а для исключений ещё, потому он всё равно будет добавляться, просто не во всех случаях он нужен.

https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine/Compiler/Compiler.cs#L1503

Вот тут передаётся параметр, я не стал передавать его везде, потому что слишком много логики менять пришлось бы. Надо продолжить работу в этом направлении, согласен, но это не баг.
