### ISSUE TITLE
ЗаписьТекста ведет неадекватно описанию

### ISSUE THREAD

**Issue by 1cwin** [EvilBeaver/OneScript#393]
Не создается новый файл. А всегда записывается в конец.
Параметр append пишется как текст в виде Да/Нет...

13.12.2016 16:36:13         myRetail/ЗагрузитьКлассификатор.epfДа13.12.2016 16:54:31      myRetail/ЗагрузитьСоответствие.epfДа

**Comment by 1cwin** [comment]
15 версия...

**Comment by dmpas** [comment]
@1cwin пример кода можно? append должен быть четвёртым параметром, а тут складывается ощущение, будто он идёт третьим - как "РазделительСтрок"

**Comment by dmpas** [comment]
http://oscript.io/syntax/page/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C%D0%A2%D0%B5%D0%BA%D1%81%D1%82%D0%B0

в документации ошибка в описании конструктора "По имени файла и кодировке" :(

**Comment by 1cwin** [comment]
ок.

**Comment by nixel2007** [comment]
не надо закрывать! :) надо пофиксить документацию

**Comment by dmpas** [comment]
@EvilBeaver смотрю, исправил документацию? эту можно закрыть.
