### ISSUE TITLE
Как выполнять доработку стандартных пакетов (Разработка, тестирование) ?

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#396]
У меня сложилась интересная ситуация при разработке/тестирования пакета 1commands

Прогоняю бдд-фичи проекта 1commands через другой проект 1bdd 
код вызова `call 1bdd features -junit-out ./bdd-log.xml`
и получаю ошибку https://ci.appveyor.com/project/artbear/1commands/build/1.2.27#L352

Проблема в том, что в локальном коде и репозитарии проекта выполнено добавление указанного метода `УстановитьПравильныйКодВозврата`
но тестировщик 1bdd пользуется более старой версией 1commands из мастер-ветки, в которой нет указанного метода, и который установлен через `opm install` или через установку OneScript

Т.е. структурно получаем след.стек вызовов тестировния 1commands 
+ 1bdd
  + 1commands из мастера (через Использовать)
    + `Команда = Новый Команда` - загружаю экземпляр из мастер-ветки
  + загружаем тестовый сценарий через ЗагрузитьСценарий
    + Использовать "." - хочу использовать свежие доработки проекта 1commands 
    +  `Команда = Новый Команда` - **попытка использовать свежую версию, но неудача, т.е. этот класс уже определен ранее !!**

Надеюсь, схему понятно описал.

ИМХО эта проблема критична при разработке всех типовых пакетов, которые будут юзаться в 1бдд или 1тестраннер.

Что делать?
Как мне протестировать поведение свежих доработок своего класса, который юзается и как типовой пакет?

/cc @EvilBeaver @dmpas @nixel2007

**Comment by artbear** [comment]
Сейчас я выполняю обход следующим костылем: удаляю папку проекта из стандартной поставки и вместо этой папки создаю симлинк на папку репозитария проекта.

ИМХО так работает на локальной машине, но приходится вручную заморачиваться :(

И на CI из-за этой проблемы билды падают - https://ci.appveyor.com/project/artbear/1commands/build/1.2.27#L352

**Comment by nixel2007** [comment]
lib.additional?

**Comment by artbear** [comment]
@nixel2007 Расшифруй.
Еще раз - сначала стартует 1bdd со штатными пакетами и их штатной реализацией, а уже потом доходит дело до моих тестовых шагов с новой реализацией

**Comment by nixel2007** [comment]
ты дорабатываешь 1commands в e:\git\1commands.
Указываешь lib.additional e:\git
Таким образом, когда ты запускаешь 1тестраннер, он подхватывает 1commands из гитового репо, а не из программ файлс.

**Comment by nixel2007** [comment]
возможно только надо будет package-loader положить в e:\git.
Надо проверитью

**Comment by artbear** [comment]
>ты дорабатываешь 1commands в e:\git\1commands.
Указываешь lib.additional e:\git
Таким образом, когда ты запускаешь 1тестраннер, он подхватывает 1commands из гитового репо, а не из программ файлс.

сейчас у меня на машине разработки так и сделано.
Выдается описанная выше ошибка :(

что за package-loader положить?

**Comment by nixel2007** [comment]
Который лежит в OneScript/lib. 
 Мне еще два варианта в голову пришло. 
1. Использовать локальные инстансы, как я сделал это в PackageDef самого opm
2. Подключать тестраннер не из командной строки, а изнутри скрипта, как это сделано в tasks/test.os в gitrunner. 
Таким образом ты сможешь в test.os сначала подключить нужную тебе версию библиотеки, которую ты разрабатываешь (через использовать ../src), следом использовать 1testrunner и уже запускать прогон тестов через интерфейс класса.

**Comment by nixel2007** [comment]
Во втором случае тесты запускаются через opm test

**Comment by artbear** [comment]
>0. надо будет package-loader положить в e:\git.
>1. Использовать локальные инстансы, как я сделал это в PackageDef самого opm
>2. Подключать тестраннер не из командной строки, а изнутри скрипта, как это сделано в tasks/test.os в gitrunner.
Таким образом ты сможешь в test.os сначала подключить нужную тебе версию библиотеки, которую ты разрабатываешь (через использовать ../src), следом использовать 1testrunner и уже запускать прогон тестов через интерфейс класса.

0. Вариант 0 не получился. Файл положил, ничего не поменялось
1. Локальный инстансы не очень хочется. Ведь я правильно понял про `Команда = ЗагрузитьСценарий(Файл, "Команда")` ?
Поведение, в принципе, может отличаться от типового применения через пакеты
2. Этот вариант получился.
Но у меня в VSC используется порядка 5 тасков для обеспечения нормальной разработки, не хочется их все переводить на opm task. И порядка 5 тасков-скриптов создавать :(
Тем более, что я говорю о типовых пакетах, в этом случае придется для каждого пакета добавлять аналогичные файлы.

**Comment by nixel2007** [comment]
> Тем более, что я говорю о типовых пакетах, в этом случае придется для каждого пакета добавлять аналогичные файлы.

посмотри на это с другой стороны. единый интерфейс тестирования приложения, не зависящий от применяемого фреймворка. таски vsc нельзя запустить из консоли, они привязаны к VSC. таски опм можно запустить откуда угодно.

**Comment by nixel2007** [comment]
плюс я делал opm test как раз для того, чтобы он стал единой точкой тестирования для пакетов. единым стандартом разработки библиотеки.

**Comment by nixel2007** [comment]
унификация для CI туда же.

**Comment by dmpas** [comment]
что-то я ничего не понял из обсуждения... @artbear у тебя там циклическая зависимость или мне показалось??

**Comment by artbear** [comment]
не циклическая зависимость.

я дорабатываю версию типового пакета в своем рабочем каталоге.
Этот же пакет уже стоит у меня через opm install

при вызове прогона фич используется вызов версии из общего каталога библиотек (от opm install), а не из моего пакета.

**Comment by EvilBeaver** [comment]
Статья @nixel2007 решает этот вопрос.
