### ISSUE TITLE
Непубличные классы в стандартной библиотеке

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#397]
https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs#L14

https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Json/JSONWriter.cs#L18

https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Json/JSONWriterSettings.cs#L13

https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Hash/HashFunctionEnum.cs#L19

https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Hash/HashImpl.cs#L15

https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Regex/Regex.cs#L18

https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Regex/MatchImpl.cs#L14

https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Regex/MatchCollectionImpl.cs#L17

Эти классы нет возможности использовать во внешних компонентах.

**Comment by ret-Phoenix** [comment]
Там ведь надо только public дописать и тесты прогнать?

**Comment by EvilBeaver** [comment]
Да

**Comment by ret-Phoenix** [comment]
Сделаю в следующем PR.

**Comment by ret-Phoenix** [comment]
Если пробегусь по всем классам в ScriptEngine.HostedScript и поставлю public можно?
Хочу для всех доступных из скрипта классов поставить public, к т.ч. для работы с консолью.

**Comment by ret-Phoenix** [comment]
PR принят, можно закрывать.

**Comment by dmpas** [comment]
@ret-Phoenix когда в мастер пойдёт - само закроется

**Comment by nixel2007** [comment]
@dmpas не вижу fix у коммитов, с чего оно должно закрыться? :)

**Comment by dmpas** [comment]
@nixel2007 и правда, просто ссылки на задачу не хватит
