### ISSUE TITLE
При установке стандартной библиотеке создаются ли командные файлы согласно указаниям из packagedef пакетов?

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#398]
Сейчас при установке пакета через `opm install Пакет` создаются командные файлы, например, `1testrunner.bat` или `1testrunner.sh`

ИМХО но при установке движка OneScript этого не происходит.

Выполняется ли создание командных файлов или нет?

/cc @EvilBeaver @dmpas @nixel2007

**Comment by dmpas** [comment]
>Выполняется ли создание командных файлов или нет?

нет.

**Comment by nixel2007** [comment]
Упс. Это к вообще к вопросу способа поставки библиотек с движком. Сейчас копируется репо целиком, а по сути нужны только файлы, которые включены внутрь пакета, собираемого опм

**Comment by artbear** [comment]
Вот я и задаю вопрос, хочу исправления.
Например, пост-инсталл хук для запуска opm update -all

**Comment by nixel2007** [comment]
Имхо, архитектурно не верно. Лучше при сборке инсталлятора класть к нему собранные ospx, а пост инсталл хуком делать opm install -f

Остаётся вопрос как сам опм поставить, но и он решаемый

**Comment by artbear** [comment]
>Имхо, архитектурно не верно. Лучше при сборке инсталлятора класть к нему собранные ospx, а пост инсталл хуком делать opm install -f
Остаётся вопрос как сам опм поставить, но и он решаемый

Ага, меня вариант также устраивает.
Вопрос только - как и когда автоматом получать ospx-файлы?

**Comment by pumbaEO** [comment]
Зачем потом вызывать, разве не проще сразу в песочницу поставить и потом уже готове запихнуть в инсталятор (rpm,deb,msi)?

**Comment by nixel2007** [comment]
@artbear ну, собрать ospx можно тем же опм. Мы же знаем, какие пакеты надо собрать - они в сабмодулях определены. Соответственно при сборке инсталлятора можно запустить сборку пакетов

**Comment by nixel2007** [comment]
@pumbaEO тоже хороший вариант

**Comment by EvilBeaver** [comment]
Хотели же поставлять с движком только опм и его зависимости. Без приложений а-ля гитсинк. И тогда не надо ospx с дистрибутивом тащить

**Comment by EvilBeaver** [comment]
Закрываю, как решенный вопрос. Нужны допилки opm.
