### ISSUE TITLE
Ошибка в строке: 534 / Не найден путь к платформе 1С <8.3>

### ISSUE THREAD

**Issue by AdapterBatareev** [EvilBeaver/OneScript#399]
#Использовать v8runner
Конфигуратор = Новый УправлениеКонфигуратором();

и сразу ошибка
{Модуль C:\Program Files (x86)\OneScript\lib\v8runner\src\v8runner.os / Ошибка в строке: 534 / Не найден путь к платформе 1С <8.3>}

была версия библиотеки 0.4.0, обновил на 0.6.0 и не помогло. Я что то делаю не так?

**Comment by AdapterBatareev** [comment]
включил отладку

```
Лог = Логирование.ПолучитьЛог("oscript.lib.v8runner");
Лог.УстановитьУровень(УровниЛога.Отладка);
Конфигуратор = Новый УправлениеКонфигуратором();
Конфигуратор.ПолучитьПутьКВерсииПлатформы("8.3.8.2008");
```

running command> oscript -encoding=utf-8 d:\Git\osTest\hooks\unpack.os
ОТЛАДКА - Читаю конфигурационный файл C:\ProgramData\1C\1CEStart\1CEStart.cfg.
ОТЛАДКА - Читаю конфигурационный файл C:\Users\Bahtyreev_AV\AppData\Roaming\1C\1CEStart\1CEStart.cfg.
ОТЛАДКА - Выполняю попытку поиска версии в каталоге C:\Program Files (x86)\1cv8
ОТЛАДКА - Выполняю попытку поиска версии в каталоге C:\Program Files (x86)\1cv82
ОТЛАДКА - Не найдено ни одного каталога с версией.
{Модуль C:\Program Files (x86)\OneScript\lib\v8runner\src\v8runner.os / Ошибка в строке: 534 / Не найден путь к платформе 1С <8.3>}

cfg файлы на месте, папки с платформами тоже

**Comment by EvilBeaver** [comment]
Это не относится к движку. Я закрываю здесь и продублирую в репо v8runner. Недавно что-то такое исправляли, возможно, коллеги подскажут.

https://github.com/oscript-library/v8runner/issues/26
