### ISSUE TITLE
В случае циклических зависимостей библиотек выдавать подробный лог о причинах ошибки

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#400]
Довольно часто при разработке и использовании пакетов возникает ошибка циклической зависимости
Например, https://github.com/oscript-library/v8runner/issues/27
```
cmd /c chcp 65001 >nul & 1testrunner -runall c:\projects\oscript-libs\v8runner/tests
{Модуль C:\OneScript\lib\1testrunner\main.os / Ошибка в строке: 0 / 
Ошибка загрузки библиотеки C:\OneScript\lib\1testrunner. Обнаружены циклические зависимости}
```

Хотелось бы получать более подробный лог о причинах ошибки.
Например, указание цикла библиотек Например, `источник - потомок - источник` 

Подобный лог позволит быстрее понимать причину ошибки и упростить разбор полетов для разработчиков и пользователей фреймворка.

/cc @EvilBeaver @dmpas

**Comment by artbear** [comment]
400 !

**Comment by dmpas** [comment]
тестраннер тестирует себя тестраннером???

**Comment by nixel2007** [comment]
@dmpas а я говорил...

**Comment by artbear** [comment]
@dmpas 
+ Да, тестирует, конечно.
  + Тестраннер сам себя отлично тестирует :)
+ В данном случае проблема при тестировании не тестраннера, а в8раннера через тестраннер :) oscript-library/v8runner#27
  + Т.е. это все-таки другая проблема.

**Comment by EvilBeaver** [comment]
Стойте, "довольно часто" она возникать не может, это косяк разработчика 100%

**Comment by artbear** [comment]
Разработчики косячат часто, мы все это знаем :) - между нами, мальчиками :)
Нужно как-то разбираться с этой проблемой.
Если будет четко написано, в какой цикл мы попали, будет НАМНОГО проще !

**Comment by EvilBeaver** [comment]
Дык никто и не спорит. Запилишь? Там в загрузчике при выбросе этого исключения нужно просто Соответствие перебрать и ключи в строку вывести

**Comment by khorevaa** [comment]
Дополнительно хочеться видеть откуда загрузилась та или иная библиотека. Допустим для режима отладки.

**Comment by artbear** [comment]
>Дополнительно хочеться видеть откуда загрузилась та или иная библиотека. Допустим для режима отладки.

+1

**Comment by EvilBeaver** [comment]
Ну так запилите, корифеи опенсорса. Там реально легко. А вам скиллы в си-шарпе
