### ISSUE TITLE
`СтрЗаменить` и суррогаты

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#401]
По мотивам копаний в https://github.com/oscript-library/json/issues/2

Есть код (https://github.com/oscript-library/json/blob/develop/src/json.os#L677)
```bsl
	ПоследоавтельностьПеремаскировки = "\" + Символ(65535);
	
	// Демаскирование служебных символов.
	Результат = СтрЗаменить(СтрЗаменить(СтрЗаменить(СтрЗаменить(СтрЗаменить(СтрЗаменить(СтрЗаменить(СтрЗаменить(Значение, 
						"\\",			ПоследоавтельностьПеремаскировки),		// Перемаскирование последовательности.
```

Код заменяет подстроку `"\\"` на слэш и несимвол.
Код ниже (https://github.com/oscript-library/json/blob/develop/src/json.os#L691):
```bsl
Позиция = Найти(Результат, "\u"); Пока Позиция Цикл
```
ищет маскированные символы уникода. И!! `Найти()` **находит** последовательность `"<слэш><фигня>u"`, считая её подходящей (игнорируя незнакомый суррогат).

Подобный код на C#:
```cs
			var src = @"\\up";
			var seq = src.Replace(@"\\", "\\\xFFFF");

			seq.IndexOf(@"\u", StringComparison.Ordinal);

			Console.WriteLine(seq.IndexOf(@"\u", StringComparison.Ordinal));          // -1
			Console.WriteLine(seq.IndexOf(@"\u", StringComparison.InvariantCulture)); // 0
			Console.WriteLine(seq.IndexOf(@"\u", StringComparison.CurrentCulture));   // 0

```
то есть, только `Ordinal` даёт правильный ответ.

Код на 1С:
```bsl
Строка = "\\up";
Строка = СтрЗаменить(Строка, "\\", "\" + Символ(65535));
Сообщить(Найти(Строка, "\u"));
```
говорит "0" - не найдено.

Итого, поведение функции `СтрЗаменить` отличается от ожидаемого в случаях с нечеловеческими символами уникода.

**Comment by EvilBeaver** [comment]
Да. конечно. Вешаю плашку баг?

**Comment by dmpas** [comment]
Ага. Осталось подумать, везде ли надо Ordinal делать.
