### ISSUE TITLE
Зависает Процесс.ПотокВывода.Прочитать при вызове "долгих" команд

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#402]
В результате расследования зависаний гитсинка с новым 1commands https://github.com/artbear/1commands/issues/14
я нарвался на ошибку движка :(

У меня есть тестовый гит-репо, в котором core.autocrlf = true (это сделано специально!!)

Запускаю тестовый скрипт для этого репо

```bsl
СтрокаЗапуска = "git add -A .";
Процесс = СоздатьПроцесс(СтрокаЗапуска, ".", Истина, Истина);
Процесс.Запустить();

ПериодОпросаВМиллисекундах = 200;
сообщить(20);
Если ПериодОпросаВМиллисекундах <> 0 Тогда
	Приостановить(ПериодОпросаВМиллисекундах);
КонецЕсли;
сообщить(30);
Если НЕ Процесс.Завершен ИЛИ Процесс.ПотокВывода.ЕстьДанные Тогда
	// Пока НЕ Процесс.Завершен ИЛИ Процесс.ПотокВывода.ЕстьДанные Цикл
	Если ПериодОпросаВМиллисекундах <> 0 Тогда
		Приостановить(ПериодОпросаВМиллисекундах);
	КонецЕсли;
	сообщить(40);
	
	ОчереднаяСтрокаВывода = Процесс.ПотокВывода.Прочитать(); // ВОТ ЗДЕСЬ ЗАВИСАЕМ !!
	сообщить(50); // TODO сюда выполнение не доходит!!!!!

	ОчереднаяСтрокаВывода = СтрЗаменить(ОчереднаяСтрокаВывода, Символы.ВК, "");
	сообщить(60);
	// Лог.Отладка("%2%1", ОчереднаяСтрокаВывода, Символы.ПС);
	// сообщить(70);
	
	// ЗаписьXML.ЗаписатьБезОбработки(ОчереднаяСтрокаВывода);
	сообщить(80);
КонецЕсли;
// КонецЦикла;

сообщить(90);
```

Как видно из кода, до `Сообщить(50)` выполнение не доходит, т.к. скрипт зависает вместе с гитом!

При этом при ручном запуске `git add -A .` выдает кучу сообщений по отличия CrLf для каждого файла и через небольшое время завершается успешно.

/cc @dmpas @EvilBeaver  Помогите!!
Без вашей помощи никак.

Прикладываю тестовый архив. Там и файлы, и тест.скрипт, и батник для его запуска :)
[process-bug.zip](https://github.com/EvilBeaver/OneScript/files/767289/process-bug.zip)

**Comment by artbear** [comment]
`Приостановить` можно убрать, он на зависание не влияет.

**Comment by EvilBeaver** [comment]
До исправления задачи по апи потоков ничего 100% хорошего не выйдет. Могу порекомендовать использовать не Прочитать, а ПрочитатьСтроку

**Comment by EvilBeaver** [comment]
А 100 вариант использовать перенаправление в файл

**Comment by khorevaa** [comment]
А возможность перенаправить в файл есть?

**Comment by nixel2007** [comment]
ПрочитатьСтроку точно так же зависает. От него как раз и перешли Прочитать, чтобы реже вызывать чтение из буфера

**Comment by EvilBeaver** [comment]
Бяда. Задачка на это есть, надо уже сделать. Там просто низкоуровневое все и тестировать тяжело.  Займусь

**Comment by JohnyDeath** [comment]
Можно чуть проще и без гита:
```bsl
Функция ВыполнитьДинамически(КолИтераций)
	ИмяВремФайла = ПолучитьИмяВременногоФайла("os");
	ТекстФайла = СтрШаблон("Сообщить("">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Количество итераций %1"");", КолИтераций);
	Для й = 1 По КолИтераций Цикл
		ТекстФайла = ТекстФайла + СтрШаблон("Сообщить(""Итерация № %1"");", й) + Символы.LF;
	КонецЦикла;

	Текст = Новый ТекстовыйДокумент;
	Текст.ДобавитьСтроку(ТекстФайла);
	Текст.Записать(ИмяВремФайла);

	СтрокаЗапуска = "oscript " + ИмяВремФайла;
	Процесс = СоздатьПроцесс(СтрокаЗапуска, , Истина, Истина);
	Процесс.Запустить();

	Пока НЕ Процесс.Завершен ИЛИ Процесс.ПотокВывода.ЕстьДанные Цикл

		ОчереднаяСтрокаВывода = Процесс.ПотокВывода.ПрочитатьСтроку(); 
		сообщить("Из процесса: " + ОчереднаяСтрокаВывода); 

	КонецЦикла;

	УдалитьФайлы(ИмяВремФайла);
КонецФункции

ВыполнитьДинамически(50000);
```

ВыполнитьДинамически(10000); - выполняется
ВыполнитьДинамически(50000); - не дождался


Вообще я ожидал, что буду видеть процесс накапливания сообщений вида "Из процесса: Итерация №---"
Но в итоге все сообщения вываливаются разом в конце. Это какая-то особенность шелла/vsc.. ?

**Comment by nixel2007** [comment]
В всц 1.9 переделали терминал в сторону быстрого непосредственного вывода, но все равно такие вещи лучше тестировать прямо из консоли

**Comment by JohnyDeath** [comment]
В консоли тоже самое (проверяю на 10000). Сначала висит, потом скопом выводит все строки

**Comment by dmpas** [comment]
исторически сложилось, что stdout - буферизированный вывод, то есть приложение не обязано выдавать его сразу (да и выдавать вообще - в случае падения). Потому "вжух и сразу 10000" - это обычное дело.

**Comment by EvilBeaver** [comment]
@JohnyDeath а вот формировать в памяти построчную строку из 100500 конкатенаций - это жестоко :) В таких случаях лучше сразу писать в файл через ЗаписьТекста, а не мучить выделятор памяти.

**Comment by EvilBeaver** [comment]
Закрываю:

Реализовал неблокирующее чтение из потоков процесса.
Коммиты: 65f0c46b2 c4be395688

Особенность (возможно Breaking change):

Методы **ЕстьДанные** **Прочитать** и **ПрочитатьСтроку** возвращают результат немедленно, показывая "Срез" на момент вызова. Отсутствие данных не означает конца потока. Оно означает, что на момент вызова в потоке данных не было.

Данные в потоке появляются "построчно". Т.е. не будет оборванных на середине строк.

**Comment by nixel2007** [comment]
По поводу breaking change - вроде у нас в скриптах всегда идёт дополнительная проверка на Процесс.Завершен, так что не должно поломать что-либо

**Comment by nixel2007** [comment]
> Отсутствие данных не означает конца потока. Оно означает, что на момент вызова в потоке данных не было.

А раньше было не так?

**Comment by EvilBeaver** [comment]
Раньше блокировалось и ждало пока данные поступят. Сейчас моментально возвращает результат. Часто пустой.

**Comment by EvilBeaver** [comment]
И по поводу Процесс.Завершен. Как только он завершен обязательно надо прочитать еще раз. Там хвост данных часто приезжает с задержкой уже после остановки процесса. Т.е. для длительного процесса цикл Пока Не Завершен () и потом еще раз Прочитать. Для короткого можно ждать щавершения и потом читать.

**Comment by nixel2007** [comment]
@artbear - обрати внимание на сообщение @EvilBeaver

**Comment by artbear** [comment]
@EvilBeaver Проверил поведение на последнем ночнике.
Указанный мной код на указанном архиве стал проходить.

**Но когда в этом коде я вместо Если вернул Пока (закомментировано), баг остался :(**

Проверял варианты
+ `Пока НЕ Процесс.Завершен ИЛИ Процесс.ПотокВывода.ЕстьДанные Цикл`
+ `Пока НЕ Процесс.Завершен Цикл`

Висим :(

Посмотришь?

**PS предлагаю переоткрыть ишуз!**

**Comment by EvilBeaver** [comment]
@artbear сбрось сюда конечный вариант кода, который зависает.
И на какой строчке

**Comment by artbear** [comment]
@EvilBeaver смотри TODO
```bsl
СтрокаЗапуска = "git add -A .";
Процесс = СоздатьПроцесс(СтрокаЗапуска, ".", Истина, Ложь);
Процесс.Запустить();

ПериодОпросаВМиллисекундах = 200;
сообщить(20);
Если ПериодОпросаВМиллисекундах <> 0 Тогда
	Приостановить(ПериодОпросаВМиллисекундах);
КонецЕсли;
сообщить(30);
//Если НЕ Процесс.Завершен ИЛИ Процесс.ПотокВывода.ЕстьДанные Тогда
Индекс = 0;
Пока НЕ Процесс.Завершен ИЛИ Процесс.ПотокВывода.ЕстьДанные Цикл
	Индекс = Индекс + 1;
	// Пока НЕ Процесс.Завершен ИЛИ Процесс.ПотокВывода.ЕстьДанные Цикл
	Если ПериодОпросаВМиллисекундах <> 0 Тогда
		Приостановить(ПериодОпросаВМиллисекундах);
	КонецЕсли;
	сообщить("40 - " + Индекс);
	
	ОчереднаяСтрокаВывода = Процесс.ПотокВывода.Прочитать();
	сообщить(50); // TODO сюда выполнение не доходит!!!!!

	ОчереднаяСтрокаВывода = СтрЗаменить(ОчереднаяСтрокаВывода, Символы.ВК, "");
	сообщить(60);
	// Лог.Отладка("%2%1", ОчереднаяСтрокаВывода, Символы.ПС);
	// сообщить(70);
	
	// ЗаписьXML.ЗаписатьБезОбработки(ОчереднаяСтрокаВывода);
	сообщить(80);
//КонецЕсли;
КонецЦикла;

сообщить(90);
```

**Comment by artbear** [comment]
Для приложенного к шапке архива

**Comment by artbear** [comment]
Итак, правильное решение - читать поток вывода и поток ошибок.
**Нужно задокументировать** анализ @EvilBeaver 
>Процесс не завершается, пока поток stderr открыт для чтения
Процесс не завершен. Он висит в процессах и ждет пока ты освободишь его от текста в stderr

Правильный код:
> 
```bsl
Пока НЕ Процесс.Завершен ИЛИ Процесс.ПотокВывода.ЕстьДанные ИЛИ Процесс.ПотокОшибок.ЕстьДанные Цикл
			Если ПериодОпросаВМиллисекундах <> 0 Тогда
				Приостановить(ПериодОпросаВМиллисекундах);
			КонецЕсли;
сообщить(40);

			ОчереднаяСтрокаВывода = Процесс.ПотокВывода.Прочитать();
			ОчереднаяСтрокаОшибок = Процесс.ПотокОшибок.Прочитать();
			Если Не ПустаяСтрока(ОчереднаяСтрокаВывода) Тогда
				Сообщить(ОчереднаяСтрокаВывода, СтатусСообщения.Информация);
			КонецЕсли;
			
			Если Не ПустаяСтрока(ОчереднаяСтрокаОшибок) Тогда
				Сообщить(ОчереднаяСтрокаОшибок, СтатусСообщения.Важное);
			КонецЕсли;
сообщить(50);
			
сообщить(60);
			// Лог.Отладка("%2%1", ОчереднаяСтрокаВывода, Символы.ПС);
// сообщить(70);

			// ЗаписьXML.ЗаписатьБезОбработки(ОчереднаяСтрокаВывода);
сообщить(80);
		КонецЦикла;
```

**Comment by artbear** [comment]
Теперь эта магия :) запрятана в 1commands!

Управляется методом `ПоказыватьВыводНемедленно`, который и вызывает код, аналогичный коду выше.
