### ISSUE TITLE
Для режима отладки необходимо понимание откуда подключены библиотеки

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#403]
Как разработчику скриптов,  при установке режима отладки скрипта (в в движке oscript) необходимо понимание последовательно подключения библиотек, с указанием путей к файлам. 

Для получение более прозрачной отладки использовая библиотек

**Comment by EvilBeaver** [comment]
Понимание и так есть, насколько я понимаю - подключается всегда из настроек в oscript.cfg.

Сначала системный каталог, потом из lib.additional в порядке следования.

**Comment by dmpas** [comment]
мне кажется, тут имеется в виду возможность видеть, какая библиотека из какой была использована, чтобы, к примеру, конфликты отследить. Сам вчера сел и почти запилил такое. Правда потом подумал и удалил.

**Comment by EvilBeaver** [comment]
Мне больше интересно, как это будет выглядеть для конечного пользователя. Как эти трейсы смотреть потом?

**Comment by artbear** [comment]
>Как разработчику скриптов, при установке режима отладки скрипта (в в движке oscript) необходимо понимание последовательно подключения библиотек, с указанием путей к файлам.

Самый простой путь - это доработать системный загрузчик библиотек `OneScript\lib\package-loader.os`

Например, я для расследования сделал такой код/костыль (добавил вывод сообщений)
```bsl
Перем ПоказатьСообщенияЗагрузки;

Процедура ПриЗагрузкеБиблиотеки(Путь, СтандартнаяОбработка, Отказ)
Вывести("ПриЗагрузкеБиблиотеки " + Путь);	
	ФайлМанифеста = Новый Файл(ОбъединитьПути(Путь, "lib.config"));
	
	Если ФайлМанифеста.Существует() Тогда
		СтандартнаяОбработка = Ложь;
		ОбработатьМанифест(ФайлМанифеста.ПолноеИмя, Путь, Отказ);
	Иначе
		Вывести("ОбработатьСтруктуруКаталоговПоСоглашению");
		ОбработатьСтруктуруКаталоговПоСоглашению(Путь, СтандартнаяОбработка, Отказ);
	КонецЕсли;
	
КонецПроцедуры

Процедура ОбработатьМанифест(Знач Файл, Знач Путь, Отказ)
	
	Чтение = Новый ЧтениеXML;
	Чтение.ОткрытьФайл(Файл);
	Чтение.ПерейтиКСодержимому();
	
	Если Чтение.ЛокальноеИмя <> "package-def" Тогда
		Отказ = Истина;
		Чтение.Закрыть();
		Возврат;
	КонецЕсли;
	
	Пока Чтение.Прочитать() и Чтение.ТипУзла = ТипУзлаXML.НачалоЭлемента Цикл
		
		Если Чтение.ЛокальноеИмя = "class" Тогда
			ФайлКласса = Новый Файл(Путь + "/" + Чтение.ЗначениеАтрибута("file"));
			Если ФайлКласса.Существует() и ФайлКласса.ЭтоФайл() Тогда
				Идентификатор = Чтение.ЗначениеАтрибута("name");
				Если Не ПустаяСтрока(Идентификатор) Тогда
					Вывести(СтрШаблон("класс %1, файл %2", Идентификатор, ФайлКласса.ПолноеИмя));
					ДобавитьКласс(ФайлКласса.ПолноеИмя, Идентификатор);
				КонецЕсли;
			Иначе
				ВызватьИсключение "Не найден файл " + ФайлКласса.ПолноеИмя + ", указанный в манифесте";
			КонецЕсли;
			
			Чтение.Прочитать(); // в конец элемента
		КонецЕсли;

		Если Чтение.ЛокальноеИмя = "module" Тогда
			ФайлКласса = Новый Файл(Путь + "/" + Чтение.ЗначениеАтрибута("file"));
			Если ФайлКласса.Существует() и ФайлКласса.ЭтоФайл() Тогда
				Идентификатор = Чтение.ЗначениеАтрибута("name");
				Если Не ПустаяСтрока(Идентификатор) Тогда
					Вывести(СтрШаблон("модуль %1, файл %2", Идентификатор, ФайлКласса.ПолноеИмя));
					ДобавитьМодуль(ФайлКласса.ПолноеИмя, Идентификатор);
				КонецЕсли;
			Иначе
				ВызватьИсключение "Не найден файл " + ФайлКласса.ПолноеИмя + ", указанный в манифесте";
			КонецЕсли;
			
			Чтение.Прочитать(); // в конец элемента
		КонецЕсли;
		
	КонецЦикла;
	
	Чтение.Закрыть();
	
КонецПроцедуры

Процедура ОбработатьСтруктуруКаталоговПоСоглашению(Путь, СтандартнаяОбработка, Отказ)
	
	КаталогКлассов = Новый Файл(ОбъединитьПути(Путь, "Классы"));
	КаталогМодулей = Новый Файл(ОбъединитьПути(Путь, "Модули"));
	
	Если КаталогКлассов.Существует() Тогда
		Файлы = НайтиФайлы(КаталогКлассов.ПолноеИмя, "*.os");
		Для Каждого Файл Из Файлы Цикл
			Вывести(СтрШаблон("класс %1, файл %2", Файл.ИмяБезРасширения, Файл.ПолноеИмя));
			СтандартнаяОбработка = Ложь;
			ДобавитьКласс(Файл.ПолноеИмя, Файл.ИмяБезРасширения);
		КонецЦикла;
	КонецЕсли;
	
	Если КаталогМодулей.Существует() Тогда
		Файлы = НайтиФайлы(КаталогМодулей.ПолноеИмя, "*.os");
		Для Каждого Файл Из Файлы Цикл
			Вывести(СтрШаблон("модуль %1, файл %2", Файл.ИмяБезРасширения, Файл.ПолноеИмя));
			СтандартнаяОбработка = Ложь;
			ДобавитьМодуль(Файл.ПолноеИмя, Файл.ИмяБезРасширения);
		КонецЦикла;
	КонецЕсли;
	
КонецПроцедуры

Процедура Вывести(Знач Сообщение)
	Если ПоказатьСообщенияЗагрузки Тогда
		Сообщить(Сообщение);
	КонецЕсли;
КонецПроцедуры

ПоказатьСообщенияЗагрузки = Ложь;
```

Когда мне нужно разобраться в последовательности, я изменяю в конце файла
`ПоказатьСообщенияЗагрузки = Истина;` 

Раза 3 за полгода помогало.

Возможно добавить какой-то флаг в командную строку оскрипт и передавать его в событие 
`ПриЗагрузкеБиблиотеки`
например, добавив 4 параметр
`ПриЗагрузкеБиблиотеки(Путь, СтандартнаяОбработка, Отказ, ВыводитьЛогЗагрузки)`

тогда будет легко проверять загрузку.

**Comment by artbear** [comment]
Либо по ключу из ком.строки добавить вывод лога в методы движка `ДобавитьКласс` и `ДобавитьМодуль`
в этому случае загрузчик менять не придется

**Comment by EvilBeaver** [comment]
> в этому случае загрузчик менять не придется

Ну ты троллище! :) В этом случае придется менять движок. Что, в сравнении с банальной правкой скрипта кажется какой-то сверхзадачей.

**Comment by artbear** [comment]
>Возможно добавить какой-то флаг в командную строку оскрипт и передавать его в событие
ПриЗагрузкеБиблиотеки
например, добавив 4 параметр
ПриЗагрузкеБиблиотеки(Путь, СтандартнаяОбработка, Отказ, ВыводитьЛогЗагрузки)

@EvilBeaver может быть, рано закрыл?
Что насчет реализовать фичу из цитаты ?

**Comment by EvilBeaver** [comment]
Не рано. Выводить лог можно и так как ты сделал. На уровне движка такому не место. Кроме того, флаговые параметры в методах вызывают у меня немотивированную агрессию

**Comment by EvilBeaver** [comment]
Кто и как установит этот параметр в True?

**Comment by artbear** [comment]
Тот, кто запустит 1скрипт со спец.параметром

вт, 20 Июн 2017, 16:51 Andrei Ovsiankin <notifications@github.com>:

**Comment by EvilBeaver** [comment]
Все просто. Дорабатывается штатный лоадер, который входит в поставку. Он проверяет установку специальной переменной в окружении. Если она есть - делает эти сообщить. @artbear, сделаешь?

**Comment by artbear** [comment]
Да, такой вариант устраивает.

Да, сделаю.
По срокам пока не могу сказать.

Ишуз переоткроешь?
