### ISSUE TITLE
Повторное подключение классов и модулей. Различное поведение

### ISSUE THREAD

**Issue by Stepa86** [EvilBeaver/OneScript#404]
Если какой-то класс подключается дважды из разных мест, то все проходит нормально и используется последний. Если же таким образом подключается модуль, то падает исключение.
Если в OneScript\lib\package-loader.os добавить вывод сообщений при подключении, то для копии логоса будет выглядеть так запуск теста

```bsl
PS G:\git\Forks\Logos> 1testrunner -run G:\git\Forks\Logos\tests\logos-test.os
Подключаю манифест C:\Program Files (x86)\OneScript\lib\1testrunner
        Подключаю Класс Тестер - C:\Program Files (x86)\OneScript\lib\1testrunner\testrunner.os
Подключаю манифест C:\Program Files (x86)\OneScript\lib\asserts
        Подключаю Модуль Утверждения - C:\Program Files (x86)\OneScript\lib\asserts\src\xunit-asserts.os
        Подключаю Модуль Ожидаем - C:\Program Files (x86)\OneScript\lib\asserts\src\bdd-asserts.os
Подключаю манифест C:\Program Files (x86)\OneScript\lib\tempfiles
        Подключаю Модуль ВременныеФайлы - C:\Program Files (x86)\OneScript\lib\tempfiles\ВременныеФайлы.os
        Подключаю Класс МенеджерВременныхФайлов - C:\Program Files (x86)\OneScript\lib\tempfiles\ВременныеФайлы.os
Подключаю манифест C:\Program Files (x86)\OneScript\lib\logos
        Подключаю Модуль УровниЛога - C:\Program Files (x86)\OneScript\lib\logos\src\levels.os
        Подключаю Класс Лог - C:\Program Files (x86)\OneScript\lib\logos\src\log.os
        Подключаю Модуль Логирование - C:\Program Files (x86)\OneScript\lib\logos\src\log-manager.os
        Подключаю Класс ВыводЛогаВФайл - C:\Program Files (x86)\OneScript\lib\logos\src\file-appender.os
        Подключаю Класс ВыводЛогаВКонсоль - C:\Program Files (x86)\OneScript\lib\logos\src\console-appender.os
        Подключаю Класс ОсновнаяРаскладкаСообщения - C:\Program Files (x86)\OneScript\lib\logos\src\basic-layout.os
1testrunner, ver. 1.2
Подключаю манифест G:\git\Forks\Logos
        Подключаю Класс Лог - G:\git\Forks\Logos\src\log.os
        Подключаю Класс ВыводЛогаВФайл - G:\git\Forks\Logos\src\file-appender.os
        Подключаю Класс ВыводЛогаВКонсоль - G:\git\Forks\Logos\src\console-appender.os
        Подключаю Класс ОсновнаяРаскладкаСообщения - G:\git\Forks\Logos\src\basic-layout.os
        Подключаю Класс НастройкиЛогирования - G:\git\Forks\Logos\src\log-options.os
        Подключаю Модуль УровниЛога - G:\git\Forks\Logos\src\levels.os
Не удалось загрузить тест G:\git\Forks\Logos\tests\logos-test.os
{Модуль C:\Program Files (x86)\OneScript\lib\package-loader.os / Ошибка в строке: 52 / Невозможно загрузить модуль УровниЛога. Такой символ уже определен.}
```
Хочется, чтобы поведение для модулей и для классов было одинаковым. Либо всем падать, либо подключать последний.

**Comment by Stepa86** [comment]
Вот этот кэтч есть в добавлении модуля и отсутствует в добавлении класса https://github.com/EvilBeaver/OneScript/blob/36c8480caaa342d2b827c210f49966be42ffcc34/src/ScriptEngine.HostedScript/LibraryLoader.cs#L116

**Comment by EvilBeaver** [comment]
То, что классы из разных мест подключаются - это странно. Должны так же падать с ошибкой "Тип уже зарегистрирован". Это где-то в дебрях TypeManager.cs

**Comment by EvilBeaver** [comment]
Проверил. На самом деле, если подключается один и тот же тип то используется первый. А исключение не выбрасывается. Надо переделывать.

**Comment by nixel2007** [comment]
@EvilBeaver ты не сломаешь таким образом `#Использовать asserts`, например, среди россыпи тестов?
Или точечное подключение не в main.os, а в конкретных подклассах/подмодулях?

Не, я помню про глобальный контекст и все такое, но если внезапно мой скрипт начнет падать при подключении логоса из-за того, что логос подключаеся в каком-нибудь cmdline - я "обижусь"

**Comment by nixel2007** [comment]
Апдейт - из разных мест. Слепая моя голова, вопрос снимаю.

**Comment by EvilBeaver** [comment]
Вообще там идет хеширование кода. Если подклбчаем из разных мест, но идентичные файлы то ругаться не будет. Вот только эта проверка сейчас не вызывается.
