### ISSUE TITLE
ошибка при gitsync init

### ISSUE THREAD

**Issue by Dumsik** [EvilBeaver/OneScript#409]
выполняю gitsync init D:\1c_Dev\Arautom\_ХранилищеКонфигурации D:\1cGitSync\KA\SrcConfig выходит ошибка 
GitSync v2.1
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\src\core\Классы\МенеджерСинхронизации.os / Ошибка в строке: 842 / Метод объекта не обнаружен (ДобавитьКоманду)}

oscript последний 1Script Execution Engine. Version 1.0.15.260
устанавливал все по инструкции с сайта. Библиотека 1commands есть.
вывод opm list
Пакеты в системном каталоге библиотек <C:\Program Files (x86)\OneScript\lib>:
1commands
1testrunner
asserts
cmdline
fs
gitsync
json
logos
opm
strings
tempfiles
tool1cd
v8runner

**Comment by EvilBeaver** [comment]
Перенаправил в https://github.com/oscript-library/gitsync/issues/52
