### ISSUE TITLE
В справке из командной строки нет описания ключа "-env" для команды "-check"

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#414]
Две задачи:

1. Нужно доработать описание из http://oscript.io/docs/page/running 
 ключ -env принимает параметр через пробел, а не через знак =
Правильный вызов `oscript -check .\src\Классы\КомандаVersion.os -env .src\main.os`
```
PS C:\projects\vanessa-runner> oscript -check .\src\Классы\КомандаVersion.os -env .src\main.os
{Модуль C:\projects\vanessa-runner\src\Классы\КомандаVersion.os / Ошибка в строке: 25 / Неизвестный символ: ПараметрыСистемы}
        Сообщить(ПараметрыСистемы.ВерсияПродукта());
```
Неправильный вызов через = `oscript -check .\src\Классы\КомандаVersion.os -env=.src\main.os`
```
PS C:\projects\vanessa-runner> oscript -check .\src\Классы\КомандаVersion.os -env=.src\main.os
System.ArgumentException: Путь имеет недопустимую форму.
   в System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.GetFullPathInternal(String path)
   в ScriptEngine.Environment.ScriptSourceFactory.FromFile(String path)
   в oscript.CheckSyntaxBehavior.Execute()
   в oscript.Program.Main(String[] args)
```

2. Нужно добавить доработанное указанное описание в справку командной строки

---

### Раздел Проверка синтаксиса

Проверка синтаксиса предполагает попытку компиляции приложения и всех связанных библиотек.

`oscript.exe -check <файл-скрипта> [-env=<файл-точки-входа>]`
Необязательный параметр -env позволяет задать точку входа в которой указаны внешние библиотеки. Обычно это используется для того, чтобы инициализировать все внешние (по отношению к проверяемому файлу) библиотеки.

Например, если проверяется некий модуль, в котором нет директив "Использовать", но применяются импортированные модули, то параметр -env позволяет указать другой файл, который содержит все необходимые директивы импорта. Как правило, это файл с точкой входа в приложение.

**Comment by ret-Phoenix** [comment]
https://github.com/EvilBeaver/OneScript/blob/develop/src/oscript/BehaviorSelector.cs#L59-L62
Можешь приложить файлы, на которых можно смоделировать?
