### ISSUE TITLE
Ошибка установки пакета all <404> при выполнении opm update all

### ISSUE THREAD

**Issue by Dumsik** [EvilBeaver/OneScript#418]
c:\Program Files (x86)\OneScript>opm update all
OneScript Package Manager v0.9.3

ИНФОРМАЦИЯ - Скачиваю файл: all.ospx
ИНФОРМАЦИЯ - Ошибка установки пакета all <404>
1Script Execution Engine. Version 1.0.17.44

Причем opm update opm корректно отрабатывает

**Comment by EvilBeaver** [comment]
По-моему, all надо писать с черточками: --all

**Comment by nixel2007** [comment]
с одной черточкой - `opm update -all`

**Comment by nixel2007** [comment]
О чем, кстати, и написано в справке
```
C:\Users\nixel>opm help update
update - Обновить пакет
Параметры:
 <ИмяПакета> - Имя пакета в хабе. Чтобы установить конкретную версию, используйте ИмяПакета@ВерсияПакета
 -all - Обновить все установленные пакеты
 -f - Указать файл из которого нужно установить пакет
```

**Comment by Dumsik** [comment]
Упс. Извиняюсь, не досмотрел. Но если бы писал пакет all не найден на сервере я бы сразу понял свою ошибку, а так 404, понятно not found но не понятно что.

**Comment by nixel2007** [comment]
@Dumsik Регайте ишуз в репе opm. Понятные ошибки - это тоже очень важно :)
