### ISSUE TITLE
Несовместимость с 1С при удалении файлов из несуществующего пути

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#419]
УдалитьФайлы("C:\нет такого пути", "*.txt");

Script started: 17.03.2017 19:03:55
{Модуль C:\distr_build.os / Ошибка в строке: 2 / Внешнее исключение (System.IO.DirectoryNotFoundException): Не удалось найти часть пути "C:\нет такого пути".}    
  УдалитьФайлы("C:\нет такого пути", "*.txt");

**Comment by artbear** [comment]
1скрипт ведет себя верно. Это правильное поведение для скриптового движка

пт, 17 Мар 2017, 19:08 Andrei Ovsiankin <notifications@github.com>:
