### ISSUE TITLE
Перенос стандартных коллекций С# в язык OneScript

### ISSUE THREAD

**Issue by fishca** [EvilBeaver/OneScript#421]

**Comment by EvilBeaver** [comment]
А что имеется в виду? Соответствие и Массив и так на базе стандартных коллекций

**Comment by dmpas** [comment]
Я так полагаю, Стэки какие-нибудь, ХэшСеты. Да, тут лучше на берегу список обговорить.

**Comment by fishca** [comment]
Queue, Stack, HashSet, Hashtable, Dictionary в общем что что лежит в System.Collections.Generic, если это вообще возможно конечно.

**Comment by ret-Phoenix** [comment]
Есть реальные задачи, требующие этих объектов?
Сделать обертку для них не долго. Первые 2 вообще дело нескольких минут, Dictinary - не думаю что нужно, Структура вполне заменяет.

**Comment by EvilBeaver** [comment]
Да, с очередью, хэшсетом и таблицей непонятно. Все они запросто реализуются на существующих коллекциях 1С.

**Comment by ret-Phoenix** [comment]
https://github.com/ret-Phoenix/OneScript-Collections

**Comment by EvilBeaver** [comment]
Закрываю, т.к. сделано вовне и к движку не относится. Ок?
