### ISSUE TITLE
СтрПолучитьСтроку - проблема с разделителем строк

### ISSUE THREAD

**Issue by ret-Phoenix** [EvilBeaver/OneScript#424]
[module.txt](https://github.com/EvilBeaver/OneScript/files/954700/module.txt)

[НавигацияПоМодулю.txt](https://github.com/EvilBeaver/OneScript/files/954701/default.txt)
![selectvaluesharp](https://cloud.githubusercontent.com/assets/8619544/25381066/10e518ce-29bb-11e7-9af5-9225e98d7de2.jpg)

Не понимаю как происходит считывание текста

**Comment by ret-Phoenix** [comment]
Из приколов, удалил 1 пустую строку, сохранил - заработало.
Складывается впечатление что разделитель строк как-то не так был записан

**Comment by EvilBeaver** [comment]
Картинка не читается. Закрывать задачу?

**Comment by ret-Phoenix** [comment]
Пусть пока повисит, потом в движке отладчиком покопаюсь, может найду в чем дело.
такое возникает на ряде модулей (типовая упп либо erp)

**Comment by EvilBeaver** [comment]
Тогда переформулируй заголовок плиз.
