### ISSUE TITLE
Остановка по исключению

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#425]
Обеспечить остановку по исключению (в отладчике)

**Comment by best-tech** [comment]
А как пользоваться отладчиком?

**Comment by nixel2007** [comment]
@best-tech отладчик пока не опубликован в виде готового расширения. только собирать самому.

**Comment by EvilBeaver** [comment]
Уу брат, это сакральное знание, тут без поедания лягушек на кладбище никак...

**Comment by best-tech** [comment]
Я не хочу ни лягушек ни на кладбище, хочу F9;)

**Comment by akpaevj** [comment]
Закрыто в #1434 . Надо было в коммите тегнуть(
