### ISSUE TITLE
Вынести методы работы с переменными окружения в глобальный контекст

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#426]
Кажется, что удобнее работать с переменными окружения напрямую, не создавая объект СистемнаяИнформация.

Глобальные методы УстановитьПеременнуюСреды/ПолучитьПеременнуюСреды и т.п. вынести из объекта СистемнаяИнформация в глобальный контекст.

Старый вариант оставить для совместимости.

**Comment by EvilBeaver** [comment]
@dmpas @pumbaEO @nixel2007 и anybody else - что скажете?

**Comment by dmpas** [comment]
нечасто пользуюсь, сложно сказать.

**Comment by artbear** [comment]
Да, с глобальными методам поудобнее работать.
сразу в один вызов получаешь нужное значение, просто и все сразу понятно.

**Comment by nixel2007** [comment]
сам хотел предложить :)

**Comment by ret-Phoenix** [comment]
Взял задачу себе.

**Comment by ret-Phoenix** [comment]
При создании СИ будет писаться в консоль: SystemInfo deprecated, use GlobalContext
Подойдет?

**Comment by kuntashov** [comment]
> Подойдет?

Задача вроде только про методы УстановитьПеременнуюСреды() и ПолучитьПеременнуюСреды(), а в СИ есть и другие методы и свойства, с чего бы она вся была не рекомендованной к использованию?

Или решили все свойства СИ вынести в глобальный контекст?
Меня не спрашивали, но я все равно против переноса остальных свойств методов в глобальный контекст :)

**Comment by EvilBeaver** [comment]
Только по переменны среды

**Comment by ret-Phoenix** [comment]
Там всего 3 метода: ПеременныеСреды, Получить/Установить ПеременнуюСреды
и 3 свойства: ИмяКомпьютера, ВерсияОС, Версия (1С скрипт)
Если выносим 3 метода, в СИ останутся 3 свойства. Их тоже можно перенести в ГК.

**Comment by ret-Phoenix** [comment]
еще бы добавил свойство: ИмяПользователя(). Брать из System.Environment.UserName. Сейчас в OneScript не реализовано.
\+ можно еще: System.Environment.UserDomainName

**Comment by EvilBeaver** [comment]
Нет. Давайте в СИ оставим то, что есть в 1С. Плюс, по пользователю тоже можно туда добавить. (Обсуждаемо) А вот переменные среды это не совсем ИнформацияОСистеме и эту функциональность оттуда надо вынести.

**Comment by ret-Phoenix** [comment]
В таком случае "SystemInfo deprecated, use GlobalContext" надо будет выводить только в 3 методах, а не при создании Класса.

По пользователю:

> ПользовательИнформационнойБазы.ПользовательОС (InfoBaseUser.OSUser)
> ПользовательИнформационнойБазы (InfoBaseUser)
> ПользовательОС (OSUser)
> Использование:
> 
> Чтение и запись. 
> Описание:
> 
> Тип: Строка. 
> Содержит строку, идентифицирующую пользователя операционной системы при установленном свойстве АутентификацияОС.
> Формат строки: \\ИмяДомена\ИмяПользователя. 
> При установке наличие пользователя в операционной системе не проверяется.
> 
> Доступность: 
> 
> Сервер, толстый клиент, внешнее соединение. 
> Примечание:
> 
> Доступно только пользователю с административными правами.

**Comment by EvilBeaver** [comment]
Да

4 Май 2017 г. 14:20 пользователь "ret-Phoenix" <notifications@github.com>
написал:

**Comment by kuntashov** [comment]
> SystemInfo deprecated, use GlobalContex

Тогда надо про сами  методы говорить в предупреждении, что-то вроде такого:

```
SystemInfo.SetEnvironmentVariable() is deprecated, use SetEnvironmentVariable() from global context
```

**Comment by ret-Phoenix** [comment]
Да. так и сделано уже: "DeprecationWarning: 'SystemInfo.EnvironmentVariables()' is deprecated, use 'EnvironmentVariables' from global context"

**Comment by ret-Phoenix** [comment]
у кого под рукой есть машина без домена?

**Comment by artbear** [comment]
у меня

чт, 4 мая 2017 г. в 15:13, ret-Phoenix <notifications@github.com>:

**Comment by ret-Phoenix** [comment]
Спасибо, уже проверил на 2 шт )
