### ISSUE TITLE
Не отрабатывает ЗаписьZipФайла для файлов больше 4 Гб.

### ISSUE THREAD

**Issue by Tavalik** [EvilBeaver/OneScript#433]
Доброго времени суток.

Есть скрипт, который занимается копированием файловых баз. Скрипт создает архив файла 1Cv8.1CD. Пример кода:

ЗаписьZip = Новый ЗаписьZipФайла;
ЗаписьZip.Открыть(ИмяАрхива);
ЗаписьZip.Добавить("D:\WorkBase\1Cv8.1CD");
ЗаписьZip.Записать();

Не отрабатывает на файлах, больше 4 Гб.

Текст ошибки: Внешнее исключение (Ionic.Zip.ZipException): Compressed or Uncompressed size, or offset exceeds the maximum value. Consider setting the UseZip64WhenSaving property on the ZipFile instance.

В 1С:Предприятие 8.3 (8.3.8.2054) код работает без ошибок.

Не сталкивались с подобной проблемой?

P. S. Спасибо за столь клевый инструмент. :)

**Comment by SkyPunster** [comment]
А какая разрядность системы и какая файловая система? Если FAT32, например, то там ограничение файловой системы как раз 4 ГБ вроде. Это отпадает, если с платформы на тот же диск пишется.
Возможно еще что скрипт по x32 работает, а платформа под x64 (если у вас она x64).

**Comment by Tavalik** [comment]
NTFS, Windows x64. Проверял на 8.1 и на Server 2008 R2.

**Comment by dmpas** [comment]
@Tavalik попробуйте https://ci.appveyor.com/api/buildjobs/qkxq9ooaxxbjy8mo/artifacts/oscript.zip

**Comment by Tavalik** [comment]
Спасибо! Вот это оперативность! Все работает. 

А в релизе когда примерно это изменение ждать?

**Comment by dmpas** [comment]
@Tavalik когда вольют, пойдёт в ночник. Когда релиз - неизвестно.
