### ISSUE TITLE
Добавить класс "ИнформацияОДиске"

### ISSUE THREAD

**Issue by ret-Phoenix** [EvilBeaver/OneScript#439]
АПИ: https://github.com/ret-Phoenix/onescript-extensions/blob/dev/docs/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F%D0%9E%D0%94%D0%B8%D1%81%D0%BA%D0%B5.md

**Comment by dmpas** [comment]
Конструктор не понятен.
Под линухом что будет выдавать весь этот функционал?

**Comment by ret-Phoenix** [comment]
Конструктором передается имя диска, под linix за маунтинговые диски
https://github.com/mono/mono/blob/master/mcs/class/corlib/System.IO/DriveInfo.cs

Конструктор: 

`ИнформацияОДиске = Новый ИнформацияОДиске(Новый Окружение().ИменаЛогическихДисков[0]);`

Как Travis настрою - прогоню тест под Linux

**Comment by dmpas** [comment]
убунту под винду не пробовал ещё? Спасает во многих случаях.

**Comment by ret-Phoenix** [comment]
Пока нет, на работе у меня Win7, Дома 10. Но лучше настрою виртуального сборщика

**Comment by dmpas** [comment]
Приложу, как это выглядит под убунтой
[example.txt](https://github.com/EvilBeaver/OneScript/files/1021820/example.txt)

https://gist.github.com/dmpas/5231a570945ef9f5aa988716a292ad1a
