### ISSUE TITLE
Добавить в ГК методы: Сигнал + ОчиститьСообщения

### ISSUE THREAD

**Issue by ret-Phoenix** [EvilBeaver/OneScript#440]
ОчиститьСообщения - по сути есть в Консоль.Очистить(), но в 1С это в ГК

**Comment by EvilBeaver** [comment]
А что за Сигнал?

**Comment by ret-Phoenix** [comment]
Просто Бип)
Иногда бывает удобно, чтобы по завершении обработки пикнул комп.

**Comment by EvilBeaver** [comment]
ОчиститьСообщения, кажется, что не нужен. А Консоль.Сигнал пусть будет, why not?

**Comment by JohnyDeath** [comment]
Почему не нужен "ОчиститьСообщения"?

**Comment by ret-Phoenix** [comment]
он есть в классе Консоль

**Comment by nixel2007** [comment]
а как же "упрощение портирования 1с кода"?

**Comment by EvilBeaver** [comment]
@nixel2007 вброс не засчитан. Портирование кода с ОчиститьСообщения вряд ли будет 1-в-1 для консольного приложения. Но если считаете, что метод нужен - не возражаю.

**Comment by dmpas** [comment]
по-моему, метод нужен.

**Comment by nixel2007** [comment]
не считайте за вброс, но разве Сигнал относится к консоли? это же чистый системный beep, который вообще не завязан на способ взаимодействия с пользователем.

**Comment by dmpas** [comment]
Системный бип идёт на сервере, а консоль.сигнал должна бипнуть на клиенте. Ssh и всё такое.

**Comment by EvilBeaver** [comment]
Ты не поверишь, но сигнал - это символ в ascii

**Comment by nixel2007** [comment]
@dmpas хм, интересная мысль.

**Comment by nixel2007** [comment]
@EvilBeaver а вот это удивительно :) не знал :)
