### ISSUE TITLE
Расширить информацию об "Окружении"

### ISSUE THREAD

**Issue by ret-Phoenix** [EvilBeaver/OneScript#441]
АПИ: https://github.com/ret-Phoenix/onescript-extensions/blob/dev/docs/%D0%9E%D0%BA%D1%80%D1%83%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5.md

Как вариант можно перенести класс как есть, т.к. прямого аналога в OneScript нет, включить в СИ не вижу смысла.

**Comment by EvilBeaver** [comment]
Давайте включим все это в СИ, чтобы не дублировать. Уж больно похожи классы друг на друга?

**Comment by ret-Phoenix** [comment]
Очень даже похожи, тогда допилю, вчера уже начал перенос.
По специальным папкам, предлагаю включить только те, что в Mono реализованы, чтобы не было различного поведения скрипта под разными ОС.
