### ISSUE TITLE
Значение не является значением объектного типа для колонки таблицы значений

### ISSUE THREAD

**Issue by vsuh** [EvilBeaver/OneScript#444]
**oscript** ver. 1.0.17.73

```bsl
 времТаблица = Новый ТаблицаЗначений;
 времТаблица.Колонки.Добавить("ИБ", "Строка");

```
возвращает ошибку:
`{Модуль модуль.os / Ошибка в строке: NN / Значение не является значением объектного типа}`
англоязычное наименование метода возвращает ту же ошибку.

```bsl
  времТаблица = Новый ТаблицаЗначений;
  Сообщить(времТаблица.Колонки);

```
`КоллекцияКолонокТаблицыЗначений`

**Comment by nixel2007** [comment]
Второй параметр должен быть ОписаниеТипов, а не строка.

**Comment by vsuh** [comment]
строка тоже допускается
на версии 1.0.16.41 скрипт работает без ошибок

**Comment by vsuh** [comment]
Нашел еще машину с oscript
```bsl
СИ = Новый СистемнаяИнформация;
Сообщить("OSCRIPT: вер. " +СИ.Версия); 
ТЗ = Новый ТаблицаЗначений;
ТЗ.Колонки.Добавить("Имя", "Строка");
Сообщить(ТЗ.Колонки.Количество());

```
OSCRIPT: вер. 1.0.17.50
1

**Comment by dmpas** [comment]
@vsuh раньше этот параметр просто игнорировался, потому там допускалось вообще, что угодно.
теперь там согласно синтаксис-помощника только ОписаниеТипов.
