### ISSUE TITLE
Параметр "ИмяВыходногоФайла" в методах объекта HTTPСоединение

### ISSUE THREAD

**Issue by afanasko** [EvilBeaver/OneScript#447]
Если в качестве параметра "ИмяВыходногоФайла" методов: **ВызватьHTTPМетод**,  **ОтправитьДляОбработки**, **Получить** передать пустую строку, то OneScript вываливается на исключение "Пустое имя пути не допускается". В 1С пустая строка в этом параметре допускается и не приводит к возникновению исключения.

**Comment by EvilBeaver** [comment]
Спасибо.

**Comment by EvilBeaver** [comment]
@afanasko сможешь починить на ветке release/1.0.17?

**Comment by afanasko** [comment]
@EvilBeaver, на выходных постараюсь сделать.

**Comment by EvilBeaver** [comment]
@afanasko сделано же? Закрываю?

**Comment by afanasko** [comment]
Ага, сделано.
