### ISSUE TITLE
АргументыКоманднойСтроки - фиксированный массив

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#450]
Зачем для `АргументыКоманднойСтроки` выделен свой велосипедо-класс, если по сути это `ФиксированныйМассив`. Из плюшек перехода на ФиксированныйМассив такие вещи из коробки, как `Найти` и `Получить`.

**Comment by EvilBeaver** [comment]
Руками и ногами за. Сам давно такое хочу. Решим вопрос обратной совместимости сейчас как-нить? Или тупо грохнем тип?

**Comment by dmpas** [comment]
Тупо грохнем тип. Мне кажется, никто не проверяет нигде на тип КоллекцияАргументовКоманднойСтроки.

**Comment by ret-Phoenix** [comment]
Может сначала Deprecated сделаем?

**Comment by artbear** [comment]
Нет, при столь малой скорости выпуска релизов лучше сразу грохать, тем более, что разница в клиентском не будет видна или почти незаметна

**Comment by EvilBeaver** [comment]
Грохаем

8 Июн 2017 г. 10:00 пользователь "Artur Ayukhanov" <notifications@github.com>
написал:
