### ISSUE TITLE
Переопределять каталог библиотек в переменной окружения

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#451]
По мотивам задачи #385 

Нужна переменная окружения, позволяющая переопределить конфигурационные параметры движка из файла oscript.cfg.

**Comment by artbear** [comment]
@EvilBeaver А где дока на `OSCRIPT_CONFIG` ?

**Comment by EvilBeaver** [comment]
Шутишь, я только закодить успел а ты доку хочешь

**Comment by artbear** [comment]
Я хотел бы, чтобы не забылось про доку.
Я обычно либо не закрываю задачу, добавив в че-лист невыполненную задачу по
доке,
Либо создаю новую задачу на доку.
Пока ты в контексте, сделай что-то подобное.

вт, 20 Июн 2017, 16:48 Andrei Ovsiankin <notifications@github.com>:
