### ISSUE TITLE
Дублировать сообщения от движка на русском

### ISSUE THREAD

**Issue by Stepa86** [EvilBeaver/OneScript#453]
Предлагаю дополнить сообщение 

> WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated, use 'GetEnvironmentVariable' from global context

руководством к действию на русском. Например, 

> Используйте вместо СистемнаяИнформация.ПолучитьПеременнуюСреды( глобальный метод ПолучитьПеременнуюСреды(

**Comment by EvilBeaver** [comment]
Я не против. Но делать не буду. Опенсорс и все такое :)

**Comment by dvakor** [comment]
Предложение хорошее, учитывая, что миссия проекта (как я понял статью Бивера) сделать скриптовый движок для 1Сников, которые не знают ничего кроме 1С, а судя по опыту некоторые 1Сники и с иглишом не особо, т.к. вся инфа на нативном нашем языке.
Но нужно решить, на каком языке выводить предупреждения\ерроры конкретному потребителю (язык ОС?) т.к. делать всё на русском тоже не комильфо, 1С не спеша идет зарубеж и по идее могут появится зарубежные потребители.
Ну и переделать все подобные выводы с подключением словарей, а там.... хоть на традиционном китайском.

**Comment by EvilBeaver** [comment]
Словари избыточно... в 1С и в односкрипте двуязычный синтаксис. Можно писать ``Если``, можно писать ``If``. Думаю, достаточно двух языков. А как выбирать тот или иной - можно пообсуждать. Это не так важно. Русский по-умолчанию закроет потребности 99% пользователей, полагаю.

**Comment by fishca** [comment]
Одновременно выводить на нескольких языках не очень красиво. Надо сделать настройку на каком по умолчанию вывод должен идти. Либо в ключи запуска оскрипта добавить дополнительный ключ локализации.

**Comment by EvilBeaver** [comment]
Предлагаю параметр в oscript.cfg

**Comment by fishca** [comment]
Согласен

**Comment by kuntashov** [comment]
Правильнее по умолчанию язык брать из системных настроек локали ОС.
Переопределение в конфиге, конечно, нужно для нестандартных случаев.

**Comment by EvilBeaver** [comment]
Язык != Кодировка

**Comment by alexkmbk** [comment]
Мое мнение: по дефолту выводить сообщения в зависимости от языка операционной системы, если русский то на русском, если любой другой кроме русского - на английском. Плюс дать возможность задать язык где-нибудь в файле настроек.

Также предлагаю добавить в движок внутреннюю глобальную константу - SystemLanguage типа enum (доступную только разработчикам движка и компонент), с двумя возможными значениями: English и Russian. Это позволит разработчику программно определять то, на каком языке выводить сообщения, также можно будет дожать функцию NSTR которая в зависимости от значения SystemLanguage будет обрабатывать варианты текста для Ru и для En. Этой функцией смогут воспользоваться как разработчики самого движка, так и прикладные разработчики на языке 1С.

**Comment by alexkmbk** [comment]
Сформулирую постанову еще раз, более подробно:

1) в файле oscript.cfg добавляем свойство SystemLanguage  (по аналогии с параметром SystemLanguage из файла conf\conf.cfg). Свойство может принимать следующие значения: En и Ru.
После установки движка, по умолчанию, свойство в файле не будет задано, то есть будет закомментировано.

2) В движок добавляем новое перечисление LanguagesEnum типа enum. Оно будет состоять из двух значений: English и Russian. 

3) В глобальный контекст движка добавляем свойство SystemLanguage типа LanguagesEnum. оно будет доступно разработчикам компонент и разработчикам движка. Если в файле oscript.cfg  не задано свойство SystemLanguage, то значение будет определяться по значению System.Globalization.CultureInfo.CurrentCulture.EnglishName. Если установлен английский язык или любой другой кроме русского, то свойство SystemLanguage устанавливается в значение English иначе Russian.

4) Дорабатываем функцию Nstr чтобы она учитывала значение глобального свойства SystemLanguage.  То есть:

Если SystemLanguage==LanguagesEnum.English Тогда 
функция Nstr возвращает то значение, которое задано для En. При этом, если значение для En не указано, то возвращается значение, заданное для Ru, если и значение для Ru не указано, то выводится первое по порядку значение из доступных..

Если SystemLanguage==LanguagesEnum.Russian Тогда 
функция Nstr возвращает то значение, которое задано для Ru. При этом, если значение для Ru не указано, то возвращается значение, заданное для En, если и значение для En не указано, то выводится первое по порядку значение из доступных.

Функция Nstr  должна быть доступна в том числе и разработчикам компонент и движка.

5) Разработчики компонент и движка при выводе сообщений об ошибках должны будут пользоваться функцией Nstr, с обязательной установкой текста как для варианта сообщения на русском языке, так и на английском.

**Comment by alexkmbk** [comment]
Добавлю также что лично моих познаний не достаточно для реализации озвученной выше постановки. В частности не знаю как правильно добавить переменную SystemLanguage, так, чтобы она была доступна в модуле реализации функции Nstr.

**Comment by EvilBeaver** [comment]
Статический класс, например, для управления системным языком.

**Comment by alexkmbk** [comment]
@EvilBeaver Да, проблема тут только в разграничении прав доступа к изменению. По хорошему значение должен иметь возможность изменить только класс HostedScriptEngine, все остальные могут только читать. Через синглтон, можно такое поведение сделать. Добавить проверку, если не заполнено то можно изменить. Но будет выглядеть не очень красиво, то есть можно будет задать значение только один раз и не только из объекта HostedScriptEngine, а откуда угодно, то есть кто раньше это сделает тот и задаст значение, ну или вообще с разграничением не заморачиваться.

**Comment by EvilBeaver** [comment]
> ну или вообще с разграничением не заморачиваться

Я все чаще склоняюсь к такому паттерну :)

**Comment by alexkmbk** [comment]
> Я все чаще склоняюсь к такому паттерну :)

Да, может быть даже так лучше будет, получиться что внешние компоненты смогут менять язык и тем самым кастомизировать поведедение движка. Что тоже полезно в определенных случаях.

**Comment by alexkmbk** [comment]
> Предлагаю дополнить сообщение
> 
> > WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated, use 'GetEnvironmentVariable' from global context
> 
> руководством к действию на русском. Например,
> 
> > Используйте вместо СистемнаяИнформация.ПолучитьПеременнуюСреды( глобальный метод ПолучитьПеременнуюСреды(

@Stepa86 
https://github.com/EvilBeaver/OneScript/pull/852 - добавлен вывод сообщений на русском или на английском языках, в зависимости от языка ОС или значения параметра systemlanguage в файле oscript.cfg. Предлагаю этот issue закрыть.
