### ISSUE TITLE
Ключи -check -compile выдают ошибку: Object reference not set to an instance of an object}

### ISSUE THREAD

**Issue by best-tech** [EvilBeaver/OneScript#457]
{Модуль /usr/share/oscript/lib/logos/src/log-manager.os / Ошибка в строке: 65 / Внешнее исключение (System.NullReferenceException): Object reference not set to an instance of an object}
КаталогКонфига = СтартовыйСценарий().Каталог;

**Comment by best-tech** [comment]
1.0.16.41
1.0.17.78

**Comment by EvilBeaver** [comment]
Дайте пожалуйста полную строку запуска oscript с ключом -check на которой воспроизводится.

**Comment by best-tech** [comment]
/usr/bin/oscript -compile ./making.os
а так же 
/usr/bin/oscript-cgi ./making.os

**Comment by best-tech** [comment]
а вот запуск из режима cgi, видимо аналогичная проблема
ругается на обращение ВебЗапрос.GET;

`ScriptEngine.Machine.ExternalSystemException: {Модуль /var/www/html/cgi-bin/cgi.os / Ошибка в строке: 9 / Внешнее исключение (System.NullReferenceException): Object reference not set to an instance of an object} d = ВебЗапрос.GET; ---> System.NullReferenceException: Object reference not set to an instance of an object at oscript.Web.WebRequestContext.get_GET () <0x41241410 + 0x00012> in :0 at ScriptEngine.Machine.Contexts.PropertyTarget`1+<>c__DisplayClass21_0`1[TInstance,T].b__0 (TInstance inst) <0x412413a0 + 0x00030> in :0 at ScriptEngine.Machine.Contexts.AutoContext`1[TInstance].GetPropValue (Int32 propNum) <0x41241290 + 0x00098> in :0 at ScriptEngine.Machine.Variable+VariableReference.get_Value () <0x412408d0 + 0x00070> in :0 at ScriptEngine.Machine.Variable+VariableReference.GetRawValue () <0x412410f0 + 0x0000f> in :0 at ScriptEngine.Machine.MachineInstance.BreakVariableLink (IValue value) <0x41241070 + 0x00019> in :0 at ScriptEngine.Machine.MachineInstance.LoadLoc (Int32 arg) <0x41240fd0 + 0x00053> in :0 at ScriptEngine.Machine.MachineInstance.MainCommandLoop () <0x4123d210 + 0x00093> in :0 --- End of inner exception stack trace --- at ScriptEngine.Machine.MachineInstance.MainCommandLoop () <0x4123d210 + 0x00147> in :0 at ScriptEngine.Machine.MachineInstance.ExecuteCode () <0x4123ce80 + 0x0010b> in :0`

**Comment by best-tech** [comment]
теперь -make ((
1Script Execution Engine. Version 1.0.17.90

 Ссылка на объект не указывает на экземпляр объекта

Make started...

ScriptEngine.Machine.ExternalSystemException: {Модуль C:\Program Files (x86)\OneScript\lib\logos\src\log-manager.os / Ошибка в строке: 69 / Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}
