### ISSUE TITLE
По умолчанию ставить OneScript не в "Program Files", а в корень системного диска

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#466]
Чем мы хуже всяких Python, Go, Ruby и т.п., которые ставятся в корень диска С:\ ?

да и обновление легче будет, т.к. режим администратора не будет нужен - правда, это не всем удобно.

**Comment by dmpas** [comment]
гадить в корень - это плохо.

**Comment by EvilBeaver** [comment]
Будет нужен. Не нужен только если в appdata для конкретного пользователя

**Comment by dmpas** [comment]
Нужны будут админские права, но не режим администратора.

**Comment by artbear** [comment]
вот именно, что обычные права, а не супер-админские

**Comment by ret-Phoenix** [comment]
all users - appdata

**Comment by EvilBeaver** [comment]
Вообще что то в этом есть.

**Comment by fishca** [comment]
Лучше ставить в корень D:\, но никак не в корень системного диска. Хотя я может слишком старомоден.

**Comment by ret-Phoenix** [comment]
может быть только 1 диск, и думаю так у многих. Так что не вариант.
сделать выбор, как у других ПО
- программы
- апп дата пользователя
- апп дата всех пользователей (так кажется гугл хром ставится)

то как ставится Python, если честно раздражает.

**Comment by nixel2007** [comment]
Я против установки в корень C - это дико бесит и захламляет чистое и уютное местечко.
Аппдата - да, можно. Можно даже не в allUsers, а в текущего - тогда точно никаких прав не нужно.

**Comment by nixel2007** [comment]
а еще лучше - на выбор, как делают инстялляторы - для всех/для текущего пользователя

**Comment by artbear** [comment]
Да, выбор варианта (для всех/текущий) нужен и полезен.
Только куда ставить при выборе "для всех" ? 

нужно решить.

**Comment by dvakor** [comment]
Тоже не люблю, когда интерпретаторы ставятся в корень, потом заходишь в С, а там
Python27
Python34
Ruby22-x64
и тд.
А почему не дать свободу в выборе пути, а потом не прописать его в переменные окружения?

**Comment by EvilBeaver** [comment]
> А почему не дать свободу в выборе пути, а потом не прописать его в переменные окружения?

Свободу выбора не отменяет никто. Речь о правах на каталоги. Если ставить в Program Files, то потом, для работы с пакетным менеджером требуется либо консоль суперадмина, либо настройка себе самому прав. Т.е. issue предлагает решить именно эту проблему, а не каталог установки движка.

**Comment by EvilBeaver** [comment]
Кажется, потеряло актуальность, с появлением ovm
