### ISSUE TITLE
У элемента СовпадениеРегулярногоВыражения / RegExMatchx коллекции КоллекцияСовпаденийРегулярногоВыражения / RegExMatchCollection не хватает свойства Позиция

### ISSUE THREAD

**Issue by petypen** [EvilBeaver/OneScript#471]
Добрый день.
у элемента `СовпадениеРегулярногоВыражения` коллекции `КоллекцияСовпаденийРегулярногоВыражения`  есть свойство `Длина` но нет свойства `ПозицияПервогоСимвола`

Пример сценария использования:
автоматически обрабатывается текст модуля обработки и удаляются все комментарии.  При этом, описание процедур и функций хочу оставить. Мне необходимо получить диапазон позиций текста модуля между // Функция и Функция, который я и буду считать описанием.

**Comment by dvakor** [comment]
у СовпадениеРегулярногоВыражения есть свойство Индекс(Index) это разве не то, что вы хотите?)

**Comment by petypen** [comment]
@ArchLord42RU Дмитрий, вы абсолютно правы. Спасибо за помощь.

Провел эксперимент. Следующий скрипт:
``` bsl
Function main()
	Перем ТЕКСТ, РЕГВЫР;
	Перем коллекцияСовпадений, Совпадение;

	ТЕКСТ = "При этом, описание процедур и функций хочу оставить.
			| Мне необходимо получить диапазон позиций текста модуля между // Функция
			| и Функция, который я и буду считать описанием.";
	
	РЕГВЫР = "[Фф]унк[\wА-Яа-яЁё]+";

	Сообщить("Исходная строка:");
	Сообщить(ТЕКСТ);

	regExp = New RegEx(РЕГВЫР);
	коллекцияСовпадений = regExp.Matches(ТЕКСТ);
	Если коллекцияСовпадений.Количество()>0 Тогда
		Для каждого Совпадение Из коллекцияСовпадений Цикл
			Сообщить("-------------------------------------");
			Сообщить("Индекс - " + Строка(Совпадение.Индекс));
			Сообщить("Значение - " + Совпадение.Значение);
			Сообщить("Длина - " + Строка(Совпадение.Длина));
		КонецЦикла;
	КонецЕсли;

	Возврат Истина;
EndFunction

main();
```
В следующем тексте ищет совпадения слов, которые начинаются на "Функ"
_При этом, описание процедур и функций хочу оставить.
 Мне необходимо получить диапазон позиций текста модуля между // Функция
 и Функция, который я и буду считать описанием._

Вот что дает лог вывода:
Исходная строка:
При этом, описание процедур и функций хочу оставить.
 Мне необходимо получить диапазон позиций текста модуля между // Функция
 и Функция, который я и буду считать описанием.

Индекс - 30
Значение - функций
Длина - 7

Индекс - 118
Значение - Функция
Длина - 7

Индекс - 129
Значение - Функция
Длина - 7

А вот скриншот онлайн regex тестера https://yadi.sk/i/_Ji6Xxrc3KndCV 
Все отлично совпало. Еще раз спасибо.
Тикет можно закрывать.

**Comment by dvakor** [comment]
Тикет можно преобразовать в что-то типа "Дополнить синтаксис помощник на сайте", ибо там нет данного свойства в описании объекта.

**Comment by artbear** [comment]
Не соглашусь, в СП на сайте есть описание
![image](https://user-images.githubusercontent.com/2920817/27904372-2e56450a-6245-11e7-8618-682dcf55bacf.png)

**Comment by dvakor** [comment]
хм, видимо плохо смотрел :(

**Comment by petypen** [comment]
Закрываю, как решенный
