### ISSUE TITLE
Убрать зависимость от NewtonsoftJson из ядра движка

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#472]
Зависимость от библиотеки JSON в движке не нужна. Лучше оставить ее только в HostedScriptLibrary.dll

**Comment by dvakor** [comment]
Посмотрел, что зависимость находится только в классе CodeStatProccessor.
Как вариант можно убрать запись в файл из него (класса), а реализовать уже в HostedScriptLibrary.

**Comment by EvilBeaver** [comment]
Да, в самой машине можно выводить статистику в какой-то спец. класс. А потом в Library или вообще прямо в oscript.exe сериализовывать это в нужный формат.

**Comment by dmpas** [comment]
в данном случае json вообще можно руками писать. Хитростей там нет.
