### ISSUE TITLE
ЗаписатьСоответствиеПространстваИмен записывает префикс при объявлении префикса

### ISSUE THREAD

**Issue by alexey-marochkin** [EvilBeaver/OneScript#473]
ЗаписатьСоответствиеПространстваИмен("xmlns","http://v8.1c.ru/8.3/config/merge/settings");

Записывается следующее: xmlns:xmlns="http://v8.1c.ru/8.3/config/merge/settings"

Написал скрипт для преобразования патча GIT в mergesettigs для 1С и 1С такую конструкцию не проглатывает при загрузке настроек объединения. Выдает ошибку 
![redefinition_forbiden](https://user-images.githubusercontent.com/402495/27698449-331781c2-5d08-11e7-81a5-fe18d6be69b1.png)

Если поменять на xmlns="http://v8.1c.ru/8.3/config/merge/settings", то все ок.

**Comment by EvilBeaver** [comment]
А 1с как себя ведет при такой попытке записать соответствие?

**Comment by khorevaa** [comment]
@mrscylla еще бы скрипт в студию или на гитхаб  полезно будет

**Comment by alexey-marochkin** [comment]
Почитал про нэймспэйсы понял что не прав.
Нэймспэйс по умолчанию объявляется при записи начала элемента, а остальные при записи соответствия.

В итоге такой код работает

`Хмл.ЗаписатьНачалоЭлемента("Settings", "http://v8.1c.ru/8.3/config/merge/settings");
Хмл.ЗаписатьСоответствиеПространстваИмен("xs", "http://www.w3.org/2001/XMLSchema");
Хмл.ЗаписатьСоответствиеПространстваИмен("xsi", "http://www.w3.org/2001/XMLSchema-instance");`

**Comment by alexey-marochkin** [comment]
@Khorevaa [скрипт](https://github.com/mrscylla/DevOps/blob/master/%D0%A1%D0%B1%D0%BE%D1%80%D0%BA%D0%B0/make_merge_settings.os)

**Comment by EvilBeaver** [comment]
@mrscylla не прав, но не в порядке записи. Просто нельзя записать префикс xmlns в явном виде.     
Можно попробовать вариант:

    Хмл.ЗаписатьСоответствиеПространстваИмен("", "my-default-ns")

**Comment by EvilBeaver** [comment]
Ну или в наглую "ЗаписатьАтрибут("xmlns", "my-default-ns")
