### ISSUE TITLE
Свойство объекта не обнаружено (LF).

### ISSUE THREAD

**Issue by CT144** [EvilBeaver/OneScript#479]
Версия OneScript v.1.0.17.90.
Если написать `Символы.LF`, получаем ошибку: "Свойство объекта не обнаружено (LF)".
Использование английского "Tab", также вызывает ошибку.
В предыдущей версии, ошибки не возникало. 
Видимо, сочетание русскоязычного "Символы" и англоязычного свойства не работает.

**Comment by dvakor** [comment]
Подтверждаю, не пашет на данном релизе, в предыдущем все ок.

**Comment by EvilBeaver** [comment]
Спасибо!
