### ISSUE TITLE
Неверная диагностика места ошибки в "exe" модуле.

### ISSUE THREAD

**Issue by CT144** [EvilBeaver/OneScript#480]
OneScript v.1.0.17.90.
Скрипт "упакован" в EXE-модуль. Из основного скрипта из внешней библиотеки создается новый класс. При вызове в методе этого класса возникает ошибка. В сообщении об ошибке:
"Модуль Service1cDB.exe / Ошибка в строке: 372 /"
указывается модуль основного скрипта, а не того в котором возникла ошибка. Номер строки при этом верный и указывает на строку из внешней библиотеки.

**Comment by EvilBeaver** [comment]
Так и хочется сказать: "это фича"

Exe приложение все модули слепляет в одну кучу. Диагностика ошибок в нем не задумывалась. Пофиксить надо, наверное, но некритично

**Comment by EvilBeaver** [comment]
наверное можно привязать к #925
