### ISSUE TITLE
Страница "http://oscript.io/syntax/page/Операции с строками" не открывается 

### ISSUE THREAD

**Issue by vasvl123** [EvilBeaver/OneScript#481]

**Comment by dvakor** [comment]
По идее этот УРЛ и не должен работать)
Где вы нашли этот линк? УРЛ СП представленный на сайте ведет в http://oscript.io/syntax (без page) и работает он прекрасно

**Comment by vasvl123** [comment]
http://oscript.io/syntax/page/%d0%9e%d0%bf%d0%b5%d1%80%d0%b0%d1%86%d0%b8%d0%b8%20%d1%81%20%d1%81%d1%82%d1%80%d0%be%d0%ba%d0%b0%d0%bc%d0%b8

**Comment by vasvl123** [comment]
http://oscript.io/syntax/page/%D0%9E%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8%20%D1%81%D0%BE%20%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B0%D0%BC%D0%B8 а вот так работает, нужно исправить на "Операции со строками"

**Comment by EvilBeaver** [comment]
Исправлено
