### ISSUE TITLE
 Ключ -make выдают ошибку:  (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}

### ISSUE THREAD

**Issue by best-tech** [EvilBeaver/OneScript#486]
1Script Execution Engine. Version 1.0.17.90

Make started...
ScriptEngine.Machine.ExternalSystemException: {Модуль C:\Program Files (x86)\OneScript\lib\logos\src\log-manager.os / Ошибка в строке: 69 / Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}

[#457](https://github.com/EvilBeaver/OneScript/issues/457)

**Comment by EvilBeaver** [comment]
Уточню: это происходит, если в скрипте, который упаковываем, косвенно есть обращения к СтартовыйСценарий() в теле модуля. При инициализации объекта СтартовыйСценарий нулевой, похоже. В данном примере - это внутри logos обращение к СтартовыйСценарий().Каталог
