### ISSUE TITLE
Выполнение файла скрипта в другом скрипте

### ISSUE THREAD

**Issue by Denotop** [EvilBeaver/OneScript#488]
Мне кажется не хватает процедуры которая бы подключала текст модуля к текущему скрипту.
Не ввиде класса или модуля, а в контексте текущего модуля.
Например:
в файле test1.os
Функция МояФункция() Экспорт
	Сообщить("Работает");
КонецФункции

в файле test2.os
#Использовать "test1.os"
МояФункция();

так test2.os работать не будет, но хотелось чтобы функция МояФункция() была доступна.

**Comment by dvakor** [comment]
Просто интересно, а зачем? Кто вам мешает все в одном файле реализовать?
Если у вас много кода в рамках одного скрипта, то тут априори надо делить на модули\классы, вы же не пишете конфигурацию, запихивая весь код в один общий модуль \ несколько глобальных модулей, это полный бред.

**Comment by Denotop** [comment]
Если onescript позиционирует себя как скриптовый язык то эта функция должна быть, как например в php функция include,require. 
Нужно это для двух вещей:
1) Разделение бизнес логики по файлам, а не писать все в одном файле
2) Организации наследования методов и свойств, в текущей модели я не вижу как организовать наследования

**Comment by dmpas** [comment]
> Разделение бизнес логики по файлам, а не писать все в одном файле

Для этого есть библиотеки. Делаются они лишь капельку сложнее, чем "test1.os".

> Организации наследования методов и свойств, в текущей модели я не вижу как организовать наследования

тут у нас идеологический пробел. Не все считают, что это нужно.

**Comment by EvilBeaver** [comment]
А Андрей Ош уже запилил наследование и полиморфизм :trollface:
