### ISSUE TITLE
Создание фоновой задачи или асинхронное выполнение функции

### ISSUE THREAD

**Issue by Denotop** [EvilBeaver/OneScript#489]
Не хватает фоновых задач.
Конечно можно несколько раз вызвать через командную строку, но в нее не очень удобно передавать параметры.

**Comment by artbear** [comment]
Все решается через объекты/классы/библиотеки.

посмотри примеры реализаций в репо библиотек из https://github.com/oscript-library

**Comment by EvilBeaver** [comment]
А зачем фоновые? Что хотите ими сделать?

**Comment by Denotop** [comment]
ну например запрос на TCPСервер обрабатывать в фоновом задании

**Comment by EvilBeaver** [comment]
@Denotop а в основном потоке при этом что делать?

**Comment by Denotop** [comment]
это на усмотрения программиста, можно ожидать результат выполнения фонового задания
можно завершить выполнения скрипта, не дожидаясь выполнения фонового задания

**Comment by EvilBeaver** [comment]
Я и спрашивал: "Что конкретно надо сделать с помощью фоновых"? Если результат ожидать, то зачем тогда фоновое? А если скрипт завершать, то кто будет довыполнять фоновое?

**Comment by nixel2007** [comment]
> Если результат ожидать, то зачем тогда фоновое?

Параллельная обработка?

**Comment by EvilBeaver** [comment]
Ну вот сделает Никита лямбды, их можно будет использовать в качестве THREADFUNC

**Comment by nixel2007** [comment]
Не совсем уловил связи. Ты хочешь сказать, что передача аргументов в лямбда-функцию технически похожа на передачу аргументов в новый поток? Лямбды же живут в потоке родителя, общая память, область видимости (ну, почти)

**Comment by EvilBeaver** [comment]
/all ну таки и что с этой задачей? @Denotop можешь набросать короткий пример кода реальной задачи, как будто фоновые существуют?

**Comment by k4rimov** [comment]
Фоновые нужны, точнее потоки.
Например создать массив Потоков загрузки по http. Реальный пример - на входе есть список ссылок на mp3 файлы (неважно откуда они прилетели). Закидываем их в массив.
Создаем потоковую функцию - суть которой скачать данные по ссылке (подается на вход функции).

Здесь главный поток - создает и подготавливает данные (список ссылок), создает 3-5 потоков в цикле. И раздает на эти потоки ссылки и запускает очередную сессию потоковой функции на выполнение.
Главный поток обрабатывает результаты потоковых функций, следит за прогрессом, рестартует потоковую функцию заново если где-то сбой/таймаут и т.п.

Итого: скачивать в один поток много быстрее чем в однопоточном режиме. То же относиться и к остальным областям: копирование файлов, обработка каталогов, поиск файлов, решение кроссворда..
Код движка, конечно же, должен обеспечивать такой функционал. Заранее нужно думать о синхронизации потоков, приостановки и возобновлении.

**Comment by khorevaa** [comment]
Мне тоже потоки нужны, для организации обновлений ИБ  в несколько потоков вместо  нескольких копий скрипта

**Comment by artbear** [comment]
Взаимодействие разных скриптов можно и без движка сделать, через библиотеки.
Все средства есть.

**Comment by artbear** [comment]
Дубль задачи https://github.com/EvilBeaver/OneScript/issues/764
правда, та позже появилась )
