### ISSUE TITLE
Собрать релиз OneScript, в котором в библиотеках нет использования устаревшей функции

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#490]
Нужно исключить сильно отвлекающее сообщение о deprecated методе.

я выпустил релизы opm, logos, v8runner для поддержки 17 движка и исключения этого предупреждения.

@EvilBeaver сможешь собрать и выложить на сайт версию с "правильными" библиотеками?

**Comment by EvilBeaver** [comment]
opm update --all?
