### ISSUE TITLE
Упросить получение версии ОС

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#491]
Убрав переменные среды, СистемнаяИнформация теперь используется только для одного:
```
ЭтоWindows = Найти(ВРег(СистемнаяИнформация.ВерсияОС), "WINDOWS") > 0;
```

**Comment by EvilBeaver** [comment]
Я подумываю о препроцессоре для этих целей. Или лишнее?

**Comment by dmpas** [comment]
У меня по поводу препроцессора смешанные чувства.
С одной стороны - это полезно и "для совместимости" всё равно придётся делать.
С другой стороны - делать его долго (полпарсера перелопатить); и опыт Си/Си++ показывает, что препроцессор всем подряд в руки давать не стоит.

**Comment by EvilBeaver** [comment]
Он есть уже в 2.0. Поскольку она чет не едет, думаю удачные куски оттуда перетаскивать сюда

**Comment by EvilBeaver** [comment]
А так да, чувства аналогичные у меня

**Comment by ret-Phoenix** [comment]
Я тоже против препроцессоров.

**Comment by EvilBeaver** [comment]
@ret-Phoenix, аргументация?

**Comment by ret-Phoenix** [comment]
Усложнение кода, уменьшение прозрачности.

**Comment by dmpas** [comment]
Может сделать глобальную переменную `СистемнаяИнформация` ?? всё равно от экземпляра к экземпляру данные не меняются...

**Comment by EvilBeaver** [comment]
Оно украдено с 1с жеж

**Comment by dmpas** [comment]
@EvilBeaver да ладно?! :trollface: 

в любом случае это не повод не делать его удобнее, сохраняя при этом совместимость.

**Comment by EvilBeaver** [comment]
Я и не спорю. Глобально удобно. Но может это пакет sys с модулем, а не правка движка?

**Comment by dmpas** [comment]
убираем `Новый СистемнаяИнформация`, добавляем `#Использовать sys` ? сомнительный выигрышь.

**Comment by nixel2007** [comment]
@dmpas использовать sys - один раз, а новый системная информация - каждый, если оно не глобальное (Перем и прочее)

**Comment by dmpas** [comment]
@nixel2007 ты данные об ОС скорее всего один раз за скрипт и получаешь.

**Comment by EvilBeaver** [comment]
Реализован препроцессор в дополнение к СисИнфо
