### ISSUE TITLE
Проброс произвольных .NET API с помощью ManagedCom

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#492]
Текущая реализация COMОбъекта в целом, может быть применена и к произвольным .NET классам.

Нужно провести натурный эксперимент и попытаться использовать .NET классы через прослойку COMОбъекта.

Проблемы вылезут с дженериками и, возможно, перечислениями. В остальном, должно быть совместимо.

**Comment by dmpas** [comment]
пока я экспериментирую, предлагаю обсудить синтаксис.
```bsl
МояПеременная = Новый System.Net.TcpListener(1234);

МояПеременная = Новый("System.Net.TcpListener", 1234);

МояПеременная = Новый NetОбъект("System.Net.TcpListener", 1234);

```

**Comment by artbear** [comment]
Вроде бы 1-й вариант не валиден с точки зрения синтаксиса

```bsl
МояПеременная = Новый System.Net.TcpListener(1234);
```
2-й и 3-й вполне себе валидны
```bsl
МояПеременная = Новый("System.Net.TcpListener", 1234);

МояПеременная = Новый NetОбъект("System.Net.TcpListener", 1234);
```

Мне больше нравится 3й вариант - четко обозначаем класс и назначение

**Comment by dmpas** [comment]
а как же мечта о пространствах имён? почему-бы не воплотить её "заодно" :)

**Comment by EvilBeaver** [comment]
Уже сейчас она может работать через Новый COMОбъект

7 Авг 2017 г. 15:11 пользователь "Sergey Batanov" <notifications@github.com>
написал:

**Comment by dmpas** [comment]
@EvilBeaver и правда, работает.
Понеслась развлекуха!
```
{Модуль <string> / Ошибка в строке: 2 / Внешнее исключение (System.Reflection.AmbiguousMatchException): Обнаружено неоднозначное соответствие.}    

```

**Comment by dmpas** [comment]
да, с амбигусом будут большие запары. Тут придётся выдумывать какую-нибудь хитрую эвристику, чтобы выбор метода был очевиден для разработчика.

**Comment by EvilBeaver** [comment]
Речь о перегрузках методов? Рефлекшен вроде бы умно умеет его разруливать по переданным параметрам

**Comment by dmpas** [comment]
вот пробую. там же разные приведения типов, параметры по-умолчанию и прочая-прочая.

**Comment by nixel2007** [comment]
> Рефлекшен вроде бы умно умеет его разруливать по переданным параметрам

Вроде бы за это отвечает интерпретатор/компилятор используемого языка. Разве нельзя "просто" выполнить метод класса, прокинув ему все параметры, переданные из оскрипта?

**Comment by dmpas** [comment]
> Разве нельзя "просто" выполнить метод класса

а который??? у тебя десяток с одинаковым именем, но разными параметрами. Притом, что `int A(int x)` и `double A(double x)` могут делать совершенно разные вещи, но в Односкрипте и то, и то - Число

**Comment by nixel2007** [comment]
@dmpas в смысле "который"? Мы же не выбираем сигнатуру явно, мы пробрасываем параметры, а нужную сигнатуру выбирают за нас. 

Из проблемных преобразований на вскидку приходят только числа, да. Что-то ещё есть? Остальные примитивные типы вроде бы не имеют таких градаций - строка она и в Африке строка. 

Движок оскрипта сам выбирает, во что скастить Число из 1с-кода? Или там обертка-тип поверх? 

Хотя один фиг получается, что надо пытаться угадать/определить доступную сигнатуру, если среди параметров есть число...

**Comment by dmpas** [comment]
> если среди параметров есть число...

а ещё есть объекты, массивы.

**Comment by Faithfinder** [comment]
Есть мнение, что перегрузы без строгого типирования не вариант.

**Comment by dmpas** [comment]
> Есть мнение, что перегрузы без строгого типирования не вариант.

если перегруз по количеству параметров - то очень вариант.
в перегрузе по типам главное в нашем случае сделать выбор метода прозрачным и документировать.

**Comment by dmpas** [comment]
По количеству параметров получилось. Такой код отрабатывает:
```bsl
R = New ComObject("System.Random");
Message(R.Next(10, 20));
Message(R.Next(20));
Message(R.Next());
Message(R.NextDouble());

```

**Comment by dmpas** [comment]
Теперь следующий вопрос на обсуждение: что должна возвращать функция `ТипЗнч()` ? Сейчас это `COMОбъект`.

**Comment by dmpas** [comment]
А ведь работает же
```bsl
L = New ComObject("System.Collections.ArrayList");
L.Add(1);
L.Add("string");
For Each m In L Do
	Message(m);
EndDo;
```

**Comment by dvakor** [comment]
> Теперь следующий вопрос на обсуждение: что должна возвращать функция ТипЗнч() ? Сейчас это 

> COMОбъект.

Намекаешь на получение .Net типа?
Его же можно уже сейчас через GetType получить спокойно.

**Comment by artbear** [comment]
>Теперь следующий вопрос на обсуждение: что должна возвращать функция ТипЗнч() ? Сейчас это COMОбъект

да, хотелось бы получить Net-тип

**Comment by EvilBeaver** [comment]
ненене. Концептуально это чужеродный объект. Как в 1С COMОбъект для всего чем не управляет платформа. Я бы оставил так же. Т.е. не стал бы декларировать гладкий проброс типов дотнет в односкрипт "как родных". Все-таки чужие.

**Comment by dmpas** [comment]
@artbear @EvilBeaver итого, как с типами будем договариваться? я промеж вас потерялся: с одной стороны я согласен, что если у нас не OneScript.Net, то .NET-типы нам чужие; с другой стороны - всё же клёво и удобно работать с ними как с родными.

**Comment by EvilBeaver** [comment]
Я за чужие. Непрозрачно для ТипЗнч, аки сделано для COM. Аргумент: полноценно родными все равно не станут, ибо дженерики, строготипизированные перегрузы не дадут им стать истинно родными. Неизбежно будет костылестроение, лучше его избежать совсем. Черный ящик и все тут. Как в COM.

**Comment by artbear** [comment]
@dmpas @EvilBeaver Мы уже обсуждали, начиная с https://github.com/EvilBeaver/OneScript/issues/492#issuecomment-320645541
возможность использования NetObject

Может быть, так и сделать?
+ Спец.объект NetObject вместо ComObject
+ ТипЗнч возвращает подробный тип `NetОбъект.System.Net.TcpListener`

Непрозрачность уж больна неудобна, валидность объекта сложно проверить, тот ли объект получен из net-методов, все время какие-то костыли приходилось писать в 1С :(

**Comment by EvilBeaver** [comment]
Пример приведи, когда тебе позарез нужен был тип у КомОбъекта?
Ящетаю, что это вообще не надо. Плюс, у любого .NET объекта есть GetType() раз на то пошло.

**Comment by artbear** [comment]
Точный пример не приведу, за давностью лет.
Насколько помню, было сложно/неудобно, когда метод какой-нибудь коллекции КомОбъекта возвращал значение, также КомОбъект.

Что за GetType() ? в реалиях наших скриптов как это будет/должно работать?
приведи пример, плиз.

**Comment by dmpas** [comment]
@artbear как-то так:
```bsl
Если Нечто.GetType().FullName = "System.Collections.List" Тогда
// ...
КонецЕсли;
```

**Comment by artbear** [comment]
Уже лучше.
Вопросы:
+ ТипЗнч(Нечто) будет возвращать ComObject, верно ?
+ как узнать, что это самое Нечто поддерживает GetType() ?
  + или любой ComObject() поддерживает GetType(), хотя я что-то такого не помню
  + чтобы не воротить код проверки типа внутри блока попытки-исключения :)

**Comment by dmpas** [comment]
Надо попробовать натравить на него рефлектор. Вдруг поможет.

**Comment by EvilBeaver** [comment]
Для односкрипта что ком-объект, что .net объект - одно и то же
Достается системным рефлектором все. Даже на уровне движка нам проблематично будет отделить КОМ от НЕТ. И предлагаю этого вобще не делать. По крайней мере до появления внятных кейсов, поясняющих, что это необходимо.

**Comment by artbear** [comment]
@dmpas Проверишь свою реализацию рефлектором?
Возможно ли так проверить наличие метода GetType у этого метода ?

**Comment by EvilBeaver** [comment]
@artbear объясни, зачем это Сергею делать? Чтобы что?

**Comment by artbear** [comment]
Если рефлектор сможет сказать по наличию метода GetType, тогда у меня нет возражений по использованию НетОбъектов как КомОбъектов

**Comment by artbear** [comment]
Чтобы был нормальный метод получения инфы о типе Нет-объекта

**Comment by EvilBeaver** [comment]
это не ответ. Зачем он нужен? Для ком - его нет.

**Comment by artbear** [comment]
Как мне внутри своего скрипта/метода/библиотеки узнать, какой именно НетОбъект мне передали?
например, в зависимости от типа объекта у меня должна быть разные вариант обработки?

**Comment by artbear** [comment]
Для Ком нету типов, потому что 1С молодцы.
Для Ком вообще можно получить инфу о типе, если у Ком-объекта есть его поддержка.

**Comment by EvilBeaver** [comment]
> Для Ком вообще можно получить инфу о типе, если у Ком-объекта есть его поддержка.

Средствами 1С или вообще?

**Comment by artbear** [comment]
Не в 1С, конечно. 
1С молодцы - они этого не сделали, насколько я знаю.

**Comment by dmpas** [comment]
ну короче! я тогда запиливаю CLR-объекты, как COM-объекты - чтобы неотличимы были. а то что-то затянулося...

**Comment by artbear** [comment]
ты запиливай, я после получения сборки в девелопе посмотрю работу с типами.

**Comment by EvilBeaver** [comment]
@dmpas закрываем же?

**Comment by dmpas** [comment]
да, давай закроем.

**Comment by artbear** [comment]
В ночнике уже есть, верно?

**Comment by dmpas** [comment]
@artbear да.
