### ISSUE TITLE
не понимает ValueIsFilled

### ISSUE THREAD

**Issue by vasvl123** [EvilBeaver/OneScript#496]

**Comment by dmpas** [comment]
https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs#L414

У нас `IsValueFilled`, надо поправить.

**Comment by EvilBeaver** [comment]
Ошибочно закрыл текстом коммита

**Comment by EvilBeaver** [comment]
Я недопонял, мы это починили или нет?

**Comment by dmpas** [comment]
нет, не починили. Остановились на том, что надо депрекейтед алиас вводить.
