### ISSUE TITLE
"И", "ИЛИ", "НЕ" как свойство структуры 

### ISSUE THREAD

**Issue by vasvl123** [EvilBeaver/OneScript#498]
стр = Новый Структура;
	стр.Вставить("И", "And");
	Сообщить(стр.И);

{Модуль C:\os\srv\3.os / Ошибка в строке: 3 / Ожидается идентификатор}

**Comment by EvilBeaver** [comment]
В 1С такое работает разве?

**Comment by dmpas** [comment]
Ага.

**Comment by EvilBeaver** [comment]
У меня какое-то дежавю, что это уже фиксилось

**Comment by EvilBeaver** [comment]
@dmpas нет под рукой 1С. А как там насчет Если, Цикл и прочего?
