### ISSUE TITLE
Нестабильный тест http

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#500]
Сторонний ресурс httpbin.org время от времени трещит от перегрузок и выдаёт ошибки 400, 500, 408 и им подобные. Вследствие чего вся сборка помечается нестабильной.

Нужно уменьшить зависимость от проблем стороннего ресурса:
 1. отключить тест http
 2. или отрабатывать в тестах отдельные коды ошибок

**Comment by artbear** [comment]
предлагаю отключить так, что тесты все-таки были, но отмечались пропущенными.

например, убрать Экспорт у реализаций методов-тестов или тупо закомментить все, оставив только ПолучитьСписокТестов

возможно, в будущем что-то другое придумаем

**Comment by dmpas** [comment]
@artbear есть возможность тест запустить всё же, но пометить его пропущенным, если он провалился?

**Comment by artbear** [comment]
@dmpas нет, в старой версии testrunner.os, который находится в исходниках движка, нет такой возможности

для исправления нужно встраиваться вот сюда https://github.com/EvilBeaver/OneScript/blob/develop/tests/testrunner.os#L608
и анализировать исключение.

в версиии 1testrunner (для скриптов) это исправлено. можно оттуда взять

**Comment by EvilBeaver** [comment]
@artbear несколько туманное объяснение, накидай на пальцах, пожалуйста. Или пулреквестом

**Comment by artbear** [comment]
Пока нет времени на PR :(

**Comment by EvilBeaver** [comment]
@artbear тогда словами поясни
