### ISSUE TITLE
ПолучитьВремяСоздания зависит от файловой системы

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#503]
Не все файловые системы поддерживают получение времени создания файлов (xfs, ext3), потому проверяющий тест должен быть исключён, т.к. он будет нестабилен.

**Comment by artbear** [comment]
Для винды предлагаю тест оставить
для Линукса решайте сами - новые возможности СистемнойИнформации от @ret-Phoenix не помогут в определении типа файловой системы?

**Comment by dmpas** [comment]
вопрос файловой системы не есть вопрос операционной системы. У тебя и под виндой может на чём попало тестовая система крутиться, и в линухе под ntfs.

**Comment by artbear** [comment]
Много ты видел систем на винде, где `на чем попало крутится` ? :(

**Comment by dmpas** [comment]
да примерно ни одной. :trollface:

**Comment by Faithfinder** [comment]
Для линуксоидных файловых систем насколько я понял, покурив вопрос, по запросу времени создания будет возвращаться время изменения. Правда, вести список ФС в тесте было бы как-то неправильно.

Самый простой способ решить вопрос - написать вместо "ПроверитьМеньше" -
 "ПроверитьМеньшеИлиРавно". Тест получится не самый точный, но вроде как будет работать стабильно.

**Comment by EvilBeaver** [comment]
У нас и сейчас в половине тестов "Если Линукс Тогда НахерТест()"

Так что не смертельно, если и здесь будет так же. И потом, кто тут махровый ретроград и юзает ext3?

**Comment by dmpas** [comment]
@EvilBeaver в докере разве не xfs??

**Comment by nixel2007** [comment]
В докер сейчас вроде Overlay 2. Или это про что-то другое?

**Comment by dmpas** [comment]
В "Debian Stretch" - overlay2, в остальных - aufs по-умолчанию

**Comment by EvilBeaver** [comment]
Ну а собственно, какой путь решения в данной issue предлагается?

**Comment by dmpas** [comment]
@EvilBeaver сделаем проверку на ОС.
