### ISSUE TITLE
Обеспечить несколько термов для методов и свойств

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#505]
1С время от времени переименовывает методы. Особенно английские. При этом она оставляет как старый так и новый вариант. У нас так сделать нельзя (вернее, сложно). Надо бы лать возможность легко и прозрачно задавать термы методов в нескольких вариантах. С deprecated-ами и т.п.

См. #496

**Comment by dmpas** [comment]
> При этом она оставляет как старый так и новый вариант.

`IsValueFilled` же не работает

**Comment by EvilBeaver** [comment]
@dmpas это не про данный конкретный случай. Вообще, 1С в справке к новой версии часто пишет, что заменили тот или иной английский терм, но оставили старый для совместимости.

**Comment by dmpas** [comment]
Что-нибудь в этом роде:
```c#
[ContextMethod("Метод", "Method")]
[DeprecatedAlias("Mehtod")]
[DeprecatedAlias("OldMethod")]
[DeprecatedAlias("БылоРанее")]
void Method()
{
...
}
```

**Comment by EvilBeaver** [comment]
Я думал чуть иначе:

```c#
[ContextMethod("МетодРусский", "МетодАнглийский")]
[ContextMethod("МетодСтарый", deprecated: true)]
```

И все алиасы, которые добавлялись как deprecated автоматом ругаются (или вообще не ругаются)
