### ISSUE TITLE
Реализовать КодировкаТекста в виде класса

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#510]
Можно сделать, чтобы ТипЗнч(КодировкаТекста.UTF8) был равен Тип("КодировкаТекста")

В качестве значения - обернуть системный тип Encoding и получить из коробки методы GetBytesCount и подобные.

```bsl
Байты = КодировкаТекста.UTF8.ПолучитьБайты("Превед Медвед!");
Размер = КодировкаТекста.UTF8.ПолучитьКоличествоБайт("Свободу Анжеле Дэвис!");
```

**Comment by dmpas** [comment]
В духе платформы должно быть нечто вроде:
```bsl
Функция ОпределитьКоличествоБайтВСтроке(Знач Строка, Знач КодировкаТекста = КодировкаТекста.UTF8)
```

**Comment by tsukanov-as** [comment]
Кстати, а в платформе строки в памяти не в UTF-8?
Если так, то хватило бы СтрРазмер() или типа того.
А вообще было бы круто получать из строки байтовый массив только для чтения. Тут и копирование не нужно, и по байтам гулять можно (строки ведь неизменяемые) В 1С есть бинарные буферы, но они вроде как копируют тоже (хотя надо бы проверить)

**Comment by dmpas** [comment]
> Кстати, а в платформе строки в памяти не в UTF-8

в UTF-16, насколько я знаю.

**Comment by tsukanov-as** [comment]
> в UTF-16, насколько я знаю.

Меня смущает то, что я для хэширования передаю строку как есть [тыц](https://github.com/Lead-Bullets/Radar/blob/master/src/CommonModules/Git_ServerCall/Ext/Module.bsl#L26). Неужели оно конверит в UTF-8 при этом O_o

**Comment by dmpas** [comment]
Синтаксис:

Добавить(<Текст>) 
Параметры:

<Текст> (обязательный)

Тип: Строка. 
Добавляемые текстовые данные (в UTF8 кодировке).

**Comment by dmpas** [comment]
конвертит, значит.

**Comment by tsukanov-as** [comment]
Странно. Почему тогда они именно в UTF-8 конвертят? И выбора кодировки нет.
Я думал что это именно чтобы не конвертить.

**Comment by dmpas** [comment]
видимо, потому что считать хэш от UTF-16 нафиг никому никогда не нужно. Для экзотик есть двоичные данные.

**Comment by tsukanov-as** [comment]
Возможно, да

**Comment by EvilBeaver** [comment]
Внутри CLR все строки в UTF-16, а тип Char равен 2 байтам

**Comment by nixel2007** [comment]
@dmpas 

> В духе платформы должно быть нечто вроде:

1с не позволяет использовать непримитивные типы в качестве значений по умолчанию

**Comment by dmpas** [comment]
Да я знаю. Там будет `Неопределено`, а в коде оно будет переопределяться. Я упростил.

**Comment by EvilBeaver** [comment]
@dmpas я не понял, что именно ты хотел сказать в камменте про "В духе платформы"?

Это "за" предложение, "против" или что?

**Comment by dmpas** [comment]
это ни "за", ни "против". это просто размышления на тему "если бы это было сделано в 1С".
```bsl
Р = СтрРазмерВБайтах("123", КодировкаТекста.UTF8);
```

Сама по себе затея мне нравится, особенно, если продолжить её на другие примитивные типы:
```bsl
"Строка".Длина(), ТекущаяДата().НачалоДня(), ...
```

**Comment by EvilBeaver** [comment]
@dmpas теперь ясно. Это был 1С-стайл. Ты прав, скорее всего так бы и было. Но он мне претит чота.

**Comment by EvilBeaver** [comment]
С появлением двоичных данных в платформе и 1скрипте задача теряет актуальность
