### ISSUE TITLE
НайтиФайлы() неверно возвращает объект Файл

### ISSUE THREAD

**Issue by pumbaEO** [EvilBeaver/OneScript#511]
linux - fedora 26, oscript - 1.0.17.95
При указании во второй части поиска пути с подкаталогами, возвращает не нулевой массив с файлами, но элементы массива указывают на несуществующий путь, точнее отрезается часть пути во втором параметре. 
Пример кода, создаю временный каталог, создаю подкаталоги и записываю пустой файл, потом делаю поиск относительно временной папки и получаю не пустой массив,т.е. файл находит, но когда обращаюсь к элементам и получаю полное имя, указывает путь неправильный. 
```
ИмяВременногоКаталог = ПолучитьИмяВременногоФайла();
СоздатьКаталог(ИмяВременногоКаталог);
КаталогПроверки = ОбъединитьПути(ИмяВременногоКаталог, "test/test");
СоздатьКаталог(КаталогПроверки);

ЗаписьТекста = Новый ЗаписьТекста;
ЗаписьТекста.Открыть(ОбъединитьПути(КаталогПроверки, "test.txt"));
ЗаписьТекста.ЗаписатьСтроку("");
ЗаписьТекста.Закрыть();

МассивФайлов = НайтиФайлы(ИмяВременногоКаталог, "./test/test/test.txt");
Сообщить(МассивФайлов.Количество());
Для каждого Элемент из МассивФайлов Цикл 
	Сообщить(Элемент.ПолноеИмя);
	Сообщить("Должно быть:"+Новый Файл(ОбъединитьПути(КаталогПроверки, "test.txt")).ПолноеИмя);
КонецЦикла;
```
Вывводит 
```
1
/tmp/46lytwad.4nf/test.txt
Должно быть:/tmp/46lytwad.4nf/test/test/test.txt
```

**Comment by artbear** [comment]
Проверил твой код в винде.

В винде поведение правильное.

**Comment by EvilBeaver** [comment]
@dmpas у меня нет отладочной среды под линукс. Сможешь взять?

**Comment by dmpas** [comment]
Да, беру.

**Comment by dmpas** [comment]
@pumbaEO 
у меня не воспроизводится на девелопе.
```
1
Получено   : /tmp/xlcpxvbc.cg5/test/test/test.txt
Должно быть: /tmp/xlcpxvbc.cg5/test/test/test.txt
``
```
$ mono --version
Mono JIT compiler version 5.2.0.215 (tarball Mon Aug 14 15:46:23 UTC 2017)
...
```

**Comment by pumbaEO** [comment]
Да, на 5 все работает:
```
docker run -it -v ${PWD}:/tmp mono:5 mono /tmp/bin/oscript.exe /tmp/del.os
1
/tmp/qktl26w9.xst/test/test/test.txt
Должно быть:/tmp/qktl26w9.xst/test/test/test.txt
```
а на 4 нет
```
docker run -it -v ${PWD}:/tmp mono:4 mono /tmp/bin/oscript.exe /tmp/del.os
1
/tmp/19r6plig.uky/test.txt
Должно быть:/tmp/19r6plig.uky/test/test/test.txt
```

**Comment by EvilBeaver** [comment]
Закрываем?

**Comment by artbear** [comment]
@pumbaEO Женя, тогда и этот коммит https://github.com/artbear/1bdd/commit/658f20e091b059210bc58e204a4b413ba07ce7d7
откатывает, раз здесь ничего не изменили?
верно?

**Comment by pumbaEO** [comment]
нет, т.к. в centos и fedora еще 4.8 версия. Сейчас работа НайтиФайлы - это особенность на 4.8. Но тот коммит позволяет ее обойти и еще годик до следующего релиза пользоваться тестовым фреймворком.

**Comment by artbear** [comment]
как-то не очень логично.
а если еще где-то подобное поведение упадет, опять будем менять скрипты что-ли?
это костыльное решение.

**Comment by pumbaEO** [comment]
Костыльно - согласен, пока это работает. Если дальше будет вылазить, тогда согласен - рекомендация обновить моно, но такое только в 1bdd вылезло. Можно задачку сделать, с датой через год, еще раз взглянуть свежим взглядом.
