### ISSUE TITLE
Добавить расшифровку неверного пути или имени файла в тексте исключения ОбъединитьПути

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#523]
Сейчас получаем сообщение, из которого совершенно непонятно, в чем проблема.
```
Внешнее исключение (System.ArgumentException): Путь содержит недопустимые знаки.}
НовыеПараметры = ОбъединитьПути(ТекущийКаталогПроекта, ИмяФайла);
```
Также ИМХО возможная проблема наблюдается у класса `Файл`

А было бы удобно получить нормальную расшифровку неверного пути или имени файла в тексте исключения `ОбъединитьПути`/`Файл` для быстрейшего понимания проблемы.

**Comment by nixel2007** [comment]
По-млему ошибка вполне очевидна - строка содержит недопустимые для пути символы. Куда уж еще понятнее?

**Comment by artbear** [comment]
Никита, а какие именно символы? в каком из параметров?
проблема возникает не так уж и редко :(

**Comment by nixel2007** [comment]
А проблема не в параметрах ОбъединитьПути, проблема в результате работы функции. На каждой фс список запрещённых символов свой. Емнип платформа кидает не шибко более понятное исключение, так как оно идёт из низкоуровнего вызова работы с фс. Что и в односкрипте происходит собственно

**Comment by EvilBeaver** [comment]
Шедеврально в этом плане поступает и сама OS в винде и линуксе. Любимое же всеми сообщение

    Не удается найти указанный файл

Какой файл, чего? Однако, все живы

**Comment by artbear** [comment]
И что?
Будем ориентироваться на плохие результаты?
ах, все так делают, давайте и мы также чтоли?
меня как пользователя такая аргументация не устраивает.

**Comment by artbear** [comment]
Меня устроит простая расшифровка 2х переданных параметров - для ОбъединитьПути, и одного для Файл.
Не нужно искать, какие именно символы невалидны, если это сложно.

**Comment by artbear** [comment]
А ошибка "Не удается найти указанный файл" многим проблем добавила.
бывает совсем не просто понять, какого же именно файла не хватает :(
бывало, и файл-моном приходилось смотреть.

**Comment by dmpas** [comment]
https://msdn.microsoft.com/ru-ru/library/system.io.path.getinvalidpathchars(v=vs.110).aspx

в `Path.Combine()` тупо идёт проверка на `GetInvalidPathChars()` без участия файловой системы. Соответственно, можно либо пробросить эту функцию в односкрипт, либо на основании неё сообщать, какой же символ не понравился.

**Comment by EvilBeaver** [comment]
с 2017 года не определено желаемое поведение. wontfix за невостребованностью.
