### ISSUE TITLE
Авто-апдейтер

### ISSUE THREAD

**Issue by Faithfinder** [EvilBeaver/OneScript#524]
Следить за выходом новых версий и потом скачивать сетап занудно. Как сделать пока не умею, но попробую разобраться. Как я это вижу:

1) При любом запуске oscript проверять наличие новой версии, если за последние сутки такая проверка не проводилась. Если при проверке обнаружили, что апдейт есть - запоминаем и выводим в консоль соответствующее сообщение при каждом запуске.

2) Команда oscript -update (или через opm). Запускается, увы, вручную. возможно ключ -update-nightly для ночных сборок.

**Comment by EvilBeaver** [comment]
Это уже зарубали раза три. И я уже забыл аргументацию. Помню, что с аргументами соглашался

**Comment by pumbaEO** [comment]
Если, только будет по умолчанию выключенно и включатся будет по флагу --trackme

**Comment by Faithfinder** [comment]
А почему, жалко раз в день сбегать в интернет и проверить версию?

**Comment by EvilBeaver** [comment]
@Faithfinder проще написать скрипт

    wget oscript.io
     setup.exe /q

И поставить его себе

**Comment by nixel2007** [comment]
Это будет решено в рамках opm/ovm

**Comment by pumbaEO** [comment]
@nixel2007 - апдейте в linux-e?

**Comment by dmpas** [comment]
`choco upgrade onescript.cli` по расписанию

**Comment by artbear** [comment]
+ В очередной раз напомню про мой старый репо
https://github.com/artbear/OneScript-install - Вин + Лин
+ а также есть варианты установки через choco

**Comment by EvilBeaver** [comment]
@nixel2007 ovm???

WTF?

**Comment by pumbaEO** [comment]
Если была возможность переопределить путь к бибилиотекам через переменную окружения, я бы тогда понял ovm, а так ...

**Comment by EvilBeaver** [comment]
Женя, уже есть возможность через env менять конфиг. В том числе параметр поиска библиотек

**Comment by pumbaEO** [comment]
Где? Я могу указать set OSCRIPT_LIBS=/home/shenja/test/ ?

**Comment by Faithfinder** [comment]
"Напиши себе проверку апдейтов сам" - это не юзерфрендли. Софт должен сам проверять наличие у себя апдейтов

**Comment by EvilBeaver** [comment]
@pumbaEO ты можешь написать set oscript_config=lib.system=mypath

**Comment by EvilBeaver** [comment]
Но не помню с какой версии
