### ISSUE TITLE
Неверная кодировка файлов в DEB-пакетах

### ISSUE THREAD

**Issue by naodesu** [EvilBeaver/OneScript#525]
После установки одного из пакетов
onescript-engine_1.0.17_all.deb
onescript-engine_1.0.18_all.deb
получаем неверную кодировку у тех файлов, в имени которых есть кириллица:
```
$ dpkg-query -L onescript-engine
...
/usr/share/oscript/lib/opm/src/������/����������������.os
/usr/share/oscript/lib/opm/src/������/�������Opm_Version.os
...

$ locale 
LANG=ru_RU.UTF-8
LANGUAGE=
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```
А так же не работает opm :
```
$ opm
{Модуль /usr/share/oscript/lib/opm/src/opm.os / Ошибка в строке: 0 / Ошибка загрузки библиотеки /usr/share/oscript/lib/opm/src. Обнаружены циклические зависимости.
-> /usr/share/oscript/lib/cmdline
  -> /usr/share/oscript/lib/logos
    -> /usr/share/oscript/lib/opm/src
}

$ ls /usr/share/oscript/lib/opm/src
������  opm.os
```

OS: Debian Jessie

**Comment by EvilBeaver** [comment]
Да, мы уже боремся с этой бедой. Спасибо!

@nixel2007, а что там за npm?

**Comment by nixel2007** [comment]
@EvilBeaver не понял, причем тут npm?

**Comment by naodesu** [comment]
@EvilBeaver Я опечатался, не npm а opm.

**Comment by nixel2007** [comment]
@naodesu @EvilBeaver npm в составе opm нет. А проблема та же, из-за неверной кодировки файлов opm не может нормально заимпортировать нужные ему библиотеки. Пытаемся побороть, да.
Как временное решение могу предложить воспользоваться вручную собранной 17ой версией от @dmpas https://files.gitter.im/EvilBeaver/OneScript/VreX/onescript-engine_1.0.17_all.deb

**Comment by dmpas** [comment]
@naodesu попробуй последний ночник. Мусор в нём всё ещё есть, но хотя бы работает.

**Comment by naodesu** [comment]
@dmpas opm Вроде работает, но некоторые файлы в пакете всё равно с неверной кодировкой.

**Comment by EvilBeaver** [comment]
@dmpas а что там еще за мусор? Какой природы?

**Comment by dmpas** [comment]
@EvilBeaver там лежат исходники пакета. но теперь там по два файла - и в правильной кодировке, и в битой.

**Comment by nixel2007** [comment]
Закрываем? @pumbaEO @dmpas
