### ISSUE TITLE
Не освобождается файл после закрытия "ЧтениеТекста"

### ISSUE THREAD

**Issue by realMaxA** [EvilBeaver/OneScript#528]
```
C:\temp>oscript
1Script Execution Engine. Version 1.0.17.90
```

Воспроизведение очень сложное, понять причину не могу.
Суть: Сначала при помощи "ЧтениеТекста" читаем содержимое файла (после чего говорим `ЧтениеТекста.Закрыть()`. Спустя какое-то время пытаемся писать в этот же файл при помощи "ЗаписьТекста", в результате чего получаем ошибку записи because it is being used by another process.

Воспроизведение:
1. `git clone https://github.com/realMaxA/FilesMonitor.git`
2. `cd FilesMonitor`
3. `git checkout 1ccd66dce2bda6547507cb19cf87012ce93c9e83`
4. `oscript src/main.os check README.md ../hashes.json`
5. `oscript src/main.os check ../hashes.json ../hashes.json`

Следующим коммитом (2b4e37ba9b75aa931284f494bee220a4ca0c4c9c) ошибка обойдена.

Инструкция `ОсвободитьОбъект(ЧтениеТекста)` не помогает

**Comment by dmpas** [comment]
Выяснил. Затык не в чтении/записи текста - там `Закрыть()` отрабатывает верно. Беда в Хешировании - `ДобавитьФайл()` захыватывает файл и не отпускает, пока Хеширование существует. А убивается хеширование, соответственно, сборкой мусора.

Путь обхода - вписать `ХешФайла.Очистить();` после того, как получена хеш-сумма.
Будем ли чинить поведение хеширования, я пока не знаю.

**Comment by realMaxA** [comment]
Вписывание `ХешФайла.Очистить()` не помогает. Работает только сборка мусора, причём не в этой процедуре, а там, где написано сейчас.

**Comment by EvilBeaver** [comment]
Конечно надо починить хеширование. Ему вроде бы незачем удерживать файл после подсчета суммы

**Comment by dmpas** [comment]
> Ему вроде бы незачем удерживать файл после подсчета суммы

тут надо проверить, как 1С себя ведёт.

**Comment by EvilBeaver** [comment]
Вообще говоря, странно. https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Hash/CombinedStream.cs#L88-L89

Тут явно закрываются все потоки, которые добавлены для подсчета хэша.

@realMaxA Очистить() должно помогать.

**Comment by EvilBeaver** [comment]
Вообще говоря, такие объекты надо явно закрывать через ОсвободитьОбъект. Это будет правильнее.

**Comment by EvilBeaver** [comment]
Закрою, т.к. по коду внутри класса все выглядит корректным. Если проблема останется - открою заново.
