### ISSUE TITLE
КопироватьФайл() не умеет копировать файлы по http

### ISSUE THREAD

**Issue by realMaxA** [EvilBeaver/OneScript#531]
Согласно документации 1С, при использовании процедуры `КопироватьФайл()` "Допускается использование схем http, https и ftp для адресации файлов." На данный момент соответствующая процедура onescript способна копировать файлы только в пределах файловой системы.

**Comment by dvakor** [comment]
![image](https://user-images.githubusercontent.com/4038422/64219866-72cd2d00-cef1-11e9-990d-9f97fd36a208.png)
Перемещение тоже работает с ftp \ http

Под капотом, у хттп перемещения GET \ DELETE вызовы

**Comment by dmpas** [comment]
Эту можно закрыть? @realMaxA @ArchLord42RU @EvilBeaver

**Comment by realMaxA** [comment]
> Эту можно закрыть? @realMaxA @ArchLord42RU @EvilBeaver

1.2.0: http Работает.
https не проверил. В лоб не работает: "Внешнее исключение (System.Net.WebException): Запрос был прерван: Не удалось создать защищенный канал SSL/TLS."

У меня вообще есть сомнения, что "КопироватьФайл" должен уметь в https даже в самой платформе 1С, несмотря на документацию.

**Comment by dmpas** [comment]
> У меня вообще есть сомнения, что "КопироватьФайл" должен уметь в https даже в самой платформе 1С, несмотря на документацию.

почему бы и нет?

**Comment by dvakor** [comment]
Думаю итогом будет решение: Если 1 умеет в хттпс, значит надо доработать, если нет закроем ишуз?)

**Comment by EvilBeaver** [comment]
я думаю 1С умеет в https, а в односкрипте код КопироватьФайл+HTTP отличается от реализации собственно СоединенияHTTP, в "соединении" ошибка насчет TLS пофикшена. И потом, скоро не останется сайтов без https, поэтому думаю, что надо эту возможность поддержать и перетащить в КопироватьФайл настройки TLS из СоединенияHTTP

**Comment by EvilBeaver** [comment]
@ArchLord42RU - наведи на мысль - мы закрываем ишуз или что?

**Comment by dvakor** [comment]
> @ArchLord42RU - наведи на мысль - мы закрываем ишуз или что?

По идее судя по комментам, там чет хттпс не пашет, докину тогда поддержку и прикроем.
