### ISSUE TITLE
Сборка пакета для VSC

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#536]
* Настроить в CI отдельную сборку компонентов пакета для VSC
* Настроить сборку пакета VSC и его публикацию на oscript.io

**Comment by nixel2007** [comment]
Добавлю:
* настроить автопубликацию готового vsix в маркетплейс VSCode из ветки мастер

**Comment by nixel2007** [comment]
Еще вариант публикации в релизы гитхаба, если они тебе нужны. https://github.com/silverbulleters/sonarqube-inject-vsc/blob/develop/.travis.yml#L21

**Comment by nixel2007** [comment]
Сборка готова. Что с публикацией? ты хочешь из девелопа рсинком так же публиковать отдельный файлик (пятый)?
