### ISSUE TITLE
Крах консоли при сворачивании блока кода

### ISSUE THREAD

**Issue by NeonSalamander** [EvilBeaver/OneScript#537]
При сворачивании блока кода в консоли появляется ошибка
Сигнатура проблемы:
  Имя события проблемы:	CLR20r3
  Сигнатура проблемы 01:	TestApp.exe
  Сигнатура проблемы 02:	1.0.17.95
  Сигнатура проблемы 03:	597b5966
  Сигнатура проблемы 04:	ICSharpCode.AvalonEdit
  Сигнатура проблемы 05:	4.4.2.9744
  Сигнатура проблемы 06:	536281b2
  Сигнатура проблемы 07:	7e7
  Сигнатура проблемы 08:	173
  Сигнатура проблемы 09:	System.InvalidOperationException
  Версия ОС:	6.1.7601.2.1.0.256.48
  Код языка:	1049
  Дополнительные сведения 1:	0a9e
  Дополнительные сведения 2:	0a9e372d3b4ad19135b953a78882e789
  Дополнительные сведения 3:	0a9e
  Дополнительные сведения 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by EvilBeaver** [comment]
Дайье кусок кода, пожалуйста, на котором воспроизводится

**Comment by nixel2007** [comment]
@EvilBeaver тестовая консоль умеет сворачивать области? :)

**Comment by EvilBeaver** [comment]
Ты не поверишь...

**Comment by NeonSalamander** [comment]
тестовый код без каких либо обязательств, падает при попытке свернуть блок комментариев

```
// <Описание функции>
//
// Параметры:
//  <Параметр1>  - <Тип.Вид> - <описание параметра>
//                 <продолжение описания параметра>
//  <Параметр2>  - <Тип.Вид> - <описание параметра>
//                 <продолжение описания параметра>
//
// Возвращаемое значение:
//   <Тип.Вид>   - <описание возвращаемого значения>
//
Функция ИмяФункции()
	
КонецФункции // ИмяФункции()  

ТЗ = Новый ТаблицаЗначений;
ТЗ.Колонки.Добавить("ИД");
ТЗ.Колонки.Добавить("Наименование");
НоваяСтрока = ТЗ.Добавить();
НоваяСтрока.ИД = "2";
НоваяСтрока.Наименование = "Тестовое";
```

**Comment by EvilBeaver** [comment]
Падает где-то внутри AvalonEdit. Возможно, имеет смысл обновить его версию.
