### ISSUE TITLE
После сборки exe файла, при его запуске возникает ошибка NullReferenceException

### ISSUE THREAD

**Issue by metal-doctor** [EvilBeaver/OneScript#539]
После сборки exe файла (-make), при его запуске возникает ошибка:
{Модуль test_ext.exe / Ошибка в строке: 4 / Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}

На версии 1.0.17.90 такая ошибка возникает при сборке exe файла.
На версии 1.0.18.51 сборка выполняется, а при запуске - возникает ошибка.

Пример: https://github.com/metal-doctor/001_NullReferenceException

**Comment by nixel2007** [comment]
Текст скрипта?

**Comment by dmpas** [comment]
@nixel2007 по ссылке "Пример"

**Comment by nixel2007** [comment]
Вангую, что еще может мешать одинаковое название методов... нэймспейсов-то нет.

//vanga_mode: off

**Comment by EvilBeaver** [comment]
Ох уж этот exe mode. На свежм ночнике аналогично?

**Comment by metal-doctor** [comment]
На последней версии 1Script Execution Engine. Version 1.0.18.54 - аналогично.

**Comment by metal-doctor** [comment]
@nixel2007 Упростил пример, вообще убрал методы в основном скрипте. Ошибка осталась.

**Comment by EvilBeaver** [comment]
Ок, принято. Спасибо

2 окт. 2017 г. 17:44 пользователь "metal-doctor" <notifications@github.com>
написал:

**Comment by artbear** [comment]
@EvilBeaver Теперь можно собирать экзешник с библиотеками внутри??

**Comment by EvilBeaver** [comment]
@artbear давно можно
