### ISSUE TITLE
Ошибка связанная с вызовом V83.COMConnector.ConnectAgent

### ISSUE THREAD

**Issue by Diversus23** [EvilBeaver/OneScript#540]
При выполнении кода:
`	V8 							= Новый COMObject("V83.COMConnector");	
	Попытка		
		Агент 	 = V8.ConnectAgent(ИмяСервера);
		...
`
валится на **V8.ConnectAgent** и в логе получаю ошибку:

> Ошибка в строке: 226 / Внешнее исключение (System.Runtime.InteropServices.COMException): Член группы не найден. (Исключение из HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND))}

При этом, в версии 1.0.16 все отрабатывает нормально, а в версиях повыше получаю исключение.

**Comment by dmpas** [comment]
> в версиях повыше

это в 17 или в 18 ??

**Comment by Diversus23** [comment]
И в той и в той. В 16-ой все нормально.

**Comment by EvilBeaver** [comment]
Ну в 18-й то я туда лазил и мог поломать, а в 17 странно. Тем более, что у нас на CI стоит ~~18~~ 17 и там без замечаний

**Comment by Diversus23** [comment]
Поставил последнюю не взлетело (18-ю), потом 17-ую, аналогично. Поставил 16-ую код заработал.
Не знаю :)

**Comment by EvilBeaver** [comment]
@Diversus23 на 18 воспроизводится, уже смотрю. На 1.0.17.90 работает автодеплой, 15 минут назад проблем не было. Там как раз похожее есть для выгона пользователей.

**Comment by Diversus23** [comment]
@EvilBeaver с сайта качал 1.0.17.95 (так написано в свойствах файла в OneScript-1.0.17-setup.exe)

**Comment by EvilBeaver** [comment]
Это привнесено в 18. Уже починил. Просто установка 17 поверх 18 не делает даунгрейд. Оно все равно 18-е осталось, видимо.

**Comment by EvilBeaver** [comment]
@Diversus23 спасибо, что нашел ошибку!

**Comment by Diversus23** [comment]
@EvilBeaver да было бы за что :) Тут уместнее: спасибо, что исправил!

**Comment by EvilBeaver** [comment]
Собралось и опубликовалось http://oscript.io/downloads
