### ISSUE TITLE
Свойства Дерева, Таблицы, Структуры не отображаются в отладчике

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#541]
При попытке раскрыть свойства локальной переменной типа ДеревоЗначений, СтрокаДереваЗначений, Структура, и др. не все свойства отображаются в отладчике.

**Comment by nixel2007** [comment]
да лааааадно. хотеть!

**Comment by EvilBeaver** [comment]
http://build.oscript.io/job/1Script/

**Comment by nixel2007** [comment]
Там экстеншен с протоколом еще не надо пересобирать?

А то у меня как-то грустненько.
![image](https://user-images.githubusercontent.com/1132840/31129795-4db93c4a-a85e-11e7-9149-3f12275f386c.png)

**Comment by EvilBeaver** [comment]
Дык надо, естессна. Правки и в сервере и в движке были

**Comment by EvilBeaver** [comment]
И на CI мне нужен докер-контейнер с нодой для сборки vsix

**Comment by nixel2007** [comment]
docker run --rm node:latest

:)

А если серьезно, то посмотри в sonar-backend. Там лежит собирающийся Dockerfile, в который можно через volume подключать каталог. в нем npm install и прочее.

**Comment by EvilBeaver** [comment]
Я все чаще думаю, что нам надо с тобой собрать мини-хакатон, сесть и наконец доделать все хвосты по опенсорсу.

Бухло и суши maybe?

**Comment by nixel2007** [comment]
Поддерживаю. Думаю, можно даже у нас дома :D

**Comment by artbear** [comment]
Я за
