### ISSUE TITLE
ПодключитьВнешнююКомпоненту("OneScript")

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#548]
Есть часть автоматизационных задач, которые проще делать на OneScript в силу наличия в нем различных библиотек. При этом некоторые управляющей конструкцией должна выступать 1С.

ЗапуститьПриложение, конечно, работает, но предлагаю обсудить возможность подключения оскрипта как внешней компоненты по NativeApi, с единственным (для начала) методом Выполнить().

В 18 движка релизе появился нативный Выполнить, типы из в с# пробрасываются тоже более-менее прозрачно.

/discuss

**Comment by artbear** [comment]
Тема интересная.
Но, если я не ошибаюсь, нативный Выполнить грузит только код без методов, верно, как и 1С?

**Comment by artbear** [comment]
и как определить путь к библиотекам для подключения в случае нативной ВК ?

**Comment by dmpas** [comment]
.net уже пробрасывали в 1с. Теми же средствами можно попробовать подключить движок односкрипта.

**Comment by nixel2007** [comment]
Помимо Выполнить вроде бы ещё хотели добавить (добавили?) ВыполнитьСценарий.

**Comment by EvilBeaver** [comment]
Некроссплатформенно - смотри вариант от @dmpas. Там только винда, но вроде как функционал полный, т.е. выполнить код 1скрипта будет можно.

Кроссплатформенно - пока идей нет. C++ CLI в моно не работает. Кажется, что ЗапуститьПриложение - дешево и сердито - наиболее жизнеспособный вариант.

**Comment by EvilBeaver** [comment]
Совсем ж0сткий вариант: NativeAPI, которое под капотом делает запуск приложения :)

**Comment by nixel2007** [comment]
Вроде никто не мешает сделать native-api so'шник?

**Comment by dmpas** [comment]
https://infostart.ru/public/541518/

**Comment by EvilBeaver** [comment]
> Вроде никто не мешает сделать native-api so'шник?

Зачем?

**Comment by nixel2007** [comment]
Чтобы из него подключать .Нет?
Я мож чего не знаю. В моем понимании Native api компонента - это просто обёртка, реализующая определённый интерфейс. Соответственно по сути задача сводится к подключению к движку из этой компоненты.

Я правильно понимаю, что проблема в вызове .нет из си?

**Comment by EvilBeaver** [comment]
Да, на моно

**Comment by nixel2007** [comment]
Оно как-то жутко костыльно и трудозатратно или в целом пока не особо реализуемо? Мне просто чтобы понять, стоит с этим вообще возиться или не очень.

**Comment by EvilBeaver** [comment]
Нереализуемо/сложно, поэтому можно эакостылить через запуск процесса, но зачем?

**Comment by nixel2007** [comment]
@EvilBeaver чтобы код скриптов не хранить где-то сбоку, в прямо в конфе, при этом не флашить их на диск, а сразу в памяти запускать.

Это так, размышления на тему решения прикладной задачи, которую я тебе вчера описывал.

**Comment by dmpas** [comment]
Запускаем односкрипт-хост-процесс, который слушает определённый порт, получает текст сценария и исполняет. В 1С будет как обычный вызов HTTP-службы.

**Comment by EvilBeaver** [comment]
Этот варинт я тоже понимал под" Запуск процесса" а вот внутри процесса 1с - проблемно
