### ISSUE TITLE
Ошибка разбора "Возврат КонецПроцедуры" 

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#549]
Не кушается правильный с точки зрения 1С код:
```bsl
Процедура НекотораяПроцедура()

	Возврат 

КонецПроцедуры
```

```
{Модуль bug.os / Ошибка в строке: 5 / Процедуры не могут возвращать значение}
```

**Comment by EvilBeaver** [comment]
Точку с запятой надо поствть. У нас по-моему вообще операторы без точки с запятой как в 1с не работают

**Comment by dmpas** [comment]
Я понимаю, что её надо поставить. Но это ж 1С:Несовместимо.

**Comment by EvilBeaver** [comment]
Засунь в 19 майлстоун пожалуйста

**Comment by nixel2007** [comment]
Перед концом операторных скобок 1с позволяет не ставить точку с запятой
