### ISSUE TITLE
Задокументировать + зафиксировать в тесте создание Net-типов, которые передачей простого имени класса не создаются

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#552]
Из гиттера https://gitter.im/EvilBeaver/OneScript?at=59e07dcce44c43700a29c3b8
>@EvilBeaver 11:48
@dmpas хочу поиграться в оскрипте с классом System.Uri, но не могу его подключить через COM-механизм работы с CLR
```bsl
 А = Новый COMОбъект("System.Uri", "file:///c:/djjd");
А = Новый COMОбъект("System.Uri, System", "file:///c:/djjd");
А = Новый COMОбъект("System.System.Uri,System", "file:///c:/djjd");
```

>Type.GetType упорно возвращает null

>Sergey Batanov @dmpas 11:49
то есть, конструктор исключения не бросает?

>Andrei Ovsiankin @EvilBeaver 11:50
Бросает, но потом, когда он уже понял, что это не CLR тип и уходит в ветку создания честного COM
Т.е. он я не могу правильно задать тип, чтобы он был опознан, как CLR

>Sergey Batanov @dmpas 11:54
https://stackoverflow.com/questions/12898282/type-gettype-not-working

>Artur Ayukhanov @artbear 12:02
@dmpas а для нас какой рецепт в итоге? как решить в оскрипте проблему Андрея?

>Andrei Ovsiankin @EvilBeaver 12:06
@dmpas если посмотреть в мой пример, то видно, что я пытался указать Assembly через запятую и не преуспел.

>Sergey Batanov @dmpas 12:14
System.Uri, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
вот так сработало.
ща, отсекая лишнее, надо привести к вменяемому виду
мда. ничего не отсеклось.

>Andrei Ovsiankin @EvilBeaver 12:15
Мдя, этого я и боялся
Нууу, в принципе, если есть через зпт только один идентификатор, то можно поискать его в зависимостях самой assembly односкрипта. и если она там есть, то оттуда вытянуть qualified name
Таким образом сократить до System.Uri, System

>Artur Ayukhanov @artbear 12:20
Поискать с помощью такого кода?
```c#
public static Type GetType(string typeName)
        {
            var type = Type.GetType(typeName);
            if (type != null) return type;
            foreach (var a in AppDomain.CurrentDomain.GetAssemblies())
            {
                type = a.GetType(typeName);
                if (type != null)
                    return type;
            }
            return null ;
        }
```

>Sergey Batanov @dmpas 12:20
да, сейчас пробую что-то в этом роде

>Artur Ayukhanov @artbear 12:23
А нельзя ли метод GetType подменять внутри движка на подобный код,
чтобы нам, клиентам в скриптах, не пришлось городить такой код?

>Sergey Batanov @dmpas 12:23
какой код ты собрался городить в клиентском скрипте?

>Alexey Sosnoviy @asosnoviy 12:24
шарповый?

>Sergey Batanov @dmpas 12:24
нормуль, с таким поиском типа срабатывает.

>Artur Ayukhanov @artbear 12:25
Мне бы не хотелось вместо простого Объект.GetType юзать такую внешнюю портянку кода

**Comment by dmpas** [comment]
я против. Раз уже решили, что .NET-типы для нас внешние, то будем предполагать, что человек, их использующий, разбирается в вопросе. Иначе это ровно то же самое, что документировать ADODB или WSH.

Поиск типа в загруженных сборках мы запилим.

**Comment by artbear** [comment]
Не согласен.
Нужно дать разработчику скриптов **удобные** возможности использования АПИ.
Иначе все будут тыкаться и задавать бесконечные вопросы.

А нам всего лишь нужно задокументировать (в доке или в тестах) правильный вызов

при всех вопросах будем направлять на эту доку.
это несложно, но будет очень полезно.

**Comment by dmpas** [comment]
Мы пробрасываем совершенно стороннее АПИ, на которое есть своя документация. Чтобы разработчику скриптов было удобно - для этого нужны библиотеки-обёртки над этим АПИ, которые будут в духе и букве ОдноСкрипта и которые уже можно документировать.

**Comment by artbear** [comment]
Сделать библиотеки-обертки - это очень долгий и непростой шаг, который непонятно кто и непонятно когда будет делать.

Я же предлагаю сделать **маленькое и несложное** дополнение, после которого новыми NET-объектами станет **удобнее** пользоваться.

Покажите мне, как решить/упростить проблему Андрея из ишуза.

Я лично зафиксирую это поведение или в доке, или в тесте.

Минимум действий и профит

**Comment by dmpas** [comment]
> Покажите мне, как решить/упростить проблему Андрея из ишуза.

это будет допилка в движок.

**Comment by EvilBeaver** [comment]
@artbear правильно я понимаю, что ты на днях добавил тест, после которого можно считать эту issue выполненной?

**Comment by artbear** [comment]
Нет, неправильно, в этом ишузе решается твоя проблема, которая еще не решена, насколько я понимаю.
Или @dmpas что-то сделал?
