### ISSUE TITLE
Рефлектор - расширение информации о методах

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#554]
Сейчас единственная информация о параметрах метода - это их количество.

Хотелось бы видеть информацию о наличии/значении параметра по умолчанию и наличии модификатора Знач.

**Comment by nixel2007** [comment]
Имена параметров, наверное, тоже могут быть полезными, но это "во вторую очередь"

**Comment by dmpas** [comment]
Решаем в рамках аннотаций. https://github.com/EvilBeaver/OneScript/issues/581

**Comment by EvilBeaver** [comment]
А разве не так что аннотации отдельно, а рефлексия списка параметров - отдельно? Разные все же вещи.

**Comment by dmpas** [comment]
ну как бы аннотации сейчас через рефлектор получаются.

**Comment by EvilBeaver** [comment]
Я к тому, что это 2 разных доработки рефлектора и чтобы не забыть, лучше пусть будут разными ишузами

**Comment by dmpas** [comment]
А, ну задачу-то я не закрываю. Просто обозначаю, что они связаны и что там можно погрузиться в ход работ.

**Comment by EvilBeaver** [comment]
Рефлексию имени параметра внезапно сделал в рамках #689

**Comment by artbear** [comment]
И как воспользоваться?
Нужно рефлектор подпилить, верно?

**Comment by EvilBeaver** [comment]
@artbear да. Суть в том, что теперь имя параметра добавлено в коллекцию параметров. НО это только один из шагов.

**Comment by EvilBeaver** [comment]
@nixel2007 не хочешь еще и этот челлендж закрыть?

**Comment by nixel2007** [comment]
Да можно попробовать

**Comment by EvilBeaver** [comment]
Закрыто в 900c7821
