### ISSUE TITLE
При попытке упаковка в EXE-модуль ОШИБКА (oscript v. 1.0.17.90)

### ISSUE THREAD

**Issue by CT144** [EvilBeaver/OneScript#557]
Make started...
ScriptEngine.Machine.ExternalSystemException: {Модуль C:\Program Files (x86)\OneScript\lib\logos\src\log-manager.os / Ошибка в строке: 68 / Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}    
		КаталогКонфига = СтартовыйСценарий().Каталог;

Что делать?

**Comment by EvilBeaver** [comment]
Миха, ты?

**Comment by CT144** [comment]
Нет, не Миха я.

С уважением,
 С.Тимонин

2017-10-16 18:08 GMT+03:00 Andrei Ovsiankin <notifications@github.com>:

**Comment by metal-doctor** [comment]
Похоже на вот это https://github.com/EvilBeaver/OneScript/issues/539.
В ночной сборке должнно быть исправлено, проверьте.

**Comment by EvilBeaver** [comment]
Это исправлено в версии 18, попробуйте

**Comment by CT144** [comment]
Да, в 18 работает. А подскажите, как отладчик 18 версии использовать?

2017-10-17 0:18 GMT+03:00 Andrei Ovsiankin <notifications@github.com>:

**Comment by CT144** [comment]
Увы, но и в 18 версии все не слава богу.
Использую в скрипте компоненту https://github.com/oscript-library/sql.
При выполнении из под oscript.exe все работает.
После упаковки в EXE, получаю ошибку:
{Модуль Service1cDB.exe / Ошибка в строке: 24 / Конструктор не найден
(Соединение)}

Попытки откатиться назад по версиям, вплоть до 15, безуспешны.


2017-10-17 0:18 GMT+03:00 Andrei Ovsiankin <notifications@github.com>:

**Comment by EvilBeaver** [comment]
Упаковка в EXE упаковывает только скрипты. Никакие двоичные данные (файлы, картинки, компоненты, и т.п.) в EXE не включаются.

В случае компоненты DLL, в принципе, можно попробовать положить ее рядом с EXE, она, скорее всего, подхватится.

Режим упаковки в EXE не является основным, и поддерживается по остаточному принципу. Мы будем только рады, если кто-то возьмет эту подсистему на себя и займется ее развитием.

Например, двоичные данные, входящие в EXE могут "доставаться" наподобие "Макетов" в 1С...

Сейчас ничего этого нет, работает только упаковка скриптовых модулей и активно развивать это я не предполагаю, именно из-за нехватки сил и времени.

**Comment by CT144** [comment]
Понял, спасибо.
