### ISSUE TITLE
ComОбъект Excel

### ISSUE THREAD

**Issue by iolko** [EvilBeaver/OneScript#558]
При работе с объектом Range у листа Excel, допустим:
`НачалоКопирования = Лист.range("A"+Сч); `
нельзя проверить переменную НачалоКопирования на заполненность, а именно `ЗначениеЗаполнено(НачалоКопирования) `- ошибка " Метод или операция не реализована", так же не реализован метод Copy объекта Range:
`Лист.Range(НачалоКопирования.Address+":"+КонецКопирования.Address).Copy();`
В 1С данные фрагменты кода отрабатывают без ошибок.

**Comment by EvilBeaver** [comment]
Возможно, связано в том числе с #559

**Comment by EvilBeaver** [comment]
@iolko а подскажите, 1С для Com-коллекций как обрабатывает ЗначениеЗаполнено? Проверяет на количество элементов в коллекции или просто, если не Неопределено, то считает заполнено?

**Comment by EvilBeaver** [comment]
Первый вариант со ЗначениеЗаполнено я починил. Насчет Copy ошибку не подтверждаю, у меня он работает.

**Comment by iolko** [comment]
Проверил, все работает, спасибо!
