### ISSUE TITLE
COMОбъект ADODB.Connection в 18 версии глючит

### ISSUE THREAD

**Issue by CT144** [EvilBeaver/OneScript#559]
Один и тот же "скрипт":
`	Лог.Отладка("Пытаемся соединиться!");
	Соединение = Новый COMОбъект("ADODB.Connection");
	_СтрокаСоединения = ПолучитьСтрокуСоединения(БД);
	Лог.Отладка(_СтрокаСоединения);
	Результат = Соединение.Open(_СтрокаСоединения);
	Лог.Отладка("Соединились");
`
на разных версиях разные результаты:
ОТЛАДКА - Начали (OneScript v.1.0.18.13) ...
ОТЛАДКА - Пытаемся соединиться!
ОТЛАДКА - Provider=SQLOLEDB; Data Source="SQLsrv"; Initial Catalog="debug_2"; User Id="aaaaa"; Password="zzzzz";
ОТЛАДКА - {Модуль ADOSQL.os / Ошибка в строке: 29 / Внешнее исключение (System.Reflection.TargetInvocationException): Адресат вызова создал исключение.}
ОТЛАДКА - . . . . . ЗАКОНЧИЛИ

ОТЛАДКА - Начали (OneScript v.1.0.17.90) ...
ОТЛАДКА - Пытаемся соединиться!
ОТЛАДКА - Provider=SQLOLEDB; Data Source="SQLsrv"; Initial Catalog="debug_2"; User Id="aaaaa"; Password="zzzzz";
ОТЛАДКА - Соединились
ОТЛАДКА - . . . . . ЗАКОНЧИЛИ

**Comment by CT144** [comment]
Не понял.


2017-10-18 10:46 GMT+03:00 Nikita Gryzlov <notifications@github.com>:

**Comment by nixel2007** [comment]
@CT144 это призыв последнего правившего сом-объекты :)

**Comment by CT144** [comment]
Моя твоя не понимай.

**Comment by dmpas** [comment]
@CT144 это такой способ позвать меня в обсуждение.

**Comment by EvilBeaver** [comment]
Ну, во-первых, надо найти, где выскочило из заслона System.Reflection.TargetInvocationException и выдавать не его, а InnerException от него.

**Comment by EvilBeaver** [comment]
@CT144 можешь дать точный кусок кода, чтобы не гадать, а сразу запустить?

**Comment by CT144** [comment]
Лог.Отладка("Пытаемся соединиться!");
    Соединение = Новый COMОбъект("ADODB.Connection");
    _СтрокаСоединения = "Provider=SQLOLEDB; Data Source="""+ИмяСервера+""";
Initial Catalog="""+ИмяБД+"""; User Id="""+Пользователь+"""; Password="""
+Пароль+""";";
    Лог.Отладка(_СтрокаСоединения);
    Попытка
        Соединение.Open(_СтрокаСоединения);
        Результат = Истина;
    Исключение
        Результат = Ложь;
        ВызватьИсключение("НЕ удалось установить соединение с БД:"+
_СтрокаСоединения);
    КонецПопытки;
    Лог.Отладка("Соединились");

2017-10-20 15:52 GMT+03:00 Andrei Ovsiankin <notifications@github.com>:

**Comment by Tavalik** [comment]
Ишус закрыт, но у меня такая же ошибка. Версия OneScript - 1.0.19.105. При работе с ADODB.Connection получаю ошибку:

> (System.Reflection.TargetInvocationException): Адресат вызова создал исключение.}

Но блин, в версии 1.0.17.90 все работает отлично.

Как же так?

**Comment by EvilBeaver** [comment]
@Tavalik а кусок кода тот же?

**Comment by Tavalik** [comment]
Один и тот же код.

**Comment by dvakor** [comment]
Попробуйте ночную сборку, в ней фикс должен присутствовать. В 1.0.19.105 ошибка не была исправлена ( #670 )

**Comment by EvilBeaver** [comment]
@ArchLord42RU насколько я понял, @Tavalik говорит, что в 20-ке тоже не работает.

**Comment by Tavalik** [comment]
Нет, в 1.0.20 работает. Спасибо. Ждем релиза и рабочего отладчика в 20.

**Comment by nixel2007** [comment]
@tavalik отладчик работает в 20 :)

**Comment by Tavalik** [comment]
Расскажите тогда как? Из магазина ставится версия расширения 0.2.0. На сайте тоже только эта версия http://oscript.io/downloads. Где взять vsix для Oscript 20? Или я чего-то не понимаю?

**Comment by nixel2007** [comment]
@Tavalik - о, поломалась сборка отладчика на ночник
@EvilBeaver

**Comment by nixel2007** [comment]
@EvilBeaver точнее сборка сама работает. но почему-то в загрузках нет нужного линка.

@Tavalik пока можно взять напрямую с билд-сервера - http://build.oscript.io/job/1Script/job/develop/lastSuccessfulBuild/artifact/built/vscode/

**Comment by Tavalik** [comment]
Спасибо. Было бы здорово и на сайт добавить.

**Comment by EvilBeaver** [comment]
@Tavalik то что в ночной сборке отсутствует отладчик - это поломка. Он должен там быть. Посмотрю, что случилось.

**Comment by EvilBeaver** [comment]
@Tavalik отладчик для 20-ки опубликован на сайте
