### ISSUE TITLE
Win XP 64 HTTPS

### ISSUE THREAD

**Issue by serpentariy** [EvilBeaver/OneScript#560]
Здравствуйте, WinXP64 и простая WinXP. Пытаюсь послать запрос GET на сайт, получаю ошибку... 
` Внешнее исключение (System.Net.WebException): The request was aborted: Could not create SSL/TLS secure channel.`

На Win10 скрипт отрабатывает.
ранее пробовал писать запрос через WinHttp.WinHttpRequest.5.1, создавая VBS скрипт. Если скрипт запускать через cmd таже ошибка, если через Explorer все OK. По этому и решил попробовать Ваш OneScript, но в нем не используется 'ЗащищенноеСоединениеOpenSSL', по этому и не получается установить соединение. Как побороть?

**Comment by dmpas** [comment]
попробуйте взять ночную сборку, в HTTPСоединении не указывайте ЗащищенноеСоединеие, а в адресе хоста напишите `https://`

**Comment by dmpas** [comment]
то есть, просто:
```bsl
	Соединение = Новый HTTPСоединение("https://myhost.ru/");
```

**Comment by serpentariy** [comment]
Попробую

**Comment by serpentariy** [comment]
![opm](https://user-images.githubusercontent.com/32895914/31711611-65efb9fc-b401-11e7-9937-48c9a90efa3c.jpg)
Установил ночную сборку, при запуске получаю ошибку

**Comment by dmpas** [comment]
Забавно.  .Net Framework 4.5 установлен ?

**Comment by serpentariy** [comment]
нет

**Comment by serpentariy** [comment]
Блокирующие требования:

.NET Framework 4.5 не поддерживается этой операционной системой.

**Comment by dmpas** [comment]
попробуйте, вдруг через моно получится: http://www.mono-project.com/download/

**Comment by dmpas** [comment]
> Supported on Windows 7, 8, 10 or later.

тоже нет ...

**Comment by serpentariy** [comment]
Печаль

**Comment by artbear** [comment]
Прикольно - на XP мы не работаем :(

**Comment by nixel2007** [comment]
Поддержку XP дропнули в то ли 16ом то ли 17 ом релизе. Осознанно.

**Comment by serpentariy** [comment]
Ну если только "осознано".... на ХР у  нас еще многие работают и "перетекать" не собираются на 10-ку. (:

**Comment by EvilBeaver** [comment]
Есть вариант пересобрать из исходников под 4-й .net Вроде бы мы не вносили никаких существенных зависимостей от нового фремворка.

**Comment by dmpas** [comment]
@EvilBeaver вот не поверишь, не соберётся.
взял 17-й выпуск, закинул туда один свой коммит по сертификатам - не собралось:

https://ci.appveyor.com/project/dmpas/onescript/build/1.0.17-alpha227

**Comment by serpentariy** [comment]
У нас много Хотелок(задумок заказчика) с использованием "GET"-запросов в 1С7.7.
с ХР он(заказчик) переходить не хочет. При помощи WinHttp.WinHttpRequest.5.1, создавая VBS скрипт не взлетело.... Хотелось проверить Ваше, но видно тоже не судьба

**Comment by nixel2007** [comment]
Попробуйте поставить 15ый или 16ый движок

**Comment by serpentariy** [comment]
ни на 15 ни на 16 не взлетело...
`Внешнее исключение (System.Net.WebException): The request was aborted: Could not create SSL/TLS secure channel.`

**Comment by EvilBeaver** [comment]
Ну значит тут проблема в самом объекте, и в WinXP

**Comment by EvilBeaver** [comment]
Если и на VBS не работает, то предлагаю закрыть задачу

**Comment by serpentariy** [comment]
Да нет.... если запускать скрипт через cmd wscrypt.exe имя скрипта... не работает,а если через explorer имя скрипта, работает НО выскакивают запросы безопасности запуска.

**Comment by EvilBeaver** [comment]
Получается, что на VBS тоже не работает в неинтерактивном режиме. И проблема тут не в 1script.

**Comment by serpentariy** [comment]
Я не говорил ,что проблема в 1script, я писал что в 1С у HTTPСоединение есть параметр 'ЗащищенноеСоединениеOpenSSL'. в ОдинСкрипт Вы его не используете. вот и возник вопрос.

**Comment by dmpas** [comment]
@serpentariy @EvilBeaver закрываем?

**Comment by serpentariy** [comment]
Re[2]: [EvilBeaver/OneScript] Win XP 64 HTTPS (#560)


Здравствуйте, Sergey.

Вы писали 28 ноября 2017 г., 13:56:10:





@serpentariy @EvilBeaver закрываем?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



закрывайте, если ничего сделать нельзя

-- 
С уважением,
программист
internecional.corp

 Sergey                          mailto:serpent1C@bk.ru
