### ISSUE TITLE
Исправить устаревшую документацию по тестированию

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#563]
>Зашел на оффсайт оскрипта, раздел "Тестирование": http://oscript.io/docs/page/testing. Прочитал примеры, перешел по ссылке из предложения "Для запуска тестов используется скрипт testrunner.os." (второе предложение сверху на странице) в проект https://github.com/EvilBeaver/oscript-library/tree/develop/tests . Там ридми ссылается на https://github.com/oscript-library/1testrunner/ . Во всех трех местах (oscript.io, EvilBeaver/oscript-library, oscript-library/1testrunner) написано, что для тестов нужно использовать testrunner.os

Нужно исправить доку в указанных соседних местах

Исходный ишуз для 1testrunner https://github.com/artbear/1testrunner/issues/19

@EvilBeaver Сможешь поправить? или мне дай права на исправление

**Comment by asosnoviy** [comment]
@artbear сюда шли пр https://github.com/otymko/OneScript.WebSite

**Comment by asosnoviy** [comment]
@EvilBeaver закрывай висяк

**Comment by EvilBeaver** [comment]
Не, надо бы и правда исправить. Только есть проблема. Я не тестирую и не знаю, как сейчас надо - через opm test или через 1bdd или что...

**Comment by EvilBeaver** [comment]
@artbear будь другом, скажи, что делать с задачей?

**Comment by artbear** [comment]
@EvilBeaver сделал ПР в правильный проект https://github.com/otymko/OneScript.WebSite/pull/27
принимайте его.

не стал делать ссылки на 1testrunner, оставил tests\testrunner.os, т.к. помню, что в движке юзается именно встроенный
