### ISSUE TITLE
Неочевидное падение функции Вычислить

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#564]
Жмякание F5 [вот здесь](https://github.com/nixel2007/moskito/blob/develop/test.os) приводит к выбросу исключения:
```
{Модуль <string> / Ошибка в строке: 328 / Внешнее исключение (System.InvalidOperationException): Symbol already defined in the scope (ИспользоватьАутентификациюОС)}
```

Попытался воспроизвести на вот таком случае (и из строки и из обычного сценария) - не падает.

```bsl
Объект1 = Новый HTTPСоединение("http://localhost");
Объект2 = Новый HTTPСоединение("http://localhost");

ИмяСвойства = "ИспользоватьАутентификациюОС";

А = Вычислить("Объект1." + ИмяСвойства);
Б = Вычислить("Объект2." + ИмяСвойства);

МодульПроверки = ЗагрузитьСценарийИзСтроки(
	"Процедура Проверить(Объект1, Объект2, ИмяСвойства, Итерация) Экспорт
	|	
	|	Сообщить(Итерация);
	|	Если Итерация > 20 Тогда
	|		Возврат;
	|	КонецЕсли;
	|	
	|	А = Вычислить(""Объект1."" + ИмяСвойства);
	|	Б = Вычислить(""Объект2."" + ИмяСвойства);
	|	
	|	Если Истина Тогда
	|		Проверить(Объект1, Объект2, ИмяСвойства, Итерация + 1);
	|	КонецЕсли;
	|	
	|КонецПроцедуры"
);
МодульПроверки.Проверить(Объект1, Объект2, ИмяСвойства, 1);

```

**Comment by artbear** [comment]
Я также пробовал на разных примерах с переработкой кода москито.
Вычислить работает всегда, кроме кода с указанной вложенностью из москито :(

**Comment by nixel2007** [comment]
Хвала шаманам окна и пузатого пингвина, починилось само.

**Comment by EvilBeaver** [comment]
Так не бывает.. никто ничего не трогал. Точно починилось и точно ли был мальчик?

**Comment by nixel2007** [comment]
@EvilBeaver у @artbear воспроизводилось на другом компе. Теперь на моем работает, Артур вроде ещё не проверял

**Comment by artbear** [comment]
@EvilBeaver @nixel2007 У меня также вылечилось :) 
ночник вчера поставил 1.0.19.94
