### ISSUE TITLE
Перевести содержимое сайта oscript.io в опенсорс

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#568]
Хранить markdown содержимого.

**Comment by ArsenShnurkov** [comment]
У меня есть отличный мегаплан, даже два. Сайт ведь весь насквозь статичный?
1) Нужно использовать gh-pages фичу гитхаба, а страницы формировать при помощи хука интегрированного с Travis-CI и шаблонного движка Razor.
2) Razor надо переписать на языке 1Скрипт

**Comment by EvilBeaver** [comment]
@ArsenShnurkov ты не поверишь, но у нас даже есть под это проект. https://github.com/EvilBeaver/OneScript.Web

Сайт не совсем статичный, из динамики там отображение доступных файлов в downloads

**Comment by ArsenShnurkov** [comment]
1) список файлов наверное обновляется коммитами (ну или можно так сделать), а значит хук перегенерирует всё что нужно. Так что можно считать сайт совсем статичным
2) Razor можно использовать без MVC (как и oscript.exe из консоли), поэтому тот ваш проект - он скорее для другого, решает более сложную задачу, чем минимально необходимая. Его надо будет хостить и не получится всё провернуть только в рамках одного Travis-CI

**Comment by EvilBeaver** [comment]
Короче, тут целое поле для попроектировать. Изначально, данная issue предполагала тупое размещение существующего маркдауна на гитхабе.

**Comment by EvilBeaver** [comment]
https://github.com/EvilBeaver/oscriptiocontent
