### ISSUE TITLE
Падение теста managed-com в ветке develop

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#571]
В ветке develop стабильно падает 1 тест. В 18 релизе не падает.

@dmpas обещал посмотреть

**Comment by dmpas** [comment]
Не поверишь, открыл вот райдер полчаса назад.

**Comment by dmpas** [comment]
и самая беда, что у меня тест не падает...

**Comment by dmpas** [comment]
```
<testcase classname="managed-com" name="ТестДолжен_ПроверитьСозданиеClrОбъекта" status="passed"/>
<testcase classname="managed-com" name="ТестДолжен_ПроверитьСозданиеClrКоллекции" status="passed"/>
<testcase classname="managed-com" name="ТестДолжен_ПроверитьСозданиеClrКоллекцииШаблона" status="passed"/>
<testcase classname="managed-com" name="ТестДолжен_ПроверитьТипыClrОбъектов" status="passed"/>
<testcase classname="managed-com" name="ТестДолжен_ПроверитьРаботуGetType" status="passed"/>
<testcase classname="managed-com" name="ТестДолжен_ПроверитьРаботуGetTypeДляЭлементовСписка" status="passed"/>
<testcase classname="managed-com" name="ТестДолжен_ПроверитьРаботуGetTypeДляCLRКоллекции" status="passed"/>
<testcase classname="managed-com" name="ТестДолжен_ПроверитьРаботуТипаНеИзЯдра" status="passed"/>
```

@EvilBeaver  это же значит, прошли?

**Comment by EvilBeaver** [comment]
Напасть, как она есть

**Comment by dmpas** [comment]
Понял, почему у меня не падает: я под AnyCPU собираю. Под x86 тоже падает - будут разбираться.

**Comment by dmpas** [comment]
Жестяная жесть. Первый раз при поиске типа он находит `ADODB.ConnectionClass` как COM-объект по ProgID `ADODB.Connection`.
А второй раз он находит его (опа!) в подключенной сборке! Видимо, при первом подключении COM-объекта, он в текущий домен подгружает найденную сборку. В х64 такой сборки не было и всегда срабатывал чистый COM-объект - потому у меня тесты не падали.

Копаю дальше.

**Comment by EvilBeaver** [comment]
@dmpas что-то пошло не так http://build.oscript.io/job/1Script/job/develop/87/testReport/

**Comment by dmpas** [comment]
![3b3](https://user-images.githubusercontent.com/5665433/32042910-e15169ce-ba41-11e7-8c49-b09d509ec23b.jpg)

**Comment by EvilBeaver** [comment]
@dmpas думаю, если мы просто отрубим этот тест на Linux - будет не очень больно

**Comment by dmpas** [comment]
@EvilBeaver я не теряю надежды.
