### ISSUE TITLE
Некоторые сообщения при сборке на Gentoo Linux

### ISSUE THREAD

**Issue by ArsenShnurkov** [EvilBeaver/OneScript#574]
$ mono oscript.exe 
    1Script Execution Engine. Version 1.0.19.0
    
    Usage:
    
    I. Script execution: oscript.exe <script_path> [script arguments..]
    
    II. Special mode: oscript.exe <mode> <script_path> [script arguments..]
    Mode can be one of these:
      -measure    measures execution time
      -compile    shows compiled module without execution
      -check [-env=<entrypoint-file>]provides syntax check
      -check -cgi provides syntax check in CGI-mode
    
      -encoding=<encoding-name> set output encoding
      -codestat=<filename> write code statistics
    
    III. Build standalone executable: oscript.exe -make <script_path> <output_exe>
      Builds a standalone executable module based on script specified
    
    IV. Run as CGI application: oscript.exe -cgi <script_path> [script arguments..]
      Runs as CGI application under HTTP-server (Apache/Nginx/IIS/etc...)

**Comment by ArsenShnurkov** [comment]
https://github.com/EvilBeaver/OneScript/blob/d1bf7fba64c4049691a508bef9777ac65c3782a8/src/StandaloneRunner/StandaloneRunner.csproj#L131-L132

что-то не так со свойством OS

**Comment by ArsenShnurkov** [comment]
Следующая ошибка:

msbuild /p:OS=Unix 1Script_Mono.sln

/usr/src/git/github.com/1script/xDrivenDevelopment/src/1Script_Mono.sln : Solution file error MSB4051: Project {2590E2BB-CC1F-4775-80ED-451F45C9A4F1} is referencing a project with GUID {795AA2F5-3074-4BC5-A30F-1B6354044D9B}, but a project with this GUID was not found in the .SLN file

**Comment by ArsenShnurkov** [comment]
/usr/share/msbuild/Microsoft.Common.CurrentVersion.targets(2000,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Ionic.Zip". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/usr/src/git/github.com/1script/EvilBeaver/src/ScriptEngine.HostedScript/ScriptEngine.HostedScript.csproj]

**Comment by ArsenShnurkov** [comment]
Я осознал всю глубину своего морального падения, как дособеру отпишусь.

**Comment by ArsenShnurkov** [comment]
$ mono StandaloneRunner.exe 
No module found

Нда...

**Comment by EvilBeaver** [comment]
Я уже не помню точно, @dmpas возможно, подскажет. По-моему, для сборки под линукс нужно собирать файл 1Script_Mono.sln

**Comment by ArsenShnurkov** [comment]
Всё уже собрали, опакетили, в официальный оверлей <a href="https://github.com/gentoo/dotnet/pull/343">поместили</a>, теперь только тестировать надо

**Comment by EvilBeaver** [comment]
А где бы все это посмотреть? А то у нас есть пакет в arch, делал, если не ошибаюсь @konarev, но он обновляется руками и, как правило, неактуален.

**Comment by ArsenShnurkov** [comment]
у меня тоже руками. Я же дал <a href="https://github.com/gentoo/dotnet/pull/343">ссылку</a>. Если язык будет полезным, то потом утрясётся и заавтоматизируется.

**Comment by EvilBeaver** [comment]
@ArsenShnurkov ссылку не заметил, спасибо.

Из чистого любопытства: mpkh пишет "omg odin ass". Это он откуда понабрался? :)

**Comment by ArsenShnurkov** [comment]
Он русскоговорящий. Просто пошутил, смешно же :)

**Comment by EvilBeaver** [comment]
Смешно, да. Я просто подумал, что где-то в исходниках у вас так написано ) Но уже вижу, что нет.
