### ISSUE TITLE
Добавить отсутствующее свойство ThisObject

### ISSUE THREAD

**Issue by leemuar** [EvilBeaver/OneScript#575]
Русский синоним существует - ЭтотОбъект, а английского нет.

**Comment by leemuar** [comment]
> Sergey Batanov @dmpas 17:17
> там помимо этого ещё надо искать "магическое +1" и поменять на "магическое +2". насколько я помню.
> потому что раньше у нас был ЭтотОбъект + определённые свойства, а теперь ЭтотОбъект + ThisObject + нувыпоняли

**Comment by EvilBeaver** [comment]
@dmpas вроде бы этого больше нет

**Comment by dmpas** [comment]
Возможно. Я год назад там лазил последний раз.
