### ISSUE TITLE
Неожиданное завершение скрипта с ошибкой из движка

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#577]
При запуске `1bdd exec .\features\ВыгрузитьИнфоБазуВФайлdt.feature` возникает ошибка
```ОШИБКА   -       {Модуль C:\OneScript\lib\1bdd\src\bdd-exec.os / 
Ошибка в строке: 430 / 
Внешнее исключение (ScriptEngine.Machine.WrongStackConditionException): 
Внутренняя ошибка: неверное состояние стека}
```
**Ошибка возникает как на 18 релизе, так и на свежайшей версии 19
На 17 релизе работает.**
в линуксе аналогично
из-за этой проблемы у нас на локальных машинах нельзя протестировать `vanessa-runner`

**Сценарий повторения:**
+ ставим движок, 18 или 19
  + с установкой штатных библиотек
+ opm install 1bdd
+ opm install vanessa-runner
+ переходим в каталог vanessa-runner
+ запускаем команду `1bdd exec .\features\ВыгрузитьИнфоБазуВФайлdt.feature`

@EvilBeaver @dmpas Сценария достаточно для анализа проблемы?

Начало в https://gitter.im/EvilBeaver/OneScript?at=59fcd584614889d4753899a8

Лог из гиттера:

>  Artur Ayukhanov @artbear нояб. 03 23:45

@EvilBeaver @dmpas Возникла проблема с неожиданным поведением 1скрипта.

есть коммит https://github.com/silverbulleters/vanessa-runner/commit/44e87c92b30d334746a60f36f03b3ddaae4f0198
это свежая ветка develop продукта

запускаю для этого состояния `1bdd features`

через пару секунд получаю следующий лог и ошибку:
```
     Я выполняю команду "oscript" c параметрами "<КаталогПроекта>/src/main.os dump ./build/1Cv8.dt --ibconnection /F./build/ib"
vanessa-runner v0.15.0
03.11.2017 23:41:40: ИНФОРМАЦИЯ - Запускаю выгрузку информационной базы в файл
03.11.2017 23:41:42: ИНФОРМАЦИЯ - Выгрузка информационной базы успешно завершена

03.11.2017 23:41:42: ИНФОРМАЦИЯ - Выгрузка в файл завершена.

      Я сообщаю вывод команды "oscript"
      Код возврата команды "oscript" равен 0
      Файл "./build/1Cv8.dt" существует
      Вывод команды "oscript" содержит
      """
      Выгрузка в файл завершена.
      """


ОШИБКА   -       {Модуль C:\OneScript\lib\1bdd\src\bdd-exec.os / Ошибка в строке: 430 / 
Внешнее исключение (ScriptEngine.Machine.WrongStackConditionException): Вну
тренняя ошибка: неверное состояние стека}
```

Ошибка возникает как на 18 релизе, так и на свежайшей версии 19 (хотя почему-то дата 26.10.2017) :worried:
Подскажете?
1bdd давно не менялся.

@pumbaEO у тебя vanessa-runner в develop проходит фичи?

Evhen Sosna @pumbaEO нояб. 04 09:37
@artbear тут вроде все работает `http://ci.silverbulleters.org/job/Vanessa-runner/job/develop/`

Evhen Sosna @pumbaEO нояб. 04 09:51
да, на 19 подтверждаю.
```
ОШИБКА   -       {Модуль C:\Program Files (x86)\OneScript\lib\1bdd\src\bdd-exec.os / Ошибка в строке: 430 / Внешнее исключение (ScriptEngine.Machine.WrongStackConditionException): Внутренняя ошибка: неверное состояние стека}
ПРЕДУПРЕЖДЕНИЕ - Попытка удаления C:\Users\esosna\AppData\Local\Temp\2\gguvivzs.on3.tmp закончилась неудачей, по причине {Модуль C:\Program Files (x86)\OneScript\lib\tempfiles\ВременныеФайлы.os / Ошибка в строке: 74 / Внешнее исключение (System.IO.IOException): Процесс не может получить доступ к файлу "C:\Users\esosna\AppData\Local\Temp\2\gguvivzs.on3.tmp", так как этот файл используется другим процессом.}
```

**причем ошибка именно для 1bdd exec .\features\ВыгрузитьИнфоБазуВФайлdt.feature**
**в линукс тоже самое, на 18 движке**

**У нас на CI.s-b.org находится версия 1.0.17.95**
поэтому там тестирование ванесса-раннер и работает

**Comment by dmpas** [comment]
> Сценария достаточно для анализа проблемы?

для анализа хотелось бы чего попроще. Там в стэке закопаться можно, пока от старта 1bdd до точки падения дойдёт...

**Comment by pumbaEO** [comment]
Шаг Допустим я подготовил репозиторий и рабочий каталог проекта - все ломает, точнее метод Шаг.ВыполнитьШаг(), который вызывается в методе реализации шага.  В фиче я оставил только 2 шага, "Допустим я подготовил репозиторий и рабочий каталог проекта" содержит в себе только "БДД.ВыполнитьШаг("И ии")". 
```
# language: ru

Функционал: Выгрузка базы данных в dt
  
Контекст:
    Допустим я подготовил репозиторий и рабочий каталог проекта
    
Сценарий: Выгрузка базы данных в dt файл
    
    Допустим Я выполняю команду "oscript" c параметрами "<КаталогПроекта>/src/main.os dump ./build/1Cv8.dt --ibconnection /F./build/ib"  
```

в реализации шагов в БазовыйКонтекст.os в методе ЯПодготовилРепозиторийИРабочийКаталогПроекта, оставляю только одну строку БДД.ВыполнитьШаг("и ИИ"); 
```
//я подготовил репозиторий и рабочий каталог проекта
Процедура ЯПодготовилРепозиторийИРабочийКаталогПроекта() Экспорт
	БДД.ВыполнитьШаг("и ИИ");
КонецПроцедуры
```
и получаю указанную ошибку. 

```
oscript ./oscript_modules/1bdd/src/bdd.os exec ./features/ВыгрузитьИнфоБазуВФайлdt.feature
BDD for OneScript ver.1.5.2
Это ВыполнитьФичуСУчетомБиблиотечныхШагов
Эээээто я
Функциональность Выгрузка базы данных в dt
   Как разработчик
   Я хочу иметь возможность делать быструю выгрузку базы данных в файл dt
   Чтобы выполнять коллективную разработку проекта 1С
   Сценарий Выгрузка базы данных в dt файл
      Контекст 
Я переопределил
Эээээто я
ПРЕДУПРЕЖДЕНИЕ 	 - ии
Не реализован
ОШИБКА 	 - У шага <я подготовил репозиторий и рабочий каталог проекта>
- {Модуль /home/shenja/projects/sl/vanessa-runner/oscript_modules/1bdd/src/bdd-exec.os / Ошибка в строке: 98 / Неверно выполнен шаг <и ии>}    
- 		ВызватьИсключение СтрШаблон("Неверно выполнен шаг <%1>", НаименованиеШагаСценария);
ОШИБКА 	 - я подготовил репозиторий и рабочий каталог проекта
Сломался

      Я выполняю команду "oscript" c параметрами "<КаталогПроекта>/src/main.os dump ./build/1Cv8.dt --ibconnection /F./build/ib"
      
      
ОШИБКА 	 -       {Модуль /home/shenja/projects/sl/vanessa-runner/oscript_modules/1bdd/src/bdd-exec.os / Ошибка в строке: 434 / Внешнее исключение (ScriptEngine.Machine.WrongStackConditionException): Внутренняя ошибка: неверное состояние стека}
```

**Comment by artbear** [comment]
@pumbaEO Женя, отформатируй, плиз, свое сообщение.
сейчас непонятно, как ты исправил и что еще сделал.

**Comment by artbear** [comment]
@dmpas Если бы можно было найти проще, давно бы сделали :)
Пока особо больше помочь не можем.
Раньше работало, а теперь нет :(

**Comment by EvilBeaver** [comment]
Ок, принимаем к расследованию пока это

**Comment by nixel2007** [comment]
Возможно проблемы со стеком как-то связаны с соседним ишузом про москито

**Comment by EvilBeaver** [comment]
@nixel2007 это с которым ишузом?

**Comment by artbear** [comment]
Я так понимаю, что с Выполнить https://github.com/EvilBeaver/OneScript/issues/564

**Comment by EvilBeaver** [comment]
Нет это разные.

**Comment by artbear** [comment]
Вчера с Женей слегка упростили проблему и выяснили, что падает именно вызов `БДД.ВыполнитьШаг`
Я подготовил демо-пример [files-for-577.zip](https://github.com/EvilBeaver/OneScript/files/1456958/files-for-577.zip)

**Сценарий повторения:**
+ ставим движок, 18 или 19
  + с установкой штатных библиотек
+ opm install 1bdd
+ переходим в каталог архива
+ запускаем команду `1bdd exec .\1.feature`

**Comment by artbear** [comment]
Надеюсь, так будет попроще разбираться.
и `opm install vanessa-runner` выполнять уже не нужно

**Comment by artbear** [comment]
Эта ошибка в 1.0.19.94 повторяется.

**Comment by EvilBeaver** [comment]
Какая-то квантовая ошибка :( проявляется только когда на нее не смотрят отладчиком. Heisenbug, мать его.

**Comment by artbear** [comment]
Прикольные я баги нахожу, да? :)

**Comment by EvilBeaver** [comment]
Да там у тебя и код своеобразный )))

15 нояб. 2017 г. 15:27 пользователь "Artur Ayukhanov" <
notifications@github.com> написал:

**Comment by artbear** [comment]
Так, прямой наезд зафиксирован :)

А что с кодом не так-то?

**Comment by EvilBeaver** [comment]
Все так, все в рамках синтаксиса, и баги ты находишь, прямо скажем, отлично. Тут талант налицо!
