### ISSUE TITLE
Странная ошибка выполнения, исчезающая после мельчайшей перестановки кода

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#579]
Есть ишуз https://github.com/artbear/1bdd/issues/124
```
ОШИБКА   - {Модуль C:\OneScript\lib\1bdd\src\bdd-generate.os / 
Ошибка в строке: 45 / Значение не является значением объектного типа}
```

Например, проблема на коммите https://github.com/artbear/1bdd/commit/0eda95148bc1438d1fc8b110b4089f4e072900eb

Проблема в строке 
```bsl
РезМассивФайлов.Добавить(СоздатьФайлРеализацииШагов(ФайлФичи, НаборБиблиотечныхШагов));
```
Если ее разделить на 2 строки
```bsl
ФайлРеализации = СоздатьФайлРеализацииШагов(ФайлФичи, НаборБиблиотечныхШагов);
РезМассивФайлов.Добавить(ФайлРеализации);
```
то проблема исчезает.

Похоже, что-то с  движком :(
У меня 1скрипт 1.0.19.92

**Comment by EvilBeaver** [comment]
А ошибка-то какая? И просой пример запуска, если можно?

**Comment by artbear** [comment]
В упомянутом ишузе все написано про ошибку, я не стал дублировать.

Пример запуска `1bdd gen ЛюбаяФича` или `1testrunner -runall tests` в каталоге 1bdd

**Comment by artbear** [comment]
В ветке девелоп 1bdd я уже исправил, поэтому, если что, использовать коммит выше из описания ишуза.
На 18 и 19 релизах баг повторяется.

**Comment by artbear** [comment]
Выложил ошибку в описание текущего ишуза, вам будет проще

**Comment by EvilBeaver** [comment]
@artbear то есть, я должен взять 1bdd из коммита 0eda95148bc143, зайти в каталог 1bdd и запустить в нем ```1testrunner -runall tests```, верно?

**Comment by artbear** [comment]
@EvilBeaver Ну да.
или команда `1bdd gen ЛюбаяВыбраннаяТобойФича` для простоты

**Comment by EvilBeaver** [comment]
Полагаю, это дубликат от #577. Т.е. после исправления 577 эта также закроется. @artbear проверь, пожалуйста, как соберется сегодняшний билд.
