### ISSUE TITLE
Перехват всех сообщений, которые выдаются через штатный "Сообщить"

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#583]
Было бы полезным добавить возможность перехвата всех сообщений, которые выдаются через штатный "Сообщить".
Например, это полезно для доп.управления.

Полезные сценарии 
- выдаем красивый прогресс-бар. 
  + Новые сообщения в консоли не дают сделать красивый прогресс-бар, т.к. новые сообщения будут на новой строке
- скрытие ненужных подробностей от пользователя
- полное логирование абсолютно всех сообщений скрипта и всех используемых пакетов, а не только при использовании явных вызовов logos

API:
+ `Консоль.УстановитьКонтроллер(ОбъектСкрипта);`
+ обработчик внутри скрипта `ПриПоявленииСообщения(Знач Сообщение, Знач Статус, СтандартнаяОбработка)`

**Comment by dmpas** [comment]
> выдаем красивый прогресс-бар.

как?

> скрытие ненужных подробностей от пользователя

само слово "Сообщить" как бы намекает, что мы хотим поделиться этой важной информацией. Для всего технического должны использоваться логи.

> полное логирование абсолютно всех сообщений скрипта и всех используемых пакетов, а не только при использовании явных вызовов logos

зачем? и зачем тогда логос?..

**Comment by nixel2007** [comment]
@dmpas 

>> выдаем красивый прогресс-бар.

> как?

например библиотекой progbar

**Comment by dmpas** [comment]
@nixel2007 дай примерный код. Вот есть у тебя событие `ПриПоявленииСообщения(Знач Сообщение, Знач Маркер)`, вот как ты по нему полоску состояния сделаешь???

**Comment by artbear** [comment]
>> полное логирование абсолютно всех сообщений скрипта и всех используемых пакетов, а не только при использовании явных вызовов logos

>зачем? и зачем тогда логос?..

@dmpas Вот я же явно написал :( 
>полное логирование абсолютно всех сообщений скрипта и всех используемых пакетов, а не только при использовании явных вызовов logos

кто-то из используемых библиотек или приложений не юзает логос, например, или юзает частично (и Сообщить, и логос)

Сейчас чтобы получить полный лог для этих случае, нужно выполнять перенаправление вывода в файл `> file.txt`
А в этом случае интерактивного вывода нету :(

**Comment by Stepa86** [comment]
Для вывода в лоб - Сообщить, для вывода с переопределением и красивостями - логос. Я конечно использую Сообщить параллельно логосу чисто для раскрашивания текста, но это изза лени только. В общем не вижу смысла

**Comment by artbear** [comment]
Ребята, а подумать?

**Comment by dmpas** [comment]
я бы с бОльшим удовольствием запилил логи прямо в движок, а логос - уже надстройкой над этим.

**Comment by artbear** [comment]
Запилить в движок интересно, но сложно.
А логос уже есть.
И сделать универсальный обработчик полезно, пригодится для разных задач

**Comment by artbear** [comment]
В первую очередь, конечно, нужно полное логирование абсолютно всех сообщений скрипта и всех используемых пакетов, а не только при использовании явных вызовов logos

**Comment by dmpas** [comment]
Давай посмотрим в корень проблемы. Как мне кажется, он тут:
> кто-то из используемых библиотек или приложений не юзает логос, например, или юзает частично (и Сообщить, и логос)

почему народ использует Сообщить вместо логос??? Потому что логос надо (а) подключить, (б) создать, (в) в глобальную переменную сунуть в каждом модуле. А так фигак-фигаг Сообщить, ну типа на время, а потом уже "работает-не-трожь".

Если на уровне движка можно будет вместо `Сообщить("отладочное сообщение");` сразу писать `лог("Отладочное сообщение")`, было бы приятнее, мне кажется.

**Comment by Stepa86** [comment]
Сообщить в библиотеках не сказать что часто пользуют, чтоб это стало проблемой https://github.com/search?q=org%3Aoscript-library+%D0%A1%D0%BE%D0%BE%D0%B1%D1%89%D0%B8%D1%82%D1%8C%28&type=Code

**Comment by artbear** [comment]
Еще раз - если на уровне движка можно будет логи, это будет несомненно круто.
Но это
1 сложновато в согласовании/реализации
2 долговато в согласовании/реализации :)
3 и все равно без гарантии, что не будет юзаться Сообщить :(
  + т.е. ситуация после реализации ничем не будет отличаться от текущей!

3 можно обойтись простой и универсальной вставкой, когда вызывающий код-клиент сам будет решать, что и как делать

**Comment by artbear** [comment]
>Сообщить в библиотеках не сказать что часто пользуют, чтоб это стало проблемой https://github.com/search?q=org%3Aoscript-library+%D0%A1%D0%BE%D0%BE%D0%B1%D1%89%D0%B8%D1%82%D1%8C%28&type=Code

39 раз в РАЗНЫХ библиотеках - это разве не проблема??
я как раз об этом и говорю!

Нафига мне, вызывающему коду зависеть от выдачи сообщений?

я владелец консоли, нафига они (пакеты) кидают какие-то сообщения в МОЮ консоль :)

**Comment by EvilBeaver** [comment]
Ну раз уж меня призвали, я скажу, что Артур хочет странного, а зачем именно - не говорит.

**Comment by EvilBeaver** [comment]
Какую конкретную задачу ты решаешь и полагаешь решить с помощью этой функциональности?

**Comment by leemuar** [comment]
Интересное предложение. 
Но выглядит как обходное решение для проблемы плохого дизайна существующих скриптов/библиотек. Библиотеки должны использовать специализированные библиотеки/объекты для вывода (logos, например), а не использовать стандартное Сообщить() напрямую.

Предлагаю 

* предложенную подписку на событие не делать
* библиотеки отрефакторить (заменить Сообщить() на вызов библиотеки), 
* в справке к Сообщить() не рекомендовать ее для постоянного использования

Ну или как второй вариант - буферизировать весь вывод скрипта, при завершении скрипта буфер выводить в потоки вывода. Добавить функции работы с буфером вывода - получение содержимого, вывод содержимого буфера в потоки и т.п.

**Comment by pumbaEO** [comment]
Он хочет как в питоне
Процедура МояСообщитьПерехват(арг1, арг2)

КонецПроцедуры

Сообщить = МояСообщитьПерехват;

**Comment by artbear** [comment]
а я ведь уже писал в самом начале про сценарии использования


>Полезные сценарии 
> - выдаем красивый прогресс-бар. 
>    + Новые сообщения в консоли не дают сделать красивый прогресс-бар, т.к. новые сообщения будут на новой строке
> - скрытие ненужных подробностей от пользователя
> - полное логирование абсолютно всех сообщений скрипта и всех используемых пакетов, а не только при использовании явных вызовов logos

**Comment by leemuar** [comment]
Если в терминах 1С, то выглядит как подписка на событие с возможностью отключения стандартной обработки:

```
Процедура МойОбработчикСообщений(Сообщение, Тип, СтандартнаяОбработка)
    СтандартнаяОбработка = Ложь;
    // ...
КонецПроцедуры

ДобавитьОбработчик("Сообщение", "МойОбработчикСообщений");

// будет сгенерировано событие "Сообщить", вызовется зарегистрированный обработчик этого события  "МойОбработчикСообщений"
Сообщить("1");
```

**Comment by artbear** [comment]
Да, я забыл написать про СтандартнаяОбработка, конечно.

**Comment by artbear** [comment]
@EvilBeaver @dmpas Как мне решить прикладную задачу:
+ получить немедленный интерактивный вывод работы приложения-скрипта в консоли
+ и ОДНОВРЕМЕННО в то же время сохранить лог работы приложения в файле
?

Предложите вменяемый вариант

ЗЫ желательно и для Win и для Lin :)

**Comment by artbear** [comment]
За мое предложение уже 1 голос за :)

**Comment by artbear** [comment]
Точнее, за мое предложение, конечно.

**Comment by leemuar** [comment]
Немного обобщая проблему: может добавить в движок возможность подписок на события (аналог ДобавитьОбработчик в 1С) и сделать чтобы некоторые стандартные механизмы движка генерировали события? Это позволит решить https://github.com/EvilBeaver/OneScript/issues/555 и https://github.com/EvilBeaver/OneScript/issues/583 (этот ишуз)

**Comment by leemuar** [comment]
Предложил более общее решение: https://github.com/EvilBeaver/OneScript/issues/584

**Comment by EvilBeaver** [comment]
> получить немедленный интерактивный вывод работы приложения-скрипта в консоли

приложения-скрипта, запущенного через 1commands? Ну так же, как и сейчас, чтением потока. Предполагаю, что ты натолкнулся на сложности с этим. Расскажи про них тогда.

@leemuar в задаче #555 проблема в том, что ошибка неизвестного символа генерируется во время компиляции модуля. А обработчик должен работать во время выполнения, т.е. когда компиляция уже завершена. Получается проблема курицы и яйца.

**Comment by artbear** [comment]
@EvilBeaver Мне нужно запустить свой скрипт интерактивно
+ получить результаты и на экране и в файле для анализа

Предложите вариант

**Comment by artbear** [comment]
1коммандс пока сюда приплетать не нужно :)

**Comment by EvilBeaver** [comment]
@artbear если я правильно понял кейс, то это логос и два аппендера. На экран и в файл.

**Comment by nixel2007** [comment]
@EvilBeaver не совсем. В своих скриптах ты можешь контролировать вывод и переписать все через логос. А потом ты начинаешь использовать стороннюю библиотеку, автор которой упорно везде использует Сообщить, пулл-реквест с исправлением не принимает и вообще. Форкать и постоянно синхронизировать - вариант не очень

**Comment by kuntashov** [comment]
Как справедливо заметил @leemuar :

> выглядит как обходное решение для проблемы плохого дизайна существующих скриптов

Нужно рефакторить библиотеки. 

@nixel2007 
> автор которой упорно везде использует Сообщить, пулл-реквест с исправлением не принимает и вообще

Это гипотетически или есть реальный пример писателя на OS, чья нетленка ну вот прямо нереально  восстребована, но автор редиска, а вы сами сделать аналог не можете?

Имхо, из области фантастики. Все кто пишет на OS что-то стоящее, адекватные люди, и все друг друга знают :)

**Comment by kuntashov** [comment]
Ну и да, напишите простейший style guide с требованиями к библиотечным скриптам и правила проверки для сонара + бейджик для гитхаба в виде медальки Серебряной пули в качестве дополнительного стимула.

**Comment by EvilBeaver** [comment]
Иными словами, подписка на события - дело хорошее. Вопрос на какие события. Например, событие завершения работы - кажется неплохим вариантом, подчистить там за собой и все вот это вот. А перехват вызова Сообщить кажется вариантом плохим, поскольку Сообщить - это низкоуровневая функция, прямой вывод в stdout, аналог printf. Эту задачу если и надо решать (в чем сомневаюсь), то иначе, предоставляя инфраструктуру потоков ввода/вывода на уровне языка. Это можно сделать, но это совсем другая история, к теме issue отношения не сильно имеющая.

**Comment by artbear** [comment]
>@EvilBeaver не совсем. В своих скриптах ты можешь контролировать вывод и переписать все через логос. А потом ты начинаешь использовать стороннюю библиотеку, автор которой упорно везде использует Сообщить, пулл-реквест с исправлением не принимает и вообще. Форкать и постоянно синхронизировать - вариант не очень 

Дополню @nixel2007 
Форкать/дорабатывать/пулл-реквестить - это хорошо, когда есть время.

А когда нужно решить проблему здесь и сейчас, возникают трудности.

Я уже предлагал, подскажите, как мне решить прикладную проблему, возникающую здесь и сейчас.
Пока мне никто не предложил решения.

только и пишут, что "не согласен, не нужно, сомневаюсь, низя, вредно" и прочие гадости :)

**Comment by artbear** [comment]
"Здесь и сейчас" (или "Здесь в будущем") 
у меня на моей машине есть набор приложений и библиотек, в одной из которых используется Сообщить, а не Лог.???
Запускаю основное приложение и получаю вывод в консоль.

>@EvilBeaver Мне нужно запустить свой скрипт интерактивно
>+ получить результаты и на экране и в файле для анализа

>Предложите вариант
 
Вот зачем мне, как клиенту приложения, тратить время на разбор полетов и анализ ВСЕГО существующего кода (или дерева вызовов) для решения небольшой прикладной задачи?

PS вот задолбался уже повторять свой прикладной сценарий.
Почему все его пропускают? Доктор, почему?

**Comment by kuntashov** [comment]
> здесь и сейчаc

Такое решение ты знаешь, его в общем-то называли как "рефакторинг":  поиск и замена "Сообщить(" на "МояВерсияСообщить(". Это решение на несколько минут (сравни с доработкой движка).

Вот реально, даже если @EvilBeaver согласится сделать "подписку", то это, очевидно, не "здесь и сейчас".

**Comment by artbear** [comment]
@kuntashov Ты же понимаешь, что это костыльное решение? :(
А если потом наступит "здесь и в будущем", а прилетели новые версии со старым Сообщить или еще с чем?

ОФФ я вам говорю, приходите завтра, а вы все сегодня, да сегодня :(

**Comment by artbear** [comment]
Надеюсь, все понимают, что я не рассказываю про сценарий, который возник у меня неожиданно, в первый раз и больше никогда не повторится?
этот сценарий возникает частенько

**Comment by kuntashov** [comment]
Ну меня уговаривать в принципе не надо, ты меня позвал, я мнение сказал (я считаю как раз подписку на "сообщить" костылем).

Не костыль - рефакторить библиотеки и ради светлого будущего - делать гайд по стилю для библиотек, чтобы сеять доброе и вечное и уменьшать вероятность появления либ с Сообщить внутри.

По твоему же сценарию наше будущее будет заполонено библиотеками с Сообщить и с подписками на эти Сообщить в клиентском коде этих библиотек. Бррр.

**Comment by artbear** [comment]
Я согласен, что нужно рефакторить библиотеки, делать гайд и т.п.
Другого будущего не вижу.

(Дурная?) идея - на уровне движка запретить юзать все Сообщить, кроме, как внутри класса `ВыводЛогаВКонсоль` :)
или не рекомендовать с выводом сообщения в консоль

вот тогда законодательно все тут же перепишут на Лог :)

**Comment by leemuar** [comment]
Объявить Сообщить() deprecated, выдавать предупреждение при использовании если интерпретатор запущен с опр.ключом(например, -warnings=all), добавить новый объект для вывода в stdout

**Comment by dmpas** [comment]
"У нас пряником тоже бьют". Не надо запрещать, надо давать удобный инструмент, чтобы лучи радости исходили от разраба и ему хотелось влепить логи везде, где только рука дотянется.

PS :trollface: новая метрика рядом с покрытием тестами - покрытие логами

**Comment by artbear** [comment]
Мне как большому любителю логов очень нравится эта метрика :)

**Comment by EvilBeaver** [comment]
Закрываю. Пути решения обсуждены в #609
