### ISSUE TITLE
Стандартный механизм событий

### ISSUE THREAD

**Issue by leemuar** [EvilBeaver/OneScript#584]
Добавить в движок механизм событий, подписок на них. 
Добавить генерацию событий стандартным объектам. Ближайший аналог из 1С: ДобавитьОбработчик / УдалитьОбработчик

Решает https://github.com/EvilBeaver/OneScript/issues/555 и https://github.com/EvilBeaver/OneScript/issues/583

```
Процедура МояРеализацияСообщения(текстСообщения, ТипСообщения, СтандартнаяОбработка) Экспорт
    СтандартнаяОбработка = Ложь;
    // ...
КонецПроцедуры


Процедура МоеПодключениеТипов(ИмяТипа) Экспорт
     Если ФайлСуществует("./vendor/" + ИмяТипа + ".os") Тогда
          ПодключитьСценарий("./vendor/" + ИмяТипа + ".os", ИмяТипа);
     КонецЕсли;
КонецПроцедуры


// Стандартная функция Сообщить() генерирует событие "стд.вывод.сообщение"
ДобавитьОбработчик("стд.вывод.сообщение", "МояРеализацияСообщения", ЭтотОбъект);
Сообщить("1");

// попытка инициализировать неизвестный тип генерирует событие "стд.ядро.типы.НеизвестныйТип"
ДобавитьОбработчик("стд.ядро.типы.НеизвестныйТип", "МоеПодключениеТипов", ЭтотОбъект);
Нечто = Новый НеизвестныйТип;
```

**Comment by EvilBeaver** [comment]
Да, хорошая идея. Осталось решить вопрос с тем - какие именно это будут события :)

**Comment by nixel2007** [comment]
@EvilBeaver можно пойти радикально... Дать возможность переопределить любую функцию глоб контекста

**Comment by artbear** [comment]
Да, с переопределение глоб.функций будет круто и решит мою проблему.

Я так и в 1С++ в свое время делал - перехватывали любые контекст 1С 77

**Comment by leemuar** [comment]
Не надо Monkey Patching, пожалуйста :(

**Comment by nixel2007** [comment]
> Не надо Monkey Patching, пожалуйста :(

если переопределение, то да, это monkey patching. а если именно подписка на событие, то вроде бы не очень страшно. ну ладно, очень страшно, но не совсем.

**Comment by artbear** [comment]
В 1С++ все было красиво и удобно, народ активно пользовался этой фичей под название "Перехватчик"

**Comment by leemuar** [comment]
> Дать возможность переопределить любую функцию глоб контекста

Если будет механизм событий и движок будет генерировать событие на вызов всех стандартных функций - можно будет реализовать так:

```
Процедура МоеСообщение(Текст, Тип) Экспорт
    // ...
КонецПроцедуры

Процедура ПереопределениеСообщения(ИмяФункции, ПараметрыФункции, СтандартнаяОбработка)
    Если ИмяФункции = "сообщить" Тогда
        // стандартная обработка не будет выполняться
        СтандартнаяОбработка = Ложь;
        ВызватьФункцию("МоеСообщение", ПараметрыФункции);
    КонецЕсли;
КонецПроцедуры


// вызов любой функции генерирует событие "oscript.function.call", передавая имя вызываемой функции
ДобавитьОбработчик("oscript.function.call", ПереопределениеСообщения);
Сообщить("123");
```

**Comment by EvilBeaver** [comment]
Чуваки, ну смотреть на каждый вызов - нет ли там оверрайдов - это какое замедление байт-кода же! Оно вам чо, вот прямо точно надо?

**Comment by leemuar** [comment]
Не ну мы пока фантазируем, набрасываем идеи.
Наверно событие на каждый вызов функции - это совсем перебор. С другой стороны, даже если хочется такой функционал использовать за счет производительности - почему нет?

**Comment by dmpas** [comment]
> почему нет

@leemuar потому что получим тучу говнокода в библиотеках, а потом начнётся, что "односкрипт - тормознутый", а ускорить его не позволят три тонны существующего кода.

**Comment by EvilBeaver** [comment]
Итого, сформулируем суть задачи: сделать ДобавитьОбработчик / УдалитьОбработчик, придумать какие именно события суть полезные, а какие - зело вредные.

**Comment by leemuar** [comment]
@EvilBeaver + еще какую-нибудь функцию для генерации событий в скриптах, а-ля fireEvent()

**Comment by nixel2007** [comment]
да давайте уж `EventEmitter.on("myEvent", () => console.log("here is my event!"))` и `EventEmitter.emit("myEvent");` :trollface:

**Comment by dvakor** [comment]
Еще одна идея, не факт что хорошая :)
Взять идею расширений и внедрить 3 предопределенных аннотации

&Вместо("Сообщить")
&Перед("МойКласс.МояФункция")
&После("ОбщийМодуль.Чтото")

Но это порождает один фиг проблему 

> Чуваки, ну смотреть на каждый вызов - нет ли там оверрайдов - это какое замедление байт-кода же! Оно вам чо, вот прямо точно надо?

Так же для каких то событий сделать предопределенные идентификаторы

```
&Вместо("ОбработкаПолученияОбъекта")
Функция ОбработкаПолученияОбъектаВместо(ИмяТипа, ПараметрыКонструктора)
      Если ИмяТипа= "хз" Тогда
             Возврат Новый Враппер(ПараметрыКонструктора);
      Иначе
              ПродолжитьВызов(ИмяТипа, ПараметрыКонструктора);
      КонецЕсли;
КонецФункции
```

```
&Вместо("ОбработкаВызоваИсключения")
Функция ХендлерИсключений(ИнформацияОбОшибке)
      //Что-то делаем
      Возврат Неопределено; //Ловим исключение движка, о то, что надо возрвщать ИнформацияОбОшибке
КонецФункции
```

**Comment by EvilBeaver** [comment]
Ой не, вот эти вместо это беда какая-то. Лучше уж нормальное наследование ввести, но ООП не нужно, если есть функции первого порядка, а ишуз на лямбды у нас уже где-то был.

**Comment by nixel2007** [comment]
@EvilBeaver держи https://github.com/EvilBeaver/OneScript/issues/422

P.S. Забавно, что обсуждение в итоге выродилось в библиотеку fluent.

**Comment by EvilBeaver** [comment]
Реализована поддержка ДобавитьОбработчик / УдалитьОбработчик
