### ISSUE TITLE
Ошибка при запуске gitsinc "гитрепозиторий.os" . Сразу после установки

### ISSUE THREAD

**Issue by YLioY** [EvilBeaver/OneScript#585]
Пробовал установить gitsync как по инструкции , перед этим пользовался "oscript" , скачал через сайт. 

C:\WINDOWS\system32>opm install gitsync
ИНФОРМАЦИЯ - Скачиваю файл: gitsync.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет gitsync
ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
ИНФОРМАЦИЯ - logos уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: cmdline
ИНФОРМАЦИЯ - cmdline уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: tempfiles
ИНФОРМАЦИЯ - tempfiles уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: tool1cd
ИНФОРМАЦИЯ - tool1cd уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: v8runner
ИНФОРМАЦИЯ - v8runner уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: gitrunner
ИНФОРМАЦИЯ - gitrunner уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: strings
ИНФОРМАЦИЯ - strings уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: 1commands
ИНФОРМАЦИЯ - 1commands уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: v8unpack
ИНФОРМАЦИЯ - v8unpack уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Регистрация приложения: gitsync
ИНФОРМАЦИЯ - Установка завершена

C:\WINDOWS\system32>gitsync
{Модуль C:\Program Files (x86)\OneScript\lib\gitrunner\src\ГитРепозиторий.os / Ошибка в строке: 0 / Невозможно загрузить модуль РежимУстановкиНастроекGit. Такой символ уже определен.}

C:\WINDOWS\system32>

// Пробовал запустить это через "oscript "
PS C:\Program Files (x86)\OneScript\lib\gitrunner\src> oscript гитрепозиторий.os
{Модуль C:\Program Files (x86)\OneScript\lib\gitrunner\src\гитрепозиторий.os / Ошибка в строке: 1014 / Внешнее исключение (System.IO.DirectoryNotFoundException): Не удалось найти часть пу
ти "C:\Program Files (x86)\OneScript\lib\gitrunner\src\src\Классы\НастройкаРежимаОтправкиGit.os".}

// Возможно это причина ошибки 
"\src\src\Классы" - это путь сообщения об ошибке
C:\Program Files (x86)\OneScript\lib\gitrunner\src\Классы - это мой путь

Первый раз пишу через git .Я не знаю как получить ответ. Мне самому нужно найти и исправить ошибку , так как такая у меня одного или просто переустановить onescript  ?

**Comment by nixel2007** [comment]
Скорее всего в гитсинке неверная зависимость от gitrunner. Попробуйте обновить через opm install gitrunner

**Comment by EvilBeaver** [comment]
В админской командной строке наберите opm install gitrunner

**Comment by YLioY** [comment]
Спасибо работает. Если можно еще вопрос. Пошел дальше , начал работать с "gitsync" .  Не уверен или я сделал все в правильном порядке .
1) gitsync init - все ок
2) gitsync set-version 1  - все ок 
3) Руками изменил логин и имейл в файле "AUTHORS" 
4) Запустил gitsync  export  . В папке с гит все появилось , но в конце появилась ошибка

gitsync export "D:\1CRepositories\UT23" "D:\1с files\GitRepo\UT23Repository"
GitSync v2.3.0
ИНФОРМАЦИЯ - Начинаю выгрузку исходников
ИНФОРМАЦИЯ - Начало синхронизации с git
ИНФОРМАЦИЯ - Номер синхронизированной версии: 1
ИНФОРМАЦИЯ - Номер последней версии в хранилище: 2
ИНФОРМАЦИЯ - Получаем исходники для версии 2, 21.11.2017 16:18:57
WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated, use 'GetEnvironmentVariable' from global context
WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated, use 'GetEnvironmentVariable' from global context
WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated, use 'GetEnvironmentVariable' from global context
WARNING! Deprecated method: 'SystemInfo.GetEnvironmentVariable' is deprecated, use 'GetEnvironmentVariable' from global context
ИНФОРМАЦИЯ - Раскладываем модули по папкам согласно иерархии метаданных
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\gitrunner\src\ГитРепозиторий.os / Ошибка в строке: 823 / Метод объекта не обнаружен (ДобавитьПараметры)}

Пробовал выполнить " opm install gitrunner" , но ошибка осталась.

И еще вопрос :
1)  Если в двух словах, можно сделать обмен изменениями цф между серверами через гит без выгрузки всей цф в файлах на внешний гит ?

**Comment by nixel2007** [comment]
> Метод объекта не обнаружен (ДобавитьПараметры)}

opm install 1commands

P.S. Добавляющих зависимости активно разрабытываемых библиотек без указания версий я скоро буду сжигать на костре

**Comment by artbear** [comment]
Давайте хотя бы ишузы вывешивать на такие репозитории?

**Comment by YLioY** [comment]
все ок спасибо. Я так понял , если появляется ошибка для начала нужно выполнить "opm install -all" или "opm update -all"?

**Comment by nixel2007** [comment]
@YLioY opm install -all можно не выполнять - он устанавливает вообще все библиотеки с хаба. обычно хватает opm update -all
