### ISSUE TITLE
Макеты

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#588]
Набросок:

 * В контекст загрузчика библиотеки (`package-loader.os`) добавляем метод `ПолучитьМакет()`.
 * DLL/EXE/прочие бинари складываем в `src/Макеты` (`bin/Макеты`, `res/Макеты`), или прописываем в `lib.config`
 * При упаковке EXE-файла все найденные макеты упаковываются внутрь ЕХЕ-файла
 * При вызове ПолучитьМакет по имени ресурса (регистро-независимом ? ) получаем:
   - в случае ЕХЕ-файла - двоичные данные из ресурса ЕХЕ-файла
   - в случае скриптов на диске - двоичные данные из файла на диске

Обсуждаем, дополняем частности.

**Comment by artbear** [comment]
Мне кажется, все что нужно, уже обсудили.
Прекрасно описано.

**Comment by EvilBeaver** [comment]
Из частностей - получение не только дв. данных, но и сразу путей. А то для неупакованых скриптов существенное неудобство получается.

**Comment by dmpas** [comment]
Любой неупакованный скрипт неожиданно может стать упакованным. Разрботчик библиотеки же не знает, придёт ли кому в голову упаковывать её.

**Comment by EvilBeaver** [comment]
Совершенно верно. Но и каждый раз работать с дв. данными неудобно, все знают. Поэтому, на "подумать", пусть эта деталь тоже будет.

**Comment by khorevaa** [comment]
Как идея  сделать библиотеку аналогичную https://github.com/jteeuwen/go-bindata

**Comment by EvilBeaver** [comment]
# Задачка

* добавить в загрузчик метод ДобавитьМакет, наравне с ДобавитьКласс и ДобавитьМодуль
* регистрировать макеты в движке по неймспейсам, если не получится, то глобально
* реализовать ПолучитьМакет. Возможно, имя макета нужно будет задавать в виде ``ПолучитьМакет("/packagename/templateName")`` для неймспейсинга или автоматически резолвить (не знаю как)
* реализовать упаковку макетов при процедуре make
* реализовать загрузку макетов в standalone режиме
* реализовать загрузку макетов в обычном режиме

**Comment by khorevaa** [comment]
Жду с нетерпением...
