### ISSUE TITLE
Автоматическая сборка мусора

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#593]
Есть замысел "О Великом Костыле". Чтобы не думать об освобождении управляемых ресурсов и добавить чуть больше совместимости поведения с 1С, предлагаю вкостылить следующее:

 * Если внутри метода создавались `IDisposable`-объекты, то ставим себе какой-нибудь флажок.
 * При выходе из метода после очистки скопа переменных, если сей флажок отмечен, запускаем сборку мусора.

Таким образом, если `IDisposable`-объект больше нигде не используется, он будет закрыт. Если таких объектов создано не было, то сборка не вызовется и провес производительности будет минимален.

Такое сработает только с методами, потому что есть чёткие рамки существования скопа. В циклах так не получится.

**Comment by EvilBeaver** [comment]
Угу, а если мы передали его в какой-то метод, а там он взял и сохранился в какую-то переменную
А потом херак и задиспозился

**Comment by dmpas** [comment]
> а там он взял и сохранился в какую-то переменную

так не задиспозится же. Если есть ссылки на него, сборщик его не будет потрошить.

**Comment by EvilBeaver** [comment]
Выглядит как костыль. Может лучше все-таки AddRef и Release в IValue добавим?

**Comment by EvilBeaver** [comment]
@artbear знал нормальный алгоритм плюсования и вычитания ссылок

**Comment by dmpas** [comment]
> Выглядит как костыль

оно, собственно, прямо так и названо.

> Может лучше все-таки AddRef и Release в IValue добавим?

просто как ни начну читать, почему в C# нет счётчика ссылок, так и увеличивается желание не делать их. И AddRef и Release для ЛЮБЫХ IValue выглядит как ещё бОльший костыль, если честно.

**Comment by artbear** [comment]
>@artbear знал 

@EvilBeaver Как ты меня, а?

**Comment by artbear** [comment]
Для IValue как раз счетчик ссылок приложится.
То самое мое ИМХО :)

**Comment by EvilBeaver** [comment]
> AddRef и Release для ЛЮБЫХ IValue выглядит как ещё бОльший костыль

А мне кажется, наоборот, гламурненько. Чистый ~~амфетамин~~ полиморфизм. Объект или щелкает свои внутренние ссылки, или не щелкает - сам решает.

**Comment by EvilBeaver** [comment]
Там и надо-то в 2 местах.

    А = ЧтоТоТам(); // А.Relesase();A.Assign();A.AddRef()

и в передаче параметра в метод

**Comment by artbear** [comment]
@EvilBeaver +1

**Comment by artbear** [comment]
Ну и `ЧтоТоТам().Release()` :)

**Comment by artbear** [comment]
>EvilBeaver deleted a comment from artbear a minute ago

@EvilBeaver читерством балуешься? :)

**Comment by EvilBeaver** [comment]
@artbear то был флуд вида +1. Для этого уже есть кнопка такая.

> Ну и ЧтоТоТам().Release() :)

ЧтоТоТам не освобождается. Он же остается жить.

**Comment by artbear** [comment]
Вот ты сейчас чего, путаешь ведь :(
ЧтоТоТам() это функция :) и результат ее значения удаляется сразу же после выхода из выражения равенства.
Иначе кирдык твоему подсчету ссылок.

**Comment by artbear** [comment]
А внутри функции перед выходом из нее делается `Результат.AddRef`

**Comment by artbear** [comment]
о как, я еще **знаю**/помню `нормальный алгоритм плюсования и вычитания ссылок`

**Comment by dmpas** [comment]
> Там и надо-то в 2 местах.

ой, помню, возюкался я с этими счётчиками в своём говно-движке на Сишечке... ой, не два там места... ой, а как КОМ-объекты появятся, так совсем страх начнётся.

**Comment by dmpas** [comment]
https://github.com/dmpas/e8engine/search?utf8=%E2%9C%93&q=e8_gc_use_object&type=

так навскидочку

**Comment by dmpas** [comment]
>Объект или щелкает свои внутренние ссылки, или не щелкает - сам решает.

но ты же всё равно будешь вызывать AddRef и Release у КАЖДОГО объекта.

**Comment by dmpas** [comment]
И эти аддреф и релиз придётся делать САМОСТОЯТЕЛЬНО разработчикам компонент. Таки в топку управляемый код при таком геморре.

**Comment by EvilBeaver** [comment]
@dmpas я может чего не догоняю, и не постиг, поэтому и возражать пытаюсь, ты уж потерпи, ладно? Мне казалось, что нужно реализовать Release для переменной в которую идет присваивание (т.к. старое значение уничтожается) и AddRef для значения, которое присваивается (т.к. его теперь используют). Ну и понятно - при уничтожении кадра callstack всем локальным переменным надо сделать Release.

> И эти аддреф и релиз придётся делать САМОСТОЯТЕЛЬНО разработчикам компонент

разве? Если они наследуются от ContextIValueImpl, то там уже будет правильная реализация и ничего делать не надо.

Получается, вроде как по книжкам: вызов полиморфного метода, а внутри каждый класс сам решает считать ему ссылки или еще чего делать (например, ничего). Вроде бы не страшно. Но не отпускает неизведанный ужос от того, что я недопонял риски.

**Comment by EvilBeaver** [comment]
Т.е. AddRef и Release нужно делать в опкодах, и ни в коем случае не внутри компонентных классов. Иначе, действительно, задница получается.

Да... задачка получается чуть шире, но нам не нужен строгий подсчет ссылок, по идее. Сборщик же на подхвате. Если мы делаем ValueTable.Delete(); а разработчик ValueTable не сделал Release для всех колонок удаляемой записи - то утечки все равно не будет. Хотя это и будет явный баг.

Но в данном кейсе - и предлагаемый тобой в первом посте способ - тоже не сработает. Короче, мне и без этого хорошо, осталось убедить @artbear чтобы он сделал подсчет ссылок самостоятельно и прислал PR. И в случае чего, мы всегда сможем свалить на него :trollface:

**Comment by dmpas** [comment]
> утечки все равно не будет

У нас проблема не в утечках, а в излишнем удержании ресурса. Утечек не будет в принципе (в том объёме, в котором с этим борется CLR).

То есть, если разработчик ValueTable не сделал Release, но если там был IDisposable-ресурс, то он будет держаться, не освободиться. Соответственно, цели не достигли.

**Comment by EvilBeaver** [comment]
Мне все равно не хочется решать проблему принудительным вызовом GC на каждом методе...

**Comment by dmpas** [comment]
Тогда хотя бы согласись, что подсчёт ссылок больше добавит проблем, чем решит.

**Comment by EvilBeaver** [comment]
> Тогда хотя бы согласись, что подсчёт ссылок больше добавит проблем, чем решит.

Я соглашусь, что он не решит. Вернее, решит, но более трудоемко, чем я думал. А вот насчет добавит - хз. Кажется, что наравне с частым GC.

**Comment by dmpas** [comment]
В топку.
