### ISSUE TITLE
Получение информации рефлектором из типа объекта

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#594]
Сейчас рефлектор умеет работать только с объектами как таковыми. Т.е. для получения данных рефлектора из объекта, нужно вызвать его конструктор (Новый HTTPСоединение()). Часть объектов не имеет конструкторов (HTTPОтвет), соответственно рефлектором данные такого объекта можно получить только *каким-то* образом создав этот объект, вызвав метод реального HTTPСоединения.

Хочется что-то вроде Рефлектор.ПолучитьТаблицуСвойствИзТипа(Тип("HTTPОтвет")), которая вернет тоже самое, что и Рефлектор.ПолучитьТаблицуСвойств(РеальныйHTTPОтвет);

**Comment by artbear** [comment]
А зачем дублировать методы?
предлагаю вставить работу с Типом в существующие методы.

Надеюсь, никому не придеть в голову "рефлекторить" работу с самим объектом Тип :)

**Comment by nixel2007** [comment]
> Надеюсь, никому не придеть в голову "рефлекторить" работу с самим объектом Тип :)

вот именно поэтому и отдельный метод/флаг

**Comment by EvilBeaver** [comment]
> Надеюсь, никому не придеть в голову "рефлекторить" работу с самим объектом Тип

Тип "Тип" - это тоже тип. Его тоже можно рефлектить. Но это то же самое, что рефлектить Число и Строку.

**Comment by EvilBeaver** [comment]
Хм... получается не очень красиво для объектов и для типов - разное API. Понятно почему так, но некрасиво. Может подумаем, как сделать иначе?

**Comment by nixel2007** [comment]
Рефлексия примитивных типов падает с исключением. не знаю, правильно это или нет. "Тип" - тоже примитивный тип, то есть он тоже будет падать.

из этого следует, что можно оставить старое апи, но просто дописать в доку, что при передаче в рефлектор типа "Тип" будет анализироваться выведенное из типа значение

**Comment by EvilBeaver** [comment]
@nixel2007 да, вполне рабочий вариант. Поскольку рефлексия простых типов не имеет физического смысла, то такое решение будет работать.

Своя версия: Первый параметр "Цель" рефлектора (тот где сейчас передаем объект) сделать имеющим тип "Тип". И именно этот вариант API считать основным. Но в качестве синтаксического сахара разрешить передавать туда объект, как будто движок, ради удобства, сам сделает этому объекту GetType и дальше будет работать по основному варианту.

Тогда, если передан не тип и не объект, то это нарушение API. И тогда, вполне можно отрефлексировать тип "Тип" и тип "Число". Вот так:

    Рефлектор.ПолучитьСвойства(Тип("Тип"));
    Рефлектор.ПолучитьСвойства(Тип("Число"));

**Comment by EvilBeaver** [comment]
Oops... а произвольные типы-то просто так не рефлексируются... писать надо...

**Comment by nixel2007** [comment]
@EvilBeaver что такое произвольные типы?

**Comment by EvilBeaver** [comment]
@nixel2007 тебе должно понравиться: 

https://github.com/EvilBeaver/OneScript/blob/acb5aeb6625ca289496964f69145e86ec2ea1b64/tests/reflector.os#L354-L360

Тест проходит.

"Произвольные типы" - это типы, которые встроены в движок, а не скомпилированы из скрипта. Но с небольшим добавлением магии, они тоже рефлексируются.

**Comment by nixel2007** [comment]
@EvilBeaver Выглядит здорово!

**Comment by nixel2007** [comment]
А можно так же для ПолучитьТаблицуСвойств и ПолучитьТаблицуМетодов?

**Comment by EvilBeaver** [comment]
Конечно. Это же только первый коммит "на попробовать".

**Comment by leemuar** [comment]
> Рефлектор.МетодСуществует(Тип("HTTPОтвет"), "ПолучитьТелоКакСтроку");

С другой стороны выглядит странно, потому что у типов нет методов. ```Тип("HTTPОтвет").ПолучитьТелоКакСтроку()``` не будет работать

Может сделать отдельный метод для получения списка методов из типов?

**Comment by EvilBeaver** [comment]
@leemuar почему странно? Метод у "Типа" существует или нет - проверить можно.

**Comment by leemuar** [comment]
@EvilBeaver странно, потому что перегруженная функция уже имеет не прозрачное наименование, делает не совсем то что декларирует своим именем в зависимости от типа параметра. Такая реализация прямо противоречит первому принципу SOLID.

С практической точки зрения я видел код, который выглядит примерно так:

```
Если Рефлектор.МетодСуществует(Объект, Метод) Тогда
    Рефлектор.ВызватьМетод(Объект, Метод);
КонецЕсли;
```

Он сломается с такой реализацией МетодСуществует(), если в качестве объекта передать объект типа "Тип"

В других языках рефлекторы явно разделены по типам - есть отдельный рефлектор для объектов, есть рефлектор для классов (типов). Примеры: 

* http://php.net/manual/en/class.reflectionobject.php
* http://php.net/manual/en/class.reflectionclass.php

В теории если у объекта типа "Тип" потом появятся свои методы - будет невозможно отделить методы объекта от методов объектов этого типа.

**Comment by leemuar** [comment]
Можно дальше пофантазировать. Если получить список методов от объекта типа "Тип" - что должно быть возвращено? Пустой список (т.к. объект типа "Тип" не имеет собственных методов) или список методов объекта с этим типом?

```
Методы = рефлектор.ПолучитьТаблицуМетодов(Тип("Рефлектор"))
// Методы.Количество() = 0
```

Путанница получается. имхо было бы здорово "специализировать" рефлектор: иметь отдельные рефлекторы для разных типов данных, что в коде в явном виде указывать намерения разработчика: "хочу методы типа (класса)", "хочу методы именно экземпляра объекта"

**Comment by dmpas** [comment]
>  Такая реализация прямо противоречит первому принципу SOLID.

@leemuar можешь в качестве ликбеза раскрыть, в чём именно противоречие (S) в данном случае?

**Comment by leemuar** [comment]
@dmpas 
имхо Рефлектор.МетодСуществует() до этого изменения имел одну четкую ответственность - ответить на вопрос, имеет ли переданный объект **собственный** метод с указанным именем

После перегрузки метода у него добавилось второе поведение, зависящее от типа первого параметра. Которое отвечает уже на совсем другой вопрос - имеет ли объект указанного типа метод с указанным именем. 

Метод начал выполнять разные действия в зависимости от типа первого параметра. Метод умеет слишком много, уже 2 разных поведения, 2 разных ответственности, поэтому я написал по S в SOLID.

На практике увидев такую строчку:

```
Рефлектор.МетодСуществует(Об, "бла")
```

я не буду понимать что именно здесь имел в виду разработчик: хотел он получить методы самого объекта или типа (класса)? Поведение неочевидное, нужно искать доп информацию о типе переменной Об, чтобы что-то понять.

Если было бы написано так:
```
РефлекторТипов.МетодСуществует(Об, "бла");
РефлекторОбъекта.МетодСуществует(Об, "бла")
```
никаких неоднозначностей нет, очевидно что хотел сделать разработчик.

**Comment by nixel2007** [comment]
у объекта Тип в 1с никогда не появится методов просто потому, что Тип в 1С - это примитивный тип (простите за каламбур)

**Comment by dmpas** [comment]
@leemuar в терминах "понятно/непонятно" и "очевидно/неочевидно", я всё это понимаю. Я не понимаю противоречия именно в терминах SOLID.
В частности, https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8#%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5

**Comment by artbear** [comment]
У разработчика 1С не появится вопросов, потому что Рефлектор работает с любыми объектами, а Тип - это не объект :)

**Comment by leemuar** [comment]
Вот что пишут в английской вики на эту тему:

> Martin defines a responsibility as a reason to change, and concludes that a class or module should have one, and only one, reason to be changed (i.e. rewritten). As an example, consider a module that compiles and prints a report. Imagine such a module can be changed for two reasons. First, the content of the report could change. Second, the format of the report could change. These two things change for very different causes; one substantive, and one cosmetic. The single responsibility principle says that these two aspects of the problem are really two separate responsibilities, and should therefore be in separate classes or modules. It would be a bad design to couple two things that change for different reasons at different times.
> 
> The reason it is important to keep a class focused on a single concern is that it makes the class more robust. Continuing with the foregoing example, if there is a change to the report compilation process, there is greater danger that the printing code will break if it is part of the same class.

По аналогии с классом, который формирует отчет и печатает его (2 ответственности), МетодСуществует тоже имеет теперь 2 ответственности. Или, говоря другими словами, две причины для изменения:
* когда нужно будет изменить алгоритм получения метода у экземпляра объекта
* когда нужно будет изменить алгоритм получения метода  у объектов, имеющих указанный в параметре тип

**Comment by artbear** [comment]
У нас нет 2х ответственностей, потому что Тип это не объект!
Если захочешь ввести, сделай ПР на добавление метода РефлекторТипа.
Но его вряд ли примут :)

**Comment by leemuar** [comment]
Не важно объект Тип или нет, ответственностей стало 2.
Да я уже давно понял всю безнадегу :)

**Comment by nixel2007** [comment]
емнип SRP вообще не применяется на уровне модулей. это принцип проектирования классов. но это так, оффтопик

**Comment by leemuar** [comment]
Да, конечно. Речь-то про объект Рефлектор. Поэтому я и привел пример с разделением на два класса рефлектора. Но те же принципы легко применяются и к методам (god method, например). 

> Но его вряд ли примут :)
> Да я уже давно понял всю безнадегу :)

Тоже в порядке оффтопа, потому что уже ничего не поменяется.
Сейчас Никита заложится на это поведение - и все, "не меняем, потому что breaking change для существующих библиотек"

**Comment by EvilBeaver** [comment]
Я согласен с @leemuar и понимаю его претензии. Смотрите сами, есть тип "Сценарий", создаваемый через ЗагрузитьСценарий. Данный тип будет иметь экспортные методы, которые "через объект" будут рефлексироваться, а "через тип" - нет. Потому что "Сценарий" - это динамический тип, его члены зависят от скрипта, который он представляет.

Но есть и светлая (назовем ее так :trollface: ) сторона этой ситуации. Дело в том, что "через тип" могут рефлектится только наследники от AutoContext<>, в силу особенностей реализации "рефлектора типов". Поэтому попытка передать туда тип "Сценарий" приведет к исключению.

**Comment by dmpas** [comment]
ааа! Даёшь ещё больше взрыва мозга и неочевидного поведения!!!

**Comment by EvilBeaver** [comment]
@leemuar безнадеги нет, и как раз, спасибо тебе, что обращаешь общее внимание на такие вещи.

Строго говоря, нарушения "Single Responsibility" здесь нет, т.к. рефлектор делает одно и то же. Здесь обычная перегрузка методов и разное поведение в зависимости от переданного типа.

Если объяснишь для тупых на пальцах, где здесь 2 ответственности - буду благодарен. Я без троллинга, действительно хочется сделать непротиворечивый API.
