### ISSUE TITLE
Ошибка при выполнении операции "Переместить файл"

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#599]
При вызове функции "ПереместитьФайл" Возникает следующая ошибка
```
Внешнее исключение (System.IO.IOException): Win32 IO returned ERROR_ALREADY_EXISTS. Path: }
```
Контекст: 
Версия движка
1Script Execution Engine. Version 1.0.18.35
```
Файл1 = "/mnt/4726E0D171584E1C/test_gitsync/test-gitsync/src/DataProcessors/ГрупповаяОбработкаСправочниковИДокументов/Forms/ФормаНастройки/Ext/Form/module"
Файл2  = "/mnt/4726E0D171584E1C/test_gitsync/test-gitsync/src/DataProcessors/ГрупповаяОбработкаСправочниковИДокументов/Forms/ФормаНастройки/Ext/Form/Module.bsl"
ПереместитьФайл(Файл1, Файл2);
```

Что не так? что делать? 
@EvilBeaver @artbear @dmpas 

п.с. 
Замена кода на две операции 
КопироватьФайл
УдалитьФайлы 

Решила проблему

**Comment by dmpas** [comment]
`/mnt/4726E0D171584E1C` - а там что подключено?

**Comment by khorevaa** [comment]
@dmpas Да внешний жёсткий диск

**Comment by EvilBeaver** [comment]
У меня диссонанс между путями вида /mnt/ и текстом ошибки "Win32 IO"

Это же линукс и моно? А какой именно моно по версии?

**Comment by pumbaEO** [comment]
А разве перемещение в 1С перезаписывает существующий файл или каталог?

**Comment by khorevaa** [comment]
@EvilBeaver  Вот вывод версии
```
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

```

**Comment by EvilBeaver** [comment]
Попробуй на 5-й моно. У меня были случаи исправления всяких странных глюков с помощью обновления моно. И, кстати, вопрос @pumbaEO тоже актуален.

**Comment by AlexMasljukov** [comment]
При вызове функции ПереместитьФайл(ПапкаСФайлами, ДругоеИмяПапкиСТемижеФайлами) ошибка:
Внешнее исключение (System.IO.FileNotFoundException): Файл 'D:\.....\.....' не найден.} (здесь полный путь существующей папки ПапкаСФайлами). Хотя папка по указанному пути существует и определяется командой НайтиФайлы().

Т.е., ошибка возникает при попытке переименования папки с файлами. Хотя в СП описание данной процедуры гласит:
Выполняет перемещение (переименование) указанного файла (папка же тоже файл, я так понимаю).

**Comment by Mr-Rm** [comment]
Нет, в 1С переименование каталогов тоже не работает.
```bsl
ИмяКаталога = "C:\Temp\Dir1";
КаталогНаДиске = Новый Файл(ИмяКаталога);
Если КаталогНаДиске.Существует() Тогда
	Сообщить("Каталог существует");
	ПереместитьФайл(ИмяКаталога, ИмяКаталога+"2");
КонецЕсли
```
получаем:
_Каталог существует_
и далее:
_Ошибка при вызове метода контекста (ПереместитьФайл)
по причине:
Ошибка переименования файлов
по причине:
Неправильный путь к файлу 'C:\Temp\Dir1'. Объект является каталогом_
