### ISSUE TITLE
Ошибка отладки под Убунтой: Duplex mode is expected to be 2

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#602]
Воспроизводится, если установлена хотя бы одна точка останова. Без точек останова запуск и выполнение отладчика проходят без проблем.

**Comment by EvilBeaver** [comment]
А понять в чем дело удалось?

**Comment by dmpas** [comment]
Пока нет. Иду наощупь, методом проб, ошибок, отключения/подключения фич.

**Comment by EvilBeaver** [comment]
Может сразу WCF выпилить нахер и доделать REPL-style отладчик? (Начало положено в ветке feature/debugger)

**Comment by dmpas** [comment]
выпилить WCF мне нравится. Но причём тут REPL и как он спасёт нас?

**Comment by EvilBeaver** [comment]
Там не совсем repl. Там цикл "выполни команду отладчика из консоли и жди следующую" И уже даже работает одна из них.

**Comment by kuntashov** [comment]
Пока не исправлено?

**Comment by dmpas** [comment]
нет :(

**Comment by kuntashov** [comment]
Поиск по исходникам обнаруживает единственное место с сообщением об ошибке "Duplex mode is expected to be": https://github.com/mono/mono/blob/79d96a5a8dbcbed6242c703f18b3becc36abf863/mcs/class/System.ServiceModel/System.ServiceModel.Channels.NetTcp/TcpBinaryFrameManager.cs#L273

Это поможет понять, где ошибка возникла?
Сам браться пока не берусь, т.к. порог вхождения для нуба в C# и инструментах отладки высоковат.

**Comment by kuntashov** [comment]
> -- Доктор, почему меня все игнорируют?
> -- Следующий!

@allustin ты в том самом эпическом треде на партнерском форуме написал, что ежедневно пользуешься отладчиком под linux. Ты без точек останова это делаешь или я не знаю про какую-то волшебную сборку, в которой все работает?

@EvilBeaver конкретно по этой проблеме есть план решать ее?

**Comment by EvilBeaver** [comment]
@kuntashov план есть и очень актуальный. Задача одна из приоритетных. Но времени не хватает. Там много переделывать очень

**Comment by kuntashov** [comment]
@EvilBeaver спасибо, очень жду!

**Comment by khorevaa** [comment]
@EvilBeaver  В последнем ночнике так и не работает отладка...

**Comment by EvilBeaver** [comment]
@khorevaa сам отладчик тоже надо ставить из ночника.
И если не работает - то как именно не работает?

**Comment by khorevaa** [comment]
@EvilBeaver  Жму F5 Выдает `Процесс адаптера отладки неожиданно завершился`
Где логи лежат? 
Все установлено из последнего ночника

**Comment by khorevaa** [comment]
Нашел багу.. При сборке пакета не правильный путь к исполняемому файлу.
[тут жесткий путь](https://github.com/EvilBeaver/OneScript/blob/57e7abb2a9def8390742b1d029a0945dc1eb3ffb/src/DebugServer/package.json#L38)
Прописвал вместо этой строчки `"program": "./bin/DebugServer.exe",`
И все заработало!!

/cc @EvilBeaver @dmpas

**Comment by EvilBeaver** [comment]
Блин, просочилась временная правка. Ее не надо было коммитить. Спасибо @khorevaa !!

**Comment by Vertudo** [comment]
Судя по последним комментариям код вроде рабочий под linux? Есть надежда на его деплой в продакшен?

**Comment by EvilBeaver** [comment]
Эта ошибка не исправлялась. @Vertudo если сможешь подтвердить/опровергнуть ее в Ubuntu - будет здорово. Вдруг она на свеших бубнах самопочинилась?

**Comment by Vertudo** [comment]
Дано. Debian 9.8. Свежий VS Code 1.34. Расширение OneScript Debug 0.3.0. Breakpoint выдают ошибку: "Duplex mode is expected to be 2".

**Comment by EvilBeaver** [comment]
Спасибо

**Comment by ghost** [comment]
@EvilBeaver не починилось к сожалению. Code-Insiders также

**Comment by EvilBeaver** [comment]
По слухам, на моно 6.х не воспроизводится.

**Comment by EvilBeaver** [comment]
Отладчик переписан под другой протокол. Должно все работать начиная с 1.4
