### ISSUE TITLE
Перестали работать F10/F11 в отладчике. Закрытый канал WCF

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#605]
В отладчике операции F10 и F11 выполняются через раз (даже чаще НЕ выполняются), т.к. канал обратной связи почему-то в закрытом состоянии.

**Comment by EvilBeaver** [comment]
Внезапно начало работать

**Comment by DmitryShehovtsev** [comment]
мне помогло полное удаление VSC и повторная установка. До и после переустановки была свежая версия VSC 1.22.2 (windows 10)
