### ISSUE TITLE
ЗаписьЖурналаРегистрации

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#609]
На уровне движка добавить встроенную команду `ЗаписьЖурналаРегистрации(<ИмяСобытия>, <Уровень>, <ОбъектМетаданных>, <Данные>, <Комментарий>, <РежимТранзакции>)`.

Сама по себе команда ничего не делает, но отдаёт входящие параметры подписанным обработчикам (мы же будем делать подписку?).
+1 к переносимости.

**Comment by EvilBeaver** [comment]
Мысль. Вот только API журнала регистрации всегда меня бесило :) но идея клевая, надо покумекать

**Comment by dmpas** [comment]
> API журнала регистрации всегда меня бесило

И не говори!!!!

**Comment by artbear** [comment]
Смысл дублировать именно эту команду??
только для непонятной в данной случае совместимости?

Правильнее сделать свое АПИ, которое при желании автор скрипта вызовет, добавив реализацию метода `Процедура ЗаписьЖурналаРегистрации`, если ему будет так нужно.

**Comment by EvilBeaver** [comment]
> Правильнее сделать свое АПИ

Правильнее по отношению к чему? Свое API у нас и так есть - в логосе. Но и вопрос твой тоже понятен. @dmpas а какую задачу ты решал, наткнувшись на эту мысль? Может нам от задачи пойти?

**Comment by dmpas** [comment]
@EvilBeaver задачи у меня не было, просто вспомнил обсуждение по #583. В частности, начиная отсюда: https://github.com/EvilBeaver/OneScript/issues/583#issuecomment-344249199

А так, я тоже считаю, что нужен простой понятный АПИ, который бы сам на пальцы ложился.

**Comment by EvilBeaver** [comment]
Давайте тогда для начала сформулируем цель. Что мы хотим получить?

**Comment by dmpas** [comment]
> Что мы хотим получить?

инструмент для логов на уровне движка. С возможностью управления им из кода (тем же логосом при его подключении).

ЗаписьЖурналаРегистрации - первое, что приходит на ум. Плюс: не возникает WTF при чтении кода. Минус: много WTF при написании такого кода.

**Comment by Stepa86** [comment]
Может лучше stdout сделать?

**Comment by EvilBeaver** [comment]
А зачем инструмент для логов на уровне движка? Чтобы что?

**Comment by dmpas** [comment]
> Чтобы что?

чтобы разработчик, пилящий на коленке свой маленький скрипт, писал сразу `лог(чтототам)` вместо `Сообщить(чтототам)`, чтобы потом при разрастании этого маленького скрипта на 5 строчек в библиотеку на 5 каталогов Артуру не было мучительно больно перехватывать логи.

**Comment by EvilBeaver** [comment]
Задача понятна. Просто мне наверное, кажется, что если я в программе пишу stdout.writeln вместо log.info, то я так и хочу. И "перехватывать" это не надо. А если "надо" - то надо в исходной программе исправить. А если автор неадекватный (у нас, слава Богу, нет таких пока) - то сделать форк, а оригинал послать нахер.

См. пост @kuntashov 

Но, раз общественность требует, то может сделаем что-то вроде:

```bsl
ДобавитьОбработчик "СобытиеВывода", "ПроцедураПерехватаIApplicationHost_Echo"
```

**Comment by dmpas** [comment]
> если я в программе пишу stdout.writeln вместо log.info

а теперь представь, что у тебя **нет** `log.info`. То есть, ты пишешь `stdout.writeln` не только потому, что ты так хочешь.

**Comment by EvilBeaver** [comment]
Из фразы "писал сразу лог(чтототам) вместо Сообщить(чтототам)" я понял, что он все равно пишет log.info, но только встроенный в движок.

**Comment by dmpas** [comment]
да. Но этого сейчас нет. Сейчас у нас нет чёткого разделения, хочет чел пользователю выдать что-то или технические логи сохранить.

**Comment by EvilBeaver** [comment]
Так этого и нигде нету. Технические логи всегда и везде явные. А Сообщить - это stdout.writeln.

Вернемся к кейсу: 

"1. Чел на коленке написал Сообщить, а потом ушло в народ и долго исправлять
2. Артур (имя вымышлено, совпадения с реальными личностями случайны) хочет пользоваться этой библиотекой, но рулить ее выхлопом - писать в файл, обеспечивать уровни и т.п.
3. Артур делает Х и получает желаемое"

Я правильно понял кейс? В таком случае, я не понимаю чему равен Х?

**Comment by dmpas** [comment]
нет, мой чемодан по именно этой задаче - исправить недоразумение под номером 1.

**Comment by EvilBeaver** [comment]
А так а я об чем? А номер 1 исправить как именно-то?

**Comment by artbear** [comment]
`Х` = `Артур добавляет перехватчик вывода в код, вставляет туда вызовы логоса, получает профит`

**Comment by EvilBeaver** [comment]
@artbear вот это ```ДобавитьОбработчик "СобытиеВывода", "ПроцедураПерехватаIApplicationHost_Echo"``` же спасет отца русской ~~демократии~~ тестирования?

**Comment by artbear** [comment]
Должно спасти.

Только вы внутри движка должны обеспечить отсутствие зацикливания.

Типа внутри обработчика Сообщить еще раз вызывается Сообщить :)

В свое время в 1С++, чтобы не грузить клиентский код, пришлось помудрить с этим.

**Comment by kuntashov** [comment]
Может добавить тогда в рефлектор возможность подменить любой метод на свой (как в дружественном PHP сделано)?
 
p.s.
```bsl
Процедура МоеСообщение(ТекстСообщения)
    ВыполнитьКомандуСистемы("rm -rf /");
КонецПроцедуры

ДобавитьОбработчик("СобытиеВывода", "МоеСообщение");
```

**Comment by artbear** [comment]
Саша, 
1 а в чем разница между твоим предложением в PS и ранее предложенным 
`ДобавитьОбработчик "СобытиеВывода", "ПроцедураПерехватаIApplicationHost_Echo"`

2 Про рефлектор вроде говорили уже.
Его задачи - все-таки только получение инфы.
Всякие подмены/перехваты ИМХО должны быть не в нем.

**Comment by EvilBeaver** [comment]
> Только вы внутри движка должны обеспечить отсутствие зацикливания.

Ну вот еще. А бесконечные рекурсии вам не поотлавливать? 👿

**Comment by kuntashov** [comment]
Да ничем, я же и пример использования привел :) 
Просто вижу, что Андрей уже почти сдался и предложил обобщить :)

**Comment by artbear** [comment]
Троллинг не прошел :)

Лады, можно/нужно, конечно, внутри обработчика Сообщить использовать
```bsl
ОтключитьОбработчик "СобытиеВывода";
Сообщить(Строка);
ДобавитьОбработчик "СобытиеВывода", "МойОбработчик";
```

**Comment by artbear** [comment]
>А бесконечные рекурсии вам не поотлавливать? 

А я в 1С++ отлавливал, было интересно :) - молодой был

**Comment by dmpas** [comment]
> ОтключитьОбработчик "СобытиеВывода";
> Сообщить(Строка);
> ДобавитьОбработчик "СобытиеВывода", "МойОбработчик";

вот сюда бы аннотации :)

```bsl
&ОбработчикСобытия("IApplicationHost_Echo")
Процедура МойОбработчик(параметры)
```

**Comment by artbear** [comment]
Пока нам и явное указания ДобавитьОбратчик подойдет :)

**Comment by dmpas** [comment]
А так при входе в процедуру можно сразу отключить остальные обработчики по этому событию, как вариант, включив обратно при выходе во имя продолжения цепочки.

**Comment by leemuar** [comment]
имхо логирование не должно быть частью движка, должно решаться библиотеками.
Подобный фасад можно реализовать на самом oscript, в том числе и с событиями через свой EventListener

**Comment by leemuar** [comment]
Уже в трех задачах обсуждаем проблему, привнесенную самим существованием функции Сообщить(). Может ее deprecate'нуть и вводить раздельные библиотеки для логирования, вывода и т.п.?

**Comment by Faithfinder** [comment]
Я конечно понимаю, у всех тут библиотеки, разработка мирового класса и всё такое на уме, но миссия односкрипта озвучена как "Автоматизируй себя на знакомом языке, 1Сер". И нет ничего лучше "Сообщить" для вывода быстренького одноразового скрипта (например, надо было мне как-то раз узнать все файлы в папке, созданные раньше определенной даты. Ну просто надо. И если бы мне пришлось искать какую-то библиотеку чтобы вывести результат я бы Андрея проклял ;)).

Ну и да, 1С-совместимость и всё такое.

**Comment by leemuar** [comment]
Забудьте про "Совместимость" и "знакомый язык" уже, миссия поменялась :)

**Comment by Faithfinder** [comment]
Вот как :) Меня не уведомили ;) Но так если так, то может сразу наконтрибутить в компилятор шарпа возможность писать по-русски :)? А то, ИМХО, например "КонецПроцедуры" против "КонецФункции" так убого, так убого ;)

**Comment by nixel2007** [comment]
миссия не менялась.

**Comment by kuntashov** [comment]
Боль от необходимости устанавливать какие-то библиотеки во всех современных языках уже давно в прошлом. Посттравматический эффект конечно же у нас, ~~старперов~~ бывалых разработчиков, остался из-за того, что раньше зависимости надо было разрешать вручную, мучиться с подбором версий библиотек и переживать о том, что какое-то другое приложение обновит общую библиотеку, авторы которой не позаботились об обратной совместимости и все сломается.

Но лично мне не нравится идея удаления теплого лампового `Сообщить()` из OneScript'а, ибо я тоже, встретив баг, не брезгую первую попытку найти его делать по-старинке принтами в консоль (даже когда у меня уже в скрипте подключен какой-нибудь логос). Потому что в простых случаях  возня с логом и информация в нем избыточна. 

Во-вторых, есть ниша скриптов из 10-20 строк, которые пишутся  для разового использования, и не разумно заставлять меня и кого-бы то ни было в таком случае писать столько же бутстрап-кода для  логов. Я немного утрирую, но тем не менее.

**Comment by Faithfinder** [comment]
Да черт с ним, с подбором версий и разрешением зависимостей, чтобы библиотеку использовать о ней надо хотя бы знать ;)

**Comment by kuntashov** [comment]
В случае с `Сообщить`, думаю, это не было (не будет?) проблемой.

**Comment by EvilBeaver** [comment]
Чуваки, нет никакой идеи удаления Сообщить, вы о чем?

**Comment by leemuar** [comment]
Мы обсуждаем же.
Я согласен, действительно нет  смысла удалять простой метод вывода.

**Comment by dmpas** [comment]
Развели трололо на ровном месте. Закрыть надо задачку или вонтфикс повесить.

**Comment by EvilBeaver** [comment]
наоборот, я сделаю реопен с метками, т.к. много идей хороших озвучено

**Comment by ReDBrother** [comment]
А есть уже рабочий вариант того, как перехватить?
Сейчас пытаюсь прикруть onescript в игру для программистов и мне нужно для повторяющего вызова функции, под каждый сформировать stdout вывод, чтобы облегчить отладку решений задачи.

**Comment by EvilBeaver** [comment]
@ReDBrother поясните - какую задачу вы делаете?

**Comment by ReDBrother** [comment]
По условиям игры, есть два участника, которые решают алгоритмическую задачу на выбранном языке. Задача заключается в написании функции, которая берет предопределенные аргументы и возвращает правильный результат.

Под каждую задачу формируется набор входных/выходных параметров. Когда участник отправляет на проверку свое решение, запускается докер контейнер, в котором это решение запускается под этим набором входных значений (их штук 30).

Каждый результат вызова у нас формирует ответ, который указывает на прохождение (условного) тестового кейса, и под него формируется отчет. Участник может, в целях отладки, выводить свои промежуточные результаты, и мы хотим их группировать под каждый конкретный вызов.

**Comment by nixel2007** [comment]
Может быть ид участника + ид запуска использовать как идентификатор лога для logos? Туда же можно передать абсолютно любую строку

**Comment by nixel2007** [comment]
Если ид лога не подойдёт, всегда можно использовать "поля" для вывода структурированного лога

**Comment by ReDBrother** [comment]
Но об этой особенности нужно будет отдельно сообщить участнику. Хотелось бы, чтобы участник мог писать на языке так, как пишет обычно и получать понятные логи.

> Если ид лога не подойдёт, всегда можно использовать "поля" для вывода структурированного лога

Да, можно поработать с выводом, который возвращает контейнер, но это довольно хрупкая штука. Вседа есть шанс, что игрок случайно его сломает. Переопределение stdout является стандартным решением в таких делах.

**Comment by ReDBrother** [comment]
Можно пойти дальше и сгенерить 30 отдельных функций и их позапускать, с последующим изьятием вывода каждого, но это с точки зрение ресурсов и времени работы безумие.

**Comment by EvilBeaver** [comment]
> Переопределение stdout является стандартным решением в таких делах

Поясните, пожалуйста, что вы понимаете под "переопределением stdout"? Да еще и стандартным. Можете привести пример на любом языке программирования, демонстрирующий данную технику? Непонятно о какой стандартной практике речь?

**Comment by kuntashov** [comment]
@EvilBeaver 

perl:

```perl
open(local *STDOUT, '>', "my_output.txt")
```
js (node.js):

```js
var myOutput = fs.createWriteStream('my_output.txt');
process.stdout.write = myOutput.write.bind(myOutput);
```

PHP:
```php
fclose(STDOUT);
$STDOUT = fopen('my_output.txt', 'wb');
```
и т.п.

В результате вывод всяких `print`/`console.log`/`echo` будет записываться в файл `my_output.txt`, а не в `stdout`.

**Comment by ReDBrother** [comment]
Или не в файл а в строку, тут неважно куда перенаправляют поток.
Для с# это бы выглядело так:
``` C#
TextWriter oldOut = Console.Out;
StringBuilder sb = new StringBuilder();
TextWriter newOut = new StringWriter(sb);
Console.SetOut(newOut);
...
Console.SetOut(oldOut);
Console.WriteLine(sb.ToString());
```

**Comment by EvilBeaver** [comment]
Понятно. Сейчас такой функции нет. Задача на работу со стандартными потоками процесса висит уже года три. @arkuznetsov даже за нее взялся не так давно. Артём, можешь этот кейс туда же в скоуп задачи добавить?

**Comment by arkuznetsov** [comment]
@EvilBeaver Я пока еще не дошел до осмысления твоего последнего коммента (в Телеге) :-) Подумаю как объединить эти задачи.

**Comment by nixel2007** [comment]
Мне не совсем понятен тезис про простоту использования для прикладников. В 1с нельзя переопределить stdout, так что прикладник, решающий задачу, не может знать о том, как это сдедать. Но при этом с помощью логоса текущую задачу разделения выводов по файлам уже можно решить.

Так что я ставлю под сомнение постановку задачи + это похоже на сову с глобусом

@ReDBrother

**Comment by leemuar** [comment]
Солидарен с Никитой. Не нужно выводить в stdout и переопределять его. Нужно выводить сразу туда куда нужно в конкретной прикладной функции

**Comment by ReDBrother** [comment]
@nixel2007 Да, я отчасти понимаю что подобного нет в оригинальном языке и действительно это будет немного не в кассу. Скорее у меня был вопрос по существующим вариантам. Попробую для начала с logos'ом поиграть и написать mvp, потом по фидбеку буду ориентироваться.

Всем большое спасибо за дискуссию и предложения)

**Comment by EvilBeaver** [comment]
Закрываю, т.к. переопределение вывода stdout реализовано в рамках #746 и цель данного ишуза достигнута.
