### ISSUE TITLE
Пропуск параметров при вызове методов. Совместимость с 1С

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#611]
Обнаружил, что onescript не хочет выполнять такой код:
```bsl
Процедура ИмяПроцедуры(А, Б)
	Сообщить(ТипЗнч(А));
	Сообщить(ТипЗнч(Б));
КонецПроцедуры

ИмяПроцедуры(, 2)
```
Ругается так: `Ошибка в строке: 7 / Аргумент 1 не имеет значения по умолчанию`

Но в языке 1С пропускать можно любые параметры. Если нет значения по умолчанию то параметр  должен быть равен Неопределено.

**Comment by dmpas** [comment]
Что-то я упустил в этой жизни??

**Comment by tsukanov-as** [comment]
@dmpas, видимо да: https://its.1c.ru/db/v8doc#content:58:1:issogl3_4.7.3.3.общиеособенностиуказанияпараметров

**Comment by EvilBeaver** [comment]
Прикольна.. )))) Ну да, я даже теперь вспоминаю такой топик на партнерке был. А так - кто ж мог подумать )))

**Comment by dmpas** [comment]
@EvilBeaver в 19-й засунем?

**Comment by EvilBeaver** [comment]
Да, если получится. И нам с тобой надо бы обсудить - что именно мы будем сувать в 19 и когда.

**Comment by EvilBeaver** [comment]
btw, вот для такого прототипа: ``Функция Ф(Парам1, Парам2)`` вызов с помощью ``Ф(,)`` - это вызов с одним параметром (должен упасть) или с двумя (должен сработать)?

**Comment by dmpas** [comment]
раз запятая, то с двумя как минимум

**Comment by EvilBeaver** [comment]
> раз запятая, то с двумя как минимум

Вот для меня сие не очевидно

**Comment by JohnyDeath** [comment]
> Что-то я упустил в этой жизни??

А как вы сейчас пишите в коде ассинхронной 1С "Предупреждение"?
Я вот так:

`ПоказатьПредупреждение( , ТекстПредупреждения, 30)`

Обработчик оповещения после предупреждения мне за всю жизнь не понадобился ни разу. Благо здесь он необязательный (а это вроде как уже нарушает стандарты: когда необязательные параметры должны идти в самом конце)

**Comment by dmpas** [comment]
> А как вы сейчас пишите в коде ассинхронной 1С "Предупреждение"?

я только пару месяцев, как слез с обычных форм. Так что, никак...

**Comment by EvilBeaver** [comment]
> А как вы сейчас пишите в коде ассинхронной 1С "Предупреждение"?

Рыдая и матерясь

**Comment by EvilBeaver** [comment]
> Обработчик оповещения после предупреждения мне за всю жизнь не понадобился ни разу

А как же

```
Предупреждение("Сейчас все ваши данные будут удалены. Вы согласны?");
УдалитьФайлы("C:\",*.*");
```

**Comment by JohnyDeath** [comment]
А как тут ответить "Нет"? )
Ребут?

**Comment by dmpas** [comment]
> А как тут ответить "Нет"? )

сдаётся мне, в том и был трололо...

**Comment by nixel2007** [comment]
Трололо это

```bsl
ПоказатьПредупреждение( , "Сейчас все ваши данные будут удалены. Вы согласны?", 30)
УдалитьФайлы("C:\",*.*");
```

**Comment by dmpas** [comment]
киньте кто-нибудь, что там в ИТСе написано. У меня дома нету туды полноценного доступа... Можно в гиттер в личку. Буду премного благодарен.

**Comment by tsukanov-as** [comment]
@dmpas https://i.imgur.com/uIWlCXb.png

**Comment by dmpas** [comment]
Всем спасибо!
