### ISSUE TITLE
Класс ЧтениеТекста перестал быть совместимым с 1С

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#616]
В 1С у конструктора класса ЧтениеТекста и метода Открыть появился 
необязательный 5-ый параметр `МонопольныйРежим: Булево`
```
МонопольныйРежим: Определяет режим открытия файла. 
Истина - монопольный, Ложь - разделяемый. Значение по умолчанию: Истина.
```

При попытке использовать этот параметр в скрипте 
```bsl
	ЧтениеТекста = Новый ЧтениеТекста;
	ЧтениеТекста.Открыть(Файл.ПолноеИмя, Кодировка, , , Ложь);
```
выдается ошибка
```
{Модуль ФайловыеОперации.os / 
Ошибка в строке: 317 / Слишком много фактических параметров}
        ЧтениеТекста.Открыть(Файл.ПолноеИмя, Кодировка, , , Ложь);
```

@dmpas @EvilBeaver Сделайте, пожалуйста, до выхода 19 релиза

**Comment by artbear** [comment]
![image](https://user-images.githubusercontent.com/2920817/33796773-4e7774de-dd0c-11e7-963c-84ca228ba9b1.png)

**Comment by dmpas** [comment]
запилю на выходных.

**Comment by artbear** [comment]
Спасибо. Буду ждать

**Comment by ghost** [comment]
@dmpas гляньте #617 - предполагаю что это связанные штуки

**Comment by dmpas** [comment]
@allustin связаны, но #617 решим в рамках отдельной допилки.

@artbear подсобишь с тестом??

**Comment by artbear** [comment]
Да, помогу.
Простейший сценарий, на который я нарвался.
Открываем файл через ЗаписьТекста
далее пытаемся читать через ЧтениеТекста.
Сейчас прочитать нельзя
С твоей доработкой будет можно при МонопольныйРежим = Ложь

**Comment by dmpas** [comment]
@artbear тут всё чётко?

**Comment by artbear** [comment]
По коду и тестам на главном CI все нормально, 
На ночнике еще проверю на днях.
