### ISSUE TITLE
Блокировки на чтение и запись файла

### ISSUE THREAD

**Issue by ghost** [EvilBeaver/OneScript#617]
https://github.com/EvilBeaver/OneScript/blob/16f3af1edaed0bcd69cf5c2cf70b0ec44d830195/src/ScriptEngine/Environment/FileOpener.cs#L19

Хотелось бы явно управлять уровнем изоляции файлового потока

```
using (FileStream fs = new FileStream(logFilePath, 
                                      FileMode.Open, 
                                      FileAccess.Read,    
                                      FileShare.ReadWrite)
```

то есть

* открыть для чтения, разрешить запись
* открыть для чтения, разрешить чтение
* открыть для чтения, запретить чтение и запись

**Comment by EvilBeaver** [comment]
А зачем? Этот класс он же по определению на чтение только должен открывать...

**Comment by EvilBeaver** [comment]
Управление режимом файла есть в файловых потоках.
