### ISSUE TITLE
Рефлексия экспортных методов

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#626]
При рефлексии модуля нельзя понять какой из методов скрипта экспортный. Флаги public|private не выставляются

**Comment by nixel2007** [comment]
Разве рефлексия должна отдавать приватные методы? Сейчас отдаются только публичные и это кажется логичным.

**Comment by EvilBeaver** [comment]
Еще как! Вот, например, какие костыли приходится делать, из-за ишуза #625.

https://github.com/EvilBeaver/OneScript.Web/blob/master/src/OneScript/Infrastructure/Implementations/OscriptApplicationModelProvider.cs#L47-L63

Если бы не рефлексия приватов...

**Comment by leemuar** [comment]
Я правильно понял, что определение приватных методов нужно для каких-то внутренних нужд движка, а не для нового метода объекта Рефлектор в языке?

**Comment by EvilBeaver** [comment]
@leemuar да, это для шарпистов.

**Comment by dmpas** [comment]
нафига вообще приватные методы рефлексировать? По-моему, компилятор должен иметь полное право их выкинуть, или переименовать, или преобразовать любым иным доступным ему способом.

**Comment by EvilBeaver** [comment]
Нене, речь о другом. Когда ты рефлектишь os-метод в родной шарповый MethodInfo, то ты не узнаешь был этот метод приватным или публичным.

А рефлектить приваты обязательно надо, т.к. это штатный механизм CLR, а основная суть как раз и была сделать os-модуль видимым в рефлексии, с теми же функциями, что и рефлексированный шарповый модуль. Т.е. конструкторы, методы, поля, приватные, публичные, атрибуты и пр.
