### ISSUE TITLE
Не учитываются относительные пути файлов при помещении в ZIP-архив

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#627]
похоже, на баг нарвался.
Делаю пакет ADD
в opm есть возможность включить файлы в поставку библиотеки
этот код работает верно для каталогов и файлов только из корневого каталога.
А вот если указать путь файла из какого-то вложенного каталога, например, "plugins\Настройки.epf", то файл будет помещен в корневой каталог
`.ВключитьФайл("plugins\Настройки.epf")`
тогда файл в итоговом зип-файле включается в корень, а не в папку plugins

Смотрю исходники
В opm есть код
```bsl
    АрхивПакета.Добавить(Новый Файл(ПутьФайла).ПолноеИмя,
        РежимСохраненияПутейZIP.СохранятьОтносительныеПути,
        РежимОбработкиПодкаталоговZIP.ОбрабатыватьРекурсивно);
```
похоже на баг движка 
 
вот код проверки
```bsl
ПутьАрхиваЦелевойСистемы = "test1.zip";
АрхивЦелевойСистемы = Новый ЗаписьZIPФайла(ПутьАрхиваЦелевойСистемы);

ВключаемыйФайл = "plugins\Настройки.epf";
Сообщить("Добавляем файл: " + ВключаемыйФайл);
ПолныйПуть = Новый Файл(ВключаемыйФайл).ПолноеИмя;
АрхивЦелевойСистемы.Добавить(ПолныйПуть, РежимСохраненияПутейZIP.СохранятьОтносительныеПути, РежимОбработкиПодкаталоговZIP.ОбрабатыватьРекурсивно);

АрхивЦелевойСистемы.Записать();
```
![image](https://user-images.githubusercontent.com/2920817/34003965-c09784ec-e107-11e7-8c46-cf8d1c438da6.png)
 
т.е. никаких относительных путей 

/cc @EvilBeaver @dmpas @nixel2007

**Comment by EvilBeaver** [comment]
Кажется дубликат

**Comment by EvilBeaver** [comment]
@artbear для обхода, попробуй сделать у "plugins/Обработка.epf" получение полного пути и в архив добавлять уже полный путь. По-моему, оно тогда корректно вычислит относительный.

**Comment by artbear** [comment]
Я разные способы попробовал.
Не помогло.
Тогда и создал ишуз

**Comment by artbear** [comment]
@EvilBeaver @dmpas Я провел небольшое исследование кода
https://github.com/EvilBeaver/OneScript/blob/7e84f4d5c51a350679a0e8b1b4c07d8d875a4234/src/ScriptEngine.HostedScript/Library/Zip/ZipWriter.cs#L121

при добавлении одиночных файлов написано
```c#
        private void AddSingleFile(string file, SelfAwareEnumValue<ZipStorePathModeEnum> storePathMode)
        {
            var storeModeEnum = GlobalsManager.GetEnum<ZipStorePathModeEnum>();
            if (storePathMode == null)
                storePathMode = (SelfAwareEnumValue<ZipStorePathModeEnum>)storeModeEnum.StoreRelativePath;

            string pathInArchive;
            if (storePathMode == storeModeEnum.StoreFullPath)
                pathInArchive = null;
            else
                pathInArchive = ""; // ВОТ ЗДЕСЬ

            
            _zip.AddFile(file, pathInArchive);
        }
```
а при добавлении каталога код другой
в https://github.com/EvilBeaver/OneScript/blob/7e84f4d5c51a350679a0e8b1b4c07d8d875a4234/src/ScriptEngine.HostedScript/Library/Zip/ZipWriter.cs#L107 
```c#
        private void AddDirectory(string file, System.IO.SearchOption searchOption, SelfAwareEnumValue<ZipStorePathModeEnum> storePathMode)
        {
            var path = Path.IsPathRooted(file) ? Path.GetDirectoryName(file) : Path.GetFullPath(file);
            string allFilesMask;

            if (System.Environment.OSVersion.Platform == PlatformID.Unix || System.Environment.OSVersion.Platform == PlatformID.MacOSX)
                allFilesMask = "*";
            else
                allFilesMask = "*.*";

            var filesToAdd = System.IO.Directory.EnumerateFiles(file, allFilesMask, searchOption);
            AddEnumeratedFiles(filesToAdd, path, storePathMode);
        }
```
идет вызов метода 
`AddEnumeratedFiles`  из https://github.com/EvilBeaver/OneScript/blob/7e84f4d5c51a350679a0e8b1b4c07d8d875a4234/src/ScriptEngine.HostedScript/Library/Zip/ZipWriter.cs#L179
```c#
        private void AddEnumeratedFiles(IEnumerable<string> filesToAdd, string relativePath, SelfAwareEnumValue<ZipStorePathModeEnum> storePathMode)
        {
            var storeModeEnum = GlobalsManager.GetEnum<ZipStorePathModeEnum>();
            if (storePathMode == null)
                storePathMode = (SelfAwareEnumValue<ZipStorePathModeEnum>)storeModeEnum.DontStorePath;

            foreach (var item in filesToAdd)
            {
                string pathInArchive;
                if (storePathMode == storeModeEnum.StoreRelativePath)
                    pathInArchive = GetRelativePath(item, relativePath); // ВОТ ЗДЕСЬ
                else if (storePathMode == storeModeEnum.StoreFullPath)
                    pathInArchive = null;
                else
                    pathInArchive = "";

                _zip.AddFile(item, pathInArchive);
            }
        }
```
мои комментарии ` // ВОТ ЗДЕСЬ`

Видно, что в первом участке кода (для файла) вообще не указан относительный путь
а вот во втором он рассчитывается
`pathInArchive = GetRelativePath(item, relativePath);`

ИМХО нужно 
1 добавить нахождение пути каталога, где находится файл, для получения корня
2 для первого участка кода (для файла) добавить аналогичное условие с указанием вышенайденного корня.

@dmpas Сможешь проверить? Пример тестового кода указан в начале досады :)

PS у меня на машине не на чем собирать, поэтому сам проверить не смогу :(

**Comment by dmpas** [comment]
@artbear а ты можешь проверить, как оно в 1С себя ведёт??

**Comment by EvilBeaver** [comment]
Есть хитрость. В 1с ВООБЩЕ нет понятия относительных путей для зипа и мне пришлось изобретать поведение. 1С, если ты помещаешь в зип файл с относительным путем ведет себя совершенно как-то иначе.

**Comment by artbear** [comment]
Да, у 1С фактически нет текущего каталога, поэтому в части классов работает странно.
А у нас есть, поэтому нам нужно учитывать текущий каталог

**Comment by artbear** [comment]
Давайте придерживаться нормального поведения зипа.
Относительный путь - это относительный путь.

Если указан путь, который находится внутри текущего каталога, нужно юзать относительные пути.
Если указан путь, который находится вне текущего каталога, нужно юзать абсолютные пути.

**Comment by EvilBeaver** [comment]
> нормального поведения зипа

@artbear никто же не против. А "нормальное" - это какое? Закинь пулреквестом тест, декларирующий правильное поведение, мы починим.

**Comment by artbear** [comment]
Создал тесты в #629 
@EvilBeaver @dmpas Посмотрите, поправите?

**Comment by artbear** [comment]
Два добавленных теста сейчас падают.
