### ISSUE TITLE
Запуск zip или ospx без распаковки 

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#628]
По мотивам giiter'a,
Предлагаю реализовать возможность запуска собранных, по принципе sefl-контейнер, приложений на oscript сразу по указанию в строке запуска без распаковки и прочего. По примеру java. 

Например, 

`oscript -run opm.ospx .... аргументы`

**Comment by nixel2007** [comment]
а что запускать-то? только приложения по их энтрипойнтам? тогда нужно еще и энтрипойнт указывать, если он не один

**Comment by khorevaa** [comment]
Энтрипоинт же прописывается.... где-то, если несколько запускать первый...

**Comment by dmpas** [comment]
либо энтрипоинт, либо какое-то соглашение типа main.os

**Comment by artbear** [comment]
Зачем смешивать 2 функциональности?
У нас есть движок, и у нас есть opm.
Каждый выполняет свою работу.
Если и добавлять запуск ospx, то через opm

Предлагаю перенести ишуз в opm

**Comment by dmpas** [comment]
нет у тебя opm. есть только opm.ospx и oscript.exe

**Comment by artbear** [comment]
Еще раз - зачем смешивать?
нафига движку знать о внутренностях реализации ospx ?

**Comment by dmpas** [comment]
забудь про ospx, подумай о zip. Zip - это как exe, но с открытым кодом.

**Comment by artbear** [comment]
лукавить не нужно, мы говорим именно о ospx.
zip всплыл уже как особенность реализации.

**Comment by artbear** [comment]
Никита в гиттере https://gitter.im/EvilBeaver/OneScript?at=5a33817bc65707ba2b552f3e
хорошо описал.

**Comment by dmpas** [comment]
я и не лукавлю. в моей голове изначально была мысль про zip, а ospx всплыл лишь сегодня

**Comment by khorevaa** [comment]
Можно и любой другой формат не принципиально, важна сама возможность запуска приложения включащего в себя все необходимое без необходимости распаковки и прочего.

**Comment by dmpas** [comment]
>  важна сама возможность запуска приложения включащего в себя все необходимое без необходимости распаковки и прочего

если открытость исходника не важна, то подожди макеты и сборку ЕХЕ

**Comment by artbear** [comment]
И мы плавно возвращаемся в тему make или макетов :)

**Comment by artbear** [comment]
Закрываю ишуз?

**Comment by dmpas** [comment]
разница между zip и exe в данном случае - в открытости исходника. Если такого требования нет, то получается одно и то же. В противном случае - разные вещи.

> ишуз

вот окаянный!!!

**Comment by artbear** [comment]
Закрыл для пробы :)
Если кому-то очень сильно нужно, переоткрывайте.
Но в авторской формулировке досада должна быть переподана в опм.

ОФФ
>zip и exe

вот окаянный!!!

**Comment by dmpas** [comment]
Переоткрою. Ибо тема всё же не раскрыта до конца, как мне кажется.

**Comment by artbear** [comment]
ОФФ Потому что пятница и сиськи :) ?

**Comment by dmpas** [comment]
ОФФ нет, потому что у меня блюз в си миноре не получается и меня это разрдражает.


Просто есть проблема, есть очевидное решение, но нет трезвой всесторонней оценки насколько оно лучше/хуже того, что есть/будет.

**Comment by EvilBeaver** [comment]
> блюз в си миноре не получается

Закинь табы.

P.S. /me не умеет играть блюз совершенно, но хочет освоить хотя бы азы

**Comment by dmpas** [comment]
> Закинь табы.

гармошка в G, 5-я позиция: `2 2- 3" 3' 3- 4- 5 6 6- 7- 8- 8 9 10- 10" 10'`

**Comment by nixel2007** [comment]
@EvilBeaver офф. там несколько базовых позиций. а так по по тонике просто вверх-вниз. азы я тебе могу в воскресенье показать) у меня с импровизацией плохо, но база довольно простая.

посоны, а может это в гиттер, а? :)
