### ISSUE TITLE
Баг свежей ночной сборки 19 релиза

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#633]
@EvilBeaver @dmpas @nixel2007 **Выпускать релиз 19 пока нельзя !**

скачал вчерашнюю ночную сборку (от 22.12) - 1.0.19.19
пытаюсь прогнать тесты, скомпилить пакет и прочее для ванесса-раннер
и кирдык, все падает

например, `opm build . ` перестает правильно работать,
потому что ванесса-раннер использует в packadef код из `1commands` через `#Использовать 1commands`

а у `opm` в `oscript_modules` старая-старая версия `1commands` приезжает, аж 0.8  хотя текущая уже 1.3.1

`opm test` для ванесса-раннер также падает по тем же причинам 

пробовал разные варианты
```cmd
cmd /c "(set LOGOS_CONFIG=logger.rootLogger=DEBUG) && (set OSLIB_LOADER_TRACE=1) && (set OSLIB_LOADER_DUPLICATES=1) && (opm build . >1.txt)"
cmd /c "(set LOGOS_CONFIG=logger.rootLogger=DEBUG) && (set OSLIB_LOADER_TRACE=1) && (set OSLIB_LOADER_DUPLICATES=0) && (opm build . >1.txt)"
cmd /c "(set LOGOS_CONFIG=logger.rootLogger=DEBUG) && (set OSLIB_LOADER_TRACE=1) && (set OSLIB_LOADER_DUPLICATES=0) && (opm build . >1.txt)"
```

бесполезно.
Все время подсовывается старая версия `1коммандс` из `opm`, что видно из подробного лога

режим self-contained фактически очень сложно будет юзать, если нужно запускать чужие скрипты.
Как например, в `opm run ЗадачаИзЧужогоПродукта` или `opm test`
т.к. могут юзаться разные зависимости пакетов

Да и другое странно - собираемся выпускать движок с develop-версией opm  которая еще даже не зарелизена ??

опять без меня натворили чего-то :trollface:

**Comment by artbear** [comment]
и далее `opm update opm` выдает странные ошибки :(

**Comment by artbear** [comment]
Первый запуск выдает такую ошибку
```
C:\> opm update opm
{Модуль C:\OneScript\lib\package-loader.os / Ошибка в строке: 56 / 
Не найден файл C:\OneScript\lib\opm\oscript_modules\cmdline\src\cmdline.os, 
указанный в манифесте}
```
а следующий запуск уже другую ошибку
```
C:\> opm update opm
{Модуль C:\OneScript\lib\opm\src\Классы\КомандаOpm_Push.os / 
Ошибка в строке: 5 / Библиотека не найдена gitrunner}
```

Весело!

**Comment by artbear** [comment]
Каталог `C:\OneScript\lib\opm\oscript_modules\cmdline\src\` становится пуст после выполнения `opm update opm` :(

**Comment by EvilBeaver** [comment]
Последний камент подтверждаю

**Comment by EvilBeaver** [comment]
Два предыдущих - его следствие

**Comment by nixel2007** [comment]
Ну естественно, в хабе старый опм, а селф-контейнед опм может работать только по-новому.

**Comment by nixel2007** [comment]
Бампните зависимости в опмовском пэкэдждеф и вся недолга.

**Comment by artbear** [comment]
Зачем закрыл без реального исправления?

**Comment by nixel2007** [comment]
Потому что это не баг движка да и вообще не баг. Это проблема пакетов, которым нужен новый 1командс при запуске тасков. Правильным путем здесь было бы создать ишуз в репе опм с **просьбой** обновить 1коммандс в опм, а не кидаться багами свежего ночника.

**Comment by artbear** [comment]
Никита, а если встать на сторону пользователя?

+ Я как обычный пользователь скачал полную сборку движка, 
+ установил движок, указав все флаги в форме установки
+ больше никаких изменений на своей машине не делал
+ начал использовать продукт, завязанный на движок
+ и получил баг
+ на старой версии движка бага не было, других изменений не было, значит, виновата свежая установка движка
+ вот и регистрация бага в движок

Для пользователя важно исправление бага в движке.
А уж разработчики могут/должны сами создать зависимые задачи в необходимых репозиториях.
И лучше это делать комплексно - поправить здесь и здесь, включить там и там, добавить при сборке и т.п.
Не нужно кусочечно решать.
В опм можно многое сделать, но кто в движок это закинет?
и т.п. и т.д.

**Comment by artbear** [comment]
А вообще все странно - пришел заинтересованный человек, сообщил о проблеме, к нему бы прислушаться и сделать что-то правильное, а не писать, что этот баг в другом месте и вообще не баг, и лучше было не регистрировать баг, и т.п.
Зашибись клиенто-ориентированность :(

**Comment by nixel2007** [comment]
Ты же помнишь, что это ночник?

**Comment by nixel2007** [comment]
И последнее

> Да и другое странно - собираемся выпускать движок с develop-версией opm которая еще даже не зарелизена ??

Новый опм требует ещё не вышедший 19ый движок. Мы договорились не публиковать в хабе библиотеки, требующие ночника.

**Comment by EvilBeaver** [comment]
В dev-channel хаба можно поместить новый opm, и будет правильно. Ночник на ночном пакете.
@artbear я закрыл issue, т.к. не знаю что именно должно быть сделано, чтобы issue считался исправленным. Каков критерий выполнения задачи?

**Comment by EvilBeaver** [comment]
> Зашибись клиенто-ориентированность

Ну и да, ты все-таки не человек со стороны, поэтому к тебе клиентоориентированность не относится. 😄  Ты ведь человек из нашего гаражного кооператива. Поэтому на вопрос "я снял карбюратор и перестало заводиться" мы не отвечаем тебе "поставь назад", а по-свойски говорим: "а хуле ты хотел, епт?" 😄

**Comment by artbear** [comment]
Критерий выполнения:
добиться, чтобы на ночнике и дев-сборке опм не было привнесено ошибок работы существующих приложений оскрипт, например, сборки vanessa-runner через opm

Чек-лист проверки:

+ скачать ночную сборку движка, 
+ установить движок, указав все флаги в форме установки
+ больше никаких изменений на своей машине не делать
+ запустить в каталоге vanessa-runner команду `opm build .`
+ ошибок при сборке не должно быть
+ команда `opm update opm -ключ_указания_дев-хаба` не должна выдавать ошибок
+ и после этого сборка ванесса-раннер опять должна выполняться

**Comment by artbear** [comment]
И еще :
+ команда `opm update opm -ключ_указания_дев-хаба` не должна выдавать ошибок
+ и после этого сборка ванесса-раннер опять должна выполняться

**Comment by artbear** [comment]
Проблема, кстати, не в opm.
А в гитраннере или какой-то другой библиотеке, которую юзает opm

**Comment by artbear** [comment]
Проблема была найдена в гитраннере и 1тестраннере.
+ Выпустил релизы 1.5.1 обоих продуктов 
  + номера версий неожиданно совпали :)
+ выпилил использование 1тестраннер из зависимостей opm и выгрузил в develop-ветку opm

**Comment by artbear** [comment]
Выпустил дев-сборку opm 0.12.1 в дев-хаб
Упс, хотя это версия 1.0.0 (как минимум) :)

**Comment by EvilBeaver** [comment]
@artbear а что за проблема была?

**Comment by artbear** [comment]
В обоих измененных продуктах была старая версия 1коммандс.
А т.к. в 1тестраннере была более  старая (очень старая) версия 1коммандс (0.8), то она и приехала.
Исправил/Выпилил

**Comment by artbear** [comment]
Но еще не проверял по чек-листу

**Comment by artbear** [comment]
Вот ты зачем опять закрываешь-то?
Проблема-то не решена.

Я все обновил, установил ночную сборку, 
настроил opm.cfg на дев-хаб
`opm update opm` один раз выполнился и все.

второй раз выполняется с ранее же найденной ошибкой - 
Первый запуск выдает такую ошибку
```
C:\> opm update opm
{Модуль C:\OneScript\lib\package-loader.os / Ошибка в строке: 56 / 
Не найден файл C:\OneScript\lib\opm\oscript_modules\cmdline\src\cmdline.os, 
указанный в манифесте}
```

**Comment by artbear** [comment]
А у нас сейчас dev-opm жестко связан с релизом 19, насколько я понимаю :(
Релиз 19 не будем же выпускать без `self-contained opm`, верно?

**Comment by artbear** [comment]
Андрей, если скажешь `вето`, больше переоткрывать не буду :)

**Comment by EvilBeaver** [comment]
Ты написал "Проблема была найдена в гитраннере и 1тестраннере." Я решил, что вопрос исчерпан и закрыл.

А вообще - зачем ты обновляешь opm? Ведь это как раз то, чего делать не надо и как раз то, что делать совсем необязательно после установки ночника.

**Comment by EvilBeaver** [comment]
Артур, смотри: сейчас в дев-хабе лежит битый opm. Он больше 64Кб и такие пакеты мы через opm push не публикуем. Проблема известна, признана, сейчас не о ней. Итак, дано: в develop-хабе лежит поврежденный архив opm.ospx.

Если бы он был нормальный, то ``opm update opm`` работал бы без проблем - распаковывая новую версию вместо старой.

Однако, сейчас он перед установкой вычищает целевой каталог от файлов *.os, затем пытается распаковать и валится. Вполне вероятно, что в opm есть баг, который прячет эту ошибку или выводит ее в "Отладку", хотя надо бы в "Критичную ошибку" (насчет бага просто гипотеза).

Итого, получается, что у тебя удалился старый opm, но новый не поставился, т.к. в хаб выложен кривой опм. Где тут баг движка, блокирующий релиз?

**Comment by artbear** [comment]
+ Да, я опять забыл про дурацкий баг в 64К и не увидел, что опм-билд больше этого размера :(
+ И да, опм не выдает ошибок при обновлении :(

Далее:
+ я обновляю опм, т.к. мы-разработчики-пользователи оскрипта привыкли, что нужно делать opm update opm :) 
  + у меня opm build выдает ошибку для ванесса-раннер, как описано выше.
+ я подозреваю, что еще какие-то продукты дадут баг при использовании команд приложений оскрипт - opm, 1testrunner, 1bdd и другие, которые могут вызывать скрипты.

и еще
>А у нас сейчас dev-opm жестко связан с релизом 19, насколько я понимаю :(
Релиз 19 не будем же выпускать без self-contained opm, верно?

Потому я и меняю opm

**Comment by EvilBeaver** [comment]
Ничего не понял... Какие мои действия после всего вышеописанного ожидаются?

**Comment by artbear** [comment]
Твои действия:
+ тебе нужно выложить opm-XXX.ospx в дев-хаб, т.к. он больше 64 Кб, Никита в отпуске, а доступ к хабу только у тебя и у него.
  + после появления нового опм в дев-хабе я еще раз могу выполнить прогон по чек-листу проверки.
+ тебе нужно (или можно) сымитировать работу с новым движком и новым opm, как будто это выполняется пользователем после развертывания релиза 19
  + я имитировал, у меня не работает.

ну и чек-лист проверки я указывал в https://github.com/EvilBeaver/OneScript/issues/633#issuecomment-353862522

**Comment by nixel2007** [comment]
В чем проблема собрать опм локально и установить его из файла? К чему эти пляски с хабом? Проблемы на ровном месте, ей богу.

**Comment by nixel2007** [comment]
Ещё раз - проблема решается двумя путями: 1) обновить 1коммандс в опм. 2) не использовать таски опм для ванесса-раннер.

И никакого блокера релиза нет, это проблема именно взаимодействия ванесса-раннера и опм.

**Comment by EvilBeaver** [comment]
Ну путь 2 заведомо неправильный. @nixel2007 Артур работает по сценарию, по которому пойдет большинство пользователей, поэтому и говорит, что ничо не работает. Проблема же есть, разве нет? Ну и да, это не блокер.

**Comment by artbear** [comment]
С точки зрения пользователей - если после установки нового движка у них перестанет работающий до этого функционал, виноват в этом будет новый релиз :(
вот и вся связь и блокер тут же :)

**Comment by artbear** [comment]
Эх, все-таки выпустили релиз и нарвались на баги :(
