### ISSUE TITLE
Подобъем итоги выпуска 19 релиза и сделаем, чтобы они не повторялись

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#636]
После выпуска 19 релиза проявилось несколько проблем:
+ opm работал неверно 
  + https://gitter.im/EvilBeaver/OneScript?at=5a44abc40163b02810879b73
  +   не было файла oscript.cfg, т.к. неверно был собран opm.ospx в движке
  + Исправлено
+ неверно начал работать vanessa-runner
  + проблема с v8runner и монопольном чтении по умолчанию на 19 релизе
  + Исправлено
```
{Модуль C:\Program Files (x86)\OneScript\lib\v8runner\src\v8config-file.os / 
Ошибка в строке: 15 / Внешнее исключение (System.IO.IOException): 
Процесс не может получить доступ к файлу "C:\ProgramData\1C\1CEStart\1CEStart.cfg", 
так как этот файл используется другим процессом.}
```
+ fluent падает с ошибкой 
  + исправление было в ветке develop, но в мастере релиза не было
  + Исправлено
```
{Модуль C:\OneScript\lib\opm\oscript_modules\fluent\src\Классы\ПроцессорКоллекций.os / 
Ошибка в строке: 861 / Внешнее исключение (System.IO.IOException): 
Процесс не может получить доступ к файлу
"C:\OneScript\lib\opm\oscript_modules\fluent\src\Классы\ШаблонИзолированногоКласса.os", 
так как этот файл используется другим процессом.}
```
+ logos стал работать неверно - не все сообщения выдавались в лог
  + https://github.com/oscript-library/logos/pull/18
  + Было мало ручных тестов + не было автотеста на эту ситуацию
  + Исправлено ( и добавлен автотест)

/cc @EvilBeaver @dmpas @nixel2007

**Comment by artbear** [comment]
ИМХО не прогнали тесты мастер-веток штатных библиотек на новом движке.
а ведь у нас есть целый CI для этого :)

**Comment by artbear** [comment]
Штатные сценарии, которые можно было проверить сразу после развертывания релиза на CI
+ `opm list`
+ `opm update opm`
+ `opm update -all`

**Comment by artbear** [comment]
Обновил проблемы в шапке

**Comment by EvilBeaver** [comment]
Плюс монетка в копилку тех, кто считает, что поставлять с движком надо только opm, а библиотеки нахер

**Comment by artbear** [comment]
Нет, напротив, это минус в их копилку.
Например, баг с флюентом и в8раннером случился из-за того, что в движке добавили Монопольность/Немонопольность в режиме совместимости с 1С, чем **сломали нашу совместимость** :( без объявления этого!

если бы тесты этих библиотек прогнали на 19 движке, эти проблемы были бы выявлены и их можно было исключить

**Comment by EvilBeaver** [comment]
А, ну с этим не спорю, тесты надо гонять

**Comment by nixel2007** [comment]
Если бы прогнали тесты опм, то сразу бы выявились проблемы опм :trollface: и флюента. Но поломка совместимости - это подстава, да.
