### ISSUE TITLE
Консольное окно

### ISSUE THREAD

**Issue by hqsone** [EvilBeaver/OneScript#637]
Подскажите пожалуйста возможно ли избавиться от окна во время работы скрипта скомпилированного в приложение.

Или при простом запуске скрипта.

**Comment by dmpas** [comment]
штатных средств в односкрипте нет. Под виндой можно использовать `binedit`.

**Comment by hqsone** [comment]
А как можно попросить добавить такой параметр командной строки при  указании которого окно не показывалось бы?

**Comment by dmpas** [comment]
параметром тут не обойтись, это особенность поведения в винде: там приложение либо консольное, либо графическое. В первом случае появляется окно консоли, во втором - нет. Поэтому появляются костыли в виде двух приложений (`cscript.exe` и `wscript.exe`, например). У нас в планах когда-то было нечто подобное, но сейчас такого нет и в ближайшем будущем не появится.

**Comment by EvilBeaver** [comment]
А я так и не понял о чем вы. Речь идет о том, чтобы запустить процесс в режиме WINDOW_MODE:HIDDEN? Так можно сделать извне односкрипта, запустив его, скажем через shell. А как внутри - хз

**Comment by hqsone** [comment]
Да именно это я и имел ввиду. Но через shell, можно только с помощью Run, а мне подходит только Exec, так как надо мониторить процесс.
