### ISSUE TITLE
Ошибка конструктора ЧтениеДанных 

### ISSUE THREAD

**Issue by vasvl123** [EvilBeaver/OneScript#638]
ИмяФайлаДанных = "C:\Windows\win.ini";
ПотокДанных = ФайловыеПотоки.ОткрытьДляЧтения(ИмяФайлаДанных);
Чтение = Новый ЧтениеДанных(ПотокДанных);
Сообщить(Чтение.ПрочитатьСимволы(ПотокДанных.Размер()));

Ошибка в строке: 3 / Внешнее исключение (System.ArgumentException): Невозможно преобразовать объект типа "ScriptEngine.HostedScript.Library.Binary.FileStreamContext" к типу "ScriptEngine.HostedScript.Library.Binary.BinaryDataContext".}

**Comment by EvilBeaver** [comment]
Исправлено
