### ISSUE TITLE
Не находит метод insert структуры

### ISSUE THREAD

**Issue by vasvl123** [EvilBeaver/OneScript#639]
стр = Новый Структура;
стр.Вставить("ключ1","значение1");
стр.insert("ключ2","значение2");

 Ошибка в строке: 3 / Метод объекта не обнаружен (insert)}

**Comment by dmpas** [comment]
беда-безобразие! это в которой версии?

**Comment by vasvl123** [comment]
1Script Execution Engine. Version 1.0.19.103

**Comment by EvilBeaver** [comment]
Вот она - востребованность английских терминов )) за 4 года никто не додумался вызвать.

Спасибо!

**Comment by vasvl123** [comment]
раньше работало. в 17 точно.

**Comment by nixel2007** [comment]
А с большой буквы? (ну а вдруг)

**Comment by dmpas** [comment]
@vasvl123  если не сложно, проверь сборку отсюда http://build.oscript.io/job/1Script/job/hotfix%252Ffix-components-19/2/

**Comment by vasvl123** [comment]
работает

**Comment by dmpas** [comment]
качаем исправленную 19-шку http://oscript.io/Downloads/Archive/1_0_19

**Comment by EvilBeaver** [comment]
@dmpas типа самопочинилось при смене конструктора атрибута?

**Comment by dmpas** [comment]
@EvilBeaver не совсем.
https://github.com/EvilBeaver/OneScript/commit/b69e004931677a5b13d426befd6258b570914c8d#diff-8c563a877d4ee9837fb92cdc5351c76fR208
