### ISSUE TITLE
Подключить SpecLog для прогона тестов

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#64]
Originally reported by: **Alexey Lustin (Bitbucket: [allustin](http://bitbucket.org/allustin), GitHub: [allustin](http://github.com/allustin))**

---

Предлагают задействовать https://github.com/techtalk/SpecFlow

Будет намного удобней писать тесты, а точнее ожидаемое поведение.

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/64

**Comment by EvilBeaver** [comment]
_Original comment by_ **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**:

---

Ты говоришь о приемочных тестах внутри солюшена Net/Студии или о приемочных тестах запуска скриптов через командную строку?

**Comment by dmpas** [comment]
@EvilBeaver эту закрыть, наверное, надо?

**Comment by artbear** [comment]
+1 за закрытие
