### ISSUE TITLE
Конструкторы структуры, соответствия, массива работают не быстро

### ISSUE THREAD

**Issue by vasvl123** [EvilBeaver/OneScript#643]
старт = ТекущаяУниверсальнаяДатаВМиллисекундах();
Для н = 1 по 1000000 Цикл
	с = Новый Структура();
КонецЦикла;
Сообщить(ТекущаяУниверсальнаяДатаВМиллисекундах()-старт);

результаты замеров:
1script: 9780.0137 ms
1c: 3 120 ms

**Comment by EvilBeaver** [comment]
А остальных классов - быстро? Или речь про все конструкторы?

**Comment by vasvl123** [comment]
```bsl
Для м = 1 по 20 Цикл
старт = ТекущаяУниверсальнаяДатаВМиллисекундах();
Для н = 1 по 100000 Цикл
	Если м = 1 Тогда
		с = Новый Массив();
	ИначеЕсли м = 2 Тогда
		с = Новый Структура();
	ИначеЕсли м = 3 Тогда
		с = Новый Соответствие();
	ИначеЕсли м = 4 Тогда
		с = Новый СписокЗначений();
	ИначеЕсли м = 5 Тогда
		с = Новый ТаблицаЗначений();
	ИначеЕсли м = 6 Тогда
		с = Новый ДеревоЗначений();
	ИначеЕсли м = 7 Тогда
		с = Новый ЗаписьZipФайла();
	ИначеЕсли м = 8 Тогда
		с = Новый ЧтениеZipФайла();
	ИначеЕсли м = 9 Тогда
		с = Новый ПотокВПамяти();
	ИначеЕсли м = 10 Тогда
		с = Новый Файл("c:\windows\win.ini");
	ИначеЕсли м = 11 Тогда
		с = Новый ГенераторСлучайныхЧисел ();
	ИначеЕсли м = 12 Тогда
		с = Новый ТекстовыйДокумент();
	ИначеЕсли м = 13 Тогда
		с = Новый ЧтениеТекста();
	ИначеЕсли м = 14 Тогда
		с = Новый ЗаписьТекста();
	ИначеЕсли м = 15 Тогда
		с = Новый ЧтениеXML();
	ИначеЕсли м = 16 Тогда
		с = Новый ЗаписьXML();
	ИначеЕсли м = 17 Тогда
		с = Новый ЧтениеJSON();
	ИначеЕсли м = 18 Тогда
		с = Новый ЗаписьJSON();
	ИначеЕсли м = 19 Тогда
		с = Новый ХешированиеДанных(ХешФункция.SHA256);
	ИначеЕсли м = 20 Тогда
		с = Новый ДвоичныеДанные("c:\windows\win.ini");
	КонецЕсли;
КонецЦикла;
Сообщить("" + м + ": " + (ТекущаяУниверсальнаяДатаВМиллисекундах()-старт));
КонецЦикла;
```

1script: 
1: 1039.0595
2: 1179.0675
3: 1138.0651
4: 1402.0802
5: 1845.1055
6: 1993.1140
7: 1617.0925
8: 1618.0926
9: 2464.1409
10: 1443.0826
11: 2575.1472
12: 1373.0785
13: 3121.1786
14: 2401.1374
15: 1511.0864
16: 1536.0879
17: 1657.0948
18: 1676.0958
19: 2341.1339
20: 6330.3621

1c:
1: 469
2: 582
3: 668
4: 746
5: 933
6: 960
7: 1 328
8: 1 352
9: 1 303
10: 2 202
11: 1 390
12: 1 619
13: 1 579
14: 1 761
15: 1 806
16: 2 011
17: 1 985
18: 2 073
19: 2 285
20: 6 497

Итого:

Конструктор | 1script | 1c | Медленнее
--|-|-|-
Массив | 1039,06 | 469 | 2,215478678
ДеревоЗначений | 1993,114 | 960 | 2,076160417
Структура | 1179,068 | 582 | 2,025889175
ТаблицаЗначений | 1845,106 | 933 | 1,977605038
ЧтениеТекста | 3121,179 | 1579 | 1,976680557
ПотокВПамяти | 2464,141 | 1303 | 1,891128856
СписокЗначений | 1402,08 | 746 | 1,879464075
ГенераторСлучайныхЧисел | 2575,147 | 1390 | 1,852623885
Соответствие | 1138,065 | 668 | 1,703690269
ЗаписьТекста | 2401,137 | 1761 | 1,363507893
ЗаписьZipФайла | 1617,093 | 1328 | 1,217690136
ЧтениеZipФайла | 1618,093 | 1352 | 1,196814053
ХешированиеДанных | 2341,134 | 2285 | 1,024566258
ДвоичныеДанные | 6330,362 | 6497 | 0,974351562
ТекстовыйДокумент | 1373,079 | 1619 | 0,848102841
ЧтениеXML | 1511,086 | 1806 | 0,836703433
ЧтениеJSON | 1657,095 | 1985 | 0,834808463
ЗаписьJSON | 1676,096 | 2073 | 0,808536324
ЗаписьXML | 1536,088 | 2011 | 0,763842815
Файл | 1443,083 | 2202 | 0,655350863

**Comment by EvilBeaver** [comment]
@vasvl123 спасибо огромное!!!

В конструкторах там есть куда оптимизировать, думаю сделаем.

**Comment by artbear** [comment]
@vasvl123 Отличное исследование, спасибо!

**Comment by vasvl123** [comment]
```bsl
м=0;
старт = ТекущаяУниверсальнаяДатаВМиллисекундах();
Для н = 1 по 10000 Цикл
	м=м+1;
КонецЦикла;
Сообщить((ТекущаяУниверсальнаяДатаВМиллисекундах()-старт));

м=0;
старт = ТекущаяУниверсальнаяДатаВМиллисекундах();
Для н = 1 по 10000 Цикл
	Выполнить("м=м+1;")
КонецЦикла;
Сообщить((ТекущаяУниверсальнаяДатаВМиллисекундах()-старт));
```
1c:
10
140

1script:
10.0000
575.0008

Тоже хотелось бы побыстрее)

**Comment by EvilBeaver** [comment]
"Выполнить" вряд-ли будет очень быстро работать. Если нужно вызвать произвольный метод, то лучше пользоваться рефлектором.

**Comment by vasvl123** [comment]
```bsl
// конструктор структуры
нач = ТекущаяУниверсальнаяДатаВМиллисекундах();
стр = Неопределено;
Для н = 1 по 100000 Цикл
	стр = Новый Структура("Соседний", стр);
КонецЦикла;
Сообщить(ТекущаяУниверсальнаяДатаВМиллисекундах()-нач);

нач = ТекущаяУниверсальнаяДатаВМиллисекундах();
Пока НЕ стр = Неопределено Цикл
	стр = стр.Соседний;
КонецЦикла;
Сообщить(ТекущаяУниверсальнаяДатаВМиллисекундах()-нач);
```

OneScript:
1972.0035
211.0003

1C:
210
90

Конструктор структуры работает почти в 10 раз медленнее чем в 1С

**Comment by EvilBeaver** [comment]
Оптимизация работы конструкторов начата на отдельной ветке. Из-за занятости на работе сейчас очень мало удается времени посвящать opensource

**Comment by vasvl123** [comment]
Ясно, спасибо. Тоже буду свой код оптимизировать.

**Comment by EvilBeaver** [comment]
Исправил ошибки в новом механизме и получил следующее:

Странность: радикально медленнее конструктор двоичных данных. Ушел изучать, что в нем изменилось.

Конструктор | 1script-1 | 1script-2 | 1c | Медленнее-1 | Медленнее-2
-- | -- | -- | -- | -- | --
Массив | 1039,06 | 302,00 | 469 | 2,215479744 | 0,643920043
ДеревоЗначений | 1993,114 | 355,00 | 960 | 2,076160417 | 0,369794688
Структура | 1179,068 | 376,00 | 582 | 2,025890034 | 0,64604433
ТаблицаЗначений | 1845,106 | 480,99 | 933 | 1,977605573 | 0,515534834
ЧтениеТекста | 3121,179 | 598,00 | 1579 | 1,976680811 | 0,378719063
ПотокВПамяти | 2464,141 | 544,00 | 1303 | 1,891128933 | 0,417496316
СписокЗначений | 1402,08 | 622,00 | 746 | 1,879463807 | 0,833778686
ГенераторСлучайныхЧисел | 2575,147 | 524,99 | 1390 | 1,852623741 | 0,377694101
Соответствие | 1138,065 | 612,99 | 668 | 1,70369012 | 0,917655988
ЗаписьТекста | 2401,137 | 563,00 | 1761 | 1,363507666 | 0,319704997
ЗаписьZipФайла | 1617,093 | 709,00 | 1328 | 1,217690512 | 0,533887048
ЧтениеZipФайла | 1618,093 | 593,00 | 1352 | 1,196814349 | 0,438607988
ХешированиеДанных | 2341,134 | 562,00 | 2285 | 1,024566302 | 0,245952298
ДвоичныеДанные | 6330,362 | 585,99 | 6497 | 0,974351547 | 0,090193997
ТекстовыйДокумент | 1373,079 | 624,99 | 1619 | 0,84810315 | 0,386036936
ЧтениеXML | 1511,086 | 651,01 | 1806 | 0,836703212 | 0,360468106
ЧтениеJSON | 1657,095 | 876,14 | 1985 | 0,834808564 | 0,441381914
ЗаписьJSON | 1676,096 | 735,00 | 2073 | 0,808536421 | 0,354560106
ЗаписьXML | 1536,088 | 1 149,00 | 2011 | 0,763842864 | 0,571357434
Файл | 1443,083 | 13 668,00 | 2202 | 0,655351045 | 6,207084242

**Comment by nixel2007** [comment]
Двоичных данных или файла? Файл вроде вырос в десять раз

**Comment by EvilBeaver** [comment]
@nixel2007 двоичных данных. Странно сползла таблица.

**Comment by EvilBeaver** [comment]
Хьюстон, у нас кажется проблема:

```
Старт = ТекущаяУниверсальнаяДатаВМиллисекундах();
Приостановить(1000);
Сообщить(ТекущаяУниверсальнаяДатаВМиллисекундах()-старт);
```

В 1С это целое число, а в 1Скрипт - дробное. Кажется, 1Скрипт неверно считает УниверсальнуюДатуВМиллисекундах

**Comment by EvilBeaver** [comment]
Актуальная и исправленная табличка.

N|Тип|Время 1.0.21|Время v1.1|Время 1С
-|-|-|-|-
1|Массив|1464.0072|386.9986| 146,00   
2|Структура|1491.9989|505.9926| 202,00   
3|Соответствие|1522.9932|519.9960| 211,00   
4|СписокЗначений|1610.9941|827.0067| 252,00   
5|ТаблицаЗначений|1781.9979|851.0013| 352,00   
6|ДеревоЗначений|1652.0049|956.9995| 301,00   
7|ЗаписьZipФайла|2122.9976|789.9991| 366,00   
8|ЧтениеZipФайла|2089.9982|886.9992| 365,00   
9|ПотокВПамяти|3018.0061|1201.9969| 458,00   
10|Файл|2054.0023|883.0068| 1465,00   
11|ГенераторСлучайныхЧисел|3470.9949|1429.9918| 388,00   
12|ТекстовыйДокумент|1654.9905|1237.0005| 729,00   
13|ЧтениеТекста|4418.0047|1020.9952| 460,00   
14|ЗаписьТекста|3449.9932|1054.0077| 536,00   
15|ЧтениеXML|1866.9806|1194.0055| 530,00   
16|ЗаписьXML|2446.9991|1508.0042| 729,00   
17|ЧтениеJSON|4308.0023|1448.9962| 575,00   
18|ЗаписьJSON|4810.0017|1481.0052| 598,00   
19|ХешированиеДанных|3564.0029|2070.9908| 852,00   
20|ДвоичныеДанные|25738.9960|15292.0025| 14386,00

**Comment by EvilBeaver** [comment]
Ускорение по сравнению с v1.0.21 достигнуто. 1С не догнали, но для выпуска версии 1.1 задачку считаю можно закрыть.
