### ISSUE TITLE
Ошибка получения файлов > 64Кб в режиме CGI

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#644]
В режиме CGI метод ```ВебЗапрос.ПолучитьТелоКакДвоичныеДанные() ``` возвращает двоичные данные правильной длины, но все, что больше 64Кб забивает нулями.

Проверено на docker-compose инфраструктуре. Если вместо os поставить другой бэкенд (например *.sh), то инфраструктура отрабатывает корректно, ошибка в движке.

**Comment by nixel2007** [comment]
А вот и виновник...

**Comment by artbear** [comment]
:)

**Comment by EvilBeaver** [comment]
Думаю в виду очевидной сложности применения режим CGI надо задепрекейтить в пользу HTTP-сервисов. @dmpas - что думаешь на этот счет?

**Comment by dmpas** [comment]
я всегда говорил, что CGI - отстой :) ЦГИ на свалку, HTTP - флаг в руки!!

**Comment by artbear** [comment]
Проголосовал за HTTP

**Comment by EvilBeaver** [comment]
@dmpas просто у тебя есть сервис, прячущий tool1cd и выгрузку хранилища...
