### ISSUE TITLE
HTTPСервисы предварительная загрузка os файлов как общих модулей

### ISSUE THREAD

**Issue by jdeshin** [EvilBeaver/OneScript#646]
Предлагаю в качестве экспериментальной возможности для ASPNetHandler следующее:
Для небольших проектов, а также библиотечных функций в текущем проекте, по аналогии с общими модулями 1С, в корне веб-приложения, создается папка, куда складываются библиотечные os файлы текущего проекта.
При создании экземпляра обработчика, производится загрузка этих файлов, как общих модулей. Имя общего модуля == имя файла os без расширения.
Например:

```
// Файл: МоиСтроковыеФункции.os

Функция МояСтроковаяФункция() Экспорт
    Возврат "ЧтоТоТам";
КонецФункции
```

будет загружен как общий модуль МоиСтроковыеФункции.

Из кода HTTPСервиса его можно использовать:

```
...
МойРезультат = МоиСтроковыеФункции.МояСтроковаяФункция();
...
```
Обращение осуществляется без использования директивы #использовать, что делает возможным Ctrl+C -> Ctrl+V из/в 1С. Конечно возможно параллельное использование #использовать и описанной возможности.
Путь к папке общих модулей устанавливается в web.config, в секции <appSettings>, установкой настройки:

```
<add key="commonModulesPath" value="~/scripts"/>
```
Предварительная сборка готова и опробована.

Собственно предлагаю обсудить :)

**Comment by nixel2007** [comment]
@jdeshin ты же знаешь, что `#использовать` умеет работать не только по имени библиотеки но и по пути? в том числе относительному? можно сделать `#использовать "./my_internal_lib"`, при этом штатным package-loader'ом будут загружены классы и модули

**Comment by dmpas** [comment]
@nixel2007  принципиальный вопрос в том, чтобы не писать "Использовать" вообще.

**Comment by jdeshin** [comment]
Ту два момента:
1. прозрачный Ctrl+C Ctrl-V из/в 1С. С #using надо вручную анализировать зависимости и вписывать #использовать. Соответственно при переносе в 1С - необходимо закомментировать эти директивы.
2. При использовании #использовать - процесс подгрузки в какой-то его части будет вызываться при каждом запросе к os файлу, что может сказаться на производительности приложения.
Еще раз обозначу, что речь идет об http сервисах

**Comment by EvilBeaver** [comment]
Если на уровень web.config вынести, то вроде как и не страшно. Вообще, идея "библиотек-по-умолчанию" уже как-то обсуждалась, но чем кончилась не помню.

**Comment by EvilBeaver** [comment]
@jdeshin это же выполнено? Закрываю?

**Comment by jdeshin** [comment]
Да, выполнено
