### ISSUE TITLE
XMLЗначение не читает ДвоичныеДанные

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#647]
После использования XMLСтрока на тип ДвоичныеДанные
Невозможно прочитать назад через XMLЗначение
```bsl
        Данные = Новый ДвоичныеДанные(ПутьКФайлу);
	СтрокаДанных = XMLСтрока(Данные);
	ЗначениеИЗСтроки = XMLЗначение(Тип("ДвоичныеДанные"), СтрокаДанных);
```
Выдает ошибку
`Неверное значение аргумента`

Прошу исправить, чтобы можно было паковать данные в текст и извлекать

**Comment by khorevaa** [comment]
/сс @dmpas @nixel2007 @EvilBeaver Поправьте. Нужно для разработки библиотеки

**Comment by EvilBeaver** [comment]
@khorevaa это исправлено же, да? Пулреквест от @ArchLord42RU влит.

**Comment by khorevaa** [comment]
Да исправлено.
