### ISSUE TITLE
Баг команды -make. Не доступны экспорные методы модулей

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#652]
Как воспроизвести:
oscript - нужен из ночника
1. `git clone https://github.com/silverbulleters/ovm.git` и `cd ovm`
2. `opm install`
3. `opm install cli@0.9.4`
4. `opm install fluent@0.3.1`
5. `oscript -make ./src/ovm.os  ovm.exe`
6. `ovm.exe --help`
  
![image](https://user-images.githubusercontent.com/2920817/34761276-2730d522-f5f4-11e7-9043-3dfa1d73e24a.png)

**Comment by artbear** [comment]
@khorevaa картинки же можно вставлять сразу в текст ишуза :) вместо ссылки
ЗЫ я твою картинку вставил

**Comment by artbear** [comment]
@khorevaa в ишузе п.6 запускает `--help`, а на картинке `i` :(
ошибка в обоих случаях воспроизводится?

**Comment by khorevaa** [comment]
Да что запускать не принципиально

**Comment by khorevaa** [comment]
Спасибо. За картинку

**Comment by nixel2007** [comment]
Смог сократить выброс исключения до модуля этой же библиотеки. 

git clone https://github.com/silverbulleters/ovm
cd ovm
opm install -l
oscript -make ./src/cmd/ovm.os ovm.exe
.\ovm.exe use 1.0.18

{Модуль ovm.exe / Ошибка в строке: 53 / Метод объекта не обнаружен (ВерсияУстановлена)}

ВерсияУстановлена - это экспортный метод модуля УстановленныеВерсииOneScript

**Comment by nixel2007** [comment]
@dmpas @EvilBeaver нужна ваша помочь. происходит что-то странное.

**Comment by nixel2007** [comment]
Возможно это связано с плавающей проблемой рефлектора, который периодически теряет экспортные методы

**Comment by nixel2007** [comment]
@EvilBeaver перенесу, чтобы не потерять.

Мне таня говорила

Nikita Gryzlov янв 11 23:15
По словам Лёши Серёга хочет работать как фрилансер, из дома. На много клиентов и немного на нас.
А по нашему опыты из этого жопа выходит. И его зовут в штат.
Сам с ним я не говорил, своих выводов не могу сказать.

Andrei Ovsiankin янв 11 23:16
Не сочти за лесть, мне очень нравится с тобой работать, продуктивно получается и комфортно. Поэтому хотелось бы, чтобы ты никуда не девался
Бля, теперь бы еще понять, как отладить собранный ovm.exe

Nikita Gryzlov янв 11 23:17
Взаимно, Андрюх 
Принтлны в стэндэлон раннер?
Прям в сорцы движка

Andrei Ovsiankin янв 11 23:18
ну вот как-то так придется сейчас изъебнуться
Короче, наебал ты меня с 10 минутами ))

Nikita Gryzlov янв 11 23:19
Я чо-то забыл, что проблема в самом ехе. Думал, получится подцепить отладяик к двтжку без особых проблем.
Если и наебал, то не со зла, а по недоумию)

Andrei Ovsiankin янв 11 23:19
сам exe ничего в себе не содержит. Проблема-то в движке, но он запакован внутрь exe

Nikita Gryzlov янв 11 23:20
Тогда почему запуск из обычного движка работает, а из мэйк - нет?
Алгоритм упаковки скриптов в одно место?
Причём проблема исключительно в модулях
Классы работают без ошибок

Andrei Ovsiankin янв 11 23:25
Дык не в курсе я ))
Смотрю

Andrei Ovsiankin 00:13
Кажется, вы с Хоревым нашли мегакосяк
перепроверяю

Andrei Ovsiankin 00:26
Короче, гипотеза, верная на 95%. Порядок загрузки модулей в обычном режиме и в режиме собранного exe отличается. И номера переменных, отвечающих за свойства глобального контекста перепутываются. Весь движок живет на том, что номер гл. переменной во время компиляции строго совпадает с номером гл. переменной во время выполнения
По сути, это адреса
В инициализации упакованного exe эти адреса почему-то кривые, но не везде, а только кое где.
В итоге у тебя для свойства УстановленныеВерсииOneScript на самом деле возвращается объект ФС
Можешь поприкалываться и вызвать у него вместо ВерсияУстановлена метод "ОбеспечитьПустойКаталог"

**Comment by nixel2007** [comment]
Andrei Ovsiankin 00:13
Кажется, вы с Хоревым нашли мегакосяк
перепроверяю

Andrei Ovsiankin 00:26
Короче, гипотеза, верная на 95%. Порядок загрузки модулей в обычном режиме и в режиме собранного exe отличается. И номера переменных, отвечающих за свойства глобального контекста перепутываются. Весь движок живет на том, что номер гл. переменной во время компиляции строго совпадает с номером гл. переменной во время выполнения
По сути, это адреса
В инициализации упакованного exe эти адреса почему-то кривые, но не везде, а только кое где.
В итоге у тебя для свойства УстановленныеВерсииOneScript на самом деле возвращается объект ФС
Можешь поприкалываться и вызвать у него вместо ВерсияУстановлена метод "ОбеспечитьПустойКаталог"

**Comment by dmpas** [comment]
У меня это сейчас не воспроизводится на девелопе под убунтой. Проблема есть ещё, отзовитесь?

**Comment by nixel2007** [comment]
@dmpas проблема еще есть, сейчас я тебе сделаю бранч, где она воспроизводится. в девелопе - костыли, чтобы работало

**Comment by nixel2007** [comment]
@dmpas глянь ветку fix/oscript-make.
К слову, под виндой оно у меня вообще сейчас не компилируется. Да и под линуксом (травис) лезут эксепшены

**Comment by dmpas** [comment]
@nixel2007 ткни ~~носом~~ ссылкой

**Comment by nixel2007** [comment]
https://travis-ci.org/silverbulleters/ovm/builds/348643969

**Comment by nixel2007** [comment]
в отличие от сценария в первом посте я делаю opm install -l

**Comment by dmpas** [comment]
вооо, на той ветке пошло мясо.

**Comment by nixel2007** [comment]
@dmpas есть успехи?

**Comment by dmpas** [comment]
@nixel2007 нет. ковыряюсь, там много...

**Comment by dmpas** [comment]
@nixel2007 https://github.com/EvilBeaver/OneScript/pull/730#issuecomment-370239966

**Comment by EvilBeaver** [comment]
@dmpas эту фичу закрывать?

**Comment by dmpas** [comment]
@EvilBeaver спроси лучше у @khorevaa

**Comment by khorevaa** [comment]
@EvilBeaver  @dmpas  Проверить пока не могу. Но судя по комментариям @nixel2007 - Работает. Предлагаю закрыть.
Благодарность @dmpas
