### ISSUE TITLE
Сделать единое описание изменений движка

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#653]
Сейчас у нас есть различные страницы описания изменений движка на офиц.сайте.
Например, http://oscript.io/downloads/archive/1_0_17 или http://oscript.io/downloads/archive/1_0_19

А в другой документации у нас также не все есть.

И на гитхабе. в релизах, у нас есть не все.
  + Например, 19 релиз на гитхабе так и не документирован до сих пор, оказывается :(
  + есть различия в описания релиза на гитхабе и на сайте oscript.io

В итоге выполнять поиск новых изменений и хоть какой-то документации по ним не удобно!
Сегодня в очередной раз в этом убедился

Предлагаю сделать единое описание изменений движка, некий changelog

/cc @EvilBeaver @dmpas @nixel2007 @kuntashov @khorevaa

**Comment by nixel2007** [comment]
в целом страница релизов на гитхабе довольно удобная. надо просто перенести с сайта

**Comment by nixel2007** [comment]
лови 
  https://github.com/EvilBeaver/OneScript/releases/tag/v1.0.19
