### ISSUE TITLE
Где документировано перечисление `СистемнаяПапка` и в каком релизе оно появилось?

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#654]
https://github.com/EvilBeaver/OneScript/blob/4fa0ae6d93e4ab876dd71615e482f44917c6b94b/src/ScriptEngine.HostedScript/Library/SpecialFolderEnum.cs#L18

**Comment by dmpas** [comment]
https://github.com/EvilBeaver/OneScript/commit/f741c851b04d23040de294b440732c19965d435f#diff-cf0cff03359cc73328193b50040a077c

судя по всему, уже в 17-м это было.
спроси @ret-Phoenix

**Comment by artbear** [comment]
@bambr1975 Интересно, а в СП из VSC есть инфа об этом перечислении?

**Comment by nixel2007** [comment]
@artbear а посмотреть?)

**Comment by bambr1975** [comment]
Раздел Системные перечисления я заполняю вручную, то есть, если системное перечисление не обнаруживается документером (а таких много), я его информацию добавляю вручную и делаю это глобальным поиском по слову SystemEnum в исходниках OneScript. В последний раз это видимо было ранее 17-го релиза

**Comment by EvilBeaver** [comment]
@bambr1975 надо просто документер допилить, чтобы перечисления обнаруживал

**Comment by bambr1975** [comment]
https://github.com/EvilBeaver/OneScriptDocumenter/blob/master/OneScriptDocumenter/AssemblyLoader.cs#L51-L54
https://github.com/EvilBeaver/OneScriptDocumenter/blob/master/OneScriptDocumenter/AssemblyLoader.cs#L103-L110
но остальные-то SystemEnum у меня находятся - почему с этим проблема?

**Comment by ret-Phoenix** [comment]
https://github.com/EvilBeaver/OneScript/blob/4fa0ae6d93e4ab876dd71615e482f44917c6b94b/src/ScriptEngine.HostedScript/Library/SpecialFolderEnum.cs#L19

надо объявить как public и будет видно.

**Comment by bambr1975** [comment]
![default](https://user-images.githubusercontent.com/9781644/44312845-396d7080-a407-11e8-9b45-dcee6556600f.png)
было вручную добавлено в СП 01.10.2017, в рамках глобального перехода на новый формат СП. https://github.com/1c-syntax/vsc-language-1c-bsl/blob/3c480a71ab22aad6e2aded4fd812950731cd6932/src/features/oscriptStdLib.json
До этого в СП действительно не было, но в момент создания задачи уже было. Задачу можно закрывать

**Comment by EvilBeaver** [comment]
Спасибо!
