### ISSUE TITLE
Ошибка загрузки библиотеки

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#656]
Вот такая вот не задача. Не хочет находить библиотеку.. Что делать хз

`#Использовать "../../../plugins"` - когда вот так длинно

![default](https://user-images.githubusercontent.com/665525/34830758-efd559d8-f6f5-11e7-855e-ec509149a39a.png)

**Comment by artbear** [comment]
+ Включи переменную окружения 
`set OSLIB_LOADER_TRACE=1`
+ и выполнить `oscript твой файл`
+ проверь лог - какие пути подставляются?

**Comment by artbear** [comment]
Если релиз движка какой - 19 или 20

**Comment by artbear** [comment]
Ну и что у тебя в `plugins/package-loader.os` ?

**Comment by khorevaa** [comment]
Забил на данный вопрос. Передалал просто на отдельный класс
