### ISSUE TITLE
Работа с переменными окружения

### ISSUE THREAD

**Issue by LexaSH** [EvilBeaver/OneScript#657]
УстановитьПеременнуюСреды() позволяет установить в качестве значения переменной любой тип данных, а ПолучитьПеременнуюСреды() возвращает всегда строку. Это так надо или случайно вышло?

**Comment by nixel2007** [comment]
Все переменные среды хранятся в строковом виде. В СП на УстановитьПеременнуюСреды указано, что значение имеет строковый тип. Возможность передачи туда не строки - что-то среднее между багом и фичей.

**Comment by LexaSH** [comment]
В СП про строку сказано только в ПолучитьПеременнуюСреды, что я благополучно заметил только после того, как попытался прочитать данные из массива, который до этого поместил в переменную.

А в целом, хранение только строк в переменных окружения явно недостаточно. Есть возможность доработать данный функционал?

**Comment by nixel2007** [comment]
@LexaSH извиняюсь, я за дефолтный СП уже считаю СП в VSCode - там выводится информация по типам переменных.

Доработать хранение других типов данных в переменных среды не получится - это функциональность операционной системы, движок не делает и не может делать с ней никакой магии.

**Comment by nixel2007** [comment]
@LexaSH ну и классический вопрос. Какую проблему вы решаете? Может можно обойтись и без переменных среды? А обычными переменными в классах и модулях.

**Comment by LexaSH** [comment]
Нужна была глобальная переменная, где я мог бы хранить сессии пользователей. Заглянул в СП,   увидел работу с переменными окружения и посчитал, что мне это подойдет.

**Comment by nixel2007** [comment]
Возможно подойдёт следующий вариант. Он не является классическим в разработке OneScript, нарушает некоторые принципы и блаблабла, но работает.

Решение - объявить в "модуле" экспортную переменную и сохранить нужное значение туда. Дело в том, что в OneScript модули (в отличие от классов) инициализируются один раз при первом обращении (аналогично с 1с). Но, в отличие от 1с, модули могут иметь переменные, объявленные в заголовке модуля.

Соответственно, если файл os будет определяться как модуль (лежать в корректном каталоге или явно объявлен в lib.config), то он может выступать глобальным хранилищем данных.

**Comment by nixel2007** [comment]
И соответственно при доступе к этому модулю из других классов и модулей, сохраненное значение можно будет достать без проблем.

**Comment by LexaSH** [comment]
Спасибо, помогло.

**Comment by EvilBeaver** [comment]
Хранить в переменных окружения не-строки не получится, ибо они хранятся средствами операционной системы, и там они могут быть только строковыми.
