### ISSUE TITLE
Рефлексия в типы CLR не учитывает возможность т.н. OwnMethods

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#660]
Рефлексия в типы CLR не учитывает возможность т.н. OwnMethods, когда в скриптовом модуле вызываются методы самого объекта.

В результате ReflectEngine присваивает экземплярам ReflectedMethodInfo номера, которые не учитывают наличие методов "родительского" класса. Это приводит к тому, что dispId становится неверным (указывает на другой метод).

Нужно пронумеровывать идентификаторы рефлексируемых методов с учетом "смещения" по количеству собственных методов. Со свойствами аналогично.

**Comment by khorevaa** [comment]
@EvilBeaver А когда будет в ночнике? )

**Comment by EvilBeaver** [comment]
Нууу... когда будет исправлено, тогда и будет в ночнике. А вам зачем, собсна? Это внутренний механизм ведь.

**Comment by khorevaa** [comment]
@EvilBeaver А разве это не связано с запаковкой в exe?

**Comment by EvilBeaver** [comment]
@khorevaa нет.
