### ISSUE TITLE
Текст исключения `Тип не поддерживает преобразование в CLR-объект`

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#662]
Если пробросить в, например, `Сообщить` вторым параметром само системное перечисление `СтатусСообщения` (без указания конкретного уровня), вызывается исключение `Тип не поддерживает преобразование в CLR-объект`.

Судя по тексту, оно похоже на исключение движка.

Вопрос - можно ли сделать его "более понятным"? Или по контексту в момент выброса все равно не понятно, что хотел данным кодом сказать программист?

**Comment by EvilBeaver** [comment]
Можно сделать более понятное, в рамках эпика по упрощения встраивания в другие проекты будет сделано. Но исключение все равно будет. Просто другое.
