### ISSUE TITLE
Простой тест команды -make - 1 скрипт с вызовом 1го модуля, make, вызов скрипта

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#665]
Нужен простой тест команды -make - 1 скрипт с вызовом 1го модуля, make, вызов скрипта

Связано с #652

**Comment by EvilBeaver** [comment]
Смею ли я надеяться на пулреквест?

**Comment by EvilBeaver** [comment]
Закрываю за невостребованностью
