### ISSUE TITLE
Установка oscript в каталог пользователя

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#666]
На текущий момент на linux - oscript устанавливаеться s /usr/share/oscript
Туда необходим доступ sudo

Предалагаю сделать  ключ или флаг установки в каталог пользователя `~/.local/share/` чтобы не просило администраторские права

**Comment by nixel2007** [comment]
может это решить в рамках ovm? :)

**Comment by pumbaEO** [comment]
Нет rpm и deb будет /user/share , а вот все что opm ставит, тут можно было-бы параметр -u (--user)и тогда ставить в каталог пользователя.

**Comment by khorevaa** [comment]
ovm решит проблему ))
Но хотелось бы по дефолту, чтобы хотябы либы ставилсь в пользовательский каталог - без требования адмнистраторских прав..

Допустить я хочу установить proxy сервер для opm - надо вызывать sudo... что не есть хорошо. Хотя если убить от туда .cfg то можно будет и без sudo

**Comment by pumbaEO** [comment]
А если ты его в ~/.opm.cfg положишь, то будет оттуда брать.

**Comment by EvilBeaver** [comment]
Закрываю, т.к. появился ovm. Кстати, на каталог lib вполне можно выдать самому себе права и не будет требовать админские
