### ISSUE TITLE
Версия 1.0.10 в имени бинаря содержит лишний постфикс

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#668]

**Comment by dmpas** [comment]
в топку 1.0.10.

**Comment by EvilBeaver** [comment]
Не думаю, что кто-то расстроится, если ovm не сможет поставить 1.0.10

**Comment by nixel2007** [comment]
@EvilBeaver ovm сможет поставить 1.0.10. Я нашел секретный линк /zip. Он даже с 10 работает корректно.

**Comment by pumbaEO** [comment]
Удалить линк и нет проблемы.

**Comment by EvilBeaver** [comment]
@nixel2007 более того, этот линк специально делался для всяких автоматических утилит. И он не секретный, я тебе его в скайп сбрасывал.

**Comment by nixel2007** [comment]
@EvilBeaver ты его скидывал для night-build :) не думал, что он и для версий работает.

**Comment by EvilBeaver** [comment]
@nixel2007 Все просто. night-build - это тоже версия. И latest тоже версия.

Схема такая /downloads/<версия>/zip|exe|msi (про deb и rpm не уверен)

Версия может быть latest,night-build,или трехзначный номер, но вместо точек - подчеркивания (1_0_17)
