### ISSUE TITLE
Запуск скомпилированного exe из под mono приводит к ошибке

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#669]
Сабж.

```
PS D:\git\silverbulleters\ovm> oscript -version
1.0.20.134
PS D:\git\silverbulleters\ovm> oscript -make src\cmd\ovm.os ovm.exe
Make started...
Make completed
PS D:\git\silverbulleters\ovm> bash
ngryzlov@DESKTOP-TT43R45:/mnt/d/git/silverbulleters/ovm$ mono ovm.exe

Unhandled Exception:
System.TypeLoadException: Could not load file or assembly 'ScriptEngine.HostedScript, Version=1.0.20.134, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:ScriptEngine.HostedScript, Version=1.0.20.134, Culture=neutral, PublicKeyToken=null type:<unknown type> member:<none>
  at StandaloneRunner.Program.Main (System.String[] args) [0x00016] in <70f09c2e556d4b0fb9d406fdadefeb45>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load file or assembly 'ScriptEngine.HostedScript, Version=1.0.20.134, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:ScriptEngine.HostedScript, Version=1.0.20.134, Culture=neutral, PublicKeyToken=null type:<unknown type> member:<none>
  at StandaloneRunner.Program.Main (System.String[] args) [0x00016] in <70f09c2e556d4b0fb9d406fdadefeb45>:0
ngryzlov@DESKTOP-TT43R45:/mnt/d/git/silverbulleters/ovm$ mono --version
Mono JIT compiler version 5.4.1.6 (tarball Wed Nov  8 20:37:08 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

**Comment by dmpas** [comment]
гы, на руками собранном движке такого не возникает, потому я не нарывался на это.
Вот скачал ночник, запустил `-make` под виндой, закинул на убунту - упало с ошибкой.

**Comment by dmpas** [comment]
Если руками собирать под Release, то тоже падает. Видимо,  косяк где-то в условиях сборки.

**Comment by dmpas** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=60100

**Comment by nixel2007** [comment]
ЕОСПННР
А обойти не-вызов этой процедуры можно? Может быть как-то явно не вызвать из /инициализатора класса?

**Comment by dmpas** [comment]
@nixel2007 пробую. Но чо-то хрень какая-то. Из DLL грузит, из ресурса ту же DLL грузит, но не учитывает.

**Comment by dmpas** [comment]
вот в Debug-режиме этот обработчик вызывается. в Release - нет. WTF?!

**Comment by EvilBeaver** [comment]
Кажыца, пора спрашивать в Mono

**Comment by dmpas** [comment]
> Кажыца, пора спрашивать в Mono

два часа вчера исходники ковырял, так и не пойму, в чём разница.

**Comment by EvilBeaver** [comment]
Может хитромудрая оптимизация компилятора какая - вырезает его, а?

**Comment by EvilBeaver** [comment]
Если разница между дебаг и релизом, и нет явных директив препроцессора в округе, то вроде больше ничего другого не может влиять

**Comment by dmpas** [comment]
дебаг и релиз касаются только движка. Моно один и тот же в обоих случаях.

**Comment by dmpas** [comment]
@EvilBeaver ты оказался прав насчёт оптимизаций: https://social.msdn.microsoft.com/Forums/vstudio/en-US/669215f7-fcdb-4345-8d9d-d399e3d139dc/assemblyresolve-event-not-firing-when-using-a-release-build?forum=netfxbcl
