### ISSUE TITLE
Поддержка длинных путей

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#67]
Originally reported by: **EvilBeaver (Bitbucket: [EvilBeaver](http://bitbucket.org/EvilBeaver), GitHub: [EvilBeaver](http://github.com/EvilBeaver))**

---

.NET на Windows не поддерживает обработку путей, превышающих величину MAX_PATH (260 символов). При выполнении файловых операций с длинными именами файлов выдается ошибка.

1С при работе с длинными путями умеет их корректно обрабатывать, используя расширенный режим работы с путями (http://blogs.msdn.com/b/bclteam/archive/2007/02/13/long-paths-in-net-part-1-of-3-kim-hamilton.aspx).

Необходимо внедрить поддержку длинных путей, например вот отсюда:

http://bcl.codeplex.com/releases/view/42783

На Linux такого ограничения нет (на ext3 и ext4 точно), там данное расширение использовать не надо.

Проблема проявляется в классе Файл, которому передается длинный путь.

В качестве обхода можно использовать в алгоритмах более короткие пути, т.к. 260 символов - это, действительно, много.

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/67

**Comment by dmpas** [comment]
Говорят, в .net core длинные пути из коробки работают. Сам я не проверял.

**Comment by artbear** [comment]
В #691 подробно описан прикладной пример и возникающая ошибка

**Comment by git22ura** [comment]
Коллеги, на сколько понимаю, проблема осталась не решенной. Предложите пути обхода, если можете. Разбирается конфигурация Управление холдингом, где присутствует стандартная подсистема вида:
Подсистема.БухгалтерияПредприятияПодсистемы.Подсистема.ИнтеграцияСВнешнимиСистемами.Подсистема.ТранспортИнтернетПоддержкаПользователей.Подсистема.ТранспортИнтернетПоддержкаПользователейРасширенныйФункционал\ТранспортИнтернетПоддержкаПользователейРасширенныйФункционал.xml
```
07:29:11 ИНФОРМАЦИЯ - Раскладываем модули по папкам согласно иерархии метаданных
07:29:11 ПРЕДУПРЕЖДЕНИЕ - Попытка удаления C:\Users\gitsyncbot\AppData\Local\Temp\g5nh4x1q.rgl.tmp закончилась неудачей, по причине {Модуль C:\OneScript_portable\1.0.18\lib\tempfiles\ВременныеФайлы.os / Ошибка в строке: 74 / Внешнее исключение (System.IO.DirectoryNotFoundException): Не удалось найти часть пути "ТранспортИнтернетПоддержкаПользователейРасширенныйФункционал.xml".}
07:29:11 КРИТИЧНАЯОШИБКА - {Модуль C:\OneScript_portable\1.0.18\lib\gitsync\src\core\Классы\МенеджерСинхронизации.os / Ошибка в строке: 191 / Внешнее исключение (System.IO.PathTooLongException): Слишком длинный путь или имя файла. Полное имя файла должно содержать меньше 260 знаков, а имя каталога - меньше 248 знаков.}

```
Установка windows 10, и включение режима [Enable win32 long path](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/) не спасает ситуацию.
Спасибо.

**Comment by EvilBeaver** [comment]
@dmpas да, работают. Только вот .net core не стоит из коробке на большинстве виндов ((

**Comment by theshadowco** [comment]
@EvilBeaver 

Так надо в инсталлятор включить :)

**Comment by EvilBeaver** [comment]
@git22ura обходы проблемы 

- вынести корень рабочего каталога на временный диск через subst
- использовать старый гитсинк, который умел переименовывать длинные файлы (@khorevaa, сейчас в GS 3.0 же это отключили, верно?)
- Наконец реализовать данную задачу #67

**Comment by thedemoncat** [comment]
@EvilBeaver @allustin Эта же проблема возникает при гитсинке БП

Возможно полезная ссылка https://gallery.technet.microsoft.com/DelimonWin32IO-Library-V40-7ff6b16c

**Comment by EvilBeaver** [comment]
Решается переходом на core
