### ISSUE TITLE
COMОбъект ADODB.Connection и в 19 версии тоже НЕ работает

### ISSUE THREAD

**Issue by CT144** [EvilBeaver/OneScript#670]
в продолжение #559
ОТЛАДКА -  Начали (OneScript v.1.0.17.90) ...
ОТЛАДКА -
_Строка соединения="Provider=SQLOLEDB; Data Source="SQL"; Initial Catalog="debug_Р2"; User Id="sss"; Password="1";"
Соединение = Новый COMОбъект("ADODB.Connection");
Соединение.Open(_СтрокаСоединения);

ОТЛАДКА - Соединились
ОТЛАДКА - . . . . . ЗАКОНЧИЛИ

ОТЛАДКА -  Начали (OneScript v.1.0.19.105) ...
ОТЛАДКА -
_Строка соединения="Provider=SQLOLEDB; Data Source="SQL"; Initial Catalog="debug_Р2"; User Id="sss"; Password="1";"
Соединение = Новый COMОбъект("ADODB.Connection");
Соединение.Open(_СтрокаСоединения);

{Модуль Z:\src\дляРазработки.os / Ошибка в строке: 197 / НЕ удалось установить соединение с БД:Provider=SQLOLEDB; Data Source="SQL"; Initial Catalog="debug_Р2"; User Id="sss"; Password="1";}
Процесс терминала завершен с кодом выхода: 1

**Comment by nixel2007** [comment]
Кавычки в строках точно нормально экранируются?

**Comment by EvilBeaver** [comment]
А где можно получить сам скрипт, которым проверяется?

**Comment by CT144** [comment]
Ничего не менял в скрипте, а менял только OneScript.
Сам скрипт (в нем нужно установить свои параметры с строке соединения):
#Использовать logos

Лог = Логирование.ПолучитьЛог("СТ.Отладка.протокол");
Лог.УстановитьУровень(УровниЛога.Отладка);
ФайлЖурнала = Новый ВыводЛогаВФайл;
ФайлЖурнала.ОткрытьФайл("ЖурналРазработки.log");
Лог.ДобавитьСпособВывода(ФайлЖурнала);
Лог.ДобавитьСпособВывода(Новый ВыводЛогаВКонсоль);


СисИнфо = новый СистемнаяИнформация();
Лог.Отладка(" Начали (OneScript v."+СисИнфо.Версия+") ...");

Соединение = Новый COMОбъект("ADODB.Connection");
 _СтрокаСоединения = "Provider=SQLOLEDB; Data Source=""SQL""; Initial Catalog=""debug_Р2""; User Id=""sss""; Password=""1"";";
Попытка
	Соединение.Open(_СтрокаСоединения);
	Результат = Истина;
Исключение
	Результат = Ложь;
	ВызватьИсключение("НЕ удалось установить соединение с БД:"+ _СтрокаСоединения);
КонецПопытки;
Лог.Отладка("Соединились");

Лог.Отладка(". . . . . ЗАКОНЧИЛИ");
Лог.Закрыть();

**Comment by EvilBeaver** [comment]
Ок, спасибо. Будем смотреть

**Comment by dvakor** [comment]
Странно на билде из дев ветки и на последнем релизе все работает хорошо под win 10, на серваке с win 2012r2 не пашет
![win 10 - dev](https://user-images.githubusercontent.com/4038422/36436154-223e92c6-1696-11e8-97fb-69f79e84d7a0.png)
![win 10 - release](https://user-images.githubusercontent.com/4038422/36436157-2531f9fa-1696-11e8-8289-e061b679ab9e.png)
![win 2012 r2](https://user-images.githubusercontent.com/4038422/36436221-4249c0ae-1696-11e8-8e6a-8312aa026133.png)

**Comment by nixel2007** [comment]
Версия .Net Framework какая? Нужна минимум 4.5.2

**Comment by dvakor** [comment]
4.7 и там и там

**Comment by dvakor** [comment]
Подключился удаленным дебаггером к машине на которой падает и кое что узнал, но пока не особо понял с чем это связано:
Валится все внутри CallAsProcedure при попытки инвока метода, собственно на машине где все ок и на сервере вызываются 2 разных метода (из разных классов - контекстов)
Где все ок, вызывается из **UnmanagedRCWComContext**, где падает вызывается из **ManagedCOMWrapperContext**, судя по всему не верно определяется контекст ком объекта (managed \ unmanaged).

вот тут расходятся "пути"
https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine/Machine/MachineInstance.cs#L1042

Времени пока нету дальше покопать, завтра продолжу :)

**Update**

я был в шаге от понимания.

type = Type.GetTypeFromProgID(progId, throwOnError: false);

Возврашает 2 разных типа, на тестируемых машинах.
Где все ок возвращается System.__ComObject
Где была проблема System.RuntimeType с бейс классом System.__ComObject

позже сделаю ПР
