### ISSUE TITLE
Синтаксис тернарного оператора. Совместимость с 1С.

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#671]
OneScript ругается на такой код:
```bsl
x = ?(true, new array, null).count();
```
но это корректный код на языке 1С.

**Comment by EvilBeaver** [comment]
Спасибо

**Comment by artbear** [comment]
У 1С весело реализовано.
Код выше работает.
А вот код 
+ `Икс = ( Новый Массив ).Количество();` или 
+ `Икс = ( Новый Массив() ).Количество();`

выдает ошибки :)

**Comment by nixel2007** [comment]
потому что в 1С запрещено инлайн обращение к объектам, созданным конструктором Новый

**Comment by realMaxA** [comment]
> код
> 
> Икс = ( Новый Массив ).Количество(); или
> Икс = ( Новый Массив() ).Количество();
> выдает ошибки :)

А оскрипт работает

И так тоже (инлайн не при чём):

```
a = Новый массив;
Сообщить(( a ).Количество());
```

**Comment by nixel2007** [comment]
емнип, @EvilBeaver рассказывал, что это было сделано случайно, а потом не стали откатывать, потому что разошлось по библиотекам. всякие там Новый Файл().Существует()

**Comment by artbear** [comment]
`Новый Файл().Существует()` да, это очень удобно.

**Comment by tsukanov-as** [comment]
Только синтаксис странный. Я понимаю еще `(Новый Файл).Существует()`

**Comment by perfolenta** [comment]
нормальный синтаксис... ключевое слово Новый смело можно считать унарной операцией... как унарный минус...

**Comment by tsukanov-as** [comment]
Эмм, ну унарная операция (минус) будет работать так `- (Файл().Существует())`
Я как-то привык что она жадно работает ))
Почему она (операция Новый) только к файлу относится то?

Другими словами приоритет точки выше любых других операций.

**Comment by perfolenta** [comment]
с точки зрения унарного минуса вы конечно правы, но это же предмет договоренностей.... у нас будет унарный Новый, который имеет приоритет выше точки... просто исходя из практического смысла... новый ведь нельзя применить к результату выражения, только к типу прочитанному во время компиляции... другое дело когда тип написан через точку, но в 1С так не бывает вроде...

**Comment by tsukanov-as** [comment]
А кто с кем договаривался? )))

**Comment by perfolenta** [comment]
я в договоренностях не участвовал, но судя из комментариев выше "емнип, @EvilBeaver рассказывал, что это было сделано случайно, а потом не стали откатывать, потому что разошлось по библиотекам"..  можно понять, что кто-то с кем-то поговорил и решили....
