### ISSUE TITLE
Реализация массивов. Эффективность приращения

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#672]
На волне #643 

```bsl
array = new array;
start = CurrentUniversalDateInMilliseconds();
for i = 1 to 10000000 do
	array.add(1);
enddo;
message(CurrentUniversalDateInMilliseconds() - start);
```
oscript - 14438.5199
1c - 807

В 1С приращение массива скорее всего реализовано классически через удваивание и реаллокацию (ну или вариация на тему).
А в oscript я так понимаю у вас List аллоцирует по одному элементу на вызов

ps Грубо говоря, в 1С массив - это именно массив, а не список.

**Comment by nixel2007** [comment]
В джава лист реаллоцируется с коэффициентом 0.75. В шарпе разве не так же?

**Comment by dmpas** [comment]
теоретически, в .net тоже удваивается ёмкость. Во всяком случае, про Queue нашёл такую информацию, про List пока нет.

**Comment by tsukanov-as** [comment]
А еще может быть сборщик мусора запускается не кстати там.

**Comment by dmpas** [comment]
на мой взгляд, это очень маловероятно.

**Comment by nixel2007** [comment]
@dmpas судя по исходникам - действительно, расширение идет на х2
http://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs,407

**Comment by tsukanov-as** [comment]
Хм, действительно. Ну это гипотеза была. Надо в профайлер смотреть конечно.

**Comment by perfolenta** [comment]
Странно... я запустил на 1Скрипт версии 19 и на 1с версии 8.3.11.2867
и у меня 1скрипт быстрее считает...
1ССкрипт:  9704 мс
1С: 36536 мс
как у вас 1с за 807 мс посчитала ума не приложу... 
На компилируемом языке с объектом List получилось 1375... т.е. сам объект лист не виноват...

**Comment by tsukanov-as** [comment]
Хм. Сейчас на другой машине запустил
1С - 6771
oscript - 9586

А 1С у вас чет слишком много. Отладка поди включена

зы Но результат 807 действительно странный. Может я напутал чего. Позже проверю опять в тех же условиях

**Comment by tsukanov-as** [comment]
А ну судя по порядку чисел я запускал на 1с без двух нулей.
Хз как так получилось. То ли кэш 1с, то ли мой кэш...

Ведь переоткрывал обработку дважды, чтобы убедиться :(

**Comment by perfolenta** [comment]
да, вы правы... отладку то я и забыл выключить... без отладки в 1с у меня 7407 получилось...

**Comment by tsukanov-as** [comment]
В общем перепроверил на той же машине и обработке:
1С - 9457
oscript - 10228.3228
радиус кривизны моих рук - 807

Выстрел холостой короче был.
