### ISSUE TITLE
Структуры. Совместимость с 1С

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#674]
Работает в 1С, но не работает в oscript:

```bsl
struct = new structure("one,,,,,two", 1, 2);
```

```bsl
struct = new structure("one,two", 1, 2, 3, 4, 5);
```

```bsl
struct.insert(" one", 1);
```

**Comment by tsukanov-as** [comment]
В догонку. Не работает в 1С, но работает в OneScript:
```bsl
 s = new structure;
 message(s.property("1sdf"));
```

Тест ошибки:
`Задано неправильное имя атрибута структуры`

**Comment by EvilBeaver** [comment]
почему не работает в 1С?? Что говорит?

**Comment by nixel2007** [comment]
Свойство() же булево возвращает. как оно может не работать?

**Comment by EvilBeaver** [comment]
Может по английски называется иначе? (гипотеза)

**Comment by tsukanov-as** [comment]
@EvilBeaver В 1С ругается на неправильный ключ

**Comment by nixel2007** [comment]
@tsukanov-as Вообще было бы здорово, если ты будешь тексты точные эксепшенов сразу сразу прикладывать. как 1сных, так и односкриптовых

**Comment by tsukanov-as** [comment]
@nixel2007 Добавил

**Comment by EvilBeaver** [comment]
>  В 1С ругается на неправильный ключ

~~@tsukanov-as а если на русском - то не ругается? Просто проверять методом Свойство несуществующие ключи, это вроде как нормально, разве нет?~~

А, пардон, не заметил, что строка с числа начинается.
