### ISSUE TITLE
StrStartsWith() не работает (Неизвестный символ)

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#675]
сабж
https://github.com/EvilBeaver/OneScript/blob/7e84f4d5c51a350679a0e8b1b4c07d8d875a4234/src/ScriptEngine.HostedScript/Library/StringOperations.cs#L52

**Comment by tsukanov-as** [comment]
Это вроде менялось в какой-то версии платформы

**Comment by nixel2007** [comment]
@tsukanov-as имя функции депрекейтед?

**Comment by tsukanov-as** [comment]
@nixel2007 ну типа того получается. Не знаю как тут принято, косить или помечать

StrStartWith ЕМНИП было в 8.3.9 а потом изменилось в 8.3.10 (но это не точно)

**Comment by nixel2007** [comment]
@tsukanov-as сам механизм депрекейтедов есть.
