### ISSUE TITLE
HTTPЗапрос.УстановитьТелоИзСтроки не хватает параметра ИспользоватьBOM

### ISSUE THREAD

**Issue by vbondarevsky** [EvilBeaver/OneScript#677]
HTTPЗапрос.УстановитьТелоИзСтроки(<ТелоКакСтрока>, <Кодировка>, <**ИспользоватьBOM**>) 

**ИспользованиеByteOrderMark (ByteOrderMarkUsage)**
Значения:
- Авто (Auto)
- Использовать (Use)
- НеИспользовать (DontUse)

Описание:
Содержит варианты использования метки порядка байтов ( от англ. Byte Order Mark (BOM)) при кодировании строк.

**Comment by nixel2007** [comment]
если честно, судя по исходникам даже параметр Кодировка не особо-то и учитывается.
