### ISSUE TITLE
Внешнее исключение (System.ArgumentException): С этим свойством нельзя задавать Keep-Alive и Close

### ISSUE THREAD

**Issue by vbondarevsky** [EvilBeaver/OneScript#678]
{Ошибка в строке: 8 / Внешнее исключение (System.ArgumentException): С этим свойством нельзя задавать Keep-Alive и Close.
Имя параметра: value}    
Ответ = Соединение.Получить(Запрос);

```bsl
Заголовки = Новый Соответствие;
Заголовки.Вставить("Connection", "keep-alive");

Соединение = Новый HTTPСоединение("http://ya.ru/", 80);

Запрос = Новый HTTPЗапрос("/", Заголовки);

Ответ = Соединение.Получить(Запрос);
```

**Comment by EvilBeaver** [comment]
Спасибо

**Comment by EvilBeaver** [comment]
@vbondarevsky а может ты уже в код смотрел и знаешь где и что починить?

**Comment by vbondarevsky** [comment]
@EvilBeaver неа, не смотрел. Было влом)

**Comment by EvilBeaver** [comment]
А есть шанс, что не влом будет посмотреть?
