### ISSUE TITLE
Добавить цвета для возможности цветного вывода в консоль

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#68]
Originally reported by: **artbear (Bitbucket: [artbear](http://bitbucket.org/artbear), GitHub: [artbear](http://github.com/artbear))**

---

---
- Bitbucket: https://bitbucket.org/EvilBeaver/1script/issue/68

**Comment by artbear** [comment]
@EvilBeaver Дай пример использования цветов в консоли
Что-то не получается заюзать

**Comment by EvilBeaver** [comment]
Два способа. 
Первый:

```
Сообщить(Тест, СтатусСообщения.Информация);
Сообщить(Тест, СтатусСообщения.Важное);
```

Второй:

```
Консоль = Новый Консоль;
Консоль.ЦветТекста = ЦветКонсоли.Красный;
```
