### ISSUE TITLE
Вопрос. Каким образом можно передать параметр в создаваемый экземпляр класса?

### ISSUE THREAD

**Issue by LexaSH** [EvilBeaver/OneScript#682]
Возможно ли проделать следующее:

МояПеременная = "йцукен";

Экземпляр = Новый МойКласс(МояПеременная);

**Comment by artbear** [comment]
если в модуле класса есть конструктор `ПриСозданииОбъекта(Парам)`

**Comment by LexaSH** [comment]
Спасибо. Самостоятельно не смог найти.

**Comment by EvilBeaver** [comment]
@LexaSH если я не ошибаюсь, то это нигде и не документировано.

**Comment by LexaSH** [comment]
Мне тоже так показалось. Есть еще что-то, что может быть полезным при создании класса?
