### ISSUE TITLE
Работа функции СтрРазделить

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#683]
Согласно справки
```
Разделяет строку на части по указанным символам-разделителям.
Синтаксис:

СтрРазделить(inputString: Строка, stringDelimiter: Строка, includeEmpty?: Булево): Массив
Параметры:

inputString: Разделяемая строка.
stringDelimiter: Строка символов, каждый из которых является индивидуальным разделителем.
includeEmpty: Указывает необходимость включать в результат пустые строки, которые могут образоваться в результате разделения исходной строки. Значение по умолчанию: Истина.
```
Третий параметр, по умолчанию истина, а по факту "Ложь"

Воспроизведение:
```
МассивРезультата = СтрРазделить("Истина;;0", ";", Истина);
Сообщить(МассивРезультата.Количество()); // 3 

МассивРезультата = СтрРазделить("Истина;;0", ";");
Сообщить(МассивРезультата.Количество()); // 2

```

**Comment by nixel2007** [comment]
https://github.com/EvilBeaver/OneScript/blob/220e9add17b48dc60a6640cdaecc7be78549d448/src/ScriptEngine.HostedScript/Library/StringOperations.cs#L105

**Comment by nixel2007** [comment]
@EvilBeaver если я правильно понимаю, то это из-за того, что при не указании параметра прилетает null, а не дефолтное значение. Погляжу.

**Comment by nixel2007** [comment]
Вообще такое чувство, что сломался автокаст в дефолтные значения. И он теперь всегда шлет null

**Comment by dmpas** [comment]
Так всегда и работало, емнип.

**Comment by EvilBeaver** [comment]
Да, так всегда и работал. В сигнатуре надо поменять bool на bool? и дефолтное на null

**Comment by EvilBeaver** [comment]
или починить автокастер (и сломать этим что нибудь еще)

**Comment by nixel2007** [comment]
Я за починку автокастера)

**Comment by nixel2007** [comment]
@Khorevaa забирай ночник минут через 15-20

**Comment by nixel2007** [comment]
http://build.oscript.io/job/1Script/job/develop/154/

**Comment by khorevaa** [comment]
Благодарю :)
