### ISSUE TITLE
Вопрос. Как получить this класса?

### ISSUE THREAD

**Issue by LexaSH** [EvilBeaver/OneScript#684]

**Comment by nixel2007** [comment]
если из оскрипта - ЭтотОбъект, ThisObject

**Comment by LexaSH** [comment]
Внутри класса не работает.

**Comment by nixel2007** [comment]
Приведите свой код. ЭтотОбъект должен разрешаться без ошибок. Какая версия движка?

**Comment by LexaSH** [comment]
Прошу прощения, был напуган...
Спасибо, все хорошо, работает.
