### ISSUE TITLE
Не фиксируется синтакс-ошибка при указании неверной запятой в конце списка параметров метода

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#688]
Не фиксируется синтакс-ошибка при указании неверной запятой в конце списка параметров метода.
Баг обнаружен Сонаром!

Ссылка на исходный код https://github.com/oscript-library/v8runner/blob/develop/src/v8runner.os#L411
```
Процедура ПодключитьсяКХранилищу(Знач СтрокаСоединения, 
                                    Знач ПользовательХранилища,
                                    Знач ПарольХранилища = "",
                                    Знач ИгнорироватьНаличиеПодключеннойБД = Ложь,
                                    Знач ЗаменитьКонфигурациюБД = Истина,
                                   	) Экспорт
```
![image](https://user-images.githubusercontent.com/2920817/35470540-7b103a50-035c-11e8-99db-8fd634be4aa8.png)

[Ссылка в Сонаре](https://sonar.silverbulleters.org/project/issues?id=oscript-lib-full&issues=AWCdzRmZh-Sa6Kz_ITGH&open=AWCdzRmZh-Sa6Kz_ITGH)

А в 1С выдается ошибка
```
{ВнешняяОбработка.ВнешняяОбработка1.МодульОбъекта(6,37)}: Ожидается имя формального параметра
                                   	<<?>>) Экспорт (Проверка: Сервер)
```

**Comment by artbear** [comment]
Я исправил непосредственно в коде v8runner.
Жду исправления в движке.

**Comment by EvilBeaver** [comment]
Зачем держать тут открытый ишшуз и ждать исправления в движке?
