### ISSUE TITLE
Очепятка в Continue

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#690]
сабж
https://github.com/EvilBeaver/OneScript/blob/e1545774c630f1b04a37df0f32b45eaaee5ca6d0/src/ScriptEngine/Compiler/Tokens.cs#L68

**Comment by nixel2007** [comment]
Что там за символ вообще? Выглядит как минускульная единица.

**Comment by dmpas** [comment]
Турецкая ы ?? Кто писал эту строчку?

**Comment by nixel2007** [comment]
@dmpas судя по блейму с перемоткой назад - ты, четыре года назад. :)

**Comment by tsukanov-as** [comment]
@nixel2007 Четыре года назад это был совершенно другой человек )
@dmpas Я б на вашем месте проверил бы все исходники на предмет странных символов. Мало ли. Может это восстание терминаторов.

**Comment by dmpas** [comment]
Не, у меня была турецкая раскладка одно время, не отрицаю.

**Comment by EvilBeaver** [comment]
Хм... вот так и паляцца огенты турецкой розветки!

**Comment by pumbaEO** [comment]
@EvilBeaver  кто-бьі говорил, до сих пор помню в деплойке флаг запрета динамического обновления и непечатній символ в -Dynamic...

**Comment by EvilBeaver** [comment]
Гиде? Ніколи не було
