### ISSUE TITLE
НайтиФайлы выдает ошибку длинного пути, из которой непонятно, какой же файл виноват

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#691]
Вызывающий клиентский код использует НайтиФайлы с учетом подкаталогов
```bsl
СписокФайлов = НайтиФайлы(КаталогВходящий, ПолучитьМаскуВсеФайлы(), Истина);
```
КаталогВходящий в данном случае был `c:\cicd\workspace\ADD_test_feature_ci\features`

Выдается ошибка длинного пути, из которой непонятно, какой же файл вызвал проблему :(
```
ОШИБКА - {Модуль C:\cicd\workspace\ADD_test_feature_ci\tools\runner.os / 
Ошибка в строке: 1898 / 
Внешнее исключение (System.IO.PathTooLongException): 
Слишком длинный путь или имя файла. 
Полное имя файла должно содержать меньше 260 знаков, а имя каталога - меньше 248 знаков.}
```

Хотелось бы в тексте исключения видеть 
+ как имя каталога, в котором выполняется поиск
+ так и имя проблемного файла/каталога, который и вызвал ошибку

PS вот ссылка на лог упавшей с этой ошибкой сборки http://ci.silverbulleters.org/job/ADD%20test/job/feature%252Fci/16/console

**Comment by nixel2007** [comment]
@EvilBeaver @dmpas 
если переехать на 4.6.2 можно включить поддержку длинных путей на уровне конфигурирования приложения - https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/

**Comment by nixel2007** [comment]
Другой вариант - переписать обращение к FS на использование вот этой библиотеки - https://gallery.technet.microsoft.com/DelimonWin32IO-Library-V40-7ff6b16c

Попробую добавить использование и прогнать сборку на линуксе

**Comment by EvilBeaver** [comment]
Да, есть давний ишшуз на эту тему. Я бы это закрыл, как дубликат. Есть возражения?

**Comment by nixel2007** [comment]
@EvilBeaver ага, нашел.

**Comment by nixel2007** [comment]
link https://github.com/EvilBeaver/OneScript/issues/67
