### ISSUE TITLE
Преобразование к типу 'Число' не поддерживается

### ISSUE THREAD

**Issue by LexaSH** [EvilBeaver/OneScript#693]
Ошибка при преобразовании строки к числу, у которой есть пробелы в начале или конце.
Версия 1.0.19. Код ниже.

СтрокаДляПреобразования = "1 ";

ЧислоИзСтроки = Число(СтрокаДляПреобразования);

**Comment by nixel2007** [comment]
А в платформе поддерживается?

**Comment by LexaSH** [comment]
Да, поддерживается. Проверил на 8.3.11.2867
