### ISSUE TITLE
Рефлектор съедает функции в конце модуля

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#696]
Создаем модуль вида 
```bsl
#Использовать logos

Функция МетодПеред() // Если сюда добавить Экспорт, то проверка работает
	
КонецФункции

Функция ПроверяемаяФункция() Экспорт
	
КонецФункции


Лог = Логирование.ПолучитьЛог("oscript.lib.test");
Лог.УстановитьУровень(УровниЛога.Отладка);
РефлекторПроверкиКоманд = Новый Рефлектор;

ПроверяемыйКласс = ЭтотОбъект;
ИмяМетода = "ПроверяемаяФункция";
ЭтоФункция = Истина;
ТребуемоеКоличествоПараметров = 0;

ЕстьМетод = РефлекторПроверкиКоманд.МетодСуществует(ПроверяемыйКласс, ИмяМетода);
Лог.Отладка("Проверяемый метод <%1> найден: %2", ИмяМетода, ЕстьМетод);
Если Не ЕстьМетод Тогда
	ВызватьИсключение "Нет нужного метода";
КонецЕсли;

ТаблицаМетодов = РефлекторПроверкиКоманд.ПолучитьТаблицуМетодов(ПроверяемыйКласс);

СтрокаМетода = ТаблицаМетодов.Найти(ИмяМетода, "Имя");
Лог.Отладка("Поиск строки в таблице методов класса <%1> найдена: %2, общее количество методов класса: %3", ПроверяемыйКласс, НЕ СтрокаМетода = Неопределено, ТаблицаМетодов.Количество());
Если СтрокаМетода = Неопределено Тогда
	ВызватьИсключение "Нет нужного метода";
КонецЕсли;

ПроверкаНаФункцию = ЭтоФункция = СтрокаМетода.ЭтоФункция;
ПроверкаНаКоличествоПараметров = ТребуемоеКоличествоПараметров = СтрокаМетода.КоличествоПараметров;

Лог.Отладка("Проверяемый метод <%1> корректен: %2", ИмяМетода, ПроверкаНаФункцию И ПроверкаНаКоличествоПараметров);
Если НЕ (ПроверкаНаФункцию
	И ПроверкаНаКоличествоПараметров) Тогда
	ВызватьИсключение "Нет нужного метода";
КонецЕсли;	

```
Выполняем и нет метода )

/cc @EvilBeaver @nixel2007 @artbear

**Comment by artbear** [comment]
Отличный тест!

**Comment by artbear** [comment]
Предлагаю вместо одной экспортной функции добавить две функции, чтобы убедиться, что хотя бы одна экспортная все-таки ловится в этом случае.

```bsl
Функция ПроверяемаяФункция1() Экспорт
	
КонецФункции

Функция ПроверяемаяФункция() Экспорт
	
КонецФункции
```

я проверил, баг остается, не ловится именно последняя функция

**Comment by artbear** [comment]
кто-то перепутал Количество() и Количество() - 1 :) в коде движка ?

**Comment by nixel2007** [comment]
Хм, мои методы в москито как раз последние...

**Comment by artbear** [comment]
Тут весело.
Метод Рефлектор.ВызватьМетод() для искомой функции работает, как и МетодСуществует

т.е. проблема при выполнении ПолучитьТаблицуМетодов и в недрах GetMethods.

и вот тут нужен отладчик, который не работает :)

**Comment by artbear** [comment]
@dmpas @EvilBeaver расследовал проблему Рефлектора и ПолучитьТаблицуМетодов.
Проблема только с этим методом.

В общем, у нас неверно работает `GetMethods` у класс `RCIHelperExtensions` при разборе #696

```c#
    public static class RCIHelperExtensions
    {
        public static IEnumerable<MethodInfo> GetMethods(this IRuntimeContextInstance context)
        {
            MethodInfo[] methods = new MethodInfo[context.GetMethodsCount()];
            for (int i = 0; i < methods.Length; i++)
            {
                methods[i] = context.GetMethodInfo(i);
            }

            return methods;
        }
```

в качестве context выступает объект `UserScriptContextInstance`
вызов `context.GetMethodsCount()`возвращает 0 - это верно. т.к. у нас всего одна экспортная функция

метод расположен в `UserScriptContextInstance.cs`
```c#
        public override int GetMethodsCount()
        {
            return _module.ExportedMethods.Length;
        }
```

а вот далее `context.GetMethodInfo(i);`выдает инфу не по экспортному методу, а по обычному методу

этот метод `GetMethodInfo` расположен уже в другом классе `ScriptDrivenObject`
```c#
        public override MethodInfo GetMethodInfo(int methodNumber)
        {
            if (MethodDefinedInScript(methodNumber))
            {
                return _module.Methods[methodNumber-METHOD_COUNT].Signature;
            }
            else
            {
                return GetOwnMethod(methodNumber);
            }
        }
```

а `_module.Methods`- это коллекция всех методов класса, а не только экспортных :(

в итоге получается, что запрашивается инфа по экспортному методу, а возвращается инфа по приватному методу.

пока ничего сделать не могу, т.к. я не понимаю, 
+ где и как может использовать метод `GetMethodInfo` у класса `ScriptDrivenObject`
+ должен ли он возвращать только экспортные методы или все-таки все методы?

@EvilBeaver @dmpas поможете? подскажете?

**Comment by EvilBeaver** [comment]
@artbear понимаешь все правильно, где-то путаница в логике движка и надо понять где. Спасибо за анализ

**Comment by EvilBeaver** [comment]
Решать совместно с #626

**Comment by nixel2007** [comment]
Проверяй. @Khorevaa

**Comment by khorevaa** [comment]
@nixel2007 в ночнике?

**Comment by khorevaa** [comment]
@nixel2007 @EvilBeaver  - Проверил работает на ночнике. !! отлично!!

**Comment by artbear** [comment]
У нас сегодня эта проблема возникла CI.sb.org на стабильном релизе 1.0.20.209 :( с logos
После переустановки на свежий ночник проблема ушла.
Правда, логосу это все равно не помогло :)
