### ISSUE TITLE
Не работают значения по умолчанию для метода "ПриСозданииОбъекта"

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#697]
Вопроизведение:
Создает класс в текстом: 
```bsl
Процедура ПриСозданииОбъекта(Знач Параметр = "значение")

	Сообщить("Значение по умолчанию: " + Параметр);

КонецПроцедуры
```
Вызоваем создание класса
```bsl
тест = Новый ТестовыйКласс;
```
И не видим строки "Значение по умолчанию: значение"

**Comment by EvilBeaver** [comment]
Принято

**Comment by ret-Phoenix** [comment]
https://github.com/EvilBeaver/OneScript/blob/4fa0ae6d93e4ab876dd71615e482f44917c6b94b/src/ScriptEngine.HostedScript/Library/SpecialFolderEnum.cs#L19
Надо объявить public и будет видно.
