### ISSUE TITLE
Оператор "Новый". Совместимость с 1С

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#700]
Не знаю локальная это проблема или глобальная, но следующий код не работает:
```bsl
p = new Array(1);
p[0]= 1;
x = new("Массив", p);
```

Ругается на параметры конструктора `p` так: `Преобразование к типу 'Число' не поддерживается`.

ps Подозреваю что реализовано не так как в 1С.

**Comment by nixel2007** [comment]
давно ли в 1с можно создавать массив на основании другого массива?

**Comment by tsukanov-as** [comment]
@nixel2007 Это не на основании. Это вариант оператора Новый, когда параметры конструктора массивом передаются: https://i.imgur.com/8ESGDuE.png

**Comment by EvilBeaver** [comment]
Этот вариант синтаксиса, действительно, не реализован. Значение типа "тип" и массив аргументов передать нельзя. @tsukanov-as спасибо за раскопки. Может еще и фикс, а? 😉
