### ISSUE TITLE
Массивы. Совместимость с 1С

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#701]
Следующий код не работает в 1С, но работает в OneScript
```bsl
p = new Array(1);
p["0"]= 1;
message(p["0"]);
```

**Comment by EvilBeaver** [comment]
гыгы, я написал пхп, просто пойдя по кратчайшему пути...

```
А = 1;
Сообщить(А + "2");
```

Это тоже в 1Скрипт выведет цифру 3
