### ISSUE TITLE
Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.

### ISSUE THREAD

**Issue by LexaSH** [EvilBeaver/OneScript#703]
Ошибка при вызове оператора "Выполнить" (код ниже). В 1С отрабатывает нормально.

	Массив = Новый Массив();
	Массив.Добавить(1);
	Массив.Добавить(2);
	Массив.Добавить(3);
	
	КодДляВыполнения = "
	|Для Каждого ОчередноеНечто Из Массив Цикл
	|	Сообщить(ОчередноеНечто);	
	|КонецЦикла;";
	
	Выполнить(КодДляВыполнения);

**Comment by nixel2007** [comment]
Версия оскрипта?

**Comment by LexaSH** [comment]
1.0.19

**Comment by nixel2007** [comment]
А еще точнее? :)

**Comment by LexaSH** [comment]
1.0.19.105 ))

**Comment by EvilBeaver** [comment]
Принято. Спасибо

**Comment by LexaSH** [comment]
Есть понимание, как быстро эту ошибку можно исправить? Уж очень не хочется шаблонизатор переписывать.

**Comment by EvilBeaver** [comment]
Пока нет, надо лезть в код. Скорее всего, исправить несложно, пересобрать ночник и переехать на него.

**Comment by LexaSH** [comment]
Уточнение. Такой код тоже не работает.

КодДляВыполнения = "
|Сч = 2;
|Сообщить(Сч);
|";

Выполнить(КодДляВыполнения);

**Comment by LexaSH** [comment]
В общем, не работает код где есть присваивание.

**Comment by nixel2007** [comment]
а вот это уже любопытнее.
@EvilBeaver судя по всему "внешние" для выполняемого кода переменные пробрасываются без проблем, а вот с "внутренними" есть некие проблемы.

**Comment by EvilBeaver** [comment]
Вот конкретно ближайшие 2 недели на опенсорс катастрофически не будет времени, если только ночами здоровье гробить, но под это у меня есть уже приоритетные желания на означеный период.

**Comment by LexaSH** [comment]
Спасибо за информацию. Придется переписывать шаблонизатор.
