### ISSUE TITLE
Соответствия. Совместимость с 1С

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#704]
В 1С этот код работает (ничего конечно не присваивается)

```bsl
m = new map;
m[undefined] = 1;
```

В OneScript ошибка:
`Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}`

Код бредовый, но вполне может найтись уникум, который это заюзает. Совместимость она такая ))

**Comment by artbear** [comment]
Да, бред.
Предлагаю такую совместимость не поддержить.

**Comment by EvilBeaver** [comment]
System.NullReferenceException - это в любом случае ошибка в коде. Текст исключения должен быть другим.
