### ISSUE TITLE
Числа. Совместимость с 1С.

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#705]
Следующий код не работает.

```bsl
x = 999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999;
y = x * 2;
message(y);
```
В 1С числа произвольного размера. В OneScript это видимо не так.

**Comment by dmpas** [comment]
> В 1С числа произвольного размера

Мужик в шляпе говорит иное: "Максимально допустимая разрядность числа 38 знаков."

**Comment by tsukanov-as** [comment]
@dmpas Я про эти письмена знаю. Но по факту это касается вроде только типизированных реквизитов и свойств. На переменные этого ограничения нет.

**Comment by dmpas** [comment]
таки это тогда "недокументированная возможность" :)

**Comment by EvilBeaver** [comment]
БигДецимал мы в свое время не внедрили, ну и пока вроде нужды нет. Я бы повесил плашку вонт-фикс, т.к. прикладной потребности пока вроде бы нет, а данный тест синтетический.

**Comment by tsukanov-as** [comment]
@EvilBeaver Я б вообще забил. Только в доках указал бы об этом отличии (для дотошных технарей).
