### ISSUE TITLE
Булево из строки. Совместимость с 1С.

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#706]
Работает в 1С. Но не работает в OneScript

```bsl
x = boolean("Да");
message(x);
```

Текст ошибки
`Преобразование к типу 'Булево' не поддерживается`

**Comment by EvilBeaver** [comment]
Было бы ништяк, если бы ты эти вещи оформил в виде тестов для 1script и сделал пулреквест этих тестов.
