### ISSUE TITLE
ОбработкаПолученияПредставления для класса

### ISSUE THREAD

**Issue by LexaSH** [EvilBeaver/OneScript#709]

**Comment by nixel2007** [comment]
На данный момент - нет.

**Comment by LexaSH** [comment]
То есть реализация планируется?

**Comment by LexaSH** [comment]
Никита, тогда еще вопрос, с которого и следовало начать...
При приведении экземпляра класса к строке возвращается его (класса) имя, как оно задано в скрипте. Есть ли возможность, при создании класса, указать какое-нибудь свойство или метод, которое и будет возвращаться при приведении к строке?

**Comment by nixel2007** [comment]
бурные дискуссии в #584 и #583

**Comment by nixel2007** [comment]
> При приведении экземпляра класса к строке возвращается его (класса) имя, как оно задано в скрипте. Есть ли возможность, при создании класса, указать какое-нибудь свойство или метод, которое и будет возвращаться при приведении к строке?

экземпляр какого класса? движка или библиотеки? библиотека на си-шарпе или на оскрипте?

**Comment by LexaSH** [comment]
Библиотеки на оскрипте

**Comment by nixel2007** [comment]
У собственной библиотеки можно изменить имена классов в файле lib.config. У сторонних - никак нельзя

**Comment by LexaSH** [comment]
Это понятно. Но я немного не о том. Хочется чего-то такого.

Пользователь = Новый Пользователь();
Пользователь.Имя = "Мой самый любимый пользователь";
Сообщить(Пользователь); // выведет ' Пользователь', а хочется чтобы вывелось 'Мой самый любимый пользователь'

**Comment by LexaSH** [comment]
То есть, так как это в 1С реализовано. Возвращается строковое представление справочника, документа и т. д.

**Comment by nixel2007** [comment]
@EvilBeaver как тебе идея добавления волшебного переопределяемого метода ToString? :)

**Comment by pumbaEO** [comment]
toString мало, ОбработкаПолученияПолейПредставления, ОбработкаПолученияПредставления

**Comment by LexaSH** [comment]
Если появится волшебный переопределяемый метод ToString, то ОбработкаПолученияПолейПредставления и ОбработкаПолученияПредставления уже и не нужны будут.

**Comment by khorevaa** [comment]
Я в себя с либе использовать Функцию для классов `ВСтроку` Для удобства конвертации значений в строку...

**Comment by LexaSH** [comment]
Делаю также, но хотелось бы функционала сходного с 1С.

**Comment by EvilBeaver** [comment]
Вопрос интересный, да. 1С только недавно предоставила метод ToString, и как заметил @pumbaEO - ажно целых два метода. Принципиально я не возражаю, why not. Но как это должно выглядеть конкретно - не знаю.

**Comment by nixel2007** [comment]
На мой взгляд обработка получения полей представления в оскрипте - это оверкил. А вот обычная обработка Получения представления - почему бы и нет.

**Comment by LexaSH** [comment]
А кто-нибудь использовал метод 'ОбработкаПолученияПолейПредставления'? На мой взгляд, этот метод за уши притянут.

**Comment by nixel2007** [comment]
чисто теоретически оно служит для ускорения массового получения данных по ссылкам, т.к. отрабатывает один раз, а не на каждую ссылку.

**Comment by LexaSH** [comment]
Не наш случай. Кэшировать на клиенте нечего, а если когда-нибудь необходимость появится, то данный метод можно будет реализовать самостоятельно.

**Comment by EvilBeaver** [comment]
Вариантов как могло бы быть сделано у нас - много. Какой лучше - фиг его знает

**Comment by LexaSH** [comment]
Давайте остановимся на предопределенной функции ОбработкаПолученияПредставления() внутри класса. Этого, на мой взгляд, достаточно.

**Comment by EvilBeaver** [comment]
Переименовал таск

**Comment by LexaSH** [comment]
В ночной сборке уже есть?

**Comment by nixel2007** [comment]
@LexaSH да. http://build.oscript.io/job/1Script/job/develop/lastSuccessfulBuild/
