### ISSUE TITLE
Невозможно обратиться к не экспортному свойству через ЭтотОбъект внутри класса

### ISSUE THREAD

**Issue by LexaSH** [EvilBeaver/OneScript#710]
Собственно код:

  Перем Свойство1 Экспорт;
  Перем Свойство2;
  
  Процедура ПриСозданииОбъекта(ПараметрыИнициализации = Неопределено)
  
         Свойство1 = "Ура, работает!";
         Свойство2 = "Ура, не работает!";
  
        Сообщить(ЭтотОбъект.Свойство1); // тут все нормально.
        Сообщить(ЭтотОбъект.Свойство2); // а вот тут уже ошибка.  Свойство объекта не обнаружено
  
  КонецПроцедуры

**Comment by nixel2007** [comment]
А в 1с работает?

**Comment by EvilBeaver** [comment]
Мне тоже интересно

**Comment by LexaSH** [comment]
Нет, не работает. Но хотелось бы чтобы работало.

**Comment by EvilBeaver** [comment]
Боюсь это идейно неверно.

**Comment by LexaSH** [comment]
То есть все свойства объекта не получить?

**Comment by EvilBeaver** [comment]
@LexaSH пока нет, насколько я понимаю. Неэкспортные переменные это вообще не свойства

**Comment by LexaSH** [comment]
Да, не свойства. Но иметь возможность обойти все переменные находясь внутри объекта было бы не плохо.
