### ISSUE TITLE
Странное поведение оператора 'Выполнить' и 'ЭтотОбъект'

### ISSUE THREAD

**Issue by LexaSH** [EvilBeaver/OneScript#712]
Если внутри какого-нибудь класса вызвать команду "Выполнить", в которой будет сделано обращение к методу любого другого класса, то внутри этого вызванного метода, "ЭтотОбъект" будет указывать на класс, в котором находится команда "Выполнить", а не на класс, в котором вызванный метод находится.

**Comment by nixel2007** [comment]
Спасибо за репорт

**Comment by khorevaa** [comment]
Hack однако.
