### ISSUE TITLE
Падают тесты BinaryData-global

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#713]

**Comment by dmpas** [comment]
@EvilBeaver  сам запилишь?

**Comment by EvilBeaver** [comment]
@dmpas если есть желание - можешь сам взять

**Comment by dmpas** [comment]
давай я сегодня попробую запилить.

**Comment by dmpas** [comment]
https://github.com/EvilBeaver/OneScript/pull/714
