### ISSUE TITLE
ЦветКонсоли в power shell

### ISSUE THREAD

**Issue by thedemoncat** [EvilBeaver/OneScript#715]
Если запускать скрипт через power shell, то происходит падение на ЦветТекстаКонсоли = Консоль.ЦветТекста;

`Консоль = Новый Консоль();
//Консоль.ВидимостьКурсора(Ложь);	
ЦветТекстаКонсоли = Консоль.ЦветТекста;
Консоль.ЦветТекста = ЦветКонсоли.Yellow;
//Консоль.ВывестиСтроку("ИНФОРМАЦИЯ - Определяю тип возможной выгрузки в файлы");
	
Лог.Информация("Определяю тип возможной выгрузки конфигурации в файлы");
Консоль.ЦветТекста = ЦветТекстаКонсоли;`

**Comment by EvilBeaver** [comment]
А текст ошибки гласит?

**Comment by thedemoncat** [comment]
`КРИТИЧНАЯОШИБКА - {Модуль F:\1С\lab\vendor\plugins\preinstalled_plugins_gitsync\src\Классы\increment.os / Ошибка в строке: 45 / Внешнее исключение (System.InvalidOperationException): Последовательность не содержит соответствующий элемент}`

Ошибка попалась в сборке gitsync от @khorevaa

**Comment by khorevaa** [comment]
@EvilBeaver А будут подвижки в данному вопросе? -)

**Comment by EvilBeaver** [comment]
Пока низким приоритетом. Всяческая помощь в расследовании приветствуется

**Comment by Mr-Rm** [comment]
Падает ScriptEngine.HostedScript.Library.ConsoleColorEnum.FromNativeValue(). Причина -
в ScriptEngine.HostedScript.Library.ConsoleColorEnum.CreateInstance() перечислены только 9 цветов консоли из 16.
Аналогично будет падать и ЦветФона().
Причём ошибка проявляется только в 64-битных системах.
Для исправления нужны русские названия для семи "тёмных" цветов: DarkBlue, DarkCyan, DarkGray, DarkGreen, DarkMagenta, DarkRed, DarkYellow. Можно просто "ТемноСиний" и т. д.
Здесь сомнительно выглядят уже имеющиеся "Cyan"=="Бирюза" (даже не "Бирюзовый"!) и "Magenta"=="Малиновый", вместо "Голубой" и "Пурпурный", как, например, в MSDN.

**Comment by EvilBeaver** [comment]
Cyan - это как-то ни разу не "Голубой", на мой глаз....

**Comment by Faithfinder** [comment]
Велосипед придумывать незачем, есть перечисление 1С WebЦвета на двух языках

> WebЦвета (WebColors)
> Значения
> 
> Аквамарин (Aquamarine)
> АкварельноСиний (AliceBlue)
> АнтикБелый (AntiqueWhite)
> Бежевый (Beige)
> Белоснежный (Snow)
> Белый (White)
> Бирюзовый (Turquoise)
> БледноБирюзовый (PaleTurquoise)
> БледноЗеленый (PaleGreen)
> БледноЗолотистый (PaleGoldenrod)
> БледноКрасноФиолетовый (PaleVioletRed)
> БледноЛиловый (Lavender)
> БледноМиндальный (BlanchedAlmond)
> БледноСиреневый (Thistle)
> Васильковый (CornFlowerBlue)
> ВесеннеЗеленый (SpringGreen)
> Голубой (LightBlue)
> ГолубойСКраснымОттенком (LavenderBlush)
> ГолубойСоСтальнымОттенком (LightSteelBlue)
> ГрифельноСерый (SlateGray)
> ГрифельноСиний (SlateBlue)
> Древесный (BurlyWood)
> ДымчатоБелый (WhiteSmoke)
> ЖелтоЗеленый (YellowGreen)
> Желтый (Yellow)
> ЗамшаСветлый (Moccasin)
> ЗеленаяЛужайка (LawnGreen)
> ЗеленоватоЖелтый (Chartreuse)
> ЗеленоватоЛимонный (Lime)
> ЗеленоЖелтый (GreenYellow)
> Зеленый (Green)
> ЗеленыйЛес (ForestGreen)
> Золотистый (Goldenrod)
> Золотой (Gold)
> Индиго (Indigo)
> Киноварь (IndianRed)
> Кирпичный (FireBrick)
> КожаноКоричневый (SaddleBrown)
> Коралловый (Coral)
> Коричневый (Brown)
> КоролевскиГолубой (RoyalBlue)
> КрасноФиолетовый (VioletRed)
> Красный (Red)
> Кремовый (Cream)
> Лазурный (Azure)
> ЛимонноЗеленый (LimeGreen)
> Лимонный (LemonChiffon)
> Лосось (Salmon)
> ЛососьСветлый (LightSalmon)
> ЛососьТемный (DarkSalmon)
> Льняной (Linen)
> Малиновый (Crimson)
> МятныйКрем (MintCream)
> НавахоБелый (NavajoWhite)
> НасыщенноНебесноГолубой (DeepSkyBlue)
> НасыщенноРозовый (DeepPink)
> НебесноГолубой (SkyBlue)
> НейтральноАквамариновый (MediumAquaMarine)
> НейтральноБирюзовый (MediumTurquoise)
> НейтральноВесеннеЗеленый (MediumSpringGreen)
> НейтральноГрифельноСиний (MediumSlateBlue)
> НейтральноЗеленый (MediumGreen)
> НейтральноКоричневый (Peru)
> НейтральноПурпурный (MediumPurple)
> НейтральноСерый (MediumGray)
> НейтральноСиний (MediumBlue)
> НейтральноФиолетовоКрасный (MediumVioletRed)
> Оливковый (Olive)
> ОранжевоКрасный (OrangeRed)
> Оранжевый (Orange)
> Орхидея (Orchid)
> ОрхидеяНейтральный (MediumOrchid)
> ОрхидеяТемный (DarkOrchid)
> Охра (Sienna)
> Перламутровый (SeaShell)
> Персиковый (PeachPuff)
> ПесочноКоричневый (SandyBrown)
> ПолночноСиний (MidnightBlue)
> ПризрачноБелый (GhostWhite)
> Пурпурный (Purple)
> Пшеничный (Wheat)
> РозовоКоричневый (RosyBrown)
> Розовый (Pink)
> Роса (HoneyDew)
> РыжеватоКоричневый (Tan)
> СветлоГрифельноСерый (LightSlateGray)
> СветлоГрифельноСиний (LightSlateBlue)
> СветлоЖелтый (LightYellow)
> СветлоЖелтыйЗолотистый (LightGoldenRodYellow)
> СветлоЗеленый (LightGreen)
> СветлоЗолотистый (LightGoldenRod)
> СветлоКоралловый (LightCoral)
> СветлоКоричневый (Bisque)
> СветлоНебесноГолубой (LightSkyBlue)
> СветлоРозовый (LightPink)
> СветлоСерый (LightGray)
> СеребристоСерый (Gainsboro)
> Серебряный (Silver)
> СероСиний (CadetBlue)
> Серый (Gray)
> СинеСерый (DodgerBlue)
> СинеФиолетовый (BlueViolet)
> Синий (Blue)
> СинийСоСтальнымОттенком (SteelBlue)
> СинийСПороховымОттенком (PowderBlue)
> Сливовый (Plum)
> СлоноваяКость (Ivory)
> СтароеКружево (OldLace)
> ТемноБирюзовый (DarkTurquoise)
> ТемноБордовый (Maroon)
> ТемноГрифельноСерый (DarkSlateGray)
> ТемноГрифельноСиний (DarkSlateBlue)
> ТемноЗеленый (DarkGreen)
> ТемноЗолотистый (DarkGoldenRod)
> ТемноКрасный (DarkRed)
> ТемноОливковоЗеленый (DarkOliveGreen)
> ТемноОранжевый (DarkOrange)
> ТемноСерый (DarkGray)
> ТемноСиний (DarkBlue)
> ТемноФиолетовый (DarkViolet)
> ТеплоРозовый (HotPink)
> Томатный (Tomato)
> ТопленоеМолоко (PapayaWhip)
> ТусклоОливковый (Olivedrab)
> ТусклоРозовый (MistyRose)
> ТусклоСерый (DimGray)
> Ультрамарин (Navy)
> Фиолетовый (Violet)
> Фуксин (Magenta)
> ФуксинТемный (DarkMagenta)
> Фуксия (Fuchsia)
> Хаки (Khaki)
> ХакиТемный (DarkKhaki)
> ЦветМорскойВолны (Seagreen)
> ЦветМорскойВолныНейтральный (MediumSeaGreen)
> ЦветМорскойВолныСветлый (LightSeaGreen)
> ЦветМорскойВолныТемный (DarkSeaGreen)
> ЦветокБелый (FloralWhite)
> Циан (Cyan)
> ЦианАкварельный (Aqua)
> ЦианНейтральный (Teal)
> ЦианСветлый (LightCyan)
> ЦианТемный (DarkCyan)
> Черный (Black)
> ШелковыйОттенок (CornSilk)
> Шоколадный (Chocolate)

**Comment by EvilBeaver** [comment]
Ага, только далеко не все поддерживаются в консоли

**Comment by Faithfinder** [comment]
Для тех которые поддерживаются какой писать русский алиас видно, все есть. Cyan не голубой и не бирюзовый, а прям Циан

**Comment by Mr-Rm** [comment]
Основные веб-цвета и цвета консоли даже по-английски не все совпадают.

> Консоль | Веб | RGB
> -------|-----|-----
> Black | Black | #000000
> Red | Red | #FF0000
> Yellow | Yellow | #FFFF00
> Blue | Blue | #0000FF
> White | White | #FFFFFF
> Green | Lime  |  #00FF00
> Gray | Silver |#C0C0C0
> Cyan | Aqua |  #00FFFF
> Magenta | Fuchsia | #FF00FF
> DarkRed | Maroon | #800000
> DarkGreen | Green | #008000
> DarkBlue | Navy | # 000080
> DarkGray | Gray | #808080
> DarkMagenta | Purple | #800080
> DarkYellow | Olive |  #808000
> DarkCyan | Teal |  #008080

**Comment by EvilBeaver** [comment]
Готово
