### ISSUE TITLE
Простая/минимальная дока на аннотации

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#716]
https://github.com/EvilBeaver/OneScript/pull/630#issuecomment-365256888

>@dmpas сможешь кратко накидать малюсенькую доку на аннотации?
Эта инфа все равно нужна и для выпуска релиза, и для описания использования для пользователей движка.

**Comment by EvilBeaver** [comment]
@artbear где ожидается увидеть эту доку?

**Comment by artbear** [comment]
Идеально - страница на основной сайте
Минимально - описание изменений с примерами в changelog релиза

**Comment by dmpas** [comment]
@artbear 
https://github.com/EvilBeaver/oscriptiocontent/pull/7
