### ISSUE TITLE
Вопрос. Есть ли возможность добавить модуль в глобальную область видимости непосредственно из стартового сценария?

### ISSUE THREAD

**Issue by LexaSH** [EvilBeaver/OneScript#717]

**Comment by LexaSH** [comment]
Вижу метод ДобавитьКласс, но он доступен только для загрузчика библиотек

**Comment by EvilBeaver** [comment]
Нет, нельзя

**Comment by LexaSH** [comment]
А можно сделать так, чтобы было можно?

**Comment by EvilBeaver** [comment]
Планы такие были, но споткнулись об сложность реализации. Может когда-то в будущем (очень далеком)

**Comment by LexaSH** [comment]
Вот это печаль! То есть оформлять весь проект как библиотеку?

**Comment by EvilBeaver** [comment]
Не понял вопроса

**Comment by LexaSH** [comment]
Не обращайте внимания. Я уже сам себе на этот вопрос ответил.
Оформлю весь проект как библиотеку, а стартовый сценарий вынесу из проекта. При старте буду парсить папку (где будут лежать модули) внутри библиотеки и пересоздавать lib.config для всего проекта. Далее буду перезапускать стартовый сценарий.  Как-то так...

**Comment by nixel2007** [comment]
Если модули будут лежать в каталоге, удовлетворяя правилам структуры каталога, то можно и без lib.config

**Comment by LexaSH** [comment]
Спасибо, попробую.
