### ISSUE TITLE
В синтакс-помощнике отсутствует метод ПотокВПамяти.ЗакрытьИПолучитьДвоичныеДанные

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#724]
ПотокВПамяти.ЗакрытьИПолучитьДвоичныеДанные есть в исходниках, но не содержится в документации

**Comment by Stepa86** [comment]
@EvilBeaver Этот метод падает с `Метод объекта не обнаружен (ЗакрытьИПолучитьДвоичныеДанные)`

Может дело в том, что в исходниках этот метод объявлен приватным? И именно из-за этого он не попадает в СП 

https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Binary/MemoryStreamContext.cs#L277
