### ISSUE TITLE
Не работает пропуск необязятаельных параметров в "ПриСозданииОбъекта"

### ISSUE THREAD

**Issue by dvakor** [EvilBeaver/OneScript#726]
по мотивам #697
Следующий код не работает

*Файл test.os
```
Процедура ПриСозданииОбъекта(Перем1 = "1", Перем2 = "2")
	Сообщить("Перем1 " + Перем1);
	Сообщить("Перем2 " + Перем2);
КонецПроцедуры
```

*Файл main.os
```
ПодключитьСценарий("C:\Temp\test.os", "МойОбъект");
Об = Новый МойОбъект(,"44");
```
Валится с **NotImplementedException**

**Comment by arkuznetsov** [comment]
Похоже, что починили, на 1.4 точно работает.

**Comment by dvakor** [comment]
> Похоже, что починили, на 1.4 точно работает.

Интересно...мб и я как то правил, но не приленковал ишузу.
Надо хоть тест накинуть будет накрайняк :))

**Comment by EvilBeaver** [comment]
Накиньте тест por favor
