### ISSUE TITLE
Баг в обработке параметров конструктора "ПриСозданииОбъекта"

### ISSUE THREAD

**Issue by dvakor** [EvilBeaver/OneScript#727]
Следующий код работает, хотя не должен
test.os
```
Процедура ПриСозданииОбъекта(Перем1 = "1", Перем2)
	Сообщить("Перем1 " + Перем1);
	Сообщить("Перем2 " + Перем2);
КонецПроцедуры
```

main.os
```
ПодключитьСценарий("C:\Temp\test.os", "МойОбъект"); 
o = Новый МойОбъект(2);
```

**Comment by EvilBeaver** [comment]
@ArchLord42RU - это исправлено ведь уже, да?

**Comment by dvakor** [comment]
Мой ПР который ты не давно принял фиксил #697.
Проверил и на текущий момент все отлично продолжает выполнятся, так что надо фиксить отдельно.
