### ISSUE TITLE
Сообщить(Неопределено); выдает ошибку

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#735]
`Сообщить(Неопределено);` выдает ошибку
```
{Модуль C:\projects\1.os / 
Ошибка в строке: 1 / 
Внешнее исключение (System.ArgumentNullException): 
Ссылка на строку не ссылается на экземпляр String.
Имя параметра: s}
The terminal process terminated with exit code: 1
```
Проверил на версии 1.0.20.139

**Comment by artbear** [comment]
А `Сообщить(null);` ошибку не выдает

**Comment by EvilBeaver** [comment]
Это так просимый всеми тикет по маршаллингу Неопределено в null (https://github.com/EvilBeaver/OneScript/pull/634)

@dmpas @jdeshin а я говорил, говорил...

**Comment by dmpas** [comment]
@EvilBeaver правильной дорогой идём, мелкие неприятности нас не страшат!

**Comment by EvilBeaver** [comment]
Вот смотри:

```c#
public void Echo(string message, MessageStatusEnum status = MessageStatusEnum.Ordinary)
        {
            ApplicationHost.Echo(message, status);
        }
```

Мне, как пишущему метод, совершенно четко понятно, что сюда должна приходить Строка. А Неопределено или Число - не должны. А получается, что Неопределено транслируется в null всегда, безо всяких условий. Получается, что мы не можем на уровне маршалинга отсечь аргументы неверного типа, передаваемые из скриптов в наши методы.

**Comment by Stepa86** [comment]
@EvilBeaver Если чо, в 1Ске Сообщить(42) выводит 42, а Сообщить( Неопределено) и Сообщить( Null ) ничего не делают просто. Сообщить() падает `Недостаточно фактических параметров`

**Comment by dmpas** [comment]
во-первых, ты, как пишущий метод на C#, должен чётко понимать, что `string` не null-безопасен
во-вторых, на уровне маршаллера можно приводить входящие параметры к строке всегда и без исключения ибо именно так и происходит в 1С (с видимой стороны).

**Comment by EvilBeaver** [comment]
> во-первых, ты, как пишущий метод на C#, должен чётко понимать, что string не null-безопасен

Я бы все-таки в целях маршалинга отнес string к примитивному типу Строка и маршалил бы в параметр типа string всегда результат IValue.AsString передаваемого значения

**Comment by dmpas** [comment]
в целях маршаллинга да. но C#-методы могут вызываться не только из контура односкрипта, но и из другого .net-кода, откуда вполне может прилететь null в стринге.

**Comment by EvilBeaver** [comment]
Это да, но это несколько другой уровень ответственности.

**Comment by jdeshin** [comment]
Дык а в чем проблема то? Тип string может принимать значение null. Его просто надо обрабатывать вот и все :), в частности в Сообщить.

**Comment by dmpas** [comment]
@jdeshin проблема в том, что с  точки зрения односкрипта Строка - это примитивный тип, который не может быть null, Неопределено или ещё чем-то помимо строки. То есть, идеологически `Строка != string`

**Comment by nixel2007** [comment]
@dmpas с точки зрения 1С*

**Comment by dmpas** [comment]
@nixel2007 с точки зрения односкрипта*

**Comment by nixel2007** [comment]
@dmpas поясни? "примитивность" строки следует из языка 1с, это не односкриптовое изобретение. Отсутствие нулл-безопасности и проблемы с маршалингом - это внутренние сложности оскрипта, да.

**Comment by nixel2007** [comment]
Разве что брать в расчёт слабость и динамичность типизации в 1с как в языке.

**Comment by jdeshin** [comment]
Вот динамическая типизация - это ключевая фраза. В языке с динамической типизацией параметры могут быть любого типа, а мы для своего удобства их проверяем (в том числе приводя к определенным типам) и генерим исключения при необходимости. Только не меняйте пожалуйста обратно, т.к. куча .net библиотек могут принимать/возвращать null в параметрах типа string. В конце концов, если человек пишет на C# он в курсе string etc. и сделает необходимые проверки.

**Comment by nixel2007** [comment]
@jdeshin ни в коем случае не говорю про "вернуть назад". пока ехал на работу еще раздумывал, правильно ли будет неопределено/null принудительно кастить к string прямо в вызывателе функций. Пришел к выводу, что это может поломать места, где строковый параметр - необязательный, и туда вполне осознанно может прилететь null. думаю, правильным, но долгим вариантом будет обработка строк в каждой конкретной функции, как сделал @EvilBeaver в https://github.com/EvilBeaver/OneScript/commit/add60e1d6763c072532959071da408b1476f3085

Ну либо заставить всех разработчиков односкрипта и либ на c# забыть про нативный string и использовать явный IValue, но это изврат

**Comment by EvilBeaver** [comment]
Смотрите чего. Если параметр в который мы хотим пробросить значение - строковый, то надо передавать туда строку с точки зрения 1С-языка.

```
МетодСоСтроковымПараметром("Привет");
МетодСоСтроковымПараметром(25.7);
МетодСоСтроковымПараметром('2018-05-09');
МетодСоСтроковымПараметром(Неопределено);
МетодСоСтроковымПараметром(Истина);
```

Во всех случаях, кроме "Привет" - вызов выглядит бредовым. Однако, для Неопределено сделано исключение и вызов все равно осуществляется, а на уровень C# приходит null.
Но ведь речь **не о том**, что в C# string может иметь значение null. Речь о том, что мы **разрешаем некорректно использовать** сам 1С-ный метод.

**Comment by jdeshin** [comment]
Ну а если параметр необязательный и мы не задаем значение, какое значение он примет в теле функции? И опять таки, это мы для конкретной функции решили, что параметр должен иметь тип строка. Сам язык имеет динамическую типизацию, поэтому никаких ограничений не накладывает. Соответственно если мы решили для конкретной функции, что параметр только строка, то и проверяем так ли это. Также мы неявно проверяем тип значения, указав тип параметра не IVALUE а string, что отсекает передачу параметров типа int etc. Ну такова особенность string - это типа int?

**Comment by EvilBeaver** [comment]
@jdeshin шарповые (т.е. платформенные) методы строго типизированы. Загляни в синтакс-помощник 1С. Все типы параметров заявлены, а передача недопустимых - недопускается.

Если параметр необязательный - в него приходит то значение, которое заявлено в сигнатуре метода.

В платформе 1С насчет передачи Неопределено в качестве значения необязательного параметра есть несколько вариантов развития ситуации:

1. В методе есть необязательный параметр типа Х. Можно передать Неопределено и ошибки не будет
2. В методе есть необязательный параметр типа Х. При передаче Неопределено ругается на несовместимый тип аргумента

В разных классах - по-разному сделано у них, т.е. явно зависело от предпочтений автора того или иного метода. 

> Соответственно если мы решили для конкретной функции, что параметр только строка, то и проверяем так ли это. Также мы неявно проверяем тип значения, указав тип параметра не IVALUE а string, что отсекает передачу параметров типа int etc. Ну такова особенность string - это типа int?

Вот этот тезис не понял. О чем он?
