### ISSUE TITLE
С версией движка 1.0.20 идет нерабочий v8runner

### ISSUE THREAD

**Issue by Tavalik** [EvilBeaver/OneScript#739]
Воспроизвести можно так:
1. На чистую машину ставлю OneScript-1.0.20
2. opm install deployka
3. deployka help 
Получаем ошибку в библиотеке v8runner.

Лечится с помощью opm update -all

**Comment by EvilBeaver** [comment]
@nixel2007 поправь, если ошибаюсь: мы релизим свежую деплойку и все встает на место. В поставку движка ничего не добавляем. Задачу поставки ospx-ов помним и делаем когда-нибудь потом. Все верно?

**Comment by nixel2007** [comment]
@EvilBeaver насколько я понимаю сейчас в движок попадают либы, которые стоят на твоей конкретной виндовой сборочной ноде. Их там надо обновить, заодно добавить в стдлиб notify. За этим я у тебя и просил пароль сегодня

**Comment by EvilBeaver** [comment]
а я профукал ( Исправился!

**Comment by nixel2007** [comment]
@Tavalik обновил. проверяй.

**Comment by Tavalik** [comment]
Спасибо, работает.
