### ISSUE TITLE
Добавить кодировку UTF-8 без BOM в доступные варианты чтения/записи текстов

### ISSUE THREAD

**Issue by zeratulayuris** [EvilBeaver/OneScript#740]
Не нашел способа записать текст в UTF-8 без BOM. В платформе 1С это можно было сделать, указав кодировку CESU-8, а для OneScript пришлось исхитряться с двоичными данными и Base64.

Или я плохо искал?

**Comment by nixel2007** [comment]
Есть кодировка UTF8NoBOM

**Comment by EvilBeaver** [comment]
Судя по тому, что в свежих платформах появились отдельные параметры вида "ДобавлятьМеткуBOM" - даже в самой 1С не знают про кодировку CESU-2

Я вот, точно не знал про такую )) А параметры "ДобавлятьМеткуBOM" из платформы в 1скрипт портированы.

**Comment by zeratulayuris** [comment]
~~Однако вот незадача - указание UTF8NoBOM в ЗаписьТекста приводит к сообщению об отсутствии поддержки (1.0.19.105), а параметр ДобавлятьМеткуBOM работает только с потоками в памяти, емнип.~~
Ну и хоть и был он портирован, но в документации на oscript.io это не отражено примерно никак )

Кто-то балбес и невнимательно читал исходники.
