### ISSUE TITLE
ЗаполнитьЗначенияСвойств()

### ISSUE THREAD

**Issue by asosnoviy** [EvilBeaver/OneScript#741]
`ЗаполнитьЗначенияСвойств(Новый Мессенджер(), Новый Мессенджер());`   
падает с ошибкой: 
`Внешнее исключение (System.NotImplementedException): Метод или операция не реализована.}`
Но
`ЗаполнитьЗначенияСвойств(Новый Мессенджер(), Новый Мессенджер(), "ИмяСвойства");`
Отрабатывает корректно.  

Замечано на 1.0.20.209 на предидущих версиях не проверял

**Comment by nixel2007** [comment]
Неожиданно выявлено в moskito. Есть вероятность, что в 1.0.19 работало.

**Comment by EvilBeaver** [comment]
Принято, спасибо
