### ISSUE TITLE
Нужен пример консольной утилиты

### ISSUE THREAD

**Issue by ArsenShnurkov** [EvilBeaver/OneScript#745]
Нужен пример разбора параметров командной строки, открытия и чтения входного потока, записи выходного потока, потока ошибок (и не через консоль, а через файловые операции).

Мне бы пример скрипта, который парсит аргументы командной строки (да, я видел <a href="https://github.com/EvilBeaver/OneScript/blob/33b33a2fec641231a462ae80fa59fcc1d3800d55/src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs#L281">бибиотечку</a>).  Ну, то есть заготовку для типовой утилиты командной строки.
А то пишу я, к примеру,

     поток0 = ФайловыеПотоки.Открыть("/dev/stdin",РежимОткрытияФайла.Открыть);
     поток1 = ФайловыеПотоки.Открыть("/dev/stdout",РежимОткрытияФайла.Открыть);

а оно мне выдаёт

    {Модуль /home/user/ostest/1.os / Ошибка в строке: 2 / Внешнее исключение (System.IO.IOException): Sharing violation on path /dev/stdout}

**Comment by EvilBeaver** [comment]
Чтение собственных потоков ввода отсутсвует

**Comment by EvilBeaver** [comment]
Библиотечка для парсинга аргументов и вообще, заготовка для консольного приложения есть. См. oscript-library/os-app-template

**Comment by ArsenShnurkov** [comment]
> Чтение собственных потоков ввода отсутсвует

сделайте пожалуйста, я сам не справлюсь, у меня лапки

**Comment by EvilBeaver** [comment]
https://github.com/oscript-library/oscript-app-template

**Comment by ArsenShnurkov** [comment]
да, за заготовку спасибо, только заготовка - это не пример. В частности, параметры там не нашел как парсятся для разных типовых случаев (например указать параметр логический, параметр со значением, параметр со списком значений)

**Comment by EvilBeaver** [comment]
https://github.com/oscript-library/cmdline/blob/master/readme.md

Но док неполный. Есть еще методы для добавления флаговых параметров и параметров-списков. Нужно смотреть исходники

**Comment by ArsenShnurkov** [comment]
Спасибо, действительно куцый. И с потоками - это проблема, она не решилась.

**Comment by khorevaa** [comment]
@ArsenShnurkov  есть еще либо от меня для создания консольных приложений https://github.com/khorevaa/cli.

**Comment by khorevaa** [comment]
Пример можно посмотреть вот тут https://github.com/silverbulleters/ovm

**Comment by ArsenShnurkov** [comment]
Отлично, что есть целых два варианта библиотек для парсинга аргументов. Однако в документации к примеру не вижу работу со стандартными потоками (редиректами в частности).

**Comment by khorevaa** [comment]
@ArsenShnurkov ну есть повод сделать PR в любую из либ. Вопрос только зачем нужен данный функционал - пока не был востребован

**Comment by khorevaa** [comment]
Я думаю работа с потоками  ввода и вывода это уже конкретная функциональность приложения или отдельной либы упрощающей работу с потоками. ..

**Comment by ArsenShnurkov** [comment]
> пока не был востребован

мне нужен. Ведь ни одну консольную утилиту без него не написать по-юниксвейному.

> есть повод сделать PR

Я выше писал про лапки.

**Comment by khorevaa** [comment]
@ArsenShnurkov не понятно что ты имеешь в виду... может работу с Сокетами ?  Все понял. - это к движку  оскрипт...

**Comment by ArsenShnurkov** [comment]
Я имею в виду
https://msdn.microsoft.com/en-us/library/system.console.in.aspx
https://msdn.microsoft.com/en-us/library/system.console.out.aspx
https://msdn.microsoft.com/en-us/library/system.console.error.aspx

**Comment by khorevaa** [comment]
Да это я понял. Вообще при создании процесса из оскрипт есть возможность перехвата  потоков...

**Comment by ArsenShnurkov** [comment]
> при создании процесса из оскрипт есть возможность перехвата потоков...

верно, но это не то, что мне нужно.

**Comment by EvilBeaver** [comment]
@ArsenShnurkov работы с собственными stdin/stdout у движка нет. А задача на эту функциональность есть, создавал ее по наводке @awa15 я.

**Comment by ArsenShnurkov** [comment]
Спасибо.
