### ISSUE TITLE
Работа со stdin/stdout самого процесса

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#746]
Был такой разговор и заявка от @awa15, но в issues не нашел. Фиксирую:

Требуется умение читать и писать собственные потоки ввода/вывода

    cout << "bla";
    cin >> &variable;

См. также #745

**Comment by ArsenShnurkov** [comment]
Ня!

**Comment by ArsenShnurkov** [comment]
и с stderr тоже.

**Comment by EvilBeaver** [comment]
Ну разумеется. поленился писать просто :)

**Comment by ArsenShnurkov** [comment]
Это, конечно, круто, но так лень проверять, кто бы знал...
