### ISSUE TITLE
Признак из встроенного языка - это скомпилированное .exe или нет

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#747]
Для определения возможности подключения файлов необходим данный признак

**Comment by EvilBeaver** [comment]
СтартовыйСценарий() будет содержать путь к EXE, а не к OS

**Comment by khorevaa** [comment]
@EvilBeaver  Немного не понял! А с чем ее сравнивать тогда?

**Comment by dmpas** [comment]
@khorevaa имеется в виду, что берёшь СтаровыйСценарий(), получаешь из него путь к файлу и смотришь расширение файла - оно или `os`, или `exe`.
Впиливать изменения в движок сейчас нецелесообразно - я надеюсь, мы впилим концепт Макетов, которые по замыслу должны одинаково работать в обоих вариантах

**Comment by khorevaa** [comment]
@dmpas спасибо понял. Макетов не хватает пришлось в либе yaml придумать способ запаковки
