### ISSUE TITLE
Отладчик: Сдвиг строки таблицы

### ISSUE THREAD

**Issue by fominov** [EvilBeaver/OneScript#748]
![default](https://user-images.githubusercontent.com/284130/39398813-131baf3a-4b1c-11e8-9f8b-33b2476a61b3.png)
Почему происходит сдвиг? При записи в строку таблицы из соответствия в следующий реквизит записывается предыдущий, а в первом Неопределено.

```
Для каждого Строка Из JSONПродукцияТЗ Цикл
	НоваяСтрока = ПродукцияТЗ.Добавить();//Номенклатура
	А=Строка.Получить("НомерСтроки");
	Номенклатура = Строка.Получить("Номенклатура");
	Характеристика = Строка.Получить("Характеристика");
	Количество = Строка.Получить("Количество");
	Спецификация = Строка.Получить("Спецификация");
	КлючСвязи = Строка.Получить("КлючСвязи");
	НоваяСтрока.Номенклатура = Номенклатура;
	НоваяСтрока.Характеристика = Характеристика;
	НоваяСтрока.Количество = Количество;
	НоваяСтрока.Спецификация = Спецификация;
	НоваяСтрока.КлючСвязи = КлючСвязи;
КонецЦикла;
```

Так тоже самое.

**Comment by nixel2007** [comment]
Скорее всего глючит показ переменных в отладчике. Проверьте на равенство через Сообщить()

**Comment by EvilBeaver** [comment]
Да, полагаю, что это глюк отладчика. @fominov если дадите простой пример, воспроизводящий ошибку - будем благодарны и сможем быстро починить.

**Comment by fominov** [comment]
@EvilBeaver 

```
рр = Новый ТаблицаЗначений;
рр.Колонки.Добавить("ГУИД");
рр.Колонки.Добавить("Номенклатура");
рр.Колонки.Добавить("Характеристика");

Для Счетчик = 0 По 10 Цикл
	фф = рр.Добавить();
	фф.ГУИД = Счетчик;
	фф.Номенклатура = Счетчик+1;
	фф.Характеристика = Счетчик+2;
КонецЦикла;
```

**Comment by EvilBeaver** [comment]
@fominov код понятен, спасибо. А как смотреть на ошибку? В какой момент тормозить отладчик, на какой строке?

**Comment by fominov** [comment]
@EvilBeaver на строке `фф.ГУИД = Счетчик;`, и дальше шаг, в отладчике первый реквизит не отображает, а второй выводит для первого
