### ISSUE TITLE
Не хватает памяти System.OutOfMemoryException

### ISSUE THREAD

**Issue by fominov** [EvilBeaver/OneScript#749]
Внешнее исключение (System.OutOfMemoryException): Выдано исключение типа "System.OutOfMemoryException"
Процесс занял всего 1250 мегабайт памяти и выдает ошибку. Как увеличить количество возможной занимаемой памяти?

**Comment by EvilBeaver** [comment]
А можно кусок кода?
Кажется, что в .NET в отличие от Java нет явного дефолтного ограничения памяти...
Или я вру? @dmpas ничо не слышал такого?

**Comment by dmpas** [comment]
не, не слыхал. Надо курить доки по .net платформе. Тут на стороне односкрипта ничего не сделать, я думаю.

**Comment by fominov** [comment]
@EvilBeaver 
http://qaru.site/questions/161718/is-there-a-memory-limit-for-a-single-net-process/926816#926816
ограничение 2Гб для 32 битного приложения, я так понимаю 64 битного onescript нету?

**Comment by dmpas** [comment]
> ограничение 2Гб для 32 битного приложения

всяко не на одном гигабайте должно падать. Если только и правда прога не пытается за раз ещё плюс гиг откушать.

> я так понимаю 64 битного onescript нету?

в поставке нет. Руками можно собрать - технически проблем нет.

**Comment by fominov** [comment]
@dmpas 
я так понял что 600 мегабайт сам .net забирает, остается 1400, но до нее он не расширяет, видимо требует больше чем может взять.

**Comment by dmpas** [comment]
> я так понял что 600 мегабайт сам .net забирает

такого точно нет. Сам .net просто так себе такие объёмы не забирает - только на уровне прикладного кода какая-нибудь библиотека может такое съесть.

Был бы пример кода, можно было бы как-то его проанализировать.

**Comment by fominov** [comment]
Вот пример кода, с этим примером до 1720 мегабайт доходит

```
Процедура Заполняем(Варианты)
	Для КоличествоВариантов = 1 По 100 Цикл
		
		НовыйВариант = Варианты.Добавить();
		вв = Новый ТаблицаЗначений;
		вв.Колонки.Добавить("А");
		вв.Колонки.Добавить("Б");
		вв.Колонки.Добавить("В");

		Для Счетчик = 0 По 10000 Цикл
			Вариант = вв.Добавить();
			Вариант.А = Счетчик;
			Вариант.Б = Счетчик+1;
			Вариант.В = Счетчик+2;
		КонецЦикла;

		НовыйВариант.Вариант = вв;
	КонецЦикла;
КонецПроцедуры

рр = Новый ТаблицаЗначений;
рр.Колонки.Добавить("Вариант");

Пока Истина Цикл
	НовыеВарианты = рр.СкопироватьКолонки();
	Заполняем(НовыеВарианты);
	Для каждого Строка Из НовыеВарианты Цикл
		НовыйВариант = рр.Добавить();
		ЗаполнитьЗначенияСвойств(НовыйВариант, Строка)
	КонецЦикла;
	Сообщить("" + ТекущаяДата() + " Количество вариантов " + рр.Количество());
КонецЦикла
```

**Comment by EvilBeaver** [comment]
Если я правильно понял код, то он бесконечно создает таблицы значений. Рано или поздно оно, разумеется, съест всю память, да.

32-битный процесс имеет 2 Гб в пределе, но реально ему ОС выдаст меньше - часть займет код библиотек, драйверов, etc

Вам нужно пересобрать oscript.exe для 64-битной архитектуры.

**Comment by dmpas** [comment]
ну, 1720 - это нормально. Если принять во внимание, что под коллекции память перевыделяется с коэффициентом 1.5, то после 1720 будет переполнение, но после 1250 его быть не должно: должно быть 1900, а уже потом - переполнение.

**Comment by fominov** [comment]
@EvilBeaver, @dmpas не осилил я сборку в 64 бита, как лучше всего сохранять таблицы куда нибудь, чтобы не тащить их в памяти с собой. Потому что этих таблиц у меня сотни тысяч могут быть, понятно, что все в памяти держать после обработки нет смысла. Но в конце они нужны чтобы результаты сравнить.

**Comment by dmpas** [comment]
@fominov самый очевидный вариант - сливать их в SQL.

**Comment by EvilBeaver** [comment]
Закрываю, т.к. ответ получен.
