### ISSUE TITLE
Доступность свойства ЭтотОбъект

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#750]
Свойство ЭтотОбъект должно быть доступно внутри модуля ScriptDrivenObject, но недоступно "через точку" от объекта.

Т.е. это приватное свойство.

**Comment by dvakor** [comment]
хм, а какой контекст проблемы? Проверил просто вроде работает как ты и описал :)

код файла test.os
```
ПодключитьСценарий("D:\tmp\test2.os", "МойОбъект");
Об = Новый МойОбъект();
Сообщить("Вызов снаружи");
Сообщить(Об.ЭтотОбъект);
```

код файла test2.os
```
Сообщить("Вызов внутри");
Сообщить(ЭтотОбъект);
```

Вывод:

```
PS D:\tmp> oscript.exe test.os
Вызов внутри
МойОбъект
Вызов снаружи
{Модуль D:\tmp\test.os / Ошибка в строке: 4 / Свойство объекта не обнаружено (ЭтотОбъект)}
```

**Comment by EvilBeaver** [comment]
Значит я это уже починил. Была такая вероятность.

**Comment by EvilBeaver** [comment]
Переоткрываю. В отладчике свойство ЭтотОбъект видно.

**Comment by EvilBeaver** [comment]
@ArchLord42RU можешь глянуть, почему в отладчик это свойство попадает?

**Comment by dvakor** [comment]
> @ArchLord42RU можешь глянуть, почему в отладчик это свойство попадает?

Без проблем. На недельке отпишусь

**Comment by dvakor** [comment]
И так:

Есть метод
`ScriptDrivenObject.GetPropCount() `
по которому потом отладчик выводит данные по свойствам,
возврашает количество свойств самого объекта (ownProp которые) + экспортные переменные.

Собственно ЭтотОбъект добавляется как own prop и поэтому в дальнейшем попадает в отладчик.

Надо еще чекнуть че там по видимости этих своих свойств, т.к. по факту то к нему обратиться то нельзя, пока пишу тут чтобы не забыть на чём остановился)

**Comment by EvilBeaver** [comment]
1С возвращает ownProp но не считает ЭтотОбъект - prop-ом
т.е. это локальная переменная модуля типа, не пропертя

**Comment by dvakor** [comment]
Такс, значит решил я вернутся к этому вопросу :)
У меня тут вопрос возник, а какова цель выпиливания этого из дебаггера, если я тебя верно понимаю, то это выводить только паблик свойства в дебаггере так (own \ не own пофиг)? Просто `GetPropCount()` в целом не учитывает видимость самой проперти и тут надо просто отдельно проверить она экспортная или нет :)

**Comment by EvilBeaver** [comment]
Цель - сделать как в 1С + убрать лишнее свойство, которое не несет смысла для пользователя, но занимает место на экране

**Comment by dvakor** [comment]
Вернулся к этому вопросу, и у меня вопрос, если просто сделать исключение в отладчике "ЭтотОбъект" (Что на мой взгляд в целом может быть не верно для кастомных объектов например), будет ок?:))

Просто тут очень много работы, а профита маловато, т.к. архитектура щас такая, что непонять без костылей это экспортная переменная или нет, через IRuntimeContextInstance, в который приводит метод AsObject().
Рабочий вариант с использованием IRuntimeContextInstance такой:

```
var obj = someCntx.AsObject();
try
  obj.FindProperty(propName);
catch
 //это приватное свойство
```
Но это из разряда костылей для ДЗ, на которой ты поругался.

По хорошему надо бы в IRuntimeContextInstance метод добавлять `GetPropertyInfo()`, по аналогии с `GetMethodInfo()`

**Comment by EvilBeaver** [comment]
Тогда ставим на заморозку. Не такая уж критичная штука. Спасибо за анализ!
