### ISSUE TITLE
Процедура Метод(Парам = -1) 

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#752]
```
Процедура Метод(Парам = -1)

КонецПроцедуры
```

Не компилируется отрицательный литерал в параметре по умолчанию

**Comment by Mr-Rm** [comment]
В OneScript сейчас вообще нет отрицательных литералов. И, насколько можно видеть, в 1С - тоже нет.
Поведение 1С при задании значения параметра по умолчанию в некоторых случаях явно ошибочно. Следует ли учитывать все варианты для 100% взаимной совместимости?

**Comment by dmpas** [comment]
@Mr-Rm 
> Поведение 1С ... в некоторых случаях явно ошибочно

можно пример?

> Следует ли учитывать все варианты для 100% взаимной совместимости?

да, нужно стремиться к совместимости.

**Comment by Mr-Rm** [comment]
```
Процедура Метод( парам = -истина ) //  нет ошибки !
	сообщить("в методе:");
	сообщить(парам);
КонецПроцедуры

пар = -истина;
сообщить("в модуле:");
сообщить(пар);
Метод();
```
в модуле:
-1
в методе:
Да

**Comment by Mr-Rm** [comment]
Распишу подробнее для всех типов.
Вот это нормально и ожидаемо:
```
Процедура Метод( парам = -7 ) //  ок
Процедура Метод( парам = -
 // это не литерал
 7 ) //  необычно, но ок
Процедура Метод( парам = -"7" ) //  ошибка "Ожидается числовая константа"
Процедура Метод( парам = -'00010101' ) //  ошибка "Ожидается числовая константа"
```
А вот это странно:
```
Процедура Метод( парам = -истина )
Процедура Метод( парам = -Неопределено )
Процедура Метод( парам = -Null )
```
Причем параметр сохраняет соответствуюший тип и значение.
То же самое для унарного '+'.  ( Которого в OneScript просто нет. `ч = +2` - "Ошибка в выражении")

**Comment by nixel2007** [comment]
> А вот это странно:

По-моему вполне очевидно, что знак минус и число вместе не воспринимается как единый литерал в любом случае. в определении процедуры в качестве значения параметра допустимо иметь литерал с необязательным унарным минусом.

**Comment by Mr-Rm** [comment]
Поскольку формальной грамматики 1С BSL у нас нет (или есть?), выяснять приходится эмпирически.

> знак минус и число вместе не воспринимается как единый литерал в любом случае

Преобразование строк и разбор кода идет по разным правилам:
```
ч=Число("-7"); // ок 
ч=Число("- 7"); // ошибка в рантайме: "Преобразование значения к типу Число не может быть выполнено"
Выполнить("ч= - 7");  // ок
```
> в качестве значения параметра допустимо иметь литерал с необязательным унарным минусом

Литерал числового типа - да. Строки и даты отвергаются с ошибкой "Ожидается _числовая_ константа" - тоже  верно. Но логично, что для булева и "пустых" типов тоже должна быть ошибка.
И еще об унарном минусе в выражениях:
```
ч=-(-7); //  ок
ч=- -7; //  ошибка компиляции: "Ожидается выражение"
```
Двойной унарный минус парсером не принимается, в отличие от многих других языков.
Вопрос в том, стоит ли в точности повторять нелогичную/некорректную работу исходной платформы.

**Comment by EvilBeaver** [comment]
Позвольте уточнить: все эксперименты с парсером неплохо бы сравнивать с 1С - как там работает, а как не работает.

Я из переписки так и не понял - что есть ошибка движка, а что - просто занятный факт, который в 1С  работает так же, как и в 1Скрипте.

**Comment by Mr-Rm** [comment]
Да, стоит пояснить еще раз, по порядку.

- итак, движок OneScript не принимает минус у значения параметра по умолчанию;
- по исходному коду (ScriptEngine.Compiler.Compiler.BuildParameterDefinition() ) видно, что действительно, минус здесь не обрабатывается никак;
- требуется исправление движка, совместимое с платформой 1С;
- все дальнейшие эксперименты - выяснение, как эта конструкция работает в 1С, особенно в нестандартных вариантах;
- выяснилось, что поведение 1С в некоторых случаях не описано в документации и не соответствует ожидаемому;
- вопрос: стоит ли переносить все найденные особенности 1С в OneScript?

Кроме того, обнаружилось полное отсутствие в OneScript унарного '+'.

**Comment by EvilBeaver** [comment]
> требуется исправление движка, совместимое с платформой 1С

Безусловно

> Кроме того, обнаружилось полное отсутствие в OneScript унарного '+'

Да, его нет. По идее, он нужен, но я не до конца понимаю, как его нужно реализовывать. Мне нужен какой-то приемочный тест, демонстрирующий и верифицирующий работу унарного плюса.

> опрос: стоит ли переносить все найденные особенности 1С в OneScript

Не думаю. Только однозначно полезные.

P.S. спасибо за исследование!

**Comment by Mr-Rm** [comment]
Исправление движка для параметра по умолчанию, 1С-совместимое, я набросал. Надо бы оформить по-нормальному...

Про унарные плюс и минус:
В 1С, вопреки описанию, числовых литералов со знаком нет. Код вида `-7` всегда транслируется как выражение в `PushConst`, где значение константы равно 7, и последующий ` Neg`. OneScript работает так же.
Унарный плюс в 1С перед выражением или литералом любого вида всегда вызывает функцию преобразования в число. Т.е. из `+7` получается `PushConst` и `Numeric`. 
В OneScript такой унарный плюс можно добавить буквально сделав copypaste в паре-тройке мест. 
Но все описанное слабо согласуется с официальной документацией:
> Число (Number)
> Литералы:
> Набор цифр, написанных непосредственно в тексте модуля вида:
> [+|-]{0|1|2|3|4|5|6|7|8|9}[.{0|1|2|3|4|5|6|7|8|9}]

Ни у 1С, ни у OneScript в таблице констант после компиляции не бывает отрицательных числовых значений.

**Comment by EvilBeaver** [comment]
@Mr-Rm исправления удобнее всего присылать пулреквестом
