### ISSUE TITLE
ЗаписатьЦелое16 записывает 4 байта вместо двух

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#757]
БуферДвоичныхДанных.ЗаписатьЦелое16 записывает 4 байта вместо двух

**Comment by dmpas** [comment]
Эта штука убила мне вечер.

**Comment by Mr-Rm** [comment]
Исправить это просто. Но, как всегда, вопросы о тонкостях:
1. Должно ли падать `БДД.ЗаписатьЦелое16(0,65535); // ок в 1С` или всё же `БДД.ЗаписатьЦелое16(0,-1);` ?
2. `БДД.ЗаписатьЦелое16(0,1.5);` должно падать или автоматически округляться, как реализовано сейчас?
Аналогичные вопросы по ЗаписатьЦелое32 и ЗаписатьЦелое64.

**Comment by dmpas** [comment]
> Описание: Записать целое 16-битное положительное число в заданную позицию.
> Если значение не помещается в 16 бит, будет вызвано исключение. 

То есть, число `[0..2^нужныебиты)`, дробная часть отбрасывается.

**Comment by Mr-Rm** [comment]
С этим понятно, надо править. А округление? 1С на нецелых падает.

**Comment by dmpas** [comment]
> 1С на нецелых падает.

@Mr-Rm тогда и мы должны падать, мне кажется.

**Comment by EvilBeaver** [comment]
Согласен. Нецелые - это "неверный тип аргумента" по идее

**Comment by Mr-Rm** [comment]
Тогда это касается многих функций. Типы параметров менять на IValue и проверять на соответствие.

**Comment by Mr-Rm** [comment]
Вопрос о строгости типизации м.б. стоит рассмотреть отдельно и подробнее.
`БДД.ЗаписатьЦелое16("2","515");` - тоже работает, как с числами.

**Comment by dmpas** [comment]
>  Типы параметров менять на IValue и проверять на соответствие.

@Mr-Rm вот этого не надо делать. Тип должен оставаться int (long/...) или decimal. Все приведения и соответствия должны ложиться на плечи маршаллера.

**Comment by Mr-Rm** [comment]
Значит, понадобится переработка маршаллера. Сейчас типы переданных значений в нём не проверяются. Допускается, например, `ЗаписатьЦелое16( истина, "5" )`, поскольку всё успешно переводится в число.
Далее, если определить `WriteInt16(int position, ushort value, ...)`, то проверку value на диапазон 0..65535 нужно делать _до_ вызова функции.
С другой стороны, проверка на целочисленнность требуется не везде. `ЗаписатьЦелое16(0, 1.5)` - ошибка, а `ЗаписатьЦелое16(1.5, 1)` - допустимо. 
Это надо выяснять для _всех_ функций и тщательно прописывать типы. Неосторожные изменения в маршаллере могут разрушить очень многое.

**Comment by EvilBeaver** [comment]
То, что "5" маршаллится в 5 - это ошибка. Но тут по сути вот: https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs#L65

Реализация AsNumber в строке приводит его к числу. Не знаю, насколько это правильно. По-моему, это для ф-ии Число() только нужно в явном виде, а в остальных случаях вредит.

**Comment by Mr-Rm** [comment]
Большинство встроенных функций и методов стандартных объектов сильно типизированы - если указан тип параметра Число, то при передаче строки или даже булева (которое в выражениях спокойно приводится к числу) будет ошибка рантайма. 

`ContextValuesMarshaller.ConvertParam()` стоит изменить, чтобы это учитывалось. Автоматичекое приведение через AsNumber, AsString и т. п. не подходит. А в случае ошибки выдаёт неверную диагностику о невозможности пребразования значения вместо неверного типа параметра.

`WriteInt16( position, value )` и прочие представляют редкий случай, когда параметр `value` должен быть не просто числового типа, а обязательно неотрицательным целым, ограниченным сверху. Здесь возможно либо объявление параметра как `decimal` и проверка внутри функции, либо использование системы типов C# и специальный маршаллинг в `ushort`/`uint`/`ulong` с проверкой до вызова.
Да и `position` тоже, по логике, должен быть беззнаковым. И не только в этих функциях...

**Comment by Mr-Rm** [comment]
Нет, всё хуже. Упустил очевидное, напр. `Сообщить()`. Надо проверять ещё.
