### ISSUE TITLE
Не корректно считается покрытие условий Если

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#758]
В статистику попадает только последний проход. (по условию)

**Comment by dmpas** [comment]
@khorevaa дашь наглядности?

**Comment by khorevaa** [comment]
ммм. Дам. 
Берем репо https://github.com/khorevaa/oscript-coverage клонируем.

Выполняет в каталоге `opm run coverage`

В отчетах оставется не покрытой строка класса `ГенераторОтчетаGenericCoverage` [27](https://github.com/khorevaa/oscript-coverage/blob/develop/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%93%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%9E%D1%82%D1%87%D0%B5%D1%82%D0%B0GenericCoverage.os#L27)

Хотя она вызывается 100% т.к. всех теги XML закрыты. 

Для наглядности можно пройтись отладчиком через запуск файла `./tasks/test.os`

**Comment by khorevaa** [comment]
Хм... Сейчас покрылась тестом.... странно

**Comment by khorevaa** [comment]
@dmpas  Пока отбой.

**Comment by khorevaa** [comment]
@dmpas  Это мой косяк. Ошибки нет.
