### ISSUE TITLE
Непонятная ошибка функции ЗаполнитьЗначенияСвойств

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#759]
* клонируем репо https://github.com/nixel2007/moskito
* чекаут ветки develop
* oscript test.os
...
* ~profit~ fail

```
{Модуль D:\git\nixel2007\moskito\Модули\Мок.os / Ошибка в строке: 102 / Внешнее исключение (System.ArgumentOutOfRangeException): Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
```

```
PS D:\git\nixel2007\moskito> oscript -v
1.0.21.237
```

**Comment by Mr-Rm** [comment]
Ошибка в коде функции ScriptEngine.HostedScript.Library.SystemGlobalContext.FillPropertyValues(): вместо 
`if(source.IsPropReadable(propIdx) && acceptor.IsPropWritable(propIdx))`
должно быть
`if(source.IsPropReadable(srcPropIdx) && acceptor.IsPropWritable(propIdx))`
Но чтобы разобраться с этой функцией полностью, нужно уточнить, какое должно быть поведение ЗаполнитьЗначенияСвойств(), если несуществующие свойства источника или приемника будут указаны в параметрах filledProperties или ignoredProperties.

**Comment by nixel2007** [comment]
Если есть несуществующие свойства в filled Properties, то материнская платформа кидает эксепшен. Про игнорируемые не помню точно, но было бы логично поступать так же.

**Comment by Mr-Rm** [comment]
Да, верно, исключения бросаются во всех случаях.
Найдены ещё такие несоответствия:
1. В строках с именами свойств можно вставлять запятые в любом месте и в любом количестве, т.е. `",,Имя,,,Фамилия,"` - работает. Но в OneScript между запятыми могут быть пробелы (`"Имя,  ,Фамилия"`), а платформа падает с исключением:
> Ошибка при вызове метода контекста (ЗаполнитьЗначенияСвойств): Недопустимое значение параметра (параметр номер '3') (Поле '' объекта 'Структура' не обнаружено)

Здесь, пожалуй, стоит сохранить текущее поведение.

2. В описании функции:
> Если указаны копируемые свойства, то в заполнении участвуют только они, параметр <ИсключаяСвойства> игнорируется.
> В противном случае, если указан параметр <ИсключаяСвойства>, свойства перечисленные в нем, исключаются из обработки.

В 1С `ЗаполнитьЗначенияСвойств(Приемник, Источник, "Фамилия,Имя","Имя")` копирует оба свойства, в OneScript - только "Фамилия".
Это надо либо исправлять для совместимости, либо явно документировать.

to @EvilBeaver: следует ли выделять подобное в отдельное issue?

**Comment by EvilBeaver** [comment]
@Mr-Rm наверное это лучше в отдельное

**Comment by EvilBeaver** [comment]
@nixel2007 @Mr-Rm судя по всему, это уже исправлено и можно закрыть?

**Comment by nixel2007** [comment]
@EvilBeaver на моих кейсах работает, да.

**Comment by Mr-Rm** [comment]
Да, исправлено.
