### ISSUE TITLE
Неполное описание ошибки

### ISSUE THREAD

**Issue by vasvl123** [EvilBeaver/OneScript#761]
а = '123';

{Модуль  / Ошибка в строке: 0 / Преобразование к типу 'Дата' не поддерживается}

**Comment by dmpas** [comment]
а что не так?

**Comment by vasvl123** [comment]
не пишет какой модуль и номер строки

**Comment by EvilBeaver** [comment]
Интересно. @vasvl123 спасибо!

**Comment by Mr-Rm** [comment]
to @EvilBeaver: это надо объединить с #767

**Comment by EvilBeaver** [comment]
На версии 1.0.21 больше не воспроизводится, благодаря PR от @Mr-Rm
