### ISSUE TITLE
Несовместимое поведение функции ЗаполнитьЗначенияСвойств

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#763]
1. Функция `ЗаполнитьЗначенияСвойств(<Приемник>, <Источник>, <СписокСвойств>, <ИсключаяСвойства>) ` должна игнорировать параметр <ИсключаяСвойства>, если задано значение параметра <СписокСвойств>. Сейчас - учитывается. Нужно либо исправлять, либо явно документировать.
2. Если свойство, заданное в параметре <ИсключаяСвойства> отсутствует в <Приемнике>, должно вызываться исключение. Сейчас - пропускается. Нужно исправлять.
3. В строковых параметрах, содержащих списки свойств, разделяющие имена запятые могут повторяться в любом месте и в любом количестве (напр. `",,Имя,,,Фамилия,"`). Но если запятыми есть пробелы, то исходная платформа выдает ошибку `Поле '' объекта '<Тип Объекта>' не обнаружено`.
OneScript отрабатывает нормально. Это, видимо, стоит оставить.

**Comment by EvilBeaver** [comment]
По пункту 1 - в 1С разве так же?

По пункту 2 - это в 1С так работает, даже есть у них зарегистрированная ошибка, но ей уже многолет. Я просто не стал это повторять, т.к. считал странным поведением. Это реально надо?

По пункту 3 - согласен, надо оставить наш вариант

**Comment by Mr-Rm** [comment]
Все написанное соответствует документации 1С и проверялось на платформе 8.3.12.1440.
По п.3 - Ок.
П.2: оба варианта  имеют основания, надо решить, нужна ли здесь 100%-я совместимость.
П.1: в 1С при заданном <СписокСвойств> список <ИсключаяСвойства> игнорируется полностью, даже не проверяется на существование свойств, как рассмотрено в п.2. Опять же, логика в том, чтобы учитывать оба списка, тоже есть. Снова вопрос о необходимости полной совместимости.

(Пока писал, придумал, что еще стоит проверить по первому пункту, и в 1С, и в Onescript.)
Вообще, тесты в Onescript составлены "по-доброму", много вариантов не проверяется.

**Comment by Mr-Rm** [comment]
Автоматическое приведение параметров к строке вызывает баг:
```
Источник = Новый Структура("Нет", "ё");
Приемник = Новый Структура("Нет");
ЗаполнитьЗначенияСвойств(Приемник, Источник, ложь );
```
В результате Приемник.Нет == "ё"
1С падает: `Несоответствие типов (параметр номер '3')`. Там проверяется тип 3-го и 4-го (всегда!) параметров. Допускаются только Строка или Неопределено.

**Comment by EvilBeaver** [comment]
> Вообще, тесты в Onescript составлены "по-доброму", много вариантов не проверяется.

Мы были молоды и тестировали, как могли )

Будем ОЧЕНЬ рады пулреквесту с новыми тестами

**Comment by Mr-Rm** [comment]
Какие варианты выбираем для пп.1 и 2?

**Comment by EvilBeaver** [comment]
1 исправляем, 2 наверное лучше оставить. Я не могу придумать кейса, в котором данное поведение было бы полезным:

* Если в Приемнике нет свойства и его явно не надо заполнять, то выдать исключение "Свойство не обнаружено"
