### ISSUE TITLE
Фоновые задания

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#764]
Хочется функционала фоновых заданий в движке.

Запуск по определенному ключу или процедуре в коде. 

п.с. возможно просто добавление многопоточности - в каком то виде

**Comment by artbear** [comment]
>возможно просто добавление многопоточности

смешно, да :) `просто` и `многопоточность` рядом не употребляется :)

**Comment by dmpas** [comment]
> просто и многопоточность рядом не употребляется :)

@artbear вполне себе употребляются, пока не появляются "разделяемые ресурсы" - вот тогда "просто" улетает в мусор.

**Comment by khorevaa** [comment]
Ну в `golang` просто вызываешь `go` и далее имя метода с параметрами )) Предлагаю у нас сделать `os` и далее имя метода с параметрами ))

**Comment by dmpas** [comment]
@khorevaa вопрос, повторюсь, в разделении ресурсов. Синтаксис-то можно выдумать, концепции нет

**Comment by khorevaa** [comment]
@dmpas  Я тебя не понимать.. что за разделение ресурсов ... Кого делим и как...

**Comment by dmpas** [comment]
@khorevaa вот ты чего хочешь фоново распараллелить?

**Comment by nixel2007** [comment]
@khorevaa ты же фоновое задание хочешь с какими-то параметрами запустить? и это явно не строка, а например, массив? таблица значений? классы настроенные какие-нибудь?..

**Comment by khorevaa** [comment]
@dmpas  Я хочу распараллелить синхронизацию с хранилищем по нескольким репозиторием..
сейчас это возможно сделать запуская разные процессы. Т.к. дописать чтонить типа "ПотокКоманд" в 1commands, который будет уметь `ВыполнитьПараллельно(5)` 
А хочется просто запускать часть кода в отдельном потоке без генерации отдельного приложения

@nixel2007  Да захочу )) Ну можно это все копировать в процесс - как дубликаты....

**Comment by ghost** [comment]
@khorevaa то есть ты хочешь отказаться от jenkins ? 

Что касается фоновых заданий - то они тут https://github.com/EvilBeaver/OneScript.Web/blob/develop/examples/backgroundjobs/src/model/modules/%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%B8%D0%A4%D0%BE%D0%BD%D0%BE%D0%B2%D1%8B%D1%85.os

**Comment by khorevaa** [comment]
@allustin я не могу отказаться от того чего у меня нет. Но вообще смысл чутка другой... а именно многопоточное выполнение приложения и сервер сборок тут не причем

**Comment by arkuznetsov** [comment]
@allustin @dmpas Мне вот на ум приходит задача асинхронного запуска приложений, т.е. не ждать пока приложение выполнится, а подвесить "Новый ОписаниеОповещения("МойМетод")" и там уже анализировать вывод команды.
Не совсем фоновые задания, но параллельности добавляет.
Ну и в принципе, для будущих применений можно развить тему асинхронного вызова любых методов с обработкой результатов.

**Comment by dmpas** [comment]
@arkuznetsov через ОписаниеОповещения мне нравится, развивай мысль.

**Comment by arkuznetsov** [comment]
@dmpas 
Приблизительно так:

```bsl
// Основной код
МойОбработчик = Новый МойКлассОбработчик();

МойОбъект = Новый МойКласс();

ПараметрыОбработки = Новый Массив();

ОписаниеОповещения = Новый ОписаниеОповещения("МойМетодОбработки", МойОбработчик, ПараметрыОбработки);

Параметры = Новый Массив();

ВыполнитьАсинхронно(МойОбъект, "МойМетод", Параметры);

```

```bsl
// МойКласс.os

Функция МойМетод()
	Возврат "Это мой метод";
КонецФункции
```

```bsl
// МойКлассобработчик.os

Процедура МойМетодОбработки(ВозвращаемоеЗначение, ДополнительныеПараметры)
	Сообщить(ВозвращаемоеЗначение);
КонецПроцедуры
```

Дальше можно пофантазировать на тему свойства ассинхронности для экземпляра класса в целом. Там еще можно найти применение для аннотаций.

**Comment by artbear** [comment]
Пожалуйста, только не нужно `ОписаниеОповещения`

не нужен нам этот 1С-ский ад :(

**Comment by dmpas** [comment]
@artbear твои варианты? Ад от 1С хорош хотя бы тем, что уже придуман. А так, я тоже не в восторге

**Comment by nixel2007** [comment]
да бог с ним с синтаксисом. любая асинхронщина требует event loop,
сохранения контекстов и прочую "не на один вечер разработки" хрень

чт, 7 июн. 2018 г. в 12:30, Sergey Batanov <notifications@github.com>:

**Comment by dmpas** [comment]
> да бог с ним с синтаксисом

@nixel2007 тут замкнутый круг: чтобы взяться за евент луп и остальную хрень, нужна цель. Чтобы появилась цель, нужен синтаксис. Нафига пилить синтаксис, если вопрос не в нём и надо делать евент-луп.

Так что будет синтаксис - будет евент-луп. Не будет синтаксиса - не будет ничего

**Comment by arkuznetsov** [comment]
@artbear @dmpas Я исключительно с претензией на +/- совместимость с 1С.

**Comment by EvilBeaver** [comment]
Хаспада, почитайте сообщение Никиты про event-loop.

Вопрос фоновых в оскрипте очень простой - кто будет управлять временем жизни фоновых потоков, когда стартовый поток подошел к концу?

```bsl

Перем ЧтобыБылоВеселее;

Процедура МетодФонового()
     Для Сч = 1 По 10 Цикл
         ЧтобыБылоВеселее = ЧтобыБылоВеселее + 1;
         Приостановить(Сч * 2000);
     КонецЦикла;
КонецПроцедуры

Сообщить("Я начало стартового скрипта");
ЧтобыБылоВеселее = 0;
ФоновыеЗадания.Выполнить("МетодФонового");
ФоновыеЗадания.Выполнить("МетодФонового");
Сообщить("Я конец стартового скрипта");

```

Вопрос - что должно происходить после выполнения строки ```Сообщить("Я конец стартового скрипта");```?

**Comment by arkuznetsov** [comment]
@EvilBeaver Служба/демон :-) Ну или счетчик запущенных дочерних "потоков" и завершать, только когда счетчик обнулится (видимо еще какое-то TTL должно быть для принудительной остановки). Фоновые я не совсем могу придумать для чего использовать, а вот про асинхронные вызовы я выше написал.

**Comment by khorevaa** [comment]
@EvilBeaver Механизм сокетов.

**Comment by dmpas** [comment]
@arkuznetsov @khorevaa надо ответить на прямой вопрос:
> что должно происходить

варианты навскидку: 
* основной поток останавливается в ожидании
* основной поток гасит дочерние
* дочерние потоки вовсе не дочерние потоки, а самостоятельные процессы и живут своей жизнью после завершения главного потока
* исключение, формат Ц, дым из флоппи-привода, смс на короткий номер, стук в дверь.

**Comment by khorevaa** [comment]
@dmpas 
1. Процесс должен прекращаться
2. Процесс должен ждать `ФоновыеЗадания.ОжидатьЗавершения()` - тут просто ждать...
3. Процесс должен ждать `ФоновыеЗадания.ОжидатьЗавершения(КлючПроцесса)` - тут просто ждать... завершения процесса
4. Получение результатама выполнения `ФоновыеЗадания.ПолучитьРезультатВыполнения(КлючФоновогоЗадания)`
5. Ошибки выполнения фоновога задания писать в отдельный объект с возможностью получения.

У меня так получилось

**Comment by arkuznetsov** [comment]
@khorevaa А вот отладка со всем этим будет еще веселее чем в типовых 1С. :-)

**Comment by arkuznetsov** [comment]
@dmpas 

Основной процесс должен ждать пока не истечет TTL, потом гасить дочерние.
Вариант с отдельными процессами для асинхронных вызовов думаю не подойдет, т.к. нужен общий контекст выполнения.

**Comment by khorevaa** [comment]
@arkuznetsov кому надо отладит. Все развивается в усложнение...

**Comment by EvilBeaver** [comment]
Ок, идея с TTL, в принципе, мне нравится. А теперь вопрос с разделяемыми ресурсами. Меня бы устроил вариант, как в 1С - когда фоновое изолировано и параметры в него передаются сериализацией (глубокой копией). Но в случае с односкриптом, боюсь, этого будет мало. Глобальные ресурсы все равно существуют, в том числе и в подключенных пакетах.

**Comment by arkuznetsov** [comment]
@EvilBeaver Ты про то, что всем потокам будет доступно все, что есть в контексте скрипта и попытки менять одни и те же объекты/переменные?

Я бы предпочел такое запретить и изолировать контексты потоков, т.е. там должно быть доступнто, что было явно задано. Ну и все что явно задано передавать глубокой копией, без возможности доступа из породившего потока.

**Comment by dmpas** [comment]
> что было явно задано. 

@arkuznetsov подключенные библиотеки - они явно заданы? Их модули с глобальными переменными?

**Comment by arkuznetsov** [comment]
@dmpas Да, тут источник "феерических" глюков, а их нельзя как-нить сделать read-only для дочерних потоков? Ну или изолировать контексты (что, как мне кажется, существенно сложнее).

**Comment by dmpas** [comment]
> как-нить сделать read-only для дочерних потоков

вот так точно не стоит делать. Иначе, во-первых, смотря в код ни фига не понятно, как он отработает (хоть вводи &НаКлиенте да &НаСервере !), во-вторых, дочерние потоки таким образом по большому счёту лишаются возможности использовать библиотеки. Или библиотеки делать с расчётом на то, что будет выполняться в разном контексте. - Везде сплошные затыки.

**Comment by arkuznetsov** [comment]
@dmpas Это я с точки зрения упростить задачу, а не решать сразу в общем виде.
Я правильно понимаю, что проблема только в глобальных переменных, или есть еще что-то подобное?

**Comment by dmpas** [comment]
> проблема только в глобальных переменных

@arkuznetsov собственно, любое разделяемое состояние в любом его виде. Это может быть глобальная переменная, это может быть ссылка на какой-то объект, с которым работают сразу в двух потока.

**Comment by arkuznetsov** [comment]
> это может быть ссылка на какой-то объект, с которым работают сразу в двух 

@dmpas С этим как раз поможет глубокое копирование. Или ты против такого подхода?

Или ты про объекты, на которые ссылаются глобальные переменные?

**Comment by dmpas** [comment]
@arkuznetsov да, на объекты могут ссылаться глобальные переменные или какой-нибудь шарповый код в движке или компонентах

**Comment by arkuznetsov** [comment]
@dmpas А полностью контексты изолировать возможно?

**Comment by dmpas** [comment]
@arkuznetsov да, но это равносильно запуску отдельного процесса.

**Comment by arkuznetsov** [comment]
@dmpas А с отдельным процессом можно callback организовать в родительский процесс?

Может тогда так и надо делать? Т.е. условно "ВыполнитьАссинхронно()" из моего примера выше, будет создавать отдельный процесс и копировать контекст.

**Comment by dmpas** [comment]
@arkuznetsov ну, сейчас у процесса можно работать с потоком ввода и вывода. То есть, при желании, обратки можно сделать - и всё это без доработок движка, по идее.

**Comment by arkuznetsov** [comment]
> можно сделать - и всё это без доработок движка

@dmpas А вот тут можно какой-нить пример небольшой?
На тему, из основного скрипта запускаем отдельный процесс с другим скриптом, основной скрипт продолжает выполнение, по окончании "дочерний" скрипт вызывает метод основного и передает результаты.
Или мы что-то другое обсуждаем?

**Comment by dmpas** [comment]
@arkuznetsov ну, не совсем в таком виде. Сейчас можно сделать так:
основной скрипт запускает дочерний процесс, передав ему данные во входящий поток, дочерний процесс прочитал данные, обработал их, выдал результат в выходной поток. Основной процесс в это время делает своё дело, потом смотрит, что вернул дочерний процесс.

**Comment by arkuznetsov** [comment]
> Основной процесс в это время делает своё дело, потом смотрит, что вернул дочерний процесс

@dmpas А вот про этот момент поподробнее. Когда смотрит? Где смотрит?
Есть пример где-то?

**Comment by dmpas** [comment]
> Когда смотрит? Где смотрит?

в коде, в явном виде (то есть, да, без оповещения из-вне), в момент, когда нужен результат.

**Comment by tsukanov-as** [comment]
В повершеле есть фоновые задания. Мне кажется запуская на них отдельные процессы ванскрипт получится то же самое по сути что в 1С

ps Хотя руки еще не дошли попробовать
pss Вот иметь ванскрипт в повершеле как донет-объект было бы просто феерически удобно

**Comment by artbear** [comment]
Андрей сделал первичную реализацию https://github.com/EvilBeaver/OneScript/commit/1cc24e685495ec575eb65aaba47a7cfb9dc7bde5

**Comment by artbear** [comment]
и в https://github.com/artbear/1commands/pull/48 есть прототип для фоновых команд
