### ISSUE TITLE
Тип Соответствие

### ISSUE THREAD

**Issue by pallid** [EvilBeaver/OneScript#766]
в 1С для типа Соответствие значение - является необязательным параметром

в oscript 

```
Соответствие = Новый Соответствие;
Соответствие.Вставить("ИмяПоля");

``` 

Ошибка
```
Недостаточно фактических параметров
```

**Comment by pallid** [comment]
https://github.com/EvilBeaver/OneScript/blob/36c8480caaa342d2b827c210f49966be42ffcc34/src/ScriptEngine.HostedScript/Library/MapImpl.cs#L37

`public override void SetIndexedValue(IValue index, IValue val = null) `

**Comment by nixel2007** [comment]
А какое значение возвращает 1с при запросе этого ключа?

**Comment by pallid** [comment]
@nixel2007 Неопределено

**Comment by EvilBeaver** [comment]
Ок, принято

**Comment by Mr-Rm** [comment]
И ещё несовместимость: в 1С Соответствие[Неопределено]==Неопределено всегда, в т.ч. и после выполнения `Соответствие.Вставить(Неопределено, НекотороеЗначение);`
В OneScript получается Соответствие[Неопределено]==НекотороеЗначение
