### ISSUE TITLE
Не поддерживается литерал даты вида 'yyyyMMddHHmm'

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#767]
Не поддерживается литерал даты вида 'yyyyMMddHHmm'
Код `д='2008-06-07 23:59';`
дает ошибку _времени выполнения_
`Преобразование к типу 'Дата' не поддерживается`

**Comment by EvilBeaver** [comment]
По-моему, в 1С тоже так не работает. Нужны секунды. Или ошибаюсь?

**Comment by Mr-Rm** [comment]
Работает, проверял.

> Допускается при указании литералов типа Дата опускать значение секунд. В этом случае секунды будут равны 0.

Вообще, ошибки литералов стоит вынести в compile-time.

**Comment by EvilBeaver** [comment]
Принято. В compile-time это преобразуется в 

```
.loadAt: 10
.variableFrame:
.constants
0  :type: Date, val: 200806072359
```

а парсинг константы в значение выполняется во время создания LoadedModule. Т.е. это не совсем runtime, это сразу после компиляции. Но суть вопроса понятна, спасибо.

**Comment by Mr-Rm** [comment]
Чтоб выбрасывать "Некорректный литерал даты" из DateParserState, а не "Преобразование к типу 'Дата' не поддерживается" из ValueFactory
