### ISSUE TITLE
СимволыОтступа (IndentChars) в ЗаписьXML

### ISSUE THREAD

**Issue by otymko** [EvilBeaver/OneScript#768]
При использовании ЗаписьXML, как можно указать СимволыОтступа (IndentChars) вместо 4-х пробелов на знак ТАБ? 1С по умолчанию использует знак ТАБ.
Например - начальный файл из 1С выгружен, сравнение с файлом сформированный через OneScript.
![image](https://user-images.githubusercontent.com/11651847/41134948-458709ae-6af9-11e8-99ca-8e4fd93c7d5c.png)

Что можно с этим сделать? =)

**Comment by thedemoncat** [comment]
Не оно?
![image](https://user-images.githubusercontent.com/26283990/41135093-b236cd12-6af1-11e8-89ee-ed174e4626f0.png)

**Comment by otymko** [comment]
@ZhdanovR Нет. Это знаки в конфигураторе 1С. А меня интересует выгрузка в XML.

**Comment by dmpas** [comment]
Ковырну на праздниках

**Comment by otymko** [comment]
@dmpas Получается будет реализовано ПараметрыЗаписиXML и ЗаписьXML.Параметры на чтение/запись? =)

**Comment by dmpas** [comment]
Запись.параметры вроде ж только на чтение.

**Comment by otymko** [comment]
@dmpas Я ошибся)))

```
ЗаписьXML = Новый ЗаписьXML();		
ПараметрыЗаписиXML = Новый ПараметрыЗаписиXML("UTF-8", "1.0", Истина); 
ЗаписьXML.ОткрытьФайл(ИмяВременногоФайла, ПараметрыЗаписиXML);
```

Будет такая же конструкция, как из 1С?

**Comment by dmpas** [comment]
Ага

**Comment by dmpas** [comment]
Затянул чего-то. В эти выходные добью.

**Comment by otymko** [comment]
@dmpas было бы очень хорошо)

**Comment by dmpas** [comment]
@otymko погоняй сборку: http://build.oscript.io/job/1Script/view/change-requests/job/PR-773/lastSuccessfulBuild/artifact/built/

**Comment by otymko** [comment]
@dmpas в версии ниже отступы теперь работают, спасибо!) Но еще заметил следующее:
![image](https://user-images.githubusercontent.com/11651847/41503829-e6897066-7207-11e8-88c8-d7b348fc3c3f.png)
Символ BOM удаляется в любом случае. Пример кода:
```bsl
ЗаписьXML = Новый ЗаписьXML();		
ПараметрыЗаписиXML = Новый ПараметрыЗаписиXML("UTF-8", "1.0", Истина, Ложь, Символы.Таб);
ЗаписьXML.ОткрытьФайл(ИмяВременногоФайла, ПараметрыЗаписиXML, Ложь);
```
Так же (но эта проблема была ранее):
![image](https://user-images.githubusercontent.com/11651847/41503852-485c9dd6-7208-11e8-8d46-ffd0f64d8ab8.png)
между кавычкой и слешем в атрибутах onescript делает пробел.

**Comment by dmpas** [comment]
@otymko http://build.oscript.io/blue/organizations/jenkins/1Script/detail/PR-773/4/artifacts

**Comment by otymko** [comment]
@dmpas сейчас попробую

**Comment by otymko** [comment]
@dmpas с BOM теперь все хорошо. Удалось понять почему появляется пробел перед закрывающим слешем?

**Comment by dmpas** [comment]
> Удалось понять почему появляется пробел перед закрывающим слешем?

Собственно, всё просто до безобразия:
https://referencesource.microsoft.com/#System.Xml/System/Xml/Core/XmlTextWriter.cs,1159

пробел там захардкожен. Если принципиально, могу найти обходные пути, но это ещё время.

**Comment by otymko** [comment]
@dmpas из-за этого пробела при сборки xml через gitrules очень много расхождений. У меня сейчас есть костыль, но хотелось бы делать записьXML из коробки))

**Comment by dmpas** [comment]
@otymko ну тогда ждём ещё как минимум одни выходные 😃

**Comment by otymko** [comment]
@dmpas Хорошо. Буду ждать как Хатико=)))

**Comment by otymko** [comment]
@dmpas Есть новости?)

**Comment by dmpas** [comment]
@otymko не, больше пока не брался за это дело.

**Comment by dmpas** [comment]
@otymko http://build.oscript.io/blue/organizations/jenkins/1Script/detail/PR-773/6/artifacts
погоняй сборочку.

**Comment by otymko** [comment]
@dmpas сегодня)

**Comment by otymko** [comment]
@dmpas Теперь нет этих пробелов) Все огонь!

Только не могу понять с последним. Запись xml съедает символы в тесте:
![image](https://user-images.githubusercontent.com/11651847/41945001-10144472-79d5-11e8-9244-132bacf2cb5e.png)
В первом варианте есть нет пустых строк. Только 2 строки кода. Но в конце тега делается перенос
Во втором варианте есть первая пустая строка. Она передается, но перенос строки в конце все равно есть.
Второй пример посимвольно выглядит так:
![image](https://user-images.githubusercontent.com/11651847/41945119-a150cd3e-79d5-11e8-8537-fce0dd93be1b.png)
Добавляет ли записьxml перенос строки? При выгрузке из 1С такого не происходит.

**Comment by nixel2007** [comment]
записьxml добавляет перенос строки при вызове метода "ЗаписатьСтроку". без переноса есть обычный "записать"

**Comment by otymko** [comment]
@nixel2007 Для этих тегов я использую "ЗаписатьТекст". Просто метода "Записать" в ЗаписьXML я не вижу..

**Comment by dmpas** [comment]
Ковыряем дальше, чо...

**Comment by otymko** [comment]
@dmpas Добавлю себе пункт - разобраться как поднять окружение для доработка Onescript..

**Comment by nixel2007** [comment]
@otymko глобально кроме vs, настроенную на .net/rider больше ничего не нужно. Есть ругань на wsix, но не можно игнорироватт

**Comment by otymko** [comment]
@nixel2007 Вот и надо поковыряться)

**Comment by dmpas** [comment]
@otymko ЗаписатьТекст не добавляет перенос строки. Добавил тест на этот случай.

**Comment by EvilBeaver** [comment]
@dmpas уже не WIP?

**Comment by dmpas** [comment]
@EvilBeaver там ещё сонар ублажить надо. В процессе.

**Comment by EvilBeaver** [comment]
На сонаре проекта нету уже AFAIK

**Comment by dmpas** [comment]
То-то я его найти не могу... но брань же льётся откуда-то???

**Comment by nixel2007** [comment]
И ссылки в комменте на sonar.silverbulleters.org ведут. @allustin?

**Comment by EvilBeaver** [comment]
Я пролазил под админом сонар, не нашел проект... Ок, беру таймаут на выяснение. После аварии сонар чистился и восстанавливался. Не исключены половинчатые ремонты

**Comment by ghost** [comment]
@EvilBeaver в бэкапах все. А oscript лился на Сонар облачный также ??????

@EvilBeaver можно я создам хост opensonar. и всё открытое пусть лъется туда. А то у нас получается драка за "воркер"

**Comment by EvilBeaver** [comment]
Да, было бы супер

**Comment by EvilBeaver** [comment]
@dmpas пыщ! Успеешь это добить к 1.0.21?

**Comment by dmpas** [comment]
@EvilBeaver ты взял таймаут разобраться с сонаром - разобрался?

**Comment by EvilBeaver** [comment]
Наполовину )) @allustin запустил параллельный сонар.

**Comment by dmpas** [comment]
@EvilBeaver ты тогда таки дай отмашку - ждать сонара и ублажать его хотелки или забить и оставить, как есть.

**Comment by EvilBeaver** [comment]
забить конечно. мы же 1сники. Пользователи тестируют лучше чем сонар

**Comment by ghost** [comment]
@dmpas - opensonar с бранч.плагином

**Comment by nixel2007** [comment]
ERR_NAME_NOT_RESOLVED

**Comment by ghost** [comment]
@dmpas @EvilBeaver

развернул на отдельной инфраструктуре с ништяками типа бранч-плагина https://opensonar.silverbulleters.org/dashboard?id=add

дальше можно заниматься переносом скриптов в свободное от работы время

под проект создана заглушка https://opensonar.silverbulleters.org/dashboard?id=onescript
