### ISSUE TITLE
ЗаписьДанных.ЗаписатьЦелое16 падает с ошибкой

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#774]
ЗаписьДанных.ЗаписатьЦелое16 падает с ошибкой при _любом_ значении параметра.
Причина - неправильная работа `ContextValuesMarshaller` с параметром типа `short`.

**Comment by EvilBeaver** [comment]
> неправильная работа ContextValuesMarshaller с параметром типа short

А в чем она заключается?

**Comment by Mr-Rm** [comment]
https://github.com/EvilBeaver/OneScript/blob/3e38282dfa6fc7b94a6285c04b3b60ca9c3b2040/src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs#L16
`ConvertParam<T>(IValue value)` вызывает `object valueObj = ConvertParam(value, type);`,
там short (и sbyte тоже) приводятся к int:
```
            else if (type == typeof(int) || type == typeof(short) || type == typeof(sbyte))
            {
                valueObj = (int)value.AsNumber();
            }

```

А потом `return (T)valueObj;` пытается привести `object valueObj ` из _boxed_ int к short и выбрасывает InvalidCastException.

**Comment by EvilBeaver** [comment]
Исправлено
