### ISSUE TITLE
Сделать параметры конструктора ИнформацияОбОшибке необязательными

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#777]
Хотя бы второй.

Здесь https://github.com/EvilBeaver/OneScript/blob/7d39a52400cb7639de70ff11e7a3e6d8cff3e12b/src/ScriptEngine/Machine/Contexts/ExceptionInfoContext.cs#L197
и здесь https://github.com/EvilBeaver/OneScript/blob/d1bf7fba64c4049691a508bef9777ac65c3782a8/src/ScriptEngine/Machine/Contexts/ExceptionTemplate.cs#L28

**Comment by asosnoviy** [comment]
Без второго пораметра оно же не отличается от 'ВызватьИсключение "Описание"'

**Comment by nixel2007** [comment]
По смысловой нагрузке - не отличается. но в москито нельзя написать ВызватьИсключение внутри метода :)

**Comment by EvilBeaver** [comment]
@nixel2007 приведи пример кода - как ты хочешь, чтобы можно было делать?

**Comment by nixel2007** [comment]
@EvilBeaver Новый ИнформацияОбОшибке("Текст ошибки")

**Comment by EvilBeaver** [comment]
Новый ИнформацияОбОшибке("Текст ошибки", Неопределено)??

**Comment by nixel2007** [comment]
@EvilBeaver, да это понятно. Но зачем передавать параметр, если он тебе не нужен?

**Comment by EvilBeaver** [comment]
Это же как бы расширение, относительно 1С - параметризованное исключение. Значит параметр параметризованного исключения - обязательный параметр. Логика такая.
