### ISSUE TITLE
Поддержка аннотаций свойств

### ISSUE THREAD

**Issue by asosnoviy** [EvilBeaver/OneScript#780]
В `ПолучитьТаблицуСвойств()` колонка `Аннотации` есть , но значений  в ней нет.

**Comment by asosnoviy** [comment]
Sergey Batanov @dmpas 11:53
@asosnoviy нет.
мы пока не пришли к единому пониманию, что есть "свойство" в односкрипте.

Alexey Sosnoviy @asosnoviy 11:54
интересный поворот =)

Sergey Batanov @dmpas 11:54
плюс в движке под аннотации свойств надо много чего подперепилить, потому пока решили посмотреть, как зайдут аннотации методов - с ними вопросов нет

Alexey Sosnoviy @asosnoviy 11:54
искренне считал что Перем ИмяПеременной в классе это именно свойство

Sergey Batanov @dmpas 11:54
ну, кто-то скажет, что это всё же "поле", а не "свойство"

Alexey Sosnoviy @asosnoviy 11:54
Хорошо, спасибо!
смутили наличие колонки в ПолучитьТаблицуСвойств

Sergey Batanov @dmpas 11:55
не, ну оно же будет когда-нибудь. оно даже было запилено, но потом выпилено.

Alexey Sosnoviy @asosnoviy 11:55
о как

Nikita Gryzlov @nixel2007 12:02
чистых свойств в оскрипте нет, так что это именно поле. а вот что делать с классами на си-шарпе - интересный вопрос

Sergey Batanov @dmpas 12:03
@nixel2007 с ними-то всё просто: есть пометка ContextProperty - однозначно определяет свойство

Alexey Sosnoviy @asosnoviy 12:03
What is the difference between a field and a property? viewed 319,968 times

Nikita Gryzlov @nixel2007 12:04
@dmpas судя по https://github.com/oscript-library/rabbitmq/blob/master/oscript-component/Connection.cs чего-то вроде ContextField не предусмотрено? оно всегда должно быть именно пропертей?

Sergey Batanov @dmpas 12:05
@nixel2007 да, только проперти, только хардкор.

Nikita Gryzlov @nixel2007 12:05
спросил сумбурно. этот класс писался на основе твоего шаблона. и там были везде проперти, ЕМНИП
а можно ли переступить через гордость и для c# всегда возвращать проперти, а для оскрипта - Перем, которые являются филдами?

Sergey Batanov @dmpas 12:09
куда возвращать?

Nikita Gryzlov @nixel2007 12:09
насколько я поинмаю, вопрос про метод ПолучитьТаблицуСвойств? или я что-то упустил?

Sergey Batanov @dmpas 12:10
вопрос вообще про аннотации свойств, но, да, про получитьтаблицусвойств в том числе.
но получитьтаблицусвойств, если я верно помню, как-раз-таки вернёт все Перем Поля

Alexey Sosnoviy @asosnoviy 12:10
Перем Экспорт

Nikita Gryzlov @nixel2007 12:11
тааак, и какие тогда вопросы к аннотациям?
я не троллю, пытаюсь понять

Sergey Batanov @dmpas 12:15
ща попробую ткнуть тебя в обсуждение
ыыы... походу надо в гиттере искать...

Sergey Batanov @dmpas 12:20
короче, давайте заводить челобитную на аннотации свойств и там ещё раз всю эту ерунду проговорим, про поля, свойства, поля-свойства, односкриптовые, шарповые.

**Comment by nixel2007** [comment]
Кросс-линк #807 (-_-)
