### ISSUE TITLE
РегисТронЕзавИСимые Имена аннотаций

### ISSUE THREAD

**Issue by asosnoviy** [EvilBeaver/OneScript#783]
Будет немного приятней их обрабатывать... Нрег() утомил.

**Comment by EvilBeaver** [comment]
а в 1с насервере и НаСервере - не отличаются?

**Comment by asosnoviy** [comment]
не отличается... Обе будут Доступны На Сервере.

**Comment by dmpas** [comment]
ну... имя аннотации - это просто строка. Тут либо вводить под аннотации отдельный тип - под имя, или под таблицу аннотаций, или ещё под что-нибудь, что так себе вариант. Или смириться с нрег.
Ты когда по метаданным конфигурации бежишь, ты Имя объекта метаданных тоже сравниваешь регистрозависимо.

**Comment by EvilBeaver** [comment]
После камента @dmpas мне добавить нечего

**Comment by asosnoviy** [comment]
А когда может пригодится регистрозависимое имя аннотации в рефлекторе?  
Я предлагаю в движке делать Нрег()/Врег() без плясок с новым типом.  
Гдето то тут: https://github.com/EvilBeaver/OneScript/blob/6bddd377a57ad414c0dcd7c56955cb779cba3537/src/ScriptEngine.HostedScript/Library/Reflector.cs#L134  
Как оно в других языках?
В целом уже завернули в либу и там нрег делается...

ЗЫ.. Прочитал еще раз и осознал написанное @dmpas

**Comment by EvilBeaver** [comment]
> В целом уже завернули в либу и там нрег делается...

Это о чем?

**Comment by asosnoviy** [comment]
https://github.com/khorevaa/reflector
