### ISSUE TITLE
64-х разрядная версия OneScript

### ISSUE THREAD

**Issue by Dumsik** [EvilBeaver/OneScript#784]
Очень нужна 64-х разрядная версия движка OneScript т.к. в случае использования на хосте платформы 1Сx64 из скриптов OneScript нет возможности использовать 1С Ком коннектор т.к. он x64.

**Comment by EvilBeaver** [comment]
@Dumsik мне просто интересно - сработал ли вчера-добавленный шаблон задачи "Запрос функциональности" с моим комментарием?

**Comment by nixel2007** [comment]
@EvilBeaver плашка есть. только заверни большой текст в символы многострочного комментария, чтобы не обязательно его было каждый раз удалять.

**Comment by EvilBeaver** [comment]
@nixel2007 это в которые такие символы? /**/ что-ли?

**Comment by nixel2007** [comment]
```
<!---
your comment goes here
and here
-->
```

**Comment by jdeshin** [comment]
Тоже нужна т.к. есть необходимость в использовании x64 com объектов

**Comment by a-grinyuk** [comment]
+1

**Comment by otymko** [comment]
@EvilBeaver было бы удобно, если при вызове 
```bash
oscript -v
```
Выводилась еще и версия разрядности.
Сейчас так:
![image](https://user-images.githubusercontent.com/11651847/67839840-26841f00-fb27-11e9-970b-7b5d476cda72.png)
Например так:
```
1.2.0.67 (x64)
```

**Comment by EvilBeaver** [comment]
@otymko ключ -v нужен для автосборки пакетов линукса и его выхлоп должен быть именно таким. Но можно какой-то доп.ключик, да

**Comment by dmpas** [comment]
автосборка пакетов линуха тоже, наверное, должна перейти на разные пакеты под разные разрядности.

**Comment by EvilBeaver** [comment]
@dmpas я думаю там не нужен x86, а пакеты сейчас собираются как noarch и all

Т.е. если туда класть Any CPU, то все будет по честному...

**Comment by dmpas** [comment]
Тогда тебе надо собирать три зипчика: х86, х64 и хЛюбой

**Comment by EvilBeaver** [comment]
Я собираю 2 exe (x86 и Любой), 2 linux (rpm и deb) типа "Любой" и 1 зипчик "ВсеСразу"

**Comment by dmpas** [comment]
Зипчик же сейчас "Любой", а не "ВсеСразу". Или уже поменялось?

**Comment by EvilBeaver** [comment]
@dmpas сейчас зипчик это x86 по сути копия того, что в инсталлере. Я перепиливаю скрипты инсталла и сейчас пока у меня в рабочем каталоге 2 подпапки bin - собственно bin и bin32. Из них собираются правильные инсталлеры, но сам зипчик я думаю - может полениться и оставить один с двумя подпапками bin?
