### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by Simon250388** [EvilBeaver/OneScript#785]
Планируется ли переход на .net core?

**Comment by EvilBeaver** [comment]
А есть ли смысл? запускать через dotnet run не очень удобно, а паковать standalone - слишком распухнет дистрибутив. 

Веб-движок поддерживает net core. Если будут аргументы ЗА под консольный 1Script - никаких проблем. Технически это возможно.

**Comment by Simon250388** [comment]
Мне кажется это поможет избавиться от mono в linux дистрибутивах

**Comment by EvilBeaver** [comment]
Но тогда придется вместо mono ставить netcore. Наверное имеет смысл сделать несколько поставок, чтобы была свобода выбора в линукс. Не знаю... @dmpas что скажешь?

**Comment by dmpas** [comment]
@EvilBeaver односкрипт под неткор сейчас вообще собирается разве? По-моему, там были какие-то особенности.

**Comment by EvilBeaver** [comment]
@dmpas ну плюс-минус собирается. Там препроцессором вырезаны некоторые куски неподдерживаемые в методе ПолучитьCOMОбъект. Остальное собирается.

**Comment by dmpas** [comment]
@EvilBeaver за COM-объекты нас порвут. Нет COM-объектов - нет нет-кора.

**Comment by EvilBeaver** [comment]
@dmpas ком есть. Нет только одной из веток в методе ПолучитьCOMОбъект

https://github.com/EvilBeaver/OneScript/blob/25a30d28505297002bf35f77adaae7cbd6c74ee6/src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs#L619-L640

Если мы говорим про линукс, то ком там и не нужен.

**Comment by dmpas** [comment]
@EvilBeaver неткор делать или сразу под все ОСи, или не делать вовсе. Таки у нас много кто тупо качает зип, а не устанавливает деб/рпм-пакет.

**Comment by EvilBeaver** [comment]
неткор должен быть палюбасу отдельным файлом. Наряду с x64-сборкой

**Comment by EvilBeaver** [comment]
Закрываю. Переход на core запланирован.

**Comment by aliczin** [comment]
![2020-10-28 04-44-19 publish bat - oscript-net50 - Visual Studio Code - Insiders](https://user-images.githubusercontent.com/56105699/97515795-ddb5af00-19a2-11eb-9117-f61359e4a55f.png)

@EvilBeaver я сделал пеересборку под NET 5.0 RC2 - получилось слишком много изменений. Могу показать что нашел - там с CaseSensetive и с кодировками ЧтенияТекста/XML беда - как и в целом с кодировками. Микрософт вынес работу с кодировками в отдельный NuGet пакет.

Но я добился чтобы тесты все прошли.

ServiceHost выпилили - пришлось менять на альтернативу - не уверен что нашел правильную.

Попробовал Mage чтобы можно сделать приложение в виде ClickOnce - чтобы было автоматическое обновление. Причем там хитро - оно умеет докачивать только нужные Assembly и одновременнно качать нужные NETCore Runtime.
"5-ка вообще штука интересная - она там очень маленькая стала"

Самое главное - работает SelfContained в режиме Publish под любой Runtime. В докере теперь не нужно наследоваться от Mono.

Будет времечко скажи как лучше поступить - я несколько передалал MSBUild отказавшись от дополнительных костылей. То есть мне пришлось переделать структуру проекта (солюшена).

Схема сборки получилась зато простая

(for eacn runtime)
* dotnet restore
* dotnet build
* dotnet test
* dotnet publsh 
* opm install 1testunner
* 1testunner runall 

ну и дальше уже публикация на хостах и в Nuget

причем работает на GitHub Action - я на паралельном проекте проверял 

в итоге получается несколько 6 папочек

* onescript-winx64-with-no-runtime
* onescript-linx64-with-no-runtime
* onescript-osx-with-no-runtime
* onescript-winx64-with-runtime
и т.д.

![изображение](https://user-images.githubusercontent.com/56105699/97518003-646c8b00-19a7-11eb-8e74-3e0996e2cdc3.png)

размеры вот такие - если разархивировать

если заархиварировать в среднем режиме

![изображение](https://user-images.githubusercontent.com/56105699/97518513-61be6580-19a8-11eb-9186-758ddc498423.png)

Такие дела.

**Comment by aliczin** [comment]
#1037
