### ISSUE TITLE
Несовместимость с 1С (Ошибки парсера)

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#788]
1.  Унарный плюс в 1С работает, а в onescript нет:
```bsl
x = +1;
```
Ошибка:
```
{Модуль <string> / Ошибка в строке: 1 / Ошибка в выражении}    
x = +1;
```
---
2. В 1С выражение `Не` может участвовать только в логических выражениях, а в onescript в любых:
```bsl
x = 1 + Not 2;
```
Это работает в onescript, хотя не должно.

---
3. В 1С оператор `Не` не может следовать подряд несколько раз, а в onescript может:
```bsl
x = Not Not 2;
```
Это работает в onescript, хотя не должно.

**Comment by nixel2007** [comment]
Это все же ошибка парсера :)

**Comment by EvilBeaver** [comment]
Спасибо

**Comment by Mr-Rm** [comment]
1. Унарный плюс обсуждался в issue #752, но к выводу о его нужности не пришли. Для совместимости можно добавить, исправления минимальны.
2. Это к большому вопросу о неявных преобразования типов в OneScript, хотя в целом поведение логично.
3.  Здесь, скорее, ошибочно ведет себя 1С, не позволяя более одного унарного оператора подряд.  `x = Not Not 2` - вполне допустимо, как и `x = - - 2` (но тут появляется возможность сомнительного  `x = --2`)

**Comment by EvilBeaver** [comment]
по п.2 боюсь исправление будет дороже, чем польза от изменения.

**Comment by tsukanov-as** [comment]
@Mr-Rm 
2. Не согласен. Ошибка уровня синтаксиса и возникает в момент разбора а не выполнения.
3. Ну тут вообще вопрос совместимости, а не правильности. В 1С Not вообще в корне неправильно сделан. Такого приоритета ни в одном языке не видел. Профита ноль, а при парсинге как кость в горле, т.к. его нельзя разбирать на уровне унарных операторов.

**Comment by tsukanov-as** [comment]
@EvilBeaver я бы забил на 2 и 3. И даже забил бы в квадрате. Сделал бы Not унарным как в большинстве языков. Мне кажется что 99% одноэсников даже и не подозревают, что он не унарный

**Comment by Mr-Rm** [comment]
@tsukanov-as: Почему же Not не унарный? Приоритет у него _нестандартный_, это да. И в арифметических выражениях он вполне может быть:
`x = 1 + (Not 0)` == 2 // ок
`x = Not 0 + 2` == // ложь, а не 3
Это и в 1С, и в OneScript.
(Может быть, парсер 1С вообще не умеет правоассоциативные операторы разбирать?)

**Comment by tsukanov-as** [comment]
@Mr-Rm 

> `x = Not 0 + 2` == // ложь, а не 3

Ну так это же неправильно. Человек с любого другого языка испытает когнитивный диссонанс.

Он не унарный в обычном понимании. Обычно унарный оператор применяется к одному элементу (ну или множеству бит, к примеру), а тут к выражению и даже в двух словах не опишешь к какому именно выражению.

Прям задачка на собеседование расставить скобки ))
> x = Not y < 2 + R And Not Z Or P;

>`x = 1 + (Not 0)`

Хитрый какой )) Проблема то как раз в синтаксисе без скобок. А это очевидно синтаксически другая формула

**Comment by Mr-Rm** [comment]
В 1Сv77 приоритет всех трех булевых операторов был выше и сравнений, и арифметических. Это требовало расстановки скобок: `Если ( А<Б+1 ) ИЛИ ( Г>0 ) И НЕ( 2*Д=3 ) Тогда ...`
В 1Сv8 приоритет _всех трех_ булевых операторов был сделан самым низким. Запись условий упростилась. Но при этом появились булевы значения и возможность их смешивать с числовыми.
Получили ` Не 1 + 1`  != `Не 1 Или 1` , поскольку ` Не (1 + 1)` != `(Не 1) Или 1`.
> x = (Not (y < (2 + (R And (Not Z))))) Or P; // ;)

Исправлять приоритет унарного ` Не` нельзя, т.к. сломаются условия вида `Если НЕ Д=1 Тогда ...`

**Comment by EvilBeaver** [comment]
У меня приоритеты выглядят вот так: https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine/Compiler/Tokens.cs#L33-L35

**Comment by tsukanov-as** [comment]
> Исправлять приоритет унарного Не нельзя, т.к. сломаются условия вида Если НЕ Д=1 Тогда ...

Но так никто не пишет! :D (кроме меня любимого на днях, хз что за зараза)

**Comment by dmpas** [comment]
Я так пишу. Очень удобно, чтобы не переключать раскладку во имя вшивого `<>`

**Comment by tsukanov-as** [comment]
@EvilBeaver  чет не совсем верно. https://i.imgur.com/nTt699B.png
У унарных приоритет должен быть выше умножения/деления....

**Comment by tsukanov-as** [comment]
> Я так пишу. Очень удобно, чтобы не переключать раскладку во имя вшивого <>

Пиши на ангельском, там нет такой проблемы )))

Ну в целом наверно да, ломать нельзя. Печалька

**Comment by Mr-Rm** [comment]
@EvilBeaver UnaryMinus надо для порядка исправить на 7, но он парсится в `BuildPrimaryNode()` без обращения к _priority.

@dmpas а не ввести ли `!=` ?

**Comment by tsukanov-as** [comment]
> а не ввести ли != ?

Охохо! Питоновые холиворы стартуе. Хде попкорн?!

**Comment by Mr-Rm** [comment]
Почему 'питоновые' ? C и далее везде: C++/C#/Java...
Просто добавить лексему `!=`, эквивалентную `<>`.  Несовместимость при необходимости исправляется просто глобальным поиском/заменой.

**Comment by tsukanov-as** [comment]
Потому что в Питон раньше было <> ЕМНИП (и даже оба одновременно)

ps Кстати спрошу у народа раз уж речь зашла: Что удобнее набирать (на английской раскладке ессесно) <> или != ???
Мне удобнее <> но я не владею православным слепым набором

**Comment by EvilBeaver** [comment]
> чет не совсем верно

Ничего не знаю, у меня все проверено электроникой (тм) 😆

**Comment by tsukanov-as** [comment]
@EvilBeaver ну вообще хз где оно бахнет.
На ум приходит только возведение в степень, типа `x = -y^2`
В 1С есть возведение в степень? O_o (add: оператора нету)
Еще в % по идее может быть разница

**Comment by nixel2007** [comment]
> В 1С есть возведение в степень? O_o

pow

**Comment by EvilBeaver** [comment]
> ну вообще хз где оно бахнет

@tsukanov-as я проверял эмпирически, приоритеты в 1Скрипте совпадают с 1С. Пока мне неизвестно выражение, которое бы в 1С и в 1Скрипте отрабатывало бы в разном порядке.

**Comment by tsukanov-as** [comment]
@EvilBeaver да, сейчас потыкал. Остаток от деления реализован так что разницы нет какой приоритет. Возведения в степень просто нет. Похоже что этот приоритет ни на что не влияет.

> отрабатывало бы в разном порядке

Не ну отрабатывать оно в скрипте должно точно не в том порядке. Просто чисто математически (по стечению обстоятельств) результат одинаковый
