### ISSUE TITLE
Не могу обновить библиотеки через opm - ошибка "Не удалось создать защищенный канал SSL/TLS"

### ISSUE THREAD

**Issue by unichkin** [EvilBeaver/OneScript#790]
Запустил opm install -all (потом install gitsync), после установки v8unpack вижу такую боль. С чем может быть связано? 
Текст из PowerShell:
PS C:\Windows\system32>  oscript.exe "C:\Program Files (x86)\OneScript\lib\opm\src\opm.os" install gitsync
ИНФОРМАЦИЯ - Скачиваю файл: gitsync.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет gitsync
ИНФОРМАЦИЯ - Регистрация приложения: gitsync
ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
ИНФОРМАЦИЯ - logos уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: cmdline
ИНФОРМАЦИЯ - cmdline уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: tempfiles
ИНФОРМАЦИЯ - tempfiles уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: tool1cd
ИНФОРМАЦИЯ - tool1cd уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: v8runner
ИНФОРМАЦИЯ - v8runner уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: gitrunner
ИНФОРМАЦИЯ - gitrunner уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: strings
ИНФОРМАЦИЯ - strings уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: 1commands
ИНФОРМАЦИЯ - 1commands уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: v8unpack
ИНФОРМАЦИЯ - Скачиваю файл: v8unpack-1.0.1.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет v8unpack
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\v8unpack\packagedef / Ошибка в строке: 26 / Внешнее исключение (System.Net.WebException): Запрос был прерван: Не удалось создать защищенный канал SSL/TLS.}

**Comment by unichkin** [comment]
Нашел среди описания метода HttpСоединение:
ssl: Объект ЗащищенноеСоединение. На данный момент данная механика работы с SSL не поддерживается. Обращение к https возможно, если в адресе хоста указать протокол https. В этом случае будут использованы сертификаты из хранилища ОС. Указание произвольных клиентских и серверных сертификатов в текущей версии не поддерживается.

Я так понимаю, у меня что-то с сертификатами не так, что можно предпринять, подскажите пожалуйста?

**Comment by nixel2007** [comment]
Время на машине точное?

**Comment by unichkin** [comment]
Да, синхронится. win 10

**Comment by unichkin** [comment]
![image](https://user-images.githubusercontent.com/10799597/43171131-6fcf98b6-8fb1-11e8-9938-7141bba5323e.png)
Через 1С ответ получается..

**Comment by unichkin** [comment]
Случайно закрыл, нажал  клоз анд коммент..

**Comment by EvilBeaver** [comment]
В оскрипте защищенное соединение создается добавлением https:// в адрес объекта HttpСоединение

**Comment by unichkin** [comment]
Оно и создается защищенное, обращается к https://oscript.io/. И у меня валится на означенной ошибке

**Comment by EvilBeaver** [comment]
Тогда не знаю. Мало информации...

**Comment by EvilBeaver** [comment]
@unichkin проверьте, пожалуйста на ночной сборке. Воспроизводится?

**Comment by EvilBeaver** [comment]
@unichkin подниму вопрос

**Comment by unichkin** [comment]
Доброго времени. В среду вечером смогу посмотреть, отпишусь.

**Comment by unichkin** [comment]
Все работает, большое спасибо!
