### ISSUE TITLE
Встроенный JSON не экранирует двойные кавычки

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#792]
В JSON двойные кавычки внутри строки должны всегда экранироваться.
Сейчас встроенный JSON-маршаллер этого не делает.

Пример для воспроизведения:
```bsl
JSONWriter = New JSONWriter;
JSONWriter.SetString(New JSONWriterSettings(, Chars.Tab));
JSONWriter.WriteValue("Строка с ""кавычками"" внутри");
Message(JSONWriter.Close());
```

На выходе будет: `"Строка с "кавычками" внутри"`
а должно быть: `"Строка с \"кавычками\" внутри"`

**Comment by alexkmbk** [comment]
Исправлено в PR -  #791
