### ISSUE TITLE
Ссылка на обработку ГенераторКлассов-СП-CSharp.epf 

### ISSUE THREAD

**Issue by alexkmbk** [EvilBeaver/OneScript#793]
На сайте oscript.io в разделе [http://oscript.io/dev/page/components]( http://oscript.io/dev/page/components) предлагаю добавить ссылку на обработку ГенераторКлассов-СП-CSharp.epf которая позволяет генерировать классы C# на основе справочной системы 1С. А также ссылку на архив базы конфигурации Типы1С которая необходима для запуска вышеуказанной обработки.

Прилагаю тот файл обработки, которым лично пользуюсь, я вносил в него исправление. Возможно присутствует более актуальная версия.

[ГенераторКлассов-СП-CSharp.zip](https://github.com/EvilBeaver/OneScript/files/2268738/-.-CSharp.zip)

Прилагаю также архив базы конфигурации Типы1С (возможно есть более актуальная версия)

[Типы1С.zip](https://github.com/EvilBeaver/OneScript/files/2268756/1.zip)

Автор обработки кажется [Ушаков Сергей](https://github.com/ret-Phoenix).

**Comment by ret-Phoenix** [comment]
Более актуальной версии, от меня, нет.

**Comment by EvilBeaver** [comment]
Да, только ее допиливать надо серьезно

**Comment by alexkmbk** [comment]
@EvilBeaver Но главное работает и облегчает работу.
