### ISSUE TITLE
Литерал даты из нулей не распознается (совместимость с 1С)

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#795]
Следующий код работает в 1С, но не работает в onescript:
```bsl
x = '00000000';
```

Текст ошибки:
```
{Модуль  / Ошибка в строке: 0 / Преобразование к типу 'Дата' не поддерживается}  
```

ps Я сам в шоке

**Comment by tsukanov-as** [comment]
ok, еще интереснее:
```bsl
x = '000101010000';
```
Вот это уже нормальная дата, но в onescript ошибка:
```
{Модуль  / Ошибка в строке: 0 / Преобразование к типу 'Дата' не поддерживается}
```

**Comment by Mr-Rm** [comment]
Из последнего develop:
```
x = '000101010000';
сообщить(x);
```
Вывод; `01.01.0001 0:00:00` - всё работает.

Что до `x = '00000000'` - на этом падает стандартный DateTime.ParseExact(). Такие случаи (8, 12, или 14 нолей) надо распознавать отдельно, м.б. парсером, а не в рантайме.

**Comment by tsukanov-as** [comment]
@Mr-Rm не понял. Это известный баг и уже починили, или у меня версия какая-то левая? )

**Comment by Mr-Rm** [comment]
Баг со всеми  нолями есть, а с '000101010000' - нет бага.

**Comment by tsukanov-as** [comment]
Хм, да. Проверил в ночной сборке, бага нет.
