### ISSUE TITLE
System.Single Невозможно преобразовать в один из поддерживаемых типов

### ISSUE THREAD

**Issue by Sirtoo** [EvilBeaver/OneScript#798]
**Опишите ошибку**
При получении результата запроса к WMI получаю ошибку.
Тип System.Single
"невозможно преобразовать в один из поддерживаемых типов"

 WinOHM= ПолучитьCOMОбъект("winmgmts:\\" + ПеременныеСреды().Получить("COMPUTERNAME") + "\root\openhardwaremonitor");
PrimaryOHM = WinOHM.ExecQuery("Select * from Hardware);
Для Каждого item ИЗ PrimaryOHM Цикл
           Сообщить(item.Value);
КонецЦикла;

openhardwaremonitor  -  
https://github.com/openhardwaremonitor/openhardwaremonitor

 - ОС:  Win 8
 - Версия: 1.0.21

**Дополнительная информация**

**Comment by EvilBeaver** [comment]
Полагаю, вот здесь надо добавить поддержку single

https://github.com/EvilBeaver/OneScript/blob/a1c246381ac3b7851849e231700c05beb704be9f/src/ScriptEngine/Machine/Contexts/COMWrapperContext.cs#L197

**Comment by EvilBeaver** [comment]
Буду признателен за пулреквест.

**Comment by Sirtoo** [comment]
пул реквест  наверное не осилю , в гитхабе не плаваю...

**Comment by Sirtoo** [comment]
кто нибудь может помочь, скомпилить проект с исправлением ? пробовал , не получилось.
разработка проекта встала из - за этой мелочи ((

**Comment by nixel2007** [comment]
@Sirtoo подождите минут 15 и после сборки вот этого - http://build.oscript.io/job/1Script/job/PR-801/ там будет возможность скачать zip

**Comment by nixel2007** [comment]
Поторопился я, не скомпилируется. Попробую разобраться.

**Comment by Sirtoo** [comment]
большое спасибо. жду с надеждой ... )

**Comment by nixel2007** [comment]
Сделал так, что оно собирается, но, к сожалению, из-за небольшой проблемы на сервере сборок получить готовый zip пока нельзя :( надеюсь, что в ближайшее время будет решено.
Сам пулл-реквест - https://github.com/EvilBeaver/OneScript/pull/801
