### ISSUE TITLE
Не корректно работает метод ПодключитьВнешнююКомпоненту

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#804]
**Опишите ошибку**
При вызове метода `ПодключитьВнешнююКомпоненту` вне контекста файла загрузки библиотеки `package-loader.os`, для компонент содержащей внутри модули, данные модули не подключаются в глобальный контекст, при этом с классами все хорошо

**Воспроизведение ошибки**

Использовать `dll` из библиотеки `InternetMail`

1. Подключить компоненту в файле написав `ПодключитьВнешнююКомпоненту("./bin/MailComponent.dll");`
2. Дополнить файл кодом
```
ПодключитьВнешнююКомпоненту("./bin/MailComponent.dll");

Профиль = Новый ИнтернетПочтовыйПрофиль;

Профиль.АдресСервераSMTP = "mail.server.com";
Профиль.ПользовательSMTP = "1c@server.com";
Профиль.ПарольSMTP = "password";
Профиль.ИспользоватьSSLSMTP = Ложь;

Профиль.АдресСервераPOP3 = "mail.server.com";
Профиль.ИспользоватьSSLPOP3 = Ложь;
Профиль.Пользователь = "1c@server.com";
Профиль.Пароль = "password";

Сообщение = Новый ИнтернетПочтовоеСообщение;
Сообщение.Получатели.Добавить("adressee@server.com");
Сообщение.Отправитель = "1c@server.com";
Сообщение.Тема = "Тема" ;
Текст = "<html>просто тект</html>";

Сообщение.Тексты.Добавить(Текст, ТипТекстаПочтовогоСообщения.HTML);
```
3. Выполнить данный файл через oscript
4. Увидеть ошибку 
Не доступны объекты перечисления 
`Ошибка в строке: 35 / Неизвестный символ: ТипТекстаПочтовогоСообщения}`

**Ожидаемое поведение**

Загрузка компоненты со всеми необходимыми модулями и классами

**Окружение**
 - ОС: Linux/windows
 - Версия: 1.0.20

**Дополнительная информация**

Если это фича движка ее надо документировать в справке! Хотя мне не понятно почему классы подключаются, а модули нет.

/cc @allustin @nixel2007 @EvilBeaver  @dmpas

**Comment by EvilBeaver** [comment]
это дубликат одного из старых багов

**Comment by khorevaa** [comment]
@EvilBeaver 1.0.21 вышла а баг не поправили! Очень мешает жить хорошо!

**Comment by EvilBeaver** [comment]
Баг старый. Его не поправили много релизов назад.

**Comment by khorevaa** [comment]
Хорошо бы поправить....
