### ISSUE TITLE
Рефлектор: получать информацию о приватных методах

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#805]
Полезно для получения аннотаций на классы, закрытые конструкторы и т.п.

**Comment by ret-Phoenix** [comment]
Сделаю в ближайшие дни. Главное до компа добраться.

**Comment by ret-Phoenix** [comment]
Как лучше сделать?
варианты:
1. Колонка с именем Приватный - Да/Нет
2. Колонка "УровеньДоступа" - Приватный/Публичный

**Comment by khorevaa** [comment]
Колонка с булево

**Comment by nixel2007** [comment]
Мне хватит 1.

**Comment by EvilBeaver** [comment]
@ret-Phoenix сделаешь? Я приторможу выпуск релиза до твоего решения
