### ISSUE TITLE
Рефлектор не получает информацию о типах-сценариях

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#806]
**Опишите ошибку**

Через рефлектор нельзя вытащить информацию о методах и свойствах класса-сценария, передав туда его тип, вместо экземпляра.

**Воспроизведение ошибки**

```bsl
#Использовать v8runner

Рефлектор = Новый Рефлектор;
Рефлектор.ПолучитьТаблицуМетодов(Новый УправлениеКонфигуратором());

Рефлектор.ПолучитьТаблицуМетодов(Тип("УправлениеКонфигуратором"));
```

```sh
oscript path-to-script.os
```

На выходе:
```
{Модуль C:\Users\user\Desktop\Untitled-1.os / Ошибка в строке: 6 / Неверное значение аргумента {Тип не может быть отражен.}}
```

**Ожидаемое поведение**

Не выдается сообщений об ошибках

**Окружение**
 - ОС: win10 pro
 - Версия: 1.0.20.1 nightly от 13.09.2018

**Дополнительная информация**

**Comment by EvilBeaver** [comment]
Есть небольшая подстава. Типы-сценарии отдают свои Методы/Свойства через интерфейс IRuntimeContextInstance. Т.е. только через инстанс. У самого Тип("УправлениеКонфигуратором") нечего рефлектить.

@dmpas есть идеи?

**Comment by nixel2007** [comment]
Можно ли через сишарповскую рефлексию или через какой-то хитрый метод движка скомпилировать скрипт в объект без  непосредственного запуска конструктора и тела модуля?

**Comment by EvilBeaver** [comment]
@nixel2007 можно превратить скрипт или тип библиотеки (а-ля Структура) в тип среды .NET и рефлектить стандартной рефлексией методы Вставить() и Количество()
