### ISSUE TITLE
Рефлектор: Не возвращается информация о аннотациях поля класса

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#807]
**Опишите ошибку**

При получении коллекции аннотаций от поля класса возвращается Неопределено вместо таблицы аннотаций.

**Воспроизведение ошибки**

```bsl
#Использовать asserts

&МояАннотация
Перем МоеСвойство Экспорт;

Рефлектор = Новый Рефлектор;
ТаблицаСвойств = Рефлектор.ПолучитьТаблицуСвойств(ЭтотОбъект);

Ожидаем.Что(ТаблицаСвойств, "В свойствах есть экспортное свойство").ИмеетДлину(1);

Ожидаем.Что(ТаблицаСвойств[0].Аннотации, "У свойства заполнены аннотации").Не_().Равно(Неопределено);
```

```sh
oscript C:\Users\user\Desktop\Untitled-1.os
```

На выходе:

```
{Модуль C:\Users\user\AppData\Local\ovm\current\lib\asserts\src\bdd-asserts.os / Ошибка в строке: 303 / [Failed] Ожидали, что проверяемое значение () НЕ РАВНО ().
У свойства заполнены аннотации}
```

**Ожидаемое поведение**

Тест проходит, таблица аннотаций заполнена.

**Окружение**
 - ОС: win10 pro
 - Версия: 1.0.20.1 nightly от 13.09.2018

**Дополнительная информация**

**Comment by nixel2007** [comment]
Кросс-линк #780 (-_-)

**Comment by EvilBeaver** [comment]
@dmpas а мы разве начали поддерживать аннотации свойств?

**Comment by nixel2007** [comment]
@EvilBeaver вести с полей говорят, что @dmpas даже сделал какую-то черновую реализацию, потом был холивар на тему поля-свойства и он ее выпилил от греха.

p.s. пожалста, пожалста, пожааааалста.

**Comment by EvilBeaver** [comment]
А я ж не против. Просто не помню суть холивара и что случилось

**Comment by nixel2007** [comment]
Из серии #805, #806, #807 - этот сейчас самый тормозящий меня... Поэтому если кто вдруг возьмется (@ret-Phoenix, @EvilBeaver, @dmpas), начните с него, пожалуйста.

**Comment by EvilBeaver** [comment]
А чего ты такое чередишь-то опять?

**Comment by nixel2007** [comment]
@EvilBeaver странный глагол)

А вообще - https://github.com/nixel2007/entity

**Comment by EvilBeaver** [comment]
Я смотрел в эту сторону, но пришел к выводу, что набирать много таких сущностей - напряжно. Одно переключение раскладки чего стоит. Это раз. И второе - умирает читабельность сущности. Аннотации все забивают. 

Я просто тупо брал справочник из типовой и в блокноте его размечал аннотациями. Получалось вырвиглазно. Т.е. идея офигенная, нам нужен ОРМ, но аннотации, имхо, неудобны для русской раскладки и синтаксиса 1С. Хотя, я могу и ошибаться.

Второй вариант, который я пробовал - это флюенты, подсмотренные в EntityFramework.

```
Контрагент = МодельБД.Справочник("Контрагенты")
                           .ИмяСущности("Контрагент")
                           .Реквизит("ОсновнойСчет")
                                 .Ссылка("Справочник.РасчетныеСчета")
                           .Реквизит("ИНН")
                                 .Строка("10")
                                 .Индексирован() 
```

Но тоже в итоге, при переносе реального справочника получается каша.
Есть еще вариант своего DSL, который я показывал то ли @arkuznetsov то ли @ret-Phoenix не помню..

````
Справочник Контрагенты, Контрагент
    - ИНН: Строка(10), Индексирован
    - КПП: Строка(8)
    - ОсновнойСчет: Ссылка.РасчетныеСчета
````

но под него нет парсера и формализации желаемой грамматики

P.S. ты не знаешь глагол "чередИть"? Значит - вытворять, делать что-либо. "Ну ты и начередИл тут!"

**Comment by EvilBeaver** [comment]
И вдогонку: можно сделать парсер DSL, который будет генерить файлы-сущности с аннотациями, как у тебя.

**Comment by nixel2007** [comment]
~я старый джавер, я не знаю слов любви~ аннотации можно ставить с клавиатуры чистова :)

Если честно, я не рассчитываю, что кто-то будет делать на этой библиотеке очень сложную систему. И никогда не думал о ней, как о перекладывании справочников конфигуратора с десятом реквизитов на рельсы оскрипта. Основное направление, которое я вижу - небольшие веб-приложения. Одминус, опм хаб, такое вот все. Чтобы можно было просто отказаться от записи в джсон с одной стороны, и не мучаться с настройками бд с другой. Если при этом получится сделать мощный движок по работе с бд на базе ORM - круто же!

P. S. Меня пока прёт на код, и имхо лучше сделать и потом страдать от результата, чем оставить все как есть без ORM. Если кто-то возьмётся за другую реализацию - я буду только рад

**Comment by dmpas** [comment]
> Если честно, я не рассчитываю, что кто-то будет делать на этой библиотеке очень сложную систему

@nixel2007  1С так же думали. Потом опомнились и сделали восьмёрку.

**Comment by nixel2007** [comment]
@dmpas второму пользователю моей либы поставлю пиво) остальным просто спасибо :D
