### ISSUE TITLE
Рефлектор: ошибки работы после доработок рефлексии сценариев

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#809]
**Опишите ошибку**

После правок от 17.09.2018 сломалось получение методов (возможно и свойств) объектов "из типа".

**Воспроизведение ошибки**

* Установить последний ночник
* git clone https://github.com/nixel2007/entity
* Заменить строку 78 файла src/Классы/МенеджерСущностей.os на `РефлекторОбъекта = Новый РефлекторОбъекта(ТипКоннектора);` (ЭкземплярКоннектора заменить на ТипКоннектора)
* Запустить тесты (1testrunner -runall tests)
* Увидеть в консоли ошибку:
```
Сообщение: {Модуль C:\Users\user\AppData\Local\ovm\current\lib\reflector\src\Классы\РефлекторОбъекта.os / Ошибка в строке: 308 / Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}
```

**Ожидаемое поведение**

Работает без ошибок :)

**Окружение**
 - ОС: win10 pro
 - Версия: 1.0.21.6

**Дополнительная информация**

**Comment by nixel2007** [comment]
Дополнительно резко упали тесты в moskito.

* git clone https://github.com/nixel2007/moskito
* установить стабильный движок
* установить модифицированный тест-раннер (переименовать зип в ospx)
[1testrunner.zip](https://github.com/EvilBeaver/OneScript/files/2392016/1testrunner.zip)
* 1testrunner -runall tests
* проходят 19 из 20 тестов (это нормально)

---

* установить последний ночник
* установить модифицированный тест-раннер
* 1testrunner -runall tests
* проходят 3 из 20 тестов (должны проходить все)

**Comment by EvilBeaver** [comment]
![image](https://user-images.githubusercontent.com/2657561/45811306-66969280-bcd5-11e8-9c74-ed7c1c150b3e.png)

**Comment by EvilBeaver** [comment]
@nixel2007 можно какой-нибудь более дешевый (или рабочий) способ воспроизведения? Хотя бы для москита, а entity я уж и так добью
