### ISSUE TITLE
альтернатива DotNetZip под NetStandart

### ISSUE THREAD

**Issue by ghost** [EvilBeaver/OneScript#810]
сейчас по зависимостям от ScriptEngine.HostedScript приезжает DotNetZip

https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/ScriptEngine.HostedScript.csproj#L9

автор указанной библиотеки поддерживать netStandart даже не собирается

предлагается внедрить альтернативу https://www.nuget.org/packages/SharpZipLib.NETStandard/ иначее в приложения на netStandart указанную ScriptEngine.HostedScript объект внедрить не удастся ;-)

**Comment by nixel2007** [comment]
А точно её? У неё статус пререлиза и последний релиз - в 2017 году. Есть риск забрасывания автором

**Comment by EvilBeaver** [comment]
В нет.коре есть встроенный класс, а в нугете есть более свежие библиотеки и даже есть ишуз на переезд в эти библиотеки.

Вот он. https://github.com/EvilBeaver/OneScript/issues/152

**Comment by ghost** [comment]
@EvilBeaver как лучше сделать ? этот ишуз закрыть и перевести обсуждение туда ?

**Comment by EvilBeaver** [comment]
Нет, думаю тот менее "говорящий"
