### ISSUE TITLE
opm install/update на Ubuntu 16.04

### ISSUE THREAD

**Issue by fenixnow** [EvilBeaver/OneScript#811]
Установил OneScript на Убунту 
>apoletaev@P-N-TEMP:~$ oscript
>1Script Execution Engine. Version 1.0.20.108

При попытке установить пакек выдает следующую ошибку
>apoletaev@P-N-TEMP:~$ sudo opm install gitsync
>ПРЕДУПРЕЖДЕНИЕ - Ошибка получения списка пакетов с хаба ОсновнойСерверПакетов по причине {Модуль /usr/share/oscript/lib/opm/src/core/Классы/СерверПакетов.os / Ошибка в строке: 94 / Ошибка подключения к зеркалу }
>ПРЕДУПРЕЖДЕНИЕ - Ошибка получения списка пакетов с хаба ЗапаснойСерверПакетов по причине {Модуль /usr/share/oscript/lib/opm/src/core/Классы/СерверПакетов.os / Ошибка в строке: 94 / Ошибка подключения к зеркалу }

Если скачать через wget а потом проинсталировать, то, все норм, а так не находит... также wget не может получить пакет tool1cd

**Comment by EvilBeaver** [comment]
Полагаю что-то с корпоративной проксей связано

**Comment by fenixnow** [comment]
> apoletaev@P-N-TEMP:/tmp$ curl -Is http://hub.oscript.io/ | head -n 1
> HTTP/1.1 200 OK

**Comment by nixel2007** [comment]
Попробуйте установить 1.0.21

**Comment by fenixnow** [comment]
Ошибка остаётся и на этой версии

**Comment by EvilBeaver** [comment]
curl умеет работать с прокси, насколько я знаю. А вот opm нужно явно указать использование прокси через opm config.

**Comment by EvilBeaver** [comment]
@fenixnow еще актуально?

**Comment by fenixnow** [comment]
> @fenixnow еще актуально?

Нет, спасибо.
