### ISSUE TITLE
Ошибка при массовом обновлении пакетов (--all)

### ISSUE THREAD

**Issue by pruidzeko** [EvilBeaver/OneScript#813]
(Под правами администратора)
Команда opm update --all приводит к нарушению работы opm
Вот последовательность команд:
`
C:\Users\ko.pruidze
λ opm update opm
ПРЕДУПРЕЖДЕНИЕ - Ошибка получения списка пакетов с хаба ЗапаснойСерверПакетов по причине {Модуль C:\Program Files (x86)\OneScript\lib\opm\src\core\Классы\СерверПакетов.os / Ошибка в строке: 94 / Ошибка подключения к зеркалу }
ИНФОРМАЦИЯ - Скачиваю файл: opm.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет opm
ИНФОРМАЦИЯ - Регистрация приложения: opm
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: <fs> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <fs> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <asserts> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <asserts> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <json> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <json> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <fluent> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <fluent> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <logos> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <logos> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <cli> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <cli> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <tempfiles> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <tempfiles> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: <gitrunner> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <gitrunner> уже установлен. Пропускаем.

C:\Users\ko.pruidze
λ opm list
Пакеты в системном каталоге библиотек <C:\Program Files (x86)\OneScript\lib>:
1bdd@1.8.0
1commands@1.3.2
1testrunner@1.6.0
asserts@0.4.0
cli@0.9.10
cmdline@1.0.0
datetime@0.1.0
delegate@0.2.0
fluent@0.3.1
fs@0.5.0
gitrunner@1.6.0
gitsync@2.4.3
json@1.0.1
logos@1.0.2
notify@0.2.0
opm@0.15.1
reflector@0.5.1
semver@0.5.1
strings@0.4.1
tempfiles@0.2.2
tool1cd@0.6
v8runner@1.1.3
v8unpack@1.0.1

C:\Users\ko.pruidze
λ opm update --all
ПРЕДУПРЕЖДЕНИЕ - Ошибка получения списка пакетов с хаба ЗапаснойСерверПакетов по причине {Модуль C:\Program Files (x86)\OneScript\lib\opm\src\core\Классы\СерверПакетов.os / Ошибка в строке: 94 / Ошибка подключения к зеркалу }
ИНФОРМАЦИЯ - Скачиваю файл: 1bdd.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет 1bdd
ИНФОРМАЦИЯ - Регистрация приложения: 1bdd
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
ИНФОРМАЦИЯ - logos уже установлен. Пропускаем.
...
ИНФОРМАЦИЯ - Скачиваю файл: logos.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет logos
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: asserts
ИНФОРМАЦИЯ - asserts уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Скачиваю файл: notify.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет notify
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Скачиваю файл: opm.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет opm
{Модуль C:\Program Files (x86)\OneScript\lib\opm\src\core\Классы\МенеджерУстановкиПакетов.os / Ошибка в строке: 115 / {Модуль C:\Program Files (x86)\OneScript\lib\opm\src\core\Классы\УстановкаПакета.os / Ошибка в строке: 345 / Внешнее исключение (Ionic.Zip.ZipException): The file C:\Program Files (x86)\OneScript\lib\opm\oscript_modules\1commands\packagedef already exists.}}

C:\Users\ko.pruidze
λ opm list
Script file is not found 'C:\Program Files (x86)\OneScript\lib\opm\src\cmd\opm.os'

C:\Users\ko.pruidze
λ
`

**Comment by nixel2007** [comment]
@EvilBeaver ЧтениеZipФайла при вызове метода Извлечь разве не должно перезатирать файлы без запроса?

https://github.com/oscript-library/opm/blob/master/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0%D0%9F%D0%B0%D0%BA%D0%B5%D1%82%D0%B0.os#L345

**Comment by EvilBeaver** [comment]
@nixel2007 должно. Но могут встречаться read-only файлы, или захваченные другими приложениями, например

**Comment by nixel2007** [comment]
@artbear? Вроде это твои последние доработки по пэкэдждефу

**Comment by nixel2007** [comment]
например, тем же опм'ом...

ср, 26 сент. 2018 г. в 16:33, Andrei Ovsiankin <notifications@github.com>:

**Comment by khorevaa** [comment]
@nixel2007 @EvilBeaver Баг подтверждаю opm версии 0.14.4
 не  производит обномеления до 0.15.0

**Comment by EvilBeaver** [comment]
В чем заключается баг? Может отозвать 0.15.0 до получения в нем обходного маневра?

**Comment by artbear** [comment]
я сейчас проверю и поправлю, если баг подтвердится

**Comment by artbear** [comment]
Нашлась веселуха в движке и в 1С с поиском элементов внутри архива.
создал ишуз в движок https://github.com/EvilBeaver/OneScript/issues/816

**Comment by artbear** [comment]
Проблем было несколько.

Но главная-то проблема, оказывается, в том, что мы чистим каталог установки от всех устаревших файлов - `*.os, *.dll, packagedef`

Далее идет распакова файла packagedef
а в нем идет обращение к файлу констант 
```bsl
ПутьКСценариюКонстант = ОбъединитьПути(ТекущийСценарий().Каталог, "src/core", "Модули", "КонстантыOpm.os");
Константы_ЛокальнаяВерсия = ЗагрузитьСценарий(ПутьКСценариюКонстант);
```

а мы же вначале удалили все os-файлы, вот наш файл констант и не находится :(

**Comment by artbear** [comment]
Решено в https://github.com/oscript-library/opm/pull/141

**Comment by artbear** [comment]
@pruidzeko @nixel2007 Выпущен релиз 0.15.2 с исправленим.

Пожалуйста, проверьте установку нового релиза

**Comment by nixel2007** [comment]
насколько я понимаю, это изменение в opm ломает **все** пакеты, которые получают свой номер версии из общего модуля? Т.е. дефакто это все приложения, сделанные на cli, и почти все остальные приложения последних полутора лет?

@artbear может откатить твое изменение в opm и подумать еще раз?

**Comment by nixel2007** [comment]
Или уж если это событие настолько нужно, что прям вот невмоготу (на одном конкретном пакете, ага-ага), то хоть порядок событий в opm поменять?

**Comment by pumbaEO** [comment]
https://youtu.be/7dGUll4g2q0
https://youtu.be/Tdobu8lbOg8

Не знаю, каким образом проверяли, но не фига не работает сейчас.

**Comment by nixel2007** [comment]
@pumbaEO это другое. в движке поменяли библиотеку работы с зипом. из-за этого неверно зипуются ospx

**Comment by pumbaEO** [comment]
Ну я бы понял для ночной сборки, а вот стабильная тоже по факту сломана, после обновления opm

**Comment by artbear** [comment]
Баг в том, что я сделал предположение о наличии проблем в файла packagedef при неполном извлечение из архива пакета, если есть исключение по доступу к файлу.
А это предположение оказалось неполным.

Варианты решения:
 - либо добавить перехват исключение System.IO.DirectoryNotFoundException при запуска файла packagedef
- либо добавить перехват любого исключения при запуске этого файла
 
Логика такая - если при запуске есть исключения, значит, для инсталляции пакета нужен полный набор исходников, одного packagedef недостаточно.

В этом случае событие ПередУстановкой не отработает, а будет только событие ПриУстановке

И проблема будет решена.

**Comment by artbear** [comment]
Если нет других предложений, внесу вечером исправление.

**Comment by khorevaa** [comment]
Есть другое предложение... Сделать `packagedef` - в формете json или yaml
Я об этоv уже неоднократно писал/просил https://github.com/oscript-library/opm/issues/39
Данное действо  резко упростит работу с данным файлом. И его можно всегда по умолчанию включать в сборки пакета/приложения

/cc @nixel2007 @EvilBeaver

**Comment by artbear** [comment]
@khorevaa  
1 json или yaml - как решить необходимость обработки события сборки/установки?
где будут находиться обработчики событий?

2 это эпик-задача и решаться будет не быстро, а сейчас решаем не такую большую и довольно срочную задачу

**Comment by khorevaa** [comment]
@artbear Обработчики можно распологать в отдельных файлах  Или прямо в файле. packagedef и загружать эти сценарии через "ЗагрузитьСценарийИзСтроки"

**Comment by nixel2007** [comment]
Таски. 

⁣Отправлено с помощью BlueMail ​

На 10 окт. 2018 г., 13:53, в 13:53, Artur Ayukhanov <notifications@github.com> написал:п>@khorevaa

**Comment by pumbaEO** [comment]
Шел 10 день.

**Comment by artbear** [comment]
Опенсорс, чо :(

**Comment by artbear** [comment]
постараюсь добить, в метро интернета нет, не могу пакеты локально обновить :(

**Comment by artbear** [comment]
Выпустил версию 0.15.3
https://github.com/oscript-library/opm/releases/tag/v0.15.3

Проверяйте

@pumbaEO ванесса-раннер ставится нормально

**Comment by artbear** [comment]
Закрываю.
Если что не так с обновлением, переоткрывайте и пишите о проблеме
