### ISSUE TITLE
Падение РегулярноеВыражение.НайтиСовпадения

### ISSUE THREAD

**Issue by SuffArt** [EvilBeaver/OneScript#814]
**Ошибка в версиях 1.0.20, 1.0.21**
При передачи в параметре inputString результата ЧтенияТекста.Прочитать() пустого файла,
OneScript падает с ошибкой:
```
Внешнее исключение (System.ArgumentNullException): Значение не может быть неопределенным.
Имя параметра: input
```

**Воспроизведение ошибки**
Код для воспроизведения:
```
Регулярка = Новый РегулярноеВыражение(".");

ПутьКФайлу = ОбъединитьПути(ТекущийКаталог(), "Empty.txt");

ЧтениеФайла = Новый ЧтениеТекста();
ЧтениеФайла.Открыть(ПутьКФайлу); 
ТекстМодуля = ЧтениеФайла.Прочитать();	
ЧтениеФайла.Закрыть();

КоллекцияСовпадений = Регулярка.НайтиСовпадения(ТекстМодуля);
```

**Ожидаемое поведение**
КоллекцияСовпаденийРегулярногоВыражения должна быть пустой

**Окружение**
 - ОС: Win7
 - Версия: 1.0.21.298

**Дополнительная информация**
В 1.0.19 данной ошибки нет.

**Comment by artbear** [comment]
@EvilBeaver @dmpas Получается, что передается значение Неопределено и не выполняется приведение к строке.

Для автора - приводи явно к строке значение из ЧтениеТекста.Прочитать

Как лучше поправить в коде движка - сделать приведение типов ?
или что-то другое?

**Comment by nixel2007** [comment]
Вопрос в догонку - что возвращает 1С при ЧтениеТекста.Прочитать() от пустого файла? Неопределено или пустую строку?

**Comment by SuffArt** [comment]
Возвращает Неопределено, но по идее то пустая строка должна быть, или нет?

**Comment by SuffArt** [comment]
1с говорит "Не определено".

**Comment by Mr-Rm** [comment]
ЧтениеТекста.Прочитать() от пустого файла - Неопределено. Исправления для совместимости были в коммите [71fce0b](https://github.com/EvilBeaver/OneScript/commit/71fce0b2736a442ea99ae86b0f964ffe60488353#diff-b4d6d97344896440c5dda9a3ab447560).
Но, получается, где-то нет приведения значения Неопрелено к пустой строке.

**Comment by EvilBeaver** [comment]
Получается, что ошибки нет. Регулярка.НайтиСовпадения(Неопределено) говорит, что аргумент не может быть неопределенным. Все честно.

Совместимость с 1С, как понимаете, проверить нельзя, ибо в 1С такого вообще нет.

**Comment by Mr-Rm** [comment]
Есть противоречие:
`Сообщить(Неопределено)` - ок
`Регулярка.НайтиСовпадения(Неопределено)` - падает.
Неопределено должно всегда приводится к пустой строке, если тип параметра - строка. А для Регулярка.НайтиСовпадения так и есть: 
https://github.com/EvilBeaver/OneScript/blob/3a2cd27b9bfed0db8d5ac7e3f2352acb231fbbda/src/ScriptEngine.HostedScript/Library/Regex/Regex.cs#L47-L48
Однако было сделано
https://github.com/EvilBeaver/OneScript/blob/3a2cd27b9bfed0db8d5ac7e3f2352acb231fbbda/src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs#L74-L77
Обсуждалось в #634 и далее по ссылкам.

**Comment by EvilBeaver** [comment]
Ааа, вот оно и выстрелило! @dmpas, а я говорил, говорил... https://github.com/EvilBeaver/OneScript/pull/634#discussion_r158683439

**Comment by Mr-Rm** [comment]
Собственно, https://github.com/EvilBeaver/OneScript/issues/735#issuecomment-375314758
Убрать проверку на Undefined, а исключения при невозможности приведения типов выбросят value.AsNumber() и прочие.
Если метод вызывается из onescript, то его среда исполнения и должна выполнять контроль за преобразованием типов. А если сделан вызов из C#, и передан null вместо строки, то пусть срабатывает системное исключение.

**Comment by EvilBeaver** [comment]
Тут скорее другое. при маршалинге Неопределено к string что должно быть? Исключение - как здесь, или приведение к строке, как в Сообщить()?

**Comment by Mr-Rm** [comment]
Приведение к пустой строке.

**Comment by EvilBeaver** [comment]
Так раньше и было, ЕМНИП. Решено было переделать, не?

**Comment by Mr-Rm** [comment]
После переделки для исправления функции Сообщить() пришлось в нее вставить проверку `message ?? ""`. Если маршалить Неопределено в null, то подобные проверки нужны во _всех_ имеющихся (и _будущих_) функциях, принимающих строки. Сейчас падает не только рассматриваемое `НайтиСовпадения(Неопределено)`, но и, например, `СтрНайти(Неопределено,"")`, которое в 1С благополучно возвращает 1.
