### ISSUE TITLE
ЧтениеZIP - странный поиск файла по имени внутри архива

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/OneScript#816]
Народ, есть веселуха с поиском элементов внутри Zip-файлов в 1С и OneScript
`Чтение.Элементы.Найти(ИмяФайла);`

Справка из 1С
```
ЭлементыZipФайла.Найти (ZipFileEntries.Find)
ЭлементыZipФайла (ZipFileEntries)
Найти (Find)
Синтаксис:

Найти(<ИмяЭлемента>)
Параметры:

<ИмяЭлемента> (обязательный)

Тип: Строка. 
Имя элемента.
Возвращаемое значение:

Тип: ЭлементZipФайла; Неопределено. 
Если не найдена, возвращается Неопределено.
Описание:

Осуществляет поиск элемента по его имени.

Доступность: 

Тонкий клиент, сервер, толстый клиент, внешнее соединение.
```

В 1скрипт ищется по имени файла, а не полному пути.

Интересно, как в 1С ищется?  все-таки по имени файла или по полному имени.
Из справки 1С непонятно.

кто-нибудь в курсе?

**Comment by artbear** [comment]
В итоге штатный поиск юзать для сложных архивов практически нельзя
т..е. вместо `Элемент = Чтение.Элементы.Найти(ИмяФайла);`
приходится делать спец.метод
```bsl
	Элемент = НайтиЭлементАрхива(Чтение, ИмяФайла);

Функция НайтиЭлементАрхива(Знач Чтение, Знач ПолноеИмя)
	Для Каждого Элемент Из Чтение.Элементы Цикл
		Если СравнитьПутиФайлов(Элемент.ПолноеИмя, ПолноеИмя) Тогда
			Возврат Элемент;
		КонецЕсли;
	КонецЦикла;
	Возврат Неопределено;
КонецФункции
```

**Comment by EvilBeaver** [comment]
Артур, как в 1С - берем за эталон. Как оно в 1С?

**Comment by Mr-Rm** [comment]
В 1С ищется только по имени файла. Если в структуре архива есть файлы с одинаковыми именами, выдается тот, который находится раньше в каталоге zip-файла (обычно, ранее других добавленный в архив). Поиск по полному имени не находит ничего.
Качество эталона сомнительное, но поведение OneScript полностью соответствует.
А вот что не соответствует: у класса "ЭлементZipФайла" отсутствуют свойства "ИсходноеИмя" и другие вида "Исходное..."
