### ISSUE TITLE
Зависает формат лидирующих нулей

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#818]
**Опишите ошибку**

Формат(3,"ЧЦ=4; ЧВН=; ЧГ=") зависает при попытке выполнения.
В 1С работает - выводит лидирующие нули.

**Воспроизведение ошибки**
1. Запустить код ...
2. Увидеть ошибку

**Ожидаемое поведение**
Должна вести себя как в 1С - вывести строку 0003

**Comment by Mr-Rm** [comment]
"ЧВН" значения не имеет. Виснет от "ЧГ=", а также при явном "ЧГ=0" и при **любом другом значении, содержащем 0**.
Зацикливается вот тут, из-за size==0:
https://github.com/EvilBeaver/OneScript/blob/24fbe0f73bd7e49e1644d6957e920461c347ec26/src/ScriptEngine/Machine/ValueFormatter.cs#L302-L303
и далее
https://github.com/EvilBeaver/OneScript/blob/24fbe0f73bd7e49e1644d6957e920461c347ec26/src/ScriptEngine/Machine/ValueFormatter.cs#L310
Помимо этого бага, реализация формата "ЧГ" **сильно** не соответствует _спецификации_.

**Comment by EvilBeaver** [comment]
@Mr-Rm спасибо! А что именно там не соответствует? (не помню спецификацию совсем)

**Comment by Mr-Rm** [comment]
Из СП:
> ЧГ (NG) - порядок группировки разрядов числа. В качестве значения указываются числа, _через запятую_, обозначающие количество группируемых разрядов справа налево. Имеют смысл только два первых числа. Первое из них указывает первичную группировку, то есть ту, которая будет использована для наименее значимых разрядов целой части числа. Если второе число не указано, то будут сгруппированы только наименее значимые разряды. Если в качестве второго числа задан 0, то для всех разрядов целой части числа будет применено значение указанное для первичной группировки. Если в качестве второго числа используется значение, отличное от 0, то это значение будет использовано для группировки всех разрядов, кроме уже сгруппированных наименее значимых.

Что не указано: если первое число не задано, оно считается равным 0; если первое число равно 0, второе игногрируется, а группировка не производится. Запись "ЧГ=3," соответствует "ЧГ=3", а не "ЧГ=3,0".
Кроме того, **все** нечисловые символы пропускаются, и разделителем может быть любой символ, т.е. "ЧГ=ёёё-3.2+++1!!!" равнозначно "ЧГ=3,2". Но если следом идёт другой параметр, то разделяющая ';' должна быть.

**Comment by Mr-Rm** [comment]
Отмечу ещё по другому параметру:
> ЧВН (NLZ) - нужно ли выводить лидирующие нули. Значение данного параметра не задается, собственно наличие параметра определяет вывод лидирующих нулей. 

При этом "ЧВН=;" означает, что параметр задан и равен нулю, а запись "ЧВН;" - что параметр не задан.

**Comment by Mr-Rm** [comment]
Проблема: NumberFormatInfo.NumberGroupSizes не поддерживает значения больше 9. Таким образом, 1С `Формат(123456789123456789,"ЧГ=12")` выдает "123456 789123456789", а onescript падает с системным исключением. Возможные варианты действий:
- форматировать вручную
- добавить проверку и выбрасывать исключение onescript
- оставить системное исключение

**Comment by EvilBeaver** [comment]
Либо вручную, либо оставить системное. Лучше сделать совместимое форматирование, конечно

**Comment by Mr-Rm** [comment]
А ещё забыли про неразрывный пробел в качестве NumberGroupSeparator по умолчанию.

**Comment by Mr-Rm** [comment]
Углубился в форматы чисел:

Число|Строка формата|Результат|Эталон
-|-|-|-
1234567|ЧРГ=//|1//234//567|1/234/567
123.345|ЧЦ=8;ЧДЦ=2|123,34|123,35
123.345|ЧЦ=8;ЧДЦ=4|123,345|123,3450
123.345|ЧЦ=8;ЧДЦ=2ц|123|123,35
1234567890.345|ЧЦ=10;ЧДЦ=2|1 234 567 890,35|99 999 999,99
и ещё:
1234567.89|ЧЦ=10;ЧДЦ=2;ЧВН=1; Л=hi_IN|01 23 4567.89|०,१२,३४,५६७.८९
1234567.89|ЧЦ=10;ЧДЦ=2;ЧВН=1; Л=ar_AE|01 23 4567.89|٠١٬٢٣٤٬٥٦٧٫٨٩

Часть тестов в tests\formatting.os неверны.
Формат ЧС (NS) - сдвиг разрядов - отсутствует.

**Comment by EvilBeaver** [comment]
Форматирование сделано, на самом деле, довольно номинально на самых ранних этапах развития. Задачи полностью поддержать тогда не ставилось, поэтому в Формате много можно еще чего накопать.

**Comment by EvilBeaver** [comment]
Локализации точно нет )

**Comment by EvilBeaver** [comment]
@Mr-Rm правильно я понимаю, что это можно закрыть?

**Comment by Mr-Rm** [comment]
Конкретно по этому issue - всё исправлено до рабочего состояния. 
Нужен некоторый рефакторинг, с учетом поддержки форматов 'ЧС' и 'Ч'.

**Comment by EvilBeaver** [comment]
Тогда я закрою
