### ISSUE TITLE
Исправления в объекте ЗаписьДанных

### ISSUE THREAD

**Issue by alyuev** [EvilBeaver/OneScript#821]
При формировании файла с помощью объекта ЗаписьДанных файл-результат формируется некорректно.

Это связано с тем, что объект BinaryWriter дозаписывает размер строки при записи строкового значения.

Решение:
в файле src/ScriptEngine.HostedScript/Library/Binary/DataWriter.cs сделать следующие исправления:

строки 
_binaryWriter.Write(line);   (номер строк: 282 и 315)
_binaryWriter.Write(LineSplitter); (номер строки 324)
_binaryWriter.Write(lineSplitter); (номер строки 326)

заменить на соответственно:
_binaryWriter.Write(line.ToCharArray())
_binaryWriter.Write(LineSplitter.ToCharArray());
_binaryWriter.Write(lineSplitter.ToCharArray());

Просто метод Write для строковых пишет еще и длину строки:
https://docs.microsoft.com/en-us/dotnet/api/system.io.binarywriter.write?view=netframework-4.7.2#System_IO_BinaryWriter_Write_System_String_

**Comment by nixel2007** [comment]
Спасибо! Может быть сразу пулл-реквест пришлете? :)
