### ISSUE TITLE
Ошибка при сложении даты от начала времен плюс универсальную дату в мс

### ISSUE THREAD

**Issue by DitriXNew** [EvilBeaver/OneScript#823]
При выполнении кода:
`F = Дата(1,1,1,0,0,0) + Цел(ТекущаяУниверсальнаяДатаВМиллисекундах()/1000);`
На выходе получаю:

`Ошибка в строке: 1 / Внешнее исключение (System.OverflowException): Значение было недопустимо малым или недопустимо большим для Int32.}
`
**Окружение**
 - ОС Win 16: 
 - Версия 1.0.21.266:

**Дополнительная информация**

**Comment by DitriXNew** [comment]
Больше никак случайно нельзя получить универсальную дату?

**Comment by JohnyDeath** [comment]
Можно попробовать ОКР вместо Цел сделать.
Или еще как-нибудь "переопределить" у себя в коде "Цел"
Или дождаться ночника,тут вот добрый человек уже поправил
