### ISSUE TITLE
Не создаётся файл launch.json для OneScript Debug в VSCode после нажатия F5

### ISSUE THREAD

**Issue by ildary** [EvilBeaver/OneScript#825]
1. Установил OneScript и VSCode
2. Скачал OneScript Debug, перезашел в VSCode
3. Создал проект (в нём папку .vscode), нажал F5-1Script Debugger
4. В папке .vscode не вижу файла launch.json

**Ожидаемое поведение**
В папке .vscode должен создаться файл launch.json для отладки.

**Окружение**
Windows Server 2008 R2 Standart SP1
VSCode x64 1.28.1
OneScript 1.21.298

**Comment by EvilBeaver** [comment]
После нажатия F5 должен появиться пункт меню сверху с выбором отладчика. Там выбираем "1Script Debug". После выбора должен создаваться файл launch.json

если не создается - то я не знаю, как такое воспроизвести. Может гифку запишете?

**Comment by ildary** [comment]
Записал, правда гифку не умею, получился avi на 180Мб. Вот ссылка: https://www.dropbox.com/sh/dw2qy5gq1c3i6jh/AAC-sJujLZi1RV5hQJpcd7pNa?dl=0

Мне не даёт покоя то, что VSCode сегодня обновился на новую подверсию (1.28.1) - может ли быть причина в этом? Стоит ли тестить на 1.28.0?

**Comment by EvilBeaver** [comment]
@nixel2007 @asosnoviy - парни, сможете помочь? Я прям вообще в бегах сейчас

**Comment by nixel2007** [comment]
@EvilBeaver тоже наблюдал такое, решалось перезапуском. либо глюк редактора (вероятно, т.к. проявлялось как раз на какой-то из версий 1.28.х), либо самого DAP (маловероятно). лечилось перезапуском редактора.

предлагаю закрыть как won't fix, т.к. непохоже, что это наша зона ответственности.

**Comment by nixel2007** [comment]
@ildary воспроизводится еще? или переоткрытие редактора помогло?

**Comment by ildary** [comment]
К сожалению не помогло. Обновил VSCode еще раз, закрывал сеанс Windows - но файл  launch.json всё равно не создается.

**Comment by nixel2007** [comment]
А если перейти на вкладку "отладка" слева и руками добавить конфигурацию
отладчика прям оттуда?

пн, 29 окт. 2018 г. в 12:57, Yusupov Ildar <notifications@github.com>:

**Comment by ildary** [comment]
Спасибо за подсказку, таким образом файл появился, но я не совсем понял концепцию отладки - ставлю точку прерывания, запускаю скрипт на выполнение (F1, Enter, Enter)- программа запущена и точка останова не сработала. Через некоторое время внизу появилась оранжевая надпись - кеш отладчика обновлен. После чего я повторно запускаю программу на запуск - и снова точка останова не сработала.

**Comment by EvilBeaver** [comment]
"кеш отладчика обновлен" - это какие-то нововведения со стороны Visual Studio..

**Comment by ildary** [comment]
Вот примерно так выглядит: https://imgur.com/a/FD8pY5Z

**Comment by nixel2007** [comment]
Это не кэш отладчика. Это кэш bsl-плагина

**Comment by ildary** [comment]
Извините, у меня нет опыта работы в VSCode. Ещё пожалуйста уточните - как мне теперь отлаживать скрипт - я поставил точку останова, что далее?

**Comment by nixel2007** [comment]
запускаете через f5? если Windows, то при первом запуске должен был ругнуться брандмаэуэр на открытие новых портов. было такое? не блокировали работу?

**Comment by ildary** [comment]
Ничего ругалось, доступа к настройкам файервола у меня нет - т.к. они берутся из домена. Похоже, что без доменного админа тут не получится.

**Comment by nixel2007** [comment]
содержимое файла launch.json можете скинуть? он должен был создасться в подпапке .vscode

**Comment by ildary** [comment]
Вот содержимое:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Отладка 1Script",
            "type": "oscript",
            "request": "launch",
            "program": "${file}",
            "args": [],
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": null,
            "debugPort": 2801,
            "protocol": "internal"
        }
    ]
}

**Comment by nixel2007** [comment]
Сверим последовательность действий. Вот так запускаете? (вместо клика мышкой можно по f5)

![default](https://user-images.githubusercontent.com/1132840/47708412-0f260380-dc3f-11e8-89e7-65d037f6e1c3.gif)

**Comment by ildary** [comment]
Вернулся к вопросу через месяц - и о чудо - всё заработало само.

**Comment by tomskih13** [comment]
Добрый день! у меня так же не получается запустить отладчик в VSC. При нажатии f5 в debug console выводится текст, о необходимости заполнения доп параметров, а об этом ничего найти не могу. Может быть подскажите, изменить в своих действиях?

![image](https://user-images.githubusercontent.com/35293952/86820478-f2480180-c0aa-11ea-889b-cdcf8c6a8890.png)

**Comment by tomskih13** [comment]
Все получилось. Обновился до последней версии. И debug заработал.
