### ISSUE TITLE
Неверные результаты функции Pow

### ISSUE THREAD

**Issue by vasvl123** [EvilBeaver/OneScript#831]
**Опишите ошибку**

Функция Pow выдает неверные результаты

**Воспроизведение ошибки**
1. Запустить код ...

Функция Степень(Знач Осн, Знач Пок)
	Рез = Осн;
	Пока Пок > 1 Цикл
		Рез = Рез * Осн;
		Пок = Пок - 1;
	КонецЦикла;
	Возврат Рез;
КонецФункции // Степень()

Сообщить("Тестирование функции Pow");
Для ч = 2 по 9 Цикл
	Для с = 1 По 100 Цикл
		Если НЕ Степень(ч, с) = Pow(ч, с) Тогда
			Сообщить("Неверный результат функции Pow при возведении числа " + ч + " в степень = " + с);
			Прервать;
		КонецЕсли;
	КонецЦикла;
КонецЦикла;

2. Подать на вход параметры ...
3. Увидеть ошибку

Тестирование функции Pow
Неверный результат функции Pow при возведении числа 2 в степень = 50
Неверный результат функции Pow при возведении числа 3 в степень = 32
Неверный результат функции Pow при возведении числа 4 в степень = 25
Неверный результат функции Pow при возведении числа 5 в степень = 22
Неверный результат функции Pow при возведении числа 6 в степень = 20
Неверный результат функции Pow при возведении числа 7 в степень = 18
Неверный результат функции Pow при возведении числа 8 в степень = 17
Неверный результат функции Pow при возведении числа 9 в степень = 16

**Ожидаемое поведение**
Опишите, как должна вести себя система в указаных условиях. Ведет ли себя 1С в тех же условиях иным образом?

В 1с работает

**Окружение**
 - ОС: ubuntu
 - Версия: 1Script Execution Engine. Version 1.0.21.298

**Дополнительная информация**

**Comment by vasvl123** [comment]
На win7 аналогично

**Comment by dvakor** [comment]
Интересненько, результат Pow .NET верный, но возвращает double, при приведении к decimal значение меняется, попробывал хак (decimal)((long)power), так приведение работает верно.

**Comment by dvakor** [comment]
Нашел в доках по методу Convert.ToDecimal(double)

Ответ тут:
https://docs.microsoft.com/en-us/dotnet/api/system.convert.todecimal?view=netframework-4.7.2#System_Convert_ToDecimal_System_Double_

The Decimal value returned by this method contains a maximum of 15 significant digits. If the value parameter contains more than 15 significant digits, it is rounded using rounding to nearest

такие дела :)

**Comment by EvilBeaver** [comment]
Поправьте меня, разве приведение (long)power не обрежет дробную часть?

**Comment by dvakor** [comment]
ну да, обрежет, он же целочисленный тип
Это было не предпологаемое решение, а просто результат быстрых эксперементов.

Изучая вчера вопрос узнал интересную особоенность, Double вроде как хранит 15 знаков, но по факту 17 "для внутренних" целей и при приведении он то 15 отдает, то 17

И нашел вот такой метод.

`static decimal PreciseConvert(double doub)
{
  // Handle infinities and NaN-s first (throw exception)

  // Otherwise:

  return Decimal.Parse(doub.ToString("R"), NumberStyles.AllowExponent | NumberStyles.AllowDecimalPoint);
}`

но это больше на хак похоже, сам пока не проверял.

**Comment by EvilBeaver** [comment]
Чета я не в восторге от идеи конвертить числа к строке... Может тут наконец можно вернуться к идее @dmpas использовать класс BigDecimal... Или сделать альтернативную реализацию Math.Pow(decimal)

**Comment by Mr-Rm** [comment]
Нужно отдельно обрабатывать случай целой положительной степени, как, похоже, и делает 1С.
Все прочие варианты Pow и другие математические функции работают с точностью double, до 15-ти знаков. Пример:
Pow(2, 50) == 1125899906842624 // все знаки верны
Pow(2, 50.001) == 1126680591722150 // точное значение 1126680591722149.3776...

**Comment by EvilBeaver** [comment]
@Mr-Rm я тоже пришел к такому выводу. Целый показатель и целое основание - это особые случаи, работающие по твоему алгоритму умножения N раз.

**Comment by Mr-Rm** [comment]
Только целый показатель, для любого основания. 1С даёт:
Pow(2.001, 50) == 1154394986095681.37546174…[еще 132 цифры]…4900100001 // точно
И не умножением N раз, оптимальней можно.
