### ISSUE TITLE
Неверный результат сравнения двоичных данных

### ISSUE THREAD

**Issue by vasvl123** [EvilBeaver/OneScript#834]
**Опишите ошибку**
Неверный результат сравнения двоичных данных

**Воспроизведение ошибки**
1. Запустить код ...

а = ПолучитьДвоичныеДанныеИзСтроки("123");
б = ПолучитьДвоичныеДанныеИзСтроки("123");
Сообщить("Результат сравнения а=б:" + (а = б));

2. Подать на вход параметры ...
3. Увидеть ошибку

Результат сравнения а=б:Нет

**Ожидаемое поведение**
Опишите, как должна вести себя система в указаных условиях. Ведет ли себя 1С в тех же условиях иным образом?

в 1с равно

**Окружение**
 - ОС: win7
 - Версия: 1Script Execution Engine. Version 1.1.0.309

**Дополнительная информация**

**Comment by EvilBeaver** [comment]
Да, для двоичных данных сравнение не реализовано
