### ISSUE TITLE
Текущая дата с миллисекундами

### ISSUE THREAD

**Issue by pallid** [EvilBeaver/OneScript#836]
# Описание задачи

**Опишите вашу Цель, которую вы сможете достичь с помощью новой функциональности**
Какую задачу вы смогли бы решить, если бы в 1Script была предлагаемая Вами функциональность?

Хочется иметь возможность получать текущую дату с миллисекундами для большей информационности (например в логе приложения) 

**Опишите решение**
Четкое и понятное описание того, что Вы хотите видеть в проекте и как именно?

Сообщить(ТекущаяДатаСМиллисекундами()); // результат "21.11.2018 21:45:23:392"

**Дополнительная информация**
Любая дополнтельная информация

Вот тут 
https://github.com/EvilBeaver/OneScript/blob/9f9b1b888f1177ffc727b473ee6d54c4d289963b/src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs#L435

Вот это 

```
[ContextMethod("ТекущаяДатаСМиллисекундами", "CurrentDateWithMilliseconds")]
        public string CurrentDateWithMilliseconds()
        {
            return DateTime.Now.ToString("dd.MM.yyyy hh:mm:ss:fff");
        }
```

**Comment by dmpas** [comment]
@pallid предлагаю форматом воспользоваться:
https://github.com/EvilBeaver/OneScript/pull/837

**Comment by pallid** [comment]
Тады закрываю

**Comment by dmpas** [comment]
рано. ПР ещё ж не влили.

**Comment by pallid** [comment]
Так же ш в ПР указана #837 

Ну ок

**Comment by dmpas** [comment]
837 - это ПР.
836 (тут) - досада.
