### ISSUE TITLE
ТекущаяДата() не равна себе же

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#838]
**Опишите ошибку**
Так как ТекущаяДата() возвращает CLR-дату, которая в себе содержит дробную часть, а особенности языка не предполагают работу с дробной частью, то получается, что мы не сможем создать вручную точно такое же значение.

**Воспроизведение ошибки**
```bsl
ДатаИсходная = ТекущаяДата();
ДатаСозданнаяВручную = Дата(Формат(ДатаИсходная, "ДФ=ггггММддЧЧммсс"));
Сообщить(ДатаИсходная);
Сообщить(ДатаСозданнаяВручную);

Сообщить(ДатаИсходная = ДатаСозданнаяВручную);

```

Вывод:
```
21.11.2018 18:10:50
21.11.2018 18:10:50
Нет
```

**Ожидаемое поведение**
Рядовой одинэсник ожидает, что они будут равны.

**Comment by EvilBeaver** [comment]
Гыгыгы. А в 1С - можем? а то вдруг?

**Comment by Mr-Rm** [comment]
Можем:
```
д1=ТекущаяДата();
д2=д1+0.0001; // если меньше, то будут равны
сообщить("даты:"+(д1=д2)); // Нет в 1С, Да в OneScript
сообщить("строки:"+(строка(д1)=строка(д2))); // Да
```
В OneScript  различие идёт только до тысячной: `д2=д1+0.001`, меньшее округляется вверх.

**Comment by EvilBeaver** [comment]
Т.е. если я правильно понял, то в 1С все равно есть доли секунд?

**Comment by Mr-Rm** [comment]
Да, в дате/времени документов используются доли секунд. Если не ошибаюсь, SQL DATETIME2(4).

**Comment by EvilBeaver** [comment]
```
ТД = ТекущаяДата();
РучнаяДата = Дата(Год(ТД),Месяц(ТД),День(ТД),Час(ТД),Минута(ТД),Секунда(ТД));
Сообщить(ТД = РучнаяДата);
```

В 1С равно.

**Comment by dmpas** [comment]
@EvilBeaver 
```bsl
	ТД = ТекущаяДата();
	РучнаяДата = Дата(Год(ТД),Месяц(ТД),День(ТД),Час(ТД),Минута(ТД),Секунда(ТД)) + 0.001;
	Сообщить(ТД = РучнаяДата);
```
Ответ 1С: Нет

**Comment by dmpas** [comment]
то есть, разность оскрипта и 1С поведения устраняется всего лишь устранением долей секунд в ТекущейДате.

**Comment by EvilBeaver** [comment]
А ты хитрый. Я было собрался выделять отдельный класс даты и переопределять Equals

**Comment by Mr-Rm** [comment]
ТекущаяДата() в 1С возвращает целое число секунд. В ОС - до 7-го знака, как в C# System.DateTime, но методы DateTime работают только c целыми миллисекундами.
Округлять результат ТекущаяДата() до 3-го знака? Или до целых секунд?

**Comment by dmpas** [comment]
Вообще, лично я редко сравниваю в 1С текущую дату с чем-то определённым. Обычно на больше-равно или меньше-равно. Потому, наверное, можно и не округлять.

**Comment by EvilBeaver** [comment]
@Mr-Rm лучше до целых секунд, т.к. нам вроде как негде применить доли секунд

**Comment by Mr-Rm** [comment]
`ТекущаяДата()` определена в двух местах: как функция глобального контекста `CurrentDate()` и как команда ВМ `CurrentDate` (зачем-то, хотя понятно, что по аналогии с 1С). Соответственно, после компиляции вызов глобальной функции появится не может. Возможные варианты при внесении исправлений:
- убрать `ТекущаяДата()` из глобального контекста;
- ничего не менять, исправлять в обоих местах;
- игнорировать команду CurrentDate при компиляции;
- убрать команду CurrentDate (и некоторые другие) из ВМ;
- ?
По целым секундам: учитывать миллисекунды при округлении или просто отбрасывать? Второе проще, да и вряд ли нужна большая точность.

**Comment by EvilBeaver** [comment]
У нас две текущих даты? Фигасе! Конечно, одну убрать. Насчет опкодов встроенных функций, так сделано в 1С и просто утянуто оттуда. Для 1С "встроенные" функции - это именно опкоды и стало быть, доступны везде, как часть языка. Можно и убрать, только зачем?

Я за второе (ну я уже говорил выше)

**Comment by ghost** [comment]
Не то убрали !!!

**Comment by EvilBeaver** [comment]
@allustin поясни плиз

**Comment by ghost** [comment]
@EvilBeaver метод теперь не доступен в компонентах DLL которые, в OScript.Web и в OScript.For.Sharepoint

Старый код перестал работать - я пока вернул назад в форке.

**Comment by ghost** [comment]
Щас буду чинить - посмотрю как мигрировать на токены.

**Comment by EvilBeaver** [comment]
> метод теперь не доступен в компонентах DLL

@Mr-Rm а у нас точно есть байткод ТекущаяДата()? Если есть, то все компоненты должны видеть его, т.к. этот символ предоставляет компилятор...

@allustin что ты имеешь в виду под "метод недоступен в компонентах"? а где он там использовался и о каком сообщении об ошибке идет речь?

**Comment by ghost** [comment]
@EvilBeaver 5 сек

**Comment by ghost** [comment]
Нашел в Oscript.Web - https://github.com/EvilBeaver/OneScript.Web/blob/develop/src/OneScript/Application/WebGlobalContext.cs#L52

Вот это уже работать не будет

**Comment by EvilBeaver** [comment]
Да, в этот класс она засунута по ошибке. Т.е. ТекДата не "теперь" в компилере, а всегда там была. А в глоб.контекстах светилась по ошибке и ничего не делала.

**Comment by Mr-Rm** [comment]
@EvilBeaver есть байткод, `OpperationCode.CurrentDate = 96`
https://github.com/EvilBeaver/OneScript/blob/2f88c5ac48b8fc5f483fc72fdb62c0da6144a322/src/ScriptEngine/Machine/Core.cs#L112
https://github.com/EvilBeaver/OneScript/blob/2f88c5ac48b8fc5f483fc72fdb62c0da6144a322/src/ScriptEngine/Machine/MachineInstance.cs#L619
