### ISSUE TITLE
Ошибка вызова методов SDO из C#

### ISSUE THREAD

**Issue by dvakor** [EvilBeaver/OneScript#839]
**Опишите ошибку**
При "программном" (из C#) вызове метода SDO, внутри которого идет вызов метода другого объекта SDO движок падает с ошибкой 
System.IndexOutOfRangeException

**Воспроизведение ошибки**
Создать объект унаследованный от SDO, вызвать метод, которые вызывает метод другого объекта так же из C#

**Ожидаемое поведение**
Все должно работать без ошибок )

**Окружение**
ОС: Windows server 2016
Версия скрипта: Последняя из дев ветки

**Дополнительная информация**
Все падает в 
`internal IValue ExecuteMethod(IRunnable sdo, int methodIndex, IValue[] arguments)`
Идет обращение к LoadedModule (_module) последнего объекта, поэтому при двойном вызове он соответственно не равен модулю текущего объекта.

**Comment by dvakor** [comment]
Пример кода не могу сделать т.к. на голом движке ошибка не воспроизводится ибо баг проявляется при вызове метода другого объекта в другом потоке, а в той же ВК нет доступа к классу движка и вызвать UpdateContext или LoadMemory нет возможности, т.е. баг можно воспроизвести в проектах которые работают со SciptingEngine.

В целом если посмотреть на этот метод, то тут используется как раз модуль из объекта sdo
https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine/Machine/MachineInstance.cs#L86

А тут, как раз где возникает ошибка, берется модуль текущего фрейма
https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine/Machine/MachineInstance.cs#L99

Могу прислать ПР, там буквально 2 строки, только вот по причинам выше даже тест не написать.

**Comment by EvilBeaver** [comment]
После отнаследования надо корректно переопределить *Own методы, тогда вызовы будут работать корректно. Надо смотреть примеры кода, как там сделано. Основа - свойство MachineInstance.Current - возвращает экземпляр машины для текущего потока.

Т.е. по описанию ошибка не воспроизводится, например, проект osweb работает со scriptingEngine и методы вызываются. Нужно более понятное описание воспроизведения. Возможно по скайпу вечером по Мск.

**Comment by dvakor** [comment]
я когда делал, по факту все копировал с ос.веба как раз, ошибка как раз не в наследнике ScriptDrivenObject а в UserScriptContextInstance вылетает.

В общем написал тебе в телегу.

**Comment by dvakor** [comment]
ошибка была в работе с методом LoadMemory, к ошибке движка отношения не имеет.
