### ISSUE TITLE
ТаймаутЧтения в TCPСоединение по факту оказывается больше

### ISSUE THREAD

**Issue by vasvl123** [EvilBeaver/OneScript#840]
**Опишите ошибку**
Под Windows, значение ТаймаутЧтения в TCPСоединение по факту оказывается больше установленного (обычно больше на 500 мс). В Ubuntu такой проблемы нет.

**Воспроизведение ошибки**
1. Запустить код ...

```bsl
Сервер = Новый TCPСервер(8888);
Сервер.Запустить();

Попытка

	Соединение = Сервер.ОжидатьСоединения(0);

	Соединение.ТаймаутЧтения = 1000;

	Запрос = Соединение.ПрочитатьСтроку();
	
	// ждем данные а их нет
	врНачало = ТекущаяУниверсальнаяДатаВМиллисекундах();
	Запрос = Соединение.ПрочитатьСтроку();

Исключение

	Сообщить(ТекущаяУниверсальнаяДатаВМиллисекундах() - врНачало);

КонецПопытки;

Сервер.Остановить();
```

2. Подать на вход параметры ...

Открыть localhost:8888 в браузере

3. Увидеть ошибку

1530.0875

**Ожидаемое поведение**
Опишите, как должна вести себя система в указаных условиях. Ведет ли себя 1С в тех же условиях иным образом?

**Окружение**
 - ОС: win7 64
 - Версия: 1Script Execution Engine. Version 1.1.0.321

**Дополнительная информация**

Проблема возможно и не в движке а в .Net. С ТаймаутОтправки  тоже есть проблема, напишу отдельно.

**Comment by EvilBeaver** [comment]
Строго говоря, класс TCPСоединение заброшен, т.к. у него не было потребителей. Он работает, но за точность я сейчас не поручусь. Тем более, если речь идет о точности 500мсек для таймаутов, которые никогда и не являлись точными в сетевых сокетах. Они всегда приблизительные в любом языке, независимо от.

**Comment by vasvl123** [comment]
TCPСервер.ОжидатьСоединения(Таймаут) вполне себе точно работает. Ладно, может сам когда докопаюсь.

**Comment by vasvl123** [comment]
Запустил этот код с Mono под Windows и ... работает нормально! 58 мс. Походу это косяк в  .Net

**Comment by EvilBeaver** [comment]
Ок, закрываю.
