### ISSUE TITLE
просмотр структуры переменных (соответствие, тз итп) как в конфигураторе 1с

### ISSUE THREAD

**Issue by gortolspb** [EvilBeaver/OneScript#841]
# Доработать watch для отображения состава объектных переменных (Структура, ТЗ итп)

**выявление в структуре переменных данных для использования в коде значений**
Какую задачу вы смогли бы решить, если бы в 1Script была предлагаемая Вами функциональность?

**Опишите решение**
в окне Watch по отлаживаемой переменной, слева + для раскрытия структуры

**Comment by dvakor** [comment]
@EvilBeaver @nixel2007 Как будем выводить данные в вотчер, если элемент имеет и named и indexed props?

щас у меня пока так выводится

![image](https://user-images.githubusercontent.com/4038422/64314132-0d07a080-cfd8-11e9-9eb8-1abe9e5e7d56.png)

мое имхо если есть и то и то, выводить только named.

в тоже время, например в ТЗ, надо бы выводить и indexed и named по идее

![image](https://user-images.githubusercontent.com/4038422/64314204-5ce66780-cfd8-11e9-97fe-00ef0d8ceea1.png)

в общем я в смятении немного :)

**Comment by EvilBeaver** [comment]
Надо запустить отладчик node.js и посмотреть как сделано там. У меня только после просмотра отладки node.js сложилась картинка, что они вообще имели в виду в этом API

**Comment by dvakor** [comment]
> Надо запустить отладчик node.js и посмотреть как сделано там. У меня только после просмотра отладки node.js сложилась картинка, что они вообще имели в виду в этом API

в JS есть объект к которому можно и по индексу и по имени обратиться?)

с ТЗ и прочими еще понятно, что и то то выводить, в ноде кстати так же. А вот со строкой ТЗ непонятно пока

**Comment by EvilBeaver** [comment]
> в JS есть объект к которому можно и по индексу и по имени обратиться

Ну да. У array есть свойство length и по индексам элементы массива

**Comment by dvakor** [comment]
Чутка не верно выразился, есть ли объект к свойств которого можно обратится как по имени, так и по индексу, как например у строки тз, к своству можно обратится как через [0],так и через .Имясвойства

**Comment by nixel2007** [comment]
@ArchLord42RU да... Есть. Примерно *все* объекты в JS допускают обращение и по индексу и через точку :)

**Comment by dvakor** [comment]
@EvilBeaver @nixel2007 Вы миня не понимать :(
в 1Се есть объекты, в моем примере КолонкиТЗ \ СтрокаТЗ, к свойсвам которого можно обратится как через порядковый индекс, так и через именнованный одновременно, возможно термины я пишу не совсем верно :)

Вот пример:

```
ТЗ = Новый ТаблицаЗначений;
ТЗ.Колонки.Добавить("МояСуперКолонка");

Сообщить(ТЗ.Колонки[0].Имя); //МояСуперКолонка
Сообщить(ТЗ.Колонки["МояСуперКолонка"].Имя); //МояСуперКолонка
```

В JS:

```
let b = {"prop": "val"}
Console.log(b[0]); //undefinded <<< тут обращение по порядковому индексу не пашет
Console.log(b["prop"]); //val

или пример с массивом

let c = [1];
c.prop = 2;
Console.log(c[1]); //undefinded <<< тут так же обращение по порядковому индексу не пашет
Console.log(c["prop"]); //2
```

Сейчас при отладке выводится так

Колонка
- МояСуперКолонка : КолонкаТЗ
- 0 : КолонкаТЗ

В конфигураторе такие штуки игнорятся и выводится просто

Колонка
- МояСуперКолонка : КолонкаТЗ

Собственно вопросы:

Выводим все индексы, или только именованные у таких объектов?
Если хз, то есть ли пример в ноде такого объекта?

**Comment by EvilBeaver** [comment]
Выводим, как проще. Если проще именованные - выводим именованные. Если именованные сложно - выводим численные

**Comment by EvilBeaver** [comment]
сразу оба, наверное не нужно

**Comment by dvakor** [comment]
> Выводим, как проще. Если проще именованные - выводим именованные. Если именованные сложно - выводим численные

Проще всего выводить и то и то :)

**Comment by dvakor** [comment]
> сразу оба, наверное не нужно

У меня там идея есть как отсеч нужные объекты от вывода порядкового индекса, но надо показывать, может на ИС конфе, если будет время, там не много времени то надо, чтобы утвердить, а вот рефакторига много, ибо вмешательство в интерфейс будет.
