### ISSUE TITLE
Не работает создание массива из фиксированного массив

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#844]
**Опишите ошибку**
Не работает создание массива из фиксированного массив

**Воспроизведение ошибки**
1. Запустить код 
```bsl
    ЗначениеМассив = Новый Массив();
	ЗначениеМассив.Добавить("Элемент1");
	ЗначениеМассив.Добавить("Элемент2");
	
	ФиксированныйМассив = Новый ФиксированныйМассив(ЗначениеМассив);
	ЗначениеМассив = Новый Массив(ФиксированныйМассив);
```
2. Подать на вход параметры ...
3. Увидеть ошибку `/ Ошибка в строке: 8 / Преобразование к типу 'Число' не поддерживается}`

**Ожидаемое поведение**
Должен был создаться массив из фиксированного массив

**Окружение**
 - ОС: OSX
 - Версия: Oscript 1.1.0

**Дополнительная информация**

**Comment by khorevaa** [comment]
Тоже самое из фиксированного соответствия в соответствие

**Comment by vasvl123** [comment]
Для структуры исправляли https://github.com/EvilBeaver/OneScript/issues/501

**Comment by EvilBeaver** [comment]
@artbear Фиксированные делал ты, если не ошибаюсь. Посмотришь?
