### ISSUE TITLE
Ошибки DataReader.ReadIntoBinaryDataBuffer() и MemoryStream.CloseAndGetBinaryData()

### ISSUE THREAD

**Issue by vasvl123** [EvilBeaver/OneScript#846]
**Опишите ошибку**
1. DataReader.ReadIntoBinaryDataBuffer() требует параметр хотя не должен.
2. DataReader.ReadIntoBinaryDataBuffer(Count) считывает все, а не указанный объем
3. MemoryStream.CloseAndGetBinaryData() создает двоичные данные неверного объема

**Воспроизведение ошибки**
1. Запустить код ...
```
BinaryData = GetBinaryDataFromString("123");

DataReader = New DataReader(BinaryData);

MemoryStream = New MemoryStream();

DataWriter = New DataWriter(MemoryStream);

Buffer = DataReader.ReadIntoBinaryDataBuffer(1);

Сообщить(Buffer.size);

DataWriter.WriteBinaryDataBuffer(Buffer);

BinaryData1 = MemoryStream.CloseAndGetBinaryData();

Сообщить(BinaryData1.size());
```

2. Подать на вход параметры ...
3. Увидеть ошибку

3
256

**Ожидаемое поведение**

1
1

**Окружение**
 - ОС: xubuntu 16.04
 - Версия: 1Script Execution Engine. Version 1.1.0.325

**Дополнительная информация**

**Comment by Mr-Rm** [comment]
По пунктам 1 и 2: некорректная реализация полиморфизма для функции `ReadIntoBinaryDataBuffer`

**Comment by EvilBeaver** [comment]
Спасибо! Классы обработки двоичных данных, на самом деле, плохо протестированы и там много что может идти не так. По сути - это бета-версии классов
