### ISSUE TITLE
Внешнее исключение (System.Net.WebException): Запрос был прерван: Не удалось создать защищенный канал SSL/TLS.

### ISSUE THREAD

**Issue by 1cgh** [EvilBeaver/OneScript#849]
При запросе через HTTPСоединение с использованием защищенного соединения получаем ошибку:
`Внешнее исключение (System.Net.WebException): Запрос был прерван: Не удалось создать защищенный канал SSL/TLS.`

При этом ошибка возникает на компьютерах с Win10 и не возникает на компьютерах с Win7.
Версия oscript везде одинаковая, 1.0.21.1
Сертификаты действительные.

Ошибка возникает при доступе к определенному серверу, а не при любой попытке защищенного соединения.

Сервис внутренний, за nginx, соединение установилось после смены настроек nxginx.
Было (возникала ошибка):
`ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:`
Стало (не возникает ошибка):
`ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4';`

Настройка nginx по протоколам:
`ssl_protocols TLSv1 TLSv1.1 TLSv1.2;`

**Comment by EvilBeaver** [comment]
Попробуйте на 1.1 Я повышал поддерживаемые версии TLS но не помню в какой из версий

**Comment by EvilBeaver** [comment]
По поводу опций nginx, тут @zeegin соображает, может он подскажет что

**Comment by zeegin** [comment]
@1cgh пробей сервер к которому не удается подключиться через сервис
https://www.ssllabs.com/ssltest/
и там посмотри че не так с их шифрсюитом.

Скорее всего у них `EC*` группа т.е. шифры на эллиптических кривых не включены, из-за этого приходится использовать старые шифры до 2000 года, т.к. для установки соединения выполняется хэндшейк который согласует поддерживаемые шифры клиента и сервера и выбирается самый надежных из доступных у обоих сторон. Если самым надежным выступает самый слабый - то это не очень хорошо. Скорее всего с тем конфигом с которым возникала ошибка получалось что шифрсюиты клиента и сервера вообще не пересекались. С другой стороны добавление слабых шифров типа `AES128-GCM-SHA256` ведет к возможности искусственного занижения защищенности соединения для всех других узлов. Если требуется делать такие занижения, то рекомендую делать их для конкретных узлов по белому списку, а не для всех.

**Comment by EvilBeaver** [comment]
@1cgh - пинг. Закрывать задачу?

**Comment by 1cgh** [comment]
> @1cgh - пинг. Закрывать задачу?

ага
