### ISSUE TITLE
Не работает преобразование ДвоичныеДанные в Строка

### ISSUE THREAD

**Issue by vbondarevsky** [EvilBeaver/OneScript#855]
**Опишите ошибку**
Не работает приведение двоичных данных к строке.
Выполнить код `ВРег(Base64Значение("MXRlc3Q="));`
Получим ошибку: `Ошибка в строке: 1 / Ожидается символ: EndOfText}    
                                     ВРег(Base64Значение("MXRlc3Q="));`

**Ожидаемое поведение**
Возвращает строку "31 74 65 73 74"

**Окружение**
 - ОС:  Windows 10 x64
 - Версия: 1.0.21.1

**Comment by Mr-Rm** [comment]
Если `ВРег(Base64Значение("MXRlc3Q="));` это весь код, то ошибка `EndOfText` появляется от вызова функции как процедуры.
`Сообщить(ВРег(Base64Значение("MXRlc3Q=")));` действительно падает на версии 1.0.21.1 с ошибкой `Внешнее исключение (System.IndexOutOfRangeException): Index was outside the bounds of the array.}`
Ошибка закрыта коммитом  [0555b5edbf873fcd029b104c3fe8ecd53e7cac59]

**Comment by EvilBeaver** [comment]
@vbondarevsky ВРег - это так называемая "встроенная функция". Ее и в 1С нельзя вызывать просто так, только в правой части выражения. Только в 1С будет другой текст ошибки.

**Comment by vbondarevsky** [comment]
> @vbondarevsky ВРег - это так называемая "встроенная функция". Ее и в 1С нельзя вызывать просто так, только в правой части выражения. Только в 1С будет другой текст ошибки.

Ну сделай `А = ВРег(Base64Значение("MXRlc3Q="));` так и будет тебе ошибка `Внешнее исключение (System.IndexOutOfRangeException): Индекс находился вне границ массива.}    
                                     А = ВРег(Base64Значение("MXRlc3Q="));`

**Comment by vbondarevsky** [comment]
В текущей ветке develop проблемы нет
