### ISSUE TITLE
В HTTPСоединение всегда используется принудительный редирект

### ISSUE THREAD

**Issue by vbondarevsky** [EvilBeaver/OneScript#856]
**Опишите ошибку**
HTTPСоединение всегда выполняет разрешение редиректа

**Воспроизведение ошибки**
```bsl
Соединение = Новый HTTPСоединение("http://httpbin.org");
Запрос = Новый HTTPЗапрос("/redirect-to?url=http%3A%2F%2Fhttpbin.org%2Fget&status_code=307");
Ответ = Соединение.Получить(Запрос);
Сообщить(Ответ.КодСостояния);
>> 200
```

**Ожидаемое поведение**
`Ответ.КодСостояния` = 307

- Это поведение отличается от платформы 1С
- Заголовки Set-Cookie из первого ответа просто будут проигнорированы

Свойство `HttpWebRequest.AllowAutoRedirect` нужно установить в `false`

**Окружение**
 - ОС:  Windows 10 x64
 - Версия:  1.0.21.1

**Comment by EvilBeaver** [comment]
Лучше в свойство вынести

**Comment by vbondarevsky** [comment]
> Лучше в свойство вынести

https://github.com/EvilBeaver/OneScript/pull/858
