### ISSUE TITLE
Новый ЗаписьДанных() падает при указании параметров далее 2-го

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#861]
**Опишите ошибку**
Конструктор `Новый ЗаписьДанных()` падает в рантайме при указании параметров далее 2-го.

**Воспроизведение ошибки**
-  `файл=Новый ЗаписьДанных(ИмяФайла, , ПорядокБайтов.LittleEndian);`
Внешнее исключение (System.InvalidCastException): Specified cast is not valid.
- `файл=Новый ЗаписьДанных(ИмяФайла, , , Символы.ПС );`
Внешнее исключение (System.InvalidCastException): Unable to cast object of type 'ScriptEngine.Machine.StringConstantValue' to type 'System.String'.
- `файл=Новый ЗаписьДанных(ИмяФайла, , , , Ложь );`
Внешнее исключение (System.InvalidCastException): Specified cast is not valid.
- `файл=Новый ЗаписьДанных(ИмяФайла, , , , , Символы.ПС );`
Внешнее исключение (System.NullReferenceException): Object reference not set to an instance of an object.
- `файл=Новый ЗаписьДанных(ИмяФайла, , , , , , Истина );`
Внешнее исключение (System.NullReferenceException): Object reference not set to an instance of an object.

**Ожидаемое поведение**
Должен создаваться новый объект.
В 1С все варианты работают правильно.

**Окружение**
 - ОС: Windows 7 x64
 - Версия: 1.0.21.1 и develop

**Comment by EvilBeaver** [comment]
+1 Объекты работы с дв. данными следует в целом считать незаконченными. Сам недавно натыкался на массу ошибок в них.

**Comment by Mr-Rm** [comment]
C конструктором понятно: следует типы всех параметров заменить на IValue и далее преобразовывать  в нужный тип (пример - ZipWriter).
Обнаружилось, что выбор конструктора может зависеть (и зависит в данном случае) от порядка следования функций, аннотированных как [ScriptConstructor] в исходном коде.

**Comment by EvilBeaver** [comment]
> Обнаружилось, что выбор конструктора может зависеть (и зависит в данном случае) от порядка следования функций, аннотированных как [ScriptConstructor] в исходном коде.

Ну да, он так и работает. Первый подходящий по количеству параметров конструктор вызывается.

**Comment by Mr-Rm** [comment]
Так все параметры, кроме первого, необязательные. Поэтому по записи  `Новый ЗаписьДанных(Параметр1);` до проверки типа `Параметр1` нельзя определить, какой конструктор вызывать.
Сейчас код `файл=Новый ЗаписьДанных("СтрокаСИменемФайла");` работает. Но стоит поменять в DataWriter.cs местами `Constructor(...)` и `ConstructorByStream(...),` и всё сломается.
Ещё один момент:  в `Новый ЗаписьДанных(Параметр1, , , , Параметр5);` при неизвестном типе `Параметр1` значение `Параметр5` - это булево `Дописать` или строка `КонвертируемыйРазделительСтрок`?
А `Новый ЗаписьДанных(Поток, , , , , , Параметр7);` вообще не должен бы работать, но в 1С работает.
Всё это справедливо и для некоторых других типов, например "ФайловыйПоток" и "Картинка".

**Comment by Mr-Rm** [comment]
Изменения в маршалинге не помогло полностью. `файл=Новый ЗаписьДанных(ИмяФайла, , , , , Символы.ПС );`, например, по-прежнему падает.
