### ISSUE TITLE
Не читается валидный json текст через `ПрочитатьJSON`

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#862]
**Опишите ошибку**
Не читается валидный json текст через `ПрочитатьJSON`

**Воспроизведение ошибки**
Шаги:
1. Прочитать текст через "ПрочитатьJSON"
2. Увидеть ошибку `Внешнее исключение (Newtonsoft.Json.JsonReaderException): Bad JSON escape sequence: \\U. Path \u0027ПараметрыПодключения.ФайловаяБаза.ПутьККаталогу\u0027, line 1, position 120.`

```json
{
  "Версия": "1.0",
  "Наименование": "Тестовая_База",
  "Код": "695",
  "ПараметрыПодключения": {
    "ФайловаяБаза": {
      "ПутьККаталогу": "C:\\Users\\Алексей\\AppData\\Local\\Temp\\k11ajrty.m0r.tmp"
    }
  },
  "ПараметрыОбновленияКонфигурации": {
    "update": {
      "file": {
        "path": "tests/fixtures/distr/1.1/1Cv8.cf",
        "hash": {
          "ХешСумма": "96962B7B3639CA91D8DEDF3A229A814B",
          "Функция": "md5"
        }
      }
    },
    "ЗагрузитьКонфигурацию": "Ложь",
    "ПредупрежденияКакОшибки": "Ложь",
    "ДинамическоеОбновление": "Ложь",
    "after": [
      {
        "epf": {
          "bindata": {
            "hash": {
              "sum": "9c5428610c867f564e0b0683a1e696eb",
              "Функция": "md5"
            },
            "ext": "epf"
          }
        }
      }
    ]
  }
}
```

**Ожидаемое поведение**
Прочитанные данные

**Окружение**
 - ОС: windows-10
 - Версия: 1.1.0.325

**Дополнительная информация**

**Comment by EvilBeaver** [comment]
В 1С сие читается разве? По-моему это невалидный json...

**Comment by khorevaa** [comment]
Читает.. и собственно и генерит его 1с

**Comment by khorevaa** [comment]
Корректность проверена `https://jsonformatter.curiousconcept.com/`

**Comment by khorevaa** [comment]
@EvilBeaver 

Проблема в строке [143](https://github.com/EvilBeaver/OneScript/blob/84df0280447950cc5953184545e71b8a71738cef/src/ScriptEngine.HostedScript/Library/Json/JSONWriter.cs#L143)

Одинарный `\`  не экранируется...

**Comment by EvilBeaver** [comment]
Как раз экранируется.  В С# конструкция "\\\\" означает одинарный слэш. И он экранируется двумя слэшами "\\\\\\\\" (2 раза по одинарному \\\\)

**Comment by khorevaa** [comment]
@EvilBeaver Так там при записи если в строке `\` он никак не экранируется в `\\`

**Comment by nixel2007** [comment]
Проблема ж не в записи, а в чтении

**Comment by Mr-Rm** [comment]
Не воспроизводится. 
```
ЧтениеJSON = Новый ЧтениеJSON;
ЧтениеJSON.ОткрытьФайл("C:\tmp\test1s.json","UTF-8");
// или ЧтениеJSON.УстановитьСтроку(текст);
данные=ПрочитатьJSON(ЧтениеJSON);
сообщить(данные.ПараметрыПодключения.ФайловаяБаза.ПутьККаталогу);
```
Вывод: `C:\Users\Алексей\AppData\Local\Temp\k11ajrty.m0r.tmp`
Проверено в Windows 10 x64, Windows 7 x32, ubuntu-18.04 для версий 1.0.21.1, 1.1.0.6 и текущего develop.
Но в Windows без указания кодировки файла падает с сообщением `Неверное значение аргумента`, т.к. по умолчанию выбирается не UTF-8, а системная cp1251.

**Comment by khorevaa** [comment]
@Mr-Rm Странно.

**Comment by khorevaa** [comment]
@Mr-Rm @EvilBeaver На  OSX читает все нормально - это магия какая-то
Я уже 2 дня бьюсь над проблемой!

**Comment by khorevaa** [comment]
@EvilBeaver @Mr-Rm  Пока закрою! Видимо это у меня руки - из опы
