### ISSUE TITLE
Не работает получение рефлексии по типу объекта но `ЭтотОбъект`

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#864]
**Опишите ошибку**
Не работает получение рефлексии по типу объекта

**Воспроизведение ошибки**

1. Запустить код ...

```bsl
ОбъектПроверки = ЭтотОбъект;
РефлекторПроверки = Новый Рефлектор;

ТаблицаМетодов = РефлекторПроверки.ПолучитьТаблицуМетодов(ОбъектПроверки);
ТаблицаСвойств = РефлекторПроверки.ПолучитьТаблицуСвойств(ТипЗнч(ОбъектПроверки));

Сообщить(ТипЗнч(ЭтотОбъект));

```
2. Увидеть ошибку 
```
{Модуль F:\github\github\AutoUpdateIB\test.os / Ошибка в строке: 47 / Неверное значение аргумента {Тип не может быть отражен.}}
```
**Ожидаемое поведение**
Работающий рефлектор. И полученная таблица свойств 
Для созданных классов через `новый` работает нормально 

**Окружение**
 - ОС: windows
 - Версия: 1.0.21.1

**Дополнительная информация**

**Comment by EvilBeaver** [comment]
Из описания я так и не понял: на какой строке кода из примера падает? Что такое "Работающий рефлектор"? какое конкретно ожидается правильное поведение?

**Comment by nixel2007** [comment]
@EvilBeaver вот минимально падающий пример:

```bsl
Рефлектор = Новый Рефлектор();
ТаблицаМетодов = Рефлектор.ПолучитьТаблицуМетодов(ТипЗнч(ЭтотОбъект));
```

```
test.os / Ошибка в строке: 2 / Неверное значение аргумента {Тип не может быть отражен.}}
```

**Comment by EvilBeaver** [comment]
А я же правильно понимаю, что вы рефлектите тип "Сценарий", который суть безымянный тип, созданный из ЗагрузитьСценарий(), да? Какое значение возвращает у вас ```Строка(ТипЗнч(ЭтотОбъект))```?

Просто если вы делаете ЗагрузитьСценарий() а потом от него Рефлектируете ТипЗнч(ЭтотОбъект), то исключение оправдано. Тип "Сценарий" - это анонимный тип общего назначения. У него нет ни свойств, ни методов, отражать нечего. Свойства и методы появляются только у конкретного экземпляра этого типа, но не у самого типа.

**Comment by nixel2007** [comment]
Это просто запуск скрипта из двух строчек через oscript.exe path/to/file.os

Я понимаю, что ты имеешь ввиду. В целом кажется, что исключение в данном случае - это не интуитивно. Интуитивно возвращать пустую таблицу. 

Но в линуксе возникает другая ошибка при работе с рефлектором, когда смогу её поймать в минимальном примере - скину отдельным ишузом. Ну или oscript tasks/test.os в энтити - все зелёное под виндой, почти все красное под линуксом

**Comment by nixel2007** [comment]
На подумать - а нельзя ли сценарии, загружаемые через загрузитьсценарий, регистрировать под синтетическим типом? Типа ИнформацияОСценарии_ГУИД?

**Comment by EvilBeaver** [comment]
А зойчем?

**Comment by nixel2007** [comment]
ну... типа, чтобы не было анонимных классов. с другой стороны всегда можно воспользоваться ПодключитьСценарий и указать там нужное имя типа. правда тогда нужен симметричный ПодключитьСценарийИзСтроки

**Comment by EvilBeaver** [comment]
> правда тогда нужен симметричный ПодключитьСценарийИзСтроки

Или второй параметр в ЗагрузитьСценарий* с именем типа. И получится, что Загрузить - это шорткат к Подключить+Новый... Однако, все равно СтартовыйСценарий() останется типом Сценарий...

Мне все равно не понятно, зачем нужно получать рефлексию от ТипЗнч(ЭтотОбъект)?? Почему не сделать просто рефлексию ЭтотОбъект?

**Comment by nixel2007** [comment]
@EvilBeaver тут смотри какая логика. На линуксе падает рефлектор из типа. Начинаешь делать минимально воспроизводимый сценарий - впарываешься на это. Думаешь, так, это тоже какая-то херня, пойду зарепорчу, вдруг это поможет решить изначальную проблему.

А получилось, что оно просто так бай дезигн. Не очевидно, но явно проблема в другом. Мы со своей стороны продолжим пока копать дпльше. А ты подумай над дезигном :)

**Comment by EvilBeaver** [comment]
А я не очень понял чего думать над дезигном. Тип("Сценарий") не имеет ни свойств ни методов. А 2 разных экземпляра типа "Сценарий" будут иметь разные таблицы свойств и методов после рефлексии. По мне - логично, что Тип("Сценарий") лучше не отражать совсем, ибо Рефлектор(Тип) и Рефлектор(ОбъектТипа) будут давать разные результаты, что странно.

**Comment by dmpas** [comment]
Я тут вклинюсь под закрытие. А Тип("Структура") какую таблицу свойств будет иметь?

**Comment by EvilBeaver** [comment]
Пустую. А таблицу методов - нет. Но это и так динамический тип, с ним можно понять. В принципе, я не против переделки, возвращающей пустые таблицы. Если это желаемое поведение - так тому и быть. Совместимость с 1С нас тут не угнетает :)
