### ISSUE TITLE
Отладчик

### ISSUE THREAD

**Issue by ViktorErmakov** [EvilBeaver/OneScript#865]
**После остановки по ошибке, при нажатии f10, не встает на следующую строку**
Уже не первый раз пытаюсь отлаживать свой код.
Ставлю точки останова, несколько.
Во первых срабатывает не на всех точках.
Во вторых, после срабатывания хочу шагнуть вперед на одну строку, но при нажатии f10 улетает до конца выполнения кода, либо до другой точки останова.

**Comment by EvilBeaver** [comment]
Версии движка и отладчика какие?

**Comment by ViktorErmakov** [comment]
Oscript 1.1.0.325
Версия отладки точно сказать не могу, но похоже 0.2.0
Это если смотреть в файлике json

**Comment by EvilBeaver** [comment]
@ViktorErmakov есть способ воспроизведения, пример кода, на котором не работает?

**Comment by ViktorErmakov** [comment]
Андрей приветствую, ох как давно это было))
боюсь что ишуз можно закрыть до следующего выявления, я с тех пор не прогал на оскрипте практически)
