### ISSUE TITLE
Передача переменных в команду -make

### ISSUE THREAD

**Issue by khorevaa** [EvilBeaver/OneScript#869]
# Описание задачи

При компиляции в приложение (-make) хочет иметь возможность устанавливать экспортные свойства объектов контекста

**Опишите решение**
Общий модуль `ПараметрыПриложения.os`
```bsl
Перем Версия Экспорт;
Перем ГитМетка Экспорт;
```

При компиляции с параметрами
```
oscript.exe -p Версия=1.0.0 -p ГитМетка=2f5875 -make ПараметрыПриложения.os ПараметрыПриложения.exe

```

При инициализации модуля в его экспортные свойства устанавливаются переданные значения, аналогично вызову
```bsl
ПараметрыПриложения.Версия=1.0.0;
ПараметрыПриложения.ГитМетка=2f5875;
```

**Дополнительная информация**

Использование в собранных приложениях ввиде .exe

**Comment by EvilBeaver** [comment]
Ну это в случае с однофайловым модулем. А в случае более крупного приложения? Мне честно непонятен сценарий применения. Установка версии? Может просто делать СтрЗаменить перед сборкой в нужных файлах?

**Comment by khorevaa** [comment]
@EvilBeaver Для начала хватит и в точку входа.. Сделать 
Но как вариант 

```bsl
oscript.exe -p ПараметрыПриложения.Версия=1.0.0 -p ПараметрыПриложения.ГитМетка=2f5875 -make Приложение.os Приложение.exe
```

СтрЗаменить - не подходит т.к. меняет файлы и при его сборке надо будет коммитить в git... 
Кратко уже пробовал....

Вообще мне очень нужная функциональность.

**Comment by EvilBeaver** [comment]
Мне архитектурно не нравится. Призываю обсудить @nixel2007 @dmpas
