### ISSUE TITLE
Знак и Логотип

### ISSUE THREAD

**Issue by LightmanHub** [EvilBeaver/OneScript#873]
пожалуйста, взгляните на этим макеты,
возможно, они вам понравятся.
в знаке я пытался сохранить преемственность от 1С, но так, чтобы это не было слишком выражено
reks.biz/heap/OneScript.logoSet.png
reks.biz/heap/OneScript.signSet.png

**Comment by EvilBeaver** [comment]
Спасибо за интерес к проекту! Сообщество, как я помню, обсудило эти варианты в Телеграме. Предлагаю этот issue использовать для накопления вариантов логотипов. Я приму любой лого, который понравится людям.

**Comment by LightmanHub** [comment]
Спасибо за ответ.

из "я приму любой лого, который понравится людям" можно сделать вывод, что
людям не понравилось?

мне было бы интересно услышать отзывы и аргументы, но я не нашел ссылок на
Телеграм, где они прозвучали.
если это имеет значение, и если вас не затруднит, вы могли бы уточнить, в
каком канале было обсуждение?

пн, 15 апр. 2019 г. в 12:40, Andrei Ovsiankin <notifications@github.com>:

**Comment by EvilBeaver** [comment]
Вот здесь, ниже по тексту https://web.telegram.org/#/im?tgaddr=tg:%2F%2Fresolve%3Fdomain%3Doscript_library%26post%3D5251
