### ISSUE TITLE
Сломан Debian пакет

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#874]
**Опишите ошибку**

- скачиваем deb пакет с ночника
- ставим его через dpkg -i
- пробуем вызвать opm
- получаем ошибку, что "не найдена библиотека ../core
- заходим в каталог opm/src/core
- видим, что вместо Классы и Модули папки называются кодировочными кракозябрами
- переименовываем папки
- opm работает

**Ожидаемое поведение**

После установки из deb система должна работать сразу

see #870

**Comment by EvilBeaver** [comment]
@nixel2007 @dmpas создал отдельный тикет на проблему с deb. Как известно, deb собирается докер-контейнером. Так вот, deb, созданный докером из-под винды создает корректный пакет, который затем без проблем ставится с помощью dpkg.

При этом, деб-пакет, создаваемый сервером сборок - битый. 

Задача: понять, почему докерконтейнер на разных хостах выдает разный результат.

**Comment by EvilBeaver** [comment]
Кажется, решено: Имена файлов портились в момент выполнения команды stash в jenkins-slave на винде. Внес параметр -Dfile.encoding=UTF-8 в настройки службы слэйва, вроде бы архив теперь честный.

@nixel2007 @dmpas просьба проверить.

**Comment by EvilBeaver** [comment]
Нуу @dmpas, ну @nixel2007 ну проверьте же! У меня все работает, но я ж так и зарелизю, а потом выяснятся нюансы!

**Comment by nixel2007** [comment]
Скачал, внутри деб пакет выглядит корректно. Постараюсь проверить на линукс-системе на днях.
