### ISSUE TITLE
СписокЗначений и ТаблицаЗначений: Сдвинуть() работает циклично

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#876]
**Опишите ошибку**
Для объектов `СписокЗначений` и `ТаблицаЗначений` метод `Сдвинуть` выполняет циклический сдвиг, если индекс новой позиции элемента выходит за пределы коллекции. Такое поведение зафиксировано и в тестах.
**Ожидаемое поведение**
1С в этих случаях выдаёт ошибку "Недопустимое значение параметра (параметр номер '2')" для СпикаЗначений и "Неправильное смещение внутри коллекции" для ТаблицыЗначений.

Следует ли сделать совместимо?

**Comment by EvilBeaver** [comment]
@dmpas подскажи, как автор - почему сделан циклический сдвиг? Есть ли тайный смысл в этом?

**Comment by dmpas** [comment]
@EvilBeaver вот я пытался поковыряться на ИТС и найти какой-нибудь старый синтаксис-помощник. Вот чует моя ж, что когда-то в 1С так и было.

**Comment by EvilBeaver** [comment]
Ща попросим какого-нибудь старожила вспомнить...

/cc @pumbaEO @artbear @allustin ?

**Comment by EvilBeaver** [comment]
Судя по-всему - нет. Оно всегда работало с выдачей исключения. Я не могу найти подтверждения, что было циклично

**Comment by dmpas** [comment]
Надо выпиливать, значит.

**Comment by ghost** [comment]
@EvilBeaver не было такого. Я помню 8.1 я пробовал и получал исходное исключение "Неправильное смещение внутри коллекции" а вот в 7.7 1С++ вроде как смещало циклично.

**Comment by Mr-Rm** [comment]
Когда первый параметр метода Сдвинуть() не является Числом или ЭлементомСпискаЗначений / СтрокойТаблицыЗначений соответственно, 1С пытается привести его к числу и выдает ошибку "_Несоответствие типов (параметр номер '1')_" только если приведение невозможно. В OneScript происходит следующее:
`СписокЗначений.Сдвинуть("2",1)`
Ошибка: _Значение не является значением объектного типа_
`ТаблицаЗначений.Сдвинуть("2",1)`
Ошибка: _Неверный тип аргумента_
(То же и для `СписокЗначений.Удалить("2")`)

Что важнее, совместимость или типизация?

**Comment by dmpas** [comment]
Совместимость.

**Comment by Mr-Rm** [comment]
Удивительная несогласованность в 1С. Пробуем код:
```
ТЗ1 = Новый ТаблицаЗначений;
ТЗ1.Колонки.Добавить("К1");
Ст11 = ТЗ2.Добавить();
Ст12 = ТЗ2.Добавить();
ТЗ2 = Новый ТаблицаЗначений;
ТЗ2.Колонки.Добавить("К1");
Ст2 = ТЗ2.Добавить();
ТЗ1.Сдвинуть(Ст2,1);
```
Получаем ошибку: "_Недопустимое значение параметра (параметр номер '1') (Строка не принадлежит коллекции)_".
Теперь аналогичное:
``` 
СЗ1 = Новый СписокЗначений;
Эл11 = СЗ1.Добавить("э11");
Эл12 = СЗ1.Добавить("э12");
СЗ2 = Новый СписокЗначений;
Эл2 = СЗ2.Добавить("э2");
СЗ1.Сдвинуть(Эл2, 1);
```
Просто **сдвигается 0-й элемент!** `СЗ1.Индекс(Эл2)` честно возвращает -1.
Это же баг и источник багов. Нельзя такое повторять. Есть другие мнения?

**Comment by EvilBeaver** [comment]
Кажется в коде примера ошибка: в строке 2 СЗ2 еще не определен
