### ISSUE TITLE
ошибка в конструкторе Структуры при лишних значениях

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#887]
**Опишите ошибку**
В при передаче в конструктор Структуры значений больше, чем указано полей, возникает ошибка.

**Воспроизведение ошибки**
`Структ = Новый Структура("Поле1,Поле2",1,2,3);`
_Ошибка в строке: 1 / Неверное значение аргумента_

**Ожидаемое поведение**
1С игнорирует лишние значения.

**Дополнительная информация**
То же для ФиксированнойСтруктуры

**Comment by EvilBeaver** [comment]
Вот те раз... Ругалась же, вот прям помню. Ложная память?

**Comment by Mr-Rm** [comment]
Проверил на самой старой 1С, что под рукой - 8.1.6.38 - отрабатывает молча.
_(не добавить ли метку issue про 1С-совместимость?)_

**Comment by Mr-Rm** [comment]
Эта ошибка уже отмечалась в #674, но то issue было закрыто по другой упомянутой там ошибке.

**Comment by EvilBeaver** [comment]
Ок, исправляем, приводим к 1С.
