### ISSUE TITLE
конструктор Структуры из Структуры

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#888]
**Опишите ошибку**
Конструктор Структуры из Структуры работает как логично, но несовместимо с 1С.

**Воспроизведение ошибки**
```
Ст1 = Новый Структура("Поле1,Поле2",1,2);
Ст2 = Новый Структура(Ст1);
```
Теперь
Ст2 = Структура { "Поле1" : 1, "Поле2" : 2 }

**Ожидаемое поведение**
В 1С
Ст2 = Структура { "Структура" : Неопределено } !

**Дополнительная информация**
В 1С **нет** конструктора Структуры из Структуры, поэтому для всех первых параметров типа, отличного от ФиксированнойСтруктуры, выполняется приведение к строке, и работает конструктор Структура(Ключи, Значения). В приведённом примере Ключи == Строка(Ст1) == "Структура", а значения не указаны.

Нужна ли здесь совместимость, или это недоработка 1С?

Поведение конструктора ФиксированнойСтруктуры более строго: первый параметр либо строка, либо Структура, на остальное - ошибка "Несоответствие типа". (OneScript здесь соответствует, но выдает неточное, хотя и более развернутое, сообщение об ошибке).
Ещё в 1С есть, а в OneScript отсутствует конструктор ФиксированнойСтруктуры по умолчанию, без параметров. Назначение его непонятно, т.к. с созданным объектом делать практически нечего. Но для совместимости можно добавить.

**Comment by EvilBeaver** [comment]
Думаю нужно привести к 1С Структуру из Структуры, т.к. иначе будет неожидаемое 1С-ником поведение. А вот конструктор по умолчанию ФиксСтруктуры можно не делать, ибо нафиг он - непонятно, скорее всего недоработка в 1С.

**Comment by Mr-Rm** [comment]
Вряд ли кто намеренно использовал такое поведение конструктора. Предлагаю сделать как у ФиксированнойСтруктуры, с проверкой типа. Разрешить `Структура(Строка)` и `Структура(ФиксированнаяСтруктура)`, а остальное - ошибка.

**Comment by EvilBeaver** [comment]
Да, я так и сказал же, не?

**Comment by Mr-Rm** [comment]
Нет, "нужно привести к 1С" - а в 1С для Структуры 1-й параметр  преобразуется в строку.

**Comment by EvilBeaver** [comment]
Вон чего... Ну да, так прозрачнее, безусловно. Преобразование Структуры к строке это просто сайд-эффект IValue.AsString() только внутри 1С

**Comment by Mr-Rm** [comment]
Да, до появления ФиксированнойСтруктуры в 1С **всё** приводилось к строке. Потом добавили Фиксированную, для неё сделали нормальный конструктор, а старую Структуру так и оставили. Видимо, побоялись сломать совместимость, хотя стоило бы.

**Comment by Mr-Rm** [comment]
Чтоб не заводить новый issue, добавлю здесь:
`ФСт = Новый ФиксированнаяСтруктура("Поле1,Поле2");`
Ошибка: _В качестве параметра для конструктора можно передавать только Структура или Ключи и Значения_
Причина та же, что в #861 - неправильный выбор из конструкторов с одинаковым числом параметров.
