### ISSUE TITLE
Структура.Удалить(): ошибка при с несуществующем или некорректном ключе

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#891]
**Опишите ошибку**
Метод `Структура.Удалить()` с несуществующим или некорректным ключом падает с ошибкой _Свойство объекта не обнаружено_

**Воспроизведение ошибки**
```
Структура = Новый Структура("Ключ1,Ключ2", "Значение1","Значение2");
Структура.Удалить("Ключ3");
```
Ошибка: _Свойство объекта не обнаружено (Ключ3)_
```
Структура = Новый Структура("Ключ1,Ключ2", "Значение1","Значение2");
Структура.Удалить("3йКлюч");
```
Ошибка: _Свойство объекта не обнаружено (3йКлюч)_

**Ожидаемое поведение**
1С в первом случае игнорирует неизвестный ключ и ничего не делает, а во втором падает с ошибкой "_Задано неправильное имя атрибута структуры_", т.е. сначала проверяет, что ключ - корректный идентификатор.

**Comment by EvilBeaver** [comment]
@Mr-Rm я хочу выпустить релиз. Можем надеяться на попадание этих фиксов в него в ближайшее время?

**Comment by Mr-Rm** [comment]
Да, готово. Ещё #876 надо исправить.

**Comment by EvilBeaver** [comment]
Спасибо! Это очень круто!
