### ISSUE TITLE
Запуск OneScript

### ISSUE THREAD

**Issue by DwellerNet** [EvilBeaver/OneScript#892]
При запуске D:\osweb\OneScript.WebHost.exe вместо запуска сервера приложений
выходит сообщение об ошибке;
Необработанное исключение: System.TypeInitializationException: Инициализатор типа "System.Diagnostics.DiagnosticSourceEventSource" выдал исключение. ---> System.MissingMethodException: Метод не найден: "Void System.Diagnostics.Tracing.EventSource..ctor(System.Diagnostics.Tracing.EventSourceSettings)".
   в System.Diagnostics.DiagnosticSourceEventSource..ctor()
   в System.Diagnostics.DiagnosticSourceEventSource..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Diagnostics.DiagnosticListener..ctor(String name)
   в Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices()
   в Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   в OneScript.WebHost.Program.Main(String[] args)

 - ОС: Win 7 ultimate, Servise pack 1

**Comment by EvilBeaver** [comment]
Где брали дистрибутив? Собирали сами из исходников?

**Comment by EvilBeaver** [comment]
Кстати, вот обсуждение и, возможно, решение https://forum.infostart.ru/forum9/topic186559/

**Comment by DwellerNet** [comment]
> Кстати, вот обсуждение и, возможно, решение https://forum.infostart.ru/forum9/topic186559/

Вот с помощью этого обсуждения и настраивал. А движок брал здесь, на гитхабе.

**Comment by EvilBeaver** [comment]
> А движок брал здесь, на гитхабе.

Из исходников? Из релизов? из какой ветки?

**Comment by DwellerNet** [comment]
https://github.com/EvilBeaver/OneScript.Web/releases/download/v0.1-alpha-1/osp-0.1-alpha-1.zip
Вот отсюда и брался. Ссылка была на инфорстарте

**Comment by EvilBeaver** [comment]
посмотрите более свежий релиз там же: https://github.com/EvilBeaver/OneScript.Web/releases
