### ISSUE TITLE
Функция HMAC(SecretKey, SomeString, Algoritm)

### ISSUE THREAD

**Issue by ghost** [EvilBeaver/OneScript#893]
# Описание задачи

Необходимо функция получения HMAC по секретному ключу

Примерно так

```
Функция HMAC(Знач СекретныйКлюч, Знач Строка, Знач Алгоритм) Экспорт
  ...магия...
КонецФункции
```

**Дополнительная информация**

Предназначается в том числе для обработки JWT ключей

**Comment by ghost** [comment]
Хотя можно выдрать и отсюда https://infostart.ru/public/591665/

**Comment by EvilBeaver** [comment]
Вот сюда пулреквест лучше: https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Hash/HashFunctionEnum.cs

**Comment by EvilBeaver** [comment]
Хотя, hmac это же не хеш-функция..

**Comment by khorevaa** [comment]
@allustin 

А чем это плохо? [crypto](https://github.com/khorevaa/crypto/blob/develop/src/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%A8%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5.os#L15)

**Comment by EvilBeaver** [comment]
@khorevaa это не плохо, это скорее то, что надо 👍
