### ISSUE TITLE
ЧтениеZipФайла и Кирилица

### ISSUE THREAD

**Issue by asosnoviy** [EvilBeaver/OneScript#895]
ЧтениеZipФайла Не распаковывает кирилические имена.

Если взять пакет с хаба и развернуть, то вместо кирилицы будет ?????.os

Свои архивы читает нормально, поломана совместимость.

**Comment by EvilBeaver** [comment]
Мы работаем над этим. Сорри фор инконвиниенс.

**Comment by asosnoviy** [comment]
https://github.com/EvilBeaver/OneScript/commit/08c143536f0f35b685c0be1542da470e780c8d07#diff-69479ef74f6e736b314a3c2c5fcb9b65R343
