### ISSUE TITLE
Рефлектор - установка свойств

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/OneScript#897]
К обсуждению - 

Может развить немного рефлектор? Сейчас он может работать только на получение свойств и методов и вызов методов.

 Как на счет установки свойств? В том числе приватных? 

В других языках (в частности в джаве), это позволяет проще реализовывать DI-паттерн, контейнеризацию и вообще добавляет магии аннотаций. 

Это может быть полезно в вебе, где через рефлексию можно было бы организовать и пробрасывать различные "сервисы" между компонентами и друг другу. Это бы помогло обойти часть ограничений entity, с одной стороны упростив начало работы с сущностью, с другой - расширив возможности, например, позволив работать с приватными полями.

**Comment by EvilBeaver** [comment]
Ок, у меня возражений особенно нет

**Comment by nixel2007** [comment]
@EvilBeaver а не особенно? :)

**Comment by EvilBeaver** [comment]
Не особенно - я не понял про приватные переменные, допускаю что это зачем-то надо

**Comment by nixel2007** [comment]
это из принципов инкапсуляции вытекает.

в spring, например, ты у контроллеров/сервисов на приватных полях вешаешь соответствующие аннотации (`@AutoWired`, например), а DI-контейнер их через рефлексию инжектит. 

Ты в своем контроллере можешь не хотеть делать явный сеттер, оставив только геттер, или вообще скрыть от других сервисов, что ты от чего-то там зависишь, убрав даже геттер и уменьшив неявную связанность между компонентами. Про зависимости таким образом знает только di-контейнер, который оркестрирует всеми компонентами.

**Comment by otymko** [comment]
@nixel2007 а это вообще законно? До приватных полей достукиваться?

**Comment by nixel2007** [comment]
@otymko джава считает, что для рефлектора - законно. Но использование рефлектора в бизнес-логике где-то помимо di-контейнеров или схожих задач по конфигурированию классов перед из "полезной работой" - это однозначно вопрос к программисту и так делать не надо. Не говоря уже о том, что такая работа рефлектора в джаве довольно медленная штука.

**Comment by otymko** [comment]
@nixel2007 Идея хорошая, главное чтобы было востребовано.
