### ISSUE TITLE
Неожиданное исключение при запуске процедуры через Execute()

### ISSUE THREAD

**Issue by tsukanov-as** [EvilBeaver/OneScript#903]
**Опишите ошибку**

Следующий код генерит исключение, которого не должно быть:
```bsl
Procedure Test42() Export
	Try
		Test42_(1);
	Except
		Message(ErrorDescription());
	EndTry;
EndProcedure

Function Test42_(x, y = False)
	x = "1";
	If x = "1" And Not y Then // <--  Внешнее исключение (System.NotImplementedException): Метод или операция не реализована.}
		Message("!");
	EndIf;
EndFunction

Execute("Test42()");
```

**Воспроизведение ошибки**

Вставить код в TestApp.exe и запустить.

**Ожидаемое поведение**

В 1С код отрабатывает и выводит "!"

**Окружение**
 - ОС: Win10 Corp
 - Версия: 1.1.1.42

**Дополнительная информация**

Поймано с помощью фреймворка run.bsl

**Comment by Mr-Rm** [comment]
Пример можно сократить до
```BSL
Function Test(x, y = False)
	If  Not y Then // <--  Внешнее исключение (System.NotImplementedException): Метод или операция не реализована.}
		Message("!");
	EndIf;
EndFunction

Execute("Test(1)");
```
Исключение в данном случае в операции `Not` из-за DataType(y) = NotAValidValue. Немного меняя код, можно получить *System.IndexOutOfRangeException* при вызове или даже `y` равным `x` после вызова.
Проблема - в передаче параметров процедуре внутри Execute()

**Comment by EvilBeaver** [comment]
Да, InvalidVal должен был быть заменен на null, но это где-то потерялось в процессе вызова..

**Comment by Mr-Rm** [comment]
null не потерялось, а изменилось в коммите [9e82cea](https://github.com/EvilBeaver/OneScript/commit/9e82cea61516db42db17d64bf7439524f39d4fc5). 
Это тоже надо исправить, но там скрыта более глубокая ошибка:
```BSL
Function Test(x, y = False)
	If  Not y Then
		Message("!");
	else
		Message("???");
	EndIf;
EndFunction
Execute("Test(1,)");
```
Получаем *???*
```BSL
Function DontCare( x = "something" )
EndFunction

Function Test(x, y = False)
EndFunction
Execute("Test(1,)");
```
Получаем *Внешнее исключение (System.IndexOutOfRangeException): Index was outside the bounds of the array.*
Причина - в компиляторе. При трансляции кода, переданного в в Execute(), создаётся локальная для этого контекста таблица констант. А значения по умолчанию для функций модуля берутся из таблицы констант этого модуля. Отсюда несоответствие индексов. В первом случае IndexOf( False )=0, Execute.constants[0]=1 -> y=1, а во втором IndexOf( False )=1, Execute.constants[1] - нет такой.
Есть подозрение, что подобное можно сделать с `AttachScript()` но пока не получилось.

**Comment by EvilBeaver** [comment]
Эту я закрыл, а OutOfRange - это другая ошибка. Создам рядом #904
