### ISSUE TITLE
Не работает передача параметров по значению в Выполнить()

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#907]
**Опишите ошибку**
Не работает передача параметров по значению в функции `Выполнить()`

**Воспроизведение ошибки**
```bsl
Процедура Тест44( знач п )
	п=п*10;
КонецПроцедуры
ч=1;
Тест44(ч);
сообщить("ч="+ч);
Выполнить("Тест44(ч)");
сообщить("ч="+ч);
```
_ч=1_
_ч=10_

**Ожидаемое поведение**
_ч=1_
_ч=1_

**Дополнительная информация**
Ошибка была обнаружена при попытке рефакторинга по мотивам обсуждения https://github.com/EvilBeaver/OneScript/commit/31ed7061bea199479c053f5038d8682f2c5b5807
Где и как исправлять - понятно.
@EvilBeaver Сделать PR для фикса, или подождёт более значительных изменений?

**Comment by EvilBeaver** [comment]
Давай сделаем фикс. Я пока не планировал более значительных изменений (опасаюсь)

**Comment by Mr-Rm** [comment]
> Я пока не планировал более значительных изменений (опасаюсь)

Вполне поддаётся рефакторингу. MachineInstance.cs сократился строк на 70.

**Comment by EvilBeaver** [comment]
Сократился? Где посмотреть?

**Comment by Mr-Rm** [comment]
https://github.com/Mr-Rm/OneScript/tree/wip/machine

**Comment by EvilBeaver** [comment]
Супер! Спасибо!

**Comment by Mr-Rm** [comment]
Это ещё не закончено!

**Comment by EvilBeaver** [comment]
Все равно, я понял идею, это то что надо
