### ISSUE TITLE
При добавлении в ВК глобального контекста, ломается работа движка

### ISSUE THREAD

**Issue by dvakor** [EvilBeaver/OneScript#911]
**Опишите ошибку**
В ВК добавляется глобальный контекст
При подключении ВК через процедуру ПриЗагрузкеБиблиотеки в paclage-loader.os, начинаются проблемы с дальнешей работой движка.

1) Либа с компонентой не подключается, если она не указана последней
Например:

> #Использовать "./lib/ФоновыеЗадания"
> #Использовать 1connector

Падает с ошибкой 

Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index

Гдето в SetFrame

2) Если же либа указана последней, то она загружается, но при попытке вызова метода из main.os падает с NPE

Например кода main.os

> #Использовать 1connector
> #Использовать "./lib/ФоновыеЗадания"
> 
> 
> Функция ТестовыйМетодМодуля()
> 
> КонецФункции
> 
> а = ТестовыйМетодМодуля();

**Воспроизведение ошибки**

Пример кода глобального контекста

`   public class BackgroundJobsManagerGlobals : GlobalContextBase<BackgroundJobsManagerGlobals>`
  `  {`

        [ContextMethod("Test")]
        public IValue Test()
        {
            return ValueFactory.Create("123");
        }

        [ContextProperty("Test")]
        public IValue Test2 { get => ValueFactory.Create(1); }

        public static IAttachableContext CreateInstance()
        {
            return new BackgroundJobsManagerGlobals();
        }
`}`

**Ожидаемое поведение**
Все должно было работать :)

 - ОС: Windows Server 2016
 - Версия: 1.1.1.44 (с версией из гита тоже самое)

**Comment by EvilBeaver** [comment]
Эта issue уже где-то была, но найти, чтобы прикрепить сюда - не получилось. Принято, баг известен.

**Comment by EvilBeaver** [comment]
По-моему вот это: #804

**Comment by alexkmbk** [comment]
можно еще вот это присовокупить -   #344 

Похоже что оттуда же ноги растут.
