### ISSUE TITLE
Некоторые объекты созданные через CLREnumValueWrapper<T> не приводятся к строке

### ISSUE THREAD

**Issue by dvakor** [EvilBeaver/OneScript#918]
**Опишите ошибку**
При попытке привести CLREnumValueWrapper<T> к строке (AsString()) вылетает NRE.
так же не падает свойство SystemType

**Воспроизведение ошибки**

Пример кода:

```
ТЗ = Новый ТаблицаЗначений();
ТЗ.Колонки.Добавить("Тест");
Квалификатор = ТЗ.Колонки[0].ТипЗначения.КвалификаторыЧисла;
Сообщить(Тест.ДопустимыйЗнак);
```

**Ожидаемое поведение**
Враппер должен всегда корректно приводится к строке

**Окружение**
 - ОС:  Win. Server 2016
 - Версия: Последняя с develop

**Comment by EvilBeaver** [comment]
Хм, бида-бида. надо чтобы приводился
