### ISSUE TITLE
Ошибка работы OPM

### ISSUE THREAD

**Issue by thedemoncat** [EvilBeaver/OneScript#920]
**Опишите ошибку**
Ошибка замечена у пользователей Ubuntu

После установки oscript выпадает ошибка:
logos
![изображение](https://user-images.githubusercontent.com/26283990/64937387-e79e5080-d87b-11e9-8402-d971692dd9a5.png)

Если исправить/закоментировать сточку, то ошибка другая

logos
![изображение](https://user-images.githubusercontent.com/26283990/64937423-04d31f00-d87c-11e9-8f29-75b1e73b4547.png)

**Comment by thedemoncat** [comment]
Краткое расследование по поводу ошибки с OPM:
Вот [Этой](https://github.com/oscript-library/opm/blob/f279717b5bf323439aee02f28cbfb5c196c412e1/src/core/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D1%8BOpm.os#L20) переменной присваивается значение нормально

а вот [тут](https://github.com/oscript-library/opm/blob/f279717b5bf323439aee02f28cbfb5c196c412e1/src/core/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8Opm.os#L122) КонстантыOpm.СерверУдаленногоХранилища - пустое значение

Сообщить(Строка("КонстантыOpm")) падает с ошибкой System.NullReferenceException
Если поставить такой код:

![изображение](https://user-images.githubusercontent.com/26283990/64937543-790dc280-d87c-11e9-9b4e-fa99f948de92.png)
![изображение](https://user-images.githubusercontent.com/26283990/64937550-7dd27680-d87c-11e9-8958-350a7f2226a9.png)

а если так:

![изображение](https://user-images.githubusercontent.com/26283990/64937565-86c34800-d87c-11e9-862c-1742f9b0d88f.png)

![изображение](https://user-images.githubusercontent.com/26283990/64937570-8a56cf00-d87c-11e9-9051-895dbcc8dbd5.png)

Ему прям явно не нравится этот модуль. я уже пробовал заменить (удалил, создал новый, скопировал код), сменил кодировку на UTF-8 - все бесполезно(

**Comment by ghost** [comment]
Вопрос остается открытым - как ставился OScripе из какого DEB и какая версия

**Comment by thedemoncat** [comment]
@allustin поправил шапку

**Comment by EvilBeaver** [comment]
@TheDemonCat я ничего не понялъ. Дай, плиз для тупых инструкцию по шагам: Взять убунту, поставить односкрипт, дальше?

Я не привередничаю, просто катастрофически мало времени свободного, а тратить его на расследование уже расследованного я не хочу. Готов подключиться к расследованию с середины пути, но меня до этой середины надо провести за ручку. Надеюсь на понимание

**Comment by ghost** [comment]
@TheDemonCat опять же подвержу слова @EvilBeaver - как воспроизвести то эту фигню. Явно где-то и что мы не учитываем в движке (возможно) или в установке. Но как воспроизвести то.

**Comment by offnegative** [comment]
Тестировал на 16.04.6 LTS
С oscript разных версий, деб-пакеты: onescript-engine_1.0.21_all.deb  onescript-engine_1.1.1_all.deb onescript-engine_1.2.0_all.deb
Т.е путь воспроизведения выглядит так: 1) Взять Ubuntu 16.04.6 LTS 2) установить любой из деб-пакетов onescript-engine_1.0.21_all.deb  onescript-engine_1.1.1_all.deb onescript-engine_1.2.0_all.deb + зависимости 3) ввести opm list или opm install -f vanessa-porter-1.0.2.ospx 4) получить ошибку

**Comment by EvilBeaver** [comment]
@offnegative 

1. взял убунту 18.04 (16-й под рукой не было)
2. Поставил с сайта deb версии 1.0.21
3. opm list работает,  файл пакета vanessa-porter у меня отсутствует\

Итого: условий вопроизведения недостаточно.

**Comment by ghost** [comment]
@TheDemonCat посмотри воспроизведение ошибки точно. Удалив все перед этим. Сам лично ;-).

**Comment by EvilBeaver** [comment]
@TheDemonCat есть новости?

**Comment by ghost** [comment]
@EvilBeaver - закрывай. Переоткроем когда будет точное воспроизведение.

**Comment by thedemoncat** [comment]
@EvilBeaver у меня уже не удалось повторить(
