### ISSUE TITLE
В RPM-пакете нет исполняемого скрипта для OPM

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/OneScript#922]
**Опишите ошибку**
В пакете установки из -коробки нет скрипта opm

**Воспроизведение ошибки**
1. Скачиваем rpm-пакет с сайта
2. Устанавливаем
3. вводим команду `opm`
4. видим, что такой команды нет

**Ожидаемое поведение**
Ожидается, что установщик добавит ссылку на скрипт запуска opm в `/usr/bin/`

**Окружение**
 - ОС: RPM-based linux (CentOS)
 - Версия:

**Comment by EvilBeaver** [comment]
Хотеть. @dmpas any chances?

**Comment by dmpas** [comment]
попробую пнуть нашего новоиспечённого админа.
