### ISSUE TITLE
Не отрабатывает Попытка/Исключение в скомпилированном скрипте

### ISSUE THREAD

**Issue by maximkin7** [EvilBeaver/OneScript#925]
При компиляции скрипта в exe файл, при вызове исключения, не происходит его обработка в блоке Исключение ... КонецПопытки.

Воспроизведение ошибки:
Имеем следующий код (test.os).
```Сообщить("Начали выполнение.");
Попытка
	Сообщить("Зашли в попытку и вызываем исключение.");
	ВызватьИсключение "SomeError";
Исключение
	Сообщить("Обрабатываем исключение.");
КонецПопытки;
Сообщить("Работаем, после попытки.");
```

1. oscript.exe -make c:\test\test.os c:\test\test.exe
2. запускам test.exe
3. получаем вывод:
  Начали выполнение.
  Зашли в попытку и вызываем исключение.
  Ссылка на объект не указывает на экземпляр объекта.

Ожидаю увидеть:
  Начали выполнение.
  Зашли в попытку и вызываем исключение.
  Обрабатываем исключение.
  Работаем, после попытки.

При выполнение скрипта oscript.exe test.os, получаю ожидаемый вывод.

oc: Win7 Prof 
oscript: 1.1.1.44

**Comment by EvilBeaver** [comment]
Принято, спасибо

**Comment by Mr-Rm** [comment]
Ошибка тут:
https://github.com/EvilBeaver/OneScript/blob/f7be4cf8157fe6d95223b58935d3115c2042c552/src/ScriptEngine/Machine/MachineInstance.cs#L2442
Быстрое и краткое исправление:
```cs
Source = module.ModuleInfo?.Origin,
``` 
Или немного предусмотрительней:
```cs
Source = module.ModuleInfo!=null?  module.ModuleInfo.Origin :"<имя модуля недоступно>",
```
Либо надо заполнять ModuleInfo в `StandaloneRunner.StandaloneProcess.Run()`

**Comment by EvilBeaver** [comment]
вот это надо: "заполнять ModuleInfo в StandaloneRunner.StandaloneProcess.Run()"

Причем, емнип, я это уже исправлял давно. но видимо отвалилось

**Comment by maximkin7** [comment]
@EvilBeaver отравил pr
