### ISSUE TITLE
Отсутствует конструктор ЧтениеТекста на основании потока

### ISSUE THREAD

**Issue by dvakor** [EvilBeaver/OneScript#930]
**Опишите ошибку**
Объект "ЧтениеТекста" в 1С умеет читать текст из потока, в ОСкрипте такая возможность отсутствует.

Это же касается метода "Открыть"

**Воспроизведение ошибки**

Следующий код не работает

    `  
        ПотокВПамяти = Новый ПотокВПамяти;
	
	Запись = Новый ЗаписьДанных(ПотокВПамяти, Кодировка);
	Запись.Записать(ДвоичныеДанные);
	Запись.Закрыть();
	
	ПотокВПамяти.Перейти(0, ПозицияВПотоке.Начало);

        Чтение = Новый ЧтениеТекста(Поток, Кодировка);  << тут начинает искать файл с именем "Поток", а не инициализировать из ДД      
        Результат = Чтение.Прочитать();
        Чтение.Закрыть();
	Поток.Закрыть();

`

**Ожидаемое поведение**
У объекта ЧтениеТекста текста должен существовать конструктор на основании потока

**Окружение**
 - ОС: WinSrv 2016
 - Версия: последняя из дев ветки

**Comment by EvilBeaver** [comment]
@ArchLord42RU позакрывай плиз задачи, по которым твои PR влиты. На будущее, в коммит пулреквеста можно добавить closes #номерIssue и тогда при вливании PR задача будет закрываться сама.
