### ISSUE TITLE
При попытке добавить в вотчер функцию из модуля вылетает NRE

### ISSUE THREAD

**Issue by dvakor** [EvilBeaver/OneScript#932]
**Опишите ошибку**
При добавлении в вотчер вызов функции из модуля, в окне вотчера видна ошибка NRE

**Воспроизведение ошибки**
Создать модуль, встать на отладку, в вотчере вызвать экспортную функцию этого модуля
![image](https://user-images.githubusercontent.com/4038422/65669889-855d0100-e06e-11e9-8fb2-92115e5688b5.png)

**Ожидаемое поведение**
Функция должна выполняться и отдавать результат

**Окружение**
 - ОС: WinSrv 2016
 - Версия: Последняя из дева

**Comment by dvakor** [comment]
#924 эту ошибку не закрывает

**Comment by EvilBeaver** [comment]
Попробуем напрячься и включить это в 1.2?

**Comment by dvakor** [comment]
> Попробуем напрячься и включить это в 1.2?

без проблем)

**Comment by dvakor** [comment]
Хех, щас не NRE вылетает, а out of range excp, вылетает тута

![image](https://user-images.githubusercontent.com/4038422/66620735-cd059000-ec0b-11e9-8c30-6c6f1025d04e.png)
 
upd: проблема в том, выполнение начинается в инстансе полученном из GetMachine(threadId), а потом идет обращение к MachineInstance.Current , который не равен GetMachine(threadId)
