### ISSUE TITLE
ХешированиеДанных не закрывает поток к файлу

### ISSUE THREAD

**Issue by dvakor** [EvilBeaver/OneScript#933]
**Опишите ошибку**
При использовании объекта ХешированиеДанных и использовании его метода "ДобавитьФайл", после вычисления хеш суммы, доступ к объекту не возможен по причине того, что он занят другим процессом

Случай не синтетический, например при работе с протоколом Amazon S3 нужно высчитать MD5 \ SHA256 хеши файла

В 1С в целом хеш пересчитывается в момент добавления строки \ ДД \ файла, а в оскрипте в момент высчета хеш суммы.

**Воспроизведение ошибки**

Пример кода:

```
врФайл = "Какой-то файл";

Хеширование = Новый ХешированиеДанных(ХешФункция["MD5"]);
Хеширование.ДобавитьФайл(врФайл); 
Хеш = Хеширование.ХешСумма;

Хеширование2 = Новый ХешированиеДанных(ХешФункция["MD5"]);
Хеширование2.ДобавитьФайл(врФайл); //<<Падает тут
Хеш2 = Хеширование2.ХешСумма;

Сообщить(Хеш);
Сообщить(Хеш2);
```

**Ожидаемое поведение**
В 1С такой код выполняется корректно.

**Окружение**
 - ОС: WinSrv 2016
 - Версия: Последняя из дев

**Comment by dmpas** [comment]
Напомню, что уже натыкались: https://github.com/EvilBeaver/OneScript/issues/528

**Comment by dvakor** [comment]
@EvilBeaver в прошлый раз я вижу ты закрыл ишуз, но подошёл не с той стороны к проблеме :)
С диспозом то вроде ок, тут дело другое довитьфайл не должен монопольный стрим на файл открывать и все. 
И ещё вопрос в том, что в 1с хеш считается в момент добавления данных в объект хеширования, а у нас в момент получения хеша, от сюда может быть разность поведения, так вот будем это править или нет? Имхо можно забить т.к. не критично.

**Comment by EvilBeaver** [comment]
> в 1с хеш считается в момент добавления данных в объект хеширования, а у нас в момент получения хеша

Ну если я правильно понимаю, хеш считается от всех файлов, как от одного. Значит неважно в какой момент он считается, все файлы в момент подсчета будут открываться и считываться. Не держать открытым файл до момента подсчета - правильно. И закрывать после подсчета - тоже правильно. Считать хеш после добавления каждого файла, как делает 1С - хз есть ли в этом смысл?

Ну и все равно непонятно, почему после Dispose потоков внутри Хеширования они все равно не отпускаются?

**Comment by dvakor** [comment]
ОсободитьОбъект(ххх) вроде как отрабатывало верно. Просто пока сборщик (без осободитьОбъект) сам доходил до этого уже нужен был доступ к файлу.
