### ISSUE TITLE
Mono 6.4 виснет при попытке создать КОМ-объект по имени типа CLR

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#936]
## Награда за решение

https://www.bountysource.com/issues/81143574-mono-6-4-clr

**Тест создания CLR объекта конструктором COMОбъект**

```
Процедура ТестДолжен_ПроверитьСозданиеClrОбъекта() Экспорт

  РоднойОбъект = Новый COMОбъект("System.Random");
  РоднойОбъект.Next();
  РоднойОбъект.Next(10);
  РоднойОбъект.Next(10, 20);
  РоднойОбъект.NextDouble();

КонецПроцедуры
```
При выполнении под моно 6.4 в убунту - зависает.

**Ожидаемое поведение**
Не зависает

**Окружение**
 - ОС: Ubuntu 18.04
 - Версия: 1.1.1, 1.2.0
 - Mono 6.4.0.198

**Comment by EvilBeaver** [comment]
по теме #529  #573

**Comment by Infactum** [comment]
https://github.com/mono/mono/issues/17563  
Пишут, что проблема на более новых версиях отсутствует. Так что либо внедряем проверку на mono runtime, либо просто закрыть ишуз и в доках отметить, что на 6.4 не работает.

**Comment by EvilBeaver** [comment]
@Infactum нажми кнопочку Solve Issue на bountysource (ссылка вверху)

**Comment by Infactum** [comment]
Так вроде уж пару дней как нажал..

**Comment by EvilBeaver** [comment]
Хм... интересно, а как я должен это подтверждать тогда.. мне ничо не пришло никуда... Пойду FAQ почитаю
