### ISSUE TITLE
Не работает собранный в exe скрипт, при указании библиотеки

### ISSUE THREAD

**Issue by maximkin7** [EvilBeaver/OneScript#938]
Не работает собранный exe, при указании библиотеки.

Скрипт test.os
```
#Использовать irac
Сообщить("go");
```

1. выполнить oscript.exe -make  test.os test.exe
2. выполнить test.exe
3. Ошибка: {Модуль <имя модуля недоступно> / Ошибка в строке: 208 / Внешнее исключение (System.ArgumentOutOfRangeException): Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.Имя параметра: index}

Ожидаемое поведение
Вывести go
Окружение
 - Win7Prof: 
 -  oscript 1.2.0 сборка от  02.10.2019:

**Comment by maximkin7** [comment]
Если сделать так:
```
#Использовать cli
#Использовать irac
```
то работает.

**Comment by Mr-Rm** [comment]
Не воспроизводится, но и не работает. В обоих вариантах ошибка
_{Модуль <имя модуля недоступно> / Ошибка в строке: 31 / Значение не является значением объектного типа}_
oscript 1.2.0 сборка от 02.10.2019
Win7 x32, Win10 x64, Ubuntu 18.04 x64

**Comment by khorevaa** [comment]
Проблема известна... Она звучик так... при компиляции в exe не должно быть много модулей, только классы. Тогда все в exe компилится нормально

**Comment by Mr-Rm** [comment]
_Ошибка в строке: 31_ это в файле c:\Program Files\OneScript\lib\irac\src\Модули\Служебный.os:
```bsl
Чтение.ОткрытьФайл(СтрШаблон("%1/../Макеты/%2.json", ТекущийСценарий().Каталог, ИмяМакета),КодировкаТекста.UTF8);
```
Падает `ТекущийСценарий().Каталог`, т.к. ТекущийСценарий()==Неопределено для скомпилированных модулей, подключенных через `#Использовать` (в MachineInstance.ModuleInfo() currentScript == null).
Как исправлять непонятно: скомпилированный скрипт может запускаться там, где каталог библиотек отсутствует, а подмена на каталог исполняемого файла сломает конструкции с относительными путями, подобные приведённой выше.

Вариант - предусмотреть такую ситуацию в библиотеках : 
```bsl
Если ТекущийСценарий()<>Неопределено Тогда
 // относительно ТекущийСценарий().Каталог
Иначе
 // относительно КаталогПрограммы()
КонецЕсли
```

**Comment by asosnoviy** [comment]
@arkuznetsov

**Comment by arkuznetsov** [comment]
@asosnoviy Тут вообще вопрос, как сейчас правильно с макетами работать. Они в случае компиляции куда-то "вкомпиливаются" или остаются также в папке лежать?

**Comment by khorevaa** [comment]
В гитсинк я делал функцию
```bsl
Функция ЭтоСборкаEXE() Экспорт
	
	Если ЭтоПриложениеEXE = Неопределено Тогда
		ЭтоПриложениеEXE = ВРег(Прав(ТекущийСценарий().Источник, 3)) = "EXE";
	КонецЕсли;

	Возврат ЭтоПриложениеEXE;

КонецФункции
```

**Comment by EvilBeaver** [comment]
Идея для препроцессора, символ #Если КонсольноеПриложение

**Comment by EvilBeaver** [comment]
@arkuznetsov вкомпиливаются. Доставать надо через ПолучитьМакет

**Comment by arkuznetsov** [comment]
@EvilBeaver Спасибо, получилось. Но отвалилось в oscript.web, ругается, что ничего не знает про ДобавитьМакет (в package-loader.os)!

**Comment by arkuznetsov** [comment]
@maximkin7 Попробуйте на последней версии 0.11.1.

**Comment by maximkin7** [comment]
> @maximkin7 Попробуйте на последней версии 0.11.1.
На в том же окружении выдается ошибка: 
{Модуль <имя модуля недоступно> / Ошибка в строке: 356 / Значение не является значением объектного типа}

**Comment by maximkin7** [comment]
https://github.com/arkuznetsov
В том же окружении выдается ошибка:
{Модуль <имя модуля недоступно> / Ошибка в строке: 356 / Значение не является значением объектного типа}

**Comment by EvilBeaver** [comment]
see #939

**Comment by maximkin7** [comment]
ошибка в версии 0.11.1 {Модуль oscript://Служебный.os / Ошибка в строке: 39 / Не удалось найти часть пути "E:\OneScript\Макеты\Перечисления.json".}

**Comment by EvilBeaver** [comment]
Да, это в процессе исправления

**Comment by EvilBeaver** [comment]
@arkuznetsov что там написано в строке 39 модуля Служебный? Там обращение к файлу а не к макету?

**Comment by arkuznetsov** [comment]
@EvilBeaver Там написано:
``` bsl
	Если ЭтоСборкаEXE() Тогда
	    КаталогЗапуска = КаталогПрограммы();
	Иначе
	    КаталогЗапуска = ТекущийСценарий().Каталог;
	КонецЕсли;

	Чтение = Новый ЧтениеJSON();
	
	Чтение.ОткрытьФайл(СтрШаблон("%1/../Макеты/%2.json", КаталогЗапуска, ИмяМакета),
	                   КодировкаТекста.UTF8);

```
Я не стал делать макеты т.к. oscript.web не умеет в макеты (или я не понял, что не так). При компиляции в EXE в "ТекущийСценарий() = Неопределено", где можно найти каталог расположения EXE?

**Comment by EvilBeaver** [comment]
Я закоммитил свежие правки по макетам в ос.веб, но дженкинс так и не собрал это все

**Comment by arkuznetsov** [comment]
@maximkin7 Попробуй версию 0.12.0, перевел на механизм макетов.

**Comment by maximkin7** [comment]
@arkuznetsov 
Использовал ночную сборку от 29.10.2019г.
{Модуль oscript://Служебный.os / Ошибка в строке: 364 / Внешнее исключение (System.ArgumentOutOfRangeException): Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index}

**Comment by arkuznetsov** [comment]
@maximkin7 Какая версия irac? В версии 0.12.0 в указанной строке не вижу кода способного вызвать такую ошибку.
Опиши порядок действий, приводящих к ошибке (еще лучше пример скрипта), я попробую у себя воспроизвести.

**Comment by Mr-Rm** [comment]
При компиляции в exe скрипта, подключающего через `#Использовать` библиотеку, содержашую модуль, **в котором, в свою очередь используется модуль другой библиотеки**, в сборку попадают только модули из библиотеки самого первого уровня.
Исключение _System.ArgumentOutOfRangeException_ - из-за обращения ко  вложенному модулю (в данном случае Логирование), индекс которого выходит за пределы списка загруженных контекстов.

**Comment by EvilBeaver** [comment]
>  в сборку попадают только модули из библиотеки самого первого уровня

Эвона как... Странно, они же в плоский список грузятся... Это точно?

**Comment by maximkin7** [comment]
@arkuznetsov 
irac 0.12.0
'#Использовать irac
Сообщить("go");'
oscript -make test.os test.exe 
затем запускаю test.exe

**Comment by maximkin7** [comment]
@arkuznetsov 
если первой строкой сделать `#Использовать logos!@`,  то все работает. Mr-Rm прав получается.

**Comment by arkuznetsov** [comment]
@maximkin7 Это видимо уже вопрос к движку, ждем что скажет @EvilBeaver.

**Comment by EvilBeaver** [comment]
Ну раз @Mr-Rm говорит, что есть ошибка, значит она есть. Предлагаю не компилировать в exe ничего. Этот режим поддерживается по остаточному принципу, к сожалению...

**Comment by Mr-Rm** [comment]
@EvilBeaver
> Эвона как... Странно, они же в плоский список грузятся... Это точно?

Да, надо уточнить. 
В exe действительно записываются все модули, **последовательно**. И при старте из exe загружаются и **инициализируются** они  тоже последовательно. А при компиляции создаются модули в порядке появления, а инициализируются в обратном, по вложенности.
Из примера, для скрипта test.os:  `test` (создан модуль №0) -> `irac` (создан №1) -> { `logos` (создан №2), нет вложений, инициализируется; ...<другие модули> } инициализируется `irac` (здесь `logos` доступен как №2), запуск `test`, ок, "go".
Для test.exe: загружается `test`,  загружается `irac`, сразу инициализируется обращаясь к `logos`, а того ещё нет!
Обратный порядок загрузки из списка не поможет, т.к. номера(индексы) модулей уже заданы при компиляции. Разделять при загрузке создание объектов и вызов кода инициализации? Учитывать уровень вложенности?

А если при инициализации модулей нет обращения к функциям вложенных, то всё может работать.

**Comment by EvilBeaver** [comment]
Да, это косяк создания объекта модуля и то, что инициализация выполняется всегда, а не тогда, когда все уже загружено... Там сложно настроить все, как надо...

**Comment by EvilBeaver** [comment]
@maximkin7 @arkuznetsov - просьба проверить на ночнике от 31.01.20

**Comment by arkuznetsov** [comment]
@EvilBeaver Что-то пошло не так (1Script Execution Engine. Version 1.3.0.112 (x64)):
```
PS C:\WINDOWS\system32> opm list
System.Exception: Error loading assemblies:
Inner exception [0]System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Имя файла: 'OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null'

Предупреждение: регистрация привязки сборок выключена.
Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].

Inner exception [1]System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Имя файла: 'OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null'

Предупреждение: регистрация привязки сборок выключена.
Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].

Inner exception [2]System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Имя файла: 'OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null'

Предупреждение: регистрация привязки сборок выключена.
Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].

Inner exception [3]System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Имя файла: 'OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null'

Предупреждение: регистрация привязки сборок выключена.
Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].

Inner exception [4]System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Имя файла: 'OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null'

Предупреждение: регистрация привязки сборок выключена.
Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].

Inner exception [5]System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Имя файла: 'OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null'

Предупреждение: регистрация привязки сборок выключена.
Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].

Inner exception [6]System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Имя файла: 'OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null'

Предупреждение: регистрация привязки сборок выключена.
Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].

Inner exception [7]System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Имя файла: 'OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null'

Предупреждение: регистрация привязки сборок выключена.
Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].

Inner exception [8]System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Имя файла: 'OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null'

Предупреждение: регистрация привязки сборок выключена.
Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].

Inner exception [9]System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Имя файла: 'OneScript.Language, Version=1.3.0.112, Culture=neutral, PublicKeyToken=null'

Предупреждение: регистрация привязки сборок выключена.
Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].


   в ScriptEngine.Machine.Contexts.ContextDiscoverer.DiscoverClasses(Assembly assembly)
   в ScriptEngine.ScriptingEngine..ctor()
   в ScriptEngine.HostedScript.HostedScriptEngine..ctor()
   в oscript.ExecuteScriptBehavior.Execute()
   в oscript.Program.Main(String[] args)
```

**Comment by EvilBeaver** [comment]
opm упакован в exe?

**Comment by arkuznetsov** [comment]
> opm упакован в exe?

нет, до этого еще не дошло, я просто хотел воспроизвести проблемный пример и у меня даже opm не заработал.

**Comment by EvilBeaver** [comment]
@arkuznetsov не воспроизводится:

* Скачал 1.3.0.112 x64
* Запустил opm list

Работает. Нужна еще информация. Есть ли в каталоге установки 1.3.0.112 файл OneScript.Language.dll?

**Comment by arkuznetsov** [comment]
@EvilBeaver Нет, такого файла нету :-(

**Comment by EvilBeaver** [comment]
Исправил в сборке 113 https://build.oscript.io/job/1Script/job/develop/lastSuccessfulBuild/artifact/built/OneScript-1.3.0-x64.exe

**Comment by arkuznetsov** [comment]
@EvilBeaver в новой сборке проблема ушла.
При выполнении тестового сценария со сборкой exe:
- exe собрался
- при запуске exe ошибка:
```
{Модуль oscript://log-manager.os / Ошибка в строке: 24 / Значение не является значением объектного типа}
```

**Comment by EvilBeaver** [comment]
Какой именно exe собрался? Какого пакета?

**Comment by arkuznetsov** [comment]
> Какой именно exe собрался? Какого пакета?

Собирал из файлика test.os, содержащего:
```
#Использовать irac
Сообщить("go");
```

**Comment by arkuznetsov** [comment]
Заработало!

**Comment by EvilBeaver** [comment]
Гады, заставили меня-таки переписать standalonerunner более-менее по-людски

**Comment by nixel2007** [comment]
@EvilBeaver так это ж хорошо!

**Comment by EvilBeaver** [comment]
@nixel2007 дык я делал его, как прикол и надеялся, что он отомрет )

**Comment by asosnoviy** [comment]
> @nixel2007 дык я делал его, как прикол и надеялся, что он отомрет )

это же киллер фича!

**Comment by khorevaa** [comment]
@EvilBeaver Это самая нужная фича, для меня и тех проектов на oscript, что я реализовал :))

**Comment by perfolenta** [comment]
Предлагаю класть все необходимые dll в ту же папку, где лежит ЕХЕ. Рядом создавать файл имяфайлаехе.cfg, в который записывать имена dll, которые необходимо загрузить... Этот файл нужен потому, что тут же в папке могут быть сторонние dll, которые не являются библиотеками ОСкрипта и поэтому их загружать не надо...
Я дописал небольшой фрагмент в файл src\StandaloneRunner\ProcessLoader.cs и всё заработало...
Прилагаю к этому сообщению файл исходника и пример того, как все выглядит в готовом виде...
Cам сделать PR не могу, так что если решение посчитаете правильным и есть желающие внедрить, будет хорошо...
[Пример.zip](https://github.com/EvilBeaver/OneScript/files/7723843/default.zip)
