### ISSUE TITLE
Ошибка при выполнении собранного exe в mono. Ночная сборка от 15.10.2019

### ISSUE THREAD

**Issue by maximkin7** [EvilBeaver/OneScript#949]
## Заработать на исправлении

https://www.bountysource.com/issues/82095189-exe-mono-15-10-2019

## Описание

test1610v1.exe - собранный exe. 

Ошибка и её воспроизведение::

serever@user:/tmp$ mono test1610v1.exe 
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'OneScript.Language, Version=1.2.0.74, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'OneScript.Language, Version=1.2.0.74, Culture=neutral, PublicKeyToken=null'
  at StandaloneRunner.Program.Run (System.String[] args) [0x0000c] in <811c1a56ab314c79bdac43498cd2f55d>:0 
  at StandaloneRunner.Program.Main (System.String[] args) [0x00000] in <811c1a56ab314c79bdac43498cd2f55d>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'OneScript.Language, Version=1.2.0.74, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'OneScript.Language, Version=1.2.0.74, Culture=neutral, PublicKeyToken=null'
  at StandaloneRunner.Program.Run (System.String[] args) [0x0000c] in <811c1a56ab314c79bdac43498cd2f55d>:0 
  at StandaloneRunner.Program.Main (System.String[] args) [0x00000] in <811c1a56ab314c79bdac43498cd2f55d>:0 

serever@user:/tmp$ mono -V
Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:20:06 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com

 - ОС: Linux 
 - Версия: ночная сборка от 15.10.2019

**Comment by EvilBeaver** [comment]
Щёрт! (

**Comment by EvilBeaver** [comment]
Просьба проверить на Моно 5.x Шестая порождает не только эту проблему

**Comment by maximkin7** [comment]
Теперь моя очередь:) Щёрт!)
У нас хитрый linux, собранный из слоев, который уже в проде. Надо к сетивиков просить пересобрать  слой с mono и обновить.  Какую версию mono лучше ставить(попробую с сетевиками поговорить)? И может есть инфа какие баги на 6 можем отловить...

**Comment by EvilBeaver** [comment]
вот еще проблема с шестой версией #936
