### ISSUE TITLE
Ошибка метода "КопироватьФайл" Эта операция не поддерживается для относительных URI-адресов.

### ISSUE THREAD

**Issue by thedemoncat** [EvilBeaver/OneScript#957]
1Script Execution Engine. Version 1.2.0.81

Код
```bsl
Функция ПолучитьМанифестСборки(Знач КаталогСборки)

	ИсходныйМанифест = ФайлМанифеста;
	РабочийМанифест = ПолучитьИмяВременногоФайла("package.edf");
	КопироватьФайл(ИсходныйМанифест, РабочийМанифест);
	
	Возврат РабочийМанифест;
	
КонецФункции
```

И ошибка: 

`
ИНФОРМАЦИЯ - Запускаю приложение для сбора информации о метаданных
ИсходныйМанифестpackage.edf
РабочийМанифестC:\Users\ci-bot-slave\AppData\Local\Temp\obtqkdee.z1c.package.edf
КРИТИЧНАЯОШИБКА - {Модуль D:\j-int\workspace\personalBuild\v8-librmq\modules\packman\src\Классы\СборщикДистрибутива.os / Ошибка в строке: 66 / Внешнее исключение (System.InvalidOperationExcepterationException): Эта операция не поддерживается для относительных URI-адресов.}
`

Походу приехало от сюда https://github.com/EvilBeaver/OneScript/pull/916

**Comment by EvilBeaver** [comment]
Полагаю, что да. Но все тесты проходят.. ((

**Comment by dvakor** [comment]
> Полагаю, что да. Но все тесты проходят.. ((

Посмотрю на выходных
