### ISSUE TITLE
Реализация TimeSpan

### ISSUE THREAD

**Issue by witales** [EvilBeaver/OneScript#959]
Хотелось бы иметь возможность работать с временным промежутком так же удобно, как и в .NET. Для чего это может понадобиться: вывод времени выполнения процесса в читаемом виде (а не количество миллисекунд). Да, можно преобразовать это число в нужные составляющие "вручную", но код получается громоздким.

Как я это вижу:
**пример 1**
```
Интервал = Новый ИнтервалВремени(Дата(2019, 11, 1), Дата(2019, 11, 2));
Сообщить(Интервал);
```
Вывод:
`1.00:00:00`

**пример 2**
```
Интервал = Новый ИнтервалВремени(123456);
Сообщить(Интервал.Часы);
Сообщить(Интервал.Минуты);
Сообщить(Интервал.Секунды);
Сообщить(Интервал.ВсегоСекунд);
Сообщить(Интервал);
```
Вывод:
```
0
2
3
123.456
00:02:03.4560000
```

**Comment by EvilBeaver** [comment]
Я верно понял, что такого класса нет в 1С? Если так, то тогда просьба получше документировать сам класс, его методы и конструкторы, ибо пользователям класса неоткуда будет узнать о том, как им пользоваться, кроме как из Вашей документации.

**Comment by dvakor** [comment]
> Я верно понял, что такого класса нет в 1С? Если так, то тогда просьба получше документировать сам класс, его методы и конструкторы, ибо пользователям класса неоткуда будет узнать о том, как им пользоваться, кроме как из Вашей документации.

А вообще стоит ли включать такой класс сразу в движок? он же вполне себе может в виде либы существовать и для данной реализации ненужен даже .NET очень просто реализуется на нативном Оскрипте.

**Comment by witales** [comment]
Обязательно дополню документацию, если получу принципиальное согласие на включение класса в движок.
Об отдельной либе тоже думал (находил https://github.com/khorevaa/datetime), но ее предполагаемая реализация показалась мне гораздо более сложной, чем лаконичность .net.

**Comment by EvilBeaver** [comment]
Ну с одной стороны, мне не очень нравится идея включения нестандартных классов в движок. С другой стороны, у нас и так уже имеются такие классы и четких критериев "это сюда, а это туда" у меня нет. Кроме того, мне приятно получить пулреквест, поэтому я не против. Но я бы хотел послушать @dmpas например

**Comment by dvakor** [comment]
> Обязательно дополню документацию, если получу принципиальное согласие на включение класса в движок.
> Об отдельной либе тоже думал (находил https://github.com/khorevaa/datetime), но ее предполагаемая реализация показалась мне гораздо более сложной, чем лаконичность .net.

Имхо, лучше было бы отправить допилить либу и кинуть в эту либу ПР :)
Я просто против того, чтобы переносить просто .NET фичи в движок без явной на это не обходимости, в данном случае ради "сахара".
Просто сейчас у оскрипта отличная совместимость с 1С в большенстве случаев перенос кода между 1С и окспритом осуществляется копипастом, а с добавлением таких фич есть вероятность что данная совместимость сойдет на нет, и получиться свой 1С.NET

**Comment by dmpas** [comment]
> есть вероятность что данная совместимость сойдет на нет

если ты используешь либы, то ровно так же ты уже не сможешь просто копипастом переносить код. С этой точки зрения нет разницы, новый объект в движке или в библиотеке.

Я б внёс в движок, но мне не понятны сценарии.
Приведённая задача удобочитаемости в идеале должна решаться в рамках функции `Формат`, а не новым объектом.

**Comment by dvakor** [comment]
> > есть вероятность что данная совместимость сойдет на нет
> 
> если ты используешь либы, то ровно так же ты уже не сможешь просто копипастом переносить код. С этой точки зрения нет разницы, новый объект в движке или в библиотеке.
> 
> Я б внёс в движок, но мне не понятны сценарии.
> Приведённая задача удобочитаемости в идеале должна решаться в рамках функции `Формат`, а не новым объектом.

ээм, ну в данный момент и либы чаще всего копипастяться спокойно :)
По крайней мере те, что я переносил, некоторые то понятно не перенести в принципе, SFTP или Entity какой нить

**Comment by EvilBeaver** [comment]
@witales можешь, действительно, пояснить про сценарий применения этого класса? Форматирование микросекунд? Какие еще плюшки от него предполагались?

**Comment by witales** [comment]
Кейсы использования:
1. Хочу реализовать https://github.com/silverbulleters/vanessa-runner/issues/257.
Имея дату начала процесса и дату окончания, получаем разницу в секундах. Можно вывести именно её, но это хорошо только для быстрых процессов. Для более длительных удобнее видеть количество минут или даже часов.
Подумал, что логично выводить ровно в том же универсальном виде, как это реализовано в Oscript/TestApp.

2 (гипотетический). Хочу реализовать некую ленту событий (например на сайте), у каждого события должно быть представление времени, прошедшего с момента его публикации (как в twitter или в комментах GitHub)).
Логика получения представления метки примерно такая:
```
Функция МеткаСобытия(ДатаСобытия) 
   Интервал = Новый ИнтервалВремени(Текущаядата() - ДатаСобытия);
   Если Интервал.ВсегоСекунд < 60 Тогда
	Возврат Интервал.Секунды + " s";
   ИначеЕсли Интервал.ВсегоМинут < 60 Тогда
	Возврат Интервал.Минуты + " m";
   ИначеЕсли Интервал.ВсегоЧасов < 24 Тогда
	Возврат Интервал.Часы + " h";
   ИначеЕсли Интервал.ВсегоДней < 5 Тогда
	Возврат Интервал.Дни + " d";
   Иначе
	Возврат Формат(ДатаСобытия, "ДФ=dd.MM.yyyy");
   КонецЕсли;
КонецФункции
```
Согласен, что это сахар, и можно обойтись танцами с Формат() и преобразованием разности дат (числа миллисекунд) обратно в дату, но по мне это не очень наглядно.

**Comment by dmpas** [comment]
Мне кажется, что если переписать этот кусок кода на чистый 1С, то будет ровно столько же строчек кода.

**Comment by witales** [comment]
По второму кейсу - да, строк столько же, но восприятие другое. У меня так получилось:
`Функция МеткаСобытия(ДатаСобытия)
	
	РазностьСек = Текущаядата() - ДатаСобытия;
	РазностьКакДата = Дата(1, 1, 1) + РазностьСек;
	Если РазностьСек < 60 Тогда
		Возврат "" + Формат(РазностьКакДата, "ДФ=ss") + " s";
	ИначеЕсли РазностьСек / 60 < 60 Тогда
		Возврат "" + Формат(РазностьКакДата, "ДФ=mm") + " m";
	ИначеЕсли РазностьСек / (60 * 60) < 24 Тогда
		Возврат "" + Формат(РазностьКакДата, "ДФ=hh") + " h";
	ИначеЕсли РазностьСек / (60 * 60 * 24 ) < 5 Тогда
		Возврат "" + Формат(РазностьКакДата - 60 * 60 * 24, "ДФ=dd") + " d";
	Иначе
		Возврат Формат(ДатаСобытия, "ДФ=dd.MM.yyyy");
	КонецЕсли;
		
КонецФункции`

Реализация первого кейса на чистом 1С будет сложнее, чем одна строка кода.

**Comment by alexkmbk** [comment]
> 
> 
> Обязательно дополню документацию, если получу принципиальное согласие на включение класса в движок.
> Об отдельной либе тоже думал (находил https://github.com/khorevaa/datetime), но ее предполагаемая реализация показалась мне гораздо более сложной, чем лаконичность .net.

Можно реализовать не в виде библиотеки, а в виде внешней компоненты. То есть написать на .net но не делать частью движка - http://oscript.io/dev/page/components
Как пример, внешняя компонента GUI - https://github.com/ret-Phoenix/oscript-simple-gui

**Comment by EvilBeaver** [comment]
С компонентами есть некие траблы. @witales давай по документации решим вопрос и вольем

**Comment by khorevaa** [comment]
@witales Я вот думаю что такая либа на чистом 1С (без нет) была бы полезна сообществу

**Comment by witales** [comment]
Давайте я попробую в виде либы (без .net) оформить, закину PR в  https://github.com/khorevaa/datetime, раз по этому PR неоднозначные мнения. В конце концов к нему позже можно будет вернуться.

**Comment by EvilBeaver** [comment]
@witales ок
