### ISSUE TITLE
В отладчике не вычисляется значение

### ISSUE THREAD

**Issue by arkuznetsov** [EvilBeaver/OneScript#961]
В отладчике не вычисляется значение переменной возможно из за большого размера или из-за содержимого - Строка JSON (массив JSON из 200 элементов-соответствий).

**Воспроизведение ошибки**
1. Отлаживаю библиотеку https://github.com/ArKuznetsov/yabr.os
2. Запускаю с параметрами: 
```json
"args": ["p", "--work-dir", ".\\test-reports", ".\\examples\\clusterdata\\jornal2elastic.json"]
```
3. Ставлю точку останова в модуле "ВыводДанныхВЭластик.os" в строке (686).
4. Пытаюсь вычислить значение переменной "ПараметрыЗапросаДляОтправки" и получаю ошибку:
```txt
Коммуникационный объект System.ServiceModel.Channels.ServiceChannel нельзя использовать для связи, так как он находится в состоянии Faulted.
```

**Ожидаемое поведение**
Ожидаю увидеть содержимое переменной

**Окружение**
 - ОС: Win 10 (19018.1)
 - Версия: 1.2.0 (x86)
 - Отладчик: 0.5.0

**Comment by dvakor** [comment]
Ого, это что то новенькое, падает wcf по все видимости, вот только там всюду трай кетчи натыканы) 

Сколько символов в "ПараметрыЗапросаДляОтправки" ?

UPD: 

```
Текст = "";

Для й = 1 ПО 10000 Цикл

	Текст = Текст + Символы.ПС + "ыфвыворпафыловаплоыавплрывалопраыволпаывлопываорплоаывплыавдлополаыврпоолыаврплоыварполавырпдлоаывлоп";

КонецЦикла;
```

Если попытаться вычислить такое в отладчике, то падает аналогично, так что там чет с длинными строками

UPD2:
Падает прям сам WCF , по всей видимости переполнение буфера
Вычислил максимальную длину строки которую в данный момент переваривает WCF: 65286 символов
