### ISSUE TITLE
Ошибка в змейке.

### ISSUE THREAD

**Issue by MStepanov55** [EvilBeaver/OneScript#964]
Здравствуйте!
Установил версию 1.0.21
Пытаюсь запустить змейку
Выдает ошибку:

Script started: 07.12.2019 23:03:22
{Модуль D:\1C\_Дистрибутивы\Fiches\OneScript-1.2.0-x64\examples\snake.os / Ошибка в строке: 51 / Внешнее исключение (System.IO.IOException): Неверный дескриптор.
}    
	Консоль.ВидимостьКурсора(Ложь);

Error detected. Exit code = 1
Script completed: 07.12.2019 23:03:22
Duration: 00:00:00.0017623

Стоит windows 8
Подскажите в чем причина?

**Comment by EvilBeaver** [comment]
Может вы из-под powershell запускаете?

**Comment by Mr-Rm** [comment]
Из-под powershell змейка работает нормально.
Судя по "_Script started: 07.12.2019 23:03:22_" и прочему - запускалось из-под ТestApp.exe, а в нём работа с консолью отсутствует.

**Comment by EvilBeaver** [comment]
@Mr-Rm действительно! Спасибо за подсказку!

@maximkin7 консоль TestApp предназначена для разработки самого движка и его отладки. Она НЕ является средой разработки и основной средой запуска сценариев. Т.е. запускать ее надо только когда собираешься поизучать что-либо отладчиком во внутренностях движка 1Script.

**Comment by MStepanov55** [comment]
@EvilBeaver, да когда компилируешь, через "oscript -make snake.os snake.exe"  все работает! Спасибо
