### ISSUE TITLE
Созданный по oscript.exe -make exe выдает ошибку:

### ISSUE THREAD

**Issue by vampelly** [EvilBeaver/OneScript#965]
Необработанное исключение: System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "OneScript.Language, Version=1.2.0.92, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
   в StandaloneRunner.StandaloneProcess.Run()
   в StandaloneRunner.Program.Main(String[] args)

Исходный текст скрипта : 

#Использовать v8rac

Перем УправлениеКластером;

Процедура ОтключитьСоединенияИнформационнойБазы(UID)
	Если ЗначениеЗаполнено(UID) Тогда 
		ТаблицаСоединений = УправлениеКластером.СписокСоединенийИнформационнойБазы(UID);
		Для каждого Соединение Из ТаблицаСоединений Цикл
			Если НЕ Соединение.Приложение = "WebServerExtension" Тогда Продолжить; КонецЕсли;
			Попытка
				УправлениеКластером.ОтключитьСоединение(Соединение.Идентификатор, Соединение.Процесс, Соединение.Кластер);
			Исключение
				Сообщить(ОписаниеОшибки());
			КонецПопытки;
		КонецЦикла;
	КонецЕсли;
КонецПроцедуры

УправлениеКластером = Новый УправлениеКластером;
УправлениеКластером.УстановитьКластер("xxx");
УправлениеКластером.ИспользоватьВерсию("8.3");
УправлениеКластером.УстановитьАвторизациюКластера("xxx", "xxx");
УправлениеКластером.Подключить();
МассивЛокальныхКластеров = УправлениеКластером.СписокЛокальныхКластеров();
ТаблицаИБ =  УправлениеКластером.СписокИнформационныхБаз(МассивЛокальныхКластеров[0]);
Для каждого стр Из ТаблицаИБ Цикл ОтключитьСоединенияИнформационнойБазы(стр.UID); КонецЦикла;

**Comment by EvilBeaver** [comment]
@vampelly на линукс? на windows? 
Просьба оформлять багрепорты по прилагаемому шаблону

**Comment by vampelly** [comment]
Re: [EvilBeaver/OneScript] Созданный по oscript.exe -make exe выдает ошибку: (#965)


Здравствуйте, Andrei.

Вы писали 12 декабря 2019 г., 19:05:01:





@vampelly на линукс?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



на windows

--
С уважением,
 vampelly                          mailto:vampelly@mail.ru

**Comment by vadimusimus** [comment]
Суть проблемы: при установке OneScript из exe-шника в каталоге bin отсутствует библиотека OneScript.Language.dll.
Решение: скопировать библиотеку OneScript.Language.dll из zip архива.

**Comment by EvilBeaver** [comment]
Проблема известна. Обход: не делать exe или собирать exe версией 1.1

**Comment by EvilBeaver** [comment]
Решено.
