### ISSUE TITLE
opm install -all

### ISSUE THREAD

**Issue by astrizhachuk** [EvilBeaver/OneScript#966]
При установке пакетов через opm install -all для 64х разрядной windows пакеты устанавливаются не в lib, а C:\Windows\System32\oscript_modules

1. через choco поставить 1.2.0
2. opm update opm
3. opm install -all 
4. модули устанавливаются в C:\Windows\System32\oscript_modules

Проблема проявляется для "новых" машин. OneScript ранее не устанавливался, PATH пустой.

**Comment by EvilBeaver** [comment]
Занятно. А есть мысли почему так может быть?

**Comment by emayskiy** [comment]
Тоже на это попал. Ставит в текущий каталог в Командной строке. Если запустил консоль от имени пользователя, то это домашний каталог пользователя. Если консоль запущена под администратором, то это будет C:\Windows\System32.
Т.е. перед установкой пакетов надо сменить текущий каталог на тот, куда надо ставить.

**Comment by nixel2007** [comment]
Господи, да где вы берете этот -all с одним минусом? Пожалуйста, прийдите к автору и скажите, чтобы он обновил свою статью!
Opm уже года три назад перешёл на разбор параметров аргументов командной строки по стандарту posix, где опции с одним минусом - это, во-первых, шорткаты для опций с двумя минусами, а во-вторых имеют возможность склеиваться в одно слово.

opm install -all = opm install --all --local --local

Это локальная установка всех пакетов в текущий каталог, ещё и с непредсказуемым поведением от двойного использования флага --local. Не делайте так, тем более в консоли с правами админа!

**Comment by astrizhachuk** [comment]
Досада 2019 года, если она не актуальна, то можно и закрыть. А если до сих по можно воткнуть -all и софт "что-то делает" не обрабатывая кривой аргумент, то это, кмк, ошибка, и не oscript.

**Comment by nixel2007** [comment]
Он обрабатывает аргумент именно так, как его просят. Просто пользователи не понимают, что они вводят не то, что хотят

**Comment by astrizhachuk** [comment]
Госпади, да почему пользователь всегда чего-то не понимает? Причин может быть много в его ошибке с одним дефисом. Вот эти парни более дружелюбны к неучам:
```
go list -m main.go
go list -m: not using modules
```
vs
```
go list -mm main.go 
flag provided but not defined: -mm
```

**Comment by astrizhachuk** [comment]
Пардон, бомбануло. С нашим профессиональным праздником нас!
