### ISSUE TITLE
Пакет onescript-engine-1.2.0-1.fc26.noarch.rpm пустой

### ISSUE THREAD

**Issue by vasvl123** [EvilBeaver/OneScript#968]
**Опишите ошибку**
Установка проходит но файлов нет

**Воспроизведение ошибки**
1. Запустить код ...
2. Подать на вход параметры ...
3. Увидеть ошибку

**Ожидаемое поведение**
Опишите, как должна вести себя система в указаных условиях. Ведет ли себя 1С в тех же условиях иным образом?

**Окружение**
 - ОС: fedora
 - Версия:

**Дополнительная информация**

**Comment by dmpas** [comment]
Подтверждаю. В архиве только shell скрипты , бинарей нет.

**Comment by EvilBeaver** [comment]
Бида ((

**Comment by EvilBeaver** [comment]
Бида ((

**Comment by dmpas** [comment]
@vasvl123 
попробуй ночник
https://oscript.io/downloads/night-build/x64/onescript-engine-1.3.0-1.fc26.noarch.rpm
