### ISSUE TITLE
Ошибка доступа к файлу.

### ISSUE THREAD

**Issue by botokash** [EvilBeaver/OneScript#970]
**Описание проблемы**
Попытка открыть файл для чтения через **ФайловыеПотоки.ОткрытьДляЧтения()** приводит к ошибке доступа.

**Воспроизведение ошибки**
1. Включить тех. журнал платформы 1С по всем событиям, для примера взять любой файл лога.
2. Создать скрипт с кодом:
```bsl
ПутьКФайлу = "блабла\rphost_9968\20011220.log";
ПотокДанных = ФайловыеПотоки.ОткрытьДляЧтения(ПутьКФайлу);
``` 
3. Запустить скрипт.
3. Увидеть ошибку:
`Ошибка в строке: 2 / Внешнее исключение (System.IO.IOException): Процесс не может получить доступ к файлу "блабла\rphost_9968\20011220.log", так как этот файл используется другим процессом.}`

**Ожидаемое поведение**
Данный код в платформе 1С отрабатывает без ошибки.

**Окружение**
 - ОС: Windows 10 x64
 - Версия Oscript: 1.2.0.92
 - Версия платформы 1С: 8.3.12.1714

**Comment by EvilBeaver** [comment]
Т.е. 1скрипт открывает файл монопольно, а 1С - нет, я верно понял?

**Comment by Mr-Rm** [comment]
Проблема в том, что ФайловыйПоток всегда открывается в режиме `FileShare.Read`, несмотря на требуемый доступ `FileAccess`.
https://github.com/EvilBeaver/OneScript/blob/589e8efa212df25cebc7829bf670f3903d97ea84/src/ScriptEngine.HostedScript/Library/Binary/FileStreamContext.cs#L36 и то же на 5 строчек ниже.
В консоли пишем:
```
copy con > somefile
```
somefile открыт в режимах _Access: Generic Write, ShareMode: Read_
Выполняем:
```bsl
ПотокДанных = ФайловыеПотоки.ОткрытьДляЧтения("somefile");
```
Попытка открыть somefile в режимах _Access: Generic Read, ShareMode: Read_ - получаем SHARING VIOLATION.
Нужно вставить проверку в FileStreamsManager или FileStreamContext.

**Comment by botokash** [comment]
> Т.е. 1скрипт открывает файл монопольно, а 1С - нет, я верно понял?

Судя по всему так.

**Comment by EvilBeaver** [comment]
@Mr-Rm я не совсем понял фразу "нужно вставить проверку"? Какую именно проверку?

**Comment by Mr-Rm** [comment]
`access==FileAccessEnum.Read ? FileShare.ReadWrite : FileShare.Read`
Для совместимости уточнить, позволяет ли 1С другому процессу удалять открытый для чтения файл.
Плюс обработка исключений.
