### ISSUE TITLE
Некорректное/несовместимое поведение функции Файл.Существует()

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#973]
Проверялось пока только для Windows.

**Воспроизведение ошибки**

```bsl
Файл=Новый Файл(ИмяФайла);
Результат=Файл.Существует();
```
В зависимости от имени файла возможно следующее:

1. Относительные пути

ИмяФайла|Результат (1С)|Результат (OS)|ПолноеИмя (OS)
--|--|--|--
"c:windows"|Нет|Да|"C:\windows"
"windows"|Нет|Нет|"С:\Program Files\OneScript\bin\windows" _(каталог oscript.exe, не файла скрипта)_

При этом для 1С в обоих вариантах ПолноеИмя == ИмяФайла, а поиск идёт в каталоге `C:\Program Files\1cv8\common`. Вместо любого `Нет` может оказаться и `Да`.

Поиск на дисках, отличных от того, на котором расположен рабочий каталог программы производится в текущем каталоге соответствующего диска.
Варианты без пути и с пробелами:

ИмяФайла|Результат (1С)|ПолноеИмя (1С)|Результат (OS)|ПолноеИмя (OS)
--|--|--|--|--
"C: "|Да|"C:"|Да|"c:\Program Files\OneScript\bin\"
" C:"|Нет|"sfile://sfile://&nbsp;C:"|Да|"c:\Program Files\OneScript\bin\"
"&nbsp;&nbsp;C:" _(**два** пробела в начале)_|Нет|"sfile://sfile://&nbsp;&nbsp;C:"|Нет _(а может и Да)_|"c:\Program Files\OneScript\bin\C" **(!)**

Полученное ПолноеИмя в последней строке - это баг функции `System.IO.Path.GetFullPath()` в .Net Framework версий с 4 по 4.6.1 включительно.

А вот это похоже на баг и в 1С:

ИмяФайла|Результат (1С)|ПолноеИмя (1С)|Результат (OS)|ПолноеИмя (OS)
--|--|--|--|--
"\\..\\.."|Нет|""|Да|"c:\"
"..\\.."|Нет|""|Да|"c:\Program Files"
"\\."|Нет|""|Да|"c:\"
"."|Нет|""|Да|"c:\Program Files\OneScript\bin"
"c:."|Да|"c:"|Да|"c:\Program Files\OneScript\bin"
"c:..\\.."|Да|"c:"|Да|"c:\Program Files"

2. Имя файла - предопределённое устройство
1С даёт следующее:

ИмяФайла|Результат 1С
--|--
"nul"|Да
"c:\nul"|Да
"\\\\.\nul"|Нет

OScript во всех вариантах  рассматривает полное имя `\\.\nul` и падает с исключением
_System.IO.IOException: Синтаксическая ошибка в имени файла, имени папки или метке тома_, соответствуя документации .net.

3. Все прочие исключения

ИмяФайла|Результат OS
--|--
"c:\*"|System.ArgumentException: Illegal characters in path
"file://c:/windows"|System.ArgumentException: URI formats are not supported
"\\\\.\c:\windows\"|System.NotSupportedException): The given path's format is not supported
"\\\\OtherComp\WrongShare"|System.IO.IOException: Не найдено сетевое имя
"\\\\Inaccessible\RealShare"|System.IO.IOException: Не найден сетевой путь
"\\\\Nonexistent\Any"|System.IO.IOException: Указан недопустимый путь
"СлишкомДлинноеИмяФайла" _(>260 символов)_|System.IO.PathTooLongException: The specified path, file name, or both are too long.
"c:\tmp\denied\test" _(доступ к `denied` запрещён)_|System.UnauthorizedAccessException: Access to the path 'c:\tmp\denied\test' is denied

Результат 1С всегда `Нет`, без исключений.

От большей части исключений можно избавиться, используя `File.Exists()` и `Directory.Exists()` вместо `File.GetAttributes()`.
C первыми двумя пунктами надо разбираться вручную. Многие различия связаны с разным поведением свойства `Файл.ПолноеИмя`.

**Comment by EvilBeaver** [comment]
Не уверен, что все перечисленное нужно приводить в соответствие с 1С

**Comment by Mr-Rm** [comment]
Всё перечисленное - точно не нужно. Работа с "." и ".." в OS явно правильнее.
В примерах без пути с пробелами .Net Framework и .Net Core различный результат дают.
Определять ли устройства типа "NUL", "LPT", "COM1"?
Всегда ли возвращать `Нет` вместо исключений?

**Comment by EvilBeaver** [comment]
Устройства не уверен что нужны. И длинные пути у нас не поддерживаются. Но исключения некоторые можно и убрать, наверное.

**Comment by Mr-Rm** [comment]
Исключения некоторые - какие? или все? 1С не бросает исключений никогда.

_Понятно, что можно сделать любой вариант или даже оставить как есть. Тут надо решить, на что больше ориентироваться: на 1С или на .Net_

**Comment by EvilBeaver** [comment]
Думаю, что .net ведет себя правильнее за исключением пункта 3 с проверкой существования. Здесь лучше привести к 1С - файл со странным именем не существует
