### ISSUE TITLE
Ошибки в компиляторе

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#977]
**Опишите ошибку**
Компилятор допускает явно неправильные конструкции

**Воспроизведение ошибки**
1. Запустить код
```bsl
Функция Функ(парам)
	Для индекс=1 По 1 Цикл
		Если парам=0 КонецЦикла // !
			Сообщить(парам);
		КонецЕсли
	КонецЦикла
КонецФункции

Процедура Проц()
	Для индекс=1 По 1 КонецПроцедуры // !
		Сообщить(индекс);
	КонецЦикла
КонецПроцедуры

Функ(0);
Проц();

Массив=Новый Массив;
Массив.Добавить(2);
Попытка
	Для каждого элем из Массив Исключение // !
		Сообщить(элем);
	КонецЦикла;
	ВызватьИсключение("");
Исключение
	Пока Истина КонецПопытки  // !
		Сообщить(3);
		Прервать;
	КонецЦикла
КонецПопытки
```
2. Увидеть вывод:
_0
1
2
3_

**Ожидаемое поведение**
Должна быть синтаксическая ошибка в каждой строке,  отмеченной `// !`

**Дополнительная информация**
Ошибка из-за неверной обработки `endTokens` в `BuildExpression()`

**Comment by EvilBeaver** [comment]
@Mr-Rm Занятно. Могу взять в починку. Или есть желание починить?

**Comment by Mr-Rm** [comment]
Ошибку обнаружил, перерабатывая понемногу компилятор:
https://github.com/Mr-Rm/OneScript/tree/wip/compiler
Починю и это.
