### ISSUE TITLE
Остановка работы 1Script console host

### ISSUE THREAD

**Issue by 4ppl** [EvilBeaver/OneScript#978]
При выгрузке DT с помощью v8runner (класс УправлениеКонфигуратором, метод ВыполнитьКоманду()) на одной из 2-х десятков баз постоянно "падает" oscript.
Скрипт запускается из планировщика заданий windows с правами администратора.
При этом конфигуратор отрабатывает нормально и DT формирует. Т.е. происходит следующая последовательность: запуск скрипта - запуск конфигуратора - падение скрипта - конфигуратор нормально отрабатывает - **тут скрипт должен был дождаться когда конфигуратор завершит работу, после чего разблокировать начало сеансов для базы, но он уже "упал" и база остается не разблокированной**

Источник
1Script console host

Сводка
Остановка работы

Дата
‎04.‎02.‎2020 3:40

Состояние
Отчет отправлен

Описание
Неправильный путь приложения:	C:\Program Files\OneScript\bin\oscript.exe

Сигнатура проблемы
Имя проблемного события:	BEX64
Имя приложения:	oscript.exe
Версия приложения:	1.2.0.92
Отметка времени приложения:	af0da5d8
Имя модуля с ошибкой:	ucrtbase.dll
Версия модуля с ошибкой:	10.0.14393.2999
Отметка времени модуля с ошибкой:	5ce36be6
Смещение исключения:	000000000006e00e
Код исключения:	c0000409
Данные исключения:	0000000000000007
Версия ОС:	10.0.14393.2.0.0.16.7
Код языка:	1049
Дополнительные сведения 1:	a90c
Дополнительные сведения 2:	a90c21b37010a60b00fd339ae8152069
Дополнительные сведения 3:	8d38
Дополнительные сведения 4:	8d388366e7d6e5c3e7b4e106a5ae46d6

Дополнительные сведения о проблеме
ИД контейнера:	539f0f4a35f947da67f9e7d93b0f3d4f (1727666852258069839)

**Окружение**
 - ОС: Windows server 2016 standart
 - Версия: 1607

**Comment by EvilBeaver** [comment]
Эта информация мне ни о чем не говорит, к сожалению. Нужен более конкретный пример воспроизведения.

**Comment by EvilBeaver** [comment]
Рекомендуют накатить апдейты на винду. Это все что мне удалось найти.

**Comment by 4ppl** [comment]
Обновления накатаны. По мере возможностей ищу пути воспроизведения
проблемы. Если найду - сообщу обязательно.

пн, 10 февр. 2020 г., 14:44 Andrei Ovsiankin <notifications@github.com>:

**Comment by EvilBeaver** [comment]
Закрываю до выяснения. Просьба переоткрыть или создать новый issue когда будут новости.
