### ISSUE TITLE
Сбой при сравнении двух элементов массива при сортировке строк дерева значений

### ISSUE THREAD

**Issue by otymko** [EvilBeaver/OneScript#982]
Возникает проблема при сортировке строк в дереве значений. Пример:
```bsl
ДеревоПравил.Строки.Сортировать("Порядок Возр", Истина);
```

Как воспроизвести: запускает тест у проекта gitrules. Ошибка будет вида:
```
ОШИБКА: Тест: <ТестДолжен_ПроверитьСборкуПравилОбмена>
Файл: <D:\DATA\Develop\Project\gitrules\tests\Тест_СобратьПравилаОбмена.os>
Сообщение: {Модуль D:\DATA\Develop\Project\gitrules\src\core\Модули\СобратьПравилаОбмена.os / Ошибка в строке: 333 / Внешнее исключение (System.InvalidOperationException): Сбой при сравнении двух элементов массива.}
        ДеревоПравил.Строки.Сортировать("Порядок Возр", Истина);
```
Версия OS: Win 10 (17763)
Версия OneScript: 1.3.132

**Comment by EvilBeaver** [comment]
@otymko будь добр, скинь ссылку на строку исходника, которая вызывает ошибку

**Comment by otymko** [comment]
@EvilBeaver https://github.com/otymko/gitrules/blob/2fe88cf6859e9c4752e1c91201126587a7934f90/src/core/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%A1%D0%BE%D0%B1%D1%80%D0%B0%D1%82%D1%8C%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0%D0%9E%D0%B1%D0%BC%D0%B5%D0%BD%D0%B0.os#L333

**Comment by EvilBeaver** [comment]
не врубаюсь как запустить тест на gitrules

> C:\Users\ovsia\AppData\Local\ovm\current\lib\gitrules> 1bdd exec tests

ничего не происходит

Как воспроизводить ошибку?
