### ISSUE TITLE
HTTPЗапрос по разному ведет себя в 1С и в oscript (обработка редиректов)

### ISSUE THREAD

**Issue by arkuznetsov** [EvilBeaver/OneScript#984]
**Опишите ошибку**
Делаю HTTPЗапрос на сайт 1С:
в oscript:
```bsl
HTTPЗапрос1 = Новый HTTPЗапрос;
HTTPЗапрос1.Заголовки.Вставить("User-Agent", "Chrome/80");
HTTPЗапрос1.Заголовки.Вставить("Connection", "keep-alive");
	
Соединение = Новый HTTPСоединение("https://releases.1c.ru", , , , , 20);
ОтветHTTP1 = Соединение.Получить(HTTPЗапрос1);
```
в 1С (отличается созданием соединения):
```bsl
HTTPЗапрос1 = Новый HTTPЗапрос;
HTTPЗапрос1.Заголовки.Вставить("User-Agent", "Chrome/80");
HTTPЗапрос1.Заголовки.Вставить("Connection", "keep-alive");
	
Соединение = Новый HTTPСоединение("releases.1c.ru", , , , , 20, Новый ЗащищенноеСоединениеOpenSSL);	
ОтветHTTP1 = Соединение.Получить(HTTPЗапрос1);
```

В oscript ОтветHTTP1.КодОтвета = 200
В 1С ОтветHTTP1.КодОтвета = 302

Т.е. получается что в oscript редиректы "проглатываются".

**Воспроизведение ошибки**
Выполнить указанный выше код в 1С и в oscript, сравнить результаты.

**Ожидаемое поведение**
Как в 1С.

**Окружение**
 - ОС: Windows 10
 - Версия: 1.3.140

**Дополнительная информация**

**Comment by nixel2007** [comment]
Из чейнджлога 1.1

В СоединениеHTTP всегда используется автоматический редирект. Реализовано свойство РазрешитьАвтоматическоеПеренаправление для управления редиректом (спасибо Vladimir Bondarevskiy

**Comment by arkuznetsov** [comment]
@nixel2007 Спасибо! Все ОК!
