### ISSUE TITLE
Нет приведения к булеву при коротком вычислении логических И/ИЛИ

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#986]
**Опишите ошибку**
В логических выражениях числа неявно приводятся к булеву типу.
При вычислении логических И/ИЛИ применяется короткая схема.
Если для получения значения логического выражения используется значение только первого операнда, результат не приводится к булеву типу.

**Воспроизведение ошибки**
```bsl
Л=1 ИЛИ 2;
Сообщить(""+ТипЗнч(Л)+":"+Л);
Л=0 И 1;
Сообщить(""+ТипЗнч(Л)+":"+Л);
```
Вывод:
_Число:1
Число:0_

**Ожидаемое поведение**
_Булево:Да
Булево:Нет_

**Дополнительная информация**
При завершении короткого вычисления на  втором или последующих значениях в цепочке И/ИЛИ результат правильный.
(подобное было в issue #20)

**Comment by EvilBeaver** [comment]
Доктор, а что вы делаете, чтобы выходить на такие кейсы? 😆
