### ISSUE TITLE
OneScriptDebug При возврате из метода пропадает отображение локальных переменных

### ISSUE THREAD

**Issue by petypen** [EvilBeaver/OneScript#987]
**Опишите ошибку**
Во время отладки при возврате из метода пропадает отображение локальных переменных и выдается сообщение об ошибке:
error while processing request variables (exception: Коммуникационный объект System.ServiceModel.Channels.ServiceChannel нельзя использовать для связи, так как он находится в состоянии Faulted

**Воспроизведение ошибки**
Шагать отладчиком без захода в методы
После отработки строки с методом пропадает отображение локальных переменных. 

**Ожидаемое поведение**
Во время отладки при возврате из метода не должно пропадать отображение локальных переменных

**Окружение**
 - ОС: Win10 64x
 - Версия:
Oscript 1.3.0
OneScriptDebug 0.5.0
VSCode 1.42.1

**Дополнительная информация**
Пример отладки с ошибкой https://youtu.be/dwKeKkpRaBU

**Comment by dvakor** [comment]
Накидал я значит примерчик, а он работает гад!

Файл test.os

> Функция ТестШага(Текст)
> 	Текст = 222;
> 	Возврат  1;
> КонецФункции
> 
> ПодключитьСценарий("D:\tmp\test2.os", "МойОбъект");
> Об = Новый МойОбъект();
> 
> Текст = "";
> 
> Тест1 = Об.ТестШага(Текст);
> Тест2 = ТестШага(Текст);
> 
> Сообщить("Я всё");


Файл test2.os

> Функция ТестШага(Текст) Экспорт
> 
> 	Текст = 2;
> 
> 	Возврат 123123;
> 
> КонецФункции

Этот код на машине где падает попробуй запустить, ломается или тоже все ок?)

Так же как минимум надо сделать, так чтобы не падал отладчик, а всё таки выводил эксепшен.

**Comment by petypen** [comment]
Я локализовал проблему.
Ошибка устойчиво появляется при выходе из секции Попытка - Исключение

Пример ошибки https://youtu.be/m6mruS0qMoU

Получается, выход из метода ни при чем. Просто именно в этом методе была секция Попытка - Исключение

**Comment by dvakor** [comment]
Блин, уже обрадовался, но нефига :(

Накидал похожий код, все "ОК", битность какая оскрипта кстати? 32?

![image](https://user-images.githubusercontent.com/4038422/76227427-e0b43180-6251-11ea-99be-4cc027bab0e7.png)

**Comment by petypen** [comment]
Oscript 1.3.0 64x, Windows 64x
Удалось сделать сценарий для повторения

Скрипт для тестирования:
```bsl
Функция ПрочитатьФайл()
	Перем бВыполненоБезОшибок, оТкест, сСхема, сПутьКФайлу;
	
	бВыполненоБезОшибок = Ложь;
	
	сСхема = "";
	сПутьКФайлу = "c:\\CommerceML2-10.xsd";
	
	оТкест = Новый ЧтениеТекста(сПутьКФайлу, КодировкаТекста.UTF8);
	Попытка
		сСхема = оТкест.Прочитать();
	Исключение
		оТкест.Закрыть();
		Возврат бВыполненоБезОшибок;
	КонецПопытки;
	
	оТкест.Закрыть();
	
	бВыполненоБезОшибок = Истина;
	Возврат бВыполненоБезОшибок;
КонецФункции

ПрочитатьФайл();
```
Файл CommerceML2-10.xsd, который считывается в память сохранен на Яндекс.Диске https://yadi.sk/d/qZPf_Cm3LRfdag Положите его в корень диска c:\

Похоже, что эта проблема как то связана с размером считываемого текстового файла. На пустом txt файле все штатно а на этой достаточно большой XML схеме стабильно ошибка

Демонстрация: https://youtu.be/SJCYGZ8Srq4

**Comment by dvakor** [comment]
так, я кажись допёр че там, `Прочитать()` же весь текст возвращает и его там многа...!
Вот у WCF буфер опять (уже увеличивал както) перегружается и ему плохеет. Надо ограничение вводить на большие объекты, либо вообще ничего не возращать либо только часть (если это текст например).

@EvilBeaver что думаешь? Я вот погуглил на тему размеров CLR объектов в рантайме, и чет нашел только такое

```
int GetObjectSize(object TestObject)
{
    BinaryFormatter bf = new BinaryFormatter();
    MemoryStream ms = new MemoryStream();
    byte[] Array;
    bf.Serialize(ms, TestObject);
    Array = ms.ToArray();
    return Array.Length;
}
```

Чет не нравится мне, но в целом проблему решит, если проверять размер объекта и сравнивать с какой - то константой и если больше то присылать ченить типа "Значение слишком многа кушает"

**Comment by EvilBeaver** [comment]
@ArchLord42RU просто не надо пытаться сериализовывать большие значения переменных. Обрубать и выводить строку типа "НеВлезло" что-то такое. Главное не обрубать канал WCF

**Comment by dvakor** [comment]
@petypen 
[Oscript.zip](https://github.com/EvilBeaver/OneScript/files/4332273/Oscript.zip)
[DebugServer.zip](https://github.com/EvilBeaver/OneScript/files/4332274/DebugServer.zip)

Попробуй на этой сборке запустить дебаг, я вот не смог прям отловить момент когда падает и откуда, но вывод представлений ограничил по размеру буфера, так что должно заработать.

архив oscript распаковать в любую папку, потом в найстройках дебаггера указать следующее

![image](https://user-images.githubusercontent.com/4038422/76674789-97633980-65e5-11ea-97c9-c9e967dab8f5.png)

DebugServer распаковать в 

 `%UserProfile%\.vscode\extensions\evilbeaver.oscript-debug-0.5.0\bin`

заменив там всё, предварительно копию сделать, ну или переустановить расширение потом, т.к. работать будет скорее всего с оскриптом только из сборки.

В общем хочу получить обратную связь, т.к. трабл может быть не в этом :)

**Comment by petypen** [comment]
@ArchLord42RU Дмитрий, по моему неплохо

![2020-03-14 15-50-58 Скриншот экрана](https://user-images.githubusercontent.com/6500075/76681412-da380800-660b-11ea-8554-4a058616082c.png)

![2020-03-14 15-51-42 Скриншот экрана](https://user-images.githubusercontent.com/6500075/76681416-ea4fe780-660b-11ea-9104-4b58255708a7.png)

**Comment by dvakor** [comment]
Отлично, тогда всё таки, верно было моё предположение :))

**Comment by petypen** [comment]
Спасибо вам, Дмитрий. Ждем релиза

**Comment by dvakor** [comment]
> Спасибо вам, Дмитрий. Ждем релиза

В целом, если очень надо, можно и эту сборку юзать, это сборка последней дев ветки + ПР не принятый мой :)

**Comment by nixel2007** [comment]
Должно быть исправлено в ночнике 1.4.0.134

**Comment by EvilBeaver** [comment]
@ArchLord42RU - а нам надо номер самого отладчика увеличить и попросить перескачать плагин для VSC?

**Comment by dvakor** [comment]
> @ArchLord42RU - а нам надо номер самого отладчика увеличить и попросить перескачать плагин для VSC?

угу, там DebugProtocol.dll обновился он юзатся и в планине и в самом ОСе

**Comment by EvilBeaver** [comment]
@ArchLord42RU бабахнешь версию 0.5.1 (или какая там по счету)?
