### ISSUE TITLE
Некорректное отображение ДереваЗначений при отладке

### ISSUE THREAD

**Issue by arkuznetsov** [EvilBeaver/OneScript#991]
При отладке в окне переменных, контрольных значений и пр. некорректно отображается дерево значений. 

![image](https://user-images.githubusercontent.com/10762909/76767750-21a8ca80-67ab-11ea-820c-04b2a41a756b.png)

**Воспроизведение ошибки**
1. Пример кода:
```bsl
Дерево = Новый ДеревоЗначений();

Дерево.Колонки.Добавить("Колонка1");
Дерево.Колонки.Добавить("Колонка2");
Дерево.Колонки.Добавить("Колонка3");

Для й = 1 По 5 Цикл
    НоваяСтрока = Дерево.Строки.Добавить();
    НоваяСтрока.Колонка1 = й;
    НоваяСтрока.Колонка2 = й;
    НоваяСтрока.Колонка3 = й;
    Для к = 10 По 15 Цикл
        НоваяСтрока1 = НоваяСтрока.Строки.Добавить();
        НоваяСтрока1.Колонка1 = к;
        НоваяСтрока1.Колонка2 = к;
        НоваяСтрока1.Колонка3 = к;
    КонецЦикла;
КонецЦикла;

Сообщить("!");
```
2. Поставить точку останова на "Сообщить".
3. Посмотреть содержимое переменной "Дерево".

**Ожидаемое поведение**
Корректное отображение содержимого дерева значений.

**Окружение**
 - ОС: Windows 10
 - Версия: 1.4.0.135

**Comment by arkuznetsov** [comment]
@ArchLord42RU Как обещал!

**Comment by dvakor** [comment]
> @ArchLord42RU Как обещал!

Спасибо, как раз ДЗ я чет не особо тестил, и судя по выхлопу очень зря :)
