### ISSUE TITLE
Метод Сообщить() не работает при загрузке скрипта из строки

### ISSUE THREAD

**Issue by perfolenta** [EvilBeaver/OneScript#996]
если скрипт загрузить из строки, то в нем не работает метод вывода в консоль Сообщить()
выдаёт ошибку:
Ошибка: {Модуль <string> / Ошибка в строке: 11 / Внешнее исключение (System.NullR
eferenceException): Ссылка на объект не указывает на экземпляр объекта.}
    Сообщить("Поле = "+Поле); //Сообщить НЕ работает!!!

т.е. скорее всего, что при загрузке скрипта из строки какой-то внутренний объект отвечающий за Сообщить не инициализируется.....

хотя, может это и не ошибка, а просто я чего-то инициализирующего не запустил...

пример на языке Перфолента:

ТекстСкрипта="Перем Поле;
|Процедура МетодПроцедура() Экспорт
|   Сообщить(""Поле = ""+Поле); //Сообщить НЕ работает!!!
|    Поле=Поле+"" изменено процедурой! "";
|КонецПроцедуры
|Поле=""НачальноеЗначениеПоля"";"

СкриптМашина = Новый HostedScriptEngine();
СкриптМашина.Initialize();
СкриптМашина.AttachAssembly(System.Reflection.Assembly.GetExecutingAssembly());

Скрипт = СкриптМашина.EngineInstance.AttachedScriptsFactory.LoadFromString(
            СкриптМашина.EngineInstance.GetCompilerService(), ТекстСкрипта);

Попытка
    НомерМетода = Скрипт.FindMethod("МетодПроцедура");
    Массив Аргументы[] тип IValue;
    Скрипт.CallAsProcedure(НомерМетода, Аргументы);
Исключение
КонецПопытки

**Comment by dvakor** [comment]
не инициализорован глобальный контекст, пример прикручивания оскрипта можно посмотреть в TestApp или в ОС.Вебе

**Comment by perfolenta** [comment]
"не инициализорован глобальный контекст" - думаю, что инициализирован, т.к. функции глобального контекста вызываются, например, ТекущаяДата() и т.д.
А, кажется понял, надо вызвать функцию SetGlobalEnvironment и передать ей класс хост, который будет Echo в консоль выводить.... тогда заработает...
Было бы не плохо, если бы в движке уже был бы встроенный хост по умолчанию, который бы в консоль все выводил...
