### ISSUE TITLE
Странное поведение отладчика при использовании COM

### ISSUE THREAD

**Issue by milkin-vl** [EvilBeaver/OneScript#999]
### Награда за решение
https://www.bountysource.com/issues/91292265-com

Заметил, что отладчик ведёт себя некорректно при отладке кода, использующего COM для подключения к базе 1С.

Например, при попытке отладить следующий код ...

    connector = Новый COMОбъект("V83.COMConnector");
    v8 = connector.Connect("File=""с:\base"";Usr="""";Pwd="""";");
    Выборка = v8.Справочники.Контрагенты.Выбрать();
    Пока Выборка.Следующий() Цикл
        Сообщить(Выборка.Наименование);
    КонецЦикла;

... нет возможности пошагово пройти его цикл. Точка останова срабатывает, но уже на следующем шаге отладки весь цикл прокручивается целиком.

**Comment by EvilBeaver** [comment]
Скорее всего это связано с падением сервера отладки. А в какой строке стоит точка останова?

**Comment by milkin-vl** [comment]
В данном случае ставлю точку останова на Сообщить.

На всякий случай записал видео процесса отладки (40 секунд):
[Video_2020-04-15_103030.zip](https://github.com/EvilBeaver/OneScript/files/4478441/Video_2020-04-15_103030.zip)

Там ещё такой прикол (на видео его видно):
- сработала точка останова на Сообщить
- я подвожу курсором мыши к Выборка.Наименование - всплывает одно значение
- подвожу курсором мыши к слову Выборка (в условии цикла) - всплывает Да
- подвожу курсором мыши снова к Выборка.Наименование - всплывает уже следующее значение из выборки

**Comment by EvilBeaver** [comment]
> я подвожу курсором мыши к Выборка.Наименование - всплывает одно значение
подвожу курсором мыши к слову Выборка (в условии цикла) - всплывает Да
подвожу курсором мыши снова к Выборка.Наименование - всплывает уже следующее значение из выборки

@ArchLord42RU забавный эффект у hover. Надо на досуге глянуть, почему в него ушла не переменная Выборка, а вызов метода.

@milkin-vl у вас и в 1С будет такое же работать, только не при наведении мышки, а при Shift+F9 на выражении `Выборка.Следующий()`. Это вызов с сайд-эффектом перемещения по выборке, тут уж так оно должно работать.

**Comment by milkin-vl** [comment]
Про hover понял, спасибо)
Главная проблема - это то, что да, действительно падает сервер отладки с ошибкой:
error while processing request 'variables' (exception: Метод или операция не реализована.)
при попытке пошагово выполнить приведённый мною пример.

**Comment by dvakor** [comment]
> > я подвожу курсором мыши к Выборка.Наименование - всплывает одно значение
> > подвожу курсором мыши к слову Выборка (в условии цикла) - всплывает Да
> > подвожу курсором мыши снова к Выборка.Наименование - всплывает уже следующее значение из выборки
> 
> @ArchLord42RU забавный эффект у hover. Надо на досуге глянуть, почему в него ушла не переменная Выборка, а вызов метода.
> 
> @milkin-vl у вас и в 1С будет такое же работать, только не при наведении мышки, а при Shift+F9 на выражении `Выборка.Следующий()`. Это вызов с сайд-эффектом перемещения по выборке, тут уж так оно должно работать.

@EvilBeaver там надо в vsc смотреть (или за это плагин отвечает какой то?)), он "сам" разбивает выражение на части (иногда не разбирает) и отправляет в адаптер

Другое дело, что вычислять подобные вещи не совсем корректно, т.к. можно много интересных вещей наловить если ховер будет все вычислять)

**Comment by EvilBeaver** [comment]
> Другое дело, что вычислять подобные вещи не совсем корректно, т.к. можно много интересных вещей наловить если ховер будет все вычислять)

Согласен. Но как формализовать алгоритм отделения хорошего ховера от плохого - не очень понимаю )

наверное, если подтянуть экспертов по IDE в лице @nixel2007 можно что-то будет прояснить. Например, может VSC можно заставить отдавать в hover только переменные (а что такое "переменная" подскажет BSL LS) или хз...

**Comment by EvilBeaver** [comment]
@milkin-vl 
> Главная проблема - это то, что да, действительно падает сервер отладки с ошибкой:
error while processing request 'variables' (exception: Метод или операция не реализована.)

где вы читаете этот текст исключения?

**Comment by nixel2007** [comment]
@EvilBeaver разве за отдаваемые данные  в ховер дебаггера отвечает не плагин для оскрипт дебага? Кажется 1сный плагин и бсл лс тут не причём.

**Comment by EvilBeaver** [comment]
Там еще хитрее, в VSC отдает 1скрипту некое выражение для вычисления ховера, 1скрипт вычисляет. А то, что именно попадает в 1скрипт и каким образом - я не знаю

**Comment by milkin-vl** [comment]
> @milkin-vl
> 
> > Главная проблема - это то, что да, действительно падает сервер отладки с ошибкой:
> > error while processing request 'variables' (exception: Метод или операция не реализована.)
> 
> где вы читаете этот текст исключения?
Вот здесь:
![Image-2020-04-18-10-02-55](https://user-images.githubusercontent.com/31714869/79622751-e0198f80-815b-11ea-919f-e1843fc63860.png)

**Comment by EvilBeaver** [comment]
@dmpas ... а может такое быть, что где-то в недрах механики COM падает NotImplementedException для метода AsString()? И именно его мы наблюдаем в тексте исключения?

**Comment by milkin-vl** [comment]
@EvilBeaver, а есть ли какой-то механизм для того, чтобы задонатить решение этой проблемы. Я понимаю, что никто никому ничего не должен - все исходники открыты, бери и ковыряй. Но вот конкретно в моём случае мне проще было бы заплатить человеку, который в теме и который решит этот вопрос гораздо быстрее меня, чем переключаться и въезжать самому. Я видел, что на некоторых тасках в трекере есть тег Награда, но не совсем понимаю как это работает.

**Comment by EvilBeaver** [comment]
Награда работает следующим образом: https://www.bountysource.com/

Размещаете там bounty на нужную сумму в привязке к этой задаче. Потом ссылку на награду добавляете в описание issue

**Comment by milkin-vl** [comment]
Добавил награду)

**Comment by dmpas** [comment]
> 
> 
> @dmpas ... а может такое быть, что где-то в недрах механики COM падает NotImplementedException для метода AsString()? И именно его мы наблюдаем в тексте исключения?

@EvilBeaver не исключено

**Comment by dvakor** [comment]
@dmpas @EvilBeaver Трабла не в представлении, а в GetPropCount() (он вызывается когда переменная проверяется на Indexed \ Structured), который кидает NotImplemented собственно.

Посмотрел код UnmanagedRCWComContext , там вообще никак нереализована работа с свойствами, только по факту.

Собственно есть 2 решения:
1) Быстрое - Добавить исключение на ком объекты и не пытаться выводить их свойства
2) Имхо верное - Написать получение свойств ком объекта, если он реализует IDispatch (вроде через него можно как то, тут не силён я :) ) и выводить их.

**Comment by EvilBeaver** [comment]
@ArchLord42RU делаем отображение свойств COM-объекта. Документация о том, как это можно сделать я поищу инфу и отпишусь здесь

**Comment by Mr-Rm** [comment]
Если игнорировать .NET Standard (как сделано в `ПолучитьCOMОбъект`), то надо *восстановить* методы `GetType` в DispatchUtility.cs

**Comment by EvilBeaver** [comment]
@ArchLord42RU есть шансы что ты починишь?

**Comment by dvakor** [comment]
> @ArchLord42RU есть шансы что ты починишь?

Угу, только судя по твоему коммиту "немножечко помог" это возможно 70% работы. Если он работает, то нужно просто реализовать методы во враппере(ах) кома. Я кстати не проверил работает ли отладка с managed враппером

UPD: ты ж уже это сделал :) По идее оно работать должно уже

**Comment by EvilBeaver** [comment]
Вот и я не проверял. Можешь проверить и добить что понадобится?

**Comment by EvilBeaver** [comment]
Посмотри также комментарий @Mr-Rm насчет CustomMarshallers. Их можно выпилить похоже.

**Comment by dvakor** [comment]
Окей)

**Comment by EvilBeaver** [comment]
@milkin-vl попробуйте на свежей сборке 1.4, предварительно обновив пакет отладчика вот отсюда: https://oscript.io/downloads/night-build/x64/oscript-debug-0.6.0.vsix

**Comment by milkin-vl** [comment]
@EvilBeaver проверил - всё хорошо, больше не падает.
Спасибо всем, кто участвовал в решении.

**Comment by EvilBeaver** [comment]
@milkin-vl зайдите на страничку награды или в почту, не появилось ли там кнопки подтвердить, выплатить и т.п?

**Comment by milkin-vl** [comment]
@EvilBeaver не появилось нигде.

Я почитал [FAQ](https://github.com/bountysource/core/wiki/Frequently-Asked-Questions#what-happens-after-i-post-a-bounty) - там сказано, что разработчик, который закрыл задачу должен после этого как-то заявить об этом на bountysource. И вот только тогда я получу уведомление.

**Comment by EvilBeaver** [comment]
Он заявил. Подождем.

**Comment by dvakor** [comment]
> Он заявил. Подождем.

У них сайт вообще лежит уже с утра, я проверить хотел кидал \ не кидал, но обломился

**Comment by EvilBeaver** [comment]
Короче, господа, я надеюсь, что вы увидели ники друг-друга и сами разрулите эту ситуацию :)
Если награда не найдет автора, я буду чувствовать себя некомфортно, надеюсь на вас.

**Comment by milkin-vl** [comment]
@EvilBeaver @ArchLord42RU конечно, разрулим, потому что эти 65$ - я их не могу отозвать назад из награды (чтобы перевести напрямую), то есть их или заберёт решивший или они останутся у bountysource, чего конечно бы не хотелось.

Ещё странно, что я раньше отображался в backers, а теперь там пусто. Я сейчас напишу в поддержку на support@bountysource.com и буду контролировать ситуацию до момента выплаты.

**Comment by milkin-vl** [comment]
@ArchLord42RU bountysource потихонечку начинает оживать. В нём, наконец, статус задачи сменился на Closed, я вновь вернулся в Backers. Прошу вас проверить - не появилась ли у вас там сейчас возможность запросить вознаграждение.

**Comment by dvakor** [comment]
@milkin-vl ну чёт пока у меня не грузится сайт, переодически проверяю когда вспоминаю, в 99% "белый экран" и loading в углу :(
Был один раз когда грузанулся, но там мне показало что ишуза закрыта и тип всё, либо просто кнопки не прогрузились, хз кароч.

**Comment by dvakor** [comment]
@milkin-vl Заработало, там надо было решение еще выставить отдельно, в общем вроде как ОК

**Comment by milkin-vl** [comment]
@ArchLord42RU Да, мне пришло уведомление. Там сказано, что награда уйдёт заявившему спустя 2 недели автоматически или сразу, если авторы задачи её одобрят. Я, конечно, попробовал её одобрить и даже каким-то чудом один раз добрался до кнопки Accept, и даже нажал  на неё... но дальше всё. Сайт снова умер и работать с ним не получается. Но я продолжу попытки на следующей неделе. Это прямо кошмар какой-то, а не bountysource.

**Comment by milkin-vl** [comment]
@ArchLord42RU в общем кнопка Accept у них тупо не работает) Я 4 дня подряд её нажимаю. Ждём до 6 июня - тогда выплата должна будет произойти без подтверждения с моей стороны.

**Comment by dvakor** [comment]
@milkin-vl окей :)

**Comment by milkin-vl** [comment]
@ArchLord42RU Ура, я только что смог подтвердить решение. Они похоже починились наконец-то.

**Comment by dvakor** [comment]
> @ArchLord42RU Ура, я только что смог подтвердить решение. Они похоже починились наконец-то.

Мне даже уведомление пришло и сайт открылся и смог привязать пейпал оО. Наверное да починились :)

**Comment by milkin-vl** [comment]
@ArchLord42RU всё ок? вы смогли получить награду?

**Comment by dvakor** [comment]
> @ArchLord42RU всё ок? вы смогли получить награду?

Да, все ок, спасбо)
